### ISSUE TITLE
[Feature Request]: 用户自定义影片的下载路径、 QB 分类以及媒体库路径，类似 nastools

### ISSUE THREAD

**Issue by 120318** [jxxghp/MoviePilot#1007]
### 当前程序版本

v1.3.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

当前的逻辑是比较固定，对于 QB 下载来说，如果不做二级分类，那么是无法为 QB 内的种子添加分类的，而且如果不做二级分类，转移路径也只能固定一个文件夹。

举例来说，当我下载一个电影，我的诉求是，指定 QB 分类为 TTT，设置保存路径为 /downloads/TTT，下载完成后我电影自动转移到 /library/TTT。

这在 nastools 是很容易做到的，我只要新增一个下载器配置就好了。

但是在 moviepilot 中，我首先无法指定 QB 分类为 Movie，我如果想指定分类，我只能在 category.yml 里 这样写：
```
movie:
  Movie:
```

这是当前指定 QB 分类的唯一方式，但是这就会导致电影媒体库也会被 强制赋予一个二级分类文件夹，会在我指定的 DOWNLOAD_MOVIE_PATH 路径后面加上 Movie。比如 /library/movie/Movie。这非常不灵活。

而且我发现，在手动转移的时候，无论我怎么处理目的路径，它总是只能给我转移到配置文件中写的路径。电影到电影路径，电视剧到电视剧路径。

综上所述，希望能够增加一个下载器自定义配置。增强使用自由度。

**Comment by 120318** [comment]
？

**Comment by sjtuross** [comment]
+1

当选择开启QB自动管理模式，其实只要设置分类就行了，完全不需要设置目录了。这样逻辑也简洁。
