### ISSUE TITLE
能否可以考虑把原来NT的文件重命名中的{en_title}参数给加回来

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/MoviePilot#1008]
### 当前程序版本

v1.3.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否可以考虑把原来NT的文件重命名中的{en_title}也就是英文名称占位符给加回来，因为一直喜欢都是中文加英文的命名方式

**Comment by cng10001** [comment]
之前提过几个了，作者还没回复

**Comment by Mikcoono1** [comment]
我说我怎么加 en_title 不管用呢

**Comment by LGuangming** [comment]
> 我说我怎么加 en_title 不管用呢

哈哈，我还是觉得EN title比original title适用一点。主要是不同国家资源original title看着有点乱

**Comment by LGuangming** [comment]
> 之前提过几个了，作者还没回复

作者已经添加了一个en_name了可以去试试

**Comment by LGuangming** [comment]
> 我说我怎么加 en_title 不管用呢

作者已经添加了一个en_name了可以去试试
