### ISSUE TITLE
[Feature Request]: 站点数据统计和站点消息分开配置

### ISSUE THREAD

**Issue by wq2020wdm** [jxxghp/MoviePilot#1009]
### 当前程序版本

1.3.7

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

目前站点消息和站点数据统计都是在数据统计中，共用一个配置，能否在这个插件中两个可以分开配置，站点消息一天要获取几次，但数据统计感觉一天一次够了

**Comment by kingcard1131** [comment]
是的，希望支持这个特性，目前是站点数据统计一次才能获取站点消息

**Comment by kingcard1131** [comment]
现在可以用bark单独设置站点消息推送了
