### ISSUE TITLE
[Feature Request]: 微信搜索时选择搜索第几季

### ISSUE THREAD

**Issue by wq2020wdm** [jxxghp/MoviePilot#1010]
### 当前程序版本

1.3.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前为了方便分享给家人朋友，设置了他们自动下载，这样有个问题，比如我搜索花儿与少年，这个总共5季，我选择花儿与少年后，会列出缺几季，然后便开始搜索下载，没有选择搜索第几季选项，自动下载就会把缺失的都下载，所以能否添加一个选择季数的功能

**Comment by jxxghp** [comment]
@wq2020wdm 输入花儿与少年第五季

**Comment by wq2020wdm** [comment]
已解决
