### ISSUE TITLE
[错误报告]: 多选整理设定偏移集数无效

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#1014]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.3.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

如视频操作，我选择5，6两集进行转移，设置便宜集数为-1，设想转移后应该是变成4，5，但实际情况转移完成还是第五、第六集，并未产生偏移效果
https://github.com/jxxghp/MoviePilot/assets/34505611/7573b65f-3ce9-4c14-9e38-cf12aba1606c

**Comment by yellowstrong** [comment]
<img width="1038" alt="iShot_2023-10-29_14 27 04" src="https://github.com/jxxghp/MoviePilot/assets/34505611/82882e97-0bd8-484c-a670-df191afddd2c">
实测针对单集只有这样填写偏移集数才能成功

**Comment by Shurelol** [comment]
@yellowstrong 只填集数偏移

**Comment by AboutCXJ** [comment]
不要指定集数，只偏移
