### ISSUE TITLE
[错误报告]: 同步删除插件，删除媒体失败

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#1015]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

**同步删除插件，删除媒体失败，提示未找到媒体，而实际上历史记录是存在的**

**扫描方式：日志**

![image](https://github.com/jxxghp/MoviePilot/assets/23021469/b2055108-ad40-46bb-9468-9631865d0ffc)

### 发生问题时系统日志和配置文件

```bash
INFO	17:30:01,413	mediasyncdel    正在同步删除 电影 回应我
INFO	17:30:01,413	mediasyncdel    未获取到 电影 回应我 转移记录
```

**Comment by thsrite** [comment]
@mjsoftking 程序没问题，路径映射填错了，自己排查排查。
同一个视频文件在emby中和mp中路径可能不同，如果不同就按照提示正确填写此项

**Comment by mjsoftking** [comment]
@thsrite 确实是路径不对，就是提示有点不明确，如果能连同tr的种子一起删除就好了

**Comment by thsrite** [comment]
@mjsoftking 提示已经加了，更新dev。
如果通过mp转种辅种的tr种，也可删除

**Comment by mjsoftking** [comment]
@thsrite 感谢大佬，目前配合删除插件可以做到，就是TR的数据检测到数据丢失比较久^o^
