### ISSUE TITLE
[Feature Request]: 希望能像nastools一样额外添加动漫分类

### ISSUE THREAD

**Issue by 1103958779** [jxxghp/MoviePilot#1017]
### 当前程序版本

v1.3.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望能像nastools一样额外添加动漫分类，目前动漫分类到tv里面，希望能单独设置列出一个分类，这个在nastools有实现，希望能够改进，谢谢
tv:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  # 如果有配置动漫独立目录，则实际上不会使用到tv下的动漫二级分类
  动画片:
    # 匹配 genre_ids 内容类型，16是动漫
    genre_ids: '16'
  纪录片:
     # 匹配 genre_ids 内容类型，99是纪录片
    genre_ids: '99'
  国产剧:
    # 匹配 origin_country 国家，CN是中国大陆，TW是中国台湾，HK是中国香港
    origin_country: 'CN,TW,HK'
  欧美剧:
    # 匹配 origin_country 国家，主要欧美国家列表
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日韩剧:
    # 匹配 origin_country 国家，主要亚洲国家列表
    origin_country: 'JP,KP,KR,TH,IN,SG'
  # 未匹配以上分类，则命名为未分类
  未分类:

# 配置动漫的分类策略， 配置为空或者不配置该项则不启用动漫分类
anime:
  # 如果你的anime_path动漫目录已经直接设置到了动漫子目录，则这个分类可以取消
  日漫:
    origin_country: 'JP'
  国漫:
    origin_country: 'CN'
  美漫:
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'

**Comment by Shurelol** [comment]
@1103958779 配置里不是有动漫媒体库路径么，填哪在哪

**Comment by 1103958779** [comment]
想要再细分日漫，国漫和美漫这种

**Comment by 1103958779** [comment]
> @1103958779 配置里不是有动漫媒体库路径么，填哪在哪

想要再细分日漫，国漫和美漫这种
