### ISSUE TITLE
[错误报告]: 手动指定tmdb id显示未匹配到媒体信息

### ISSUE THREAD

**Issue by huojinming-1997** [jxxghp/MoviePilot#1023]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

发现问题的只是这部电影https://www.themoviedb.org/movie/184315-hercules，因自动识别错误之后改手动识别但还是显示未匹配到媒体信息，后来就怀疑是资源问题从wiki组的资源换到了MTeam组的但问题依旧，奇怪的就是其他电影都没问题就算自动错误也能手动更正

### 发生问题时系统日志和配置文件

```bash
获取RSS链接失败：https://iptorrents.com/
INFO	19:07:15,499	
cookiecloud.py
站点【憨憨】连通性正常，不同步CookieCloud数据
INFO	19:07:16,505	
cookiecloud.py
站点【阿童木】连通性正常，不同步CookieCloud数据
INFO	19:07:18,833	
cookiecloud.py
站点【我堡】连通性正常，不同步CookieCloud数据
INFO	19:07:18,863	
cookiecloud.py
CookieCloud同步成功：更新了1个站点，新增了0个站点
INFO	19:10:41,471	
transfer.py
开始删除文件以及空目录：/media/hlink/movie/হারকিউলিস (2014)/হারকিউলিস (2014) - 1080p MTeam.mkv ...
WARNING	19:10:41,488	
transfer.py
文件 /media/hlink/movie/হারকিউলিস (2014)/হারকিউলিস (2014) - 1080p MTeam.mkv 已删除
WARNING	19:10:41,494	
transfer.py
目录 /media/hlink/movie/হারকিউলিস (2014) 已删除
INFO	19:10:41,494	
transfer.py
手动转移：/media/movie/Hercules.2014.EXTENDED.BluRay.1080p.x264.DTS-HD.MA5.1.2Audio-MTeam/Hercules.2014.EXTENDED.BluRay.1080p.x264.DTS-HD.MA5.1.2Audio-MTeam.mkv ...
INFO	19:10:41,494	
tmdbapi.py
正在查询TMDB电影：184315 ...
INFO	19:10:41,495	
themoviedb
184315 未匹配到媒体信息
```

**Comment by Shurelol** [comment]
@huojinming-1997 清理缓存

**Comment by huojinming-1997** [comment]
> @huojinming-1997清理服务器

谢谢大佬指导已经能正常转移啦，因为不知如何清空缓存也没找到相关按钮就把temp整个文件夹删除了

**Comment by Shurelol** [comment]
@huojinming-1997 Tg交互消息里有

**Comment by huojinming-1997** [comment]
> @huojinming-1997 Tg交互消息里有

好的谢谢找到了
