### ISSUE TITLE
删除的站点，在订阅中残留

### ISSUE THREAD

**Issue by AboutCXJ** [jxxghp/MoviePilot#1026]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![IMG_1692](https://github.com/jxxghp/MoviePilot/assets/19811825/3287c593-c3ce-4821-9421-7999eea306ec)

**Comment by cng10001** [comment]
![残留](https://github.com/jxxghp/MoviePilot/assets/115156545/45d3cd35-5545-4e28-971c-98f14659ee09)
还是有残留哎
