### ISSUE TITLE
[Feature Request]: 站点能不能增加对象站的支持？

### ISSUE THREAD

**Issue by qa19971109** [jxxghp/MoviePilot#1037]
### 当前程序版本

1.3.8

### 运行环境

Docker

### 功能改进类型

其他

### 功能改进

希望大佬站点管理增加对象站的支持，谢谢大佬

**Comment by zhattyt** [comment]
为了尽早为站友适配，象站可以提供账号和接口信息。

**Comment by jxxghp** [comment]
@zhattyt 可以的，请tg联系 jxxghp

**Comment by qa19971109** [comment]
感谢大佬
