### ISSUE TITLE
监控目录不能监控大写.MP4文件  只能监控.mp4 也就是小写

### ISSUE THREAD

**Issue by jinshenganyuci** [jxxghp/MoviePilot#1043]
### 当前程序版本

1.3.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

监控目录不能监控大写.MP4文件  只能监控.mp4 也就是小写
希望增加后缀大写.MP4    的监控

**Comment by jxxghp** [comment]
应该也支持的，发日志

**Comment by 757321061** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/49135603/568fc5a3-b403-4c6d-b6ca-6861e98a3cb9)
只能识别第一集  因为第一集是.mp4

后面的全是.MP4
![image](https://github.com/jxxghp/MoviePilot/assets/49135603/7635f4e1-eba1-4e00-b541-f0b95a0d6e9f)
![image](https://github.com/jxxghp/MoviePilot/assets/49135603/a65d9011-d1b8-4ac9-8579-29e5e4e9060d)
