### ISSUE TITLE
插件多次运行

### ISSUE THREAD

**Issue by thsrite** [jxxghp/MoviePilot#1048]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.9-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

INFO:    command.py - 处理事件：webhook.message - [<function MediaServerMsg.send at 0x14bb6cf57f60>, <function MediaServerMsg.send at 0x14bb6cfc85e0>, <function MediaSyncDel.sync_del_by_webhook at 0x14bb6cfc9c60>, <function MediaSyncDel.sync_del_by_plugin at 0x14bb6cfc9d00>, <function MediaSyncDel.sync_del_by_webhook at 0x14bb6cfcaac0>, <function MediaSyncDel.sync_del_by_plugin at 0x14bb6cfcab60>, <function SpeedLimiter.check_playing_sessions at 0x14bb6ce3d620>, <function SpeedLimiter.check_playing_sessions at 0x14bb6ce3de40>]

日志是emby发送的webhook消息，可看出插件多次运行

删除镜像重装的，没有安装或更新三方插件

**Comment by thsrite** [comment]
webhook到MediaSyncDel插件是两次
MediaSyncDel到Clouddiskdel插件变成4次

INFO:    command.py - 处理事件：networkdisk.del - [<function CloudDiskDel.clouddisk_del at 0x14bb6d0f63e0>, <function CloudDiskDel.clouddisk_del at 0x14bb6d0f6980>]
INFO:    command.py - 处理事件：networkdisk.del - [<function CloudDiskDel.clouddisk_del at 0x14bb6d0f63e0>, <function CloudDiskDel.clouddisk_del at 0x14bb6d0f6980>]
INFO:    clouddiskdel - 获取到云盘删除请求 {'media_path': '/data/aliyun/movies/国产电影/香港恐怖电影合集【200多部】【560G】/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios.strm', 'media_name': '败家仔', 'tmdb_id': '41380', 'media_type': 'Movie', 'season_num': None, 'episode_num': None}
INFO:    clouddiskdel - 获取到云盘删除请求 {'media_path': '/data/aliyun/movies/国产电影/香港恐怖电影合集【200多部】【560G】/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios.strm', 'media_name': '败家仔', 'tmdb_id': '41380', 'media_type': 'Movie', 'season_num': None, 'episode_num': None}
INFO:    clouddiskdel - 获取到云盘删除请求 {'media_path': '/data/aliyun/movies/国产电影/香港恐怖电影合集【200多部】【560G】/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios.strm', 'media_name': '败家仔', 'tmdb_id': '41380', 'media_type': 'Movie', 'season_num': None, 'episode_num': None}
INFO:    clouddiskdel - 获取到云盘删除请求 {'media_path': '/data/aliyun/movies/国产电影/香港恐怖电影合集【200多部】【560G】/败家仔.Prodigal.Son.1981.BluRay.1080p.x264.2Audios/败家仔.Pro

貌似再安装插件或者更新插件后，插件重复会继续叠加

**Comment by thsrite** [comment]
#1047

**Comment by 757321061** [comment]
解决了吗 还是等更新？
