### ISSUE TITLE
[错误报告]:豆瓣搜索无法生效，TMDB中文搜索时好时坏，网络连接正常

### ISSUE THREAD

**Issue by chiao666** [jxxghp/MoviePilot#1049]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.9-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

TMDB下搜索铃芽之旅，搜索不出结果，搜索其他一些中文正常，在这个843问题中有人碰到了一样的情况，我在clash中添加了tmdb相关的两个关键词，网络一直联通，但是搜索有时失败
  #843
![chi_20231103102808](https://github.com/jxxghp/MoviePilot/assets/46027934/cffbd0e5-6ae4-4b95-b2dc-c70d5fbc401a)

还是用豆瓣搜索稳定点也行，但是似乎切换为豆瓣无法生效，依旧显示搜索不到TMDB信息
![chi_20231103102124](https://github.com/jxxghp/MoviePilot/assets/46027934/fe217911-7df6-43e9-b849-88d803f3d6c7)

### 发生问题时系统日志和配置文件

```bash
日志是一切正常的哈，没有err提示，也没有843问题中说到的
init.py | 运行模块 search_medias 出错：TheMovieDbModule - 'NoneType' object has no attribute 'headers'
直接显示一个
02:16:35 INFO:media.py-始索媒体信息：铃芽之旅 stdout
02:16:35 INFO:cookiecloud.py-站点【自由农场】连通性正常，不同步CookieCloud数据 stdout
02:16:36 WARNING:media.py-铃芽之旅没有找到对应的媒体信息！stdout
02:16:36 INFO：58.240.81.70:0- "GET/api/v1/media/search？page=1&title=%E9%93%83%E8%8A%BD%E4%B9%8B%E…
02:16:37 INFO: cookiecloud.py-站点【红叶PT】连通性正常，不同步CookieCloud数据 stdout
02:16:40 INFO:media.py-始索媒体信息：起风了 stdout
02:16:41 WARNING:media.py-起风了没有找到对应的媒体信息！stdout
02:16:41 INFO：58.240.81.70:0- "GET /api/v1/media/search？page=1&title=%E8%B5%B7%E9%A3%8E%E4%BA%86 HT…
02:16:45 INFO:cookiecloud.py-站点【学校】连通性正常，不同步CookieCloud数据
```

**Comment by chiao666** [comment]
或者能否添加一个直接搜索站点的功能，必须先搜索到tmdb相关影片信息才能去搜索资源，有时候确实会有一些问题

**Comment by jxxghp** [comment]
这个错就是网络问题
