### ISSUE TITLE
[错误报告]: 豆瓣榜单订阅插件，自带的订阅地址查询不到订阅内容；能否在插件增加使用代理开关（因为rsshub.app无法访问）

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1050]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.3.9-2，后端版本：v1.3.9-2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

豆瓣榜单订阅插件：
![image](https://github.com/jxxghp/MoviePilot/assets/53737003/d25b198a-b4e5-41fe-9390-889221a946d6)

选择了热门电影，热门电视剧和一周口碑电影榜，上面是运行日志，查询不到榜单内容
![image](https://github.com/jxxghp/MoviePilot/assets/53737003/64f507d1-62e8-4b11-b963-c1d45a691db6)

**Comment by honue** [comment]
rsshub.app 在境内被墙了检查自身网络，或使用镜像站。

**Comment by kingcard1131** [comment]
如何让这个rsshub使用代理呢？

**Comment by honue** [comment]
> 如何让这个rsshub使用代理呢？

rsshub.feeder.xyz

**Comment by kingcard1131** [comment]
NAS docker运行环境要怎么操作？

**Comment by kingcard1131** [comment]
我在YAML配置文件里添加了代理，能否让rsshub走代理呢，谢谢

**Comment by jxxghp** [comment]
更新插件到v1.2
