### ISSUE TITLE
[错误报告]: 搜索资源选择“IMDB链接 ”有问题

### ISSUE THREAD

**Issue by BianTan** [jxxghp/MoviePilot#1051]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.9-2

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在搜索内页 //ip:port/media?mediaid=tmdb:xxxxxx&type=xxxx剧 的“搜索资源”按钮选择“IMDB链接”，然后搜索不出资源，只有选择标题搜索才可以。
![photo_2023-11-03_17-13-43](https://github.com/jxxghp/MoviePilot/assets/13924889/fc295a65-5cbc-4c76-9b3a-d1f9f4c597c3)

比如《空中监狱》这部电影，我直接在站点内搜索不论是名字还是IMDB都可以搜索出来，在MP里面就不行

**Comment by BianTan** [comment]
我看了下日志里面使用的搜索链接，直接浏览器访问链接可以发现用的还是标题搜索。
url query 参数 search_area=0，我将这个参数修改为4才是出来的才是IMDB搜索，然后也有搜索结果

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/7f30f327-1b40-4bd9-9aa4-1f4b0d61a62e)

奇怪我跟你好像有点不一样，我日志里链接默认是search_area=4
**_search_mode=0&search_area=4&page=0&notnewword=1&search=tt0118880&_**

**Comment by BianTan** [comment]
> ![image](https://user-images.githubusercontent.com/115156545/280300472-7f30f327-1b40-4bd9-9aa4-1f4b0d61a62e.png)
> 
> 奇怪我跟你好像有点不一样，我日志里链接默认是search_area=4 **_search_mode=0
&search_area=4&page=0&notnewword=1&search=tt0118880&_**

咦？
![屏幕截图 2023-11-04 113609](https://github.com/jxxghp/MoviePilot/assets/13924889/53582fa5-3bf7-4b4f-a58c-5521d41583c1)
![屏幕截图 2023-11-04 113514](https://github.com/jxxghp/MoviePilot/assets/13924889/f22b8cab-910e-4f66-9adf-2a141023d2e4)

**Comment by zww94** [comment]
跟楼主一样 搜索框 搜索 就是404 没有资源
