### ISSUE TITLE
[Feature Request]: 自动删种插件qb状态添加一个说明

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#1056]
### 当前程序版本

 v1.3.9-2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

添加一个说明有哪些关键词对应哪些状态
![image](https://github.com/jxxghp/MoviePilot/assets/67105838/c77a2e40-7599-4cae-8af5-6c1abcf1e0fa)

**Comment by gravitation-ch** [comment]
这个地方我对应填入QB的任务状态，但是不生效，不知道咋回事。

**Comment by zero617** [comment]
> 这个地方我对应填入QB的任务状态，但是不生效，不知道咋回事。

我都不记得QB的任务状态那几个关键词是什么了-_-

**Comment by gravitation-ch** [comment]
> > 这个地方我对应填入QB的任务状态，但是不生效，不知道咋回事。
> 
> 我都不记得QB的任务状态那几个关键词是什么了-_-

![IMG_20231112_073913](https://github.com/jxxghp/MoviePilot/assets/129346715/fdd8151f-a74b-4956-bcf1-ef896b62db16)
![IMG_20231112_073735](https://github.com/jxxghp/MoviePilot/assets/129346715/f23f9942-1038-4618-9972-e53c6e4cfb44)

**Comment by jxxghp** [comment]
更新插件
