### ISSUE TITLE
[错误报告]: 入库完成以后，并没有通知plex 刷新库

### ISSUE THREAD

**Issue by hhahh2011** [jxxghp/MoviePilot#1058]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.9-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

mp转移入库完成以后，并没有通知plex 刷新库
plex token 正常（可以正常同步媒体库数据）

**Comment by ajchen1314** [comment]
你插件设置好了吗？没设置肯定不会入库通知啊
