### ISSUE TITLE
建议增加支持2个下载器或单独对保种的下载器限速。谢谢！

### ISSUE THREAD

**Issue by zraxx** [jxxghp/MoviePilot#106]
### 当前程序版本

最新版

### 功能改进

功能增加：下载器为qb，保种为tr，播放时，想对tr限速，建议增加支持2个下载器或单独对保种的tr限速。谢谢！

**Comment by jxxghp** [comment]
现在界面上就可以多选

**Comment by zraxx** [comment]
> 现在界面上就可以多选

下载默认qb，限速界面有可选qb或tr，在容器的环境变量也能增加tr的设置？
![Screenshot_2023-08-13-20-54-11-940_com.android.browser.png](https://github.com/jxxghp/MoviePilot/assets/25578054/466ec8bc-05c5-4204-b61b-cff01f90656f)

![Screenshot_2023-08-13-20-55-10-969_com.android.browser.png](https://github.com/jxxghp/MoviePilot/assets/25578054/73be8d20-3d80-4181-9c8f-bc9bd325892d)

**Comment by jxxghp** [comment]
设置上TR下载器的参数即可，DOWNLOADER的值不用增加TR

**Comment by zraxx** [comment]
> 设置上TR下载器的参数即可，DOWNLOADER的值不用增加TR

ok，我试试，谢谢！
