### ISSUE TITLE
[错误报告]: 家园 更新失败: 未找到用户名输入框

### ISSUE THREAD

**Issue by Nothend** [jxxghp/MoviePilot#1068]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

hdhome.org ，进行站点测试提示【家园 连通性测试失败:状态码: 403!】，进行手动更新提示【家园 更新失败: 未找到用户名输入框】
1、账户密码未改过，之前站点政策，从1.3.9-2到1.4.0出现这个情况
2、mp重启过。
3、站点重置过。
4、浏览器网页端正常打开登录
5、手动添加站点后，依然连通性测试失败:状态码: 403!

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-11-06 13:04:20,998 - cookiecloud.py - 开始同步CookieCloud站点 ...
【WARNING】2023-11-06 13:04:21,821 - cookiecloud.py - 站点 家园 连接状态码：403，无法添加站点
【INFO】2023-11-06 13:04:24,351 - cookiecloud.py - 新增站点 天空 ...
【INFO】2023-11-06 13:04:24,611 - cookiecloud.py - CookieCloud同步成功：更新了0个站点，新增了1个站点，1个站点添加失败，下次同步时将重试，也可以手动添加
【INFO】2023-11-06 13:04:24,612 - command.py - 处理事件：site.deleted - [<function AutoSignIn.site_deleted at 0x7fc508132520>, <function SiteStatistic.site_deleted at 0x7fc5085ac680>]
【INFO】2023-11-06 13:08:41,051 - cookiecloud.py - 开始同步CookieCloud站点 ...
【WARNING】2023-11-06 13:08:41,513 - cookiecloud.py - 站点 家园 连接状态码：403，无法添加站点
【INFO】2023-11-06 13:08:43,980 - cookiecloud.py - 新增站点 天空 ...
【INFO】2023-11-06 13:08:44,221 - cookiecloud.py - CookieCloud同步成功：更新了0个站点，新增了1个站点，1个站点添加失败，下次同步时将重试，也可以手动添加
```

**Comment by jxxghp** [comment]
403是过不了cf
