### ISSUE TITLE
[错误报告]: 服务启动的2个问题

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1069]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

## 问题1:
> 启动服务就会提示`自动更新`配置附近代码错误，但是检查我的环境变量中配置了自动更新

<img width="1422" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/522c68c5-a459-40ae-8afa-c47d8446c925">
<img width="1132" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/6870ff89-4707-475a-8e38-457278c95c00">

## 问题2:
> 无法正常同步`CookieCloud`。使用docker compose部署的CookieCloud服务，已经在chrome浏览器中正确配置并使用，但moviepilot启动依然提示无法同步

<img width="711" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/288cb3d5-060d-4752-89f3-ba57ac3816bf">
<img width="855" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/b86407c3-0e2a-464a-b8f0-876ce6131c64">

### 发生问题时系统日志和配置文件

> 敏感信息已隐藏

* docker-compose.yaml

```yaml
version: "3"

networks:
  moviepilot:
    external: false

services:
  moviepilot:
    image: jxxghp/moviepilot:1.4.0
    container_name: moviepilot
    restart: always
    environment:
      - UID=1026
      - GID=100
      - GIDLIST=100,101
      - UMASK=022
      - TZ=Asia/Shanghai
      - MOVIEPILOT_AUTO_UPDATE=true
      - NGINX_PORT=3000
      - PORT=3001
      - SUPERUSER=username
      - SUPERUSER_PASSWORD=password
      - API_TOKEN=bcyakvdcyhvbu
      - TMDB_API_DOMAIN=api.tmdb.org
      - TMDB_IMAGE_DOMAIN=image.tmdb.org
      - WALLPAPER=bing
      - REFRESH_MEDIASERVER=true
      - SCRAP_METADATA=true
      - SCRAP_FOLLOW_TMDB=true
      - TORRENT_TAG=MOVIEPILOT
      - TRANSFER_TYPE=copy
      - DOWNLOADER_MONITOR=true
      - AUTH_SITE=iyuu
      - IYUU_SIGN=IYUUSING
    volumes:
      - /volume1/docker/moviepilot/config:/config
      - /volume1/docker/moviepilot/data:/moviepilot
      - /volume2/video:/volume2/video
      - /volume2/download/bittorrent:/volume2/download/bittorrent
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3005:3000/TCP
      - 3009:3001/TCP
    network_mode: "bridge"
    networks:
      - moviepilot
```

* app.env

```yaml
####################################
#   站点                           #
####################################
# 【*】CookieCloud服务器地址，默认为公共服务器
COOKIECLOUD_HOST=https://redirect.your.domain:1234
# 【*】CookieCloud用户KEY
COOKIECLOUD_KEY=key
# 【*】CookieCloud端对端加密密码
COOKIECLOUD_PASSWORD=password
# 【*】CookieCloud同步间隔（分钟）
COOKIECLOUD_INTERVAL=1440
# OCR服务器地址
OCR_HOST=https://movie-pilot.org
# 【*】CookieCloud对应的浏览器UA
USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57
```

<table>
<tr><th>date</th><th>stream</th><th>content</th></tr>
<tr><td>2023/11/06&nbsp;14:25:48</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;【MediaServer】媒体库数据同步完成，同步数量：423
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:48</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;emby&nbsp;媒体库&nbsp;综艺&amp;纪录片&nbsp;同步完成，共同步数量：6
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:45</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;正在同步&nbsp;emby&nbsp;媒体库&nbsp;综艺&amp;纪录片&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:45</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;emby&nbsp;媒体库&nbsp;动漫&nbsp;同步完成，共同步数量：23
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:31</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;正在同步&nbsp;emby&nbsp;媒体库&nbsp;动漫&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:31</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;emby&nbsp;媒体库&nbsp;电视剧&nbsp;同步完成，共同步数量：47
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:08</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;正在同步&nbsp;emby&nbsp;媒体库&nbsp;电视剧&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:25:08</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;emby&nbsp;媒体库&nbsp;电影&nbsp;同步完成，共同步数量：347
</td></tr>
<tr><td>2023/11/06&nbsp;14:22:37</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;正在同步&nbsp;emby&nbsp;媒体库&nbsp;电影&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:22:37</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;mediaserver.py&nbsp;-&nbsp;开始同步媒体库&nbsp;emby&nbsp;的数据&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:22:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;transfer.py&nbsp;-&nbsp;没有获取到已完成的下载任务
</td></tr>
<tr><td>2023/11/06&nbsp;14:22:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;transfer.py&nbsp;-&nbsp;开始执行下载器文件转移&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>None
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>[31mERROR:[0m&nbsp;&nbsp;&nbsp;chain&nbsp;-&nbsp;运行模块&nbsp;tmdb_trending&nbsp;出错：TheMovieDbModule&nbsp;-&nbsp;Failed&nbsp;to&nbsp;establish&nbsp;a&nbsp;new&nbsp;connection:&nbsp;no&nbsp;response&nbsp;from&nbsp;the&nbsp;server.
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>app.modules.themoviedb.tmdbv3api.exceptions.TMDbException:&nbsp;Failed&nbsp;to&nbsp;establish&nbsp;a&nbsp;new&nbsp;connection:&nbsp;no&nbsp;response&nbsp;from&nbsp;the&nbsp;server.
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;TMDbException("Failed&nbsp;to&nbsp;establish&nbsp;a&nbsp;new&nbsp;connection:&nbsp;no&nbsp;response&nbsp;from&nbsp;the&nbsp;server.")
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;File&nbsp;"/app/app/modules/themoviedb/tmdbv3api/tmdb.py",&nbsp;line&nbsp;176,&nbsp;in&nbsp;_request_obj
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._request_obj(
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;File&nbsp;"/app/app/modules/themoviedb/tmdbv3api/objs/trending.py",&nbsp;line&nbsp;8,&nbsp;in&nbsp;_trending
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._trending(media_type="all",&nbsp;time_window="week",&nbsp;page=page)
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;File&nbsp;"/app/app/modules/themoviedb/tmdbv3api/objs/trending.py",&nbsp;line&nbsp;28,&nbsp;in&nbsp;all_week
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.tmdb.trending.all_week(page=page)
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;File&nbsp;"/app/app/modules/themoviedb/__init__.py",&nbsp;line&nbsp;254,&nbsp;in&nbsp;tmdb_trending
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^^^^^^^^^^^^^^^^^^^^^
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;func(*args,&nbsp;**kwargs)
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>&nbsp;&nbsp;File&nbsp;"/app/app/chain/__init__.py",&nbsp;line&nbsp;97,&nbsp;in&nbsp;run_module
</td></tr>
<tr><td>2023/11/06&nbsp;14:19:18</td><td>stderr</td><td>Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
</td></tr>
<tr><td>2023/11/06&nbsp;14:18:35</td><td>stderr</td><td>[31mERROR:[0m&nbsp;&nbsp;&nbsp;cookiecloud.py&nbsp;-&nbsp;CookieCloud同步失败：
</td></tr>
<tr><td>2023/11/06&nbsp;14:18:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;cookiecloud.py&nbsp;-&nbsp;开始同步CookieCloud站点&nbsp;...
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:36</td><td>stderr</td><td>INFO:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Uvicorn&nbsp;running&nbsp;on&nbsp;http://0.0.0.0:3001&nbsp;(Press&nbsp;CTRL+C&nbsp;to&nbsp;quit)
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:36</td><td>stderr</td><td>INFO:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Application&nbsp;startup&nbsp;complete.
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：IyuuMsg
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：PersonMeta
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;personmeta&nbsp;-&nbsp;演职人员刮削服务启动，周期：0&nbsp;*/12&nbsp;*&nbsp;*&nbsp;*
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：BrushFlow
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[31mERROR:[0m&nbsp;&nbsp;&nbsp;brushflow&nbsp;-&nbsp;用户未认证，无法使用站点功能！
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：SyncDownloadFiles
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;syncdownloadfiles&nbsp;-&nbsp;自动同步下载器文件记录服务启动，时间间隔&nbsp;6&nbsp;小时
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：RssSubscribe
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：AutoBackup
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：NAStoolSync
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：WebHook
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：MediaServerRefresh
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：MediaServerMsg
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：CustomHosts
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;customhosts&nbsp;-&nbsp;更新系统hosts文件成功
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：LibraryScraper
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;libraryscraper&nbsp;-&nbsp;媒体库刮削服务启动，周期：0&nbsp;0&nbsp;*/7&nbsp;*&nbsp;*
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：ChineseSubFinder
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：DirMonitor
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/variety&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/tvs&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/movies&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/documentary&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/children&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;dirmonitor&nbsp;-&nbsp;/volume2/video/links/animation&nbsp;的目录监控服务启动
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：SiteStatistic
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;plugin.py&nbsp;-&nbsp;Plugin&nbsp;Loaded：AutoSignIn
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:35</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;autosignin&nbsp;-&nbsp;站点自动签到服务启动，执行周期&nbsp;0&nbsp;1&nbsp;*&nbsp;*&nbsp;*
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：TransmissionModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：TheTvDbModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：TheMovieDbModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：TelegramModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：SubtitleModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：IndexerModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：FilterModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：FileTransferModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：FanartModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：EmbyModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:32</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;module.py&nbsp;-&nbsp;Moudle&nbsp;Loaded：DoubanModule
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:29</td><td>stderr</td><td>[31mERROR:[0m&nbsp;&nbsp;&nbsp;singleton.py&nbsp;-&nbsp;未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:29</td><td>stderr</td><td>[31mERROR:[0m&nbsp;&nbsp;&nbsp;singleton.py&nbsp;-&nbsp;iyuu认证出错：无法连接站点
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:08</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;singleton.py&nbsp;-&nbsp;认证资源版本：1.0.1
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:08</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;singleton.py&nbsp;-&nbsp;站点资源版本：1.0.1
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:06</td><td>stderr</td><td>INFO:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Waiting&nbsp;for&nbsp;application&nbsp;startup.
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:06</td><td>stderr</td><td>INFO:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Started&nbsp;server&nbsp;process&nbsp;[58]
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:06</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;migration.py&nbsp;-&nbsp;Will&nbsp;assume&nbsp;non-transactional&nbsp;DDL.
</td></tr>
<tr><td>2023/11/06&nbsp;14:17:06</td><td>stderr</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;migration.py&nbsp;-&nbsp;Context&nbsp;impl&nbsp;SQLiteImpl.
</td></tr>
<tr><td>2023/11/06&nbsp;14:16:50</td><td>stdout</td><td>Proxy&nbsp;dockerfrontend&nbsp;started.
</td></tr>
<tr><td>2023/11/06&nbsp;14:16:50</td><td>stdout</td><td>Proxy&nbsp;dockerbackend&nbsp;started.
</td></tr>
<tr><td>2023/11/06&nbsp;14:16:41</td><td>stderr</td><td>/usr/local/bin/mp_update:&nbsp;line&nbsp;77:&nbsp;`if&nbsp;[[&nbsp;"${MOVIEPILOT_AUTO_UPDATE}"&nbsp;=&nbsp;"true"&nbsp;]]&nbsp;||&nbsp;[[&nbsp;"${MOVIEPILOT_AUTO_UPDATE}"&nbsp;=&nbsp;"release"&nbsp;]]&nbsp;||&nbsp;elif&nbsp;[[&nbsp;"${MOVIEPILOT_AUTO_UPDATE}"&nbsp;=&nbsp;"dev"&nbsp;]];&nbsp;then'
</td></tr>
<tr><td>2023/11/06&nbsp;14:16:41</td><td>stderr</td><td>/usr/local/bin/mp_update:&nbsp;line&nbsp;77:&nbsp;syntax&nbsp;error&nbsp;near&nbsp;unexpected&nbsp;token&nbsp;`elif'
</td></tr>
</table>

**Comment by carolcoral** [comment]
## 补充
除IYUU外，同时HDFANS和杜比也无法进行认证

<img width="1058" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/5c8c396e-5498-4b2a-9952-50c3be19f041">
<img width="1072" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/8048baed-a0b8-431f-a47a-aac396e82fa4">

**Comment by carolcoral** [comment]
已经解决IYUU认证和浏览“推荐”问题，需要在docker compose部署的时候使用`host`方式而不是桥接。
```yaml
network_mode: "host"
```

下一步去解决CookieCloud同步失败问题，目前使用自建CC和默认CC都失败

**Comment by carolcoral** [comment]
1. cookiecloud依然无法正常同步
2. 站点配置RSS后依然无法搜索到资源（点击测试可以连接、可以更新cookie，通过站点可以直接搜索到资源）

**Comment by jxxghp** [comment]
问题1重拉镜像，之前的更新脚本有语法错误。

**Comment by carolcoral** [comment]
> 问题1重拉镜像，之前的更新脚本有语法错误。

问题2我在论坛咨询中进行了详细描述，能否帮忙看看是什么问题呢，谢谢🙏

地址：https://github.com/jxxghp/MoviePilot/discussions/1080
