### ISSUE TITLE
[错误报告]: 插件：豆瓣榜单订阅评分不生效

### ISSUE THREAD

**Issue by AlleNPooh** [jxxghp/MoviePilot#1078]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

豆瓣榜单订阅评分不生效，设置了8.5的评分，还是能够刷到低于次评分的资源。ps：自我设置了榜单地址：
https://rsshub.feeded.xyz/douban/movie/weekly/tv_hot
https://rsshub.feeded.xyz/douban/movie/weekly/movie_hot_gaia
https://rsshub.feeded.xyz/douban/movie/weekly/show_domestic
https://rsshub.feeded.xyz/douban/movie/weekly/subject_real_time_hotest

**Comment by jxxghp** [comment]
插件已更新：但要升级到下个版本才能升级。
