### ISSUE TITLE
[Feature Request]: 关于assets.fanart.tv这个网站的刮削，能不能自由选择加入或取消

### ISSUE THREAD

**Issue by adaisanhao** [jxxghp/MoviePilot#1082]
### 当前程序版本

v1.4.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

关于assets.fanart.tv这个网站的刮削，我发现即使配置过代理也进不去这个网站，这个网站好像很久之前被墙了，每次刮削的时候下载这个网站的图片就是失败一直重试，（我再环境变量中加入了代理，连接性都是通的，但连接性中这个网站好像看不到）可不可以有两种方法
1，能在环境变量中加入这个网站刮削的选择，可以取消或者选择这个网站
2，能不能在默认代理里加入这个网站（好像加了代理，只对tg,tmdb,github这几个有效，对fanart这个网站不会起作用）
下面是日志：
正在下载logo图片: http://assets.fanart.tv/fanart/tv/411469/hdtvlogo/the-glory-2022-6390df82df0fpng
3 秒后重试 ...
正在下载logo图片: http://assets.fanarttv/fanart/tv/411469/hdtvlogo/the-glory-2022-6390dff82dfOf.png
6 秒后重试 ..
正在下载logo图片: http://assetsfanart.tv/fanart/tv/411469/hdtvlogo/the-glory-2022-6390dff82dfOfpng
/data/media/电视剧/日韩剧/黑暗荣耀(2022)/Season 1/黑暗荣耀 - S01E05 -第 5 集mkv 刮削失败
/data/media/电视剧/日韩剧/黑暗荣(2022)/Season 1/黑暗荣耀 - S01E05 -第 5 集mkv 刮削完成

有这个网站图片的  都是这样

**Comment by qa19971109** [comment]
我也是这个问题，每次都因为这个然后刮削不成功

**Comment by faithleysath** [comment]
阅读源码可知，fanart同样使用了代理`PROXY_HOST`
![image](https://github.com/jxxghp/MoviePilot/assets/120073078/bfb287bf-f8c9-4c07-a607-d8679fd86988)
