### ISSUE TITLE
[错误报告]: 猫站pterclub.com自动签到不了了，上一个版本还可以的，消息通知里没有提示猫站签到失败，但是实际上并没有签到成功

### ISSUE THREAD

**Issue by 459633382** [jxxghp/MoviePilot#1083]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.0

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

消息通知里没有提示猫站签到失败，但是实际上并没有签到成功

**Comment by AlleNPooh** [comment]
我的可以成功
