### ISSUE TITLE
[错误报告]: Scripter X 文件同步删除不生效, 源文件还在

### ISSUE THREAD

**Issue by Matzoh** [jxxghp/MoviePilot#1084]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

emby 删除通知mp后, 源文件还在(硬链接目录已正常被删除)
mp 可以正常收到请求

**插件情况**: 
emby: scripter x 
mp: 媒体文件同步删除 

**mp 刮削记录**: 
> /media/downloads/movie/三线轮洄.San.Xian.Lun.Hui.2023.2160p.WEB-DL.60fps.H265.10bit.AAC-SharkWEB/三线轮洄.San.Xian.Lun.Hui.2023.2160p.WEB-DL.60fps.H265.10bit.AAC-SharkWEB.mkv=> /media/links/movie/三线轮洄 (2023)/三线轮洄 (2023) - 2160p.mkv

**emby操作**
> \\192.168.101.15\media\links\movie\xxx
<img width="780" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/19823952/e47f4ca1-82bc-4e11-8285-a94a28cddb0e">

### 发生问题时系统日志和配置文件

```bash
INFO:     192.168.101.22:62626 - "GET /api/v1/webhook?token=xxx&event_type=media_del&media_type=Movie&media_name=%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84&media_path=%5C%5C192.168.101.15%5Cmedia%5Clinks%5Cmovie%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%20-%202160p.mkv&tmdb_id=1107397&item_isvirtual=False HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.101.22:62626 - "GET /api/v1/webhook/?token=xxx&event_type=media_del&media_type=Movie&media_name=%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84&media_path=%5C%5C192.168.101.15%5Cmedia%5Clinks%5Cmovie%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%20-%202160p.mkv&tmdb_id=1107397&item_isvirtual=False HTTP/1.1" 200 OK
```

**Comment by thsrite** [comment]
程序没问题
路径映射填 \\192.168.101.15\media:/media
不行的话 emby就挂载本地路径 再不行就放弃

mp日志应该还有`未获取到可删除数据，请检查路径映射是否配置错误`吧？

**Comment by Matzoh** [comment]
> 程序没问题 路径映射填 `\\192.168.101.15\media:/media` 不行的话 emby就挂载本地路径 再不行就放弃
> 
> mp日志应该还有`未获取到可删除数据，请检查路径映射是否配置错误`吧？

感谢解答

docker logs查看上下文确实没有这个日志, 试了下这个映射路径还是不行, 后面试试emby挂载本地路径.
暂时用定时清理媒体库代替源文件删除了~ 

```
INFO:     192.168.101.22:56816 - "GET /api/v1/webhook?token=xxx&event_type=media_del&media_type=Movie&media_name=%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84&media_path=%5C%5C192.168.101.15%5Cmedia%5Clinks%5Cmovie%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%20-%202160p.mkv&tmdb_id=1107397&item_isvirtual=False HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.101.22:56816 - "GET /api/v1/webhook/?token=xxx&event_type=media_del&media_type=Movie&media_name=%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84&media_path=%5C%5C192.168.101.15%5Cmedia%5Clinks%5Cmovie%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%5C%E4%B8%89%E7%BA%BF%E8%BD%AE%E6%B4%84%20(2023)%20-%202160p.mkv&tmdb_id=1107397&item_isvirtual=False HTTP/1.1" 200 OK
INFO:     192.168.101.22:56816 - "POST /api/v1/webhook?token=xxx HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.101.22:56816 - "POST /api/v1/webhook/?token=xxx HTTP/1.1" 200 OK
ERROR:   emby.py - Items/RemoteImages 未获取到返回数据
INFO:    command.py - 处理事件：webhook.message - [<function MediaSyncDel.sync_del_by_webhook at 0x14b92c711f80>, <function MediaSyncDel.sync_del_by_plugin at 0x14b92c712020>]
```
