### ISSUE TITLE
[Feature Request]: 能不能支持电影、剧集和动漫的下载路径为不同的盘

### ISSUE THREAD

**Issue by anooki-c** [jxxghp/MoviePilot#1085]
### 当前程序版本

1.4.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

因为硬盘不是很大，目前只能配置一个下载路径，电影、剧集、动漫都在这个路径下面，硬盘很容易就满了，删了就不能做种。
能不能支持电影、剧集和动漫的下载路径为不同的盘，DOWNLOAD_MOVIE_PATH、DOWNLOAD_TV_PATH、DOWNLOAD_ANIME_PATH可以是不同的父级目录或者盘。
nt好像就支持这样设置

**Comment by luojianquan443** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/63084641/82dfa2c1-b087-487a-8992-de2fff4575dd)
我的media和media2就是位于两个不同的盘

**Comment by anooki-c** [comment]
> ![image](https://user-images.githubusercontent.com/63084641/281608272-82dfa2c1-b087-487a-8992-de2fff4575dd.png) 我的media和media2就是位于两个不同的盘

我之前试是不行，后来更新也没看到相关的更新。
刚刚试了一下，又可以了。
不知道是之前配置出问题了，还是更新了。

**Comment by anooki-c** [comment]
> ![image](https://user-images.githubusercontent.com/63084641/281608272-82dfa2c1-b087-487a-8992-de2fff4575dd.png) 我的media和media2就是位于两个不同的盘


image 我的media和media2就是位于两个不同的盘

我之前试是不行，后来更新也没看到相关的更新。
刚刚试了一下，又可以了。
不知道是之前配置出问题了，还是更新了。
