### ISSUE TITLE
[Feature Request]: 能否给历史记录增加一个筛选功能

### ISSUE THREAD

**Issue by cute-pidan** [jxxghp/MoviePilot#1087]
### 当前程序版本

V1.4.0

### 运行环境

Docker

### 功能改进类型

其他

### 功能改进

能否给历史记录增加一个筛选功能，方便把失败的记录筛选出来，单独进行手动操作
假如一次性下载了大量的电影、电视剧，在历史记录里面会生成大量的记录，一页一页地去翻找失败的记录，不太方便。假如能加入筛选功能，将大大改善这个操作的便利性。

**Comment by JakieWin** [comment]
同求

**Comment by FLIER001** [comment]
附议
