### ISSUE TITLE
[错误报告]: 个别种子集数识别错误

### ISSUE THREAD

**Issue by wushuai111** [jxxghp/MoviePilot#1089]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

这个种子被识别成了有1893集资源的种子，并选中了缺失的第六集也是最后一集。
可否优化识别，或者对集数相关做一下校验，解析到的集数已经大于了订阅处获取到的总集数，这类种子应该丢弃了
<img width="1579" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/60729425/9a586c22-78e6-4730-8be2-1c7079717d5d">

**Comment by cng10001** [comment]
https://github.com/jxxghp/MoviePilot/issues/934
