### ISSUE TITLE
[错误报告]: CookieCloud 跟手动都添加不了馒头

### ISSUE THREAD

**Issue by jiezaizone** [jxxghp/MoviePilot#1090]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="1256" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/28976666/2ac14fea-620f-4d7a-b181-65ce0a4477e6">
CookieCloud 跟手动都添加不了馒头提示不支持或用户未通过认证

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/9ab77da0-9a41-4300-8279-3efd67bf9508)
