### ISSUE TITLE
[错误报告]: pushdeer设置消息类型，在微信上操作时，不起作用

### ISSUE THREAD

**Issue by horseytr** [jxxghp/MoviePilot#1092]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1.pushdeer只接受整理入库和订阅的消息推送
<img width="544" alt="iShot_2023-11-09_05 08 52" src="https://github.com/jxxghp/MoviePilot/assets/76861393/4cabc3de-b3ea-4496-8963-f62ab62fb436">
2.通过企业微信，和moviepilot交互时，一直给pushdeer发送消息推送，只要操作的都会推送
<img width="660" alt="iShot_2023-11-09_05 09 24" src="https://github.com/jxxghp/MoviePilot/assets/76861393/a0b5043f-a9b0-4629-a0b0-2362aab31db1">
<img width="486" alt="iShot_2023-11-09_05 09 53" src="https://github.com/jxxghp/MoviePilot/assets/76861393/4c820aff-4488-48b9-bf8a-80fa1203e9ec">

**Comment by jxxghp** [comment]
已修复，更新插件

**Comment by horseytr** [comment]
谢谢，这么及时
