### ISSUE TITLE
[错误报告]: 😭无法保存下载优先规则和搜索站点设置，一重启就恢复😢

### ISSUE THREAD

**Issue by horseytr** [jxxghp/MoviePilot#1094]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1.在设定-下载优先规则-选择“做种数优先”
2.在设定-搜索-搜索站点-选定“特定的站点”
以上都保存后，日志里也出现POST请求，但是一旦重启，就会恢复，日志里找不出错误提醒
---------------------------------------
这是设定，保存
<img width="2268" alt="iShot_2023-11-09_12 35 33" src="https://github.com/jxxghp/MoviePilot/assets/76861393/159c727b-29e0-49ea-8d40-1b463882e6b6">
<img width="1233" alt="iShot_2023-11-09_12 34 50" src="https://github.com/jxxghp/MoviePilot/assets/76861393/9b00811e-4d26-4351-b5f3-b393fe741551">

----------------------------------------
这是日志Post请求
<img width="912" alt="iShot_2023-11-09_12 39 54" src="https://github.com/jxxghp/MoviePilot/assets/76861393/6c1b8a46-0d0e-4205-a2b0-eac3788e234e">
这是重启日志
<img width="1037" alt="iShot_2023-11-09_12 39 05" src="https://github.com/jxxghp/MoviePilot/assets/76861393/2d7337ea-19f7-4551-905a-9d465a3dd8a7">

----------------------------------------
这是重启后，设定又恢复了，没有保存之前的修改
<img width="2348" alt="iShot_2023-11-09_12 40 37" src="https://github.com/jxxghp/MoviePilot/assets/76861393/78b3a86a-aafb-4f41-8749-6356a74fbc80">
<img width="1262" alt="iShot_2023-11-09_12 40 13" src="https://github.com/jxxghp/MoviePilot/assets/76861393/c398dc71-3190-48c0-8949-8deda25f6192">

### 发生问题时系统日志和配置文件
这是权限设定，其他地方都是可以保存保存的
<img width="439" alt="iShot_2023-11-09_13 08 28" src="https://github.com/jxxghp/MoviePilot/assets/76861393/131aeaf1-e9b1-45fd-a284-9460c4815ab2">

_No response_

**Comment by jxxghp** [comment]
没有这个问题

**Comment by horseytr** [comment]
好的，我自己再找找问题出在哪，谢谢发自我的 iPhone在 2023年11月10日，22:03，jxxghp ***@***.***> 写道：﻿
没有这个问题
