### ISSUE TITLE
[Feature Request]: 希望可以给订阅增加一个自定义下载目录

### ISSUE THREAD

**Issue by luojianquan443** [jxxghp/MoviePilot#1099]
### 当前程序版本

v1.4.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

如题，类似于NASTOO可以给每个订阅设置一个下载目录
![1699599513651](https://github.com/jxxghp/MoviePilot/assets/63084641/346e6ade-7b27-4026-b8b3-43d1941fa661)

### 参考资料

Nastool订阅设置

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/093a0f05-0c73-4af1-a1c7-46ba3801b20f)这3个应该是能自定义的

**Comment by luojianquan443** [comment]
这个我是知道的，主要是有时候有跨盘的需求，比如我日漫看得比较多，日漫全放在放在了1盘，但是我想把国漫下载到2盘，然而国漫也属于动漫的分类就会下到了1盘，所以目前好像是做不到的吧

> ![image](https://user-images.githubusercontent.com/115156545/282283181-093a0f05-0c73-4af1-a1c7-46ba3801b20f.png)这3个应该是能自定义的

**Comment by cng10001** [comment]
https://github.com/jxxghp/MoviePilot/issues/290 
https://github.com/jxxghp/MoviePilot/issues/969
https://github.com/jxxghp/MoviePilot/issues/1007
有很多类似的提问
