### ISSUE TITLE
不能添加用户，不知道咋回事！[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by daguo9** [jxxghp/MoviePilot#1102]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

设定-用户里面，点添加用户没反应！日志也完全没有

**Comment by jxxghp** [comment]
需要维护邮箱

**Comment by Link-KXL** [comment]
我也一样，新增不了用户，添加了邮箱点了没反应
