### ISSUE TITLE
[错误报告]: 使用第三方插件库后，每次重启都要重新更新插件版本，不会记录更新好的版本

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#1104]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新dev

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

使用第三方插件库后，每次重启都要重新更新插件版本，不会记录更新好的版本

**Comment by jxxghp** [comment]
1、不要使用dev更新模式。
2、拉取最新的镜像，同时不要重置镜像。
