### ISSUE TITLE
[错误报告]: 下载器设为Transmission，不能监控下载器

### ISSUE THREAD

**Issue by hbq0405** [jxxghp/MoviePilot#111]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版

### 问题类型

主程序运行问题

### 问题描述

当下载器设置为TR时，可以推送种子到下载器并成功下载，仪表板也能正常显示实时速率。但是正在下载栏看不到正在下载的记录，且下载完成后没有识别转移。

**Comment by samyang211** [comment]
+1，一模一样问题。
同时打开管理台内日志查看页面，很卡顿，很久才能打开。

**Comment by jxxghp** [comment]
@samyang211 日志刷的是增量的，有新日志才显示啊，没新日志就一真等待。去docker后台看一下不就知道了。

**Comment by samyang211** [comment]
> @samyang211 日志刷的是增量的，有新日志才显示啊，没新日志就一真等待。去docker后台看一下不就知道了。

收到，明白了，谢谢大佬

**Comment by samyang211** [comment]
建议考虑NT的日志模式，页面上很好用
