### ISSUE TITLE
[错误报告]: 订阅电视剧出错

### ISSUE THREAD

**Issue by madswaord** [jxxghp/MoviePilot#1116]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我订阅清单里已经有电视剧6666， 然后新增订阅电视剧 2024时会跳出6666的确认框， 查看后台log已经正确识别到2024的tmdbid 但还是跳转到缓存6666的记录
![截屏2023-11-13 22 15 21](https://github.com/jxxghp/MoviePilot/assets/86275875/7907e1f2-2451-46cc-9466-6143edd83a8d)
![截屏2023-11-13 22 14 56](https://github.com/jxxghp/MoviePilot/assets/86275875/d751cddf-06e3-4214-b613-c3f554ce8a20)

**Comment by jxxghp** [comment]
重现不了
