### ISSUE TITLE
[错误报告]: 删除历史记录、源文件、媒体库文件时，部分辅种任务没有被删除

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#1124]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.4.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

事情是这样的，测试的时候发现，1.4的某个版本的问题，我是前两天新加入了ttg，然后对某个之前存在的种子进行了辅种，现在对那个种子进行删除时，之前的任务都删除掉了，唯独辅种的任务没有被删除，查询日志发现，ttg辅种的任务是不是没有被写入iyuu的日志信息？
![iShot_2023-11-14_16 12 05](https://github.com/jxxghp/MoviePilot/assets/34505611/b2df1051-9346-4003-b838-59ec4a94135d)
![iShot_2023-11-14_16 12 27](https://github.com/jxxghp/MoviePilot/assets/34505611/f90f64b2-46a3-4933-a045-8f2d215e7929)

**Comment by thsrite** [comment]
通过mp辅种插件辅种的？
剩下那个ttg的种子hash是什么？

**Comment by yellowstrong** [comment]
> 通过mp辅种插件辅种的？ 剩下那个ttg的种子hash是什么？
对的，我发现问题了，可以看下面的图片，我查找目前下载器的甄嬛传这个种子，一共有8个，其中一个是MP手动下载的，剩下7个中的5个是辅种插件第一次辅种出来的，还有两个岛跟ttg的种子是第二次辅种出来的，然而在数据库中的插件日志里面，IYUU的日志只能查询到第一次5个种子的日志，并没有后面新辅种的日志记录
![iShot_2023-11-14_16 38 36](https://github.com/jxxghp/MoviePilot/assets/34505611/e859bf2b-b69c-4960-bf99-bc83a9d86f09)
![iShot_2023-11-14_16 35 17](https://github.com/jxxghp/MoviePilot/assets/34505611/62ed09cd-25d8-4ff7-96df-f389ae8d9866)
![iShot_2023-11-14_16 35 30](https://github.com/jxxghp/MoviePilot/assets/34505611/e81166bb-8694-4d2a-bc27-74727c4122ee)

**Comment by yellowstrong** [comment]
另外是否可以考虑将这种没有被成功添加日志的数据，在使用辅种插件时，添加一个小功能，让这些已经成功辅种站点数据同步到IYUU插件的日志中以解决这种问题

**Comment by yellowstrong** [comment]
经过整理数据库发现，并不是第二次辅种的hash没有写入到数据库的插件记录IYUUAutoSeed中，而是新建多条，如下两图
![iShot_2023-11-15_11 05 44](https://github.com/jxxghp/MoviePilot/assets/34505611/a634d004-291d-400e-8338-503f1c881ff8)
![iShot_2023-11-15_11 06 12](https://github.com/jxxghp/MoviePilot/assets/34505611/f0c5e363-ffa3-4d89-a042-f7825b929df1)
下载器中，由MP下载的种子hash为c54打头，然而，在第二次辅种成功后，相同的种子居然又写入了一条之前辅种的hash 9da为key的新纪录，而不是在c54的key种追加hash，导致出现的数据错误

**Comment by thsrite** [comment]
更新插件1.2版本试试

**Comment by thsrite** [comment]
> ![iShot_2023-11-22_14 14 49](https://user-images.githubusercontent.com/34505611/284807462-aed76ae9-5760-440d-8bd9-7f59588e1703.png) 报错

删除镜像重拉
