### ISSUE TITLE
11月4日开始无法连通 audiences.me站点，同网络电脑可正常登入。

### ISSUE THREAD

**Issue by vin-ng** [jxxghp/MoviePilot#1131]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.2-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

之前一直无问题，11月4日开始无法连通 audiences.me站点，通过代理也无法访问，同个网络电脑可正常访问站点。

### 发生问题时系统日志和配置文件

```bash
browser.py
网页操作失败: net::ERR_CONNECTION_REFUSED at https://audiences.me/
```

**Comment by lux032** [comment]
这个问题我没出现 大概率是你本地环境的问题
