### ISSUE TITLE
[Feature Request]: 既然支持豆瓣刮削的话，希望能在媒体页面也能有个豆瓣超链接，嘿嘿

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#1135]
### 当前程序版本

v1.4.2-1

### 运行环境

Docker

### 功能改进类型

其他

### 功能改进

如题  
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/48a1418c-388e-4bb6-823f-b4998b8655c3)

**Comment by ati121** [comment]
支持.这样跳转豆瓣看评论很方便

**Comment by Spirei** [comment]
支持 这样就不用再去豆瓣搜了 跳转方便

**Comment by jifengguo** [comment]
支持。。有这个需要。
