### ISSUE TITLE
[错误报告]: 天空的种子一直404出错一直不停重复下载

### ISSUE THREAD

**Issue by syscc** [jxxghp/MoviePilot#1141]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

订阅的剧集，下天空404还是一直不停重复下。
很多这种错误。但是我在空进这个id是存在种子，下载种子是没问题

### 发生问题时系统日志和配置文件

```bash
【ERROR】2023-11-18 07:45:57,154 - download.py - 下载种子文件失败：Chase the Truth S01 2023 2160p WEB-DL AAC H265-HDSWEB - https://hdsky.me/download.php?id=353453&t=***&sign=***
【INFO】2023-11-18 07:45:57,155 - chain - 发送消息：channel=None，title=Chase the Truth S01 2023 2160p WEB-DL AAC H265-HDSWEB 种子下载失败！, text=错误信息：下载种子出错，状态码：404
【ERROR】2023-11-18 08:10:05,323 - download.py - 下载种子文件失败：Chase the Truth S01 2023 2160p WEB-DL AAC H265-HDSWEB - https://hdsky.me/download.php?id=353453&t=***&sign=***
【INFO】2023-11-18 08:10:05,324 - chain - 发送消息：channel=None，title=Chase the Truth S01 2023 2160p WEB-DL AAC H265-HDSWEB 种子下载失败！, text=错误信息：下载种子出错，状态码：404
```

**Comment by NikoYomi** [comment]
+1！通知还一直发送，憨憨也会报，不过是403！
