### ISSUE TITLE
[错误报告]: 当微信搜索自动下载在更剧时，剧集未入库，首次添加订阅的搜索会出现重复下载

### ISSUE THREAD

**Issue by wq2020wdm** [jxxghp/MoviePilot#1144]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

微信设置的自动下载，搜索下载了但是没有入库，因为剧集正在更新，所以自动添加了订阅，添加订阅会首次全量搜索，搜索时判断库里没有，会再次下载

**Comment by jxxghp** [comment]
代码逻辑上看不出来问题，请补充日志：
```
# 未完成下载
            logger.info(f'{_current_media.title_year} 未下载未完整，添加订阅 ...')
            # 添加订阅，状态为R
            self.subscribechain.add(title=_current_media.title,
                                    year=_current_media.year,
                                    mtype=_current_media.type,
                                    tmdbid=_current_media.tmdb_id,
                                    season=_current_meta.begin_season,
                                    channel=channel,
                                    userid=userid,
                                    username=username,
                                    state="R")
```

**Comment by thsrite** [comment]
@jxxghp 这里添加订阅的时候加上note字段，把搜索自动下载的集数加进去应该就好了。
