### ISSUE TITLE
[错误报告]: 播放限制插件不能正常触发限速

### ISSUE THREAD

**Issue by tone88** [jxxghp/MoviePilot#1145]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

MP版本：1.4.3，播放限速插件版本：1.0，Jellyfin版本：10.8.10

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

运行环境： 群晖里docker跑的MP和Jellyfin。

播放限制插件使用中遇到的问题：
1、播放限速功能必须设置“不限速地址范围”才会生效，如果此项不设置不论是在局域网内播放还是在外通过域名访问都不会触发播放限速。   
2、在设置“不限速地址范围”后播放时能正常触发播放限速，但是这时不论是在外通过域名访问还是在家用局域网访问都会触发播放限速。

**设置限速地址范围后的日志：**（这时如果在局域网内播放仍然会触发限制策略并成功限速）
【INFO】2023-11-20 08:51:45,154 - speedlimiter - 播放限速检查服务启动
【INFO】2023-11-20 08:54:39,646 - chain - 发送消息：channel=None，title=【播放限速】, text=Qbittorrent 开始播放限速
上传：-67 KB/s
下载：512.0 KB/s，userid=None
【INFO】2023-11-20 08:54:39,648 - command.py - 处理事件：notice.message - []
【INFO】2023-11-20 08:54:41,667 - chain - 发送消息：channel=None，title=【播放限速】, text=Transmission 开始播放限速
上传：-60 KB/s
下载：512.0 KB/s，userid=None
【INFO】2023-11-20 08:54:41,668 - command.py - 处理事件：notice.message - []
【INFO】2023-11-20 08:55:18,381 - brushflow - 开始执行刷流任务 ...

**未设置不限速地址范围是的日志：**（此时已经播放一段时间，日志里并没有限速相关信息）
【INFO】2023-11-20 09:05:21,994 - brushflow - 刷流下载任务检查完成
【INFO】2023-11-20 09:08:00,121 - torrentremover - 自动删种任务 获取符合处理条件种子数 0
**【INFO】2023-11-20 09:08:23,512 - speedlimiter - 播放限速检查服务启动**
【INFO】2023-11-20 09:10:18,385 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2023-11-20 09:10:18,390 - brushflow - 开始检查刷流下载任务 ...

附一张插件设置图：
![11111](https://github.com/jxxghp/MoviePilot/assets/47731895/882cebc9-ecbf-4562-bbfb-652f7f10ddcb)

**Comment by jxxghp** [comment]
正常使用，确认不是自己的问题再提。
