### ISSUE TITLE
[Feature Request]: 建议支持鲨鱼pt

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#1146]
### 当前程序版本

1.4.3

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

建议支持鲨鱼pt，还有影换了新域名

**Comment by thsrite** [comment]
老大早就支持了

环境变量或者app.env添加
`AUTO_UPDATE_RESOURCE=true`

重启mp

**Comment by dlovew** [comment]
> 老大早就支持了
> 
> 环境变量或者app.env添加 `AUTO_UPDATE_RESOURCE=true`
> 
> 重启mp

好哒
