### ISSUE TITLE
[错误报告]: 无意中发现日志的报错

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#1149]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![screenshot20231120 (1)](https://github.com/jxxghp/MoviePilot/assets/59035223/e866fb02-3826-45ea-81b5-ed625690dafc)

**Comment by jxxghp** [comment]
已在插件仓库修改， 演职人员刮削插件 升级到v1.1
