### ISSUE TITLE
[错误报告]: 搜索资源后台日志显示“获取网页源码失败”

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1151]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.4

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

使用 `搜索/推荐` 功能搜索资源，后台日志中站点全部返回 `获取网页源码失败` 。前端页面返回 `站点搜索完成，有效资源数：0，总耗时 76 秒`

#### 尝试过：
1. 重新构建容器
2. 重启容器
3. 修改站点 `代理/非代理` 模式
4. 切换网络模式为 `host`/`bridge`

以上操作全部尝试后仍然无法解决问题

<img width="1428" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/561853cf-d29e-4296-9b62-7117a8b419cd">

**Comment by carolcoral** [comment]
@jxxghp 大佬啊，我是真的不知道怎么解决了啊。升级版本、局域网开启`科学上网`、host方式连接都试过了，都不行啊

**Comment by jxxghp** [comment]
确认站点连通性， 关掉仿真试试。
上面的错就是连不上，超时了。
