### ISSUE TITLE
彩虹岛新域名无法自动添加站点进MP

### ISSUE THREAD

**Issue by Taurus0514** [jxxghp/MoviePilot#1157]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

由于地区一些网络原因，彩虹岛开启新域名chddiy.xyz针对无法登入的玩家。我在cookie插件中添加这个新域名，然后删除原来的域名，手动备份。然后在MP中删除原来的站点，重启后彩虹岛站点无法自动被添加。

**Comment by cng10001** [comment]
那还是先用mp支持的ptchdbits.co，自定义hosts目前还可以用

**Comment by Taurus0514** [comment]
> 那还是先用mp支持的ptchdbits.co，自定义hosts目前还可以用

我这边用不了，直接跳转96110
