### ISSUE TITLE
iyuu插件辅种馒头不成功

### ISSUE THREAD

**Issue by whhphd** [jxxghp/MoviePilot#1159]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

iyuu 插件辅种馒头不成功，其他站点都可以辅上，就是馒头不行，用 iyuu原版手动辅种就可以辅上
清空缓存后运行，查看日志，全部显示为：当前站点不在选择的辅种站点范围，跳过 ... 或者：已在下载器中，跳过 ...
怀疑是否为馒头新旧域名导致self.iyuuhelper.get_torrent_url和self._sites不一致？

```
if self._sites and site_info.get('id') not in self._sites:
    logger.info("当前站点不在选择的辅种站点范围，跳过 ...")
return False
```

![image](https://github.com/jxxghp/MoviePilot/assets/5513043/d3857a58-1588-4afc-9c8b-1682efa6966a)
tg群搜索到有人反映同样的问题,但无解答

**Comment by jxxghp** [comment]
是的，只支持xp.xxx.io域名

**Comment by whhphd** [comment]
> 是的，只支持xp.xxx.io域名

mp站点使用的是xp.xxx.io域名，是iyuu不支持吗？

**Comment by hh0610** [comment]
> 是的，只支持xp.xxx.io域名

站点选择了xp.xxx.io域名一样提示当前站点不在选择的辅种站点范围，跳过 ...

**Comment by SawXu** [comment]
iyuu中支持的馒头域名是 kp.xxx.cc，但是moviePilot中的是xp.xxx.io。
在`plugins/iyuuautoseed/__init__.py`中这一行
```
        # 站点信息
        site_info = self.sites.get_indexer(site_domain)
```
从IYUU中获取的site_domain是"kp.xxx.cc"
而self.sites中的馒头域名却是“xp.xxx.io”
从而无法获取到site_info，导致辅种失败。

想请教下大佬要怎么改比较好。

> 是的，只支持xp.xxx.io域名
