### ISSUE TITLE
[错误报告]: 豆瓣手动识别成功，自动刮削失败

### ISSUE THREAD

**Issue by bigmouse0001** [jxxghp/MoviePilot#1170]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.6

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

配置中心启用豆瓣刮削，手动识别文件名，选择豆瓣，可以搜出来信息；自动整理文件，啥都失败。。。确定这个资源只有豆瓣有，TMDB搜不出来的  

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-11-26 20:47:59,948 - media.py - 开始搜索媒体信息：父亲是棵树
【INFO】2023-11-26 20:47:59,950 - media.py - 父亲是棵树 搜索到 9 条相关媒体信息
【INFO】2023-11-26 20:48:13,610 - transfer.py - 手动转移：A:\电影\test\电影频道3300部测试\父亲是棵树.ts ...
【INFO】2023-11-26 20:48:13,614 - douban - 正在识别 父亲是棵树 ...
【INFO】2023-11-26 20:48:13,615 - douban - 开始使用名称 父亲是棵树 匹配豆瓣信息 ...
【INFO】2023-11-26 20:48:13,615 - douban - 父亲是棵树 未匹配到豆瓣媒体信息
【INFO】2023-11-26 20:48:13,616 - media.py - 请求辅助识别，标题：父亲是棵树 ...
【INFO】2023-11-26 20:48:13,616 - command.py - 处理事件：name.recognize - []
【WARNING】2023-11-26 20:48:23,663 - media.py - 父亲是棵树 未识别到媒体信息
【WARNING】2023-11-26 20:48:23,663 - transfer.py - A:\电影\test\电影频道3300部测试\父亲是棵树.ts 未识别到媒体信息
【INFO】2023-11-26 20:48:23,994 - chain - 发送消息：channel=None，title=父亲是棵树.ts 未识别到媒体信息，无法入库！
回复：
/redo 17485 [tmdbid]|[类型]
``` 手动识别转移。, text=None，userid=None
【INFO】2023-11-26 20:48:23,994 - command.py - 处理事件：notice.message - []
【INFO】2023-11-26 20:48:23,995 - transfer.py - A:\电影\test\电影频道3300部测试\父亲是棵树.ts 转移完成，共 1 个文件，失败 1 个，跳过 0 个
```

**Comment by cirry** [comment]
windows下的这个用户认证是怎么弄的，我手动去同步cookiecloud提示证用户未认证，无法使用站点功能！但是在app.env也不知道在哪配置用户认证信息

**Comment by bigmouse0001** [comment]
> windows下的这个用户认证是怎么弄的，我手动去同步cookiecloud提示证用户未认证，无法使用站点功能！但是在app.env也不知道在哪配置用户认证信息

开心版

**Comment by SSL4536** [comment]
> windows下的这个用户认证是怎么弄的，我手动去同步cookiecloud提示证明用户未认证，无法使用站点功能！但是在app.env也不知道在哪配置用户认证信息

在环境变量里添加iyuu或者站点就行，看教程阿伟
