### ISSUE TITLE
[Feature Request]: 希望增加github代理环境变量

### ISSUE THREAD

**Issue by MinTiang** [jxxghp/MoviePilot#1171]
### 当前程序版本

最新版

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前GitHub挺难连接的，希望可以增加配置GitHub代理的环境变量
例如这个：https://mirror.ghproxy.com/https://github.com/stilleshan/ServerStatus

### 参考资料
github代理网站：https://mirror.ghproxy.com/

_No response_

**Comment by mizb** [comment]
是的，我也希望增加。毕竟cf套一层比翻墙稳定多了。
