### ISSUE TITLE
[Feature Request]: 推荐影片增加豆瓣评分及链接

### ISSUE THREAD

**Issue by linlincomic** [jxxghp/MoviePilot#1173]
### 当前程序版本

1.4.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

现有影片评分为IMDB，评分机制与国内口味不太吻合，豆瓣更适合国人一点，希望能增加豆瓣评分显示。

**Comment by FLIER001** [comment]
豆瓣评分人多了就大致回归正常了，国外对部分国产影视作品的评分人数太少了，分数不具有代表性
