### ISSUE TITLE
[Feature Request]: 希望订阅和刷流相结合，先获取订阅再过滤刷流

### ISSUE THREAD

**Issue by WannaYoung** [jxxghp/MoviePilot#1179]
### 当前程序版本

1.4.6

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

比如我想自动下载馒头免费的3-20G的9kg资源到下载器的/aaa目录

**Comment by Cvencent** [comment]
是的，有时候订阅会在刷流后面，刷流下载到刷流目前下了，订阅再下载就会报错
