### ISSUE TITLE
[错误报告]: hdsky和audiences 站点搜索不到资源

### ISSUE THREAD

**Issue by codeses** [jxxghp/MoviePilot#1182]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.7 最新

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

首先是cookie没有问题，在nastool中复制过来的，订阅地址放到浏览器也能返回xml形式的内容。但是在moviepilot的日志中提示没有资源
![image](https://github.com/jxxghp/MoviePilot/assets/58210554/7cfc4b6b-996d-47b2-be32-b529ae2d7b24)
直接在站点管理中点击浏览
![image](https://github.com/jxxghp/MoviePilot/assets/58210554/b048f7e6-e69f-46ce-b71f-b750f6ea8fd7)
qingw请问是不支持这两个站点吗

**Comment by chiao666** [comment]
猪猪好像也不能浏览到资源了

**Comment by codeses** [comment]
> 猪猪好像也不能浏览到资源了

我感觉是我什么地方没有配置对，因为我的馒头也不对。但是 我看其他人的馒头都是对的

**Comment by codeses** [comment]
不知道怎么回事 关闭站点的仿真就可以了

**Comment by MoonMaoo** [comment]
> 不知道怎么回事 关闭站点的仿真就可以了

太感谢了，翻遍了readme和tg群，终于在这解决了问题
