### ISSUE TITLE
[错误报告]: 标题刮削问题

### ISSUE THREAD

**Issue by rotent** [jxxghp/MoviePilot#1196]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.8

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

刮削nfo文件没问题，但是剧集标题不是tmdb的而是顺序命名
![410199e3aae722064d333a3b1b6fc5e](https://github.com/jxxghp/MoviePilot/assets/93746829/31d38e7b-eb1a-4ef2-b6b0-63c70bc9b08b)
![57c43d01f425e38ba195b593062f80a](https://github.com/jxxghp/MoviePilot/assets/93746829/aa951d7d-8f5e-4416-b669-b7407b28756d)
![ce6edd97f6dbd05ed7e86450808ec64](https://github.com/jxxghp/MoviePilot/assets/93746829/0ec35e19-1d7a-4b4a-8fd4-08324a4b0f64)
![db7c2a987dd63c24a882954fa966692](https://github.com/jxxghp/MoviePilot/assets/93746829/cda48704-1992-42c3-a5d0-264caf8c8b28)

**Comment by rotent** [comment]
tmdb的是这样的标题
![acd1ae3225ece5c890e3ec6131c7b1f](https://github.com/jxxghp/MoviePilot/assets/93746829/d18423c8-d1c4-44a9-b7e3-f361b72a4476)

**Comment by rotent** [comment]
不知道哪个版本开始出现的问题，以前标题是正确的

**Comment by dlovew** [comment]
好像确实这样

**Comment by dlovew** [comment]
> 看看你的坏境变量 TV_RENAME_FORMAT

他说的不是这个标题，是tmdb的信息，在emby出现的集信息

**Comment by jxxghp** [comment]
刮削的时候TMDB就有了吗？ 如果这集是新出的，下载很及时的话，大概率TMDB那里还没有，只是后面去看被人补充上去了吧。

**Comment by rotent** [comment]
> 刮削的时候TMDB就有了吗？ 如果这集是新出的，下载很及时的话，大概率TMDB那里还没有，只是后面去看被人补充上去了吧。

刮削的时候TMDB就有了，删了重新刮也是一样

**Comment by rotent** [comment]
破案了，是emby4.8.0.61版本的问题，62版本已修复
