### ISSUE TITLE
索引未显示

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/MoviePilot#120]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/61082200/edeb060c-acac-4cd6-a4ee-58501255e719)
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/21a4edcb-d95c-4ef0-9295-d94159004795)
1.站点管理有显示的站点，但是索引却无法显示，已删除所有数据，重新设置也一样
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/7dcf6d9c-fa69-48d4-9f91-f94ce6a7ab20)
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/d46939d4-a051-4b2a-b3ad-fd5fc97aae55)

2.还是有报错
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/63cf4548-e96d-4be5-b5ab-3e2a58a2faad)
3.还有站点数据统计插件如果勾选立即运行一次，并保存，启用插件为未勾选状态，反之为勾选状态

**Comment by jxxghp** [comment]
不显示索引站点的问题，可能是没有认证。
没有Plex，Plex的问题没法查了，等有Plex的有缘人来修吧。
站点统计数据的问题修好了。

**Comment by aiwu12** [comment]
> 不显示索引站点的问题，可能是没有认证。 没有Plex，Plex的问题没法查了，等有Plex的有缘人来修吧。 站点统计数据的问题修好了。

![image](https://github.com/jxxghp/MoviePilot/assets/61082200/80e5f103-ea67-4dd5-9948-b606aa9e895c)
这个认证成功了吧，还是没有
