### ISSUE TITLE
[Feature Request]: 目录同步指定类型以及辅助识别

### ISSUE THREAD

**Issue by sjtuross** [jxxghp/MoviePilot#1200]
### 当前程序版本

v1.4.8

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

目的是批量识别网盘转存的电影，装了目录同步和ChatGPT插件

1. 由于命名问题，有些电影被当作电视剧识别了，监控目录设置处是否可以指定类型为电影？
2. 同步的时候，通过观察日志，未识别的并没有调用ChatGPT辅助识别

**Comment by ainas999** [comment]
这个目录识别确实没有nt的好，nt只要设定好了目标目录就可以了，但是mp还要在目标目录后加上媒体库名称。例如，我想转移到“媒体库/电影”，实际上就会变成“媒体库/电影/电影”。
