### ISSUE TITLE
每次更新后，药丸签到周期被重置

### ISSUE THREAD

**Issue by bg1258** [jxxghp/MoviePilot#1203]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

药丸签到周期之前设置为9点整，由于经常无法签到，后面改成非整点签到使用正常，但是每次更新后，签到周期都会变成9点整，卸载重装插件也是一样

**Comment by jxxghp** [comment]
请提交插件仓库Bug
