### ISSUE TITLE
[Feature Request]: win端可以开启在线插件功能吗？

### ISSUE THREAD

**Issue by q10855901** [jxxghp/MoviePilot#1210]
### 当前程序版本

v1.4.8-2

### 运行环境

Windows

### 功能改进类型

主程序

### 功能改进

期望win端可以开启在线插件功能，能够使用第三方插件，谢谢

### 参考资料

。

**Comment by coco-bike** [comment]
需要这样的功能，现在windows程序，无法安装其他插件，也找不到安装方法
