### ISSUE TITLE
订阅日历不显示视频图标了

### ISSUE THREAD

**Issue by zrwd01** [jxxghp/MoviePilot#1212]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.4.8-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅日历不显示视频图标了
![QQ截图20231205230104](https://github.com/jxxghp/MoviePilot/assets/33946060/710c535f-0243-4e36-8fc6-b2b03aefbd06)

**Comment by sexyfeifan** [comment]
我也发生了 发了求助 没人理，后来你是怎么好的？

**Comment by zrwd01** [comment]
> 我也发生了 发了求助 没人理，后来你是怎么好的？

好像是重新部署了，时间太久了，记不清楚了
