### ISSUE TITLE
[Feature Request]: ERROR:   qbittorrent.py - qbittorrent 连接出错：身份认证失败次数过多，您的 IP 地址已被封禁。

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1213]
### 当前程序版本

前端版本：v1.4.8，后端版本：v1.4.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

内网IP地址封了，希望能添加设置解封的操作，谢谢

**Comment by kingcard1131** [comment]
已解决，不是MP的问题

**Comment by IOTA233** [comment]
> 已解决，不是MP的问题

请问是怎么解决的？我也遇到了，换了另外一个qb也一样报错了

**Comment by Camellia0821** [comment]
> 已解决，不是MP的问题

请问怎么解决的，我今天也遇到同样的问题
