### ISSUE TITLE
[错误报告]: 订阅界面无法修改信息

### ISSUE THREAD

**Issue by hbzjwyz** [jxxghp/MoviePilot#1215]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.4.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅界面无论输入什么都会被清空，下拉菜单选择的也是

https://github.com/jxxghp/MoviePilot/assets/63764017/7fb4bfc8-4ffe-4148-a893-c79f40e4e5cb

**Comment by lushhweb** [comment]
同样的问题，看控制台一直在请求
![image](https://github.com/jxxghp/MoviePilot/assets/89635428/eaed5b71-104f-4059-b1c7-d3200d74312e)

**Comment by hermer** [comment]
v1.5.3版本也有同样的问题，求解决方案

**Comment by xdjohn99** [comment]
docker
1.5.3 
也是这个问题

**Comment by xdjohn99** [comment]
手动取消订阅后最后输出
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/site/rss HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "DELETE /api/v1/subscribe/1 HTTP/1.1" 200 OK
INFO:     192.168.50.66:0 - "GET /api/v1/subscribe/1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
