### ISSUE TITLE
[Feature Request]: 请求对麒麟站点的支持

### ISSUE THREAD

**Issue by itonycheng** [jxxghp/MoviePilot#1216]
### 当前程序版本

1.4.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

请求对麒麟站点的支持
[www.hdkylin.in](https://www.hdkyl.in/)

**Comment by hh0610** [comment]
不是新出了插件要是会写的话自己直接配置就可以了. 自定义索引站点

**Comment by kingcard1131** [comment]
同求麒麟  杏坛 海胆的支持

**Comment by phantasyleo** [comment]
麒麟，海胆+1，谢谢

**Comment by kayloving** [comment]
自定义索引插件安装好添加这段
hdkyl.in|eyJpZCI6Imhka3lsIiwibmFtZSI6Ium6kum6nyIsImRvbWFpbiI6Imh0dHBzOi8vd3d3Lmhka3lsLmluLyIsImVuY29kaW5nIjoiVVRGLTgiLCJwdWJsaWMiOmZhbHNlLCJzZWFyY2giOnsicGF0aHMiOlt7InBhdGgiOiJ0b3JyZW50cy5waHAiLCJtZXRob2QiOiJnZXQifV0sInBhcmFtcyI6eyJzZWFyY2giOiJ7a2V5d29yZH0iLCJzZWFyY2hfYXJlYSI6NH0sImJhdGNoIjp7ImRlbGltaXRlciI6IiAiLCJzcGFjZV9yZXBsYWNlIjoiXyJ9fSwiY2F0ZWdvcnkiOnsibW92aWUiOlt7ImlkIjo0MDEsImNhdCI6Ik1vdmllcyIsImRlc2MiOiJNb3ZpZXPnlLXlvbEifSx7ImlkIjo0MDUsImNhdCI6IkFuaW1lIiwiZGVzYyI6IkFuaW1hdGlvbnPliqjmvKsifSx7ImlkIjo0MDQsImNhdCI6IkRvY3VtZW50YXJ5IiwiZGVzYyI6IkRvY3VtZW50YXJpZXPnuqrlvZXniYcifV0sInR2IjpbeyJpZCI6NDAyLCJjYXQiOiJUViIsImRlc2MiOiJUViBTZXJpZXPnlLXop4bliacifSx7ImlkIjo0MjAsImNhdCI6IlRWIiwiZGVzYyI6IlRWIFNob3dz57u86Im6In0seyJpZCI6NDA0LCJjYXQiOiJEb2N1bWVudGFyeSIsImRlc2MiOiJEb2N1bWVudGFyaWVz57qq5b2V54mHIn0seyJpZCI6NDA1LCJjYXQiOiJBbmltZSIsImRlc2MiOiJBbmltYXRpb25z5Yqo5ryrIn1dfSwidG9ycmVudHMiOnsibGlzdCI6eyJzZWxlY3RvciI6InRhYmxlLnRvcnJlbnRzID4gdHI6aGFzKFwidGFibGUudG9ycmVudG5hbWVcIikifSwiZmllbGRzIjp7ImlkIjp7InNlbGVjdG9yIjoiYVtocmVmKj1cImRldGFpbHMucGhwP2lkPVwiXSIsImF0dHJpYnV0ZSI6ImhyZWYiLCJmaWx0ZXJzIjpbeyJuYW1lIjoicmVfc2VhcmNoIiwiYXJncyI6WyJcXGQrIiwwXX1dfSwidGl0bGVfZGVmYXVsdCI6eyJzZWxlY3RvciI6ImFbaHJlZio9XCJkZXRhaWxzLnBocD9pZD1cIl0ifSwidGl0bGVfb3B0aW9uYWwiOnsib3B0aW9uYWwiOnRydWUsInNlbGVjdG9yIjoiYVt0aXRsZV1baHJlZio9XCJkZXRhaWxzLnBocD9pZD1cIl0iLCJhdHRyaWJ1dGUiOiJ0aXRsZSJ9LCJ0aXRsZSI6eyJ0ZXh0IjoieyUgaWYgZmllbGRzWyd0aXRsZV9vcHRpb25hbCddICV9e3sgZmllbGRzWyd0aXRsZV9vcHRpb25hbCddIH19eyUgZWxzZSAlfXt7IGZpZWxkc1sndGl0bGVfZGVmYXVsdCddIH19eyUgZW5kaWYgJX0ifSwiZGV0YWlscyI6eyJzZWxlY3RvciI6ImFbaHJlZio9XCJkZXRhaWxzLnBocD9pZD1cIl0iLCJhdHRyaWJ1dGUiOiJocmVmIn0sImRvd25sb2FkIjp7InNlbGVjdG9yIjoiYVtocmVmKj1cImRvd25sb2FkLnBocD9pZD1cIl0iLCJhdHRyaWJ1dGUiOiJocmVmIn0sImltZGJpZCI6eyJzZWxlY3RvciI6ImRpdi5pbWRiXzEwMCA+IGEiLCJhdHRyaWJ1dGUiOiJocmVmIiwiZmlsdGVycyI6W3sibmFtZSI6InJlX3NlYXJjaCIsImFyZ3MiOlsidHRcXGQrIiwwXX1dfSwiZGF0ZV9lbGFwc2VkIjp7InNlbGVjdG9yIjoidGQ6bnRoLWNoaWxkKDQpID4gc3BhbiIsIm9wdGlvbmFsIjp0cnVlfSwiZGF0ZV9hZGRlZCI6eyJzZWxlY3RvciI6InRkOm50aC1jaGlsZCg0KSA+IHNwYW4iLCJhdHRyaWJ1dGUiOiJ0aXRsZSIsIm9wdGlvbmFsIjp0cnVlfSwic2l6ZSI6eyJzZWxlY3RvciI6InRkOm50aC1jaGlsZCg1KSJ9LCJzZWVkZXJzIjp7InNlbGVjdG9yIjoidGQ6bnRoLWNoaWxkKDYpIn0sImxlZWNoZXJzIjp7InNlbGVjdG9yIjoidGQ6bnRoLWNoaWxkKDcpIn0sImdyYWJzIjp7InNlbGVjdG9yIjoidGQ6bnRoLWNoaWxkKDgpIn0sImRvd25sb2Fkdm9sdW1lZmFjdG9yIjp7ImNhc2UiOnsiaW1nLnByb19mcmVlIjowLCJpbWcucHJvX2ZyZWUydXAiOjAsImltZy5wcm9fNTBwY3Rkb3duIjowLjUsImltZy5wcm9fNTBwY3Rkb3duMnVwIjowLjUsImltZy5wcm9fMzBwY3Rkb3duIjowLjMsIioiOjF9fSwidXBsb2Fkdm9sdW1lZmFjdG9yIjp7ImNhc2UiOnsiaW1nLnByb181MHBjdGRvd24ydXAiOjIsImltZy5wcm9fZnJlZTJ1cCI6MiwiaW1nLnByb18ydXAiOjIsIioiOjF9fSwiZGVzY3JpcHRpb24iOnsic2VsZWN0b3IiOiJ0ZDpudGgtY2hpbGQoMikgPiB0YWJsZSA+IHRyID4gdGQuZW1iZWRkZWQgPiBzcGFuW3N0eWxlXSIsImNvbnRlbnRzIjotMX0sImxhYmVscyI6eyJzZWxlY3RvciI6InRkOm50aC1jaGlsZCgyKSA+IHRhYmxlID4gdHIgPiB0ZC5lbWJlZGRlZCA+IHNwYW4udGFncyJ9fX19
然后cc同步就添加进去了

**Comment by phantasyleo** [comment]
我加了，没用

**Comment by phantasyleo** [comment]
重新尝试，已成功，谢谢大佬
