### ISSUE TITLE
希望可以支持被动刷流

### ISSUE THREAD

**Issue by eagleandsanake** [jxxghp/MoviePilot#122]
### 当前程序版本

v1.0.0

### 功能改进

希望可以实现被动维护，也就是被动积累上传。如若从A站点下载了一个150G的资源，那么mp将在后台默默的积累150G上传

**Comment by JX0204** [comment]
只要你不删除 下载器不是会一直做种么，你要是删了MP也没办法帮你积累上传啊

**Comment by hbq0405** [comment]
> 只要你不删除 下载器不是会一直做种么，你要是删了MP也没办法帮你积累上传啊

他的意思，有些冷门资源无法提供上传流量又不能不下载，那就从别的热门资源找补回来这些损失的流量，这样可以把站点始终维持在一个健康的状态。

**Comment by eagleandsanake** [comment]
@hbq0405 对，我的意思就是不过度的取刷流，用多少则积累上传多少，位置站点的健康！自动下载免费的种子被动积累！

**Comment by LoSiTeE** [comment]
> @hbq0405 对，我的意思就是不过度的取刷流，用多少则积累上传多少，位置站点的健康！自动下载免费的种子被动积累！

被动刷流吗？感觉还是主动刷流自由度更高一点啊，被动刷流好像更复杂。
