### ISSUE TITLE
[错误报告]: synologyChat 推送通知错误

### ISSUE THREAD

**Issue by west-shih** [jxxghp/MoviePilot#1220]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.4.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我的是DSM7.2.1版本，synologyChat是2.4.1版本的。url配置为内网的, 但系统内置的消息通知报错。(如资源下载，入库整理)
![image](https://github.com/jxxghp/MoviePilot/assets/49203073/6a035de6-90e2-4ea7-9043-996abbf9eb59)

另外，签到插件, 站点数据统计的插件信息可以被推送。
![image](https://github.com/jxxghp/MoviePilot/assets/49203073/81ed7dab-206f-4ac5-8c55-6c81b30fa1a2)

**Comment by dwwl886** [comment]
SynologyChat返回错误：117-None
 我和你一样也是返回错误 我的是  Jellyfin 播放  停止 等信息错误

**Comment by github410117** [comment]
现在还是有这个问题，有解决了吗？
