### ISSUE TITLE
[错误报告]: 在指定整理目的目录时，不会判断二级分类开关了。

### ISSUE THREAD

**Issue by bcseputetto** [jxxghp/MoviePilot#1224]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

#1219 
之前我提了 指定目录时，不强制加一级分类名称，也就是不在指定目录后强制再加一次 LIBRARY_XX_NAME 这个变量
开发者修复了这个问题。
但似乎对指定目录时，不会去判断二级分类的开关了，导致指定目录后，二级分类可能失效。

对于指定目录是否加一级分类 LIBRARY_XX_NAME 这个也可以考虑加一个开关。
或者用户如果不填 `LIBRARY_MOVIE_NAME` `LIBRARY_TV_NAME` `LIBRARY_ANIME_NAME`
这三个变量，或者这三个设定为空时，不使用一级分类名称目录。而不是之前那样不填则使用默认值。这样就变相实现了一级分类开关。

`LIBRARY_PATH`:`/NAS/media`
`LIBRARY_TV_NAME`:`TV`
`LIBRARY_CATEGORY`:`true`
结果 /NAS/media/自定路径(如果有)/TV/国产剧
`LIBRARY_CATEGORY`:`false`
结果 /NAS/media/自定路径(如果有)/TV/
`LIBRARY_TV_NAME`:`为空或者不设`
`LIBRARY_CATEGORY`:`true`
结果 /NAS/media/自定路径(如果有)/国产剧
`LIBRARY_CATEGORY`:`false`
结果 /NAS/media/自定路径(如果有)/

**Comment by jxxghp** [comment]
@bcseputetto 如果要指定目录又要自动二级分类，就要配置多条分别指定到二级分类目录，并提前自己建好目录结构

**Comment by mmzy12** [comment]
> @bcseputetto 不能要指定目录又要自动二级分类，这个场景配置多条，分别指定到二级分类目录，并提前自己建好目录结构

大大！他的意思需要自自定义指定路径后还需要开启自动2级分类功能。建议增加个开关2级功能参数到里面，给需要自定义路径的人2级功能继续打开此功能，不需要的人关闭就好了！

**Comment by bcseputetto** [comment]
主要是为了和 nastool 的目录监控，手动识别，以及二级分类功能 一样
如果开启二级分类，目录监控里指定目的目录和手动识别指定目的目录，就会根据二级分类开关(MP多个一级分类)多加一层路径。
现在只要指定目录，就不会判断开关。

**Comment by bcseputetto** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/29139573/627e740b-6909-4857-82c6-ca163714fad1)
在nastool上，开启二级分类
![image](https://github.com/jxxghp/MoviePilot/assets/29139573/522aaf65-75fb-4648-bbb4-4864014c223a)
设置目录同步。(这个目录同步的路径是完全自定义)
![image](https://github.com/jxxghp/MoviePilot/assets/29139573/7dbdf1fe-b2b3-4ca4-b24a-4528772899cf)
手动识别(自定义路径)
![image](https://github.com/jxxghp/MoviePilot/assets/29139573/2583cb75-fe1d-4803-b16c-a3abf494813d)

![image](https://github.com/jxxghp/MoviePilot/assets/29139573/fe8b13c6-677f-4dd7-b92b-ab6175196bfc)


像这样，目录同步，手动识别，都会因为二级分类开关，使用自定路径也可以进行二级分类，关闭二级分类开关则就不会进行二级分类。
现在来到MP，就是变成了两个分类，一个是一级大类`电影``电视剧``动漫`，然后二级分类`华语电影``外语电影``国产剧``海外剧`等。这两个希望都能跟nastool 一样，就算自定路径也能根据开关判断是否添加
