### ISSUE TITLE
[错误报告]: 一级分类二级分类文件夹没有按预期被创建

### ISSUE THREAD

**Issue by surjur** [jxxghp/MoviePilot#1231]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

不指定目录时，一级分类二级分类文件夹没有按预期被创建
指定目录时，二级分类文件夹没有按预期被创建。

![telegram-cloud-photo-size-5-6323356071183366627-y](https://github.com/jxxghp/MoviePilot/assets/7477889/1db0c1aa-3b33-400b-8bd2-ac78ee0b21a9)
![telegram-cloud-photo-size-5-6323356071183366628-y](https://github.com/jxxghp/MoviePilot/assets/7477889/6dc7ae82-3b6b-4ef6-b288-d53c7cc0c823)
![telegram-cloud-photo-size-5-6323356071183366638-x](https://github.com/jxxghp/MoviePilot/assets/7477889/6ef9c1c1-8e78-4957-8bb3-07d4ffc83b5e)
![telegram-cloud-photo-size-5-6323104424754526672-m](https://github.com/jxxghp/MoviePilot/assets/7477889/53460c29-7b5c-43bd-a2f3-9207709f6cbe)
![telegram-cloud-photo-size-5-6323104424754526684-x](https://github.com/jxxghp/MoviePilot/assets/7477889/420fdd72-0703-4815-9a10-786f26fbe05b)
![telegram-cloud-photo-size-5-6323104424754526685-x](https://github.com/jxxghp/MoviePilot/assets/7477889/bf6a30eb-7e66-40d2-a4e5-5b9cbfad6654)
![telegram-cloud-photo-size-5-6323104424754526687-x](https://github.com/jxxghp/MoviePilot/assets/7477889/6b3fe26b-40dc-47e0-a7f5-d7888b2d49f7)

**Comment by surjur** [comment]
容器目录映射图
![image](https://github.com/jxxghp/MoviePilot/assets/7477889/041b5a6b-7db9-4411-8dfd-e4271adbfb46)

**Comment by xiaobaiwaf** [comment]
二级分类这个文件很容易加载不到，希望能改善以下
