### ISSUE TITLE
[错误报告]: 反代以后新增用户错误，

### ISSUE THREAD

**Issue by jian263994241** [jxxghp/MoviePilot#1232]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5/

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="452" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/2673531/a84c05f2-82a6-4339-b170-8c32f18d6731">

打开devtool可以带到， 新增用户那一步api请求url异常

**Comment by jian263994241** [comment]
具体接口： https://127.0.0.1:13001/api/v1/user/

**Comment by jxxghp** [comment]
无法重现

**Comment by faithleysath** [comment]
同样有这个问题，100%稳定复现。

补充信息：用的群晖的反代，未添加任何请求头。

**Comment by lm93129** [comment]
NGINX配置文件，需要修改proxy_set_header为`Host $host:$server_port;`
否则可能会因为带入的请求头只包含域名，不包含端口，导致307重定向的时候，丢失端口

> 同样有这个问题，100%稳定复现。
> 
> 补充信息：用的群晖的反代，未添加任何请求头。
