### ISSUE TITLE
[错误报告]:下载二级分类始终不生效

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot#1241]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载的二级分类始终不生效，只能推送标签
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/c4e3ab15-490e-4ee9-ad5b-7a3cf69a8e4c)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/09f806ec-f621-44a2-ad33-5fcb6fe34c7e)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/99eb03e4-3053-4823-a652-15c7b83771ca)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/cb1d7fa7-00dc-43b5-bcf7-8342ad875c09)

**Comment by xiaobaiwaf** [comment]
已解决，PUID.PGID给0

**Comment by cng10001** [comment]
请问 ，开了二级分类实际的下载路径，就算download_tv_path  download_movie_path  download_anime_path这些设置了，但也没有关系了，是取决于qbittorrent里的保存路径的？
