### ISSUE TITLE
[错误报告]: ERROR:   scheduler.py  无法整理下载器下载的文件

### ISSUE THREAD

**Issue by mildnes** [jxxghp/MoviePilot#1242]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.5.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

```ERROR:   scheduler.py - 定时任务 transfer 执行失败：'动漫' is not a valid MediaType```
这个是运行下载器整理时候出现的错误。
使用的系统是unraid，在每一个磁盘里面都有对应的目录。
二级分类已经开启，二级分类的配置使用的是默认的

### 发生问题时系统日志和配置文件

```bash
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 获取到 382 个已完成的下载任务
ERROR:   scheduler.py - 定时任务 transfer 执行失败：'动漫' is not a valid MediaType
INFO:     10.10.10.3:0 - "GET /api/v1/system/runscheduler?jobid=transfer HTTP/1.1" 200 OK
INFO:     10.10.10.3:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
```

**Comment by mildnes** [comment]
自己搞定了，把数据库systemconfig表中的目录同步插件的数据删除就好了

**Comment by mildnes** [comment]
自己搞定了，把数据库里面downloadhis里面动漫分类全部删除了就好了。不知道哪里的数据读取，把动漫全部type变成了动漫，不是电视剧。

**Comment by Sajotim** [comment]
> 自己搞定了，把数据库里面downloadhis里面动漫分类全部删除了就好了。不知道哪里的数据读取，把动漫全部type变成了动漫，不是电视剧。

大佬打扰了，想问下怎么删除downloadhistory里的动漫分类呢？
