### ISSUE TITLE
[错误报告]: 搜索适配不准确 出现搜索不到的情况

### ISSUE THREAD

**Issue by felix-klk** [jxxghp/MoviePilot#1246]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.5.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索适配不准确 出现搜索不到的情况 同样的名字 nastool可以搜索到 mp就不行  删除两个字又可以适配到
<img width="921" alt="Snipaste_2023-12-14_15-57-17" src="https://github.com/jxxghp/MoviePilot/assets/52670643/b0ef90bc-094d-46ae-8c17-dba8d893654f">
<img width="1130" alt="Snipaste_2023-12-14_15-57-33" src="https://github.com/jxxghp/MoviePilot/assets/52670643/34b0cd38-a590-4790-935d-96b6edeeee50">
<img width="873" alt="Snipaste_2023-12-14_15-58-42" src="https://github.com/jxxghp/MoviePilot/assets/52670643/2d71d23a-084a-4439-94c2-a6bc3fbe5214">

**Comment by felix-klk** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/52670643/13a46727-0d60-49ba-a469-875e4e157d3a)
b'z不知道发生了什么现在又可以了

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/39a84c6d-1aff-4e51-9383-da9be04d21ee)
