### ISSUE TITLE
[Feature Request]: Plex拼音索引，加强汉化插件

### ISSUE THREAD

**Issue by Numb-S** [jxxghp/MoviePilot#1252]
### 当前程序版本

v1.5.1-1

### 运行环境

群晖套件

### 功能改进类型

插件

### 功能改进

有作者开发了PLEX 中文本地化项目，但每次需要交互运行，希望加入插件库，后台定时自动运行。
这个脚本主要有三个功能：
> 1.         实现电影及电视剧类型的媒体库按标题拼音首字母排序，并支持按标题拼音缩写搜索。
> 2.         实现电影类型的媒体库类别标签汉化。
> 3.         实现电视剧类型的媒体库类别标签汉化。
> 4.         实现音乐库的媒体库类别标签汉化。

项目地址：

> [https://github.com/sqkkyzx/plex_localization_zhcn](url)

**Comment by InfinityPacer** [comment]
已加个人插件库
