### ISSUE TITLE
[错误报告]: 无法连接transmission

### ISSUE THREAD

**Issue by yangtao521** [jxxghp/MoviePilot#1258]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

无法连接transmission，transmission为群晖套件版，版本>=3.0.0

### 发生问题时系统日志和配置文件

```bash
ERROR:   transmission.py - transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.0.110:9091/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f9588722f10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
```

**Comment by it985** [comment]
watching，等一手解释

**Comment by yangtao521** [comment]
发现问题了 地址不能加http前缀

**Comment by lili890527** [comment]
同样的问题，各种地址都试过了，不行。加不加http都试过了

**Comment by Yinghai75** [comment]
同样问题，死活连不上，只是输了IP:9091；
连QB就没问题，输的IP:6363
Transmission 4.05
Moviepilot 1.8.5
都是 Docker

**Comment by Yinghai75** [comment]
我的出错提示比较简单：

transmission.py | transmission 连接出错：timeout when connection to transmission daemon
