### ISSUE TITLE
[错误报告]: ffmpeg生成缩略图生成失败！

### ISSUE THREAD

**Issue by dwwl886** [jxxghp/MoviePilot#1259]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.5.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="1012" alt="微信图片_20231218011148" src="https://github.com/jxxghp/MoviePilot/assets/41872694/ada2516d-a680-4a1c-bbb6-05d4567c8c75">
docker  里面显示已经安装ffmpeg  插件生产缩略图还是 失败

### 发生问题时系统日志和配置文件

```bash
WARNING	01:05:14,936	
ffmpegthumb
/Download/video/国产剧/故乡别来无恙 (2023)/Season 1/故乡别来无恙 - S01E07 - 第7集.mp4 缩略图生成失败！
```

**Comment by jxxghp** [comment]
使用官方docker镜像自带ffmpeg经测试没有问题

**Comment by dwwl886** [comment]
我安装的核实后确实是官方的版本，出现这种情况 应该如何排查那 ？ 我之前也重新安装过，结果还是一样。
