### ISSUE TITLE
[Feature Request]: 建议增加手动整理功能

### ISSUE THREAD

**Issue by zraxx** [jxxghp/MoviePilot#126]
### 当前程序版本

1.0

### 功能改进

建议增加手动整理功能，谢谢！！！！

**Comment by samyang211** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/14155364/1aeb184a-ac3d-4451-889a-8fc829bf654a)
是不是这个？  如果是的是NT之前的文件管理手动整理，那个确实挺好用

**Comment by zraxx** [comment]
不是，老版本手动整理功能

**Comment by ThierryCheng** [comment]
> ![image](https://user-images.githubusercontent.com/14155364/260924130-1aeb184a-ac3d-4451-889a-8fc829bf654a.png) 是不是这个？ 如果是的是NT之前的文件管理手动整理，那个确实挺好用

NT的手动整理逻辑是自动匹配的媒体信息如果出错了，可以手动进行搜索和选择正确的那个
不是这个的，这个只是说重新整理一遍，还是有继续出错的可能
