### ISSUE TITLE
[错误报告]: 无法正确整理原盘电影分盘的情况

### ISSUE THREAD

**Issue by 434451580** [jxxghp/MoviePilot#1261]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

原始电影目录结构如下
![screenshot-20231218-161456](https://github.com/jxxghp/MoviePilot/assets/41474859/cd161ad9-d671-4d5e-a4df-424dd8997ab1)

整理之后无法正确识别文件大小
![screenshot-20231218-161118](https://github.com/jxxghp/MoviePilot/assets/41474859/cf6784ae-63b1-41ee-861a-34b6c3b60e9f)

并且只有disc1 的文件大小，
![screenshot-20231218-162555](https://github.com/jxxghp/MoviePilot/assets/41474859/fa6f23db-4233-4292-81e5-fdeb2868788f)

猜测是，整理时识别了目录，并创建了硬链接，当整理到disc2的时候被误判为已存在； 

部分日志
![20231218-162314](https://github.com/jxxghp/MoviePilot/assets/41474859/cddc3a58-d287-4bf6-b730-f3025bd36adb)

**Comment by 434451580** [comment]
猜测是，整理时识别了目录，并创建了硬链接，当整理到disc2的时候被误判为已存在；

**Comment by jxxghp** [comment]
不支持
