### ISSUE TITLE
[错误报告]: app.env添加插件仓库链接后插件列表没有新插件

### ISSUE THREAD

**Issue by summer0607** [jxxghp/MoviePilot#1269]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.3

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

本人非常需要https://github.com/thsrite/MoviePilot-Plugins该插件库里的插件，按照官方说明文档，在app.env文件里添加了“PLUGIN_MARKET="https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://github.com/thsrite/MoviePilot-Plugins/”后重启容器，发现插件市场内并没有新增容器
先后进行了如下尝试：
1.修改host，添加github.com优选节点
2.挂代理
3.将app.env单独修改为PLUGIN_MARKET=“https://github.com/thsrite/MoviePilot-Plugins/”
因对代码和软件知识的匮乏，只能做以上尝试并且每一次尝试均重启了容器了，依然无法获取到该插件库的插件，求大佬帮助，非常需要！

**Comment by mjsoftking** [comment]
[http.zip](https://github.com/jxxghp/MoviePilot/files/13725736/http.zip)
下载解压后尝试按下图方式映射
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/e949cf43-364e-41cf-8b93-a3bd9d055d64)

`/app/app/utils/http.py`

估计就是网络访问的问题，这个文件使用了代理

**Comment by ZACKLZ** [comment]
> [http.zip](https://github.com/jxxghp/MoviePilot/files/13725736/http.zip) 下载解压后尝试按图方式映射 ![图像](https://private-user-images.githubusercontent.com/23021469/291852587-e949cf43-364e-41cf-8b93-a3bd9d055d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODU0MjAsIm5iZiI6MTcwNjE4NTEyMCwicGF0aCI6Ii8yMzAyMTQ2OS8yOTE4NTI1ODctZTk0OWNmNDMtMzY0ZS00MWNmLThiOTMtYTNiZDlkMDU1ZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODFmYzYzOWQzNDAyOTg3YTIwYmY3M2RhN2Y2MGFmZDZhNzYwYjY0MGI3Yjg2YWI2ZmVlZTY0ZGIyMzI0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AkrM5ZGNx-c5OcFwirHxK7ZbnaXUfoEin46cfpv2_90)
> 
> `/app/app/utils/http.py`
> 
> 估计就是网络访问的问题，这个文件使用了代理 可以试试，我就这么用的好使，不知道你行不行，如果不行删除这个文件映射即可还原原代码

感谢大佬，不过还是时不时无法更新插件，只有让nas全局代理，才能丝滑下载和更新插件····

**Comment by ZACKLZ** [comment]
新版本别再映射这个文件了，会出问题，我才从坑里出来= =
