### ISSUE TITLE
[错误报告]:日志报错ERROR: Pipe to stdout was broken，然后插件自动重载

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#1273]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

日志不定时报错后，所有插件自动重载。

### 发生问题时系统日志和配置文件

```bash
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
INFO:    pluginautoupdate - 插件 同步CookieCloud 更新成功，最新版本 1.1
INFO:    pluginautoupdate - 开始插件重载
INFO:    plugin.py - Plugin Loaded：AutoSignIn
INFO:    plugin.py - Plugin Loaded：CustomSites
INFO:    plugin.py - Plugin Loaded：SiteStatistic
INFO:    plugin.py - Plugin Loaded：SiteUnreadMsg
INFO:    plugin.py - Plugin Loaded：SiteRefresh
INFO:    plugin.py - Plugin Loaded：DoubanSync
```

**Comment by thsrite** [comment]
自动安装三方插件依赖有问题

进入mp容器手动安装插件依赖吧。pip install PyCookieCloud

可以打开数据库，systemconfig表，installplugin的value里删掉synccookiecloud或者pluginautoupdate
