### ISSUE TITLE
[Feature Request]: 提供服务 BASE_URL 的配置

### ISSUE THREAD

**Issue by GmwEnterprise** [jxxghp/MoviePilot#1277]
### 当前程序版本

1.5.4

### 运行环境

Docker

### 功能改进类型

其他

### 功能改进

期望作者大大提供一下服务 BASE_URL 的配置，我目前无法通过 `http://域名/moviepilot` 的反向代理方式来访问（也许是我没找到怎么配置捏） (●'◡'●)

**Comment by ptninja** [comment]
请问这个功能如何配置？code 里查了一遍似乎没有找打，也不在 `ConfigModel` 里。
