### ISSUE TITLE
 后端下载失败，继续使用旧的程序来启动

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#128]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0

### 问题类型

主程序运行问题

### 问题描述

可以正常连接网络，但“ 后端下载失败，继续使用旧的程序来启动”

### 发生问题时系统日志和配置文件

```bash
2023-08-15 21:51:03 发现新版本，开始更新程序...
2023-08-15 21:51:09 Archive:  -
2023-08-15 21:51:09 后端下载失败，继续使用旧的程序来启动...
```

**Comment by tardlk** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/37508088/c54eb01f-c740-43da-acc8-5e8e95c115a6)
相同问题

**Comment by DDSDerek** [comment]
网络问题。正常来说现在不可能会出现版本更新的提示
