### ISSUE TITLE
[错误报告]: 刮削的集图片名称缺少videoCodec

### ISSUE THREAD

**Issue by zhuweitung** [jxxghp/MoviePilot#1285]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

目录监控自动转移或者手动执行媒体库刮削插件进行刮削后，剧集中的集图片名称与视频文件名称以及nfo文件名称不一致
![image](https://github.com/jxxghp/MoviePilot/assets/20264596/4ca4816a-e9f9-4fd9-a1d5-7eafd250b6e1)
导致在emby中无法正确显示集图片
![image](https://github.com/jxxghp/MoviePilot/assets/20264596/92d98bfc-d6ed-43e0-9631-011c1102dda0)

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-12-27 20:24:46,851 - tmdbapi.py - 正在查询TMDB电视剧：240880 ...
【INFO】2023-12-27 20:24:48,012 - tmdbapi.py - 240880 查询结果：鸣龙少年
【INFO】2023-12-27 20:24:48,013 - themoviedb - 240880 TMDB识别结果：电视剧 鸣龙少年 (2023)
【INFO】2023-12-27 20:24:48,233 - tmdbapi.py - 正在获取剧集组年份：658501bc223e2041109507a1...
【INFO】2023-12-27 20:24:48,234 - themoviedb - 开始刮削媒体库文件：/video/emby/tv/鸣龙少年 (2023)/Season 1/鸣龙少年.S01E16.2160p.H265.mp4 ...
【INFO】2023-12-27 20:24:48,238 - tmdbapi.py - 正在查询TMDB电视剧：240880，季：1 ...
【INFO】2023-12-27 20:24:49,450 - scraper.py - 正在下载鸣龙少年.S01E16.2160p图片：https://image.tmdb.org/t/p/original/rPn7VYF0DevP5CVaWSxT9NbQqxb.jpg ...
【INFO】2023-12-27 20:24:51,463 - scraper.py - 图片已保存：/video/emby/tv/鸣龙少年 (2023)/Season 1/鸣龙少年.S01E16.2160p.jpg
【INFO】2023-12-27 20:24:51,464 - themoviedb - /video/emby/tv/鸣龙少年 (2023)/Season 1/鸣龙少年.S01E16.2160p.H265.mp4 刮削完成
```

**Comment by linxc-0515** [comment]
.的问题，换成其他符号就行了，但是1.4.9之前好像是可以的

**Comment by zhuweitung** [comment]
> .的问题，换成其他符号就行了，但是1.4.9之前好像是可以的

是哪个.有问题，之前几个版本刮削的时候确实没出现过这种情况

**Comment by linxc-0515** [comment]
> > .的问题，换成其他符号就行了，但是1.4.9之前好像是可以的
> 
> 是哪个.有问题，之前几个版本刮削的时候确实没出现过这种情况

2160p.H265 中的这个，我之前也这样命名的

**Comment by zhuweitung** [comment]
> > > .的问题，换成其他符号就行了，但是1.4.9之前好像是可以的
> > 
> > 
> > 是哪个.有问题，之前几个版本刮削的时候确实没出现过这种情况
> 
> 2160p.H265 中的这个，我之前也这样命名的

那只能先把剧集命名格式改了
