### ISSUE TITLE
希望将下载目录设置进行变量区分，不要强制一致

### ISSUE THREAD

**Issue by Tsenghan** [jxxghp/MoviePilot#1288]
### 当前程序版本

1.5.4

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移，会提示找不到文件。

现在遇到无法转移的问题，因为qb在windows下用的路径名称是windows的，而容器监控下载器的路径只能设置为挂载的路径。
希望可以将两个路径区分开来，如:
download_ture_path （传递给下载器的真实路径）
download_monit_path (下载目录转移用的路径)
然后在设置项中，通过
download_ture_path:download_monit_path的方式进行映射

### 参考资料

nt的实现方式就能很好的满足这一需求

**Comment by mjsoftking** [comment]
考虑使用目录监控试试

**Comment by Tsenghan** [comment]
> 考虑使用目录监控试试

使用监控 入库没问题，同步删种还是有问题

**Comment by mjsoftking** [comment]
> > 考虑使用目录监控试试
> 
> 使用监控 入库没问题，同步删种还是有问题

是媒体删除还是自动删种
媒体删除，我是这样配置的，媒体路径是媒体库的实际路径，MP路径就是创建硬连接的实际文件路径
https://github.com/jxxghp/MoviePilot/issues/1288#issuecomment-1873426600

**Comment by mjsoftking** [comment]
> > > 考虑使用目录监控试试
> > 
> > 
> > 使用监控 入库没问题，同步删种还是有问题
> 
> 是媒体删除还是自动删种 媒体删除，我是这样配置的，媒体路径是媒体库的实际路径，MP路径就是硬连接到的实际文件路径 [#1288 (comment)](https://github.com/jxxghp/MoviePilot/issues/1288#issuecomment-1873426600)

**Comment by Tsenghan** [comment]
> > > 考虑使用目录监控试试
> > 
> > 使用监控 入库没问题，同步删种还是有问题
> 
> 是媒体删除还是自动删种
> 媒体删除，我是这样配置的，媒体路径是媒体库的实际路径，MP路径就是硬连接到的实际文件路径
> ![image](https://github.com/jxxghp/MoviePilot/assets/23021469/1f5c2b5b-1bb4-4efe-97ec-0647af39d580)
> 

自动删种。就是联动删除下载器的任务，你咋操作的

**Comment by mjsoftking** [comment]
@Tsenghan 
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/5f8d223c-090c-43ef-ae16-b6742bb42d56)
我用的TR检测文件丢失错误的种子，由于一直启动就不检测，所以我的NAS每周定时重启一次，然后就会检测到文件丢失，再然后就都删除掉了

**Comment by Tsenghan** [comment]
@mjsoftking 谢谢，这个思路不错。我用的是qb，也不重启，主要不知道丢失文件了当启动的时候会不会不报错直接开始重新下载。。。。。
我试了重启qb，会正常报错丢失文件。应该可以满足需求。
还有请问你目录监控和自动删种插件的执行周期是如何设置的？可否参考一下。

**Comment by mjsoftking** [comment]
目录监控 不需要设置周期，若你认为存在未处理的影视，可以选择立即运行一次，手动进行全量扫描，非要自动每周每月每天一次都行，看你自己
自动删种插件，我设置的30分钟或者1小时也可以，无需太频繁，也不要太慢，我的是重启后30分钟内就会检测到。
媒体同步删除，我设置的30分钟，也是不需要太频繁的，一切看你自己，NAS性能够用可以适当快一些，但也没必要过于频繁

**Comment by Tsenghan** [comment]
> 目录监控 不需要设置周期，若你认为存在未处理的影视，可以选择立即运行一次，手动进行全量扫描，非要自动每周每月每天一次都行，看你自己
> 自动删种插件，我设置的30分钟或者1小时也可以，无需太频繁，也不要太慢，我的是重启后30分钟内就会检测到。
> 媒体同步删除，我设置的30分钟，也是不需要太频繁的，一切看你自己，NAS性能够用可以适当快一些，但也没必要过于频繁
> 

嗯主要是订阅更新他不能自动刷新，后续如果目录监控的触发器也能做到监听下载器结束事件自动触发就好了。
媒体同步删除我发现在历史记录里也可以同时删除源文件和硬连接，你使用插件，场景是什么，平时看完直接在jellyfin这类软件里删除吗？

**Comment by mjsoftking** [comment]
目录监控 监控的就是你设定的目录只要有视频进来就开始处理
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/f7912eff-29c4-47e8-ac1d-28a1f9df1453)
这是我的目录监控设置

删除的话我是jellyfin直接删掉，然后联动删除，最后重启的时候种子就都删除了，jellyfin使用的是日志方式，任何方式的删除都会导致媒体同步删除

**Comment by Tsenghan** [comment]
> 目录监控 监控的就是你设定的目录只要有视频进来就开始处理
> ![image](https://github.com/jxxghp/MoviePilot/assets/23021469/f7912eff-29c4-47e8-ac1d-28a1f9df1453)
> 这是我的目录监控设置
> 
> 删除的话我是jellyfin直接删掉，然后联动删除，最后重启的时候种子就都删除了，jellyfin使用的是日志方式，任何方式的删除都会导致媒体同步删除
> 

好，我按照你的设置也试一下，我前面是开了目录监控，但下载完成以后它好像没有自动启动文件转移和刮削，不知道是不是有延迟还是什么原因。我后面手动点了运行一次他就识别了，好像全量同步才可以。

**Comment by mjsoftking** [comment]
我这个可以正常扫描到，有就开始处理了，如果目录监控存在问题，建议你单独开一个关于目录监控的issue，并附件设备信息以供参考，等大佬看到的时候就会处理了。

当前如果非要全量处理，那就设置半小时或1小时左右的，视频越多同步间隔就尽量越长一些

**Comment by Tsenghan** [comment]
> 我这个可以正常扫描到，有就开始处理了，如果目录监控存在问题，建议你单独开一个关于目录监控的issue，并附件设备信息以供参考，等大佬看到的时候就会处理了。
> 
> 当前如果非要全量处理，那就设置半小时或1小时左右的，视频越多同步间隔就尽量越长一些

你配置文件中这个设置项是开着的还是没开？
```
# 下载器监控开关
DOWNLOADER_MONITOR='false'
```

**Comment by mjsoftking** [comment]
> > 我这个可以正常扫描到，有就开始处理了，如果目录监控存在问题，建议你单独开一个关于目录监控的issue，并附件设备信息以供参考，等大佬看到的时候就会处理了。
> > 当前如果非要全量处理，那就设置半小时或1小时左右的，视频越多同步间隔就尽量越长一些
> 
> 你配置文件中这个设置项是开着的还是没开？
> 
> ```
> # 下载器监控开关
> DOWNLOADER_MONITOR='false'
> ```

关闭的，下载器监控与目录监控开一个即可

**Comment by LiXianSebastian** [comment]
小心点,你们这样搞,在文件已经删除,而机器没有重启期间,qb或tr仍然显示在做种,这属于做假种,被举报会被联ban的

**Comment by LiXianSebastian** [comment]
> @Tsenghan ![image](https://private-user-images.githubusercontent.com/23021469/293676280-5f8d223c-090c-43ef-ae16-b6742bb42d56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODE3NTQsIm5iZiI6MTcwNDQ4MTQ1NCwicGF0aCI6Ii8yMzAyMTQ2OS8yOTM2NzYyODAtNWY4ZDIyM2MtMDkwYy00M2VmLWFlMTYtYjY3NDJiYjQyZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE5MDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNjE4MWE5ZDMzMGY4NDUxYjg0NWM4MmM1NTU1YzU0OGVhYmM1YjI0MjJhMWUzMTIyYWQzMDU4MGFmMWYyMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3wduHsKAeX1o67DnEI2A7MPCWzkXiHJRY-54n_cJipE) 我用的TR检测文件丢失错误的种子，由于一直启动就不检测，所以我的NAS每周定时重启一次，然后就会检测到文件丢失，再然后就都删除掉了

小心点,你们这样搞,在文件已经删除,而机器没有重启期间,qb或tr仍然显示在做种,这属于做假种,被举报会被联ban的

**Comment by mjsoftking** [comment]
@LiXianSebastian 一般也不会轻易删除，删除手动处理有遗漏的，这个只是兜底，辅种过多实在查不到的只能兜底了
