### ISSUE TITLE
[Feature Request]: 增加多下载器功能

### ISSUE THREAD

**Issue by qingahan** [jxxghp/MoviePilot#1297]
### 当前程序版本

1.5.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

大佬有考虑增加多下载器功能吗

**Comment by cng10001** [comment]
https://github.com/jxxghp/MoviePilot/issues/780
https://github.com/jxxghp/MoviePilot/issues/736
10月份的回复
