### ISSUE TITLE
[错误报告]: 织梦刷流的问题

### ISSUE THREAD

**Issue by iovejieba** [jxxghp/MoviePilot#1299]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.6

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

rss抓取种子貌似会报错，已经跑了3天测试了，基本都会提示qbittorrent 获取种子Hash失败

**Comment by jxxghp** [comment]
那是你QB的问题
