### ISSUE TITLE
[错误报告]:plex媒体库跳转错误401 Unauthorized 

### ISSUE THREAD

**Issue by ShiharaX** [jxxghp/MoviePilot#1316]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.7-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

plex媒体库跳转错误401 Unauthorized 
<img width="749" alt="捕获" src="https://github.com/jxxghp/MoviePilot/assets/61444826/0d6f0ef1-51a4-4cbb-8b5e-79625ec6afec">
<img width="937" alt="捕获1" src="https://github.com/jxxghp/MoviePilot/assets/61444826/3e0446f1-0992-42ae-b5e0-ae39dcd07308">

### 发生问题时系统日志和配置文件

```bash
# Plex服务器地址，IP:PORT
PLEX_HOST=127.0.0.1:32400
# Plex外网地址，http(s)://DOMAIN:PORT，未设置时使用PLEX_HOST
PLEX_PLAY_HOST=https://nas.zco.ltd:32400
```

**Comment by mizb** [comment]
一样的情况
