### ISSUE TITLE
[错误报告]: 开启代理 可以访问tg和tmdb，但是媒体库图片无法刷新出来

### ISSUE THREAD

**Issue by ShiharaX** [jxxghp/MoviePilot#1317]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.7-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

开启代理 可以访问tg和tmdb，但是媒体库图片无法刷新出来

**Comment by laobanbiefangcu** [comment]
不仅图片加载不出来，MP也是肉眼可见的卡顿，不知道怎么回退1.5.6版本

**Comment by faithleysath** [comment]
> 不仅图片加载不出来，MP也是肉眼可见的卡顿，不知道怎么回退1.5.6版本

是的，我也遇到了这个问题。mp运行数小时后开始异常卡顿，每打开一个页面都得转圈半天。
