### ISSUE TITLE
[错误报告]: 订阅搜索问题

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot#1324]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.7-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅搜索后日志里会显示错误
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/7c5fcb1f-7d8d-4a4c-a003-d00eb0f471b9)
好像不是自定义订阅插件的问题，是MP的问题，设置的时候间隔是30分钟，RSS模式，不知道是什么问题

**Comment by xiaobaiwaf** [comment]
并且及时搜索到资源也不会下载
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/1095b651-9ced-478a-9e9a-2939abb9bc1d)
执行到这里就结束了

**Comment by jxxghp** [comment]
无法重现，请检查运行的Python环境，是否自己有修改运行环境或代码？
