### ISSUE TITLE
演职人员中文刮削对 Plex 无法生效

### ISSUE THREAD

**Issue by GangplankWong** [jxxghp/MoviePilot#1325]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.7-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用插件商店的 “演职员中文刮削” 插件，日志中显示对于 Plex 的媒体库刮削都是成功的，但是登录 Plex 看的话演职员还是英文名称，尝试重启 Plex 和刷新元数据依旧未改变

### 发生问题时系统日志和配置文件

```bash
INFO	20:19:23,491	
personmeta
演职人员刮削服务启动，立即运行一次
20:19:26,492	
personmeta
开始刮削服务器 plex 的演员信息 ...
INFO	20:19:26,497	
personmeta
开始刮削媒体库 电影 的演员信息 ...
INFO	20:19:33,983	
personmeta
媒体库 电影 的演员信息刮削完成
INFO	20:19:33,984	
personmeta
开始刮削媒体库 动漫 的演员信息 ...
INFO	20:19:34,973	
personmeta
媒体库 动漫 的演员信息刮削完成
INFO	20:19:34,973	
personmeta
开始刮削媒体库 电视剧 的演员信息 ...
INFO	20:19:39,146	
personmeta
媒体库 电视剧 的演员信息刮削完成
INFO	20:19:39,146	
personmeta
服务器 plex 的演员信息刮削完成
```

**Comment by jxxghp** [comment]
去插件仓库提问题
