### ISSUE TITLE
[Feature Request]: fanart能否加入代理，或者自定义代理地址。自己用cf中转

### ISSUE THREAD

**Issue by mizb** [jxxghp/MoviePilot#1326]
### 当前程序版本

1.5.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![image](https://github.com/jxxghp/MoviePilot/assets/22237339/4fd28f24-0064-4855-a490-d1a950002583)
fanart一直无法链接，能否给个自定义代理的设置，自己套个cf来中转？

**Comment by yangtao521** [comment]
TMDB图片地址 要是也能走代理就好了 感觉有点慢

**Comment by mizb** [comment]
> TMDB图片地址 要是也能走代理就好了 感觉有点慢

可以啊，cloudflare work就行

**Comment by yangtao521** [comment]
> > TMDB图片地址 要是也能走代理就好了 感觉有点慢
> 
> 可以啊，cloudflare work就行

配了网络代理了，再配一个图片代理不是多余吗，直接走网络代理多好
