### ISSUE TITLE
[Feature Request]: 升级一下刷流插件，增加灵活性

### ISSUE THREAD

**Issue by lovesakuratears** [jxxghp/MoviePilot#1329]
### 当前程序版本

1.57

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

![IMG_0063(20240108-155635)](https://github.com/jxxghp/MoviePilot/assets/54654377/3a916478-afa6-43bd-83eb-f3cbcdbfc5c2)
粗略画了一个草图，对于，目前删种，选种条件比较局限，是否考虑配置页面部分选项升级成这种，可以方便自由搭配

**Comment by Travel2Here** [comment]
搭车问一个，有没有可能将刷流完成的下载任务，便捷的转成正式内容进行管理。
场景：
刷流进行了目录和标签隔离，设置了完成多少分享率或者时长达到多少就自动删任务了。
而有时候发现刷流的内容也感兴趣，想要留下。
就想能不能快速转正。多谢。

**Comment by lovesakuratears** [comment]
> 搭车问一个，有没有可能将刷流完成的下载任务，便捷的转成正式内容进行管理。 场景： 刷流进行了目录和标签隔离，设置了完成多少分享率或者时长达到多少就自动删任务了。 而有时候发现刷流的内容也感兴趣，想要留下。 就想能不能快速转正。多谢。

确实，能否利用刷流插件首页，给展示刷流的每个种子添加一个选项，直接刮削入库不受刷流规则影响
