### ISSUE TITLE
[Feature Request]: 新增类似于NT的同步目录插件

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/MoviePilot#133]
### 当前程序版本

1.0

### 功能改进

由于下载文件是在多个盘保存的，当前NT如果跨盘硬链复制文件时就会失败，再加上目前电影和电视剧等等都是分盘保存的，所以没有办法把library_path和download_path都映射在同一个盘下面。
之前NT的这个功能就很好可以完美解决这个问题，希望可以开发类似于NT的同步目录插件。这样就可以设置多个盘的多个路径分别进行硬链了。
<img width="737" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8851199/de925a3a-d9a2-4ad2-b751-c5ff32068c0e">

**Comment by xiaojie-jack** [comment]
+1

**Comment by Hiccup90** [comment]
有相同需求。+1

**Comment by ArthurSmoke** [comment]
相同需求
