### ISSUE TITLE
[错误报告]: 我的媒体库 手机端封面很不清晰

### ISSUE THREAD

**Issue by ShiharaX** [jxxghp/MoviePilot#1335]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

很模糊 切换到电脑端不放大还好，手机版是模糊的
![Screenshot_2024-01-10-00-07-18-699_com android chrome-edit](https://github.com/jxxghp/MoviePilot/assets/61444826/4fb66338-aa88-47d9-b6ae-0ed59482b5ae)

**Comment by jxxghp** [comment]
直接取的媒体服务器的图片，没有经过处理。

**Comment by ShiharaX** [comment]
好的
