### ISSUE TITLE
[错误报告]: 插件问题：目录监控插件监控CD2挂载的115网盘无反应

### ISSUE THREAD

**Issue by sunbroke555** [jxxghp/MoviePilot#1339]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.8

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

插件版本：1.5
目录监控插件配置：/115/CloudDrive/115/手动:/115/CloudDrive/115/video#move
监控模式：兼容模式
具体现象：
将文件加入/115/CloudDrive/115/手动文件夹后，查看日志无任何反应（之前版本是好的）。
moviepilot文件管理器内可以看到文件
![image](https://github.com/jxxghp/MoviePilot/assets/74763419/8e36f5cf-d420-4a0d-99e3-36f7c6c39c5b)

点击立即运行一次可以成功转移，仅监控失效。

### 发生问题时系统日志和配置文件

```bash
日志信息：
INFO	11:16:46,277	dirmonitor
/115/CloudDrive/115/手动 的目录监控服务启动

日志仅有此条成功监控信息，后续无任何相关日志或者报错信息
```

**Comment by jxxghp** [comment]
去插件仓库提问题，附上启动日志
