### ISSUE TITLE
[错误报告]: 转移覆盖模式选择latest(仅保留最新版本)未生效

### ISSUE THREAD

**Issue by z2561221** [jxxghp/MoviePilot#1347]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.5.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![photo_2024-01-11_10-00-22](https://github.com/jxxghp/MoviePilot/assets/30318614/f214b2ed-b946-45af-8416-dfdb925f78b9)

已选择'仅保留最新版本'，但媒体库旧版本未删除。

**Comment by jxxghp** [comment]
提供日志？

**Comment by z2561221** [comment]
> 提供日志？

<img width="1033" alt="PixPin_2024-01-11_21-18-08" src="https://github.com/jxxghp/MoviePilot/assets/30318614/99da49b1-b075-48a3-93ba-c00d7eabb590">
<img width="725" alt="PixPin_2024-01-11_21-19-13" src="https://github.com/jxxghp/MoviePilot/assets/30318614/d73fe6c6-b778-4744-bdf5-4992b9464fd0">

**Comment by Chen3167** [comment]
在最新版本v1.8.5-1又发现了这个问题，具体从哪个版本开始的不确定

日志：
INFO:    transfer.py - 手动转移：/media/downloads/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv ...
INFO:    themoviedb - Pegasus 2 使用TMDB识别缓存：飞驰人生2
INFO:    tmdbapi.py - 正在查询TMDB电影：1228891 ...
INFO:    tmdbapi.py - 1228891 查询结果：飞驰人生2
INFO:    themoviedb - Pegasus 2 TMDB识别结果：电影 飞驰人生2 (2024) 1228891
INFO:    media.py - 飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv 识别到媒体信息：电影 飞驰人生2 (2024)
WARNING: fanart - 没有获取到 飞驰人生2 (2024) 的fanart图片数据
INFO:    tmdbapi.py - 正在获取电影图片：1228891...
INFO:    transfer.py - 飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv 识别为：电影 飞驰人生2 (2024)
INFO:    filetransfer - 获取转移目标路径：/media/Movie
INFO:    filetransfer - 转移覆盖模式：latest，仅保留最新版本
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
INFO:    filetransfer - 正在转移文件：/media/downloads/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv 到 /media/Movie/飞驰人生2 (2024)/飞驰人生2 (2024).2160p.WEB-DL HDR.mkv
INFO:    filetransfer - 文件 /media/downloads/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv link完成
INFO:    filetransfer - 文件 /media/downloads/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv 转移成功
INFO:    themoviedb - 开始刮削媒体库文件：/media/Movie/飞驰人生2 (2024)/飞驰人生2 (2024).2160p.WEB-DL HDR.mkv ...
INFO:    scraper.py - 正在生成电影NFO文件：飞驰人生2 (2024).2160p.WEB-DL HDR.mkv
INFO:    scraper.py - NFO文件已保存：/media/Movie/飞驰人生2 (2024)/飞驰人生2 (2024).2160p.WEB-DL HDR.nfo
INFO:    themoviedb - /media/Movie/飞驰人生2 (2024)/飞驰人生2 (2024).2160p.WEB-DL HDR.mkv 刮削完成
INFO:    chain - 发送消息：channel=None，title=飞驰人生2 (2024)  已入库, text=评分：7.2，类型：电影，质量： WEB-DL HDR 2160p，共1个文件，大小：7.58G，userid=None
INFO:    command.py - 处理事件：notice.message - []
INFO:    transfer.py - /media/downloads/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb/飞驰人生2.Pegasus.2.2024.2160p.WEB-DL.H265.HDR.DDP5.1.Atmos-ADWeb.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
INFO:    command.py - 处理事件：transfer.complete - [<function FFmpegThumb.scan_rt at 0x7f335f617420>, <function MediaServerRefresh.refresh at 0x7f335f65f880>]
INFO:     172.21.0.4:0 - "POST /api/v1/transfer/manual?logid=24713&path=&target=%2Fmedia%2FMovie&type_name=&transfer_type=&episode_format=&episode_detail=&episode_part=&min_filesize=0 HTTP/1.1" 200 OK
INFO:    ffmpegthumb - FFmpeg缩略图处理文件：/media/Movie/飞驰人生2 (2024)/飞驰人生2 (2024).2160p.WEB-DL HDR.mkv
INFO:    mediaserverrefresh - 延迟 30 秒后刷新媒体库... 

<img width="1093" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/27947708/9c4e4a22-d530-41d1-bcca-374af8f4ff81">
