### ISSUE TITLE
[错误报告]: 升级到1.5.9以后，仪表盘的“最新观看”和“最近添加”无法正常显示，“我的媒体库”有图片

### ISSUE THREAD

**Issue by horseytr** [jxxghp/MoviePilot#1355]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

升级到1.5.9以后，仪表盘的“最新观看”和“最近添加”无法正常显示，“我的媒体库”有图片
1.5.8是正常显示的
<img width="2352" alt="iShot_2024-01-12_14 56 37" src="https://github.com/jxxghp/MoviePilot/assets/76861393/efd0ffa8-081b-4295-beeb-f0947b9eca2e">
<img width="1060" alt="iShot_2024-01-12_14 56 11" src="https://github.com/jxxghp/MoviePilot/assets/76861393/c0171089-2de3-44b5-8d0d-e9975f1a100c">

**Comment by horseytr** [comment]
检查了各种配置，查看emby和moviepilot的日志，都没问题
最终发现，1.5.9版本后只要emby影音库名称带有emoji，最近加入和继续观看都不会显示
汗流浃背😓

**Comment by thsrite** [comment]
@horseytr 重启dev更新，或者等下个release版本
