### ISSUE TITLE
[错误报告]: 1.5.9更新后，主页无法正常显示海报

### ISSUE THREAD

**Issue by Secular2020** [jxxghp/MoviePilot#1358]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新了 1.5.9后，主页我的媒体库、继续观看、最近添加无法正常显示海报，搜索资源可正常显示海报背景。

**Comment by autunn** [comment]
> 更新前1.5.8 一切正常，没有修改任何设置。

你也出现了同样的问题吗，我试过删除所有数据进行重装，还是不能解决这个问题，估计是这个版本的问题吧

**Comment by xyswordzoro** [comment]
更新dev，或者等下个版本，修复了

**Comment by ufocat000** [comment]
我也是，另外 在文件管理里，查不到本地硬盘数据。要退回到本地，一步步进去才能看到

**Comment by ufocat000** [comment]
WARNING: plugin.py - 获取插件库失败 https://github.com/jxxghp/MoviePilot-Plugins
ERROR:   plugin.py - 未获取到在线插件
这里测试网络联通性，是可以连上github

**Comment by lihouyu520** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 1.5.9
> 
> ### 运行环境
> Docker
> 
> ### 问题类型
> 主程序运行问题
> 
> ### 问题描述
> 更新了 1.5.9后，主页我的媒体库、继续观看、最近添加无法正常显示海报，搜索资源可正常显示海报背景。
> 
> ### 发生问题时系统日志和配置文件
> _No response_

在反向代理的代理目标勾选websocket即可。

**Comment by autunn** [comment]
> 在反向代理的代理目标勾选websocket即可正常访问

您是指在哪里勾选，软路由？还是什么地方，我没有在mp找到

**Comment by ufocat000** [comment]
无法显示海报大概1.58就开始了。另外我那个关于，软件版本一直都不显示， 已经通过认证而且是管理员登陆
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年1月14日 15:33
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [jxxghp/MoviePilot] [错误报告]: 1.5.9更新后，主页无法正常显示海报 (Issue #1358)
        
      
    
  


在反向代理的代理目标勾选websocket即可正常访问

您是指在哪里勾选，软路由？还是什么地方，我没有在mp找到

**Comment by autunn** [comment]
> 无法显示海报大概1.58就开始了。另外我那个关于，软件版本一直都不显示， 已经通过认证而且是管理员登陆
> […](#)
> ---- 回复的原邮件 ---- 发件人 ***@***.***> 发送日期 2024年1月14日 15:33 收件人 ***@***.***> 抄送人 ***@***.***> , ***@***.***> 主题 Re: [jxxghp/MoviePilot] [错误报告]: 1.5.9更新后，主页无法正常显示海报 (Issue #1358) 在反向代理的代理目标勾选websocket即可正常访问 您是指在哪里勾选，软路由？还是什么地方，我没有在mp找到 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

这是你自己的问题，1.5.8是正常的

**Comment by ufocat000** [comment]
是不是1.58我也不是记得太清楚，最近才有

**Comment by Aodi** [comment]
1.6.1版本还是存在这个问题

**Comment by Aodi** [comment]
我猜和这次的修改有关系，版本时间也对的上，不知道和反向代理有没有关系，反向代理之后的url解析错了？我的表现上，内网访问图片显示没问题，外网访问不显示。
![image](https://github.com/jxxghp/MoviePilot/assets/19473876/952fea47-e099-4486-9a80-a421a9971d73)

**Comment by JavaZeroo** [comment]
> 我猜和这次的修改有关系，版本时间也对的上，不知道和反向代理有没有关系，反向代理之后的url解析错了？我的表现上，内网访问图片显示没问题，外网访问不显示。 ![image](https://private-user-images.githubusercontent.com/19473876/301384861-952fea47-e099-4486-9a80-a421a9971d73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzczNTIsIm5iZiI6MTcwOTc3NzA1MiwicGF0aCI6Ii8xOTQ3Mzg3Ni8zMDEzODQ4NjEtOTUyZmVhNDctZTA5OS00NDg2LTlhODAtYTQyMWE5OTcxZDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAyMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTljZTU5N2QwMDhlOTI4MGM1Mzk2ZTViZWUxNGVlMDBkNmUwYmViYmY5YWY3MDgyZDg4YmUyYTk0NzYxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S9qigjm-YtOiHI_nJZVextAC9GuOUToaij_0FVIXzfQ)

1.7.0 仍然有这个问题
