### ISSUE TITLE
[Feature Request]: 提供刮削开关

### ISSUE THREAD

**Issue by tardlk** [jxxghp/MoviePilot#136]
### 当前程序版本

1.0.0

### 功能改进

目前moviepilot默认对整理的文件进行刮削，这会在媒体文件夹内刮削好海报及nfo,这对emby用户很友好，但对plex的刮削产生影响导致plex海报有时候会出现混乱，能否提供一个开关，仅对文件进行重命名， 而不刮削nfo及海报，感谢。

**Comment by jxxghp** [comment]
已经有了，请阅读文档
