### ISSUE TITLE
[错误报告]: CloudflareSpeedTest安装失败，内置代理下载报错

### ISSUE THREAD

**Issue by Mrxlei** [jxxghp/MoviePilot#1361]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

CloudflareSpeedTest安装失败,进入docker手动下载发现，是加内置代理无法下载，去掉内置代理可以下载，但是不知道应该放在什么位置，无法手动安装。

### 发生问题时系统日志和配置文件

```bash
14:44:31,264	
cloudflarespeedtest
检测到CloudflareSpeedTest有版本[v2.2.5]更新，开始安装
ERROR	14:44:31,377	
cloudflarespeedtest
CloudflareSpeedTest安装失败，无可用版本，停止运行

--2024-01-13 14:50:40--  https://ghproxy.com/https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
Resolving ghproxy.com (ghproxy.com)... 46.82.174.69, 8.7.198.46
Connecting to ghproxy.com (ghproxy.com)|46.82.174.69|:443... connected.
GnuTLS: Error in the pull function.
Unable to establish SSL connection.
```

**Comment by ufocat000** [comment]
v1.9.9 版本，这里还是这个问题，自己加个代理下载
