### ISSUE TITLE
[Feature Request]: 关于订阅功能的补充，跳转TMDB相关页面。

### ISSUE THREAD

**Issue by sunr1s6** [jxxghp/MoviePilot#1368]
### 当前程序版本

1.5.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

订阅功能如图所示，在以前的nastool的订阅功能里面 是有超链接 可以直接跳转到TMDB的。不知道为何把这个功能砍掉了， 希望作者能加上，最好是在MP内跳转，交互后名称去到搜索框进行搜索展示。如图2

![photo_2024-01-16_09-49-21](https://github.com/jxxghp/MoviePilot/assets/89040381/a7c5d2d1-fdb5-49a9-bf7f-284c0d7af679)

![photo_2024-01-16_09-54-09](https://github.com/jxxghp/MoviePilot/assets/89040381/fb2d9bcd-e409-4a54-9094-46d7ec30652d)

**Comment by jxxghp** [comment]
<img width="524" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/c90d9042-f81f-4b3b-a031-b9f8133bec24">


<img width="832" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/ea9b11e0-1430-4d37-9ffe-bc728c546863">
