### ISSUE TITLE
[Feature Request]: 提供nyaa镜像站功能

### ISSUE THREAD

**Issue by tardlk** [jxxghp/MoviePilot#137]
### 当前程序版本

1.0.0

### 功能改进

nyaa的网址国内目前无法打开，有一个镜像项目（网址：https://moonchan.xyz/site.html）提供nyaa的国内网址https://nyaa.moonchan.xyz/，我将此网址放在站点管理的nyaa的地址栏，但无法搜索资源，希望能提供更改为镜像站的功能。
![image](https://github.com/jxxghp/MoviePilot/assets/37508088/51033d3c-ed06-4842-bc08-865da4691666)

**Comment by samyang211** [comment]
这种很小众的需求，估计没精力支持，下面不是有代理功能么，搞个梯子吧

**Comment by yegetables** [comment]
动漫花园的镜像站 https://garden.breadio.wiki/ 速度很快,原站加了代理速度也一般,得模拟浏览器访问

**Comment by Aqr-K** [comment]
暂不做任何第三方镜像站地址适配，只对官方官网地址或官方分流地址接入。如果出现访问失败，请自行加代理或者寻找其他解决方法。
