### ISSUE TITLE
[错误报告]: 更新1.5.9后无法显示jellyfin媒体库中新添加及继续播放的内容

### ISSUE THREAD

**Issue by seeson** [jxxghp/MoviePilot#1373]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/12587456/bddb48ce-931e-431a-9e7a-ab074405d8bf)
开机时报错，无法查看jellyfin媒体库中播放和新添加的内容

**Comment by mjsoftking** [comment]
相同问题

**Comment by JVDormael** [comment]
相同问题

**Comment by MMAX5358** [comment]
-1的bug，退回1.5.9就好了

**Comment by Melody-Test** [comment]
同样的问题
