### ISSUE TITLE
[错误报告]: `正在下载`无法正确显示内容

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1376]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

通过MP执行下载任务后，可以在下载器中正常查看到下载任务，但是通过MP的`正在下载`显示是空

<img width="1301" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/282b9e56-03d5-4474-8f7d-07568363055e">
<img width="981" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/b32de428-9d43-4d76-9448-5e167c8379e2">
<img width="874" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/17a7ce42-522d-4f52-b911-8b7e43c6bdb8">

**Comment by Melody-Test** [comment]
一样的问题

**Comment by carolcoral** [comment]
> 我的是在管理员用户中可以正常显示，但是子用户里面看不到下载状态

@ToJ112 我只有一个管理员用户，没有别的用户

**Comment by carolcoral** [comment]
@jxxghp 大佬，这个问题已经修复了么，我更新到1.6.5还是存在这个问题

**Comment by jxxghp** [comment]
@carolcoral 我用QB没有问题，无法重现

**Comment by carolcoral** [comment]
> @carolcoral 我用QB没有问题，无法重现

我用的transmission 3

**Comment by fyu0h** [comment]
升级到transmission 4即可解决
