### ISSUE TITLE
[Feature Request]: 能否把搜索结果的样式改成和nastool那种呢

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1377]
### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前的MP的搜索结果样式感觉有点乱，能不能改成行展示，和原来的nastool那种，每条搜索结果可以独立一行展示，可以清晰的查看到`站点`、`大小`、`做种数`、`分辨率`、`免费2x`等信息

<img width="1415" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/5aa11bfc-33aa-47a9-a902-2c8050173a43">

<img width="1406" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/76015e1f-ff6b-424e-a727-71dc96960cad">

**Comment by GlowsSama** [comment]
MP的右下角可以切换显示样式

**Comment by carolcoral** [comment]
> MP的右下角可以切换显示样式

好的，感谢，没注意到🙏
