### ISSUE TITLE
在最新的1.5.9-1中，有以下报错，更新完版本后突然出现的

### ISSUE THREAD

**Issue by MMAX5358** [jxxghp/MoviePilot#1380]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

ERROR | 01:42:46,915 | jellyfin.py | 连接Users/Items/Resume出错：%i format: a real number is required, not str
-- | -- | -- | --
ERROR | 01:42:47,027 | jellyfin.py | 连接Users/Items/Latest出错：%i format: a real number is required, not str

**Comment by cng10001** [comment]
举手，我还寻思咋就我一个人有问题呢，想着我jellyfin也妹出问题啊，也就没有问。

**Comment by cng10001** [comment]
https://github.com/jxxghp/MoviePilot/issues/1373  原来前面还有人提过了
