### ISSUE TITLE
[错误报告]: 洗版功能报错

### ISSUE THREAD

**Issue by woocoder** [jxxghp/MoviePilot#1381]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

首次使用洗版插件，过程中发生报错，具体如图
![image](https://github.com/jxxghp/MoviePilot/assets/11451001/13a89876-1cab-4883-afcf-72ffc76d197b)

### 发生问题时系统日志和配置文件

```bash
ERROR:   base.py - Job "收藏洗版 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/30'], next run at: 2024-01-18 10:30:00 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/bestfilmversion/__init__.py", line 432, in sync
    tmdb_id = item_info_resp.tmdbid
```

**Comment by jxxghp** [comment]
日志不完整
