### ISSUE TITLE
iyuu消息通知报错，但是依然收到了通知

### ISSUE THREAD

**Issue by MMAX5358** [jxxghp/MoviePilot#1384]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

iyuu消息通知出现报错，提示通知失败，但其实收到了通知

### 发生问题时系统日志和配置文件

```bash
ERROR | 11:52:07,882 | iyuumsg | IYUU消息发送失败，Expecting value: line 1 column 1 (char 0)
```

**Comment by HR4912** [comment]
\app\plugins\iyuumsg\__init__.py, Line 176
`
sc_url = "http://iyuu.cn/%s.send?%s" % (self._token, urlencode({"text": title, "desp": text}))
res = RequestUtils().get_res(sc_url)
`
改为
`
sc_url = "http://iyuu.cn/%s.send?%s" % (self._token, urlencode({"text": title, "desp": text}))
res = RequestUtils().post_res(sc_url)
`
这样好像可以解决
