### ISSUE TITLE
[错误报告]: IYUU一直提示认证失败

### ISSUE THREAD

**Issue by mrxiaozuo** [jxxghp/MoviePilot#1387]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

之前IYUU认证一直都没有问题，更新了一下后启动一直报IYUU认证失败
环境配置如下
![QQ截图20240118211622](https://github.com/jxxghp/MoviePilot/assets/11365018/c2382494-5c25-4850-b7a5-e06578d38925)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-01-18 21:08:20,590 - migration.py - Context impl SQLiteImpl.
【INFO】2024-01-18 21:08:20,592 - migration.py - Will assume non-transactional DDL.
【INFO】2024-01-18 21:08:21,009 - singleton.py - 站点资源版本：1.0.9
【INFO】2024-01-18 21:08:21,018 - singleton.py - 认证资源版本：1.1.1
【ERROR】2024-01-18 21:08:21,065 - singleton.py - iyuu认证出错：无法连接站点
【ERROR】2024-01-18 21:08:21,066 - singleton.py - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
【INFO】2024-01-18 21:08:21,067 - resource.py - 开始检测资源包版本...
【INFO】2024-01-18 21:08:21,686 - resource.py - 最新资源包版本：v1.1.5
【INFO】2024-01-18 21:08:21,687 - resource.py - 所有资源已最新，无需更新
```

**Comment by mrxiaozuo** [comment]
好像是IYUU的认证域名挂了
https://api.iyuu.cn 无法访问
http://api.iyuu.cn 提示ICP未备案被拦截了。。。

**Comment by FLIER001** [comment]
> 好像是IYUU的认证域名挂了 https://api.iyuu.cn 无法访问 http://api.iyuu.cn 提示ICP未备案被拦截了。。。
没错，是IYUU的问题，目前还没回复，暂时可以使用别的途径认证

**Comment by Pazuzu5688** [comment]
> > 好像是IYUU的认证域名挂了 https://api.iyuu.cn 无法访问 http://api.iyuu.cn 提示ICP未备案被拦截了。。。
> 
> 没错，是IYUU的问题，目前还没恢复，暂时可以使用别的途径认证

請問還有什麼方式可以認證？

**Comment by AnubisYe** [comment]
https://gitee.com/ledc/iyuuplus 已经更新了新的链接http://hk.iyuu.cn，但moviePilot不知道怎么换 @jxxghp 可以自己配置iyuu链接吗

**Comment by Jacky-Bruse** [comment]
希望大佬更新iyuu,认证失败，谢谢

**Comment by arthurfsy2** [comment]
我也遇到类似的问题了，希望能修复

**Comment by a18ccms** [comment]
我重装了。也是这个问题。

**Comment by lishan148** [comment]
不能认证了，咋办

**Comment by yinshuai0324** [comment]
手机好几个站都不支持直接认证，iyuu域名好像因为备案暂时用不了。可不可以处理一下

**Comment by carolcoral** [comment]
这个域名问题好像还直接影响了IYUU自动辅种插件

**Comment by xuelei9300** [comment]
1.6.1修复了吗？ 我出现了类似的错误
`【INFO】2024-01-30 18:03:09,426 - migration.py - Context impl SQLiteImpl.
【INFO】2024-01-30 18:03:09,427 - migration.py - Will assume non-transactional DDL.
【INFO】2024-01-30 18:03:09,568 - singleton.py - 站点资源版本：1.0.9
【INFO】2024-01-30 18:03:09,571 - singleton.py - 认证资源版本：1.1.2
【ERROR】2024-01-30 18:03:09,978 - singleton.py - iyuu认证出错：非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/
【ERROR】2024-01-30 18:03:09,978 - singleton.py - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
【INFO】2024-01-30 18:03:09,979 - resource.py - 开始检测资源包版本...`

**Comment by WeiYang1982** [comment]
一样的问题
