### ISSUE TITLE
[错误报告]: 资源订阅存在资源但标题不匹配

### ISSUE THREAD

**Issue by jerrita** [jxxghp/MoviePilot#1389]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.5.9-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="973" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/28153001/14c27587-faff-4bab-b542-b7a2b844fc63">

类似这样，可以搜索到，但匹配不到，而且在资源搜索界面的制作组中也没有这个字幕组的信息。

<img width="308" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/28153001/c003f620-0443-4385-a4f0-7190f2a36bc1">

<img width="360" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/28153001/63019a95-39b5-4102-9fb2-988e0db4d507">

我在词表中按照上图添加并保存了这个字幕组，问题依旧，不知道是什么原因。

### 发生问题时系统日志和配置文件

```bash
INFO:    search.py - 开始匹配，总 4 个资源 ...
INFO:    search.py - 标题：憧憬成为魔法少女，原标题：魔法少女にあこがれて，别名：['梦想成为魔法少女', '憧憬成为魔法少女', '想要成为魔法少女', 'I Admire Magical Girls, and...', 'Mahou Shoujo ni Akogarete', 'Mahō Shōjo ni Akogarete', 'まほあこ', 'MahoAko', '憧憬成為魔法少女', 'Looking Up to Magical Girls', 'Gushing Over Magical Girls', 'Gushing over Magical Girls', '夢想成為魔法少女', '마법소녀를 동경해서', 'Looking up to Magical Girls', 'Захоплена дівчатами-чарівницями']
WARNING: search.py - MiKan - [Billion Meta Lab][憧憬成为魔法少女][03][1080p][HEVC-10bit][简繁内封][ADN].mkv 标题不匹配
WARNING: search.py - MiKan - [Billion Meta Lab][憧憬成为魔法少女][03][1080p][ADN][简体内嵌] 标题不匹配
WARNING: search.py - 动漫花园 - [Billion Meta Lab][憧憬成为魔法少女][03][1080p][HEVC-10bit][简繁内封][ADN] 标题不匹配
WARNING: search.py - 动漫花园 - [Billion Meta Lab][憧憬成为魔法少女][03][1080p][ADN][简体内嵌] 标题不匹配
INFO:    search.py - 匹配完成，共匹配到 0 个资源
WARNING: subscribe.py - 订阅 憧憬成为魔法少女 未搜索到资源
INFO:    subscribe.py - 憧憬成为魔法少女 (2024) 未下载完整，继续订阅 ...
INFO:    subscribe.py - 憧憬成为魔法少女 (2024) 季 1 更新缺失集数为12 ...
```

**Comment by Hcczz** [comment]
^[\W_](.*?(?:组|組|屋|社|動漫|Lab|sub|S(?:UB|ub|tudio)|Raw(?:|s)|Production))[\W_]+(?:[\W_]+\d{1,2}(?:月(?:新|)番|国漫)[\W_]+|)[\[【](.*?)[\]】] => [\1] \2

**Comment by cng10001** [comment]
[Billion Meta Lab]这个在前就是识别不了 - -
