### ISSUE TITLE
[错误报告]  杀毒软件报毒

### ISSUE THREAD

**Issue by Vstory** [jxxghp/MoviePilot#1390]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Windows

### 问题类型

其他问题

### 问题描述

最近下载amd版本时，基本都会出现这个报毒，请问这个是不是误报？

### 发生问题时系统日志和配置文件

```bash
病毒库时间：2024-01-18 18:30
开始时间：2024-01-19 12:22
总计用时：00:00:02
扫描对象：1
扫描文件：1
发现风险：1
已处理风险：1
病毒详情：
风险路径：C:\Users\XX\Downloads\MoviePilot_Amd64_v1.6.0, 病毒名：Backdoor/Python.ThorseRAT.b, 病毒ID：8bb30e94bc6c24ba, 处理结果：已处理，删除文件
```

**Comment by jxxghp** [comment]
因为存在nginx打包和解包操作，会被杀软识判为病毒，实际是通过GitHub actions云打包，是安全的。
如果不放心则不用windows版。
