### ISSUE TITLE
删除源文件增加同步删除下载器种子

### ISSUE THREAD

**Issue by 892899273** [jxxghp/MoviePilot#1391]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在历史记录中选择删除历史记录.源文件.媒体库文件，不会同步删除下载器种子文件

**Comment by tangyl2000** [comment]
对，可以删除源文件、历史记录、媒体库文件，但是qb中的做种任务还在
