### ISSUE TITLE
管理员修改密码，实际是重新创建一个子账户，并且不能删除

### ISSUE THREAD

**Issue by 55404** [jxxghp/MoviePilot#1392]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

安装比较早，管理员密码为环境创建，现在环境修改无效，进入MoviePilot-设定-用户，修改密码，实际是重新创建一个子账户，并且不能删除，设定-用户-下面的所有用户也不显示子账户，但是可以使用登录，一个管理员账户，2个密码并且都可以登录

**Comment by saltbo** [comment]
搞了半天居然是有这bug，我说我改完密码再登录上去就看不到设置页面了

**Comment by jxxghp** [comment]
重现不了

**Comment by vnijvet370** [comment]
我也出现这个问题，看了下登录代码的逻辑和日志才发现，本地用户名或密码不匹配，会尝试辅助认证，也就是会拿这个用户密码去配置好的Emby或者Jellyfin去校验，匹配成功会以普通用户登录
