### ISSUE TITLE
希望能增加认证轮询的功能，防止掉认证

### ISSUE THREAD

**Issue by wbhinspector** [jxxghp/MoviePilot#1397]
### 当前程序版本

1.6.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

有一个认证网站崩了，认证就失败了，能不能可以多配置几个认证信息，然后mp按配置信息轮询认证，直到有一个认证通过为止。

**Comment by jxxghp** [comment]
@wbhinspector 不看文档？

**Comment by carolcoral** [comment]
文档写的很清楚啊，可以配置多个
![image](https://github.com/jxxghp/MoviePilot/assets/8952687/f92cdbed-16ec-4ee3-9f03-fe8696c0e154)
