### ISSUE TITLE
微信或者TG搜索的时候返回结果能增加字幕和语言么

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#1398]
### 当前程序版本

1.6.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

- 不显示有无字幕和语言有时真的不好分辨，还望能加上。
- 再有就是能实现微信或者TG订阅就好了

**Comment by jxxghp** [comment]
@loveu5522 订阅xxx
