### ISSUE TITLE
[错误报告］刷流失败报错“qbittorrent 获取种子Hash失败”

### ISSUE THREAD

**Issue by demerzelxd** [jxxghp/MoviePilot#1400]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![IMG_20240121_203305_798](https://github.com/jxxghp/MoviePilot/assets/31914157/d9ea91af-850d-48e8-9e0c-dd00d0c7b203)
可以正常下载电影，但是刷流就是会报错，所有站点所有资源都报这个错，下面是插件配置：
![Screenshot_2024-01-21-20-38-41-406_com android browser](https://github.com/jxxghp/MoviePilot/assets/31914157/156903a1-5988-43e4-948b-f0561fb095fe)

**Comment by linglichao** [comment]
请问下这个怎么解决，遇到同样的问题

**Comment by love81003739** [comment]
遇到同样 的问题，有什么解决办法吗

**Comment by LoSiTeE** [comment]
我现在也是这种状态……不知道哪里出了问题。昨天还好好的，什么都没动就用不了了

**Comment by Tiksonli** [comment]
同样的站，同样的问题。

**Comment by jxxghp** [comment]
@Tiksonli 跟站点没关系，检查qb版本

**Comment by Tiksonli** [comment]
@jxxghp Qb版本是4.6.3-1，刷流是部分站有这个报错，部分站能正常刷流。

**Comment by love81003739** [comment]
我的找到原因了，是因为站点被限下载了，每次下载种子都要确认一下才行，你们试试手动下载种子，要不要点确认才能下

**Comment by CharisLee** [comment]
我也是添加了红豆后出现的问题
