### ISSUE TITLE
[错误报告]: 自动辅种插件执行失败，IYUU没有返回结果

### ISSUE THREAD

**Issue by SkySlity** [jxxghp/MoviePilot#1401]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

21:36:44,031 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息

u一直失败

**Comment by ZevAlain** [comment]
iyuu 挂了

**Comment by oynt** [comment]
iyuu恢复了，但是域名有变化。插件也要跟着跟新才行

**Comment by oynt** [comment]
> iyuu恢复了，但是域名有变化。插件也要跟着跟新才行

https://share.weiyun.com/rJL0dubA
下载这个文件到docker里替换后就可以正常使用了

**Comment by oynt** [comment]
还是希望插件作者来修改更新

**Comment by ZACKLZ** [comment]
这文件或是内容在哪里改呢？

**Comment by ZACKLZ** [comment]
我看映射目录里没有插件相关的内容，只有备份文件

**Comment by yangsheng1994** [comment]
> 我看映射目录里没有插件相关的内容，只有备份文件

同样不会修改 映射目录没看到同样的文件
![image](https://github.com/jxxghp/MoviePilot/assets/95394538/4639c2dd-e81c-4f7b-9f34-1226fcc9df22)

@oynt 能提示下怎样修改吗 谢谢

**Comment by EkkoG** [comment]
更新插件到 1.1 即可

**Comment by hh0610** [comment]
> 更新插件到 1.1 即可

<html>
<body>

开始辅种任务 ...
--
INFO | 18:19:25,366 | iyuuautoseed | 开始扫描下载器 transmission ...
INFO | 18:19:25,506 | iyuuautoseed | 下载器 transmission 已完成种子数：937
INFO | 18:19:25,507 | iyuuautoseed | 总共需要辅种的种子数：937
INFO | 18:19:25,507 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ...
WARNING | 18:19:25,566 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息
INFO | 18:19:25,567 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ...
WARNING | 18:19:25,638 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息
INFO | 18:19:25,638 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ...
WARNING | 18:19:25,687 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息
INFO | 18:19:25,688 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ...
WARNING | 18:19:25,756 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息
INFO | 18:19:25,756 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：137 ...
WARNING | 18:19:25,813 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息
INFO | 18:19:25,921 | iyuuautoseed | 辅种任务执行完成


</body>
</html>
一样不可以

**Comment by ZACKLZ** [comment]
感谢，我更新了，不过我发现只有让nas走代理才可以从github上更新插件，mp的代理好像不会给插件下载提供代理，同样discord消息推送也不能走mp环境变量配置的代理····希望啥时候能更新解决一下

**Comment by EkkoG** [comment]
> > 更新插件到 1.1 即可
> 
> 开始辅种任务 ... -- INFO | 18:19:25,366 | iyuuautoseed | 开始扫描下载器 transmission ... INFO | 18:19:25,506 | iyuuautoseed | 下载器 transmission 已完成种子数：937 INFO | 18:19:25,507 | iyuuautoseed | 总共需要辅种的种子数：937 INFO | 18:19:25,507 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,566 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,567 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,638 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,638 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,687 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,688 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,756 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,756 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：137 ... WARNING | 18:19:25,813 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,921 | iyuuautoseed | 辅种任务执行完成 一样不可以

@hh0610 浏览器访问一下 http://[hk.iyuu.cn](http://hk.iyuu.cn/)/ 看正不正常

**Comment by hh0610** [comment]
> > > 更新插件到 1.1 即可
> > 
> > 
> > 开始辅种任务 ... -- INFO | 18:19:25,366 | iyuuautoseed | 开始扫描下载器 transmission ... INFO | 18:19:25,506 | iyuuautoseed | 下载器 transmission 已完成种子数：937 INFO | 18:19:25,507 | iyuuautoseed | 总共需要辅种的种子数：937 INFO | 18:19:25,507 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,566 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,567 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,638 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,638 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,687 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,688 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：200 ... WARNING | 18:19:25,756 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,756 | iyuuautoseed | 下载器 transmission 开始查询辅种，数量：137 ... WARNING | 18:19:25,813 | iyuuautoseed | 当前种子列表没有可辅种的站点：请求IYUU失败，未获取到返回信息 INFO | 18:19:25,921 | iyuuautoseed | 辅种任务执行完成 一样不可以
> 
> @hh0610 浏览器访问一下 http://hk.iyuu.cn/ 看正不正常

不正常

**Comment by EkkoG** [comment]
用辅种插件 1.1 要保证访问 http://hk.iyuu.cn/  正常 @hh0610

**Comment by ZACKLZ** [comment]
> 用辅种插件 1.1 要保证访问 http://hk.iyuu.cn/ 正常 @hh0610

貌似被墙了，iyuu插件又不会走代理····

**Comment by EkkoG** [comment]
> > 用辅种插件 1.1 要保证访问 http://hk.iyuu.cn/ 正常 @hh0610
> 
> 貌似被墙了，iyuu插件又不会走代理····

![CleanShot 2024-01-26 at 13 09 46@2x](https://github.com/jxxghp/MoviePilot/assets/3138493/fc79cda9-6476-43e7-941d-859060654765)

应该是没有被墙的

**Comment by ThierryCheng** [comment]
> 更新插件到 1.1 即可

如何更新插件呢，插件库里面看iyuss还是1.0的呢

**Comment by EkkoG** [comment]
@ThierryCheng https://github.com/jxxghp/MoviePilot/issues/1401#issuecomment-1911308929

**Comment by SkySlity** [comment]
> 更新插件到 1.1 即可

升级后还是一样的问题，http://[hk.iyuu.cn](http://hk.iyuu.cn/)/ 也是访问正常

**Comment by yunzhongci** [comment]
我更新插件之后，重启一下容器再用就正常了
