### ISSUE TITLE
主页仪表盘jellyfin.py出现以下报错，在1.5.9无报错，1.6.0出现

### ISSUE THREAD

**Issue by MMAX5358** [jxxghp/MoviePilot#1404]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

主页仪表盘jellyfin.py出现以下报错，在1.5.9无报错，1.6.0出现

### 发生问题时系统日志和配置文件

```bash
ERROR	00:28:15,854	
jellyfin.py
Library/VirtualFolders/Query 未获取到返回数据
ERROR	00:28:16,969	
jellyfin.py
Library/VirtualFolders/Query 未获取到返回数据
```

**Comment by JVDormael** [comment]
也有相同的问题。

**Comment by tangyl2000** [comment]
同样的问题

**Comment by zzzqu** [comment]
+1

**Comment by Lobeu-m** [comment]
emby +1

**Comment by cng10001** [comment]
@jxxghp 大佬更新了1.6.6版本，这个报错还是有哎
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/b99b40d0-ff3c-471d-acf5-aea042c33d91)

**Comment by jxxghp** [comment]
> @jxxghp 大佬更新了1.6.6版本，这个报错还是有哎
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/115156545/b99b40d0-ff3c-471d-acf5-aea042c33d91)
> 
> 

jellyfin能连上吗，媒体统计是否能显示？

**Comment by cng10001** [comment]
> > @jxxghp 大佬更新了1.6.6版本，这个报错还是有哎
> > ![image](https://private-user-images.githubusercontent.com/115156545/306533509-b99b40d0-ff3c-471d-acf5-aea042c33d91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDIyODIsIm5iZiI6MTcwODUwMTk4MiwicGF0aCI6Ii8xMTUxNTY1NDUvMzA2NTMzNTA5LWI5OWI0MGQwLWZmM2MtNDcxZC1hY2Y1LWFlYTA0MmMzM2Q5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNzUzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTViMDgwZWU2ODZkMzc0MjVkNjZlMGU5YWY5Nzk5MmU3MjQ0MjUyNzk3YmJhMTNlMjE4NjJhNGVmNjI4NzdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PdObnoTm9vr05iSD9qV6NKFb5jx9XyHpx3eluWK4yfc)
> 
> jellyfin能连上吗，媒体统计是否能显示？

![image](https://github.com/jxxghp/MoviePilot/assets/115156545/cc1a2a76-6d72-4a78-b280-b9cf993f3fc1)
可以连接，可以显示，点击也能跳转外网播放地址

**Comment by windmakeppcool** [comment]
同样的问题1.6.8我也有，emby连不上，反馈如下
ERROR:   emby.py - Users 未获取到返回数据
ERROR:   emby.py - Users 未获取到返回数据
ERROR:   emby.py - Users 未获取到返回数据
ERROR:   emby.py - Items/Counts 未获取到返回数据
ERROR:   emby.py - Users/Items/Latest 未获取到返回数据
ERROR:   emby.py - Users/Items/Resume 未获取到返回数据
ERROR:   emby.py - User/Views 未获取到返回数据
ERROR:   emby.py - Users/Query 未获取到返回数据
