### ISSUE TITLE
[Feature Request]: 请求添加PTHOME和MT认证，感谢大佬。

### ISSUE THREAD

**Issue by 48542257** [jxxghp/MoviePilot#1405]
### 当前程序版本

1.5.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

请求添加PTHOME和MT认证，感谢大佬。

### 参考资料

https://www.pthome.net/
https://kp.m-team.cc//index.php

**Comment by EkkoG** [comment]
这个要站方添加接口才可以，不是项目这边说加就加的
