### ISSUE TITLE
[错误报告]: 电视剧类型订阅分季问题

### ISSUE THREAD

**Issue by iamckun** [jxxghp/MoviePilot#1406]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.0

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

站点资源名称和TheMovieDb这些不一样，站点分了季和当前季的集数，没有使用TheMovieDb的单季总集数，导致订阅功能无法使用，切换到豆瓣的话也无法搜索，能否给予自定义订阅自己设置年份、季、集和定时表达式及ssr连接的功能

**Comment by kingtalk** [comment]
设定-词表，添加“Mashle.Magic.and.Muscles.2024.S02 => Mashle.Magic.and.Muscles.2023.S01 && Muscles.2023.S01  <>  1080p >> EP+12”
可以把站点中的2024年S02E01识别成2023年S01E13，然后就可以正常订阅了。建议尝试一下
