### ISSUE TITLE
qbittorrent不能使用https

### ISSUE THREAD

**Issue by Sraw** [jxxghp/MoviePilot#1408]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我的qbittorrent是由nginx代理的，nginx接受https流量再反向代理http流量给qb。

之前一直用得好好的，最近更新过之后突然就显示“无法连接qbittorrent下载器”，具体原因显示说是http的traffic发到了https的port上。

我目测似乎突然之间mp就不支持以https的形式连接qb了，麻烦排查一下，谢谢。

### 发生问题时系统日志和配置文件

```bash
2024/01/24 14:51:42	stdout	</html>
2024/01/24 14:51:42	stdout	</body>
2024/01/24 14:51:42	stdout	<hr><center>nginx</center>
2024/01/24 14:51:42	stdout	<center>The plain HTTP request was sent to HTTPS port</center>
2024/01/24 14:51:42	stdout	<center><h1>400 Bad Request</h1></center>
2024/01/24 14:51:42	stdout	<body>
2024/01/24 14:51:42	stdout	<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
2024/01/24 14:51:42	stdout	[31mERROR:[0m   qbittorrent.py - 获取种子列表出错：<html>
2024/01/24 14:51:42	stdout	
2024/01/24 14:51:42	stdout	</html>
2024/01/24 14:51:42	stdout	</body>
2024/01/24 14:51:42	stdout	<hr><center>nginx</center>
2024/01/24 14:51:42	stdout	<center>The plain HTTP request was sent to HTTPS port</center>
2024/01/24 14:51:42	stdout	<center><h1>400 Bad Request</h1></center>
2024/01/24 14:51:42	stdout	<body>
2024/01/24 14:51:42	stdout	<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
```

**Comment by EkkoG** [comment]
请提供发生问题时的配置文件

**Comment by Sraw** [comment]
Relevant ones:

```
QB_HOST: https://qb.internal:443
QB_USER: USER_NAME
QB_PASSWORD: PASSWORD
```

**Comment by EkkoG** [comment]
你贴的这个域名应该是个只在你的局域网失效的域名，既然都在一个局域网了，建议直接用 IP 连接，即使你要反代 qb  给公网用，mp 和 qb 之间依然是可以保持 IP 访问，这不冲突，局域网加 HTTPS  个人觉得非常没有必要

另外请提供完整的日志，看一下是从登录开始就出错还是在 获取种子列表出错的时候出错

**Comment by Sraw** [comment]
你好，日志文件自动被删除了。重建环境有点麻烦...

不是什么大问题。
