### ISSUE TITLE
[错误报告]: 群晖套件版在moviepilot网页上无法重启

### ISSUE THREAD

**Issue by Timqaq** [jxxghp/MoviePilot#1409]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

点击重启按钮后弹窗提示：重启时发生错误：Error while fetching server API version: HTTPConnectionPool(host='127.0.0.1', port=38379): Max retries exceeded with url: /version (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))
查看日志时没有显示错误。

### 发生问题时系统日志和配置文件

```bash
无
```

**Comment by tangyl2000** [comment]
确实提示这个，我也碰到相同的问题了。

**Comment by arthurfsy2** [comment]
是的，我白群晖也是遇到这个问题

**Comment by zzzzzz2006** [comment]
解决了吗

**Comment by starsnowfire** [comment]
我也遇到了同样的问题，使用的是群晖里，矿神套件1.7.2版本

**Comment by raylapse** [comment]
每次重新部署容器后，第一次启动日志里都会楼主报的这条日志，然后卡在
INFO:    plugin.py - 开始安装在线插件... 

容器启动失败。再次手工点击启动容器，又可以运行。。。
