### ISSUE TITLE
[Feature Request]: 希望增加更多站点

### ISSUE THREAD

**Issue by Timqaq** [jxxghp/MoviePilot#1410]
### 当前程序版本

1.6.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

我有两个站点无法添加，分别为麒麟和馒头。点新增后提示（新增站点失败：该站点不支持或用户未通过认证）

**Comment by tangyl2000** [comment]
馒头可以用.io域名啊，另外一个不清楚

**Comment by Timqaq** [comment]
> 馒头可以用.io域名啊，另外一个不清楚

试了一下，馒头可以用.io，感谢
