### ISSUE TITLE
[Feature Request]: MP内站点浏览页面增加直接通过MP推送给QB下载器下载种子

### ISSUE THREAD

**Issue by soaizzb** [jxxghp/MoviePilot#1415]
### 当前程序版本

1.5.9-1

### 运行环境

Windows

### 功能改进类型

主程序

### 功能改进

如题，目前MP内的站点管理页面内，浏览站点列表中，只能下载种子文件，希望添加功能：点击下载或者种子标题能直接通过MP推送给QB下载器，谢谢。

**Comment by Melody-Test** [comment]
这个可以 跟ptpp类似的功能
