### ISSUE TITLE
建议外挂/app/plugins目录[Feature Request]: 

### ISSUE THREAD

**Issue by BackspaceM** [jxxghp/MoviePilot#1418]
### 当前程序版本

1.6.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

由于使用有NAS及win系统，目前nas上第三方插件库暂未发现问题，但win上安装第三方插件时会显示‘插件 短剧刮削 安装失败：可执行文件模式下，只能安装本地插件}’，是否可以考虑将plugins目录直接生成到config文件夹内，并可让用户自由下载解压进改文件夹进行插件安装呢（这样部分用户nas上若无梯子<非侵入旁路，部分docker需要科学走的macvlan指定旁路网关>，也很方便的可以在其他系统上下载并上传至改文件夹进行安装）

**Comment by jxxghp** [comment]
可执行文件版本是预编译的，跑不了源码，不是映不映射的问题。
可用第三方打包的安装程序。
