### ISSUE TITLE
[错误报告]: 在群辉中使用CloudDrive2 挂载阿里云为本地磁盘，进行文件的整理，提示错误代码 -1

### ISSUE THREAD

**Issue by ShmilyTMD** [jxxghp/MoviePilot#1419]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

通过CloudDrive2 挂载阿里云为本地磁盘，然后进行文件的整理，会提示失败，错误代码 -1，实际上MP已经在整理文件夹中创建了目录，但是就是无法硬连接和刮削，本地文件无此问题，路径设置也是正确的
![微信图片_20240129111218](https://github.com/jxxghp/MoviePilot/assets/145415544/968411da-17e0-42a1-9c5d-b98f88612386)

### 发生问题时系统日志和配置文件

```bash
INFO:chain- 发送消息:channel=None，title=TokyO MER 行动急诊室 电影版-Tokyo MER:Mobile Emergency Room:The Movie.2023.Blu-rayDTS.H.265 10-bit.mky 未识别到媒体信息，无法入库!，text=回复:redo 348「tmdbidl类型手动识别转移。，userid=Nonecommand.py-处理事件:notice.message-[]INFO :chain-请求模块执行:postmessageDEBUG:-/cloud2/阿里云盘0pen/阿里源文件/电影/TokyoMEtransfer.pyTNEO :R行动急诊室 电影版失败 1个，跳过(2023)转移完成，共1个文件，221.231.27.78:0-"PoST /api/vl/transfer/manual?logid=0&pa
```

**Comment by ShmilyTMD** [comment]
我傻B了，网盘不能硬连接，直接移动就好

**Comment by Next-Page-Vi** [comment]
解决了就close掉
