### ISSUE TITLE
[错误报告]: 管理员密码修改无法使用特殊字符

### ISSUE THREAD

**Issue by jder1234** [jxxghp/MoviePilot#1420]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

管理员密码修改无法使用某些特殊字符, 

例如: Abc-123456,  无法修改, "提示必须含有大小写和数字",  但是使用Abc123456, 去掉特殊字符-, 就可以修改成功.

**Comment by EkkoG** [comment]
https://github.com/jxxghp/MoviePilot/blob/c0eb6b060029579fe42302a7f09678c80f80ed40/app/api/endpoints/user.py#L64

设计如此，应该算不上 bug

**Comment by 757957414** [comment]
其实最好提醒不能使用特殊字符，或者干脆支持特殊字符
