### ISSUE TITLE
[Feature Request]: 希望搜索结果页面添加订阅选项

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot#1421]
### 当前程序版本

 v1.6.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![image](https://github.com/jxxghp/MoviePilot/assets/97422881/544f5843-3165-4d9a-aa59-4d23955c34f1)
希望在搜索结果页面可以添加一个订阅按钮，有时候可能会先看某个剧有没有资源或者是否完结，搜索完成可以直接订阅，同时也方便电影或电视剧进行洗版操作，希望作者大大能考虑一下！！！

**Comment by jxxghp** [comment]
浏览器选返回
