### ISSUE TITLE
[错误报告]: iyuu自动辅种插件一运行网页就崩溃，无响应

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#1422]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

iyuu自动辅种插件点击运行后，查看日志，网页卡死崩溃。

**Comment by EkkoG** [comment]
请提供日志和配置文件
