### ISSUE TITLE
订阅页面和媒体库剧集不同步（不一致）

### ISSUE THREAD

**Issue by torashen** [jxxghp/MoviePilot#1424]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅页面和媒体库剧集数量与实际不同步（不一致）
![Uploading 企业微信截图_17065803489801.png…]()

**Comment by EkkoG** [comment]
图片裂了

**Comment by torashen** [comment]
![Uploading 企业微信截图_17065803489801.jpg…]()

**Comment by EkkoG** [comment]
还是裂的。。传完检查一下呀
