### ISSUE TITLE
[错误报告]: Chinesesubfinder  插件发送的video_type 不正确

### ISSUE THREAD

**Issue by jder1234** [jxxghp/MoviePilot#1433]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/106365097/667701e8-bf68-4d7b-a068-fbe2e9879136)

如图所示, 下载电影银河护卫队, 发送的video_type: 1, 按chinesesubfinder 的api 说明movie 对应的type应该是 0.

现在的res.status_code=200, 但是 res.text 是空的 (不确定是不是上面原因导致的).

**Comment by jder1234** [comment]
电影字幕无法自动下载就是这个原因.

看了下源码, 221 行
` item_type=0 if item_type == MediaType.MOVIE.value else 1,
`
应该改为
`item_type=0 if item_type == MediaType.MOVIE else 1,`

**Comment by jxxghp** [comment]
插件已升级至1.1版本
