### ISSUE TITLE
[错误报告]: 無法獲取貓站標題

### ISSUE THREAD

**Issue by Pazuzu5688** [jxxghp/MoviePilot#1438]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

網站匯入後，透過「站點管理」-> 貓站 -> 「瀏覽」，無法獲取標題。

![2024-02-01_13-51-22](https://github.com/jxxghp/MoviePilot/assets/54314612/65ef130d-b375-49c4-a223-de551be42693)

**Comment by jxxghp** [comment]
正常，请确认是否有在站点设置中打开影响种子页UI的选项
