### ISSUE TITLE
[错误报告]: 当剧集名字中含有英文冒号:时，转移后的文件名乱码

### ISSUE THREAD

**Issue by Putarku** [jxxghp/MoviePilot#1442]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

**转移的文件名:**
> [DMG&FZSD&VCB-Studio] Princess Connect! Re Dive [12][Ma10p_1080p][x265_flac].mkv

刮削信息是正确的，可以看到剧集名字中含有:
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/348e11f3-2331-4bed-b073-094bd1ec1a05)

刮削后的效果如下
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/a5b0305a-4fec-44f6-ab82-eaf3fb5babf6)

但使用nastool时是可以正确刮削的，原因是自动将英文:替换为了中文：
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/baa4c53d-4d6b-452e-a2c3-c8aa3fcca3cf)

除此之外，类似这种还有特殊字符的影视也会导致转移时出错
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/25480713-9dca-41a0-a421-bb11489e8f6e)
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/057d54aa-dcc9-42ae-accf-9bbdcb13a16c)
mp在生成路径时会将文件名本身的特殊字符作为路径的一部分

**Comment by cng10001** [comment]
这个应该是Windows不支持英文冒号
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/eef87b2d-1ccc-4d9f-b0fa-36e313d80a85)

**Comment by Putarku** [comment]
> 这个应该是Windows不支持英文冒号
> ![image](https://github.com/jxxghp/MoviePilot/assets/115156545/eef87b2d-1ccc-4d9f-b0fa-36e313d80a85)
> 

是的，所以推荐可以按原来nt的处理方式那样转换为对应的中文标点

**Comment by cng10001** [comment]
感觉悬~

**Comment by BeyondandSharp** [comment]
研究了一下现在可以在重命名格式那边实现，用jinjia2的过滤器。以下是我的重命名格式：`{% set original_title=original_title|replace(":", "：")|replace("?", "？")|replace("*", "_")|replace("<", "《")|replace(">", "》")|replace("|", "丨") %}{% set title=title|replace(":", "：")|replace("?", "？")|replace("*", "_")|replace("<", "《")|replace(">", "》")|replace("|", "丨") %}{{title}}{% if year %} ({{year}}){% endif %}/{{title}} - {{original_title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}}`
实测可行，但我不太熟悉jinjia2，所以斜杠和引号就没有替换。

**Comment by cng10001** [comment]
> 研究了一下现在可以在重命名格式那边实现，用jinjia2的过滤器。以下是我的重命名格式：`{% set original_title=original_title|replace(":", "：")|replace("?", "？")|replace("*", "_")|replace("<", "《")|replace(">", "》")|replace("|", "丨") %}{% set title=title|replace(":", "：")|replace("?", "？")|replace("*", "_")|replace("<", "《")|replace(">", "》")|replace("|", "丨") %}{{title}}{% if year %} ({{year}}){% endif %}/{{title}} - {{original_title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}}` 实测可行，但我不太熟悉jinjia2，所以斜杠和引号就没有替换。

可以啊，起码英文冒号这个问题是被中文冒号替换掉了。⑥⑥⑥
