### ISSUE TITLE
[Feature Request]: 希望可以增加一个单纯的“硬链接转移文件"的功能插件

### ISSUE THREAD

**Issue by luowenfu** [jxxghp/MoviePilot#1445]
### 当前程序版本

1.6.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

[硬链接工具](https://github.com/appotry/PTtool/)
就是实现：不进行媒体识别，不刮削，只做硬链接转移文件。
并且可以指定文件大小，或者指定扩展名不进行转移。

### 参考资料

https://github.com/appotry/PTtool/

**Comment by LoSiTeE** [comment]
同求
