### ISSUE TITLE
[Feature Request]: 每天更新一下订阅信息

### ISSUE THREAD

**Issue by mmspuff** [jxxghp/MoviePilot#1450]
### 当前程序版本

v1.6.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

每天定时更新一下电视剧订阅信息。
有的剧很早就订阅了，tmdb信息不完善，甚至总集数都要手动设定，还有很多奇怪的订阅问题导致订阅不正确，往往需要订阅一半然后取消订阅再重新订阅来达到正确订阅的效果。如果能每天晚上自动同步，纠正潜在订阅问题就好！

**Comment by honue** [comment]
这个也可以关了，这个[commit](https://github.com/jxxghp/MoviePilot/commit/164ce8f7c4b9eaae56b6225d6a197179d8989f42)修了，不使用缓存更新订阅信息。我看半天，我说怎么我mp还是存在这个问题，dev看着是正常刷新的。。
