### ISSUE TITLE
[错误报告]: 整理资源为多部合集电影时，刮削失败

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#1453]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅后自动下载了那种多部电影合集的资源，在刮削时，应该是按目录名进行刮削的，文件夹下多个电影只能将最大的那个刮削成他识别到的目录名的哪一个电影，其他都会刮削失败。并且最大的那个文件并不是目标订阅资源，反而覆盖了媒体库中已有的其他资源。

The Amazing Spider-Man Collection 2012-2014 UHD BluRay 2160p 10bit HDR 2Audio TrueHDAtmos 7.1 x265
Spider-Man 2002-2007 UHD BluRay 2160p TrueHD Atmos 7 1 x265.10bit HDR

**Comment by jxxghp** [comment]
改重命名规则，加入区分要素
