### ISSUE TITLE
[Feature Request]: 集成clash插件使MP使用更加流畅

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1455]
### 当前程序版本

1.6.1

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

集成clash插件，支持直接添加订阅地址，让访问`TMDB`、`TVDB`、`TG`地址的网络请求直接通过clash访问，避免了因为`墙`导致的MP无法正常使用

**Comment by loveu5522** [comment]
clash可以docker自建的，集成完全没必要，臃肿，我想作者也不会集成的

**Comment by album-GitHub** [comment]
配置里面有PROXY_HOST可以配置网络代理，一般都是在软路由上配置好clash，内网有需求的设备配置代理就行

**Comment by carolcoral** [comment]
> clash可以docker自建的，集成完全没必要，臃肿，我想作者也不会集成的



> 配置里面有PROXY_HOST可以配置网络代理，一般都是在软路由上配置好clash，内网有需求的设备配置代理就行

我使用外部的clash搭配使用MP确实可以，但是发现问题就是所有流量都走了clash，导致一天下来用了100g的流量，所以才提出时候可以内置clash插件，然后插件只让指定的几个地址走clash

**Comment by carolcoral** [comment]
> > clash可以docker自建的，集成完全没必要，臃肿，我想作者也不会集成的
> 
> > 配置里面有PROXY_HOST可以配置网络代理，一般都是在软路由上配置好clash，内网有需求的设备配置代理就行
> 
> 我使用外部的clash搭配使用MP确实可以，但是发现问题就是所有流量都走了clash，导致一天下来用了100g的流量（100g的VPN流量啊！），所以才提出时候可以内置clash插件，然后插件只让指定的几个地址走clash
