### ISSUE TITLE
[Feature Request]: 支持在文件管理中对单个文件夹、文件进行刮削

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#1456]
### 当前程序版本

1.6.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前的刮削是插件自动全部/增量刮削，但是有时候因为别的一些原因会导致刮削的内容被错误覆盖或误删除，这个时候需要单独对指定的文件或文件夹进行重新刮削。目前在MP中暂时没有发现该功能的支持，在nastool中原来是支持的。

**Comment by album-GitHub** [comment]
不是在文件管理那边嘛
![image](https://github.com/jxxghp/MoviePilot/assets/51018113/04f3fef4-e959-49d8-a736-07c00a7250e3)

**Comment by carolcoral** [comment]
这个我鼠标移上去不是显示的转移么？我已经转移好了，只是重新刮削而已
<img width="946" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/5c64ab76-2754-41ef-bb35-ee220d69c04c">


> 不是在文件管理那边嘛 ![image](https://private-user-images.githubusercontent.com/51018113/302972917-04f3fef4-e959-49d8-a736-07c00a7250e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTU1NjUsIm5iZiI6MTcwNzM1NTI2NSwicGF0aCI6Ii81MTAxODExMy8zMDI5NzI5MTctMDRmM2ZlZjQtZTk1OS00OWQ4LWE3MzYtMDdjMDBhNzI1MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAxMjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwOTdkMDM1MGIyMjFiMTcwNjI0ZTViZDBiODk5MzE2MWZiN2Y0YjZkMDRmMzBiYWMzNGY2YjQ2NDQ5YzdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lcO0EJo_wvsb31_ZeAWFGJ0DTrvqXwahrryWXAy48rc)
