### ISSUE TITLE
动漫订阅和下载后文件刮削命名不一致

### ISSUE THREAD

**Issue by WadeChenn** [jxxghp/MoviePilot#1459]
### 当前程序版本

1.6.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

带有副标题的动漫季度 例如 西行纪年番 是西行纪的第五季   订阅时可以按第五季订阅并且可以正常下载对应资源。但是刮削时命名是西行纪年番，独立在了西行纪之外。
是否能将下载的资源与对应的订阅绑定，不重新进行文件名的识别，直接刮削。保证订阅和最终的刮削结果一致。

**Comment by jxxghp** [comment]
使用下载器监控整理，会复用下载时的识别信息。
