### ISSUE TITLE
[错误报告]: 目录监控插件选择硬链接但实际为复制，我确定源目录和目的目录在同盘同共享文件夹。

### ISSUE THREAD

**Issue by Timqaq** [jxxghp/MoviePilot#1461]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

目录监控插件无法硬链接，实际为复制。mp版本为群晖套件1.6.0、1.6.1，两个版本均有此问题。以下是我的目录构成、插件设置及相关日志：
![(6H2U`99%LCZW@8RPJK@2Y6](https://github.com/jxxghp/MoviePilot/assets/95278905/6a0c3aa2-57dd-41c4-905b-11883d4ddcb7)
![{N@%F55C@~J%W3$K71X~%XF](https://github.com/jxxghp/MoviePilot/assets/95278905/a3be0a18-35cb-44d3-8af1-6d6faa2f8346)
![SR78@BV 2WEZVU(58FW1W~2](https://github.com/jxxghp/MoviePilot/assets/95278905/6025ccac-53af-49cb-af55-29415c1e08af)
![RYK$8JZ%F95YFEQ8LI~17F2](https://github.com/jxxghp/MoviePilot/assets/95278905/3b60f9b1-9610-4de9-9e58-dc27c5cb948e)
![N2(MNF%$XA _}~X4{JKLPF8](https://github.com/jxxghp/MoviePilot/assets/95278905/0cad37ae-95d4-484f-a1e2-cb0a14a359cd)
另外还有一个bug，我设置的媒体库movies对应电影tvplay对应电视剧，comics对应动漫。且目录监控插件里也绑定了转移目录，但是偶尔会出现/Download/movies里的电影文件整理到了/links/tvplay里面去，同理电视剧文件也会到电影目录里面去。
![QQ图片20240208154006](https://github.com/jxxghp/MoviePilot/assets/95278905/c027bcce-16d9-4664-aabc-8c84a1a570ab)

**Comment by Timqaq** [comment]
对了，手动在文件管理里面转移历史记录显示转移方式为硬链接的，但是实际仍为复制
![LT})@)W%B29ZLSWJ CD_5Q9](https://github.com/jxxghp/MoviePilot/assets/95278905/b2eed286-3ba0-4f17-b6c1-7e835cabc583)
![QQ截图20240208155056](https://github.com/jxxghp/MoviePilot/assets/95278905/cc72abef-f03d-468f-81bc-aaa60cc1421c)
![QQ截图20240208155148](https://github.com/jxxghp/MoviePilot/assets/95278905/c5430844-357a-4eec-8e8b-7fa50fc38831)

**Comment by mjsoftking** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/f0edcb4a-0e51-433a-8269-f434211bc903)
你的配置为啥有点特别
