### ISSUE TITLE
[错误报告]: 数据类型错误

### ISSUE THREAD

**Issue by W1lsp0** [jxxghp/MoviePilot#1462]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

看不懂的数据类型错误，配置完重启就会复现，不知道原因。
![image](https://github.com/jxxghp/MoviePilot/assets/57605626/65d3a579-2024-464a-98c2-f92d7f449dd0)
![image](https://github.com/jxxghp/MoviePilot/assets/57605626/54f602e0-9369-4015-8b27-4e65faf4ae45)

### 发生问题时系统日志和配置文件

```bash
自动同步下载器文件记录 (trigger: interval[6:00:00], pending)
INFO:    plugin.py - Plugin Loaded：SyncDownloadFiles
Pending jobs:
    下载进度推送 (trigger: interval[0:05:00], pending)
INFO:    plugin.py - Plugin Loaded：DownloadingMsg
INFO:    plugin.py - Plugin Loaded：IyuuMsg
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/app/app/main.py", line 198, in start_module
    Scheduler()
  File "/app/app/utils/singleton.py", line 14, in __call__
    cls._instances[key] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/scheduler.py", line 97, in __init__
    self._scheduler.add_job(
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 434, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 935, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 920, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/interval.py", line 32, in __init__
    self.interval = timedelta(weeks=weeks, days=days, hours=hours, minutes=minutes,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: str
ERROR:    Application startup failed. Exiting.
```

**Comment by lyxcnzj** [comment]
同样遇到了这个问题，在更新了1.61后复现，之前版本没有遇到过，docker反复重启
下面是日志：

不使用代理更新程序
Release 更新模式
当前版本号：v1.6.1
最新版本号：v1.6.1
未发现新版本，跳过更新步骤...
usermod: no changes
Proxy dockerbackend started.
Proxy dockerfrontend started.
INFO:    migration.py - Context impl SQLiteImpl.
INFO:    migration.py - Will assume non-transactional DDL.
INFO:     Started server process [63]
INFO:     Waiting for application startup.
INFO:    singleton.py - 站点资源版本：1.0.9
INFO:    singleton.py - 认证资源版本：1.1.2
INFO:    singleton.py - audiences 用户认证成功！
INFO:    resource.py - 开始检测资源包版本...
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/app/app/main.py", line 192, in start_module
    ResourceHelper()
  File "/app/app/utils/singleton.py", line 14, in __call__
    cls._instances[key] = super().__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/helper/resource.py", line 24, in __init__
    self.check()
  File "/app/app/helper/resource.py", line 37, in check
    resource_info = json.loads(res.text)
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:    Application startup failed. Exiting.

**Comment by jxxghp** [comment]
> ### 确认
> 
> - [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
> - [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
> - [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
> - [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 
> 1.6.1
> 
> ### 运行环境
> 
> Docker
> 
> ### 问题类型
> 
> 主程序运行问题
> 
> ### 问题描述
> 
> 看不懂的数据类型错误，配置完重启就会复现，不知道原因。
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/57605626/65d3a579-2024-464a-98c2-f92d7f449dd0)
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/57605626/54f602e0-9369-4015-8b27-4e65faf4ae45)
> 
> ### 发生问题时系统日志和配置文件
> 
> ```bash
> 自动同步下载器文件记录 (trigger: interval[6:00:00], pending)
> 
> INFO:    plugin.py - Plugin Loaded：SyncDownloadFiles
> 
> Pending jobs:
> 
>     下载进度推送 (trigger: interval[0:05:00], pending)
> 
> INFO:    plugin.py - Plugin Loaded：DownloadingMsg
> 
> INFO:    plugin.py - Plugin Loaded：IyuuMsg
> 
> ERROR:    Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
> 
>     async with self.lifespan_context(app) as maybe_state:
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
> 
>     await self._router.startup()
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
> 
>     handler()
> 
>   File "/app/app/main.py", line 198, in start_module
> 
>     Scheduler()
> 
>   File "/app/app/utils/singleton.py", line 14, in __call__
> 
>     cls._instances[key] = super().__call__(*args, **kwargs)
> 
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/app/scheduler.py", line 97, in __init__
> 
>     self._scheduler.add_job(
> 
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 434, in add_job
> 
>     'trigger': self._create_trigger(trigger, trigger_args),
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 935, in _create_trigger
> 
>     return self._create_plugin_instance('trigger', trigger, trigger_args)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 920, in _create_plugin_instance
> 
>     return plugin_cls(**constructor_kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/interval.py", line 32, in __init__
> 
>     self.interval = timedelta(weeks=weeks, days=days, hours=hours, minutes=minutes,
> 
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> TypeError: unsupported type for timedelta minutes component: str
> 
> ERROR:    Application startup failed. Exiting.
> ```
> 

你的某个插件设置了错误的定时。

**Comment by jxxghp** [comment]
> 同样遇到了这个问题，在更新了1.61后复现，之前版本没有遇到过，docker反复重启
> 
> 下面是日志：
> 
> ```
> 
> 
> 
> 不使用代理更新程序
> 
> Release 更新模式
> 
> 当前版本号：v1.6.1
> 
> 最新版本号：v1.6.1
> 
> 未发现新版本，跳过更新步骤...
> 
> usermod: no changes
> 
> Proxy dockerbackend started.
> 
> Proxy dockerfrontend started.
> 
> INFO:    migration.py - Context impl SQLiteImpl.
> 
> INFO:    migration.py - Will assume non-transactional DDL.
> 
> INFO:     Started server process [63]
> 
> INFO:     Waiting for application startup.
> 
> INFO:    singleton.py - 站点资源版本：1.0.9
> 
> INFO:    singleton.py - 认证资源版本：1.1.2
> 
> INFO:    singleton.py - audiences 用户认证成功！
> 
> INFO:    resource.py - 开始检测资源包版本...
> 
> ERROR:    Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
> 
>     async with self.lifespan_context(app) as maybe_state:
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
> 
>     await self._router.startup()
> 
>   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
> 
>     handler()
> 
>   File "/app/app/main.py", line 192, in start_module
> 
>     ResourceHelper()
> 
>   File "/app/app/utils/singleton.py", line 14, in __call__
> 
>     cls._instances[key] = super().__call__(*args, **kwargs)
> 
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/app/app/helper/resource.py", line 24, in __init__
> 
>     self.check()
> 
>   File "/app/app/helper/resource.py", line 37, in check
> 
>     resource_info = json.loads(res.text)
> 
>                     ^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
> 
>     return _default_decoder.decode(s)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
> 
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
> 
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> 
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> ERROR:    Application startup failed. Exiting.
> 
> ```

连不上github
