### ISSUE TITLE
[错误报告]: 启用新的二级分类后，动漫的硬链接目录逻辑问题

### ISSUE THREAD

**Issue by album-GitHub** [jxxghp/MoviePilot#1467]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

动漫是有专门的一个分类目录的，但启用新的二级分类插件后硬链接会在动漫的目录下重新生成一个二级目录，比如动漫的目录为Anime，启用插件后会在Anime目录下生成一个‘动漫’二级目录（按模板去配置的），逻辑上就不太对了
如果可以的话希望可以单独给动漫一个独立的链接逻辑，或者在二级分类那边可以设置目录的绝对路径，方便进行自定义
具体设置：
![image](https://github.com/jxxghp/MoviePilot/assets/51018113/bd3bda62-ca56-440f-96b4-0a5bf7acc5b8)

![image](https://github.com/jxxghp/MoviePilot/assets/51018113/3c7564ad-6653-4f52-9cf3-706ed6220678)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-02-10 20:51:01,249 - tmdbapi.py - 正在查询TMDB电视剧：13916，季：1 ...
【INFO】2024-02-10 20:51:01,266 - filetransfer - 获取转移目标路径：/Media/Anime/动漫
【INFO】2024-02-10 20:51:01,271 - filetransfer - 正在转移文件：/Media/A1_PT_Save/anime/[2006][Death Note][BDRIP][1080P][1-37Fin+SP]/[Death Note][28][BDRIP][1080P][H264(ED60fps)_FLAC].mkv 到 /Media/Anime/动漫/死亡笔记 (2006)/Season 1/死亡笔记 - S01E28 - 第 28 集.mkv
【INFO】2024-02-10 20:51:01,273 - filetransfer - 文件 /Media/A1_PT_Save/anime/[2006][Death Note][BDRIP][1080P][1-37Fin+SP]/[Death Note][28][BDRIP][1080P][H264(ED60fps)_FLAC].mkv link完成
【INFO】2024-02-10 20:51:01,281 - filetransfer - 文件 /Media/A1_PT_Save/anime/[2006][Death Note][BDRIP][1080P][1-37Fin+SP]/[Death Note][28][BDRIP][1080P][H264(ED60fps)_FLAC].mkv 转移成功
【INFO】2024-02-10 20:51:01,331 - themoviedb - 开始刮削媒体库文件：/Media/Anime/动漫/死亡笔记 (2006)/Season 1/死亡笔记 - S01E28 - 第 28 集.mkv ...
```

**Comment by cng10001** [comment]
那你把这个动漫分类删了就直接在anime下了吧！

**Comment by album-GitHub** [comment]
> 那你把这个动漫分类删了就直接在anime下了吧！

那样会被识别成日韩剧，如果都不匹配的话，最终也会进入到一个叫未分类的文件夹中

**Comment by cng10001** [comment]
> > 那你把这个动漫分类删了就直接在anime下了吧！
> 
> 那样会被识别成日韩剧，如果都不匹配的话，最终也会进入到一个叫未分类的文件夹中

那你把动漫改成xxx动漫，内容类型加点其他国家代码，语言代码试试，我二级分类启用不了，也想搞来着~

**Comment by jxxghp** [comment]
二级分类里面删除掉动漫，单独设置动漫目录即可。

**Comment by album-GitHub** [comment]
> 二级分类里面删除掉动漫，单独设置动漫目录即可。

经测试，删掉二级分类的动漫，会被识别为日韩剧。。。。

**Comment by cng10001** [comment]
> > 二级分类里面删除掉动漫，单独设置动漫目录即可。
> 
> 经测试，删掉二级分类的动漫，会被识别为日韩剧。。。。

是不是逗号后面半句话被你吞嘞- -

**Comment by album-GitHub** [comment]
> > > 二级分类里面删除掉动漫，单独设置动漫目录即可。
> > 
> > 
> > 经测试，删掉二级分类的动漫，会被识别为日韩剧。。。。
> 
> 是不是逗号后面半句话被你吞嘞- -

以下是我的设置，一切都是按文档要求去设置的，但还是会被归类到Anime文件件，也就是我设置的动漫目录的二级目录下，并非归类到TV目录下，这个怎么看都是一个bug呀
![image](https://github.com/jxxghp/MoviePilot/assets/51018113/b82f751a-3b46-4e98-a47e-82af93136f00)

**Comment by cng10001** [comment]
动漫就是只能到动漫目录下啊，不会到tv下的

**Comment by album-GitHub** [comment]
> 动漫就是只能到动漫目录下啊，不会到tv下的

所以明明二级分类管的是TV目录的二级分类，却管到了动漫目录去了，而且没办法去掉，被强行二级分类，没办法直接保存在动漫一级目录下
我昨晚甚至都关不掉二级分类，LIBRARY_CATEGORY设置为False，二级分类依旧会生效。。。。。

**Comment by cng10001** [comment]
我懵了。这是有人写的教程，参考下吧https://github.com/Putarku/MoviePilot-Help?tab=readme-ov-file#%E5%8A%A8%E6%BC%AB%E5%86%85%E5%AE%B9%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E4%BA%8C%E7%BA%A7%E5%88%86%E7%B1%BB%E6%96%87%E4%BB%B6%E6%9D%A5%E5%AE%9E%E7%8E%B0%E4%BA%8C%E7%BA%A7%E5%88%86%E7%B1%BB

**Comment by cng10001** [comment]
重新梳理下，你是觉得你设置了Anime目录，然后开二级分类，又生成了动漫目录，你觉得重复了，有问题，是这个意思吗
那你有没有像作者说的重新设置动漫的二级分类的，比如这样
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/27f65ec2-25b4-4db0-896a-5f6067144d93)

**Comment by album-GitHub** [comment]
> 重新梳理下，你是觉得你设置了Anime目录，然后开二级分类，又生成了动漫目录，你觉得重复了，有问题，是这个意思吗 那你有没有像作者说的重新设置动漫的二级分类的，比如这样 ![image](https://private-user-images.githubusercontent.com/115156545/307483630-27f65ec2-25b4-4db0-896a-5f6067144d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzgxODcsIm5iZiI6MTcwODc3Nzg4NywicGF0aCI6Ii8xMTUxNTY1NDUvMzA3NDgzNjMwLTI3ZjY1ZWMyLTI1YjQtNGRiMC04OTZhLTVmNjA2NzE0NGQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQ5OGQ0MDA4MTQ2OGMwZDAxMTI4ZWEyNDY2MTRiMDNmOWQyODQyZGY0NGM4NTRhYzBhM2VjYmQzMzBjZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bsOVn5SJMntx-Qm_qzriBBoNqSzc_vBAWlLO9-CG4AY)

我并没有设置，但二级分类会把动漫识别成日韩剧（虽然确实是）

**Comment by cng10001** [comment]
> > 重新梳理下，你是觉得你设置了Anime目录，然后开二级分类，又生成了动漫目录，你觉得重复了，有问题，是这个意思吗 那你有没有像作者说的重新设置动漫的二级分类的，比如这样 ![image](https://private-user-images.githubusercontent.com/115156545/307483630-27f65ec2-25b4-4db0-896a-5f6067144d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzgxODcsIm5iZiI6MTcwODc3Nzg4NywicGF0aCI6Ii8xMTUxNTY1NDUvMzA3NDgzNjMwLTI3ZjY1ZWMyLTI1YjQtNGRiMC04OTZhLTVmNjA2NzE0NGQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQ5OGQ0MDA4MTQ2OGMwZDAxMTI4ZWEyNDY2MTRiMDNmOWQyODQyZGY0NGM4NTRhYzBhM2VjYmQzMzBjZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bsOVn5SJMntx-Qm_qzriBBoNqSzc_vBAWlLO9-CG4AY)
> 
> 我并没有设置，但二级分类会把动漫识别成日韩剧（虽然确实是）

那你设置啊，作者意思是你应该像这样单独配置你想要的二级目录

**Comment by album-GitHub** [comment]
> > > 重新梳理下，你是觉得你设置了Anime目录，然后开二级分类，又生成了动漫目录，你觉得重复了，有问题，是这个意思吗 那你有没有像作者说的重新设置动漫的二级分类的，比如这样 ![image](https://private-user-images.githubusercontent.com/115156545/307483630-27f65ec2-25b4-4db0-896a-5f6067144d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzgxODcsIm5iZiI6MTcwODc3Nzg4NywicGF0aCI6Ii8xMTUxNTY1NDUvMzA3NDgzNjMwLTI3ZjY1ZWMyLTI1YjQtNGRiMC04OTZhLTVmNjA2NzE0NGQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMjMxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQ5OGQ0MDA4MTQ2OGMwZDAxMTI4ZWEyNDY2MTRiMDNmOWQyODQyZGY0NGM4NTRhYzBhM2VjYmQzMzBjZjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bsOVn5SJMntx-Qm_qzriBBoNqSzc_vBAWlLO9-CG4AY)
> > 
> > 
> > 我并没有设置，但二级分类会把动漫识别成日韩剧（虽然确实是）
> 
> 那你设置啊，作者意思是你应该像这样单独配置你想要的二级目录

我自己梳理一下我自己的需求吧：
1.动漫目录单独放在一级目录下，所有识别为动漫的全部都放到这个一级目录下
2.电影、其他电视剧开启二级分类，根据规则二级分类，放在二级目录下

目前的MoviePilot的策略问题：开启二级分类、单独设置动漫目录后，二级分类中如果识别为动漫，则会根据二级分类规则，放入动漫的二级目录中，但根据配置文件中的示范来看，实际上会被二级分类的应该是除了动漫外被归类为tv的项目才对呀
目前二级分类的规则因为动漫目录的存在，逻辑比较难让人理解了，可自定义的并没有预想中那么简单

我举个例子：
环境设置：开启二级分类；设置tv与动漫目录，分别为/TV、/anime
二级分类设置：
tv:
   动漫：
          #条件
   国产剧：
          #条件
   日剧:
          #条件
刮削内容：xxx动漫、xxx国产电视剧、xxx日剧
刮削后目录情况：
xxx动漫目录：/anime/动漫/xxx动漫
xxx国产电视剧：/TV/国产剧/xxx国产电视剧
xxx日剧：/TV/日剧/xxx日剧

按我的理解是，单独设置的动漫目录已经是二级目录了，二级分类中再创建一次二级目录的话算三级目录了，实际使用中过于麻烦


最终需求：
对二级分类策略进行进一步细化并，配置文件可单独为某一项设置一级目录并默认启用，取消掉原来专门的几个目录设置，全部改为配置文件配置，或者直接给二级分类进行一个单独的页面设置，减少混乱

**Comment by Xm798** [comment]
> 二级分类里面删除掉动漫，单独设置动漫目录即可。

删掉动漫，单独设置动漫目录，会被自动识别为日剧：

正在转移文件：/downloads/Anime/Delicious.in.Dungeon.S01.2024.1080p.DSNP.WEB-DL.H264.DDP5.1-Nest@ADWeb/Delicious.in.Dungeon.S01E01.2024.1080p.DSNP.WEB-DL.H264.DDP5.1-Nest@ADWeb.mkv 到 /media/Anime/日剧/迷宫饭(2024)/Season 1/迷宫饭.Delicious in Dungeon.S01E01.2024.1080p.WEB-DL.H264.DDP 5.1-ADWeb.mkv
