### ISSUE TITLE
[错误报告]: 阿童木站点索引器错误

### ISSUE THREAD

**Issue by Summer-Tail** [jxxghp/MoviePilot#1469]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

阿童木索引器可能对于站点的支持已经失效

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-02-11 13:52:00,374 - spider.py - 阿童木 搜索出现错误：Got pseudo-element ::FunctionalPseudoElement[::nth-child(['1'])] not at the end of a selector
【ERROR】2024-02-11 13:52:00,384 - spider.py - 阿童木 搜索出现错误：Got pseudo-element ::FunctionalPseudoElement[::nth-child(['1'])] not at the end of a selector
【ERROR】2024-02-11 13:52:00,395 - spider.py - 阿童木 搜索出现错误：Got pseudo-element ::FunctionalPseudoElement[::nth-child(['1'])] not at the end of a selector
【ERROR】2024-02-11 13:52:00,407 - spider.py - 阿童木 搜索出现错误：Got pseudo-element ::FunctionalPseudoElement[::nth-child(['1'])] not at the end of a selector
```

**Comment by jxxghp** [comment]
暂不影响使用，最新资源包已修复。
