### ISSUE TITLE
[错误报告]:  API 新增订阅有问题：/api/v1/subscribe/ 

### ISSUE THREAD

**Issue by Dean12321** [jxxghp/MoviePilot#1472]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.3

### 运行环境

Docker

### 问题类型

API 问题

### 问题描述

# 这个api有问题：

```
/api/v1/subscribe/
```

# 问题描述：

`新增订阅api`每一个季只是在**第一次api调用**的时候可以正常订阅，比如已经订阅过一次A剧的第一季了，后面再调用`新增订阅api`订阅B剧的第一季的话，订阅成功的还是A剧的第一季。也就是说通过`新增订阅api`订阅的不论任何剧集的任何季度，都只认第一次调用api的的剧集的季度

---

# 复现过程：

## 一、第一次调用`新增订阅api`订阅了`少年泰坦出击 (2013)`(tmdbod=45140):S01~S08

```
curl -X 'POST' \
  'http://localhost:43001/api/v1/subscribe/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "tmdbid": 45140,
  "season": 1
}'
```
...
...
...
```
curl -X 'POST' \
  'http://localhost:43001/api/v1/subscribe/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "tmdbid": 45140,
  "season": 8
}'
```
返回显示，`少年泰坦出击 (2013)`S01~S08成功订阅

---

## 二、然后再调用`新增订阅api`订阅`彪马实时秀 (2003)`(tmdbid=4419):S01~S22，

```
curl -X 'POST' \
  'http://localhost:43001/api/v1/subscribe/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "tmdbid": 4419,
  "season": 1
}'
```
...
...
...
```
curl -X 'POST' \
  'http://localhost:43001/api/v1/subscribe/' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxxxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "tmdbid": 4419,
  "season": 22
}'
```
现在返回的结果分两种情况：
- S01-S08
显示S01-S08订阅成功，但订阅成功是`少年泰坦出击 (2013)`(tmdbod=45140):S01-S08

- S09-S22
显示S09-S22订阅成功，成功的是`彪马实时秀 (2003)`(tmdbid=4419):S09-S22

也就是说后面所有的调用`新增订阅api`订阅的电视剧的S01~S08都是首次调用`新增订阅api`订阅成功的季度

如果后面再新增一个`电视剧C`的S01-S23的订阅的话，订阅成功的就会是:
`S01-S08`--少年泰坦出击
`S09-S22`--彪马实时秀
`S23`--电视剧C

**Comment by jxxghp** [comment]
最好同时提供title和year，否则缓存会出错。这个发现可能跟 #984 也有关系。
