### ISSUE TITLE
[错误报告]: HDSky天空站更新了签到方式。原先的签到不能用了

### ISSUE THREAD

**Issue by oynt** [jxxghp/MoviePilot#1481]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

【天空】站签到会失败。提示【签到失败：未获取到验证码】

**Comment by jxxghp** [comment]
加了请求头及日志，更新插件到1.3.1后再试试看

**Comment by wjw054509** [comment]
啥时候能更新啊

**Comment by oynt** [comment]
> 加了请求头及日志，更新插件到1.3.1后再试试看

插件有更新了吗？
我删除插件后重装插件，插件版本仍然显示是1.3

**Comment by jxxghp** [comment]
> > 加了请求头及日志，更新插件到1.3.1后再试试看
> 
> 插件有更新了吗？ 我删除插件后重装插件，插件版本仍然显示是1.3

现在更新了

**Comment by oynt** [comment]
非常感谢大佬&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jxxghp/MoviePilot] [错误报告]: HDSky天空站更新了签到方式。原先的签到不能用了 (Issue #1481)





   
加了请求头及日志，更新插件到1.3.1后再试试看
  
插件有更新了吗？ 我删除插件后重装插件，插件版本仍然显示是1.3
  
现在更新了

**Comment by oynt** [comment]
OCR识别好像有问题，这个验证码链接我验证了是正确的



&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月20日(星期二) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [jxxghp/MoviePilot] [错误报告]: HDSky天空站更新了签到方式。原先的签到不能用了 (Issue #1481)





   
加了请求头及日志，更新插件到1.3.1后再试试看
  
插件有更新了吗？ 我删除插件后重装插件，插件版本仍然显示是1.3
  
现在更新了

**Comment by wjw054509** [comment]
我更新后，显示签到成功，实际还是未完成签到

**Comment by oynt** [comment]
【INFO】2024-02-21 10:51:30,232 - hdsky.py - 获取到 天空 验证码链接：https://hdsky.me/image.php?action=regimage&imagehash=3d356bb5572ef6eb919bbb353ef19a60
【INFO】2024-02-21 10:51:31,681 - hdsky.py - OCR识别 天空 验证码：
【INFO】2024-02-21 10:51:31,682 - hdsky.py - OCR识别 天空 验证码失败，正在进行重试，目前重试次数：1
【INFO】2024-02-21 10:51:34,268 - hdsky.py - OCR识别 天空 验证码：
【INFO】2024-02-21 10:51:34,268 - hdsky.py - OCR识别 天空 验证码失败，正在进行重试，目前重试次数：2
【INFO】2024-02-21 10:51:36,776 - hdsky.py - OCR识别 天空 验证码：
【INFO】2024-02-21 10:51:36,777 - hdsky.py - OCR识别 天空 验证码失败，正在进行重试，目前重试次数：3
【INFO】2024-02-21 10:51:39,372 - hdsky.py - OCR识别 天空 验证码：
【INFO】2024-02-21 10:51:39,373 - hdsky.py - OCR识别 天空 验证码失败，正在进行重试，目前重试次数：4
【ERROR】2024-02-21 10:51:40,373 - hdsky.py - 天空 签到失败：未获取到验证码

**Comment by thsrite** [comment]
@oynt 自建ocr服务器
添加环境变量OCR_HOST

**Comment by oynt** [comment]
我试试。openwrt修改环境变量，是不是只能新建一个容器？
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月21日(星期三) 中午11:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/MoviePilot] [错误报告]: HDSky天空站更新了签到方式。原先的签到不能用了 (Issue #1481)





 
@oynt 自建ocr服务器
 添加环境变量OCR_HOST

**Comment by yejialiango** [comment]
> 我试试。openwrt修改环境变量，是不是只能新建一个容器？ &nbsp; &nbsp;

可以装个portainer管理容器，方便很多
