### ISSUE TITLE
[错误报告]: 在WEB管理界面中关闭“开启订阅定时搜索”选项会导致容器无法启动

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/MoviePilot#1487]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

关闭该设置项，app.env中显示为SUBSCRIBE_SEARCH=''，缺失false，将导致容器无法识别任何媒体信息，重新启动容器发现无法启动。

### 发生问题时系统日志和配置文件

```bash
使用代理更新程序
Release 更新模式
当前版本号：v1.6.4
最新版本号：v1.6.4
未发现新版本，跳过更新步骤...
usermod: no changes
Traceback (most recent call last):
  File "/app/app/main.py", line 19, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 391, in <module>
    settings = Settings(
               ^^^^^^^^^
  File "/app/app/core/config.py", line 373, in __init__
    super().__init__(**kwargs)
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
SUBSCRIBE_SEARCH
  value could not be parsed to a boolean (type=type_error.bool)
```

**Comment by honue** [comment]
环境变量没删掉这个键值，而且填错了值

**Comment by honue** [comment]
确实有问题，我改改

**Comment by gravitation-ch** [comment]
> 确实有问题，我改改

1.6.4更新到1.6.5的过程中，启动仍会报这个错。手动再env中添加false，才能正常启动。
