### ISSUE TITLE
[Feature Request]: 能否让刷流插件也支持辅种

### ISSUE THREAD

**Issue by goxofy** [jxxghp/MoviePilot#1490]
### 当前程序版本

1.6.4

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

希望能让刷流插件也支持辅种，现在刷流插件对于同一个完全相同内容的种子会多次下载，会浪费很多带宽

**Comment by jxxghp** [comment]
只要数据文件没被删掉，同一个种子文件同一个目录，不会重新下载呀（下载器会校验并直接完成）。如果被删掉了那肯定要重新下载，要看你规则怎么设置的。

**Comment by goxofy** [comment]
> 只要数据文件没被删掉，同一个种子文件同一个目录，不会重新下载呀（下载器会校验并直接完成）。如果被删掉了那肯定要重新下载，要看你规则怎么设置的。

噢明白了，谢谢大佬
