### ISSUE TITLE
系统-下载器  QB设置里的 自动分类管理（开关）与  系统-媒体库 下载目录设置里的 下载目录自分类（开关）组合开启差异

### ISSUE THREAD

**Issue by 705058548** [jxxghp/MoviePilot#1493]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

  a、只开启自动分类管理（开关）：只按 电影 电视剧 动漫 三类进行目录分配，无下级细分目录
  b、只开启下载目录自分类（开关）：按 电影/华语电影。。。 进行目录分配，合理，是想要的效果，可以qb软件里的分类为空了
  c、同时开启：按 华语电影（没/电影的上级目录了）。。。虽然qb软件里有了分类显示，但目录少了一级
问：如何设置既可以按 ‘’电影/华语电影‘’这样两级目录分配地址，又可以在qb软件里正常显示分类。目前怎么组合，都有些问题，是否为bug？

### 发生问题时系统日志和配置文件

```bash
日志和配置文件均正常，就不上传了
只是配置不出想要的效果
```

**Comment by cng10001** [comment]
不管怎么配置我都没法开启二级分类，请教下，我想是不是描述说的需要在qb提前创建分类我没做
但是这个提前创建分类是什么意思呢
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/a10dacae-ae81-4d45-a246-ad0c23f1a27b)

**Comment by 705058548** [comment]
就是需要提前再QB下载器里，创建好分类目录，qb管理页面，左侧栏目，有个分类的栏目，您找下
