### ISSUE TITLE
[错误报告]: 插件 开启 《下载任务分类与标签》自动设置分类 出提示错误

### ISSUE THREAD

**Issue by dwwl886** [jxxghp/MoviePilot#1497]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.5

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

系统没有升级前 自动分类是正常的  升级后  发现 不能自动分类了  在qb也创建了分类标签

### 发生问题时系统日志和配置文件

```bash
INFO	23:28:15,854	
downloadsitetag
[DownloadSiteTag] 开始执行: 补全下载历史的标签与分类 ...
INFO	23:28:15,854	
downloadsitetag
[DownloadSiteTag] 开始扫描下载器 qbittorrent ...
INFO	23:28:16,527	
downloadsitetag
[DownloadSiteTag] 下载器 qbittorrent 种子数：2019
ERROR	23:28:16,540	
base.py
Job "DownloadSiteTag._complemented_history (trigger: date[2024-02-19 23:28:15 CST], next run at: 2024-02-19 23:28:15 CST)" raised an exception
```

**Comment by dwwl886** [comment]
之前开启这个功能  会自动在qb创建二级分类   现在 不支持自动创建了     还必须在qb手动先创建分类   请问管理 如果能恢复到以前的功能

**Comment by jxxghp** [comment]
@cikezhu

**Comment by cikezhu** [comment]
该版本日志信息过少, 无法判断问题所在. 使用新版本v1.6再次遇到问题时提供详细日志

**Comment by dwwl886** [comment]
问题找到了  不是 插件的问题 是 配置出现问题
