### ISSUE TITLE
[Feature Request]: 希望添加微信默认自动下载选项

### ISSUE THREAD

**Issue by wq2020wdm** [jxxghp/MoviePilot#150]
### 当前程序版本

1.0.1

### 功能改进

希望能添加个变量，和nt一样，微信搜索后自动开始下载，而不是需要选择站点资源或者输入0自动下载，这样使用习惯不变

**Comment by thsrite** [comment]
片面了，可设置某个消息渠道某个用户名自动下载，其他没设置的照旧
这样比较好

**Comment by wq2020wdm** [comment]
> 片面了，可设置某个消息渠道某个用户名自动下载，其他没设置的照旧 这样比较好

这样是更好，还有就是谁添加的下载能加上吗？现在推送的下载不知道是哪个微信用户添加的

**Comment by MichaelYXQ** [comment]
搜索下载不到的最好可以直接转为订阅。

**Comment by thsrite** [comment]
#266
