### ISSUE TITLE
历史记录删除问题

### ISSUE THREAD

**Issue by 17612587** [jxxghp/MoviePilot#1500]
### 当前程序版本

v1.6.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

历史记录删除老卡死，没办法一次清理所有历史记录，使用中经常需要删除说有历史记录，重新刮削转移，希望可以增加一个一键删除所有历史记录功能，现在的删除数量一多久卡死，不适应

**Comment by 17612587** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/157581189/00bb03d3-74d8-4a30-9f95-9f1a666f9614)
删除了1上午还有2万多条，实在是删除不动了，而且删除途中他还在刮削转移，无止境的循环，希望尽快增加一个一键删除所有历史记录功能

**Comment by 1525745393** [comment]
解决了没

**Comment by 17612587** [comment]
解决了配置文件导入数据库软件手动删除再把配置文件导入MP

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月31日 03:34 |
| 收件人 | jxxghp/MoviePilot ***@***.***> |
| 抄送人 | 17612587 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jxxghp/MoviePilot] 历史记录删除问题 (Issue #1500) |

解决了没

**Comment by InfinityPacer** [comment]
@1525745393 已经有一键删除插件了

**Comment by 1525745393** [comment]
> @1525745393 已经有一键删除插件了 
插件名是什么，晚上试一下

**Comment by 1525745393** [comment]
> 解决了配置文件导入数据库软件手动删除再把配置文件导入MP
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 发送日期 | 2024年05月31日 03:34 |
> | 收件人 | jxxghp/MoviePilot ***@***.***> |
> | 抄送人 | 17612587 ***@***.***>,
> Author ***@***.***> |
> | 主题 | Re: [jxxghp/MoviePilot] 历史记录删除问题 (Issue #1500) |
> 
> 解决了没
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

我的是群晖套件版的 配置文件名是什么
