### ISSUE TITLE
通过设定-站点-站点同步功能修改cloudcookies的key和密钥不成功

### ISSUE THREAD

**Issue by Johnhpure** [jxxghp/MoviePilot#1505]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

安装docker镜像时设定了key和密钥，但已失效，需要修改，故通过设定-站点-站点同步功能修改cloudcookies的key和密钥，修改后重启docker镜像，key和密钥的值依然为安装时所设定的，修改不成功。

**Comment by jxxghp** [comment]
配置项生效优先级：环境变量 > env文件（或通过WEB界面配置） > 默认值。
