### ISSUE TITLE
[Feature Request]: 希望增加tmdb与douban的融合来源

### ISSUE THREAD

**Issue by faithleysath** [jxxghp/MoviePilot#1508]
### 当前程序版本

1.6.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

使用tmdb完成大部分挂削，使用douban完成演职人员的刮削。对于分集的演职人员表，douban没有，还是用tmdb。

**Comment by Akimio521** [comment]
这样可能造成无法找到同一个演员的所有电影、电视剧
