### ISSUE TITLE
[错误报告]: 升级V1.6.6版本后 重命名格式不再按要求执行了

### ISSUE THREAD

**Issue by bigdongdongCLUB** [jxxghp/MoviePilot#1513]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

升级v1.6.6以后 
重命名格式 并没有按照我所要求的那样执行。

我的命名要求如下
![WX20240221-125411@2x](https://github.com/jxxghp/MoviePilot/assets/43647204/9484d01a-4f68-4d86-85d8-44c0c74853e5)

而实际实际是这样的，应该没有“第几集”字样才对吧
![WX20240221-125500@2x](https://github.com/jxxghp/MoviePilot/assets/43647204/c5b5a2c2-aef3-41a6-8d6d-737823dc9cd1)

**Comment by shixiaolong777** [comment]
环境变量 > env文件（或通过WEB界面配置） > 默认值。 检查下这个，或者清理浏览器cookie
