### ISSUE TITLE
[错误报告]: 站点更新时不填验证码报错

### ISSUE THREAD

**Issue by wkeylin** [jxxghp/MoviePilot#1516]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

站点未开启两步验证，则不需要填验证码，但是不填验证码，站点更新又报错

### 发生问题时系统日志和配置文件

```bash
2024-02-21T07:13:41.040038354Z ERROR:   twofa.py - 计算动态验证码失败：argument should be a bytes-like object or ASCII string, not 'NoneType'
```
```

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot/pull/1515/files
