### ISSUE TITLE
重命名问题 重命名设置源文件名但是会重命名为替换词以后的文件名

### ISSUE THREAD

**Issue by pikaqiu2222** [jxxghp/MoviePilot#1518]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

original_name： 原文件名（包括文件外缀）
实际上是替换词之后的名字列如
源文件名是[SBSUB][CONAN][1111][1080P][HEVC_AAC][CHS_CHT_JP](F42D0C73).mkv
替换词是\[CONAN\] => 名侦探柯南
重命名规则是
TV_RENAME_FORMAT=[tmdbid={{tmdbid}}]/Season {{season}}[{{releaseGroup}}]/{{season_episode}} - {{original_name}}
那应该是S01E1111 - [SBSUB][CONAN][1111][1080P][HEVC_AAC][CHS_CHT_JP](F42D0C73).mkv才是正确的吧
实际上重命名后是如下名字
S01E1111 - [SBSUB]名侦探柯南[1111][1080P][HEVC_AAC][CHS_CHT_JP](F42D0C73).mkv
这个是否属于正常以前用你另一款软件时是正确的

**Comment by cng10001** [comment]
“是”替换过后的名字

**Comment by jxxghp** [comment]
v1.8.3会修复
