### ISSUE TITLE
[Feature Request]: Radarr / Sonarr 支持 LunaSea

### ISSUE THREAD

**Issue by happyeddie** [jxxghp/MoviePilot#152]
### 当前程序版本

v1.0.1

### 功能改进

从 Readme 中看到已经支持了模拟 Radarr / Sonarr，超赞！！！

但是 iOS 中目前唯一可用的 arr Client LunaSea，好像并不能接入这个
可以正常添加，但是无法读取到订阅，也不能搜索，貌似接口报 404

期待支持

**Comment by insomnia417** [comment]
+1,期待更好的支持 
现在只有初步支持,仅仅是单向的从overseerr/jellyseerr发送给MP,其他功能还得填

**Comment by 2284787774** [comment]
Radarr / Sonarr的api密钥是哪个变量，我用API_TOKEN的没办法连上

**Comment by happyeddie** [comment]
> Radarr / Sonarr的api密钥是哪个变量，我用API_TOKEN的没办法连上

就是 API_TOKEN

**Comment by 2284787774** [comment]
![微信截图_20230820164604](https://github.com/jxxghp/MoviePilot/assets/26424174/7043cbef-2db1-4a67-8390-ee8d3e848d61)
![微信截图_20230820164538](https://github.com/jxxghp/MoviePilot/assets/26424174/be9b92a9-4930-436c-a6d6-12fab25da901)
能帮我看看我哪里没设置对吗，一直连不上

**Comment by 2284787774** [comment]
> 

![微信截图_20230820164943](https://github.com/jxxghp/MoviePilot/assets/26424174/353e9f59-a740-46d4-bfbd-4ed17c129ec6)

**Comment by yipapa** [comment]
> ![微信截图_20230820164604](https://user-images.githubusercontent.com/26424174/261841532-7043cbef-2db1-4a67-8390-ee8d3e848d61.png) ![微信截图_20230820164538](https://user-images.githubusercontent.com/26424174/261841534-be9b92a9-4930-436c-a6d6-12fab25da901.png)能帮我看看我哪里没设置对吗，一直连不上

请问解决了么，我也遇到了同样得问题

**Comment by mjsoftking** [comment]
> 
端口填写3300试一下呢

**Comment by mjsoftking** [comment]
> > ![微信截图_20230820164604](https://user-images.githubusercontent.com/26424174/261841532-7043cbef-2db1-4a67-8390-ee8d3e848d61.png) ![微信截图_20230820164538](https://user-images.githubusercontent.com/26424174/261841534-be9b92a9-4930-436c-a6d6-12fab25da901.png)能帮我看看我哪里没设置对吗，一直连不上
> 
> 请问解决了么，我也遇到了同样得问题

端口填写3300试一下呢

**Comment by 2284787774** [comment]
> > > ![微信截图_20230820164604](https://user-images.githubusercontent.com/26424174/261841532-7043cbef-2db1-4a67-8390-ee8d3e848d61.png) ![微信截图_20230820164538](https://user-images.githubusercontent.com/26424174/261841534-be9b92a9-4930-436c-a6d6-12fab25da901.png)能帮我看看我哪里没设置对吗，一直连不上
> > 
> > 
> > 请问解决了么，我也遇到了同样得问题
> 
> 端口填写3300试一下呢

试过了，都不行mp和overseerr用的都是host网络

**Comment by mjsoftking** [comment]
> > > > ![微信截图_20230820164604](https://user-images.githubusercontent.com/26424174/261841532-7043cbef-2db1-4a67-8390-ee8d3e848d61.png) ![微信截图_20230820164538](https://user-images.githubusercontent.com/26424174/261841534-be9b92a9-4930-436c-a6d6-12fab25da901.png)能帮我看看我哪里没设置对吗，一直连不上
> > > 
> > > 
> > > 请问解决了么，我也遇到了同样得问题
> > 
> > 
> > 端口填写3300试一下呢
> 
> 试过了，都不行mp和overseerr用的都是host网络

现在确实连不上，报错404找不到了

**Comment by happyeddie** [comment]
> > > > > ![微信截图_20230820164604](https://user-images.githubusercontent.com/26424174/261841532-7043cbef-2db1-4a67-8390-ee8d3e848d61.png) ![微信截图_20230820164538](https://user-images.githubusercontent.com/26424174/261841534-be9b92a9-4930-436c-a6d6-12fab25da901.png)能帮我看看我哪里没设置对吗，一直连不上
> > > > 
> > > > 
> > > > 请问解决了么，我也遇到了同样得问题
> > > 
> > > 
> > > 端口填写3300试一下呢
> > 
> > 
> > 试过了，都不行mp和overseerr用的都是host网络
> 
> 现在确实连不上，报错404找不到了

好像新版本解决了这个问题

**Comment by mjsoftking** [comment]
@happyeddie 确实是好使了

@2284787774 新版可以添加了

**Comment by madswaord** [comment]
> @happyeddie 确实是好使了
> 
> 
> 
> @2284787774 新版可以添加了

你们端口填的是什么 3001还是3000还是3000映射出去的端口号

**Comment by jeavenchu** [comment]
容器里的3001端口映射出来才行
