### ISSUE TITLE
[错误报告]: 日志里面一直报错jellyfin

### ISSUE THREAD

**Issue by dwwl886** [jxxghp/MoviePilot#1520]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

那位大神知道  这个错误正常吗

### 发生问题时系统日志和配置文件

```bash
ERROR	00:25:53,188	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:53,188	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
INFO	00:25:53,527	
transfer.py
没有获取到已完成的下载任务
ERROR	00:25:54,189	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:54,190	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:25:55,199	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:55,200	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:25:56,198	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:56,198	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:25:57,201	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:57,202	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:25:58,197	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:58,197	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:25:59,181	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:25:59,181	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:26:00,197	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:26:00,198	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:26:01,175	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:26:01,176	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:26:01,191	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:26:01,192	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
ERROR	00:26:02,193	
jellyfin.py
Items/RemoteImages 未获取到返回数据
INFO	00:26:02,194	
command.py
处理事件：webhook.message - [<function MediaServerMsg.send at 0x7f7e192f2840>, <function MediaSyncDel.sync_del_by_webhook at 0x7f7e192e0a40>, <function MediaSyncDel.sync_del_by_plugin at 0x7f7e192e0ae0>]
```

**Comment by jxxghp** [comment]
没有jellyfin环境，有环境的小伙伴帮忙调试下

**Comment by soongkkxx** [comment]
我也遇到同样的问题。当Jellyfin镜像是nyanmisaka/jellyfin时，日志就会报错，如下：
> INFO:    singleton.py - 站点资源版本：1.1.8
INFO:    singleton.py - 认证资源版本：1.2.0
INFO:    singleton.py - freefarm 用户认证成功！
INFO:    resource.py - 开始检测资源包版本...
INFO:    resource.py - 最新资源包版本：v1.2.4
INFO:    resource.py - 所有资源已最新，无需更新
INFO:    module.py - Moudle Loaded：DoubanModule
INFO:    module.py - Moudle Loaded：FanartModule
INFO:    module.py - Moudle Loaded：FileTransferModule
INFO:    module.py - Moudle Loaded：FilterModule
INFO:    module.py - Moudle Loaded：IndexerModule
ERROR:   jellyfin.py - Users 未获取到返回数据
ERROR:   jellyfin.py - System/Info 未获取到返回数据

但之前配合nastool使用没有问题。
尝试使用原版Jellyfin，也不会报错。

**Comment by cng10001** [comment]
> 我也遇到同样的问题。当Jellyfin镜像是nyanmisaka/jellyfin时，日志就会报错，如下：
> 
> > INFO:    singleton.py - 站点资源版本：1.1.8
> > INFO:    singleton.py - 认证资源版本：1.2.0
> > INFO:    singleton.py - freefarm 用户认证成功！
> > INFO:    resource.py - 开始检测资源包版本...
> > INFO:    resource.py - 最新资源包版本：v1.2.4
> > INFO:    resource.py - 所有资源已最新，无需更新
> > INFO:    module.py - Moudle Loaded：DoubanModule
> > INFO:    module.py - Moudle Loaded：FanartModule
> > INFO:    module.py - Moudle Loaded：FileTransferModule
> > INFO:    module.py - Moudle Loaded：FilterModule
> > INFO:    module.py - Moudle Loaded：IndexerModule
> > ERROR:   jellyfin.py - Users 未获取到返回数据
> > ERROR:   jellyfin.py - System/Info 未获取到返回数据
> 
> 如果将Jellyfin换成原版Jellyfin，就不会报错。 但之前nyanmisaka/jellyfin配合nastool使用没有问题。

原来是镜像原因，我也是这个镜像- -

**Comment by dwwl886** [comment]
一直用这个版本是没有问题的  后来更新后 就报错了

**Comment by Charonics** [comment]
这个问题现在依然存在，只能换镜像解决？

**Comment by cng10001** [comment]
> 这个问题现在依然存在，只能换镜像解决？

nyanmisaka/jellyfin
还是这个镜像，现在没这个报错了

**Comment by Charonics** [comment]
但我依然遇到这个报错，
ERROR:   jellyfin.py - Users 未获取到返回数据
ERROR:   jellyfin.py - System/Info 未获取到返回数据
配置如下：
<img width="1688" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/47098288/c5dbf304-3c44-46af-8089-1d14035de1ce">

**Comment by Charonics** [comment]
> > 这个问题现在依然存在，只能换镜像解决？
> 
> nyanmisaka/jellyfin 还是这个镜像，现在没这个报错了

但我依然遇到这个报错，
ERROR:   jellyfin.py - Users 未获取到返回数据
ERROR:   jellyfin.py - System/Info 未获取到返回数据
配置如下：
<img width="1688" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/47098288/c5dbf304-3c44-46af-8089-1d14035de1ce">

**Comment by JavaZeroo** [comment]
这个问题很奇怪，同样的配置，直接用Python运行就没有办法复现。

**Comment by JavaZeroo** [comment]
> > > > 这个问题现在依然存在，只能换镜像解决？
> > > 
> > > 
> > > nyanmisaka/jellyfin 还是这个镜像，现在没这个报错了
> > 
> > 
> > 但我依然遇到这个报错， ERROR: jellyfin.py - Users 未获取到返回数据 ERROR: jellyfin.py - System/Info 未获取到返回数据 配置如下： <img alt="image" width="1688" src="https://private-user-images.githubusercontent.com/47098288/342377662-c5dbf304-3c44-46af-8089-1d14035de1ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2OTc3ODAsIm5iZiI6MTc0MTY5NzQ4MCwicGF0aCI6Ii80NzA5ODI4OC8zNDIzNzc2NjItYzVkYmYzMDQtM2M0NC00NmFmLTgwODktMWQxNDAzNWRlMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzExVDEyNTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjQ0OTRhYmI2ZGJlMTMxMjFiNGI2MjY5OGUyMWY1MzAyOWIxZGFjZGFkZGRiZGI5ZWQyZGU0M2IzZGE2ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NpNswGJrcSevVw3NFtLfdRYPG26juZz6axm8fT_36co">
> 
> 我也是一样的问题，但是不想使用官方的镜像。该如何解决？

mp里面重新添加jellyfin，注意多余的空格
