### ISSUE TITLE
非管理员用户登陆后点击“正在下载”显示 404

### ISSUE THREAD

**Issue by goxofy** [jxxghp/MoviePilot#1525]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

非管理员用户登陆后在“正在下载”显示 404，但是实际上下载器有正在下载的种子；登陆管理员账户可见。

无论种子是否通过非管理员账户添加都不显示

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/ecdd12f5a95a8992d24d7086b3ee7a7a0f566002

**Comment by yejialiango** [comment]
> [jxxghp/MoviePilot-Frontend@ecdd12f](https://github.com/jxxghp/MoviePilot-Frontend/commit/ecdd12f5a95a8992d24d7086b3ee7a7a0f566002)

老哥，服务端版本我重启已经更新到1.6.9，不过发现普通用户前端还是没显示正在下载，是前端版本没拉到最新的吗

**Comment by goxofy** [comment]
@jxxghp @yejialiango 
我也是一样的，依然看不到正在下载

**Comment by yejialiango** [comment]
新版本修复了，老哥🐂🍺
