### ISSUE TITLE
[错误报告]: 未安装的插件也在页面全部显示，但是打开为空

### ISSUE THREAD

**Issue by sertion1126** [jxxghp/MoviePilot#1533]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

* 未安装的插件也在页面全部显示，但是打开为空

<img width="2403" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/38908547/7392d49b-c0c5-4e9a-99d0-8f2ea7a48925">

* 点击这些未安装的插件，都为空白

<img width="2321" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/38908547/94cc62b2-1c40-46d6-bf94-aa28c29a2b3f">

* 清空缓存刷新也没用！！！！！

### 发生问题时系统日志和配置文件

```bash
没有很明显的日志报错
```

**Comment by jxxghp** [comment]
@sertion1126 前后端刚好升级到了不同的版本导致，下个版本再升级下就好了。
