### ISSUE TITLE
[错误报告]: 文件名称获取剧集编号错误

### ISSUE THREAD

**Issue by lie5860** [jxxghp/MoviePilot#1539]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述
![image](https://github.com/jxxghp/MoviePilot/assets/30894657/607cc3da-516d-4476-ade3-234b74629048)

[[Audiences].Dungeon Meshi - S01E06 (1080p DSNP WEB-DL) [F0D21E47] [COPiUM].mkv.torrent]

这个种子会被识别为e06-e47,导致订阅结束，有什么办法跳过吗

**Comment by cng10001** [comment]
**F0D21E47**
应该是这个特征码的触发了识别的缘故吧， 感觉这个毕不是pt站点的种子吧？算不上普适性问题，换个其他更新快的订阅组就行了

**Comment by lie5860** [comment]
> **F0D21E47** 应该是这个特征码的触发了识别的缘故吧， 感觉这个毕不是pt站点的种子吧？算不上普适性问题，换个其他更新快的订阅组就行了
https://audiences.me/details.php?id=256343&hit=1
是观众的种子 不过不是官种吧 如果可以通过配置的方式解决掉这个问题也行。不知道这种命名有点问题的种子应该如何配置跳过他。

**Comment by cng10001** [comment]
你一定要订阅这个种子吗，这个看上去都没有制作组名称，我不知道这个COPiUM是什么意思，是每个标题都有吗，把这个字写进排除就行了。

**Comment by lie5860** [comment]
> 你一定要订阅这个种子吗，这个看上去都没有制作组名称，我不知道这个COPiUM是什么意思，是每个标题都有吗，把这个字写进排除就行了。

好的 理解了。我屏蔽COPiUM吧。我只是要订阅这部剧，没有特别喜好的组，mp自动匹配到这个种子了。前几集都没问题。我先这样处理。这个提取集数的规则大大们看看是否有优化的空间。不需要调整的话就可以关闭了。

**Comment by cng10001** [comment]
> > 你一定要订阅这个种子吗，这个看上去都没有制作组名称，我不知道这个COPiUM是什么意思，是每个标题都有吗，把这个字写进排除就行了。
> 
> 好的 理解了。我屏蔽COPiUM吧。我只是要订阅这部剧，没有特别喜好的组，mp自动匹配到这个种子了。前几集都没问题。我先这样处理。这个提取集数的规则大大们看看是否有优化的空间。不需要调整的话就可以关闭了。

如果你想固定组的话就也可以**adweb|xxxweb**类似这样关键词写进包含。
其实这个问题很早其他片子也遇到过，有人提的，但不是直接就不能用了，能自己曲线解决的，所以看作者大佬有没有兴趣再研究一下吧。

**Comment by jxxghp** [comment]
搞不定，写识别词屏蔽吧
