### ISSUE TITLE
电影电视剧重命名格式问题

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/MoviePilot#1543]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我使用程序默认的电影电视剧重命名格式进行文件转移没什么问题，但每次只要改成我自己想要的格式就会出错，但自己实在看不出哪里有些错，还烦请大家帮忙看一看。
电影：{{title}}.{{en_title}} ({{year}})/{{title}}.{{en_title}} ({{year}}).{{videoFormat}{{fileExt}}
电视剧：{{title}}.{{en_title}}/Season {{season}}/{{title}}.{{en_title}}.{{season_episode}}.{{videoFormat}{{fileExt}}

**Comment by LGuangming** [comment]
另外十分感谢作者把en_title带回来！！！ 因为这个之前买没切到mp一直用着nt🫡🫡

**Comment by cng10001** [comment]
这不还是粗心啊，一眼看videoformat符号没写全啊

**Comment by LGuangming** [comment]
> 这不还是粗心啊，一眼看videoformat符号没写全啊

真不好意思，此刻感觉我是傻子，多谢提醒！
