### ISSUE TITLE
[错误报告]: 仪表盘显示存储空间已使用和剩余空间均为零，且与默认下载器tr中显示的实际剩余空间量不相符

### ISSUE THREAD

**Issue by MidnightShake** [jxxghp/MoviePilot#155]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.1

### 问题类型

主程序运行问题

### 问题描述

仪表盘显示存储空间已使用和剩余空间均为零，且与默认下载器tr中显示的实际剩余空间量不相符：
存储空间
0.00 B
已使用 0% 🚀

实时速率显示正常实时速率
总上传量：显示为当前会话数据，非累计数据
总下载量：显示为当前会话数据，非累计数据
磁盘剩余空间    0.00 B     ：显示不正常，tr内为显示正常剩余空间。

tr使用版本：
Transmission: 3.00 (bb6b5a062e), RPC: 16
Web Control: 1.6.1 (20200913)
Copyright © 2012-2019 栽培者

重启也未能解决，不知如何处理

**Comment by MidnightShake** [comment]
mp容器内使用的路径映射情况：
主机/存储卷	容器中的路径
/srv/dev-disk-by-uuid-1/docker_data	：docker
/srv/dev-disk-by-uuid-2/media：/media
/srv/dev-disk-by-uuid-1/docker_data/moviepilot/config：/config
/srv/dev-disk-by-uuid-1/docker_data/moviepilot/config：/moviepilot

mp容器的运行环境为：pve底层中的omv虚拟机中的docker容器，tr在同个docker下另一个tr容器中

**Comment by zraxx** [comment]
/srv：/srv
/srv/dev-disk-by-uuid-1/docker_data/moviepilot/config：/config
/srv/dev-disk-by-uuid-1/docker_data/moviepilot：/moviepilot

**Comment by MidnightShake** [comment]
现在正在研究配置路径映射的问题，感觉很可能就是这个原因，谢谢楼上大佬提醒

**Comment by Enderiose** [comment]
> 现在正在研究配置路径映射的问题，感觉很可能就是这个原因，谢谢楼上大佬提醒

我今天复现了一次这个问题，也有可能不是挂载的问题，而是点开了下载器的自动分类管理，打开的时候哦会默认清空媒体库设置
