### ISSUE TITLE
订阅不执行，订阅手动搜索无效

### ISSUE THREAD

**Issue by tsymr** [jxxghp/MoviePilot#1555]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅不更新，手动点击订阅搜索无反应，点击后日志只有------INFO:     192.168.12.183:0 - "GET /api/v1/subscribe/search/31 HTTP/1.1" 200 OK
![image](https://github.com/jxxghp/MoviePilot/assets/11868091/2318b7ab-85a9-4844-8250-35ab7183a39d)
![image](https://github.com/jxxghp/MoviePilot/assets/11868091/3ef3e36c-cf55-499a-a3fd-17ca39bdf7ac)

### 发生问题时系统日志和配置文件

```bash
INFO:     192.168.12.183:0 - "GET /api/v1/subscribe/search/31 HTTP/1.1" 200 OK
```

**Comment by ListenXXK** [comment]
我也遇到了相同的问题 只有重启一下才行

**Comment by tsymr** [comment]
> 我也遇到了相同的问题 只有重启一下才行

重启后只有第一次才有效，第二次执行的时候又不行了，自动订阅也没有

**Comment by tsymr** [comment]
回退到1.6.7功能完好。

**Comment by tsymr** [comment]
> 回退到1.6.7功能完好。

**Comment by tsymr** [comment]
> 我也遇到了相同的问题 只有重启一下才行


回退到1.6.7功能完好。

**Comment by dlovew** [comment]
同样存在这个问题！添加订阅以后不会自动搜索，手动搜索也没用！

**Comment by bestfang** [comment]
一样出现该问题。订阅剧集手动订阅无效。

**Comment by dick86114** [comment]
也遇到了，订阅全部变成了0/xx，无法继续订阅

**Comment by jxxghp** [comment]
重现不了这个问题，看一下有没有更多日志？

**Comment by dlovew** [comment]
> 重现不了这个问题，看一下有没有更多日志？

已经添加的订阅，理论上应该第一次会搜索一次，现在不会搜索。手动搜索，日志没有任何呈现，页面右下角提示发送搜索请求完成

**Comment by jxxghp** [comment]
> > 重现不了这个问题，看一下有没有更多日志？
> 
> 
> 
> 已经添加的订阅，理论上应该第一次会搜索一次，现在不会搜索。手动搜索，日志没有任何呈现，页面右下角提示发送搜索请求完成

非首次添加的订阅正常吗？

**Comment by dlovew** [comment]
> > > 重现不了这个问题，看一下有没有更多日志？
> > 
> > 
> > 已经添加的订阅，理论上应该第一次会搜索一次，现在不会搜索。手动搜索，日志没有任何呈现，页面右下角提示发送搜索请求完成
> 
> 非首次添加的订阅正常吗？

所有已经添加的订阅，随便点一个手动搜索，日志没有任何相关输出，没有任何检索的动作

**Comment by Griselda-droid** [comment]
> > > 重现不了这个问题，看一下有没有更多日志？
> > 
> > 
> > 已经添加的订阅，理论上应该第一次会搜索一次，现在不会搜索。手动搜索，日志没有任何呈现，页面右下角提示发送搜索请求完成
> 
> 非首次添加的订阅正常吗？
docker重启后执行以下操作：
首次添加订阅后无反应，不会自动搜索。
![image](https://github.com/jxxghp/MoviePilot/assets/136452331/da10076d-f875-4d9a-a5c5-ee01fbbefcb5)
手动搜索之前添加的订阅可以正常搜索，随后点击新增的订阅搜索出现无反应。再次点击之前订阅的搜索同样无反应了
![image](https://github.com/jxxghp/MoviePilot/assets/136452331/0b71c9fc-1df6-4e66-8221-330a0bf613b9)
![image](https://github.com/jxxghp/MoviePilot/assets/136452331/9658db82-c4da-47e4-8c0b-dd8274a273bb)

**Comment by jxxghp** [comment]
@Griselda-droid 试下更新到dev看看问题是否仍存在

**Comment by Griselda-droid** [comment]
> @Griselda-droid 试下更新到dev看看问题是否仍存在
下载的v1.6.8-2版本，显示v1.6.8-1
使用该版本问题依然一样，重启后只能手动搜索一次。第二次搜索没反应。
我有两台设备安装了mp，无法安装Chromium 114.0.5735.35的无法使用，安装成功的可以正常使用订阅。不知道是否有关联，因为以前版本没有出现这种情况。
以下是无法安装Chromium的报错信息：
Error: Failed to download Chromium 114.0.5735.35 (playwright build v1064), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/usr/local/lib/python3.11/site-packages/playwright/driver/package/lib/server/registry/browserFetcher.js:95:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by jxxghp** [comment]
已找到原因，关联 #1535
