### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by richard-guan-dev** [jxxghp/MoviePilot#1557]
### 当前程序版本

any

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

sites 是否可提供M1 arm的版本？ 谢谢！

**Comment by jxxghp** [comment]
@richard-guan-dev 有了呀

**Comment by Iongtao** [comment]
> @richard-guan-dev 有了呀

docker有arm版吗，nas无法使用
