### ISSUE TITLE
[错误报告]: 历史记录中删除，同步删除文件不起作用

### ISSUE THREAD

**Issue by MichaelYXQ** [jxxghp/MoviePilot#156]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.1

### 问题类型

主程序运行问题

### 问题描述

如题，历史记录中删除，同步删除文件不起作用。
选择同步删除文件后，不论是qBittorrent中的下载，还是硬链接的媒体文件，都没有被删除。

**Comment by dlovew** [comment]
如果安装打开了媒体同步删除插件，在媒体库删除资源，会同步删除源文件和种子！你的需求和正常人的逻辑反过来了！

**Comment by jxxghp** [comment]
下个版本修复
