### ISSUE TITLE
[错误报告]: 订阅问题

### ISSUE THREAD

**Issue by whiaon** [jxxghp/MoviePilot#1569]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.6.8-fix

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

![未命名图片](https://github.com/jxxghp/MoviePilot/assets/46858283/016f9084-0bc4-45bc-bb93-d5447ea2a9a7)
![Snipaste_2024-03-01_17-15-17](https://github.com/jxxghp/MoviePilot/assets/46858283/4c2896b5-6a02-4890-b360-29d319cd0b32)

电视剧订阅历史记录删除媒体和源再次更新下载 日志显示已经下载过无法再次订阅下载删除后的剧集

**Comment by jxxghp** [comment]
重新订阅或者使用插件清理掉订阅的缓存。
这个是防重机制。
