### ISSUE TITLE
[错误报告]: 名称识别错误，个别电影识别为电视剧

### ISSUE THREAD

**Issue by lzcer** [jxxghp/MoviePilot#1576]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.8-fix

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

名称识别错误，个别电影识别为电视剧
目前遇到一个：Home.Alone.2.Lost.In.New.York.1992.Bluray.1080p.x265.10bit.2Audio.MNHD-FRDS.mkv
识别为Footballers' Wives
多次尝试及重启后尝试结果相同

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-03 09:38:45,999 - themoviedb - Home Alone 2 Lost In New York 使用TMDB识别缓存：Footballers' Wives
【INFO】2024-03-03 09:38:45,999 - tmdbapi.py - 正在查询TMDB电视剧：772 ...
【INFO】2024-03-03 09:38:47,400 - tmdbapi.py - 772 查询结果：Footballers' Wives
【INFO】2024-03-03 09:38:47,401 - themoviedb - Home Alone 2 Lost In New York TMDB识别结果：电视剧 Footballers' Wives (2002) 772
【INFO】2024-03-03 09:38:47,791 - media.py - Home.Alone.2.Lost.In.New.York.1992.Bluray.1080p.x265.10bit.2Audio.MNHD-FRDS.mkv 识别到媒体信息：电视剧 Footballers' Wives (2002)
【WARNING】2024-03-03 09:38:49,110 - fanart - 没有获取到 Footballers' Wives (2002) 的fanart图片数据
```

**Comment by lzcer** [comment]
清除TMDB缓存后可以正确识别了，不过不清楚是否还会触发，先不关吧

**Comment by cng10001** [comment]
个人正常
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/226de9d1-554f-4b99-aecb-1b6fce81733b)

**Comment by smilexiaoyan** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/30305781/39fdc76a-10fc-42e8-a6aa-75d49255e998)
![image](https://github.com/jxxghp/MoviePilot/assets/30305781/12b597dd-8fee-4713-8455-46ad284b525a)

我也遇到了同样的问题，在名称识别测试的时候是可以识别正确的，但是到了文件转移的时候就识别错误了。还有很多在名称识别测试的时候可以正常识别到，但是转移的时候就找不到媒体信息转移失败了，见下图。

![image](https://github.com/jxxghp/MoviePilot/assets/30305781/7122fcd6-f207-4408-bd3c-ed329e5ce798)

**Comment by fx1492** [comment]
我最近也是遇到这个问题。电影在自动识别的时候总被识别为电视剧，然后就转移失败；如果指定TMDBID，手动整理又能成功。仔细看日志，其实程序识别了电影的TMDBID，但是又连接了电视剧的API。

**Comment by fx1492** [comment]
我最近也是遇到这个问题。电影在自动识别的时候总被识别为电视剧，然后就转移失败；如果指定TMDBID，手动整理又能成功。仔细看日志，其实程序识别了电影的TMDBID，但是又连接了电视剧的API。

**Comment by jxxghp** [comment]
后面做了些调整，升级最新版本还有再贴日志重提吧。

**Comment by cng10001** [comment]
American Beauty 1999 Paramount Blu-ray 1080p AVC DTS-HD MA 5.1-blucook#262@CHDBits

> > 后面做了些调整，升级最新版本还有再贴日志重提吧。
> 
> @jxxghp 作者您好，最新版我已测试过，还是存在问题。我使用代码测试了一下，直接识别文件名是没有问题的，路径识别是有问题的，原因是由于我下载的是合集，里面有一些目录层级，比如一个未识别到的路径`/media/downloads/movie/李连杰 全集/李连杰.Jet.Li.1982-2016.BluRay.1080p.x265.10bit.2Audio.MNHD-FRDS/狼犬丹尼4.06/Unleashed.2005.BluRay.1080p.x265.10bit.3Audio.MNHD-FRDS.mkv`，这个文件的父目录为`狼犬丹尼4.06`，由于后面的数字，识别的时候将父母录识别为了电视剧，搜索的时候取匹配电视剧导致匹配失败。 <img alt="image" width="1678" src="https://private-user-images.githubusercontent.com/30305781/323489446-e4ec1af1-3240-48c8-ad76-dfe77ef2d384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU0MDQsIm5iZiI6MTcxMzc2NTEwNCwicGF0aCI6Ii8zMDMwNTc4MS8zMjM0ODk0NDYtZTRlYzFhZjEtMzI0MC00OGM4LWFkNzYtZGZlNzdlZjJkMzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwYWFkMDBiNGEyZTVmYWVkYjEzNTg3MmZmMTMwNmY5NmVjMzdmZWE4NWI2MTE5ZTA4NTU3OWEyMzdhOGU1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FxfC0nVWy8vDD194GLkTMQMwQwznS2qiny8RodPJ0_o">
> 
> 若将父路径后面的数字去除，识别成功： <img alt="image" width="1324" src="https://private-user-images.githubusercontent.com/30305781/323461286-1b1dc60e-ddca-4db5-a928-2a1be002ce93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU0MDQsIm5iZiI6MTcxMzc2NTEwNCwicGF0aCI6Ii8zMDMwNTc4MS8zMjM0NjEyODYtMWIxZGM2MGUtZGRjYS00ZGI1LWE5MjgtMmExYmUwMDJjZTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZjkyMzk0MjlkZmE5ZWY4YmQyNzE1NzY3NjcxN2U1ZjJkOGYzZGRkMjk4ZDUwZGRlZmIyZDJhNDUxOTZiMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZaXgKMoJe-IaKPrlU80yS87dPMoBiwPM4b_4oqBelks">
> 
> 还测试了另外一种方案，在recognize_by_path()方法中加入透传给recognize_media()方法的mtype参数，并在识别路径的时候规定mtype=MediaType.MOVIE <img alt="image" width="826" src="https://private-user-images.githubusercontent.com/30305781/323492536-16564b05-42ef-4ce2-ba17-8d3dddf57fe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU0MDQsIm5iZiI6MTcxMzc2NTEwNCwicGF0aCI6Ii8zMDMwNTc4MS8zMjM0OTI1MzYtMTY1NjRiMDUtNDJlZi00Y2UyLWJhMTctOGQzZGRkZjU3ZmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMzFmMzJmNWU4NWI1NTlmZGQyZTM0NmJhMmRhNmQyMjZjZGRkOWIyYjJiNjU5MzRiMzRiZDUyODYwNTk2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJLKdnhQbsjo1hkj3CvUSgYN6rrbNdKrFAIxjGmv71s"> 这样也可以识别成功 <img alt="image" width="1731" src="https://private-user-images.githubusercontent.com/30305781/323493024-8d766af6-42a1-411a-ba8c-ab2a61828377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjU0MDQsIm5iZiI6MTcxMzc2NTEwNCwicGF0aCI6Ii8zMDMwNTc4MS8zMjM0OTMwMjQtOGQ3NjZhZjYtNDJhMS00MTFhLWJhOGMtYWIyYTYxODI4Mzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1NTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2YyOTFmNDQ3OWQ1ZDdiNzZmMGMwMDkxZGU3MzBiZGUwZjAxNGNmMGY5ZTIyZWYzMzExZWYyYTA2YWM4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RB3Oac7t5fv5lNGebAOC2sWrT_qFtM6-k1ZX5xZexR4">
> 
> 所以希望在目录监控插件里可以规定监控目录的媒体类型，这样可以完美解决此类问题。

这么厉害。
看看我这个呢，也是名称识别的时候是对的，转移也变电视剧了，是不是后面有数字就会被影响
_**American Beauty 1999 Paramount Blu-ray 1080p AVC DTS-HD MA 5.1-blucook#262@CHDBits**_

**Comment by smilexiaoyan** [comment]
> 这么厉害。 看看我这个呢，也是名称识别的时候是对的，转移也变电视剧了，是不是后面有数字就会被影响 _**American Beauty 1999 Paramount Blu-ray 1080p AVC DTS-HD MA 5.1-blucook#262@CHDBits**_

看看你的完整路径，`American Beauty 1999 Paramount Blu-ray 1080p AVC DTS-HD MA 5.1-blucook#262@CHDBits`这个识别是没有问题的

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/87692e35-20bd-4a98-b037-ce53208b1d60)
没有特别多目录，就一个文件夹里面一个ISO原盘

**Comment by smilexiaoyan** [comment]
> ![image](https://private-user-images.githubusercontent.com/115156545/324350685-87692e35-20bd-4a98-b037-ce53208b1d60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzcwNDAsIm5iZiI6MTcxMzc3Njc0MCwicGF0aCI6Ii8xMTUxNTY1NDUvMzI0MzUwNjg1LTg3NjkyZTM1LTIwYmQtNGE5OC1iMDM3LWNlNTMyMDhiMWQ2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwOTA1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTg5NDgzYWRiZjJlYTFmNWFlZTA0OGZhMWFkM2NmYjliZDVkNmJmM2Q3MzUwMDVmZWM1YzMyM2FkODAwMGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TEMzlfhd-W8fFjdB3vF461lcuDF3JvbA3yOrRy_n2nw) 没有特别多目录，就一个文件夹里面一个ISO原盘

确实，也是同样的问题，不过你的是媒体文件本身就被识别成电视剧了。
