### ISSUE TITLE
[错误报告]: 目录监控插件报错

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#1577]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.8-fix

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

通过目录监控插件入库，无意中发现插件日志报错，但是文件能正常硬链接入库
补充：不是每一集刮削都有这个报错，部分有部分没有

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-03-03 11:08:37,909 - scraper.py - /volume2/Media/Hlink/Comic/日番/小不点 (2023)/Season 1/小不点.S01E19.2023.1080p.WEB-DL-ADWeb.mp4 刮削失败：expected str, bytes or os.PathLike object, not NoneType
【INFO】2024-03-03 11:08:37,910 - themoviedb - /volume2/Media/Hlink/Comic/日番/小不点 (2023)/Season 1/小不点.S01E19.2023.1080p.WEB-DL-ADWeb.mp4 刮削完成
```

**Comment by jxxghp** [comment]
下个版本修复
