### ISSUE TITLE
[Feature Request]: tmdbapi获取人物详情是否可以加入缓存

### ISSUE THREAD

**Issue by urzz** [jxxghp/MoviePilot#1581]
### 当前程序版本

v1.6.8-fix

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

在整理文件时，开启演职人员刮削插件，日志中显示一直在调用tmdbapi查询演员详情。这个查询频次，是否可以考虑在查询完后加入本地缓存，加快整理速度哈
![image](https://github.com/jxxghp/MoviePilot/assets/11271721/1a15ae9c-fa3b-44b7-b35d-9b0367694e3c)

**Comment by jxxghp** [comment]
1、tmdb api都是有缓存的，使用的是LRU，开启大内存模式时，缓存数量会增加。
2、出现这个日志并不代码就没有使用缓存。

**Comment by urzz** [comment]
> 1、tmdb api都是有缓存的，使用的是LRU，开启大内存模式时，缓存数量会增加。 2、出现这个日志并不代码就没有使用缓存。

好的，之前翻代码没往里面看，感谢
