### ISSUE TITLE
[建议]:建议新增目录映射功能，以实现win qb 与 docker moviepilot 协同

### ISSUE THREAD

**Issue by pengfei9403** [jxxghp/MoviePilot#1582]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.8-fix

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

由于个人原因无法运行windows版本moviepilot，使用docker版本，qb使用windows版本，qb使用docker版本时会导致磁盘异常占用。系统为windowsServer,期望加入目录映射，使qb与moviepilot协同工作，之前nastool是有此项配置的，下载使用windows目录，资源识别使用docker目录

**Comment by happyTonakai** [comment]
我的理解，mp 设定-系统-下载目录 里面的设置的目录会直接发送给qb，不是mp的目录，所以你直接填写qb能识别的目录即windows目录就行了

**Comment by 522654518** [comment]
> 我的理解，mp 设定-系统-下载目录 里面的设置的目录会直接发送给qb，不是mp的目录，所以你直接填写qb能识别的目录即windows目录就行了

我也是同样的问题，但是这样mp怎么做硬链接的，下载目录识别不到

**Comment by 522654518** [comment]
我也在github和tg上说了这个问题 但是暂时没人理  都不用win的嘛

**Comment by pengfei9403** [comment]
啊哈，看起来近期不会适配了嘛，提供一个思路，qb下载完成后可以执行外部程序，比如一个可以触发手动整理的python脚本，自己映射一下目录~
