### ISSUE TITLE
[Feature Request]: 记住登录状态

### ISSUE THREAD

**Issue by happyeddie** [jxxghp/MoviePilot#1585]
### 当前程序版本

v1.6.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

非常棒的软件，从 NASTool 时期就开始用，但 MP 有两个关于登录的问题困扰我很久了，不是大问题，但是稍有不方便，期待未来可以改进：

问题都发生在更新 Docker 容器之后，作者更新实在太勤快了，哈哈：
1. 更新 Docker 程序之后，可能是因为前端缓存的某个文件名发生了变化，所以第一次是会一直 Loading，等 index 缓存刷新后，再开新窗口（刷新页面都不行，一定要开新窗口），才能出现登录界面
2. 每次 Docker 更新重启后，都需要重新登录，是否可以记住登录信息，避免频繁登录的麻烦

**Comment by jxxghp** [comment]
@happyeddie 1. 版本升级后，前端资源有更新的情况下要强制刷新页面或者清一下浏览器缓存（只清文件，不用清cookie和历史纪录），否则会一直loading
2. 重启后cookie还生效的话担心安全问题。

**Comment by dlovew** [comment]
问题1 ctrl+f5即可
