### ISSUE TITLE
The app/helper/sites.py file was not found

### ISSUE THREAD

**Issue by hoey94** [jxxghp/MoviePilot#1588]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Why can't I find app/helper/sites.py file?
When i run app ,i get an error in app/main.py because the app/helper/sites.py file was not found.

<img width="1440" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/13510799/9d5fc28f-2be9-4ff0-8c92-44ec6b727584">

**Comment by honue** [comment]
Please read the [README](https://github.com/jxxghp/MoviePilot?tab=readme-ov-file#4-%E5%AE%89%E8%A3%85moviepilot) document carefully. You need to manually download the MoviePilot-resource file and place it in the "app/helper" folder directory. 另外直接说中文不好吗...
