### ISSUE TITLE
[错误报告]: 豆瓣同步异常

### ISSUE THREAD

**Issue by felix-klk** [jxxghp/MoviePilot#1589]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.6.9 

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/52670643/72428ec8-f29a-468d-98f7-07ee569645db)
![image](https://github.com/jxxghp/MoviePilot/assets/52670643/5cb2f35a-b41c-40e9-82cc-da21efad1792)
nastool同步正常 mp只能获取10条数据！

**Comment by honue** [comment]
没有异常，只是代码就是这么写的，mp插件只会读取想看页面的第一页（记忆中是这样的），nt插件会把所有页面都遍历。这个插件应该也是为了同步近期的想看记录，也就是增量的想看。如果有全量需求建议自己改改提个PR。

**Comment by felix-klk** [comment]
> 没有异常，只是代码就是这么写的，mp插件只会读取想看页面的第一页（记忆中是这样的），nt插件会把所有页面都遍历。这个插件应该也是为了同步近期的想看记录，也就是增量的想看。如果有全量需求建议自己改改提个PR。

这样子 如果重装了mp就很难受了

**Comment by honue** [comment]
现在好像是走豆瓣的rss，数量好像就算限制为10，我也不记不清了，nt是页面爬虫
