### ISSUE TITLE
[错误报告]: 开启下载目录二级分类，动漫资源不会按照二级分类文件创建目录

### ISSUE THREAD

**Issue by xiaobaiwaf** [jxxghp/MoviePilot#1590]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

相关设置如图：
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/99e8ff03-3fe3-483d-ae10-b6f1e9cc48fa)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/0376ce1e-26bb-4151-8f32-c14b4ac6b611)
问题是：二级分类文件里除完结动漫和连载动漫这两个分类，其他分类都会根据二级分类文件向QB推送正确的下载路径，例如：国产剧会推送到/downloads/tv/国产剧，华语电影会推送/downloads/movie/华语电影，但是动漫资源只会推送/downloads/anime，并不会创建完结动漫或者连载动漫的二级目录
并且二级目录是可以正常加载的，在mp里可以正确识别到完结动漫和连载动漫这两个分类
如图：
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/d454c459-4833-47cd-94fd-d55c64ea9ce1)
![image](https://github.com/jxxghp/MoviePilot/assets/97422881/692df476-10ed-4ad4-845e-a711a3c41624)

**Comment by jxxghp** [comment]
不要设置动漫下载目录，才会使用tv下的二级分类

**Comment by dlovew** [comment]
突然发现有同样问题，动漫下载和媒体库目录都设置的情况下，下载分类无效，媒体库目录分类有效，且硬链接到动漫目录下。在取消动漫下载目录后，结果同上！后连媒体库动漫目录一并取消，下载分类无效，媒体库分类有效，硬链接到tv目录下正常分类！

**Comment by xiaobaiwaf** [comment]
试了一下，会下载到/downloads/tv里，还是不会创建二级分类目录

从 Windows 版邮件发送

发件人: jxxghp
发送时间: 2024年3月6日 9:13
收件人: jxxghp/MoviePilot
抄送: xiaobaiwaf; Author
主题: Re: [jxxghp/MoviePilot] [错误报告]:=?UTF-8?Q?_=E5=BC=80=E5=90=AF=E4=B8=8B=E8=BD=BD=E7=9B=AE=E5=BD=95=E4=BA=8C=E7=BA=A7=E5=88=86=E7=B1=BB=EF=BC=8C=E5=8A=A8=E6=BC=AB=E8=B5=84=E6=BA=90=E4=B8=8D=E4=BC=9A=E6=8C=89=E7=85=A7=E4=BA=8C=E7=BA=A7=E5=88=86=E7=B1=BB=E6=96=87=E4=BB=B6=E5=88=9B=E5=BB=BA=E7=9B=AE=E5=BD=95?==?UTF-8?Q?_=28Issue_#1590=29?=

不要设置动漫下载目录，才会使用tv下的二级分类
