### ISSUE TITLE
订阅搜索提示“标题不匹配”

### ISSUE THREAD

**Issue by torasy** [jxxghp/MoviePilot#1596]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.6.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索提示“标题不匹配”
![2ba27be10fede1688c6737dbcc3f880](https://github.com/jxxghp/MoviePilot/assets/160832008/f82409af-5af4-4095-8813-1a07a6534935)

**Comment by Sowevo** [comment]
能匹配到的几个是通过IMDBID匹配到的
匹配不到的几个貌似确实是有点问题

TMDB中的原标题无`,`
想要匹配的资源副标题有`,`

https://github.com/jxxghp/MoviePilot/blob/bbf1ec4c50b16452db98f1d0f6259e8d0eef5a95/app/chain/search.py#L200-L204
应该可以在200行对`torrent.description`中的特殊符号进行过滤处理

**Comment by torasy** [comment]
看不太懂- -#
