### ISSUE TITLE
站点刷流插件目录分类导致qb目录崩溃显示异常

### ISSUE THREAD

**Issue by zhnnan** [jxxghp/MoviePilot#1600]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.6.9

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

安装站点刷流插件后，配置保存目录后，启动插件，在qb刷流过程中，造成qb软件崩溃，左侧种子数量显示0，右侧其实是有种子的，下面的速度显示也全部异常（见图）
<img width="1393" alt="Snipaste_2024-03-06_17-08-44" src="https://github.com/jxxghp/MoviePilot/assets/4023201/9bb1f41b-4c57-476a-a68b-3d0a7305d7c3">
![image](https://github.com/jxxghp/MoviePilot/assets/4023201/e6c46b6a-7653-4d11-964a-d66c612d7853)
（第一个任务为刷流的种子，见标签备注）
删除该任务后，qb恢复正常
<img width="1390" alt="Snipaste_2024-03-06_17-09-35" src="https://github.com/jxxghp/MoviePilot/assets/4023201/1b48dd88-f2be-40f7-92ad-2f2c46609292">

怀疑是由于站点刷流插件增加任务时，添加标签分类异常，造成qb系统崩溃。 qb软件4.4.2、4.3.5、4.3.9均出现此错误。

**Comment by jxxghp** [comment]
qb版本原因

**Comment by zhnnan** [comment]
请问应该升级到哪个版本才可以？
