### ISSUE TITLE
[错误报告]: 无法更新

### ISSUE THREAD

**Issue by yourwater** [jxxghp/MoviePilot#1602]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.6.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用环境：群晖 docker
因为无法更新，检查了日志，发现无法移动更新文件，目标文件夹不为空？
所以每次都这样无法更新。求助我现在应该如何更新。

另外：之前还有一次我看日志写了，需要使用Python11执行root等命令，但是我未安装套件（现在已经安装），希望以后能在更新版本日志中写出需要额外配合使用的软件/插件。

### 发生问题时系统日志和配置文件

```bash
2024/03/06 18:49:43	stdout	[32mINFO:[0m    singleton.py - 认证资源版本：1.2.0
2024/03/06 18:49:43	stdout	[32mINFO:[0m    singleton.py - 站点资源版本：1.1.4
2024/03/06 18:49:41	stdout	[32mINFO[0m:     Waiting for application startup.
2024/03/06 18:49:41	stdout	[32mINFO[0m:     Started server process [[36m60[0m]
2024/03/06 18:49:32	stdout	usermod: no changes
2024/03/06 18:49:32	stdout	后端程序下载失败，继续使用旧的程序来启动...
2024/03/06 18:49:32	stdout	mv: cannot move '/tmp/MoviePilot-1.6.9' to '/tmp/App/MoviePilot-1.6.9': Directory not empty
2024/03/06 18:49:32	stdout	  inflating: MoviePilot-1.6.9/version.py
2024/03/06 18:49:32	stdout	  inflating: MoviePilot-1.6.9/update
```

**Comment by jxxghp** [comment]
重置容器或者重新创建
