### ISSUE TITLE
[Feature Request]: 希望增加【海胆之家】站点的支持

### ISSUE THREAD

**Issue by llanc** [jxxghp/MoviePilot#1604]
### 当前程序版本

1.6.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望增加【海胆之家】站点的支持，站点地址：【https://www.haidan.video/】

**Comment by kingcard1131** [comment]
同希望

**Comment by TimoYoung** [comment]
+1

**Comment by ITXiaoPang** [comment]
+1
不过知道架构不同，可能工作量很大

**Comment by Mr-licz** [comment]
+1

**Comment by y403321959** [comment]
+1

**Comment by wch2012asd** [comment]
+1

**Comment by phantasyleo** [comment]
+1

**Comment by phantasyleo** [comment]
关键是自定义站点虽然能添加海胆，但是老是签到失败，签到失败就算了，还没有失败的提醒（插件认为是签到成功的），就会造成多日无签到……以前NASTOOL每次都是成功的
