### ISSUE TITLE
[错误报告]: V1.6.7~V1.7.0更新失败

### ISSUE THREAD

**Issue by wangjikang01** [jxxghp/MoviePilot#1607]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.6.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我的mp是安装在群辉的docker中，重启进行V1.6.7~V1.7.0更新时日志报如下错误，我进行了重新拉取镜像的操作，仍然报同样的错误，目前无法更新。
<img width="771" alt="日志1" src="https://github.com/jxxghp/MoviePilot/assets/162529084/d3ccc542-51fd-419e-ba5e-0d10b3119203">

### 发生问题时系统日志和配置文件

```bash
2024/03/07 09:50:50	stdout	[0m安装依赖失败，请重新拉取镜像
2024/03/07 09:50:50	stdout	[0m[31mERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/App/requirements.txt'[0m[31m
2024/03/07 09:50:49	stdout	[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
2024/03/07 09:50:48	stdout	Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (24.0)
2024/03/07 09:50:47	stdout	后端程序下载成功
2024/03/07 09:50:47	stdout	/usr/local/bin/mp_update: line 12: [: too many arguments
```

**Comment by jxxghp** [comment]
重拉镜像后要重置，不然新镜像是不生效的。
