### ISSUE TITLE
[错误报告]: vocechat获取信息出错

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#1608]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1、vocechat可以正常发送 电影名 字到mp
2、mp 开始可以正常反馈电影信息给vocechat
3、当vocechat输入数字选择电影后 mp无法返回详情给vocechat

![image](https://github.com/jxxghp/MoviePilot/assets/47915665/e48c9a7b-7dee-466e-84ff-1c0f7d0ce7d1)

![image](https://github.com/jxxghp/MoviePilot/assets/47915665/340976cf-13e5-4622-a916-a4e86c4c9c40)
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/7c534092-3212-437c-a634-477650091153)
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/c5884e44-495d-4881-bf8c-a266408c63bc)

### 发生问题时系统日志和配置文件

```bash
VoceChat.__send_request() got an unexpected keyword argument 'image'
健康检查：VoceChat - 错误！获取VoceChat频道失败

```

**Comment by gm-fire** [comment]
<img width="976" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/5047482/29433a1b-ed8c-4ca6-ab32-e3e138c4bfe0">
我的情况和你不一样,但是也是报错了
