### ISSUE TITLE
刮削错误的剧集优化纠正流程

### ISSUE THREAD

**Issue by sd1536617** [jxxghp/MoviePilot#1609]
### 当前程序版本

1.7.0

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

        一、刮削错误的剧集优化纠正流程
       开了媒体文件同步删除或者清理硬链接插件的情况下，如果碰到整部剧集刮削错误，在历史记录里显示的是单集记录，重新刮削麻烦，这时需要先关媒体文件同步删除或者清理硬链接插件，再手动删除错误的硬链接，再手动刮削正确的剧集，再启动插件，流程麻烦。
       二、短剧管理优化
      1、短剧分类是判断设定时长，小于这个时长会判定为短剧，在tv下创建二级目录-短剧，但是有些动画片特别短也会判断为短剧。
      2、之前的短剧刮削插件已经设定了短剧的一级目录，下载：/短剧，硬链：/link/短剧，那我就得把短剧刮削插件的硬连地址指向TV下的短剧二级目录，而且媒体库的TV不能用根目录了，得挨个把TV的二级目录加上，短剧单独建立媒体库，希望短剧分类插件能将识别的短剧硬连到指定的短剧文件夹，而不是在tv下建立二级目录。
      3、短剧大部分很短，集数多，能否添加一个是否合并的功能选项，将下载的短剧合并成一个文件，以电影文件形式给到媒体库。
      三、插件本地化
      每次更新拉取插件，能否实现插件本地化，照顾部分网络差的用户，插件添加可更新提示图标。

**Comment by thsrite** [comment]
一、你可以去文件管理，找到要刮削的文件，直接刮削文件夹，会覆盖历史记录且不会触发同步删除

**Comment by dlovew** [comment]
同样咨询一下泡面番也就几分钟，会不会错误的分到短剧目录
