### ISSUE TITLE
[Feature Request]: pttime，可以考虑增加https://www.pttime.top/吗

### ISSUE THREAD

**Issue by zhang05lei20** [jxxghp/MoviePilot#1612]
### 当前程序版本

1.7.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

部分地区封了org，导致新增pttime站点失败，是否可以考虑支持top（https://www.pttime.top/），谢谢。

### 参考资料

<img width="1033" alt="pttime" src="https://github.com/jxxghp/MoviePilot/assets/42257419/ebd1a9f2-4110-465d-a40a-3188e8654cc4">
![Uploading pttime02.png…]()

**Comment by jxxghp** [comment]
站点资源v1.2.1已支持

**Comment by zhang05lei20** [comment]
很抱歉，可能是我自己设置问题。

**Comment by zhang05lei20** [comment]
> 站点资源v1.2.1已支持

感谢
