### ISSUE TITLE
[错误报告]: MP下载器设置，TR服务器地址填写外网域名不能推送

### ISSUE THREAD

**Issue by ShmilyStar** [jxxghp/MoviePilot#1614]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

MP下载器设置，TR服务器地址填写外网域名不能推送
当填写本地服务器192.168.1.X:9091时候，可以正常推送种子下载，当填写外网域名xxxx.com的时候，健康检查显示TR服务器连接正常，但是推送种子下载失败

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-03-07 17:52:14,530 - transmission.py - transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //123456.xyz/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5cc8d16b90>: Failed to resolve 'https' ([Errno -5] No address associated with hostname)"))
【ERROR】2024-03-07 17:52:20,339 - transmission.py - transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //123456.xyz/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f5ca4118190>: Failed to resolve 'https' ([Errno -5] No address associated with hostname)"))
【ERROR】2024-03-07 17:52:31,974 - transmission.py - transmission 连接出错：can't connect to transmission daemon: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
【ERROR】2024-03-07 17:53:34,468 - transmission.py - transmission 连接出错：transmission daemon require auth
```

**Comment by ShmilyStar** [comment]
补充下，外网域名是单IPV6地址通过DDNS动态域名lucky反代，端口443，有ssl证书

**Comment by jxxghp** [comment]
如果是https，试点补齐URL：https://123456.xyz/

**Comment by ShmilyStar** [comment]
> 如果是https，试试补齐URL：https://123456.xyz/

经测试，依旧不行，https://123456.xyz/，https://123456.xyz:443，http://123456.xyz/，http://123456.xyz:80，123456.xyz，这些类型的都有尝试，依然不能正常推送，web服务有做过http到https的重定向

**Comment by ShmilyStar** [comment]
补充下，今天更新项【化了下载器及媒体目录的健康检查】后，tr服务器设置经测试填写以下类型：https://123456.xyz/，https://123456.xyz:443，http://123456.xyz/，http://123456.xyz:80，123456.xyz，123456.xyz:80，123456.xyz:443，这些类型都有测试，健康检查显示TR服务器连接失败，日志报错代码：transmission 连接出错：can't connect to transmission daemon: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by ShmilyStar** [comment]
经连夜测试，不管是MP还是NT，反代启用TLS协议，此时TR和QB服务器不论是否添加https协议头都无法正常连接，关闭TLS后，使用HTTP 协议可以正常访问

**Comment by ShmilyStar** [comment]
> 如果是https，试试补齐URL：https://123456.xyz/

经连夜测试，不管是MP还是NT，反代启用TLS协议，此时TR和QB服务器不论是否添加https协议头都无法正常连接，关闭TLS后，使用HTTP 协议可以正常访问，QB添加正向代理，MP参数添加https协议可以正常访问

**Comment by ShmilyStar** [comment]
更新下报错日志为： 
连接出错：can't connect to transmission daemon: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),
确定是这个问题，希望作者可以修复

**Comment by jessefeng2024** [comment]
同样的问题
