### ISSUE TITLE
[Feature Request]: 允许自定义slack的_ds_url地址

### ISSUE THREAD

**Issue by zfhxi** [jxxghp/MoviePilot#1619]
### 当前程序版本

 v1.7.0-1

### 运行环境

Docker

### 功能改进类型

其他

### 功能改进

我发现，即使我moviepilot通过反代绑定域名并支持https后，使用slack推送消息时，docker后台日志同样会报ssl错误`base_client.py - Failed to send a request to Slack API server……`。
经探索是因为`app/modules/slack/slack.py`中`_ds_url`被写死为`http://127.0.0.1:{settings.PORT}`的原因。

希望允许用户使用环境变量更改下面的`_ds_url`中的`http://127.0.0.1:{settings.PORT}`
https://github.com/jxxghp/MoviePilot/blob/e4a67ea052585313e94c034ec623327cbac315e8/app/modules/slack/slack.py#L25
比如说定义`SLACK_URL`环境变量：
```py
  if settings.SLACK_URL:
    _ds_url = f"{settings.SLACK_URL}/api/v1/message?token={settings.API_TOKEN}"
  else:
    _ds_url = f"http://127.0.0.1:{settings.PORT}/api/v1/message?token={settings.API_TOKEN}"
```
然后docker的环境变量`SLACK_URL`，填为`https://mp.yourdomain.com`，就不会再报错ssl了。

### 参考资料

很抱歉，我对slack api相关的规范并不熟悉，也不了解网络ssl验证相关的知识。我并不能确定上述报错的本质问题和`http://127.0.0.1:{settings.PORT}`是否唯一关联，但似乎修改为`_ds_url = f"https://mp.yourdomain.com/api/v1/message?token={settings.API_TOKEN}"`，确实不再报错。

**Comment by jxxghp** [comment]
_ds_url 只是把slack bot接到的请求转发给程序内部的message接口，你是在MP的容器nginx上加了ssl证书？
