### ISSUE TITLE
[错误报告]: 搜索和订阅默认关键字查询问题

### ISSUE THREAD

**Issue by gm-fire** [jxxghp/MoviePilot#1622]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.0-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

例如我订阅搜索 师兄啊师兄,在蜜柑里面出现2种结果.
首先是使用默认关键字,出来的结果不尽人意
<img width="2452" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/5047482/5d98461a-e580-431b-bab3-b1fac595c043">
然后我修改订阅里面的关键字为 My Senior Brother is Too Steady,结果就对了.请留意这里搜索到的标题也是有“师兄啊师兄” 这个关键字的
<img width="2448" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/5047482/2a61aa7f-af43-47d6-99dc-1ed82b3dfbdf">

另一种情况是在资源搜索的时候,使用的也是默认关键字,所以出来结果也很少
<img width="753" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/5047482/3496076c-ee61-4028-aaf2-b17f97f9a0e9">
只能匹配到pt站点

**Comment by jxxghp** [comment]
订阅可以设定搜索词，左下角图标搜索会按TMDB中的别名依次搜索，但一个站主名称没记录的时候才会搜索其它的名字，都搜的话会增加搜索次数。

**Comment by markddd268** [comment]
> 订阅可以设定搜索词，左下角图标搜索会按TMDB中的别名依次搜索，但一个站主名称没记录的时候才会搜索其它的名字，都搜的话会增加搜索次数。

搜索  葬送的芙莉莲  时，它优先搜索的日文，馒头站返回的结果才两条数据。但馒头站有几十条数据呢
