### ISSUE TITLE
[错误报告]: 获取VoceChat频道失败

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#1624]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/47915665/69631d2a-eb09-4278-a4ea-7a25eac4ad4e)
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/ac6e9590-aece-4e20-8a6a-e5bdf38f47c5)
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/e2fcf0f6-ec50-4649-b327-13147ffc85e4)
**前面输出正常，唯独后面选择数字8后 无法反馈信息给vocachat（已经正常推送到qb下载了）**
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/05e1fcc0-c3f3-4d18-9906-1e1191139b9b)
**这是后面补的图、一模一样的问题**

### 发生问题时系统日志和配置文件

```bash
健康检查：获取VoceChat频道失败
日志：vocechat 错误码404

【moviepilot设置如下】
1、网址：vocechat的地址https://vocechat域名（后面不包括/api路径）
2、密钥：vocechat机器人的密钥
3、频道ID：机器人的ID（6不带#）。同时也是https://域名/#/chat/dm/6 （这个位数6）

【vocechat设置如下】
Webhook 接收地址：https://mp域名/api/v1/message/?token=mp的api密钥
```

**Comment by Whichbfj28** [comment]
日志发现：
发送消息：channel=MessageChannel.VoceChat，title=开始搜索 电视剧 我知道我爱你 (2023) ..., text=None，userid=UID#1
正常发送
发送消息：channel=MessageChannel.VoceChat，title=我知道我爱你 (2023) S01 E11-E12 开始下载, text=用户：UID#1
无法发送 404

**Comment by gm-fire** [comment]
频道要新建一个,然后使用频道ID,而不是使用机器人ID

**Comment by Whichbfj28** [comment]
> 频道没有的话要新建一个,然后使用频道ID,而不是使用机器人ID

有频道2

**Comment by gm-fire** [comment]
> > 频道没有的话要新建一个,然后使用频道ID,而不是使用机器人ID
> 
> 有频道2。MP中设置频道2的话。 日志变成了：vocechat.py | VoceChat发送消息失败，错误码：403

Webhook 接收地址 http://ip:3000/api/v1/message/?token=xxxx 试试

**Comment by Whichbfj28** [comment]
> > > 频道没有的话要新建一个,然后使用频道ID,而不是使用机器人ID
> > 
> > 
> > 有频道2。MP中设置频道2的话。 日志变成了：vocechat.py | VoceChat发送消息失败，错误码：403
> 
> Webhook 接收地址 http://ip:3000/api/v1/message/?token=xxxx 试试,token换成你的

token是我自己的

**Comment by Whichbfj28** [comment]
找到问题原因了：
1、使用频道ID。不要使用机器人ID
2、此频道ID必须设置成公开。不能是私密

**Comment by gm-fire** [comment]
> 找到问题原因了： 1、使用频道ID。不要使用机器人ID 2、此频道必须设置成公开。不能是私密

2不成立,我用的也是私密频道

**Comment by Whichbfj28** [comment]
> > 找到问题原因了： 1、使用频道ID。不要使用机器人ID 2、此频道必须设置成公开。不能是私密
> 
> 2不成立,我用的也是私密频道

那就奇怪了。我设置为公开就行了。我在设置为私密试试

**Comment by Whichbfj28** [comment]
> > 找到问题原因了： 1、使用频道ID。不要使用机器人ID 2、此频道必须设置成公开。不能是私密
> 
> 2不成立,我用的也是私密频道

我重新测试过。
1、先设置公开，再设置私密可以正常发送
2、新建的频道一开始就是私密的。无法发送
