### ISSUE TITLE
[错误报告]: MiKan站点浏览错误

### ISSUE THREAD

**Issue by gm-fire** [jxxghp/MoviePilot#1625]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.7.0-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在站点管理点测试,提示连接正常,但是点浏览,就没数据回来,然后订阅的搜索又是可以搜索到内容

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-08 10:34:06,745 - torrents.py - 开始获取站点 mikanani.me 最新种子 ...
【INFO】2024-03-08 10:34:06,805 - spider.py - 开始请求：https://mikanani.me/Home/Classic/1
【WARNING】2024-03-08 10:34:08,183 - indexer - MiKan 未搜索到数据，耗时 1 秒
【INFO】2024-03-08 10:37:10,727 - site.py - 站点【MiKan】连通性正常，不同步CookieCloud数据
【WARNING】2024-03-08 10:37:12,054 - site.py - 获取 https://mikanani.me/ RSS链接失败，错误码：400，错误原因：Bad Request
```

**Comment by jxxghp** [comment]
fixed in 8ab9ba5a5cfb53511523e2e4800e0720e8a31225

**Comment by jxxghp** [comment]
8ab9ba5a5cfb53511523e2e4800e0720e8a31225

**Comment by jxxghp** [comment]
fixed in https://github.com/jxxghp/MoviePilot-Resources/commit/8ab9ba5a5cfb53511523e2e4800e0720e8a31225

**Comment by Earendil-C** [comment]
【INFO】2024-07-14 01:03:23,011 - spider.py - 开始请求：https://mikanani.me/Home/Search?searchstr=love
【INFO】2024-07-14 01:03:23,002 - torrents.py - 开始获取站点 mikanani.me 最新种子 ...
【INFO】2024-07-14 01:03:18,974 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x7fdab3c53380>, <function SiteChain.clear_site_data at 0x7fdab3c5cb80>]

**Comment by ivensfor** [comment]
> 【INFO】2024-07-14 01:03:23,011 - spider.py - 开始请求：https://mikanani.me/Home/Search?searchstr=love 【INFO】2024-07-14 01:03:23,002 - torrents.py - 开始获取站点 mikanani.me 最新种子 ... 【INFO】2024-07-14 01:03:18,974 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x7fdab3c53380>, <function SiteChain.clear_site_data at 0x7fdab3c5cb80>]
> 
> 在最新版本v1.9.11中有类似问题，主页数据浏览结果都是love的搜索结果

版本 v1.9.17 遇到跟你一樣的問題，瀏覽全都是 `love` 的搜索結果，請問你解決這個問題了嗎？
