### ISSUE TITLE
订阅电视剧，已下载的集数不会显示，依然是0/总集数

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot#1626]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.0-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![屏幕截图 2024-03-08 134252](https://github.com/jxxghp/MoviePilot/assets/74590603/8d57a4f5-b544-4a46-86d5-e566a79fc277)
![屏幕截图 2024-03-08 134318](https://github.com/jxxghp/MoviePilot/assets/74590603/b6625a77-a435-4d7c-b15b-836166412b4e)

### 发生问题时系统日志和配置文件

```bash
INFO:    subscribe.py - The Good Doctor S07E01 Baby Baby Baby 1080p AMZN WEB-DL DDP 2.0 H.264-FLUX 对应剧集 [1] 已下载过
INFO:    subscribe.py - The Good Doctor S07E02 Skin In The Game 1080p AMZN WEB-DL DDP 5.1 H.264-NTb 对应剧集 [2] 已下载过
INFO:    subscribe.py - The Good Doctor S07E01 Baby Baby Baby REPACK 1080p AMZN WEB-DL DD 5.1 H.264-NTb 对应剧集 [1] 已下载过
INFO:    subscribe.py - The Good Doctor S07E02 Skin In The Game 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX 对应剧集 [2] 已下载过
INFO:    subscribe.py - The Good Doctor S07E02 1080p WEB H264-SuccessfulCrab 对应剧集 [2] 已下载过
INFO:    subscribe.py - The Good Doctor S07E01 Baby Baby Baby REPACK 1080p AMZN WEB-DL DDP 5.1 H.264-FLUX 对应剧集 [1] 已下载过
INFO:    subscribe.py - The Good Doctor S07E01 Baby Baby Baby 1080p AMZN WEB-DL DDP 2.0 H.264-NTb 对应剧集 [1] 已下载过
INFO:    subscribe.py - The Good Doctor S07E01 1080p WEB H264-SuccessfulCrab 对应剧集 [1] 已下载过
WARNING: subscribe.py - 订阅 良医 没有符合过滤条件的资源
INFO:    subscribe.py - 良医 (2017) 未下载完整，继续订阅 ...
INFO:    subscribe.py - 良医 (2017) 季 7 更新缺失集数为10 ...
```

**Comment by jxxghp** [comment]
日志已经很明显了，这个下过了。如果人为干预了导致没有入库的，取消重新订阅。
