### ISSUE TITLE
请求url中包含http地址在反向代理下可能代理失败，表现是emby首页图外网访问不显示

### ISSUE THREAD

**Issue by Aodi** [jxxghp/MoviePilot#1632]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

首页的emby图片在内网访问时正常显示，外网访问时不显示。使用的威联通自带的反向代理（用的apache反向代理），写了个fastapi的demo测试了一下，果然在url参数中包含`http://xxxx`时，反向代理会识别错，导致代理不到原始请求。
建议把请求的emby图标的url做一层base64编码，后端再做一次解码。
![Snipaste_2024-03-08_22-11-15](https://github.com/jxxghp/MoviePilot/assets/19473876/ad1a0907-91d1-4a18-9dad-b2f374c90d88)
![Snipaste_2024-03-08_22-11-39](https://github.com/jxxghp/MoviePilot/assets/19473876/5ce78c9a-20a6-4aaa-801b-b1668178958d)

![Snipaste_2024-03-08_22-24-38](https://github.com/jxxghp/MoviePilot/assets/19473876/0d0a20b6-e218-4c71-9c63-47dc12f112b2)

之前反馈的类似问题：[[错误报告]: 1.5.9更新后，主页无法正常显示海报](https://github.com/jxxghp/MoviePilot/issues/1358)

**Comment by Aodi** [comment]
![Snipaste_2024-03-08_22-11-15](https://github.com/jxxghp/MoviePilot/assets/19473876/ad1a0907-91d1-4a18-9dad-b2f374c90d88)
![Snipaste_2024-03-08_22-11-39](https://github.com/jxxghp/MoviePilot/assets/19473876/5ce78c9a-20a6-4aaa-801b-b1668178958d)

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/c758ff6f-4bf5-44c6-a05e-1171f6624efe)
已经做过编码了，检查下代向代理是不是有问题。我也是用的反代，外网可正常显示。

**Comment by DDSDerek** [comment]
@jxxghp 类似于这种问题好像很多人提到了，不过一直没找到问题关键

**Comment by Aodi** [comment]
@jxxghp @DDSDerek 我上网研究了一下，大概找到问题所在了。
先说结论：apache服务器默认不接受url有编码的斜杠字符"@2f或者%5C"，有的话就会直接404。
我用的威联通的反向代理，就是apache，并且不支持修改这个配置，大家反馈有问题的，应该也都是apache。
这是apache的官网文档：
https://httpd.apache.org/docs/2.4/mod/core.html
![Snipaste_2024-03-10_11-12-34](https://github.com/jxxghp/MoviePilot/assets/19473876/9d6d8841-1ebe-4b87-85ba-a29bc87ac3a0)


为什么要默认限制？看了几个帖子，提到基于相对路径攻击（RPO）
https://github.com/cnpm/cnpmjs.org/issues/618
https://www.freebuf.com/articles/web/166731.html

考虑到有些人想我用威联通自导的反代，改不了配置文件，我建议MoviePilot可以改一下实现。我个人考虑的几个实现：
1. 字符替换，比如用`@`替换`/`，这个方法不是百分百的稳妥，如果url中原本有`@`就会出错，但也可以增加替换字符的复杂性（比如movie_pilot_xiegang），基本也没啥问题。
2. 改成post请求，把url放在body里。

@jxxghp 考虑一下哈~
