### ISSUE TITLE
BUG 订阅默认规则对标签无效！

### ISSUE THREAD

**Issue by MyGiki** [jxxghp/MoviePilot#1635]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.0-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

订阅默认规则对标签无效！下面有我测试的图和日志
下图我的订阅设置好的规则
![1](https://github.com/jxxghp/MoviePilot/assets/107430324/1f0af890-e1d0-4771-a233-741542ee25e3)
下图是订阅时测试到不匹配的问题，
![0](https://github.com/jxxghp/MoviePilot/assets/107430324/79bd074c-2bad-4b82-9cf7-cbf217d004c0)
![2](https://github.com/jxxghp/MoviePilot/assets/107430324/4c86517d-4147-488f-b6d1-842078da867d)
![观众1](https://github.com/jxxghp/MoviePilot/assets/107430324/06ea2c63-2c56-44d8-b086-65b6a2b65a05)
![观众2](https://github.com/jxxghp/MoviePilot/assets/107430324/7056e4ec-6295-485a-b2cf-82ee3d716e01)
![憨憨1](https://github.com/jxxghp/MoviePilot/assets/107430324/0ea3117d-735d-4ca4-862b-934b347db083)
![憨憨2](https://github.com/jxxghp/MoviePilot/assets/107430324/856ef312-4899-4044-8786-1ecef79cee9b)

**Comment by MyGiki** [comment]
@jxxghp 大佬你好，RSS报文没有显示标签。主副标题也没有含有设置好的中字规则，那RSS报文中有订阅的影片也会被过滤吗？
例如下图。
吞噬星空网站标签显示有中字
![2](https://github.com/jxxghp/MoviePilot/assets/107430324/d09f2468-bec0-403d-9e77-50a50868465d)

RSS报文的吞噬星空没有标签中字（很多大站RSS没有标签选项）
![1](https://github.com/jxxghp/MoviePilot/assets/107430324/bebb370c-1b8e-4a9b-8437-d83235e8f7eb)
这种情况的话我RSS订阅模式的吞噬星空是不是会被认定为不匹配设置好的默认规则被过滤掉呢？

**Comment by jxxghp** [comment]
> @jxxghp 大佬你好，RSS报文没有显示标签。主副标题也没有含有设置好的中字规则，那RSS报文中有订阅的影片也会被过滤吗？ 例如下图。 吞噬星空网站标签显示有中字 ![2](https://private-user-images.githubusercontent.com/107430324/311927446-d09f2468-bec0-403d-9e77-50a50868465d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTM3OTEsIm5iZiI6MTcxMDIxMzQ5MSwicGF0aCI6Ii8xMDc0MzAzMjQvMzExOTI3NDQ2LWQwOWYyNDY4LWJlYzAtNDAzZC05ZTc3LTUwYTUwODY4NDY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMzE4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2EyMDk4YjI5NjliODAwYmE0YzRjOTQ1ZjRjNDU4MGMzYWUzZDc3ZWI3ZmY5YjNlMzkzZDMxZTNjMDhiZjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N0DaeRJOKNTxvpsdAR1739beQNFJ2cX8gODYh4zLuOs)
> 
> RSS报文的吞噬星空没有标签中字（很多大站RSS没有标签选项） ![1](https://private-user-images.githubusercontent.com/107430324/311927027-bebb370c-1b8e-4a9b-8437-d83235e8f7eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTM3OTEsIm5iZiI6MTcxMDIxMzQ5MSwicGF0aCI6Ii8xMDc0MzAzMjQvMzExOTI3MDI3LWJlYmIzNzBjLTFiOGUtNGE5Yi04NDM3LWQ4MzIzNWU4ZjdlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMzE4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2M1ODdlODdlY2JmYzE4Y2U4NTdkZjI5Yzc1YWUyMzk0M2RjM2YwM2RjYjQ4MjVhN2RkYzE0OWM5ZTg2NWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KRPGAp66EAu3y-2rGJaI3fAqm9FG_DukQ0mQQ9_1E3I) 这种情况的话我RSS订阅模式的吞噬星空是不是会被认定为不匹配设置好的默认规则被过滤掉呢？

默认规则会过滤，RSS模式很多元素可能没有，同时推荐使用优先级规则，标签匹配不到时再通过后面的规则兜底。

**Comment by MyGiki** [comment]
大佬，请问订阅模式里的自动是怎么的用途呢，请大佬指示一下！

**Comment by MyGiki** [comment]
@jxxghp
大佬，请问订阅模式里的自动模式是怎么的用途呢，自动模式是用搜索还是RSS报文呢，多久运行一次呢，请大佬指示一下！问了群里的大伙，没人解答，实在没理解自动模式是什么功能才斗胆打扰一下大佬。大佬莫怪

**Comment by jxxghp** [comment]
@MyGiki 自动模式就是爬虫模式，每隔20到40分钟随机爬起站点主页的种子列表，每天有种爬起数量的限制，大概大晚上11:00左右就会停了，直到第二天早上7:00

**Comment by MyGiki** [comment]
@jxxghp
多谢大佬，大佬万岁！
