### ISSUE TITLE
[错误报告]: 订阅未上映的庆余年第二季，会自动下载第一季。练气十万年会反复下载之前已经下载过的集

### ISSUE THREAD

**Issue by oynt** [jxxghp/MoviePilot#1637]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅未上映的庆余年第二季，会自动下载第一季。练气十万年会反复下载之前已经下载过的集。绝世唐门 订阅到38集结束了。

等下用电脑了我截图。

**Comment by jxxghp** [comment]
你这么提问题，怎么给你看
