### ISSUE TITLE
[Feature Request]: 资源搜索页面季集显示建议优化下

### ISSUE THREAD

**Issue by gm-fire** [jxxghp/MoviePilot#1638]
### 当前程序版本

 v1.7.0-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

<img width="764" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/5047482/dad8677b-8b95-472e-b3d8-98e8a495ab5b">

这个就很乱,而且无法输入集数,建议增加一个排序功能

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/01df990aa8c5dd18fa32173e640e7dcf9a11fd26
