### ISSUE TITLE
[Feature Request]: 建议大佬优化日志显示方式

### ISSUE THREAD

**Issue by hn315** [jxxghp/MoviePilot#1640]
### 当前程序版本

 v1.7.0-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

软件越来越好用了，家人很开心。谢谢各路大佬的付出。
软件功能强大，有很多日志显示输出，提个建议，主程序在新窗口中打的日志、实时日志和各种插件的日志显示方式都是最新一条在最下面，我想大多数朋友看日志都是查最近的几条，有些日志比较多（以后可以考虑一个过滤设置），翻到最下面看有点不方便，特别是用手机、平板，摸鱼时手指飞舞，能否改为最新的记录在最上面？谢谢

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/49b71fcf5d5382c7c428f0d4a50a708be7c3e2fe
