### ISSUE TITLE
华科蝴蝶PT站下载链接出现错误

### ISSUE THREAD

**Issue by BH9ELJ** [jxxghp/MoviePilot#1645]
### 确认

- [x] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [x] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

添加华科pt站hudbt.hust.edu.cn后，使用mp搜索到资源后无法通过mp直接下载，单击下载链接后发现是链接地址错误，出现了一段重复的站点地址导致，删除掉多余的/hudbt.hust.edu.cn/后，用链接可以正常下载。
![{777307C4-1D66-4629-8B0D-3F7A44C7620E}](https://github.com/jxxghp/MoviePilot/assets/162817101/7824c593-5b42-4b44-8ccf-73673ecee1e7)
![{B7F50E19-E469-4e69-BC4C-B4DDBA1C4BB7}](https://github.com/jxxghp/MoviePilot/assets/162817101/120bdb80-0213-4dec-a43f-22728b99d9e4)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-09 22:42:17,092 - search.py - 匹配完成，共匹配到 20 个资源
【INFO】2024-03-09 22:42:17,104 - search.py - 过滤完成，剩余 23 个资源
【ERROR】2024-03-09 22:45:11,552 - download.py - 下载种子文件失败：Dune 2021 UHD BluRay 2160p x265 10bit DoVi V2 2Audio TrueHD Atmos 7.1-beAst - https://hudbt.hust.edu.cn//hudbt.hust.edu.cn/download.php?id=160149
【INFO】2024-03-09 22:45:11,580 - chain - 发送消息：channel=None，title=Dune 2021 UHD BluRay 2160p x265 10bit DoVi V2 2Audio TrueHD Atmos 7.1-beAst 种子下载失败！, text=错误信息：下载种子出错，状态码：404
站点：蝴蝶，userid=None
```

**Comment by jxxghp** [comment]
我没账号，需要提供一下种子页面的html代码

**Comment by BH9ELJ** [comment]
> 我没账号，需要提供一下种子页面的html代码

已经私发至您邮箱了

**Comment by jxxghp** [comment]
> > 我没账号，需要提供一下种子页面的html代码
> 
> 
> 
> 已经私发至您邮箱了

没有发对，需要列表页的代码

**Comment by BH9ELJ** [comment]
> > > 我没账号，需要提供一下种子页面的html代码
> > 
> > 
> > 已经私发至您邮箱了
> 
> 没有发对，需要列表页的代码

已经重新发给您了
