### ISSUE TITLE
[错误报告]: 媒体库目录 BUG 无法正常加载和配置

### ISSUE THREAD

**Issue by SoTender** [jxxghp/MoviePilot#1646]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.0-1 1.7.1

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/4a1f6158-ab57-4045-8fee-245a63a16e8d)
首先我是不用多个媒体库目录的，但是这个功能似乎对我造成了困扰；

第一：如果在不改变的情况下，点几次保存，就会在对应的配置文件里新增几个相同的路径。（而且里面还会存一些以前的路径，即使我已经删除的）

第二：如果手动修改配置文件中的逻辑为自己想要的，重新MP似乎又不能加载配置文件里的。

想要的路径手动配置env：
![image](https://github.com/jxxghp/MoviePilot/assets/127156952/02500f08-49d0-438b-8994-28f20ed6220b)

重启以后MP界面显示的：
![image](https://github.com/jxxghp/MoviePilot/assets/127156952/ea09cc21-eb19-4abe-b66a-a09403f36459)

要不就一个路径一行，类似Nastool。

临时的解决办法就是把这几项全删了env，然后启动MP再设置一次，但是如果强制退出MP又有目录丢失的情况。
如此循环。

更新了1.7.1好像也是一样的，win版的退出不知道为啥退不掉，通过任务管理器强制关闭，启动新版1.7.1，路径有变成上面那样了

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/ea09cc21-eb19-4abe-b66a-a09403f36459)

请问win版是不能退出重启吗？

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/ea09cc21-eb19-4abe-b66a-a09403f36459)

这两个地方只要一重启就会变成这样

**Comment by jxxghp** [comment]
1. 检查下是不是windows环境变量里设置过了？导致重启后以环境变量为准了。
2 重重生成多个设置项的问题没遇到过，不确定是不是windows环境才会有的问题。

**Comment by SoTender** [comment]
> 1. 检查下是不是windows环境变量里设置过了？

首先windows环境变量这个问题，建议作者大大更新下官方Wiki说明(针对win)，因为可能有些人太笨了（比如我），不知道咋设置，我是研究了半天才弄明白咋设置的，但是不知道对不对，我是[这样](https://github.com/developer-wlj/Windows-MoviePilot/issues/9)设置的：

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/7c5f9120-1d1c-456c-848c-493e75973543)

是这三项吧

AUTH_SITE=hhclub
HHCLUB_USERNAME=用户名
HHCLUB_PASSKEY=密钥

> 1.导致重启后以环境变量为准了。

如果我不添加上面的那三项，系统健康检查就不能通过用户验证；加了就提示通过了。或者需要清除缓存还是什么的嘛？因为我关闭了MP的程序，网页3000也还是有部分MP的UI？

> 2 重重生成多个设置项的问题没遇到过，不确定是不是windows环境才会有的问题。

因为刚开始玩不是很熟悉，有时候配置错了，或者修改了配置文件，所以就只有关闭重启了，但是有时候似乎关闭不了，任务管理器还有进程占用，然后就只有强制关闭mp相关的那两个exe了。

**Comment by thinktip** [comment]
同样的问题，发生在windows版，docker版本没有问题。

**Comment by jxxghp** [comment]
@thinktip 感觉还是你那个目录名带特殊字符的原因，win下也是一套代码，目前没收到类似问题

**Comment by thinktip** [comment]
> @thinktip 感觉还是你那个目录名带特殊字符的原因，win下也是一套代码，目前没收到类似问题

没有特殊字符，媒体库目录就是Z:\，电影目录Movie，电视剧目录TV

**Comment by SoTender** [comment]
> 没有特殊字符，媒体库目录就是Z:\，电影目录Movie，电视剧目录TV

1.7.2问题依旧存在。

> @thinktip 感觉还是你那个目录名带特殊字符的原因，win下也是一套代码，目前没收到类似问题

win版我是这样升级的，任务栏退出程序，并确认任务管理器中没有MoviePilot.exe和nginx.exe程序还在运行。

然后下载1.7.2的安装包去除版本后缀（个人强迫症），替换旧版本exe，然后右键管理员启动。

启动以后，目录还是跟之前的一样，每一次启动必须要重新配置目录。

**Comment by thinktip** [comment]
一样的流程。配置文件会有多条记录，电影和剧集目录不能保存，但动漫目录能保存。

**Comment by SoTender** [comment]
> 一样的流程。配置文件会有多条记录，电影和剧集目录不能保存，但动漫目录能保存。

我是媒体库目录的路径和电影的命名不能保存
每次都要手动修改成：

G:\
「电影」

**Comment by SoTender** [comment]
> 一样的流程。配置文件会有多条记录，电影和剧集目录不能保存，但动漫目录能保存。

现在我的解决办法就是在win的系统变量中新增这些目录；
亲测重启能完美加载环境变量配置的目录。


LIBRARY_PATH='G:\'
LIBRARY_MOVIE_NAME='「电影」'
LIBRARY_TV_NAME='「剧集」'
LIBRARY_ANIME_NAME='「动漫」'
LIBRARY_CATEGORY='True'

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/249240d2-a43d-40af-988d-0ed037aa47c2)
