### ISSUE TITLE
[错误报告]: Windows版无法认证

### ISSUE THREAD

**Issue by little6neko** [jxxghp/MoviePilot#1647]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.1

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

app.env中已配置了：
AUTH_SITE=iyuu,audiences
IYUU_SIGN=
AUDIENCES_UID=
AUDIENCES_PASSKEY=
![image](https://github.com/jxxghp/MoviePilot/assets/34598766/430d19f6-4fa4-432b-ab16-4ee7631f84b8)
但无法认证

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-09 23:49:59,981 - singleton.pyc - 站点资源版本：1.2.1
【INFO】2024-03-09 23:50:00,003 - singleton.pyc - 认证资源版本：1.2.0
【ERROR】2024-03-09 23:50:00,013 - singleton.pyc - 环境变量 IYUU_SIGN 未设置！
【ERROR】2024-03-09 23:50:00,086 - singleton.pyc - iyuu认证出错：非法请求：缺少必要参数sign
【ERROR】2024-03-09 23:50:00,098 - singleton.pyc - 环境变量 AUDIENCES_UID 未设置！
【ERROR】2024-03-09 23:50:00,107 - singleton.pyc - 环境变量 AUDIENCES_PASSKEY 未设置！
【ERROR】2024-03-09 23:50:00,827 - singleton.pyc - audiences认证出错：不存在该用户或者此用户被封禁
【ERROR】2024-03-09 23:50:00,838 - singleton.pyc - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
```

**Comment by little6neko** [comment]
原来是要加在Windows的环境变量才生效

**Comment by blackappleD** [comment]
通过系统环境变量配置也不生效
![image](https://github.com/user-attachments/assets/74bc84fb-5f3a-48e8-a7cf-44c993ee9c3c)


【INFO】2024-09-05 14:25:12,986 - chain - 发送消息：channel=None，title=MoviePilot用户认证, text=用户认证失败，站点相关功能将无法使用！，userid=None
