### ISSUE TITLE
[Feature Request]: 希望资源搜索的选种界面可以改成竖排排列

### ISSUE THREAD

**Issue by samir2015dzh** [jxxghp/MoviePilot#165]
### 当前程序版本

v1.0.2

### 功能改进

希望资源搜索的选种界面可以沿用nastools的设置，或者直接改成竖排排列也行，这样横着一排一排的感觉有点眼花缭乱，不太方便选种啊
![image](https://github.com/jxxghp/MoviePilot/assets/49280638/40671a18-8483-4572-ba55-7f39ecbe3f7e)

**Comment by yellowstrong** [comment]
支持，希望能增加一行一行类似NT那种搜索结果页的排列方式，并将不同的类型比如蓝光，流媒体进行分类折叠那种方式，更方便选择下载种子类型
