### ISSUE TITLE
[错误报告]: episode刮削信息普遍性错误，nfo中错误记录了tvshow的tmdbid

### ISSUE THREAD

**Issue by ChXWu** [jxxghp/MoviePilot#1655]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

最近在试图和trakt同步记录的时候发现的这个问题。

我看了一下nfo文件，show和season的信息是没有错的，但是每个episode的nfo文件中，
```
<uniqueid type="tmdb" default="true">xxxxx</uniqueid>
<tmdbid>xxxxx</tmdbid>
```
这两行显示的id目前刮削出是tvshow的id而不是具体episode的id，第一行是错误的，第二行似乎是没有意义的。

例：葬送的芙莉莲 (2023)在"tvshow.nfo"中显示的tmdbid是209867，这是正确的；但在 "葬送的芙莉莲 - S01E01 - 第 1 集.nfo"这样的episode nfo中仍然显示的是209867，这是错误的，实际上episode1的tmdbid是3946240
这是目前episode nfo中的信息
```
<uniqueid type="tmdb" default="true">209867</uniqueid>
<tmdbid>209867</tmdbid>
```
正确的应该是tmm刮削出的
` <uniqueid default="false" type="tmdb">3946240</uniqueid>`
或者按原来的格式
` <uniqueid type="tmdb" default="true">3946240</uniqueid>`

这个问题会在emby读取nfo后使emby剧集信息关联到错误的trakt数据库，并导致同步trakt时同步成另外一个剧集。

**Comment by jxxghp** [comment]
这个问题后面的版本修改过，请看下是不是之前版本刮的nfo

**Comment by ChXWu** [comment]
> 这个问题后面的版本修改过，请看下是不是之前版本刮的nfo

那就奇怪了，我一直都是跟着版本的，我仍然在不停的遇见同样的问题
```
  <dateadded>2024-03-03 22:39:58</dateadded>
  <uniqueid type="tmdb" default="true">209867</uniqueid>
  <tmdbid>209867</tmdbid>
```
是不是插件没有自动更新？

**Comment by jxxghp** [comment]
@ChXWu 这个209867不就是tmdbid吗

**Comment by ChXWu** [comment]
@jxxghp 这个仍然是show《葬送的芙莉莲 (2023)》的tmdbid，而不是正确的《葬送的芙莉莲 - S01E25》这一集episode的tmdbid

**Comment by jxxghp** [comment]
> @jxxghp 这个仍然是show《葬送的芙莉莲 (2023)》的tmdbid，而不是正确的《葬送的芙莉莲 - S01E25》这一集episode的tmdbid

是uniqueid需要是集的id？

**Comment by ChXWu** [comment]
@jxxghp 对，对于episode正确的刮削应该刮削到集，tmdb现在每一集都是有和show不一样的uniqueid的。
