### ISSUE TITLE
[Feature Request]: 使用 SyncMyCookie 同步 cookie

### ISSUE THREAD

**Issue by d0zingcat** [jxxghp/MoviePilot#1658]
### 当前程序版本

1.7.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

看了一下现在使用的 CookieCloud 发现所有的 cookie 都是由本地加密了之后直接 post 到服务端的，只能选择整体是 push 还是 pull 。
这就带来一个问题 

如果我有两台电脑 而且登录了同一个 Google 账号（那么插件就会同步）但是我两台电脑是切换了使用的，可能这个 A网站 是 电脑1 登录的，B网站 是 电脑2 登录的，这种时候就非常难受
我必须得选一个电脑做 master ，在那上面登录所有网站，在另外一台电脑上就只能 pull。
然后问题出现了，我在 电脑2 上发现有一个网站 cookie 过期了等我得重新登录的情况，我就得回到 电脑1 登录 sync 然后 电脑2 pull 。如果两个电脑都在手边还好说😅 

对比之下这个开源方案就非常清真：https://github.com/Andiedie/sync-my-cookie
你可以自由地选择你想要同步的网站和你想要 push 还是 push & merge。这样的话就可以解决多台电脑之间的同步问题，如果 mp 也可以直接用这种方式取数据的话（需要 impl 通过 github token 到 gist 获取数据并解密）就非常 nice 了。

不确定有没有更好的做法和方案来解决我的痛点，欢迎讨论。
如果确定可行的话，我后面有时间会 pr。

**Comment by jxxghp** [comment]
你可以开发个插件来实现这个功能，主程序中CookieCloud已经应用比较长的时间，用户基础大，不宜调整。

**Comment by d0zingcat** [comment]
> 你可以开发个插件来实现这个功能，主程序中CookieCloud已经应用比较长的时间，用户基础大，不宜调整。

make sense.

**Comment by lingjiameng** [comment]
这应该是cookiecloud的需要改进的功能点吧，并非mp的功能，mp只拉取cookie

**Comment by d0zingcat** [comment]
> 这应该是cookiecloud的需要改进的功能点吧，并非mp的功能，mp只拉取cookie

可能是不同角度的问题。
诚如你所说改进 cookiecloud 也可以实现，但可能对我来说去改进一个插件的成本会很高（因为得改很多东西而且会影响到本身使用 cookiecloud 的用户，也许他们并不想要这样的功能），以及 cookiecloud 目前已经进入了平稳的维护期。
而从 mp 的角度来说，本身这套系统就是在快速迭代，你可以主动选择去接入哪些数据，起码通过插件的方式能完成这样的效果，且不会改变大多数人的习惯。
