### ISSUE TITLE
[Feature Request]: 订阅剧集新增延迟阈值暂缓离开订阅组

### ISSUE THREAD

**Issue by SoTender** [jxxghp/MoviePilot#1666]
### 当前程序版本

1.7.1

### 运行环境

Windows

### 功能改进类型

主程序

### 功能改进

因为部分剧集，完结时间和TMDb元数据完结时间有些许差异。
我经常编辑TMDB（现在大约有17w+编辑），所以如果订阅剧集完结当天就取消订阅，
并且不再对其元数据进行刷新，似乎有些不妥。

以[永安梦](https://www.themoviedb.org/tv/229133/season/1)这部剧为例：

🐧官方因为超前点映，所以在3月7日就完结了。

但是因为我是采用国际版[VIU新加坡](https://www.viu.com/ott/sg/zh/vod/2315052)的元数据编辑的，新加坡国际版E19-24会晚大约一周才能完结，我也只有晚一周才能补充完元数据。

我目前在使用这个[工具](https://github.com/fzlins/TMDB-Import)维护大部分的国产剧，工具还不能完全实现全自动，我几乎是在每晚8左右维护当天的剧集，所以如果大家入库太快，最新完结的几集入库当时应该是没有元数据的，TMDB默认7个小时生效吧。也就第二天才能正常获取到这些信息。

建议能否增加一个延迟阈值，增加元数据正确获取的机率。

默认情况下：完结当天官方放出所有信息，延迟一天就能100%获取。
超前点映的情况下：可能需要约一周，主要还是看编辑者采用的信息源。

因为🐧的剧官方没有信息，同时它又上线了国际版VIU，所以我个人更倾向于使用VIU的数据维护腾讯的剧集（电视猫是最后的保底，但是剧照就随缘了）。

**Comment by SoTender** [comment]
不对，好像我理解的 服务>订阅元数据更新 好像跟实际的功能不一样。

我以为的订阅元数据更新是对Emby库订阅的元数据nfo进行刷新，
但是看日志似乎并不是啊，是对TMDb的元数据集数等信息进行更新吗？

那这样好像就没必要了。插件里的媒体库刮削应该就能实现以上请求的功能。

**Comment by jxxghp** [comment]
感谢对于themoviedb数据的贡献！
刷新订阅元数据的那个定时服务是定时更新MP里的订阅集数等信息，不是媒体服务器的。
