### ISSUE TITLE
[错误报告]: 目录中tmdbid字段被识别成蓝光碟的问题

### ISSUE THREAD

**Issue by SoTender** [jxxghp/MoviePilot#1667]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.1

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

通过对比命名格式，我发现似乎是由于我添加了tmdbid这个字段导致的？

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/db90eccd-18ef-4bbe-8047-96402f9ce144)

> 【ERROR】2024-03-12 06:08:22,574 - __init__.pyc - 运行模块 scrape_metadata 出错：TheMovieDbModule - [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E05.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'
> Traceback (most recent call last):
>   File "app\chain\__init__.py", line 97, in run_module
>   File "app\modules\themoviedb\__init__.py", line 250, in scrape_metadata
>   File "app\utils\system.py", line 396, in is_bluray_dir
>   File "pathlib.py", line 1235, in exists
>   File "pathlib.py", line 1013, in stat
> OSError: [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E05.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'
> 

似乎是因为有tmdbid，识别成蓝光了？
而且上面的路径后面都多了一个\\BDMV，正确的路径是：

G:\\「剧集」\「港台剧」\『连载』\「港台连载」\生命捕手 (2023) [tmdbid=222064]\Season 2\Dr.Lifesaver.S02E05.2023.1080p.Hami.WEB-DL.H264.AAC.mkv

正常刮削入库也是到了抓取元数据那一步就报这个错误，所以都是 入库Emby获取的，或者在Emby里手动刷新才行。
然后我又测试了另外一部，没有加tmdbid，应该能正确跑起来，只是TMDb数据库中没有录入。

> 【INFO】2024-03-12 06:08:22,591 - __init__.pyc - 开始刮削媒体库：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1 MediaType.TV ...
> 
> 【INFO】2024-03-12 06:08:22,608 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
> 
> 【INFO】2024-03-12 06:08:24,325 - tmdbapi.pyc - 正在从TheDbMovie网站查询：Please Don'T Chase Me ...
> 
> 【INFO】2024-03-12 06:08:25,393 - tmdbapi.pyc - Please Don'T Chase Me TMDB网站未查询到媒体信息！
> 
> 【INFO】2024-03-12 06:08:25,398 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
> 
> 【WARNING】2024-03-12 06:08:25,398 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\拜托了，别追我[全14集][国语配音+中文字幕].Please.Don't.Chase.Me.S01.2023.2160p.WEB-DL.H265.AAC\Please.Don't.Chase.Me.S01E01.2023.2160p.WEB-DL.H265.AAC.mkv
> 
> 【INFO】2024-03-12 06:08:25,402 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
> 
> 【INFO】2024-03-12 06:08:25,402 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息

希望能修复这个bug？不加tmdbid又不符合自己的强迫症。

下面有完整日志。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-12 06:08:19,013 - __init__.pyc - 媒体库刮削服务，立即运行一次
【INFO】2024-03-12 06:08:22,079 - __init__.pyc - 开始刮削媒体库：G:\「剧集」\「港台剧」\『连载』\「港台连载」\生命捕手 (2023) [tmdbid=222064]\Season 2 MediaType.TV ...
【INFO】2024-03-12 06:08:22,560 - __init__.pyc - 读取到本地nfo文件的tmdbid：222064
【INFO】2024-03-12 06:08:22,565 - tmdbapi.pyc - 正在查询TMDB电视剧：222064 ...
【INFO】2024-03-12 06:08:22,567 - tmdbapi.pyc - 222064 查询结果：生命捕手
【INFO】2024-03-12 06:08:22,570 - __init__.pyc - 222064 TMDB识别结果：电视剧 生命捕手 (2023)
【ERROR】2024-03-12 06:08:22,574 - __init__.pyc - 运行模块 scrape_metadata 出错：TheMovieDbModule - [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E05.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'
Traceback (most recent call last):
  File "app\chain\__init__.py", line 97, in run_module
  File "app\modules\themoviedb\__init__.py", line 250, in scrape_metadata
  File "app\utils\system.py", line 396, in is_bluray_dir
  File "pathlib.py", line 1235, in exists
  File "pathlib.py", line 1013, in stat
OSError: [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E05.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'

【INFO】2024-03-12 06:08:22,576 - __init__.pyc - 读取到本地nfo文件的tmdbid：222064
【INFO】2024-03-12 06:08:22,579 - tmdbapi.pyc - 正在查询TMDB电视剧：222064 ...
【INFO】2024-03-12 06:08:22,581 - tmdbapi.pyc - 222064 查询结果：生命捕手
【INFO】2024-03-12 06:08:22,583 - __init__.pyc - 222064 TMDB识别结果：电视剧 生命捕手 (2023)
【ERROR】2024-03-12 06:08:22,588 - __init__.pyc - 运行模块 scrape_metadata 出错：TheMovieDbModule - [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E06.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'
Traceback (most recent call last):
  File "app\chain\__init__.py", line 97, in run_module
  File "app\modules\themoviedb\__init__.py", line 250, in scrape_metadata
  File "app\utils\system.py", line 396, in is_bluray_dir
  File "pathlib.py", line 1235, in exists
  File "pathlib.py", line 1013, in stat
OSError: [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「港台剧」\\『连载』\\「港台连载」\\生命捕手 (2023) [tmdbid=222064]\\Season 2\\Dr.Lifesaver.S02E06.2023.1080p.Hami.WEB-DL.H264.AAC.mkv\\BDMV'

【INFO】2024-03-12 06:08:22,590 - __init__.pyc - 媒体库 G:\「剧集」\「港台剧」\『连载』\「港台连载」\生命捕手 (2023) [tmdbid=222064]\Season 2 刮削完成


【INFO】2024-03-12 06:08:22,591 - __init__.pyc - 开始刮削媒体库：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1 MediaType.TV ...
【INFO】2024-03-12 06:08:22,608 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:24,325 - tmdbapi.pyc - 正在从TheDbMovie网站查询：Please Don'T Chase Me ...
【INFO】2024-03-12 06:08:25,393 - tmdbapi.pyc - Please Don'T Chase Me TMDB网站未查询到媒体信息！
【INFO】2024-03-12 06:08:25,398 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,398 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E01.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,402 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,402 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,417 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E02.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,417 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,433 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,433 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E03.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,433 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,449 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,449 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E04.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,449 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,465 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,465 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E05.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,465 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,481 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,481 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E06.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,481 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,496 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,496 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E07.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,496 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,512 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,512 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E08.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,528 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,528 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,528 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E09.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,544 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,544 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,559 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E10.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,559 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,576 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,576 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E11.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,576 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,591 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,591 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E12.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,591 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,607 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,607 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E13.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,607 - __init__.pyc - 正在识别 Please Don'T Chase Me 第1季 ...
【INFO】2024-03-12 06:08:25,627 - __init__.pyc - Please Don'T Chase Me 未匹配到TMDB媒体信息
【WARNING】2024-03-12 06:08:25,627 - __init__.pyc - 未识别到媒体信息：G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1\Please.Don't.Chase.Me.S01E14.2023.2160p.WEB-DL.H265.AAC.mkv
【INFO】2024-03-12 06:08:25,627 - __init__.pyc - 媒体库 G:\「剧集」\「国产短剧」\『连载』\「短剧连载」\拜托了，别追我 (2023)\Season 1 刮削完成
```

**Comment by jxxghp** [comment]
那是因为windows不支持这个几个特殊字符作为文件或者目录名

**Comment by SoTender** [comment]
> 那是因为windows不支持这个几个特殊[]字符作为文件或者目录名

是windows不支持，还是win版的MP不支持啊？

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/f7e048d0-f2f1-494b-b321-daa5b70208c3)
我看好像可以作为目录名啊

**Comment by SoTender** [comment]
> 那是因为windows不支持这个几个特殊[]字符作为文件或者目录名

![QQ截图20240312133214](https://github.com/jxxghp/MoviePilot/assets/127156952/b8fe79cf-8521-4c36-be3d-2eb134a72d8a)


我尝试不在文件名中添加[]这两个字符，并用插件更新元数据，得到了同样的报错信息：

- 【INFO】2024-03-12 13:32:25,604 - __init__.pyc - 开始刮削媒体库：G:\「剧集」\「韩剧」\『连载』\「韩剧连载」\不可能的婚礼 (2024) tmdbid=230198\Season 1 None ...
- 【INFO】2024-03-12 13:32:26,185 - __init__.pyc - 读取到本地nfo文件的tmdbid：230198
- 【INFO】2024-03-12 13:32:26,189 - tmdbapi.pyc - 正在查询TMDB电视剧：230198 ...
- 【INFO】2024-03-12 13:32:26,190 - tmdbapi.pyc - 230198 查询结果：不可能的婚礼
- 【INFO】2024-03-12 13:32:26,192 - __init__.pyc - 230198 TMDB识别结果：电视剧 不可能的婚礼 (2024)
- 【ERROR】2024-03-12 13:32:26,196 - __init__.pyc - 运行模块 scrape_metadata 出错：TheMovieDbModule - [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「韩剧」\\『连载』\\「韩剧连载」\\不可能的婚礼 (2024) tmdbid=230198\\Season 1\\Wedding.Impossible.S01E05.2024.1080p.FriDay.WEB-DL.H264.AAC-HHWEB.mkv\\BDMV'
- Traceback (most recent call last):
-   File "app\chain\__init__.py", line 97, in run_module
-   File "app\modules\themoviedb\__init__.py", line 250, in scrape_metadata
-   File "app\utils\system.py", line 396, in is_bluray_dir
-   File "pathlib.py", line 1235, in exists
-   File "pathlib.py", line 1013, in stat
- OSError: [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「韩剧」\\『连载』\\「韩剧连载」\\不可能的婚礼 (2024) tmdbid=230198\\Season 1\\Wedding.Impossible.S01E05.2024.1080p.FriDay.WEB-DL.H264.AAC-HHWEB.mkv\\BDMV'
- 
- 【INFO】2024-03-12 13:32:26,197 - __init__.pyc - 媒体库 G:\「剧集」\「韩剧」\『连载』\「韩剧连载」\不可能的婚礼 (2024) tmdbid=230198\Season 1 刮削完成


似乎还是被识别成了蓝光碟？因为有tmdbid=这个字段？？？

**Comment by jxxghp** [comment]
不是误判断为蓝光盘，而是偿试去判断是否为蓝光盘的时候出现了错误，错误原因是windows系统返回的：OSError: [WinError 50] 不支持该请求。  如果不是[]导致的，那就可能是=号或者有其它字符导致的。

```
    @staticmethod
    def is_bluray_dir(dir_path: Path) -> bool:
        """
        判断是否为蓝光原盘目录
        """
        # 蓝光原盘目录必备的文件或文件夹
        required_files = ['BDMV', 'CERTIFICATE']
        # 检查目录下是否存在所需文件或文件夹
        for item in required_files:
            if (dir_path / item).exists():
                return True
        return False

```

**Comment by SoTender** [comment]
> 不是误判断为蓝光盘，而是偿试去判断是否为蓝光盘的时候出现了错误，错误原因是windows系统返回的：OSError: [WinError 50] 不支持该请求。 如果不是[]导致的，那就可能是=号或者有其它字符导致的。

![image](https://github.com/jxxghp/MoviePilot/assets/127156952/a43082c0-5ade-49e6-9570-491f392231f6)
 
去除等号，得到了相同的结果：

- 【INFO】2024-03-12 13:52:15,669 - __init__.pyc - 媒体库刮削服务，立即运行一次
- 【INFO】2024-03-12 13:52:18,686 - __init__.pyc - 开始刮削媒体库：G:\「剧集」\「韩剧」\『连载』\「韩剧连载」\不可能的婚礼 (2024) tmdbid 230198\Season 1 MediaType.TV ...
- 【INFO】2024-03-12 13:52:19,075 - __init__.pyc - 读取到本地nfo文件的tmdbid：230198
- 【INFO】2024-03-12 13:52:19,078 - tmdbapi.pyc - 正在查询TMDB电视剧：230198 ...
- 【INFO】2024-03-12 13:52:19,080 - tmdbapi.pyc - 230198 查询结果：不可能的婚礼
- 【INFO】2024-03-12 13:52:19,082 - __init__.pyc - 230198 TMDB识别结果：电视剧 不可能的婚礼 (2024)
- 【ERROR】2024-03-12 13:52:19,085 - __init__.pyc - 运行模块 scrape_metadata 出错：TheMovieDbModule - [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「韩剧」\\『连载』\\「韩剧连载」\\不可能的婚礼 (2024) tmdbid 230198\\Season 1\\Wedding.Impossible.S01E05.2024.1080p.FriDay.WEB-DL.H264.AAC.mkv\\BDMV'
- Traceback (most recent call last):
-   File "app\chain\__init__.py", line 97, in run_module
-   File "app\modules\themoviedb\__init__.py", line 250, in scrape_metadata
-   File "app\utils\system.py", line 396, in is_bluray_dir
-   File "pathlib.py", line 1235, in exists
-   File "pathlib.py", line 1013, in stat
- OSError: [WinError 50] 不支持该请求。: 'G:\\「剧集」\\「韩剧」\\『连载』\\「韩剧连载」\\不可能的婚礼 (2024) tmdbid 230198\\Season 1\\Wedding.Impossible.S01E05.2024.1080p.FriDay.WEB-DL.H264.AAC.mkv\\BDMV'
- 
- 【INFO】2024-03-12 13:52:19,086 - __init__.pyc - 媒体库 G:\「剧集」\「韩剧」\『连载』\「韩剧连载」\不可能的婚礼 (2024) tmdbid 230198\Season 1 刮削完成

「和『应该是没有问题的，因为前面的 拜托了，别追我 (2023) 路径同样有这两个符号，也是可以正常跑起来了。


唯一的不同就是 tmdbid

**Comment by jxxghp** [comment]
@SoTender 那我也不清楚了，我改了下代码，如果明确不是目录则直接跳过不检查是否蓝光盘，更新后再试试看。

**Comment by SoTender** [comment]
不对，这样也会报同样的错误：
![QQ截图20240312135842](https://github.com/jxxghp/MoviePilot/assets/127156952/1af6ac89-6b0d-463f-b7fd-2045e90cf79c)


哎...看来跟win八字不合啊

**Comment by SoTender** [comment]
> @SoTender 那我也不清楚了，我改了下代码，如果明确不是目录则直接跳过不检查是否蓝光盘，更新后再试试看。

不对，这样也会报同样的错误：
![QQ截图20240312135842](https://github.com/jxxghp/MoviePilot/assets/127156952/1af6ac89-6b0d-463f-b7fd-2045e90cf79c)


哎...看来跟win八字不合啊
