### ISSUE TITLE
BUG 自定义识别词失效

### ISSUE THREAD

**Issue by MyGiki** [jxxghp/MoviePilot#1670]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

自定义识别词失效，我用的替换词！
Swallowed Star S04 2023 => Swallowed Star S01 2020 && Swallowed Star S01 <> 2020 >> EP+85
![01](https://github.com/jxxghp/MoviePilot/assets/107430324/af9bc450-298d-4cd7-bc5e-c9053845301a)

用了替换词测试识别正常
![002](https://github.com/jxxghp/MoviePilot/assets/107430324/99b3d6cf-98e2-4803-8e8b-e110ab86c001)

带主标题带有E字母或者带有集数（E**）时，替换词就失效了
![03](https://github.com/jxxghp/MoviePilot/assets/107430324/83940fff-c21e-412d-a38e-31a89f317192)

![04](https://github.com/jxxghp/MoviePilot/assets/107430324/9006bece-ea67-471d-9eee-e985e9d8a668)

因为标题带有E或者集数是，日志提示年份不匹配
![005](https://github.com/jxxghp/MoviePilot/assets/107430324/e6ffb0b4-332b-443a-ad27-d1fa0994026f)

**Comment by jxxghp** [comment]
前定位词把E包进去

**Comment by MyGiki** [comment]
@jxxghp 
大佬，我试了前定位加了E进去，Swallowed Star S01E
Swallowed Star S04 2023 => Swallowed Star S01 2020 && Swallowed Star S01E <> 2020 >> EP+85
![001](https://github.com/jxxghp/MoviePilot/assets/107430324/b189dcdf-6966-4872-a244-4f244613c406)


还是没效呢，集数偏移也没生效。
![1](https://github.com/jxxghp/MoviePilot/assets/107430324/b6c34343-0a77-4060-a835-f104f75f0ab4)

**Comment by jxxghp** [comment]
不对啊，你的第一个替换词没有考虑Exx吧？

**Comment by MyGiki** [comment]
@jxxghp
大佬我试了，第一个替换词加E，也不行！
Swallowed Star S04 2023 => Swallowed Star S01E 2020 && Swallowed Star S01E <> 2020 >> EP+85
被替换词加E，替换词加E，前定位也加E，也不行！
Swallowed Star S04E 2023 => Swallowed Star S01E 2020 && Swallowed Star S01E <> 2020 >> EP+85

**Comment by thsrite** [comment]
Swallowed.Star.S04E(\d{2}).2023 =>  Swallowed.Star.S01E\1.2020 && S01E <> 2020 >> EP+85

**Comment by MyGiki** [comment]
@thsrite
这你这个可以了，好复杂呢，我小白整不明白为啥要加(\d{2})和\1
