### ISSUE TITLE
关于自定义识别词的正则表达式支持问题

### ISSUE THREAD

**Issue by JxiaoC** [jxxghp/MoviePilot#1671]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自定义识别词的替换是否支持$1的替换方式？目前测试好像并未支持，还是有别的实现方式。

![微信截图_20240312115906](https://github.com/jxxghp/MoviePilot/assets/6435789/eebb99da-de6a-46e1-bfb6-e30bb99ae609)
![微信截图_20240312120100](https://github.com/jxxghp/MoviePilot/assets/6435789/9cecedae-1621-4cc7-b4f5-3170c97ad86a)

使用的替换关键词
One Piece S01E(\d*) 1999 => One Piece S22E$1 2024

替换目标
One Piece S01E1075 1999 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb
预期替换结果
One Piece S22E1075 2024 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb
最终替换结果

One Piece S22E$1 2024 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb

### 发生问题时系统日志和配置文件

```bash
11:57:57,480	
media.py
One Piece S22E$1 2024 2160p B-Global WEB-DL x264 AAC-AnimeS@ADWeb 识别到媒体信息：电视剧 海贼王真人版 (2023)
INFO	11:57:57,479	
themoviedb
One Piece TMDB识别结果：电视剧 海贼王真人版 (2023) 111110
INFO	11:57:57,478	
tmdbapi.py
111110 查询结果：ONE PIECE
INFO	11:57:57,477	
tmdbapi.py
正在查询TMDB电视剧：111110 ...
INFO	11:57:57,476	
themoviedb
One Piece 使用TMDB识别缓存：海贼王真人版
```

**Comment by jxxghp** [comment]
试下\1

**Comment by JxiaoC** [comment]
> 试下\1

谢谢！试了%1，也试了\$1, $$1, 就是没想过\1, 用\1好了！
