### ISSUE TITLE
[错误报告]: 目录监控插件动漫二级分类失效

### ISSUE THREAD

**Issue by spirytuslove** [jxxghp/MoviePilot#1672]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.7.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

目录监控插件之前版本可以正常在anime分类下创建二级动漫分类 现在失效了现在的动漫会直接在anime文件夹下

**Comment by spirytuslove** [comment]
我目前用的是插件中心的目录监控插件  监控目录指定了目的目录时电视剧和电影可以正常移动到二级分类目录里面 但动漫不会移动到二级目录里面而是直接在anime目录下 我anime目录下还有一个动漫分类 之前都是直接能移动到这个分类里面 现在是直接移动到了anime目录下
<img width="623" alt="iShot_2024-03-12_17 09 52" src="https://github.com/jxxghp/MoviePilot/assets/64483414/6442fad2-c396-4a0b-aaf8-f237376c9966">

**Comment by spirytuslove** [comment]
> 我目前用的是插件中心的目录监控插件 监控目录指定了目的目录时电视剧和电影可以正常移动到二级分类目录里面 但动漫不会移动到二级目录里面而是直接在anime目录下 我anime目录下还有一个动漫分类 之前都是直接能移动到这个分类里面 现在是直接移动到了anime目录下 <img alt="iShot_2024-03-12_17 09 52" width="623" src="https://private-user-images.githubusercontent.com/64483414/312010326-6442fad2-c396-4a0b-aaf8-f237376c9966.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzUxNTMsIm5iZiI6MTcxMDIzNDg1MywicGF0aCI6Ii82NDQ4MzQxNC8zMTIwMTAzMjYtNjQ0MmZhZDItYzM5Ni00YTBiLWFhZjgtZjIzNzM3NmM5OTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA5MTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNGQzMjczZDE4ZTFiMTQ4M2YyODRlZTM1MTlmMTM4N2U3OTc0YzFhNTQzMWM3ZmI5ZjI3NjcwMTM2NWQ0MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cLKdBaaO-0jawRYnx1tSYfpCvmcWbr6Ou9okNZFBR4">

<img width="782" alt="iShot_2024-03-12_17 16 14" src="https://github.com/jxxghp/MoviePilot/assets/64483414/965029e8-7042-44b3-b05e-b975af5406de">
<img width="1065" alt="iShot_2024-03-12_17 16 39" src="https://github.com/jxxghp/MoviePilot/assets/64483414/ecc53795-e185-4585-92c9-cd1219254ca7">

**Comment by jxxghp** [comment]
这个问题下个版本会修复，目前可以使用最新的category.yml模板，维护好anime分类下的二级分类解决。

**Comment by spirytuslove** [comment]
> 这个问题下个版本会修复，目前可以使用最新的category.yml模板，维护好anime分类下的二级分类解决。

好的感谢
