### ISSUE TITLE
文件刮削错误

### ISSUE THREAD

**Issue by 782042369** [jxxghp/MoviePilot#1673]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

原盘刮削文件识别错误
![1fcf2205c3c42769ea0aeb33de988fb0](https://github.com/jxxghp/MoviePilot/assets/28727900/04b9df61-f6be-4065-a3f2-844294a9904f)
电影和电视剧刮削没有正确匹配目录，刮削到了docker 容器卷内。
正确的地址 /download/影音硬链接/电影/外语电影
![b5c2d9e552e6ac8afcf065cc9393dc4e_720](https://github.com/jxxghp/MoviePilot/assets/28727900/27f08b4c-52d3-4aff-8402-55bc75cc9f73)
错误地址  /download/外语电影
![d924be7785e05a262d5701e61e36520a](https://github.com/jxxghp/MoviePilot/assets/28727900/397fb923-b2c6-4415-b3bb-7a623f4f4aad)

**Comment by 782042369** [comment]
刮削目录配置
![image](https://github.com/jxxghp/MoviePilot/assets/28727900/786eb8c5-f7f3-47d9-9b55-3d6ba4a4e865)

**Comment by jxxghp** [comment]
你的目录配错了，请看清配置项，名称是指名称，不是路径。

**Comment by 782042369** [comment]
我一开始配置的名称 刮削也会路径错误 才尝试改成绝对路径看好使不

> 你的目录配错了，请看清配置项，名称是指名称，不是路径。
