### ISSUE TITLE
[错误报告]: QB远程操作插件无法单独设置暂停周期或开始周期

### ISSUE THREAD

**Issue by imao97** [jxxghp/MoviePilot#1677]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

<img width="941" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/46474701/058a134e-2504-49f0-be3e-27cb091af65d">
当我单独设置暂停周期或开始周期时，插件无法正常使用

### 发生问题时系统日志和配置文件

```bash
无效
```

**Comment by hoey94** [comment]
我理解你的意思应该是要单独使用暂停周期或者是开始周期

**Comment by hoey94** [comment]
我已经提交了代码到MoviePilot-Plugin仓库: https://github.com/jxxghp/MoviePilot-Plugins/pull/101
