### ISSUE TITLE
蜜柑搜索不到动漫资源

### ISSUE THREAD

**Issue by spirytuslove** [jxxghp/MoviePilot#1680]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在站点里面测试密码连通正常 浏览里面也能加载出来资源 但搜索的话就是搜索不到资源 目前域名已经加代理了 能正常访问网站

搜索的是葬送的芙莉莲

**Comment by jxxghp** [comment]
@spirytuslove 已修复，要更新下资源包，密柑的搜索和浏览两套页面，最新版本把浏览改好了，搜索又问题了

**Comment by spirytuslove** [comment]
> @spirytuslove 已修复，要更新下资源包，密柑的搜索和浏览两套页面，最新版本把浏览改好了，搜索又问题了
好的感谢

**Comment by ListenXXK** [comment]
请问楼主重启后解决了吗 我还是搜索不到和下载
