### ISSUE TITLE
[微信订阅问题]: 怎么在微信上订阅电视剧的具体季度

### ISSUE THREAD

**Issue by jinhua523** [jxxghp/MoviePilot#1681]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v 1.7.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/35497576/7e0a57aa-c1c1-4503-978a-172be1b42263)
怎么在微信上订阅电视剧的具体季度

**Comment by jinhua523** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/35497576/9a19f93b-762b-478e-9572-362bcc9051d4)

**Comment by jxxghp** [comment]
@jinhua523 订阅 xxx 第x季

**Comment by jinhua523** [comment]
我试试看

**Comment by jinhua523** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/35497576/1d6b7268-53a1-4071-a54e-f0047d94ed1a)
原来如此
