### ISSUE TITLE
[错误报告]: 因没有zh-cn标题导致无法被搜索到的问题

### ISSUE THREAD

**Issue by Summer-Tail** [jxxghp/MoviePilot#1687]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索问题似乎没有解决，在tmdb页面中如果使用了 zh-sg作为备选语言的话，例如：星期三
![image](https://github.com/jxxghp/MoviePilot/assets/46812909/a3c1ebac-c9a0-4729-832b-82e1774bc65e)

但是在Mp的搜索中，无法搜索到

![image](https://github.com/jxxghp/MoviePilot/assets/46812909/978633b0-4c95-4722-a875-67d6094a8100)

**Comment by jxxghp** [comment]
目前是站点的搜索和匹配会使用zh-sg，词条搜索解决不了，依赖对方api接口。
