### ISSUE TITLE
[错误报告]: 憨憨的铃芽之旅搜索不到

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#169]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.2

### 问题类型

主程序运行问题

### 问题描述

憨憨的铃芽之旅搜索不到  

文件名 ：[[HHC].Suzume.2022.1080p.iTunes.WEB-DL.DD5.1.H264-HHWEB.torrent](https://hhanclub.top/download.php?id=42055)

副标题： 铃芽之旅/すずめの戸締まり | 类型:爱情/动画/奇幻 | 主演:原菜乃华/松村北斗/深津绘里/染谷将太/伊藤沙莉

名称测试ok的 
![image](https://github.com/jxxghp/MoviePilot/assets/51367628/43cab346-2ec3-4300-9037-dcaf32528af6)

**Comment by jxxghp** [comment]
@paysenyu 憨憨把电影纳入动漫分类了，导致搜索不出来
