### ISSUE TITLE
[错误报告]: 搜索功能优先度

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#170]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.2

### 问题类型

主程序运行问题

### 问题描述

搜索功能优先度不明确，站点管理中A站点优先度2， B站点优先度7

设定-规则-下载优先规则 ：站点优先

搜索结果：资源1-6集，A站全有， B站只有4-6集

订阅之后下载器1-3集走的A站，4-6集走的B站。   

订阅规则默认，无任何设置。

不确定优先逻辑是什么。。 按理说应该全走A站。 

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/d1f3fe12-6ee5-403f-8331-55c085e1fe84)

**Comment by jxxghp** [comment]
@paysenyu 你的过滤规则才是最优先的，然后才是站点

**Comment by paysenyu** [comment]
> @paysenyu 你的过滤规则才是最优先的，然后才是站点

明白了，但是如图上面：E05 （E04同样）， 左下角更多来源也有A站。。 默认的却是B站点，那么同一个资源，AB站都有的情况下，B站点在外面，A站点被归类到“更多来源”里面了，这里的优先度是根据什么的呢？ 或者有地方可以设置这一块吗？

**Comment by jxxghp** [comment]
@paysenyu 排在前面的会把同一个种子后面的站藏起来

**Comment by paysenyu** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51367628/d483e62f-3bd1-4d9e-b672-e53740874b7f)

看了一下，发现排在“更多资源“ 前面的那个站，似乎是按照种子数最多来排序的


按我的理解，也许是
![image](https://github.com/jxxghp/MoviePilot/assets/51367628/f75043a7-300b-466f-acc5-3b6a6fd2dec6)
这个没有生效，也可能是理解错了

**Comment by jxxghp** [comment]
下个版本加了个优先级日志打印，目前实在看不出来

**Comment by paysenyu** [comment]
> 下个版本加了个优先级日志打印，目前实在看不出来

感谢老大，幸苦了。
