### ISSUE TITLE
Transmission地址无法修改，重启后回滚

### ISSUE THREAD

**Issue by ProteinPig** [jxxghp/MoviePilot#1700]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.3-2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Transmission一开始设置为192.168.1.101:9091
修改为192.168.1.1.102:9092
docker容器重启后，会变为192.168.1.101:9091

**Comment by jxxghp** [comment]
那你因为你环境变量里设了吧。
请仔细阅读说明。
