### ISSUE TITLE
[Feature Request]: 站点浏览界面增加下载选项（非下载种子文件）

### ISSUE THREAD

**Issue by glenhuo** [jxxghp/MoviePilot#1703]
### 当前程序版本

v1.7.3-2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望可以在站点浏览界面增加下载选项，即直接点击下载后直接下载推送到QB，并非单单下载种子文件，而是下载识别并推送到QB,如图类似选项
![de19af61c4215ed26662f01d4b6a81f](https://github.com/jxxghp/MoviePilot/assets/41751084/ca663407-90f4-4f8f-8870-f9b5741ac451)

**Comment by sunr1s6** [comment]
> ### 当前程序版本
> v1.7.3-2
> 
> ### 运行环境
> Docker
> 
> ### 功能改进类型
> 主程序
> 
> ### 功能改进
> 希望可以在站点浏览界面增加下载选项，即直接点击下载后直接下载推送到QB，并非单单下载种子文件，而是下载识别并推送到QB,如图类似选项 ![de19af61c4215ed26662f01d4b6a81f](https://private-user-images.githubusercontent.com/41751084/313566866-ca663407-90f4-4f8f-8870-f9b5741ac451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNzgzMTUsIm5iZiI6MTcxMTI3ODAxNSwicGF0aCI6Ii80MTc1MTA4NC8zMTM1NjY4NjYtY2E2NjM0MDctOTBmNC00ZjhmLTg4NzAtZjliNTc0MWFjNDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDExMDAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MWIyYWI3YjQzZmIxZGZhNzgyYTY0ODJmYzZhYmQyMjZhM2Y1MDhiZTY1YjU0OGI0ZTk1MjFlYjRhZWRiODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlXdj4aPSpP5FQoxRH-EsorNjzpyFBciIV44DV3CK-g)
> 
> ### 参考资料
> _No response_

難道現在不可以？ 你點擊下種子看看

**Comment by cddjr** [comment]
你没配置下载器吧
