### ISSUE TITLE
[错误报告]: 官方README.md文档里1PTBA站点名字写错，导致认证错误。

### ISSUE THREAD

**Issue by Joyist2021** [jxxghp/MoviePilot#1705]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

几乎最新版本

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

官方README.md文档里1PTBA站点名字写错，导致认证错误。

错误的
1ptba	1PTBA_UID：用户ID     1PTBA_PASSKEY：密钥

正确的
1ptba	PTBA_UID：用户ID   PTBA_PASSKEY：密钥

文档内站点名字少写了1。

帮助更多小伙伴，希望更正一下。

### 发生问题时系统日志和配置文件

```bash
INFO:     Started server process [53]
INFO:     Waiting for application startup.
INFO:    singleton.py - 站点资源版本：1.2.5
INFO:    singleton.py - 认证资源版本：1.2.3
INFO:    singleton.py - ptba 用户认证成功！
INFO:    resource.py - 开始检测资源包版本...
INFO:    resource.py - 最新资源包版本：v10
INFO:    resource.py - user.sites.bin 资源包有更新，最新版本：v1.2.6
不使用代理更新程序
Release 更新模式
当前版本号：v1.7.3-2
最新版本号：v1.7.3-2
未发现新版本，跳过更新步骤...
```

补充一下：认证站点参数也是同样问题 AUTH_SITE=ptba

**Comment by Joyist2021** [comment]
docker环境变量似乎不支持数字开头
Docker 容器中的环境变量名通常遵循标准的 shell 变量命名规则，即可以包含字母、数字和下划线，但不能以数字开头。这是因为环境变量在 Linux 系统中通常被导出为 exportexport VAR_NAME=value 形式的 shell 命令，而在这里变量名前不能直接跟数字。

如果你尝试在 Dockerfile 或者 docker run 命令中设置一个以数字开头的环境变量，你会遇到类似这样的错误：

docker: invalid reference format.

**Comment by xqk1** [comment]
为什么设置了 PTBA_UID 和 PTBA_PASSKEY，依然不成功
