### ISSUE TITLE
[错误报告]: 通过目录监控入库的电影识别错误，无法通过重新整理进行识别

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#171]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.2

### 问题类型

主程序运行问题

### 问题描述

电影A通过目录监控入库,但是电影识别错误，却无法通过重新整理进行识别

### 发生问题时系统日志和配置文件

```bash
2023-08-18 20:18:52,153 - transfer.py -【INFO】开始转移下载器文件，参数：None 37257|电影
2023-08-18 20:18:52,303 - transfer.py -【ERROR】没有获取到种子，参数：e
```

**Comment by dlovew** [comment]
补充种子不在下载器中

**Comment by jxxghp** [comment]
下个版本支持
