### ISSUE TITLE
莫妮卡站点新番  无法搜索。

### ISSUE THREAD

**Issue by torasy** [jxxghp/MoviePilot#1711]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.71

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

莫妮卡站点新番  无法搜索。

**Comment by jxxghp** [comment]
给个日志

**Comment by torasy** [comment]
【INFO】2024-03-19 17:09:02,360 - command.py - 处理事件：notice.message - [<function IyuuMsg.send at 0x7f12c7c5bec0>]
【INFO】2024-03-19 17:09:02,475 - media.py - 开始搜索媒体信息：独自
【INFO】2024-03-19 17:09:02,481 - media.py - 独自 搜索到 20 条相关媒体信息
【INFO】2024-03-19 17:09:02,620 - media.py - 开始搜索媒体信息：独自
【INFO】2024-03-19 17:09:02,663 - media.py - 独自 搜索到 20 条相关媒体信息
【INFO】2024-03-19 17:09:02,891 - media.py - 开始搜索媒体信息：独自
【INFO】2024-03-19 17:09:02,930 - media.py - 独自 搜索到 20 条相关媒体信息
【INFO】2024-03-19 17:09:03,110 - media.py - 开始搜索媒体信息：独自
【INFO】2024-03-19 17:09:03,158 - media.py - 独自 搜索到 20 条相关媒体信息
【INFO】2024-03-19 17:09:04,060 - tmdbapi.py - 正在查询TMDB电视剧：127532 ...
【INFO】2024-03-19 17:09:04,064 - tmdbapi.py - 127532 查询结果：我独自升级
【INFO】2024-03-19 17:09:04,067 - themoviedb - 127532 TMDB识别结果：电视剧 我独自升级 (2024)
【INFO】2024-03-19 17:09:04,070 - tmdbapi.py - 正在获取剧集组年份：65d3916b51c01f017cc1a724...
【INFO】2024-03-19 17:09:04,072 - search.py - 开始搜索资源，关键词：我独自升级 ...
【INFO】2024-03-19 17:09:04,081 - spider.py - 开始请求：https://monikadesign.uk/torrents?perPage=100&name=%E6%88%91%E7%8B%AC%E8%87%AA%E5%8D%87%E7%BA%A7&categories[0]=6&categories[1]=7&categories[2]=5&categories[3]=1&categories[4]=8&categories[5]=2
【INFO】2024-03-19 17:09:05,205 - spider.py - 开始请求：https://monikadesign.uk/torrents?perPage=100&name=%E4%BF%BA%E3%81%A0%E3%81%91%E3%83%AC%E3%83%99%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97%E3%81%AA%E4%BB%B6&categories[0]=6&categories[1]=7&categories[2]=5&categories[3]=1&categories[4]=8&categories[5]=2
【INFO】2024-03-19 17:09:06,278 - spider.py - 开始请求：https://monikadesign.uk/torrents?perPage=100&name=Solo%20Leveling&categories[0]=6&categories[1]=7&categories[2]=5&categories[3]=1&categories[4]=8&categories[5]=2
【WARNING】2024-03-19 17:09:07,297 - indexer - 莫妮卡 未搜索到数据，耗时 3 秒
【INFO】2024-03-19 17:09:07,299 - search.py - 站点搜索进度：1 / 1
【INFO】2024-03-19 17:09:07,302 - search.py - 站点搜索完成，有效资源数：0，总耗时 3 秒
【WARNING】2024-03-19 17:09:07,305 - search.py - 我独自升级 未搜索到资源

**Comment by jxxghp** [comment]
@torasy 他们的新蕃是单独的页面吗？

**Comment by torasy** [comment]
![微信图片_20240319171133](https://github.com/jxxghp/MoviePilot/assets/160832008/b820d3e4-53d6-4fa3-82a2-60a4ac1a41ac)

**Comment by torasy** [comment]
不同的页面

**Comment by torasy** [comment]
![001](https://github.com/jxxghp/MoviePilot/assets/160832008/62ee2ee0-6bf6-4ed4-bcd9-96207da58ee7)

**Comment by jxxghp** [comment]
@torasy 目前不支持两个地址，只能二选一

**Comment by torasy** [comment]
请问？ 二选一的话要怎么配置。？  我尝试设置站点地址，不管设置哪个都是默认  https://www.ptlsp.com/torrents.php

而非https://monikadesign.uk/torrents/airing

**Comment by jxxghp** [comment]
@torasy 配不了，除非用自定义索引插件自已张。

**Comment by torasy** [comment]
额，，这个就不会了。。。

**Comment by AisukaYuki** [comment]
#1105

**Comment by torasy** [comment]
谢谢大佬
