### ISSUE TITLE
集数偏移似乎出错

### ISSUE THREAD

**Issue by TAN-Z-H** [jxxghp/MoviePilot#1716]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.2（群晖套件）

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

**如图，使用集数偏移时刮削了错误的元数据，本应为第35集的元数据，刮削成了第1集的元数据**
![ff16e40c8a22924908c6abc2f167d905](https://github.com/jxxghp/MoviePilot/assets/70757024/f3c2780a-813e-4f40-b050-cf012112e84c)
![e766a0b0c058dfd61c0449494423d256](https://github.com/jxxghp/MoviePilot/assets/70757024/a2ac90b5-e8b2-4b75-b791-7e09cca141b7)
![86428b381608e8a9dc7dc91e172bffba](https://github.com/jxxghp/MoviePilot/assets/70757024/e08a6d5d-3594-48fc-84be-9961e82a6388)
![image](https://github.com/jxxghp/MoviePilot/assets/70757024/795d1b62-fb7a-432a-8a59-f04551e60078)

**Comment by jxxghp** [comment]
你不是设的-34吗？
