### ISSUE TITLE
群晖套件下用Cloudflare IP优选这个插件无法更新Cloudflare SpeedTest版本

### ISSUE THREAD

**Issue by ncj1990** [jxxghp/MoviePilot#1718]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

【INFO】2024-03-20 16:21:20,028 - cloudflarespeedtest - Cloudflare CDN优选服务启动，立即运行一次
【INFO】2024-03-20 16:21:23,606 - cloudflarespeedtest - 检测到CloudflareSpeedTest有版本[v2.2.5]更新，开始安装
【ERROR】2024-03-20 16:21:23,620 - cloudflarespeedtest - CloudflareSpeedTest安装失败，无可用版本，停止运行
【ERROR】2024-03-20 16:21:23,621 - cloudflarespeedtest - 获取到最优ip格式错误，请重试
【ERROR】2024-03-20 16:21:23,625 - cloudflarespeedtest - 退出插件失败：cannot join current thread

网络环境可以科学

**Comment by jeblove** [comment]
测试过一切正常，有使用PROXY_HOST网络代理吗？

**Comment by ncj1990** [comment]
有使用PROXY_HOST网络代理

**Comment by luoling76** [comment]
你解决这个问题了么？

**Comment by awsl1110** [comment]
大哥，解决了吗，飞牛这边也是这样

**Comment by wendavid552** [comment]
会不会是因为ghproxy被墙了，换一下https://ghfast.top/ ？另外一个可选方案是自己下载CloudflareSpeedTest的安装包放到指定位置：https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.5
飞牛的话一般就是这里的linux_amd64这个

**Comment by awsl1110** [comment]
> 会不会是因为ghproxy被墙了，换一下https://ghfast.top/ ？另外一个可选方案是自己下载CloudflareSpeedTest的安装包放到指定位置：https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.5 飞牛的话一般就是这里的linux_amd64这个

不行，还是下载失败，只能手动，但是不知道放哪。。

**Comment by wendavid552** [comment]
> > 会不会是因为ghproxy被墙了，换一下[ghfast.top](https://ghfast.top/) ？另外一个可选方案是自己下载CloudflareSpeedTest的安装包放到指定位置：[XIU2/CloudflareSpeedTest@`v2.2.5` (release)](https://github.com/XIU2/CloudflareSpeedTest/releases/tag/v2.2.5) 飞牛的话一般就是这里的linux_amd64这个
> 
> 不行，还是下载失败，只能手动，但是不知道放哪。。

我看了代码，是将插件那个amd64的tar.gz改名CloudflareST_linux_amd64.tar.gz，然后如果你是docker的话，那就是在docker容器里面找到/config/plugins/CloudflareSpeedTest（可能叫这个名字？总之差不多）的文件夹，这就是这个插件的数据目录，放进去。

你可以先把存有CloudflareST_linux_amd64.tar.gz的目录挂载到比如/mnt下面，然后在飞牛里面打开容器里面的终端，检查一下是不是叫这个名字，是的话再拷贝进去

**Comment by wlnxing** [comment]
review 了一下代码， 发现下载时只取了http和https格式的代理，我之前使用的socks5格式的代理失败了， 换成https代理就成功了。也许可以支持一下socks5格式的代理？ 🤔   
~~不太会python~~

---

同样遇到了这个问题，找issue找到了这里, 留个临时解决方案在这里，希望可以帮助后面的人

**Comment by Travisss** [comment]
> review 了一下代码， 发现下载时只取了http和https格式的代理，我之前使用的socks5格式的代理失败了， 换成https代理就成功了。也许可以支持一下socks5格式的代理？ 🤔 ~不太会python~
> 
> 同样遇到了这个问题，找issue找到了这里, 留个临时解决方案在这里，希望可以帮助后面的人

感谢，一直解决不了这个问题，之前都是自己下载文件放到插件目录里。看到您的回复，解决了，太棒了，感谢！确实不能使用socks5代理
