### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by hoey94** [jxxghp/MoviePilot#1720]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

蝴蝶有两个链接，希望能支持ipv4的链接。
ipv6: hudbt.hust.edu.cn
ipv4: zeus.hamsters.space

当我使用ipv4登陆后，并在cookiecloud中添加ipv4域名，在mp运行cookiecloud并不能识别到ipv4域名
希望后续。

同时蝴蝶在使用ipv4登陆后，下载种子时默认使用的是ipv6 tracker，希望开发一个QB或者TR批量替换种子tracker的插件。

**Comment by jxxghp** [comment]
己支持

**Comment by hoey94** [comment]
佬给力！ 可以了
