### ISSUE TITLE
[Feature Request]: 希望“整理方式”添加“不整理”选项

### ISSUE THREAD

**Issue by BG8FRU** [jxxghp/MoviePilot#1721]
### 当前程序版本

 v1.7.4

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

主要用于多个PT站聚合搜索和下载，目前下载好以后只能选择软、硬链接、复制和移动，希望能添加“不整理”选项。

**Comment by fxzou** [comment]
同需求

**Comment by fxzou** [comment]
@BG8FRU 刚刚看了一下源码，发现只需要加一个环境变量：`DOWNLOADER_MONITOR` : `false`  就不会自动整理了

**Comment by BG8FRU** [comment]
@fxzou 添加环境变量后，成功，谢谢大佬！

**Comment by BG8FRU** [comment]
> @BG8FRU 刚刚看了一下源码，发现只需要加一个环境变量： : 就不会自动整理了`DOWNLOADER_MONITOR``false`

添加环境变量后，成功。谢谢大佬！
