### ISSUE TITLE
[错误报告]: 豆瓣想看 下载文件目录不和订阅优先级

### ISSUE THREAD

**Issue by yesuhegaoliao** [jxxghp/MoviePilot#1722]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

豆瓣想看的插件，订阅的电影无法按照订阅优先级去搜索下载，明明是选了免费，下载的都是有费的。而且通过豆瓣想看订阅下载的媒体库不会创建 电影 电视剧 动漫 目录分类

### 发生问题时系统日志和配置文件

```bash
不好意思，找不到日志了。另外感谢您的辛勤付出。
```

**Comment by jxxghp** [comment]
你的优先级规则呢？

**Comment by yesuhegaoliao** [comment]
![微信截图_20240324112405](https://github.com/jxxghp/MoviePilot/assets/164208104/2e627063-98a3-410c-9077-13a0178f477d)

**Comment by jxxghp** [comment]
豆瓣想看首次是搜索下载，使用的是搜索优先级，未下载完整的才会添加订阅，使用的才是订阅优先级。
新版本调整了逻辑，不搜索了，直接添加订阅。
