### ISSUE TITLE
启动报错：haproxy.main，如下日志一直循环，但是启动失败

### ISSUE THREAD

**Issue by softshield** [jxxghp/MoviePilot#1727]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

[ALERT] 081/200335 (51) : [haproxy.main()] FD limit (4096) too low for maxconn=4000/maxsock=8023. Please raise 'ulimit-n' to 8023 or more to avoid any trouble.This will fail in >= v2.3

Traceback (most recent call last):
,  File "/app/app/main.py", line 21, in <module>
,    from app.core.plugin import PluginManager
,  File "/app/app/core/plugin.py", line 9, in <module>
,    from app.helper.sites import SitesHelper
,ModuleNotFoundError: No module named 'app.helper.sites'

### 发生问题时系统日志和配置文件

```bash
不使用代理更新程序
,Release 更新模式
,当前版本号：v1.7.4
,最新版本号获取失败，继续启动...
,usermod: no changes
,[WARNING] 081/200800 (51) : [haproxy.main()] Cannot raise FD limit to 8023, limit is 4096. This will fail in >= v2.3
,Proxy dockerbackend started.
,Proxy dockerfrontend started.
,[NOTICE] 081/200800 (51) : haproxy version is 2.2.9-2+deb11u6
,[NOTICE] 081/200800 (51) : path to executable is /usr/sbin/haproxy
,[ALERT] 081/200800 (51) : [haproxy.main()] FD limit (4096) too low for maxconn=4000/maxsock=8023. Please raise 'ulimit-n' to 8023 or more to avoid any trouble.This will fail in >= v2.3
,Traceback (most recent call last):
,  File "/app/app/main.py", line 21, in <module>
,    from app.core.plugin import PluginManager
,  File "/app/app/core/plugin.py", line 9, in <module>
,    from app.helper.sites import SitesHelper
,[WARNING] 081/200817 (50) : [haproxy.main()] Cannot raise FD limit to 8023, limit is 4096. This will fail in >= v2.3
,ModuleNotFoundError: No module named 'app.helper.sites'
```

**Comment by softshield** [comment]
好像是今天更新后开始的

**Comment by liteng815** [comment]
可以了吗？我的也是这样
