### ISSUE TITLE
[错误报告]: 刷流插件对馒头站点不起效

### ISSUE THREAD

**Issue by yesuhegaoliao** [jxxghp/MoviePilot#1734]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.5

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

不知道是否站点更新的原因，刷流
![360截图20240324111232781](https://github.com/jxxghp/MoviePilot/assets/164208104/5e360ec5-5348-4243-bc6f-c06bf8ba3bfc)
插件对馒头不起效。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-24 10:06:14,807 - brushflow - 没有需要检查的刷流下载任务
【INFO】2024-03-24 10:06:14,783 - brushflow - 开始检查刷流下载任务 ...
【INFO】2024-03-24 10:01:17,814 - brushflow - 开始获取站点 馒头 的新种子 ...
【INFO】2024-03-24 10:01:17,788 - brushflow - 开始执行刷流任务 ...
2024/3/24 11:17:02  [32mINFO:[0m    transfer.py - 没有获取到已完成的下载任务
2024/3/24 11:17:02  [32mINFO:[0m    transfer.py - 开始执行下载器文件转移 ...
2024/3/24 11:15:43  TypeError: '<=' not supported between instances of 'int' and 'str'
2024/3/24 11:15:43              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/3/24 11:15:43      and not int(begin_seeder) <= torrent.seeders <= int(end_seeder):
2024/3/24 11:15:43    File "/app/app/plugins/brushflow/__init__.py", line 1406, in brush
2024/3/24 11:15:43               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/3/24 11:15:43      retval = job.func(*job.args, **job.kwargs)
2024/3/24 11:15:43    File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
2024/3/24 11:15:43  Traceback (most recent call last):
2024/3/24 11:15:43  Job "站点刷流服务 (trigger: date[2024-03-24 11:15:43 CST], next run at: 2024-03-24 11:15:43 CST)" raised an exception
2024/3/24 11:15:43  [32mINFO:[0m    brushflow - 开始获取站点 馒头 的新种子 ...
2024/3/24 11:15:43  [32mINFO:[0m    brushflow - 开始执行刷流任务 ...
2024/3/24 11:15:40  INFO:     192.168.10.111:0 - "GET /api/v1/plugin/?state=market HTTP/1.1" 200 OK
2024/3/24 11:15:40  [32mINFO:[0m    plugin.py - 共获取到 54 个第三方插件
2024/3/24 11:15:40  INFO:     192.168.10.111:0 - "GET /api/v1/plugin/?state=installed HTTP/1.1" 200 OK
2024/3/24 11:15:40  INFO:     192.168.10.111:0 - "PUT /api/v1/plugin/BrushFlow HTTP/1.1" 200 OK
2024/3/24 11:15:40      站点刷流服务 (trigger: date[2024-03-24 11:15:43 CST], pending)
2024/3/24 11:15:40      站点刷流检查服务 (trigger: interval[0:05:00], pending)
2024/3/24 11:15:40  Pending jobs:
2024/3/24 11:15:40  [32mINFO:[0m    scheduler.py - 注册插件站点刷流服务：站点刷流服务 - interval
2024/3/24 11:15:40  [32mINFO:[0m    brushflow - 站点刷流服务启动，立即运行一次
```

**Comment by jxxghp** [comment]
1.7.6修复了

**Comment by yesuhegaoliao** [comment]
大佬太厉害了，膜拜。

**Comment by yesuhegaoliao** [comment]
大佬，刷流任务还是显示一直失败。

【INFO】2024-03-24 20:07:43,485 - brushflow - 刷流任务执行完成
【WARNING】2024-03-24 20:07:43,464 - brushflow - Dragon Ball Z 1989 1080p USA BluRay Remux AVC TrueHD 5.1 2Audio-ilongge@PTH 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,410 - brushflow - shanghaimeisudianyingzhipiancjingdiandonghua 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,355 - brushflow - The Walking Dead S01-S11 COMPLETE 1080p BluRay REMUX AVC TrueHD 7.1-FraMeSToR 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,302 - brushflow - Sailor Moon R 1993 1080p AVC DTS-HD MA 2.0-Anonymous@U2 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,247 - brushflow - Dian Gu Li De Ke Xue S02 2024 1080p HDTV H264 MP2 2.0-CatEDU 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,192 - brushflow - Happy Star III 2007 PAL DVD5 添加刷流任务失败！
【WARNING】2024-03-24 20:07:43,137 - brushflow - Fairies.Albums.S02.2020.2160p.WEB-DL.H265.AAC-HHWEB 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,980 - brushflow - Final Space S01 USA Blu-Ray AVC DTS-HD MA 5.1-LATENCY 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,913 - brushflow - Jian.Zheng.Xiang.Gang.Gu.Gong.2022.2160p.WEB-DL.H265.AAC5.1-CatEDU 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,854 - brushflow - Final.Space.S01-S03.1080p.WEB-DL.AVC.AAC 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,799 - brushflow - Skip to Loafer BDRip 1080p x265 FLAC@Nekomoe kissaten&VCB-Studio 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,743 - brushflow - Star.Wars.The.Bad.Batch.S03E01.Confined.2160p.DSNP.WEB-DL.DDP5.1.HDR.H.265-NTb.mkv 添加刷流任务失败！
【WARNING】2024-03-24 20:07:42,689 - brushflow - Messy Goes to Okido 2015 1080P WEB-DL H264 AAC 添加刷流任务失败！
【INFO】2024-03-24 20:07:42,634 - brushflow - 开始获取站点 馒头 的新种子 ...
【INFO】2024-03-24 20:07:42,614 - brushflow - 开始执行刷流任务 ...

2024/3/24 20:07:43  [32mINFO:[0m    brushflow - 刷流任务执行完成
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - Dragon Ball Z 1989 1080p USA BluRay Remux AVC TrueHD 5.1 2Audio-ilongge@PTH 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - shanghaimeisudianyingzhipiancjingdiandonghua 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - The Walking Dead S01-S11 COMPLETE 1080p BluRay REMUX AVC TrueHD 7.1-FraMeSToR 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - Sailor Moon R 1993 1080p AVC DTS-HD MA 2.0-Anonymous@U2 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - Dian Gu Li De Ke Xue S02 2024 1080p HDTV H264 MP2 2.0-CatEDU 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - Happy Star III 2007 PAL DVD5 添加刷流任务失败！
2024/3/24 20:07:43  [33mWARNING:[0m brushflow - Fairies.Albums.S02.2020.2160p.WEB-DL.H265.AAC-HHWEB 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Final Space S01 USA Blu-Ray AVC DTS-HD MA 5.1-LATENCY 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Jian.Zheng.Xiang.Gang.Gu.Gong.2022.2160p.WEB-DL.H265.AAC5.1-CatEDU 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Final.Space.S01-S03.1080p.WEB-DL.AVC.AAC 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Skip to Loafer BDRip 1080p x265 FLAC@Nekomoe kissaten&VCB-Studio 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Star.Wars.The.Bad.Batch.S03E01.Confined.2160p.DSNP.WEB-DL.DDP5.1.HDR.H.265-NTb.mkv 添加刷流任务失败！
2024/3/24 20:07:42  [33mWARNING:[0m brushflow - Messy Goes to Okido 2015 1080P WEB-DL H264 AAC 添加刷流任务失败！
2024/3/24 20:07:42  [32mINFO:[0m    brushflow - 开始获取站点 馒头 的新种子 ...
2024/3/24 20:07:42  [32mINFO:[0m    brushflow - 开始执行刷流任务 ...
