### ISSUE TITLE
[Feature Request]: 不能指定搜索多季资源中某一季

### ISSUE THREAD

**Issue by ghost** [jxxghp/MoviePilot#1738]
### 当前程序版本

v1.7.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![Snipaste_2024-03-24_18-02-47](https://github.com/jxxghp/MoviePilot/assets/89040381/0753310e-fe65-4c39-8585-56986a4be8ef)

如图所示，在搜索的时候 搜索框只能填写名称  ，搜索后显示TMDB的结果  ，点击进入之后 无法精确搜索某一季资源！ 点击 按标题搜索依然不行。
导致了在多季影视剧中想要单独搜索某一季的资源，会要浪费很多时间和资源。
希望在关联到TMDB之后 搜索按钮在每一级都有，能具体搜索到某一季 或者像NT那种

### 参考资料

以前NT在搜索框那可以 添加 搜索年份 名称 第几季 等详细资料。希望能改进下

**Comment by zhu0823** [comment]
好像是需要输入中文“第3季”，“第一集”等
