### ISSUE TITLE
升级最新版本找不到 控制台->实验室

### ISSUE THREAD

**Issue by dwwl886** [jxxghp/MoviePilot#1740]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.7.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

升级后系统后台找不到  控制台->实验室

### 发生问题时系统日志和配置文件

```bash
升级后系统后台找不到  控制台->实验室
```

**Comment by AkaiShuichi7** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/24691868/c9848f84-ecef-4af6-9be9-0a4ea5e3b9a2)
`控制台`->`实验室`是在 馒头 的后台。

**Comment by dwwl886** [comment]
设置好apikey   测试还是会提示  馒头 连通性测试失败：Cookie已失效

**Comment by weida295** [comment]
请问是怎么手工维护呢？是把存取的令牌填在cookie里面吗？

**Comment by AkaiShuichi7** [comment]
> 好apikey测试还是会提示设置馒头性测试失败：Cookie已失效

需要进行手动维护。

**Comment by AkaiShuichi7** [comment]
> 请问是怎么手工维护呢？是把访问的令牌填在cookie里面吗？

获取新的Cookie:
![XP](https://github.com/jxxghp/MoviePilot/assets/24691868/f17b2deb-0c81-4bd6-a986-b308dea635e3)

填入MP:
![MP](https://github.com/jxxghp/MoviePilot/assets/24691868/a74c424e-527d-4dfd-a00b-649254db3ea0)

一定一定关闭CookieCloud中的馒头同步，不然MP还会在CookieCloud中获取到之前的Cookie：
![3](https://github.com/jxxghp/MoviePilot/assets/24691868/a939f383-344b-4df1-9f44-fbd8701741fe)

**Comment by shunlongyang** [comment]
楼上的方法都试过了，还是显示cookie过期

**Comment by chenmdg** [comment]
复制cookie的时候User-Agent也要复制上

**Comment by vvnocode** [comment]
> 复制cookie的时候User-Agent也要复制上

按照上面的步骤都尝试了，并且复制了User-Agent。但是还是提示Cookie过期。

**Comment by samyang211** [comment]
> > 请问是怎么手工维护呢？是把访问的令牌填在cookie里面吗？
> 
> 获取新的Cookie: ![XP](https://private-user-images.githubusercontent.com/24691868/317094223-f17b2deb-0c81-4bd6-a986-b308dea635e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDk5NjcsIm5iZiI6MTcxMjMwOTY2NywicGF0aCI6Ii8yNDY5MTg2OC8zMTcwOTQyMjMtZjE3YjJkZWItMGM4MS00YmQ2LWE5ODYtYjMwOGRlYTYzNWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA5MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTUxNGMxZjQ2MTE5Y2IzN2UzYzNiNzM5NWU4MzExYWJhNjVkMzE1YmZkYjkxZTA5Y2QwMGYzOTQyNTFjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZdmaMz5qXVqXVeLaR26K4zkrrt2VurmcAC1mwhFk6Rg)
> 
> 填入MP: ![MP](https://private-user-images.githubusercontent.com/24691868/317094331-a74c424e-527d-4dfd-a00b-649254db3ea0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDk5NjcsIm5iZiI6MTcxMjMwOTY2NywicGF0aCI6Ii8yNDY5MTg2OC8zMTcwOTQzMzEtYTc0YzQyNGUtNTI3ZC00ZGZkLWEwMGItNjQ5MjU0ZGIzZWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA5MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ODRkYTRmZWJiZjVmNWE4YzVkZjBjOGE3NDViZGQxN2QzODJiOGU0OWNjNmEwZDkxYTIxYzJhMWM0MjYzNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrSdeZ43pePZEHYl11ExAyV44Ni2TrBvZ2puhUVECtM)
> 
> 一定一定关闭CookieCloud中的馒头同步，不然MP还会在CookieCloud中获取到之前的Cookie： ![3](https://private-user-images.githubusercontent.com/24691868/317094489-a939f383-344b-4df1-9f44-fbd8701741fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDk5NjcsIm5iZiI6MTcxMjMwOTY2NywicGF0aCI6Ii8yNDY5MTg2OC8zMTcwOTQ0ODktYTkzOWYzODMtMzQ0Yi00ZGYxLTlmNDQtZmJkODcwMTc0MWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA5MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OGVjYmMwMjZjNzY0OWQ2MDBkNjY5NTYwMmU5ODU3NmNiNjc3YWEzMjkzMDVkYzMxYjY5NGNiNTlhODI2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qbqu0A8mE29CR0towsTl2cq-725K-vtV15aQkNi4v94)

啊？  馒头以后不能用cookiecloud了么。
