### ISSUE TITLE
本地运行方式部署，帮助说明里面的“app/plugins”、“app/helper”的绝对路径是啥？

### ISSUE THREAD

**Issue by reidmex** [jxxghp/MoviePilot#1742]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.7.6-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

“app/plugins”、“app/helper”的绝对路径是啥？

### 发生问题时系统日志和配置文件

```bash
不涉及
```

**Comment by jxxghp** [comment]
项目根路径啊
