### ISSUE TITLE
找不到刷流插件

### ISSUE THREAD

**Issue by Jiangyebnn** [jxxghp/MoviePilot#1744]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

找不到刷流插件
![1711364204710](https://github.com/jxxghp/MoviePilot/assets/129022717/fbb4ca45-1c58-4de8-aabf-03e0f5528912)
![1711364183107](https://github.com/jxxghp/MoviePilot/assets/129022717/4ba597dc-c574-4bc9-9e5a-9ef470a20390)

### 发生问题时系统日志和配置文件

```bash
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
ERROR:   doh.py - 解析器(1.1.1.1)请求错误: <urlopen error EOF occurred in violation of protocol (_ssl.c:1002)>
INFO:    doh.py - 已解析 [api.themoviedb.org] 为 [18.244.214.89]
INFO:    site.py - 开始同步CookieCloud站点 ...
ERROR:   site.py - CookieCloud同步失败：CookieCloud参数不正确
INFO:    login.py - 用户 admin 登录成功！
INFO:    plugin.py - 共获取到 54 个第三方插件
INFO:    plugin.py - 加载插件：ChatGPT 版本：1.3
INFO:    plugin.py - 共获取到 54 个第三方插件
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 没有获取到已完成的下载任务
INFO:    mediaserver.py - 开始同步媒体库 emby 的数据 ...
INFO:    mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：0
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 没有获取到已完成的下载任务
INFO:    plugin.py - 共获取到 54 个第三方插件
ERROR:   doh.py - 解析器(1.1.1.1)请求错误: <urlopen error EOF occurred in violation of protocol (_ssl.c:1002)>
INFO:    doh.py - 已解析 [api.github.com] 为 [192.30.255.116]
```

**Comment by therehello** [comment]
你好，请问你的解决方案是什么

**Comment by doomlordcn** [comment]
一样找不到刷流插件
