### ISSUE TITLE
[错误报告]: 微信交互，设置了代理，但任然通过本地IP请求微信

### ISSUE THREAD

**Issue by hlhk2017** [jxxghp/MoviePilot#1745]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

配置的微信通知，报错wechat.py - 发送请求失败，错误信息：not allow to access from your ip, hint: [1711363915424272140870476], from ip: xxx.xxx.xxx.xxx（路由器wan口IP）, more info at https://open.work.weixin.qq.com/devtool/query?e=60020 stderr 18:51:55
微信的配置如下图，已设置代理，代理试过ip以及域名形式http://以及https://
<img width="716" alt="759004018FFD39E9E4DF7559336CFFB9" src="https://github.com/jxxghp/MoviePilot/assets/32770630/8e00660d-1b9a-4e76-ae71-82cf2fc660c5">

**Comment by chenmdg** [comment]
配置好，重启下docker

**Comment by hlhk2017** [comment]
> 配置好，重启下docker
😂我重启过容器啊，要重启docker服务吗

**Comment by chenmdg** [comment]
> > 配置好，重启下docker
> > 😂我重启过容器啊，要重启docker服务吗

我最开始不行，重启了下docker容器就好了，你可以在服务》缓存清理执行下再重启试试。代理http://IP

**Comment by chinafuxi** [comment]
重启容器解决，建议在页面增加相关提示
