### ISSUE TITLE
软件版本没有提示是否为最新，且无法查看历史版本

### ISSUE THREAD

**Issue by GateCross** [jxxghp/MoviePilot#1746]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.6-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

从1.7.5开始，无法查看软件历史版本，不能判断是否有最新版本
![image](https://github.com/jxxghp/MoviePilot/assets/23492993/00a1487a-c791-4cf5-aba4-4fe4a5fab7eb)

### 发生问题时系统日志和配置文件

```bash
/api/v1/system/versions返回无数据，具体如下
data:{}
message:null
success:false
```

**Comment by jxxghp** [comment]
设置GITHUB_TOKEN
