### ISSUE TITLE
[错误报告]: 全新安装1.7.6-1版本插件市场缺少插件

### ISSUE THREAD

**Issue by GilgameshXI** [jxxghp/MoviePilot#1749]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.6-1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

新建1.7.6-1版本插件市场缺少插件（站点自动签到，配置中心等）

### 发生问题时系统日志和配置文件

【INFO】2024-03-29 00:43:24,061 - singleton.py - 站点资源版本：1.2.8
【INFO】2024-03-29 00:43:24,067 - singleton.py - 认证资源版本：1.2.4
【INFO】2024-03-29 00:43:24,171 - singleton.py - iyuu 用户认证成功！
【INFO】2024-03-29 00:43:24,173 - resource.py - 开始检测资源包版本...
【INFO】2024-03-29 00:43:24,388 - doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.110.133]
【INFO】2024-03-29 00:43:24,839 - resource.py - 最新资源包版本：v12
【INFO】2024-03-29 00:43:24,841 - resource.py - 所有资源已最新，无需更新
【INFO】2024-03-29 00:43:25,231 - module.py - Moudle Loaded：BangumiModule
【INFO】2024-03-29 00:43:25,233 - module.py - Moudle Loaded：DoubanModule
【INFO】2024-03-29 00:43:25,245 - module.py - Moudle Loaded：EmbyModule
【INFO】2024-03-29 00:43:25,246 - module.py - Moudle Loaded：FanartModule
【INFO】2024-03-29 00:43:25,248 - module.py - Moudle Loaded：FileTransferModule
【INFO】2024-03-29 00:43:25,253 - module.py - Moudle Loaded：FilterModule
【INFO】2024-03-29 00:43:25,255 - module.py - Moudle Loaded：IndexerModule
【INFO】2024-03-29 00:43:25,429 - module.py - Moudle Loaded：QbittorrentModule
【INFO】2024-03-29 00:43:25,431 - module.py - Moudle Loaded：SubtitleModule
【INFO】2024-03-29 00:43:25,471 - category.py - 已加载二级分类策略 category.yaml
【INFO】2024-03-29 00:43:25,472 - module.py - Moudle Loaded：TheMovieDbModule
【INFO】2024-03-29 00:43:25,474 - module.py - Moudle Loaded：TheTvDbModule
【INFO】2024-03-29 00:43:25,483 - module.py - Moudle Loaded：TransmissionModule
【INFO】2024-03-29 00:43:27,156 - module.py - Moudle Loaded：WechatModule
【INFO】2024-03-29 00:43:27,160 - plugin.py - 开始安装第三方插件...
【INFO】2024-03-29 00:43:27,163 - doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.110.133] (缓存)
【INFO】2024-03-29 00:43:27,637 - plugin.py - 共获取到 57 个第三方插件
【INFO】2024-03-29 00:43:27,639 - plugin.py - 第三方插件安装完成
【ERROR】2024-03-29 00:43:28,187 - module.py - 加载模块 crossseed 失败：No module named 'bencodepy' - Traceback (most recent call last):
  File "/app/app/helper/module.py", line 31, in load
    module = importlib.import_module(full_package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/plugins/crossseed/__init__.py", line 27, in <module>
    from plugins.crossseed.cross_seed_helper import (CrossSeedHelper, CSSiteConfig,
  File "/app/app/plugins/crossseed/__init__.py", line 27, in <module>
    from plugins.crossseed.cross_seed_helper import (CrossSeedHelper, CSSiteConfig,
  File "/app/app/plugins/crossseed/cross_seed_helper.py", line 6, in <module>
    import bencodepy
ModuleNotFoundError: No module named 'bencodepy'

【INFO】2024-03-29 00:43:32,732 - doh.py - 已解析 [api.themoviedb.org] 为 [13.224.163.85]
【INFO】2024-03-29 00:44:19,323 - login.py - 用户 C.C. 登录成功！
【INFO】2024-03-29 00:44:29,529 - site.py - 开始同步CookieCloud站点 ...

**Comment by WhyO778** [comment]
加1，一样遇到这个问题了

**Comment by massivehard2014** [comment]
添加认证站点了吗？认证站点的新手考核通过了吗？

**Comment by xyl912158708** [comment]
+1，遇到一样的问题了，认证的iyuu

**Comment by daixuan201** [comment]
+1，最开始用IYUU认证，后来换成HH认证，都是一样的，缺少站点签到、配置中心等4个插件

**Comment by daixuan201** [comment]
+1，最开始用IYUU认证，后来换成HH认证，都是一样的。docker启动时显示成功加载了56个插件，实际上插件市场只有52个，缺少站点签到、配置中心等4个插件

**Comment by daixuan201** [comment]
找到解决办法了，进入Mp的文件管理，app/app/plugins文件夹里面除了_pycache之外的全部删除（因为我也不知道哪个文件对应哪个插件），重启docker

**Comment by jxxghp** [comment]
无法重现，不知道什么情况。

**Comment by GilgameshXI** [comment]
我是全新安装的1.7.6-1插件就是不全，然后指定的1.7.6在线升级到1.7.6-1插件库才完整的

jxxghp ***@***.***> 于 2024年3月27日周三 下午3:11写道：

**Comment by XuCcc** [comment]
同样问题 升级到1.7.7 依然无法找到站点自动签到

```bash
INFO:    singleton.py - 认证资源版本：1.2.4
ERROR:   singleton.py - iyuu认证出错：非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/
INFO:    singleton.py - hdfans 用户认证成功！
INFO:    resource.py - 开始检测资源包版本...
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133]
INFO:    resource.py - 最新资源包版本：v12
INFO:    resource.py - 所有资源已最新，无需更新
INFO:    module.py - Moudle Loaded：BangumiModule
INFO:    module.py - Moudle Loaded：DoubanModule
INFO:    module.py - Moudle Loaded：EmbyModule
INFO:    module.py - Moudle Loaded：FanartModule
INFO:    module.py - Moudle Loaded：FileTransferModule
INFO:    module.py - Moudle Loaded：FilterModule
INFO:    module.py - Moudle Loaded：IndexerModule
INFO:    module.py - Moudle Loaded：QbittorrentModule
INFO:    module.py - Moudle Loaded：SubtitleModule
INFO:    module.py - Moudle Loaded：TelegramModule
INFO:    module.py - Moudle Loaded：TheMovieDbModule
INFO:    module.py - Moudle Loaded：TheTvDbModule
INFO:    plugin.py - 开始安装第三方插件...
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
INFO:    doh.py - 已解析 [raw.githubusercontent.com] 为 [185.199.111.133] (缓存)
ERROR:   doh.py - 解析器(1.0.0.1)请求错误: <urlopen error _ssl.c:985: The handshake operation timed out>
INFO:    plugin.py - 共获取到 99 个第三方插件
INFO:    plugin.py - 第三方插件安装完成
ERROR:   module.py - 加载模块 crossseed 失败：No module named 'bencodepy' - Traceback (most recent call last):
  File "/app/app/helper/module.py", line 31, in load
    module = importlib.import_module(full_package_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/plugins/crossseed/__init__.py", line 27, in <module>
    from plugins.crossseed.cross_seed_helper import (CrossSeedHelper, CSSiteConfig,
  File "/app/app/plugins/crossseed/__init__.py", line 27, in <module>
    from plugins.crossseed.cross_seed_helper import (CrossSeedHelper, CSSiteConfig,
  File "/app/app/plugins/crossseed/cross_seed_helper.py", line 6, in <module>
    import bencodepy
ModuleNotFoundError: No module named 'bencodepy'
```

**Comment by vicjl** [comment]
> 无法重现，不知道什么情况。

目前看好像是crossseed插件的问题，青蛙辅种助手，我的移除掉就没问题了

**Comment by XuCcc** [comment]
> > 无法重现，不知道什么情况。
> 
> 目前看好像是crossseed插件的问题，青蛙辅种助手，我的移除掉就没问题了

我没有这个插件 依然找不到站点自动签到插件
