### ISSUE TITLE
【卡死】匹配完成，共匹配到 32 个资源

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#1752]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索的时候：卡死在【匹配完成，共匹配到 32 个资源】这个页面

**Comment by Whichbfj28** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/8e6bd272-8785-4c02-a5c6-cb514aec1963)

**Comment by jxxghp** [comment]
加了代理？调长代理超时时间。

**Comment by Whichbfj28** [comment]
> 加了代理？调长代理超时时间。
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/24450b4b-4f12-4adb-a6e0-56a3ed795089)
没加代理，今天测试的。现在变成了卡死在排序界面
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/50f68cfe-3987-4e5a-b09f-a45ac46cee10)

用微信的交互可以正常显示。唯独用网页搜索的时候卡死。
另外：对比chrome插件PTPP的搜索来说。moviepilot的搜索速度可以说是龟速

**Comment by Whichbfj28** [comment]
建议：搜索前先对站点进行连通性测试。比如OB的这几天打不开。会一直卡到等到超时才显示搜索出来结果

**Comment by jxxghp** [comment]
@Whichbfj28 连通性测试不是一样要耗时吗？连不上都要等超时返回！

**Comment by Whichbfj28** [comment]
> @Whichbfj28 连通性测试不是一样要耗时吗？连不上都要等超时返回！

因为测试连通性可以有多种方法。可以设置超时时间
比如用ping。2秒反应 直接判定为超时，跳过此站点，【不在乎误判的话，可以设置1秒没反应就判定为超时】 比如ping 不输出 *ms、或者不输出ttl
比如用curl。2秒没反应 直接判定超时，跳过此站点【如果站点用了cf 会有Just a moment输出、站点域名输出
目前的超时 主观上感觉应该是30秒
