### ISSUE TITLE
馒头没办法更新 cookie ，手动一直显示过期

### ISSUE THREAD

**Issue by maidou0215** [jxxghp/MoviePilot#1764]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

馒头站点没办法使用，手动填 cookie agent 都是失效；
用户名密码登录显示：未知错误；

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-03-27 21:15:23,338 - browser.py - 网页操作失败: ENOENT: no such file or directory, mkdtemp '/var/packages/MoviePilot/target/tmp/playwright-artifacts-DMwFtN'

【INFO】2024-03-27 21:20:22,017 - site.py - CookieCloud同步成功：更新了2个站点，新增了0个站点
【INFO】2024-03-27 21:20:22,016 - site.py - 站点【冰淇淋】连通性正常，不同步CookieCloud数据
【INFO】2024-03-27 21:20:21,199 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x7f61d1670180>, <function SiteChain.clear_site_data at 0x7f61d16b7d80>]
【INFO】2024-03-27 21:20:21,186 - site.py - 更新站点 m-team.cc Cookie ...
【INFO】2024-03-27 21:20:19,085 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x7f61d1670180>, <function SiteChain.clear_site_data at 0x7f61d16b7d80>]
【INFO】2024-03-27 21:20:19,064 - site.py - 更新站点 m-team.io Cookie ...
```

**Comment by maidou0215** [comment]
冰淇淋站点没问题。。馒头怎么试都不行，之前是好的。

**Comment by hnlyxjb** [comment]
用这个馒头地址 https://xp.m-team.io 从Chrome换edge抓ck，或者开无痕抓，我和你一样问题，换个浏览器解决，开无痕什么的也可以试试！

**Comment by HAN915** [comment]
馒头站点更新后一直就连不上了，试了楼上的方法，换浏览器抓ck也不管用

**Comment by maidou0215** [comment]
> 馒头站点更新后一直就连不上了，试了楼上的方法，换浏览器抓ck也不管用
我原来用 edge 的，换了 chrome 登录填了 cookie 和  agent，然后去馒头控制台实验室打开这个好了；
https://github.com/jxxghp/MoviePilot/issues/1740

**Comment by vvnocode** [comment]
> > > 馒头站点更新后一直就连不上了，试了楼上的方法，换浏览器抓ck也不管用
> > > 我原来用 edge 的，换了 chrome 登录填了 cookie 和  agent，然后去馒头控制台实验室打开这个好了；
> > > #1740
> > > 换chrome抓取了cookie和agent，手动到mp里填写了以后，还是提示失效，实验室那个令牌也打开了
> > > 实在不知道哪里出问题了

是的，我也遇到了一样的情况
