### ISSUE TITLE
[错误报告]: v1.7.7升级后启动报错

### ISSUE THREAD

**Issue by hotlcc** [jxxghp/MoviePilot#1765]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

启动报错

### 发生问题时系统日志和配置文件

```bash
Error submitting job "TmdbChain.get_random_wallpager (trigger: interval[0:30:00], next run at: 2024-03-27 22:10:40 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:10:49 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:04 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:19 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:34 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "同步CookieCloud站点 (trigger: interval[1 day, 0:00:00], next run at: 2024-03-27 22:11:37 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:49 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:04 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:19 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:34 CST)" to executor "default"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by hotlcc** [comment]
<img width="863" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/14865895/55b2772c-d88e-4642-bbb7-091003899895">

**Comment by hotlcc** [comment]
<img width="719" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/14865895/09468737-2b7b-4a33-89c6-e37fe266f1e7">

**Comment by hotlcc** [comment]
上面是三个错误

**Comment by hotlcc** [comment]
> <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/14865895/317354701-09468737-2b7b-4a33-89c6-e37fe266f1e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTcyNzIsIm5iZiI6MTcxMTU1Njk3MiwicGF0aCI6Ii8xNDg2NTg5NS8zMTczNTQ3MDEtMDk0Njg3MzctMmI3Yi00YTMzLTg5YzYtZTM3ZmUyNjZmMWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2MjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZmUxMmQ0ZTdjMTM2YWY0NjRiNjhiMDAzYmFiYjY5MDJmMjUzZDJhZmNjODNjMjE1ZTcyMzBiMjQzMzA4NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xti2M6b_2Lw9v2anTKYivM1bhmK557GH9OlaW9sLEp8">

这个我没有开启CookieCloud功能也报错。

**Comment by hotlcc** [comment]
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/14865895/317354542-55b2772c-d88e-4642-bbb7-091003899895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTcyNDYsIm5iZiI6MTcxMTU1Njk0NiwicGF0aCI6Ii8xNDg2NTg5NS8zMTczNTQ1NDItNTViMjc3MmMtZDg4ZS00NjQyLWJiYjctMDkxMDAzODk5ODk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2MjkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzZjZDQ3ZDcwOTNmNzRiMzVhMGU4MDhmNjI1Y2ZjNjEyZGVmYmMzMDQyOTBmZmZkNzNmOTBkYWRmN2Y0YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J67jgORs57YhM2KYcnbXzwVytrQr9aPuHCK9xOY6WyE">

这个应该是昨天更新什么东西导致的。

**Comment by hotlcc** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 1.7.7
> 
> ### 运行环境
> Docker
> 
> ### 问题类型
> 主程序运行问题
> 
> ### 问题描述
> 启动报错
> 
> ### 发生问题时系统日志和配置文件
> ```shell
> Error submitting job "TmdbChain.get_random_wallpager (trigger: interval[0:30:00], next run at: 2024-03-27 22:10:40 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:10:49 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:04 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:19 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:34 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "同步CookieCloud站点 (trigger: interval[1 day, 0:00:00], next run at: 2024-03-27 22:11:37 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:11:49 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:04 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:19 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> Error submitting job "DirMonitor.send_msg (trigger: interval[0:00:15], next run at: 2024-03-27 22:12:34 CST)" to executor "default"
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 988, in _process_jobs
>     executor.submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
>     self._do_submit_job(job, run_times)
>   File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
>     f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
>     raise RuntimeError('cannot schedule new futures after '
> RuntimeError: cannot schedule new futures after interpreter shutdown
> ```

这个问题后面docker容器重新创建后没再遇到过，但感觉还是有潜在问题。

**Comment by jxxghp** [comment]
一般是没有完全停止导致的。图一是插件的问题，不影响启动。

**Comment by hotlcc** [comment]
> 一般是没有完全停止导致的。图一是插件的问题，不影响启动。

第一个问题docker停止再启动后又出现了，现在启动不了了，还是同样的错误

**Comment by hotlcc** [comment]
> > 一般是没有完全停止导致的。图一是插件的问题，不影响启动。
> 
> 第一个问题docker停止再启动后又出现了，现在启动不了了，还是同样的错误

第一个问题，排查发现和我新提交的【下载器助手】插件有关，进一步排查发现是因为`get_command` 和`get_api`这两个函数返回了`[]`或者`[{}]`导致。待会我提个fix。这块底层感觉还是要做个兼容。

另外请教一下，我的`get_page`函数中也只有`pass`，为什么页面上还是展示了**详情**菜单项啊？

@jxxghp
