### ISSUE TITLE
重启MP后 青蛙辅种助手插件丢失，再次安装安装不上，插件运行的时候不显示运行状态小绿点。并且插件下载次数不显示了

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1768]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.7.7，后端版本：v1.7.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

1、重启MP后青蛙辅种助手插件丢失，有时候安装提示安装成功，但是实际没安装上。
2、插件在运行的时候不显示运行状态小绿点。

**Comment by lingjiameng** [comment]
@kingcard1131 状态显示后续会修复

**Comment by kingcard1131** [comment]
附上一些重启时候报错的日志：

moviepilot-moviepilot-1  | ERROR:   module.py - 加载模块 crossseed 失败：cannot import name 'dumps' from 'bencode' (/moviepilot/.local/lib/python3.11/site-packages/bencode/__init__.py) - Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/app/app/helper/module.py", line 31, in load
moviepilot-moviepilot-1  |     module = importlib.import_module(full_package_name)
moviepilot-moviepilot-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
moviepilot-moviepilot-1  |     return _bootstrap._gcd_import(name[level:], package, level)
moviepilot-moviepilot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
moviepilot-moviepilot-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
moviepilot-moviepilot-1  |   File "/app/app/plugins/crossseed/__init__.py", line 27, in <module>
moviepilot-moviepilot-1  |     from bencode import dumps, loads
moviepilot-moviepilot-1  | ImportError: cannot import name 'dumps' from 'bencode' (/moviepilot/.local/lib/python3.11/site-packages/bencode/__init__.py)
