### ISSUE TITLE
[错误报告]: 配置中心插件失效了

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#1769]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/115156545/ae2ba53f-a147-43af-ba98-5835a007be10)
这个插件失效了
开启写入app.env,调整配置保存后，没有后续反应。
手动在app.env记事本修改参数重启 也不会体现到这插件上面

**Comment by cng10001** [comment]
开启“启用插件”的模式点击保存，可用，但是点击保存后等待时间也很长

**Comment by jxxghp** [comment]
> 开启“启用插件”的模式点击保存，可用，但是点击保存后等待时间也很长

因为要重新加载生效，相当于重启，所以时间长。

**Comment by cng10001** [comment]
> > 开启“启用插件”的模式点击保存，可用，但是点击保存后等待时间也很长
> 
> 因为要重新加载生效，相当于重启，所以时间长。

![image](https://github.com/jxxghp/MoviePilot/assets/115156545/feb8b916-c6fd-450c-bb1a-ff5f7c60d59d)
哦懂了，可能我记错了，必须同时开启“启用插件”和“写入APP.env”才会马上写入app.env
如果想直接写入app.env，现在如果没打开“启用插件”就有点疑惑，希望大佬能改进下
