### ISSUE TITLE
媒体库能支持自定义库么，比如像NT的那个目录同步，自己设置对应的下载目录同步到对应的媒体库么。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#177]
### 当前程序版本

1.0.2

### 功能改进

使用场景比如家庭公用一个影音服务器，有些限制类的电影或者电视剧，单独同步到独立的电影或者电视剧媒体库，因为像emby都是可以设置媒体库权限的。目前看了下，所有的媒体文件都是同步到一个目录里。
只要可以设置分级，但是个人觉得一般的电影分级都不太好用和精准。还是需要自己手动分类。
这样又涉及到了下载目录的可自定义选择了。

**Comment by vevechen** [comment]
多硬盘也同样需要这个功能，非常期待功能改进。

**Comment by werran2** [comment]
是啊 ，我的nt三个下载目录对应三个媒体库，想转到mp工作量好大
