### ISSUE TITLE
[错误报告]: 猫站搜索及站点浏览返回结果列表标题为空

### ISSUE THREAD

**Issue by CharlesChen0431** [jxxghp/MoviePilot#1770]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

多站搜索结果只有猫站没有结果，相同关键词在原站搜索均有结果。
在站点管理页面中浏览标签得到结果列表如下：
![image](https://github.com/jxxghp/MoviePilot/assets/39345199/d968ee30-5a4e-4be5-867a-6c1cc881a93f)
目前就是猫有返回结果，但是不知为何，标题均为空 None，目前所有其他自有的6个站点均正常。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-03-28 15:10:38,513 - search.py - 过滤完成，剩余 13 个资源
【INFO】2024-03-28 15:10:38,507 - search.py - 匹配完成，共匹配到 0 个资源
【WARNING】2024-03-28 15:10:38,503 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,499 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,494 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,488 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,482 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,476 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,471 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,466 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,462 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,456 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,451 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,443 - search.py - 猫站 - None 标题不匹配
【WARNING】2024-03-28 15:10:38,437 - search.py - 猫站 - None 标题不匹配
【INFO】2024-03-28 15:10:38,432 - search.py - 标题：事与愿违的不死冒险者，原标题：望まぬ不死の冒険者，别名：['事与愿违的不死冒险者', '非自愿的不死冒险者', 'Nozomanu Fushi no Bōkensha', 'Nozomanu Fushi no Boukensha', '非自願的不死冒險者', 'The Unwanted Undead Adventurer', '원치 않는 불사의 모험가', 'Нежеланно бессмертный авантюрист', 'O Aventureiro Morto-Vivo Indesejado', 'Небажано немертвий шукач пригод', 'Mạo Hiểm Giả Bất Tử Ngoài Mong Muốn', 'เส้นทางพลิกผันของราชันอมตะ']
【INFO】2024-03-28 15:10:38,428 - search.py - 站点搜索完成，有效资源数：13，总耗时 3 秒
【INFO】2024-03-28 15:10:38,424 - search.py - 站点搜索进度：1 / 1
【INFO】2024-03-28 15:10:38,419 - indexer - 猫站 搜索完成，耗时 3 秒，返回数据：13
【INFO】2024-03-28 15:10:35,054 - spider.py - 开始请求：https://pterclub.com/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E4%BA%8B%E4%B8%8E%E6%84%BF%E8%BF%9D%E7%9A%84%E4%B8%8D%E6%AD%BB%E5%86%92%E9%99%A9%E8%80%85&cat404=1&cat403=1&cat405=1&cat402=1
【INFO】2024-03-28 15:10:34,916 - search.py - 开始搜索资源，关键词：事与愿违的不死冒险者 ...
【INFO】2024-03-28 15:10:34,828 - themoviedb - 197848 TMDB识别结果：电视剧 事与愿违的不死冒险者 (2024)
【INFO】2024-03-28 15:10:34,824 - tmdbapi.py - 197848 查询结果：事与愿违的不死冒险者
【INFO】2024-03-28 15:10:34,821 - tmdbapi.py - 正在查询TMDB电视剧：197848 ...
【INFO】2024-03-28 15:10:34,814 - tmdbapi.py - 197848 查询结果：事与愿违的不死冒险者
【INFO】2024-03-28 15:10:34,589 - tmdbapi.py - 正在查询TMDB电视剧：197848 ...
```

**Comment by sjtuross** [comment]
这个问题感觉存在有一段时间了，印象中我就没见过搜索结果里面有猫站的，还以为是连接的问题

**Comment by z3shan33** [comment]
没猫，不然想研究一下

**Comment by jxxghp** [comment]
@sjtuross 你在站点里开了影响UI的选项

**Comment by CharlesChen0431** [comment]
> @sjtuross 你在站点里开了影响UI的选项
请问下UI要设置成什么样才能正常获取？我看了一下，网站好像没有重置设置的按钮
![image](https://github.com/jxxghp/MoviePilot/assets/39345199/f44be70f-3cac-4cc8-97ef-865dd0a9373b)

**Comment by sjtuross** [comment]
> @sjtuross 你在站点里开了影响UI的选项

@jxxghp 印象中我没改过UI方面的设置，我尝试修改了一些网站设置，都没解决。就以下搜索结果的UI来看，标题是存在的，年份也是存在，我还能怎么排查？可能的问题会不会是站点定义里面没有抓取到标题字段？

![image](https://github.com/jxxghp/MoviePilot/assets/940110/c885a539-0ad6-4ea1-8fd0-ad6f955eb7e5)

以下是我的网站设置

![image](https://github.com/jxxghp/MoviePilot/assets/940110/c5b22b8b-ea0b-4c4c-818c-1590e228f693)

**Comment by jxxghp** [comment]
![IMG_7424](https://github.com/jxxghp/MoviePilot/assets/51039935/7087f553-9b0f-4433-a0a5-f52f8f73545d)
我也不知道是哪个，之前也有人提过问题，也是这个原因。

**Comment by sjtuross** [comment]
那你的网站设置能贴一下吗？我照抄试试看

**Comment by cddjr** [comment]
是不是配置的rss影响了结果？

**Comment by sjtuross** [comment]
> 是不是配置的rss影响了结果？

感谢提醒，我删了站点设置里猫站的RSS，但问题依旧。是不是只能本地debug才能追踪到问题的根源啊

**Comment by InfinityPacer** [comment]
> > @sjtuross 你在站点里开了影响UI的选项
> 
> @jxxghp 印象中我没改过UI方面的设置，我尝试修改了一些网站设置，都没解决。就以下搜索结果的UI来看，标题是存在的，年份也是存在，我还能怎么排查？可能的问题会不会是站点定义里面没有抓取到标题字段？
> 
> ![image](https://private-user-images.githubusercontent.com/940110/318022100-c885a539-0ad6-4ea1-8fd0-ad6f955eb7e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjU5MTYsIm5iZiI6MTcxMjQ2NTYxNiwicGF0aCI6Ii85NDAxMTAvMzE4MDIyMTAwLWM4ODVhNTM5LTBhZDYtNGVhMS04ZmQwLWFkNmY5NTVlYjdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNDUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWM2MDA2ZmU5ZTczMTBiZDMwYjE3M2NiYzJjNzhkNDAwMGE1MzAzMjYyOWVmMDViZmE2MTg3ZGVlMzA5OTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WQUJ5_S2HdTdkuIwZvmDN1F6sp7ETfnJ1fNJWIF0tNQ)
> 
> 以下是我的网站设置
> 
> ![image](https://private-user-images.githubusercontent.com/940110/318023111-c5b22b8b-ea0b-4c4c-818c-1590e228f693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjU5MTYsIm5iZiI6MTcxMjQ2NTYxNiwicGF0aCI6Ii85NDAxMTAvMzE4MDIzMTExLWM1YjIyYjhiLWVhMGItNGM0Yy04MThjLTE1OTBlMjI4ZjY5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwNDUzMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzc4OTYwZjVmNmM2ZjI4MmViMDRjMTk1YmE1NGIxZDU5ZTFjMGNiY2Q3MzFhNzE5N2ExNmJhNmJjYjU3MGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.538JMZgXCCfO7Tbq3AbwquXMy-oWrnB2XWFJ2L2xjt8)

勾选显示预览图标，重启Docker

**Comment by sjtuross** [comment]
> 勾选显示预览图标，重启Docker

@InfinityPacer 感谢大佬，这个牛皮癣问题总算解决了，之前试过各种设置都没用，关键是没有重启Docker，再次感谢！

@jxxghp 同时希望mp的猫站站点定义能兼容一下不勾选“显示预览图标”的情况，因为访问网站时，加载预览会消耗不必要的流量

**Comment by Pazuzu5688** [comment]
@InfinityPacer it works, thank you.
