### ISSUE TITLE
1、首页实时上传速率一直显示488.28或者244.14KB/s；2、docker-compose重建容器后插件不显示下载次数，内建重启可以显示插件下载次数

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1771]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.7.7，后端版本：v1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

首页实时上传速率一直显示488.28或者244.14KB/s；
1、不知道这俩问题有没有关系，下载器使用的是QB（4.6.3和4.6.4都试过），1.7.7版本之前一直正常！系统健康检查一切正常。
![image](https://github.com/jxxghp/MoviePilot/assets/53737003/2be6c278-5bce-4eb6-8477-333727949899)
2、docker-compose重建容器后插件不显示下载次数，内建重启可以显示插件下载次数，不知道是不是配置没有同步。

下面付的日志不知道与这些问题有没有关系，只是附上了报错日志。

感谢大佬！

### 发生问题时系统日志和配置文件

```bash
moviepilot-moviepilot-1 | ERROR: module.py - 加载模块 crossseed 失败：cannot import name 'dumps' from 'bencode' (/moviepilot/.local/lib/python3.11/site-packages/bencode/init.py) - Traceback (most recent call last):
moviepilot-moviepilot-1 | File "/app/app/helper/module.py", line 31, in load
moviepilot-moviepilot-1 | module = importlib.import_module(full_package_name)
moviepilot-moviepilot-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1 | File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
moviepilot-moviepilot-1 | return _bootstrap._gcd_import(name[level:], package, level)
moviepilot-moviepilot-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moviepilot-moviepilot-1 | File "", line 1204, in _gcd_import
moviepilot-moviepilot-1 | File "", line 1176, in _find_and_load
moviepilot-moviepilot-1 | File "", line 1147, in _find_and_load_unlocked
moviepilot-moviepilot-1 | File "", line 690, in _load_unlocked
moviepilot-moviepilot-1 | File "", line 940, in exec_module
moviepilot-moviepilot-1 | File "", line 241, in _call_with_frames_removed
moviepilot-moviepilot-1 | File "/app/app/plugins/crossseed/init.py", line 27, in
moviepilot-moviepilot-1 | from bencode import dumps, loads
moviepilot-moviepilot-1 | ImportError: cannot import name 'dumps' from 'bencode' (/moviepilot/.local/lib/python3.11/site-packages/bencode/init.py)
```

**Comment by cddjr** [comment]
我这里qb4.6.3 + mp1.7.7 暂时没法复现你的第一个问题，下载速度能正确显示吗？

**Comment by kingcard1131** [comment]
下载速度可以正常显示，我清了缓存还是488.28KB/s，重启MP，重建MP镜像，重启QB，升级QB,问题依旧。应该是我自己哪里的缓存吧

**Comment by cddjr** [comment]
实际上传速度是多少？ 
另外尝试取消勾选下载器 tr，只保留qb，再看实时速率是否正常？

**Comment by kingcard1131** [comment]
实际上传是0 ，我只启用TR和QB都是这个值。感觉我的零点就是488.28，不知道哪出问题了

**Comment by jxxghp** [comment]
问题2是要能连上服务器才会显示，前两天oracle cloud网络宕了十几个小时，期间连不上。
