### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by ZACKLZ** [jxxghp/MoviePilot#1773]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![微信截图_20240328173537](https://github.com/jxxghp/MoviePilot/assets/82872715/d5c6a35d-dc5d-46e3-8140-d121ebda040f)
打开启用DNS over HTTPS出现以下问题：
1、插件库安装插件经常出现无法连接的报错问题
2、重启容器后，经常会丢失已经安装的插件，重新出现在插件商店中，且点击安装后报错同上图
3、成功安装部分插件后，插件列表不显示已安装的插件

关闭后恢复

**Comment by jxxghp** [comment]
@ZACKLZ 有没有设置GITHUB_TOKEN，被guthub限流了，跟这个开关没关系。插件不显示，你看是哪个，有的插件有问题。

**Comment by ZACKLZ** [comment]
> @ZACKLZ有没有设置GITHUB_TOKEN，被guthub限流了，跟这个切换没关系。插件不显示，你看是哪个，有的插件有问题。

没有设置github_token，开启DoH后，有部分插件消失，关闭后插件处于未安装状态，重新安装恢复正常
