### ISSUE TITLE
mt 网站无法正常搜索，站点cookie失效

### ISSUE THREAD

**Issue by hk10271027** [jxxghp/MoviePilot#1782]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

无法搜索到mt的资源

**Comment by q871214** [comment]
我也是 cookie失效  >_<

**Comment by cqboyone** [comment]
我也是

**Comment by cqboyone** [comment]
新的cookie是很长的，同步后变成短的了

**Comment by Robs87** [comment]
> 新的cookie是很长的，同步后变成短的了

我也是，为啥
