### ISSUE TITLE
[错误报告]: 有一个报错，但好像没发现影响哪里了

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/MoviePilot#1785]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![QQ截图20240329182201](https://github.com/jxxghp/MoviePilot/assets/5012570/cb738576-41ae-4400-9906-cdeb892b9fe4)

**Comment by hwtwch** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/161803236/c19ec41d-d3fc-4200-be6d-735756627d8f)
我也遇到类似错误!

**Comment by kingcard1131** [comment]
我也遇到这个错误

**Comment by jxxghp** [comment]
青蛙辅种插件报错，升级插件版本。

**Comment by DDSDerek** [comment]
@jxxghp 不是青蛙辅助的原因，重启容器即可解决
