### ISSUE TITLE
https://kamept.com/index.php这个站点添加不了

### ISSUE THREAD

**Issue by keduol** [jxxghp/MoviePilot#1786]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.7.7

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

![812e2cb33aee151d1c157e4d0898d792](https://github.com/jxxghp/MoviePilot/assets/62869084/e48cde69-312f-4ece-a618-d52b60c4611e)
添加站点显示不支持或者未通过但其他站点正常 希望可以把他整进去

### 发生问题时系统日志和配置文件

```bash
未找到对应日志
```

**Comment by jxxghp** [comment]
这是什么内容的PT站？

**Comment by jxxghp** [comment]
cosav你来这提bug？
