### ISSUE TITLE
[错误报告]: 搜索结果如果站点有分页，mp只会抓取第一页内容

### ISSUE THREAD

**Issue by Euruson** [jxxghp/MoviePilot#1790]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用搜索功能时发现结果比在站点网页搜索时少。发现是由于资源太多，站点对结果进行了分页，而mp不会对其他页进行抓取。

比如在dmhy搜索迷宫饭，会发现有多页结果，而mp只会抓取[第一页](https://share.dmhy.org/topics/list?keyword=%E8%BF%B7%E5%AE%AB%E9%A5%AD)的80条记录，而总共记录有几百条。
<img width="164" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/27568823/36430981-0d63-4b49-b1fe-436306682587">

**Comment by LAN-Cliv** [comment]
因为RSS返回最大值只有这么多，建议转QB管理RSS订阅，或者从PT站点订阅动漫

**Comment by Euruson** [comment]
> 因为RSS返回最大值只有这么多，建议转QB管理RSS订阅，或者从PT站点订阅动漫

貌似不是的，搜索好像没有走rss，[rss](https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%BF%B7%E5%AE%AB%E9%A5%AD)里面给的记录是全的

**Comment by LAN-Cliv** [comment]
> > 因为RSS返回最大值只有这么多，建议转QB管理RSS订阅，或者从PT站点订阅动漫
> 
> 貌似不是的，搜索好像没有走rss，[rss](https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%BF%B7%E5%AE%AB%E9%A5%AD)里面给的记录是全的

# 确实，抱歉我之前没有查证就回复~
我尝试了一下~看了下日志，获取的确实是搜索值。
我搜索了迷宫饭，返回126个值，过滤之后最后得到109个有效资源
MP是从三个搜索链接来进行获取信息的，分别为中文，英文，日语来搜索
![QQ截图20240402120421](https://github.com/jxxghp/MoviePilot/assets/18377783/57346776-b040-4e95-9a13-6e917a43f8d7)
### 确实会缺失页数较多的信息

所以我尝试了一个办法
已知订阅时可以设定自定义搜索词
所以，添加迷宫饭为订阅后
我将`[[喵萌奶茶屋&LoliHouse] 迷宫饭]`
作为了自定义搜索词，然后指定动漫花园进行搜索
![QQ截图20240402121258](https://github.com/jxxghp/MoviePilot/assets/18377783/193773b4-fb2a-479b-ad92-db3a0a304e2c)

日志回馈了MP开始从该链接获取信息：`https://dmhy.org/topics/list?keyword=%E5%96%B5%E8%90%8C%E5%A5%B6%E8%8C%B6%E5%B1%8B%20LoliHouse%20%E8%BF%B7%E5%AE%AB%E9%A5%AD`

最终得到了我想要的字幕组和订阅结果
希望能帮得上你

**Comment by Euruson** [comment]
> > > 因为RSS返回最大值只有这么多，建议转QB管理RSS订阅，或者从PT站点订阅动漫
> > 
> > 
> > 貌似不是的，搜索好像没有走rss，[rss](https://share.dmhy.org/topics/rss/rss.xml?keyword=%E8%BF%B7%E5%AE%AB%E9%A5%AD)里面给的记录是全的
> 
> # 确实，抱歉我之前没有查证就回复~
> 我尝试了一下~看了下日志，获取的确实是搜索值。 我搜索了迷宫饭，返回126个值，过滤之后最后得到109个有效资源 MP是从三个搜索链接来进行获取信息的，分别为中文，英文，日语来搜索 ![QQ截图20240402120421](https://private-user-images.githubusercontent.com/18377783/318635975-57346776-b040-4e95-9a13-6e917a43f8d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzQ4NDEsIm5iZiI6MTcxMjAzNDU0MSwicGF0aCI6Ii8xODM3Nzc4My8zMTg2MzU5NzUtNTczNDY3NzYtYjA0MC00ZTk1LTlhMTMtNmU5MTdhNDNmOGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA1MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZmZmMTdiZjk5YWY3MDZkZTA1ZjgyZjczNjJlMjQ1NWUwMWYyOTVlYjZkZjUxZWVhNzFhOTI3MzM2ZTM3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VtmiRa-L6ZRnSP71cCgnrMpGSPkUNs6zbmvxnPFKLT0)
> 
> ### 确实会缺失页数较多的信息
> 所以我尝试了一个办法 已知订阅时可以设定自定义搜索词 所以，添加迷宫饭为订阅后 我将`[[喵萌奶茶屋&LoliHouse] 迷宫饭]` 作为了自定义搜索词，然后指定动漫花园进行搜索 ![QQ截图20240402121258](https://private-user-images.githubusercontent.com/18377783/318638745-193773b4-fb2a-479b-ad92-db3a0a304e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzQ4NDEsIm5iZiI6MTcxMjAzNDU0MSwicGF0aCI6Ii8xODM3Nzc4My8zMTg2Mzg3NDUtMTkzNzczYjQtZmIyYS00NzliLWFkOTItZGIzYTBhMzA0ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA1MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMTFiNmQ4ODZmOGNmNmEzZWJiN2IxYzg1YjI3MjFiZWZiOGQwNjI1Y2E3MzRjOTA4MTViOGQ2Y2U0YTkwMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A3Puehi0JVQcHFYVs4dyrYnNzkSBNBUyE6GDeBd5tYM)
> 
> 日志回馈了MP开始从该链接获取信息：`https://dmhy.org/topics/list?keyword=%E5%96%B5%E8%90%8C%E5%A5%B6%E8%8C%B6%E5%B1%8B%20LoliHouse%20%E8%BF%B7%E5%AE%AB%E9%A5%AD`
> 
> 最终得到了我想要的字幕组和订阅结果 希望能帮得上你

谢谢回复，确实是使用订阅时的一种解决方案。但是一般的搜索功能还是会有所限制，比如在pt站搜索一些有很多资源的老片（EVA）或者长连续剧（海贼王，火影等等），所以还是希望能够解决该问题。

**Comment by cddjr** [comment]
这个貌似都是这样设计的，包括ptpp插件也是只取第一页结果。 简单的方法是在站点设置增加每页数量，比如一页100个种子。

**Comment by jxxghp** [comment]
翻页比较困难，无法支持

**Comment by daxiguazhi** [comment]
翻页不是加上页参数就行了么，比如说搜索首页是
https://www.dmhy.org/topics/list?keyword=夏日重现
第四页是
https://www.dmhy.org/topics/list/page/4?keyword=夏日重现
是识别不到总页数还是有什么其他的考虑

**Comment by cddjr** [comment]
> 翻页不是加上页参数就行了么，比如说搜索首页是
> https://www.dmhy.org/topics/list?keyword=夏日重现
> 第四页是
> https://www.dmhy.org/topics/list/page/4?keyword=夏日重现
> 是识别不到总页数还是有什么其他的考虑

不要只会说，要去做，多考虑边界问题
