### ISSUE TITLE
[错误报告]: 文件管理搜索框无法点击

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#1797]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

文件管理界面的搜索框应该放在最上面或者固定在下面不要跟随列表滚动，放在最下面文件列表一直刷新，没办法点击到搜索框

**Comment by Hcczz** [comment]
同样的问题
希望或者做个分页显示 不然文件太多 要等好久才显示完 ctrl+F都要等一会

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/1488017bf24da090c455b115334287056ee72513
