### ISSUE TITLE
最近两个版本都有模块错误的问题

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/MoviePilot#1798]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/61082200/21ae1cd0-3470-4f2e-8f7e-bcb6143b9d9a)

**Comment by jxxghp** [comment]
都是第三方插件依赖没装的报错，拉最新镜像，重置。

**Comment by bcseputetto** [comment]
@jxxghp 好像这是一个普遍的问题，并没有安装vcbanimemonitor和PushDeer 也会报这个错误，而且这两个插件是来自官方插件仓库的
https://github.com/jxxghp/MoviePilot-Plugins/tree/main/plugins/pushdeermsg
https://github.com/jxxghp/MoviePilot-Plugins/tree/main/plugins/vcbanimemonitor
