### ISSUE TITLE
docker升级1.7.8后设定页面无法渲染

### ISSUE THREAD

**Issue by hotlcc** [jxxghp/MoviePilot#1800]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

点击设定菜单后页面顶端进度条一直在加载，控制台console报错：
<img width="593" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/14865895/41d56e34-e9c6-4c44-82ca-214d6c118b73">
控制台network所有请求均无异常

**Comment by hotlcc** [comment]
浏览器控制台application中全部清除后问题解决

**Comment by cddjr** [comment]
是的，需要Ctrl+F5强制刷新，否则不仅仅是设置进不去，站点管理等很多都不能访问。
