### ISSUE TITLE
整理VCB压制组作品在exe下不能安装

### ISSUE THREAD

**Issue by lly0010** [jxxghp/MoviePilot#1802]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Windows

### 问题类型

插件问题

### 问题描述

整理VCB压制组作品在exe下不能安装
![屏幕截图 2024-04-01 084358](https://github.com/jxxghp/MoviePilot/assets/104768330/e80d276e-e2ef-4b2c-a6ee-b434c1532863)

**Comment by lly0010** [comment]
并未安装第三方插件库

**Comment by jxxghp** [comment]
Windows 绿色版本，第三方插件都不能安装。

**Comment by lly0010** [comment]
这不是自带的吗，没有加第三方插件库

**Comment by jxxghp** [comment]
> 这不是自带的吗，没有加第三方插件库

检查下你的配置串，上面这个插件在官方和第三方库都有的，如果都配了有可能会被第三方库覆盖。

**Comment by lly0010** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/104768330/956cd1f1-9e6c-44ec-8bf3-278bda47fac4)
就一个这个
