### ISSUE TITLE
[错误报告]: 最新版1.7.8有问题，设定无法打开，无法搜索资源。

### ISSUE THREAD

**Issue by weni09** [jxxghp/MoviePilot#1810]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

最新版1.7.8有问题，设定无法打开，无法搜索资源。 初步判定为前端BUG

**Comment by Z2112** [comment]
我也遇到了。我清空重装了一遍，然后定时备份吧。出问题就回退。

**Comment by huluohu** [comment]
强制刷新

**Comment by longfei12k** [comment]
我绿联云重启就起不来了，docker更新出现问题，还得重新来一遍吗？

**Comment by jxxghp** [comment]
清浏览器缓存
