### ISSUE TITLE
新增用户界面填写完信息后点确定没有反应

### ISSUE THREAD

**Issue by DDCY115** [jxxghp/MoviePilot#1813]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在设置里新增用户填写完信息后点击确定没有反应

**Comment by Jameszhu8** [comment]
我也是，不过我是套件版。

**Comment by jxxghp** [comment]
#1952
