### ISSUE TITLE
[错误报告]: 更新1.7.8后设置里并没有出现两步验证功能

### ISSUE THREAD

**Issue by Laeoo** [jxxghp/MoviePilot#1814]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Windows

### 问题类型

其他问题

### 问题描述

更新1.7.8后设置里并没有出现两步验证功能

**Comment by z3shan33** [comment]
设置中自己开。开启后，你登录的时候输入你的用户账号后就会出现验证码的输入框

**Comment by Laeoo** [comment]
> 设置中自己开。开启后，你登录的时候输入你的用户账号后就会出现验证码的输入框

并不是没有地方输入两步验证码，而是没办法添加二步验证，设置里都没有相关选项
![Uploading IMG_4883.png…]()

**Comment by Laeoo** [comment]
![IMG_4884](https://github.com/jxxghp/MoviePilot/assets/41740567/8aa6bee2-da9c-48c5-882f-dcbe4410a401)

**Comment by jxxghp** [comment]
清浏览器缓存
