### ISSUE TITLE
[错误报告]: bangumi的每日放送列表部分动漫订阅显示未识别到媒体信息，订阅失败

### ISSUE THREAD

**Issue by zwomega** [jxxghp/MoviePilot#1817]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

部分动漫可以正常订阅，但是部分会显示添加订阅失败：未识别到媒体信息，但是用查找功能能在站点里面查到相关下载链接（其中一个剧是：神渴望着游戏）

### 发生问题时系统日志和配置文件

```bash
WARNING	13:31:02,659	
subscribe.py
未识别到媒体信息，标题：神渴望着游戏。，tmdbid：None，doubanid：None
INFO	13:31:02,657	
themoviedb
神渴望着游戏。 未匹配到TMDB媒体信息
INFO	13:31:02,638	
themoviedb
正在识别 神渴望着游戏。 ...
INFO	13:31:02,634	
subscribe.py
开始添加订阅，标题：神渴望着游戏。 ...
```

**Comment by jxxghp** [comment]
需要tmdb有元数据，这个无解
