### ISSUE TITLE
[错误报告]: 馒头下载种子失败

### ISSUE THREAD

**Issue by dongjiqiang** [jxxghp/MoviePilot#1818]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

馒头搜索结果下载时报错，站点管理->浏览, 馒头的列表下载也报错
![1](https://github.com/jxxghp/MoviePilot/assets/17396054/72994515-d8d4-4c1d-9b6c-a318d9df80ec)
![2](https://github.com/jxxghp/MoviePilot/assets/17396054/a3866e79-61a2-4b6a-8959-e2759f2064d3)
![image](https://github.com/jxxghp/MoviePilot/assets/17396054/4677f6d9-a41b-44a4-88da-be58be0b42aa)

**Comment by TyxTang** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/90897955/580b288a-3fd3-42fd-bafe-74de0fdcfef6)
同样的问题，但是日志中获取到的下载链接，复制出去是可以正常下载到种子文件的
MP内无法推送到下载器

**Comment by dwwl886** [comment]
跟我的显示一样 解析失败

**Comment by samyang211** [comment]
+1，同样问题

**Comment by wangbubu928** [comment]
怎么解决啊家人们

**Comment by dongjiqiang** [comment]
> 怎么解决啊家人们
最新版已经没这个问题了
