### ISSUE TITLE
[Feature Request]: 能不能增加EUCSTPT（花梨月下）站点的支持？

### ISSUE THREAD

**Issue by chanriver** [jxxghp/MoviePilot#1819]
### 当前程序版本

1.7.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能不能增加EUCSTPT（花梨月下）站点的支持？

**Comment by jxxghp** [comment]
新开的站吗？吴昊。

**Comment by chanriver** [comment]
不是，是华东理工大学的教育资源站，要号不，我可以发邀请，需要请留邮箱

**Comment by chinazyq123** [comment]
> 新开的站吗？吴昊。

不是，很早就开了，之前只对校内而已

**Comment by chinazyq123** [comment]
另外，应该是ECUSTPT...

**Comment by chinazyq123** [comment]
需要站点方面提供什么支持？看论坛方面好多有提需求

**Comment by jxxghp** [comment]
看了下这个是需要校园网邮箱？我没有，注册不了。

**Comment by chinazyq123** [comment]
> 看了下这个是需要校园网邮箱？我没有，注册不了。
 也许可以考虑在一个您合适的时间开放邀请？或者给pt@cic.cab发封邮件？
