### ISSUE TITLE
[Feature Request]: 刷流插件只删除自己添加的种子

### ISSUE THREAD

**Issue by 522654518** [jxxghp/MoviePilot#1820]
### 当前程序版本

2.1

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

用默认qb刷流，结果保种都被删除了。很多种子不是通过mp添加的，能否刷流插件添加的种子自己单独一个分类，只删除这个分类的种子，不影响其他种子。现在只能再启用一个qb专门刷流

**Comment by InfinityPacer** [comment]
@522654518 刷流只会删除带刷流标签的种子

**Comment by 522654518** [comment]
> @522654518 刷流只会删除带刷流标签的种子
我珍藏多年的毛骗都被删掉了，自从我用了刷流插件之后

**Comment by InfinityPacer** [comment]
@522654518 建议自行再次测试下，正常没有刷流标签的不会处理，可以查看插件的数据列表，如果有你说的已经被删除的种子，说明打了刷流标签才会被插件托管

**Comment by 522654518** [comment]
> @522654518 可以查看插件日志找到被删除种子的删除原因

我看到插件自己记录里边只删除了4个种子，我没有做任何操作，只是配置了刷流软件，我就发现我得毛片都被删掉了，吓得我直接另外起了一个qb单独给mp使用

**Comment by 522654518** [comment]
> @522654518 可以查看插件日志找到被删除种子的删除原因

另外大佬有没有什么其他渠道tg群之类的地方反馈问题，我的qb用的是win的，但是mp是装在虚拟机docker里边，媒体库下载目录应该设置docker挂载的目录还是 qb里边win的下载目录呢

**Comment by InfinityPacer** [comment]
@522654518 TG发布频道，点开有关联群组
