### ISSUE TITLE
[错误报告]: 馒头cookiecloud同步失败

### ISSUE THREAD

**Issue by richard-guan-dev** [jxxghp/MoviePilot#1823]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

馒头更新后，cookie从tp换成了auth， 并且域名改成了，".xp.m-team.cc",且仅有".xp.m-team.cc"， 没有"m-team.cc"。

".xp.m-team.cc"在 app/chain/site.py 是找不到的， 可能是域名最前面的“点”？

indexer = self.siteshelper.get_indexer(domain)
            # 数据库的站点信息
site_info = self.siteoper.get_by_domain(domain)

sitehelper没有源码，请帮忙看下是否是sitehelper的问题。

**Comment by jxxghp** [comment]
馒头现在需要手工维护，改架构了
