### ISSUE TITLE
日志显示模块加载错误，不知道具体影响如何

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#1824]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

前端版本：v1.7.8，后端版本：v1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

容器启动日志报如下错误，具体影响未知。

### 发生问题时系统日志和配置文件

```bash
moviepilot-moviepilot-1  | ERROR:   module.py - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Traceback (most recent call last):
moviepilot-moviepilot-1  |   File "/app/app/helper/module.py", line 31, in load
```

**Comment by jxxghp** [comment]
这个插件的第三方模块安装失败了，除了这个插件之外没有其他影响
