### ISSUE TITLE
[错误报告]: PTLSP网站的主页改了

### ISSUE THREAD

**Issue by iStarCc** [jxxghp/MoviePilot#1826]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

ptlsp这个站点的主页实际是：域名/index.php，不加/index.php的话连通性会失败，提示Cookies失效

### 发生问题时系统日志和配置文件

```bash
【PTLSP】模拟登陆失败：Cookie已失效！
```

**Comment by jxxghp** [comment]
不太好适配，这个站点为何要这么改

**Comment by Katou-Kouseki** [comment]
这个站改版后认证也失效了，有办法适配吗 @jxxghp

**Comment by jxxghp** [comment]
@Katou-Kouseki 没收到通知，不知道改了啥
