### ISSUE TITLE
ERROR:   singleton.py - icc2022认证出错：无法连接站点

### ISSUE THREAD

**Issue by Yuhanlll** [jxxghp/MoviePilot#1827]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在最新的版本里，确认过很多次icc2022站点的id 和 key是正确的，还是在日志里显示认证失败

ERROR:   singleton.py - icc2022认证出错：无法连接站点

### 发生问题时系统日志和配置文件

```bash
不使用代理更新程序
Release 更新模式
当前版本号：v1.7.8
最新版本号：v1.7.8
未发现新版本，跳过更新步骤...
INFO:     Started server process [60]
INFO:     Waiting for application startup.
INFO:    singleton.py - 站点资源版本：1.2.8
INFO:    singleton.py - 认证资源版本：1.2.4
ERROR:   singleton.py - icc2022认证出错：无法连接站点
ERROR:   singleton.py - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
INFO:    resource.py - 开始检测资源包版本...
```

**Comment by lkddi** [comment]
同上问题一样，确认本地能链接icc2022 站点。

**Comment by lkddi** [comment]
The system is Qunhui nas 7.2用nas安装就出现 认证错误。
用套件安装就没有问题。可以认证通过

**Comment by wishday** [comment]
PT时间遇到一样问题，自定义host添加v6 v4记录都不行
同一机器里的浏览器却可以正常打开网站
