### ISSUE TITLE
[错误报告]: 添加下载任务失败

### ISSUE THREAD

**Issue by Hefaang** [jxxghp/MoviePilot#1834]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

已添加transmission下载器为默认下载器，系统检查正常，仪表板的速率监控显示正常，无法通过搜索出的资源添加下载任务，log显示“错误信息：未知错误，userid=None“，正在下载页面显示404，手动添加到tr的下载任务完成后不会自动转移目录。

### 发生问题时系统日志和配置文件

```bash
INFO:     192.168.2.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
INFO:     192.168.2.1:0 - "GET /api/v1/history/transfer?page=1&count=50 HTTP/1.1" 200 OK
INFO:     192.168.2.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
INFO:     192.168.2.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
INFO:     192.168.2.1:0 - "GET /api/v1/search/last HTTP/1.1" 200 OK
ERROR:   download.py - 极恶非道 (2010) 添加下载任务失败：Outrage 2010 BluRay 1080p x265 10bit MNHD-FRDS - https://pt.keepfrds.com/download.php?id=XXXX，未知错误
INFO:    chain - 发送消息：channel=None，title=添加下载任务失败：极恶非道 (2010) , text=站点：朋友
种子名称：Outrage 2010 BluRay 1080p x265 10bit MNHD-FRDS
错误信息：未知错误，userid=None
INFO:    command.py - 处理事件：notice.message - []
INFO:     192.168.2.1:0 - "POST /api/v1/download/ HTTP/1.1" 200 OK
INFO:     192.168.2.1:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
```

**Comment by KAYZZ1** [comment]
我也是这个问题

**Comment by ALANPAN0** [comment]
有解决方案不？

**Comment by zyzhao-kiwi** [comment]
用的qb，但也是添加下载任务失败。

**Comment by lon994** [comment]
有解决方案吗，qb，tr都是这个报错

**Comment by Whichbfj28** [comment]
目测是下载目录 权限不够。。

**Comment by Hefaang** [comment]
> 目测是下载目录 权限不够。。给个0777试试。再慢慢缩小到0755

直接给的0777应用到全部子目录，tr的UID和GID给的0、0都不行

**Comment by Whichbfj28** [comment]
> > 目测是下载目录 权限不够。。给个0777试试。再慢慢缩小到0755
> 
> 直接给的0777应用到全部子目录，tr的UID和GID给的0、0都不行

那么mp的权限呢？

**Comment by yzl321905** [comment]
我今天也碰到这个问题了，你们发生这个问题之前有没有做过啥操作

**Comment by Hefaang** [comment]
> 我今天也碰到这个问题了，你们发生这个问题之前有没有做过啥操作

我是刚从NT转过来的，还没有成功使用过MP

**Comment by yzl321905** [comment]
我已经解决了，删掉所有的映射的配置文件后，重新生成容器就可以解决了

**Comment by ALANPAN0** [comment]
> 我已经解决了，删掉所有的映射的配置文件后，重新生成容器就可以解决了

容器、镜像和配置文件都删掉重装试过不起作用，日志里面也没有任何报错，添加到qB里面状态错误无法下载

**Comment by www121062** [comment]
![Uploading 1712970793054.png…]()
我也是一直报这个错误，不知道怎么解决啊

**Comment by dreamPis** [comment]
同样这个问题 咋解决

**Comment by dreamPis** [comment]
已解决

**Comment by akinlau** [comment]
> 已解决

怎么解决的

**Comment by zyzhao-kiwi** [comment]
docker 下qb 怎么尝试都失败，但是可以用ptpp添加下载任务。最后qb 部署到虚拟机里可以正常用了，勉强算是解决了。不知道docker 下是什么原因导致的。

**Comment by Whichbfj28** [comment]
> docker 下qb 怎么尝试都失败，但是可以用ptpp添加下载任务。最后qb 部署到虚拟机里可以正常用了，勉强算是解决了。不知道docker 下是什么原因导致的。

我猜测是因为docker无法访问192.168.*这种内网IP导致的。这个要嘛MP的docker使用host模式。要嘛把qb跟Mp两个用docker组网到一起

**Comment by akinlau** [comment]
我是用套件部署的，应该跟网络这个没什么关系，升级到最新版也不行，添加下载还是失败

**Comment by ForeverJin** [comment]
我已解决，和上述报错一致，同时系统检查是可以正确连接qb的。
处理：我是使用docker compose的方式安装的，在stack中添加    - 'DOWNLOADER=qbittorrent'
直接编辑app.env应该是一样的。
我开始是用web ui设置下载器的，可能是web ui有bug吧

**Comment by anyishusheng** [comment]
> 已解决

怎么解决得 ？

**Comment by andy4bin** [comment]
> 我已经解决了，删掉所有的映射的配置文件后，重新生成容器就可以解决了

这个方法确实解决了我的问题！关于文件地址相关的配置删掉后就好了

**Comment by LuckyLYY** [comment]
我也遇到找个问题了，是群晖矿神的套件版，最后发现是MoviePilot的权限问题，在环境文件中加入如下代码即可解决：
      # 运行程序用户的uid，默认0
      - 'PUID=0'
      # 运行程序用户的gid，默认0
      - 'PGID=0'
      # 掩码权限，默认000，可以考虑设置为022

**Comment by gdisk** [comment]
设定-连接里面，来回切换下载器设置就好了，可能初始没设置成功。

**Comment by franklioxygen** [comment]
> 我已解决，和上述报错一致，同时系统检查是可以正确连接qb的。 处理：我是使用docker compose的方式安装的，在stack中添加 - 'DOWNLOADER=qbittorrent' 直接编辑app.env应该是一样的。 我开始是用web ui设置下载器的，可能是web ui有bug吧

感谢

**Comment by ZHANGLINFENG993** [comment]
<html>
<body>

11:04:22,832 | message.py | 发送消息：{'message': Notification(channel=None, source=None, mtype=<NotificationType.Manual: '手动处理'>, ctype=None, title='Aliens 1986 1080p BluRay x264 DTS-HD MA 5.1-MTeam 种子下载失败！', text='错误信息：下载种子出错，状态码：307\n站点：PTS', image=None, link=None, userid=None, username=None, date=None, action=1, targets={}, buttons=None, original_message_id=None, original_chat_id=None)}
-- | -- | --
INFO | 11:04:22,828 | chain | NotificationType.Manual 的消息已设置发送给管理员
ERROR | 11:04:22,754 | download.py | 下载种子文件失败：Aliens 1986 1080p BluRay x264 DTS-HD MA 5.1-MTeam - https://www.ptskit.org/download.php?id=5488


</body>
</html>
有谁能帮看看啥情况

**Comment by Sarphura** [comment]
解决了，绿联Nas在docker使用特权模式，只要容器拿到root权限就行
