### ISSUE TITLE
[错误报告]: moviepilot重启后有时会掉配置

### ISSUE THREAD

**Issue by sword0922** [jxxghp/MoviePilot#1837]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

重启后会配置丢失 丢失表现在qb 媒体库 下载目录 机器人等配置丢失

### 发生问题时系统日志和配置文件

```bash
无，重启后仅仅是上述配置丢失
```

**Comment by sword0922** [comment]
tg群里已有多名用户反应此现象。

**Comment by sword0922** [comment]
tg群里已有多名用户反应此现象。

**Comment by jxxghp** [comment]
自己先搞清楚吧，你搜搜issues看有没有别人提过就知道别人有没有问题了：
1、映射了/config目录，持久化配置后，配置就不会丢失。
2、请仔细阅读项目首页说明，环境变化配置优先级大于env.app和页面设置，重启环境变量会重新覆盖生效。
