### ISSUE TITLE
[错误报告]: 同步媒体服务器失败

### ISSUE THREAD

**Issue by JOKER120YL** [jxxghp/MoviePilot#1838]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

已配置好媒体服务器，仪表盘也能看到我的媒体库的内容，但是定时作业中的同步媒体服务器一直失败，显示：'NoneType' object is not iterable - Traceback (most recent call last)。可能也是这个问题，导致我的bangumi插件无法链接到媒体库，日志显示：媒体库中没有找到媒体，跳过同步全部媒体库。
![bug](https://github.com/jxxghp/MoviePilot/assets/50386965/fc5fbfc6-648d-4d89-aa06-ca98f867f499)

### 发生问题时系统日志和配置文件

```bash
2024/4/6 18:42:52  INFO:     192.168.0.107:0 - "GET /api/v1/plugin/?state=market HTTP/1.1" 200 OK
2024/4/6 18:42:52  [32mINFO:[0m    plugin.py - 共获取到 40 个第三方插件
2024/4/6 18:42:52  INFO:     192.168.0.107:0 - "GET /api/v1/plugin/statistic HTTP/1.1" 200 OK
2024/4/6 18:42:52  INFO:     192.168.0.107:0 - "GET /api/v1/plugin/?state=installed HTTP/1.1" 200 OK
2024/4/6 18:42:50  INFO:     192.168.0.107:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
2024/4/6 18:42:47  INFO:     192.168.0.107:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
2024/4/6 18:42:46  INFO:     192.168.0.107:0 - "GET /api/v1/system/runscheduler?jobid=mediaserver_sync HTTP/1.1" 200 OK
2024/4/6 18:42:46  
2024/4/6 18:42:46  TypeError: 'NoneType' object is not iterable
2024/4/6 18:42:46      for item in self.items(mediaserver, library.id):
2024/4/6 18:42:46    File "/app/app/chain/mediaserver.py", line 90, in sync
2024/4/6 18:42:46      job["func"](*args, **kwargs)
2024/4/6 18:42:46    File "/app/app/scheduler.py", line 279, in start
2024/4/6 18:42:46  [31mERROR:[0m   scheduler.py - 定时任务 mediaserver_sync 执行失败：'NoneType' object is not iterable - Traceback (most recent call last):
2024/4/6 18:42:46  [32mINFO:[0m    mediaserver.py - 正在同步  媒体库 动漫 ...
2024/4/6 18:42:46  [32mINFO:[0m    mediaserver.py - 开始同步媒体库  的数据 ...
2024/4/6 18:42:45  INFO:     192.168.0.107:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
2024/4/6 18:42:40  INFO:     192.168.0.107:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
2024/4/6 18:42:40  INFO:     192.168.0.107:0 - "GET /api/v1/user/ HTTP/1.1" 200 OK
2024/4/6 18:42:40  INFO:     192.168.0.107:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
2024/4/6 18:42:37  INFO:     192.168.0.107:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
2024/4/6 18:42:17  INFO:     192.168.0.107:0 - "GET /api/v1/user/current HTTP/1.1" 200 OK
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:17  invalid group reference 2 at position 6
2024/4/6 18:42:17  invalid group reference 1 at position 1
2024/4/6 18:42:17  invalid group reference 1 at position 3
2024/4/6 18:42:03  
2024/4/6 18:42:03  TypeError: 'NoneType' object is not iterable
2024/4/6 18:42:03      for item in self.items(mediaserver, library.id):
2024/4/6 18:42:03    File "/app/app/chain/mediaserver.py", line 90, in sync
2024/4/6 18:42:03      job["func"](*args, **kwargs)
2024/4/6 18:42:03    File "/app/app/scheduler.py", line 279, in start
2024/4/6 18:42:03  [31mERROR:[0m   scheduler.py - 定时任务 mediaserver_sync 执行失败：'NoneType' object is not iterable - Traceback (most recent call last):
2024/4/6 18:42:03  [32mINFO:[0m    mediaserver.py - 正在同步  媒体库 动漫 ...
2024/4/6 18:42:03  [32mINFO:[0m    mediaserver.py - 开始同步媒体库  的数据 ...
2024/4/6 18:41:22  [32mINFO:[0m    bangumi - 订阅页面评分更新完成
2024/4/6 18:41:15  [32mINFO:[0m    bangumi - 搜索条目: 转生为第七王子，随心所欲的魔法学习之路
2024/4/6 18:41:13  [32mINFO:[0m    bangumi - 搜索条目: 忍者神威
2024/4/6 18:41:12  [32mINFO:[0m    bangumi - 搜索条目: 幕府将军
2024/4/6 18:41:11  [32mINFO:[0m    bangumi - 搜索条目: 月光下的异世界之旅 第二季
2024/4/6 18:41:10  [32mINFO:[0m    bangumi - 搜索条目: 死侍3
```

**Comment by jxxghp** [comment]
复现不了这个情况，检查媒体服务器的版本是不是有问题

**Comment by gxterry** [comment]
> 复现不了这个情况，检查媒体服务器的版本是不是有问题

存在同样问题，翻看日历和代码发现是媒体库遍历的位置为空报错。 即代码  File "/app/app/chain/mediaserver.py", line 90
向上发现为 逗号字符串切割 配置字符串，查看本地配置文件app.env发现 出现如下情况
![image](https://github.com/jxxghp/MoviePilot/assets/25121242/cc62d18d-d40e-4732-b05f-0e216ca65c3a)
删除前置逗号，重启应用  同步功能恢复正常

复现：
前端web配置页面  媒体库服务器 取消勾选emby---保存---再次勾选emby--报错
查看配置文件app.evn  出现  [ ,emby]  ,执行定时任务 报错

请大佬确认 是否前端改页面下复选框拼接字符串上存在BUG~

大佬辛苦 MP! YYDS

**Comment by ZACKLZ** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/82872715/c317c4c6-c05a-4fc6-a20f-f2e8c15dd5d1)
【同步媒体服务器 执行失败】
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/app/scheduler.py", line 374, in start
    job["func"](*args, **kwargs)
  File "/app/app/chain/mediaserver.py", line 86, in sync
    for library in self.librarys(mediaserver):
TypeError: 'NoneType' object is not iterable
我也遇到了一样的问题，但检查了下app.env内没一样的情况····

**Comment by ZACKLZ** [comment]
ERROR:   plugin.py - 加载插件 MediaServerMsg 出错：type object 'RequestUtils' has no attribute 'standardize_base_url' - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 176, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/mediaservermsg/__init__.py", line 69, in init_plugin
    self.emby = Emby()
                ^^^^^^
  File "/app/app/modules/emby/emby.py", line 21, in __init__
    self._host = RequestUtils.standardize_base_url(self._host)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RequestUtils' has no attribute 'standardize_base_url'

ERROR:   plugin.py - 加载插件 MediaServerRefresh 出错：type object 'RequestUtils' has no attribute 'standardize_base_url' - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 176, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/mediaserverrefresh/__init__.py", line 44, in init_plugin
    self._emby = Emby()
                 ^^^^^^
  File "/app/app/modules/emby/emby.py", line 21, in __init__
    self._host = RequestUtils.standardize_base_url(self._host)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RequestUtils' has no attribute 'standardize_base_url'

**Comment by ZACKLZ** [comment]
ERROR:   plugin.py - 加载插件 MediaServerMsg 出错：type object 'RequestUtils' has no attribute 'standardize_base_url' - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 176, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/mediaservermsg/__init__.py", line 69, in init_plugin
    self.emby = Emby()
                ^^^^^^
  File "/app/app/modules/emby/emby.py", line 21, in __init__
    self._host = RequestUtils.standardize_base_url(self._host)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RequestUtils' has no attribute 'standardize_base_url'

ERROR:   plugin.py - 加载插件 MediaServerRefresh 出错：type object 'RequestUtils' has no attribute 'standardize_base_url' - Traceback (most recent call last):
  File "/app/app/core/plugin.py", line 176, in start
    plugin_obj.init_plugin(self.get_plugin_config(plugin_id))
  File "/app/app/plugins/mediaserverrefresh/__init__.py", line 44, in init_plugin
    self._emby = Emby()
                 ^^^^^^
  File "/app/app/modules/emby/emby.py", line 21, in __init__
    self._host = RequestUtils.standardize_base_url(self._host)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RequestUtils' has no attribute 'standardize_base_url'

**Comment by InfinityPacer** [comment]
@ZACKLZ 重拉镜像

**Comment by ZACKLZ** [comment]
> @ZACKLZ重拉镜像

还是一样报错T T
![image](https://github.com/jxxghp/MoviePilot/assets/82872715/a404aaea-4533-4e92-ad79-18098581cc4b)

**Comment by InfinityPacer** [comment]
- 无法重现，请确认重拉了镜像而不是重启。
- 尝试在docker的ssh中，输入命令`nano /app/app/utils/http.py`，并提供相关内容

**Comment by ZACKLZ** [comment]
的确是删除了容器和镜像，重新下载部署的，输入你给的命令后，得到以下内容：
from typing import Union, Any, Optional

import requests
import urllib3
from requests import Session, Response
from urllib3.exceptions import InsecureRequestWarning

urllib3.disable_warnings(InsecureRequestWarning)


class RequestUtils:
    _headers: dict = None
    _cookies: Union[str, dict] = None
    _proxies: dict = None
    _timeout: int = 20
    _session: Session = None

    def __init__(self,
                 headers: dict = None,
                 ua: str = None,
                 cookies: Union[str, dict] = None,
                 proxies: dict = None,
                 session: Session = None,
                 timeout: int = None,
                 referer: str = None,
                 content_type: str = None,
                 accept_type: str = None):
        if not content_type:
            content_type = "application/x-www-form-urlencoded; charset=UTF-8"
        if headers:
            self._headers = headers
        else:
            self._headers = {
                "User-Agent": ua,
                "Content-Type": content_type,
                "Accept": accept_type,
                "referer": referer
            }
        if cookies:
            if isinstance(cookies, str):
                self._cookies = self.cookie_parse(cookies)
            else:
                self._cookies = cookies
        if proxies:
            self._proxies = proxies
        if session:
            self._session = session
        if timeout:
            self._timeout = timeout
    def post(self, url: str, data: Any = None, json: dict = None) -> Optional[Response]:
        if json is None:
            json = {}
        try:
            if self._session:
                return self._session.post(url,
                                          data=data,
                                          verify=False,
                                          headers=self._headers,
                                          proxies=self._proxies,
                                          timeout=self._timeout,
                                          json=json,
                                          stream=False)
            else:
                return requests.post(url,
                                     data=data,
                                     verify=False,
                                     headers=self._headers,
                                     proxies=self._proxies,
                                     timeout=self._timeout,
                                     json=json,
                                     stream=False)
        except requests.exceptions.RequestException:
            return None

    def get(self, url: str, params: dict = None) -> Optional[str]:
        try:
            if self._session:
                r = self._session.get(url,
                                      verify=False,
                                      headers=self._headers,
                                      proxies=self._proxies,
                                      timeout=self._timeout,
                                      params=params)
            else:
                r = requests.get(url,
                                 verify=False,
                                 headers=self._headers,
                                 proxies=self._proxies,
                                 timeout=self._timeout,
                                 params=params)
            return str(r.content, 'utf-8')
        except requests.exceptions.RequestException:
            return None

    def get_res(self, url: str,
                params: dict = None,
                data: Any = None,
                json: dict = None,
                allow_redirects: bool = True,
                raise_exception: bool = False
                ) -> Optional[Response]:
        try:
            if self._session:
                return self._session.get(url,
                                         params=params,
                                         data=data,
                                         json=json,
                                         verify=False,
                                         headers=self._headers,
                                         proxies=self._proxies,
                                         cookies=self._cookies,
                                         timeout=self._timeout,
                                         allow_redirects=allow_redirects,
                                         stream=False)
            else:
                return requests.get(url,
                                    params=params,
                                    data=data,
                                    json=json,
                                    verify=False,
                                    headers=self._headers,
                                    proxies=self._proxies,
                                    cookies=self._cookies,
                                    timeout=self._timeout,
                                    allow_redirects=allow_redirects,
                                    stream=False)
        except requests.exceptions.RequestException:
            if raise_exception:
                raise requests.exceptions.RequestException
            return None

    def post_res(self, url: str, data: Any = None, params: dict = None,
                 allow_redirects: bool = True,
                 files: Any = None,
                 json: dict = None,
                 raise_exception: bool = False) -> Optional[Response]:
        try:
            if self._session:
                return self._session.post(url,
                                          data=data,
                                          params=params,
                                          verify=False,
                                          headers=self._headers,
                                          proxies=self._proxies,
                                          cookies=self._cookies,
                                          timeout=self._timeout,
                                          allow_redirects=allow_redirects,
                                          files=files,
                                          json=json,
                                          stream=False)
            else:
                return requests.post(url,
                                     data=data,
                                     params=params,
                                     verify=False,
                                     headers=self._headers,
                                     proxies=self._proxies,
                                     cookies=self._cookies,
                                     timeout=self._timeout,
                                     allow_redirects=allow_redirects,
                                     files=files,
                                     json=json,
                                     stream=False)
        except requests.exceptions.RequestException:
            if raise_exception:
                raise requests.exceptions.RequestException
            return None

    @staticmethod
    def cookie_parse(cookies_str: str, array: bool = False) -> Union[list, dict]:
        """
        解析cookie，转化为字典或者数组
        :param cookies_str: cookie字符串
        :param array: 是否转化为数组
        :return: 字典或者数组
        """
       if not cookies_str:
            return {}
        cookie_dict = {}
        cookies = cookies_str.split(';')
        for cookie in cookies:
            cstr = cookie.split('=')
            if len(cstr) > 1:
                cookie_dict[cstr[0].strip()] = cstr[1].strip()
        if array:
            cookiesList = []
            for cookieName, cookieValue in cookie_dict.items():
                cookies = {'name': cookieName, 'value': cookieValue}
                cookiesList.append(cookies)
            return cookiesList
        return cookie_dict

**Comment by ZACKLZ** [comment]
以前曾经一致无法拉取下载插件，在issues中看到一位网友提供了一个http.py的文件，按照提示映射了/app/app/utils/http.py，才成功下载插件，以下是映射文件中的内容：
from typing import Union, Any, Optional

import requests
import urllib3
from requests import Session, Response
from urllib3.exceptions import InsecureRequestWarning
from app.log import logger

urllib3.disable_warnings(InsecureRequestWarning)


class RequestUtils:
    _headers: dict = None
    _cookies: Union[str, dict] = None
    _proxies: dict = None
    _timeout: int = 20
    _session: Session = None

    def __init__(self,
                 headers: dict = None,
                 ua: str = None,
                 cookies: Union[str, dict] = None,
                 proxies: dict = None,
                 session: Session = None,
                 timeout: int = None,
                 referer: str = None,
                 content_type: str = None,
                 accept_type: str = None):
        if not content_type:
            content_type = "application/x-www-form-urlencoded; charset=UTF-8"
        if headers:
            self._headers = headers
        else:
            self._headers = {
                "User-Agent": ua,
                "Content-Type": content_type,
                "Accept": accept_type,
                "referer": referer
            }
        if cookies:
            if isinstance(cookies, str):
                self._cookies = self.cookie_parse(cookies)
            else:
                self._cookies = cookies
        if proxies:
            self._proxies = proxies
        if session:
            self._session = session
        if timeout:
            self._timeout = timeout

    def post(self, url: str, data: Any = None, json: dict = None) -> Optional[Response]:
        if json is None:
            json = {}
        try:
            url = self.url_parse(url)
            if self._session:
                return self._session.post(url,
                                          data=data,
                                          verify=False,
                                          headers=self._headers,
                                          proxies=self._proxies,
                                          timeout=self._timeout,
                                          json=json,
                                          stream=False)
            else:
                return requests.post(url,
                                     data=data,
                                     verify=False,
                                     headers=self._headers,
                                     proxies=self._proxies,
                                     timeout=self._timeout,
                                     json=json,
                                     stream=False)
        except requests.exceptions.RequestException:
            return None

    def get(self, url: str, params: dict = None) -> Optional[str]:
        try:
            url = self.url_parse(url)
            if self._session:
                r = self._session.get(url,
                                      verify=False,
                                      headers=self._headers,
                                      proxies=self._proxies,
                                      timeout=self._timeout,
                                      params=params)
            else:
                r = requests.get(url,
                                 verify=False,
                                 headers=self._headers,
                                 proxies=self._proxies,
                                 timeout=self._timeout,
                                 params=params)
            return str(r.content, 'utf-8')
        except requests.exceptions.RequestException:
            return None

    def get_res(self, url: str,
                params: dict = None,
                data: Any = None,
                json: dict = None,
                allow_redirects: bool = True,
                raise_exception: bool = False
                ) -> Optional[Response]:
        try:
            url = self.url_parse(url)
            if self._session:
                return self._session.get(url,
                                         params=params,
                                         data=data,
                                         json=json,
                                         verify=False,
                                         headers=self._headers,
                                         proxies=self._proxies,
                                         cookies=self._cookies,
                                         timeout=self._timeout,
                                         allow_redirects=allow_redirects,
                                         stream=False)
            else:
                return requests.get(url,
                                    params=params,
                                    data=data,
                                    json=json,
                                    verify=False,
                                    headers=self._headers,
                                    proxies=self._proxies,
                                    cookies=self._cookies,
                                    timeout=self._timeout,
                                    allow_redirects=allow_redirects,
                                    stream=False)
        except requests.exceptions.RequestException:
            if raise_exception:
                raise requests.exceptions.RequestException
            return None

    def post_res(self, url: str, data: Any = None, params: dict = None,
                 allow_redirects: bool = True,
                 files: Any = None,
                 json: dict = None,
                 raise_exception: bool = False) -> Optional[Response]:
        try:
            url = self.url_parse(url)
            if self._session:
                return self._session.post(url,
                                          data=data,
                                          params=params,
                                          verify=False,
                                          headers=self._headers,
                                          proxies=self._proxies,
                                          cookies=self._cookies,
                                          timeout=self._timeout,
                                          allow_redirects=allow_redirects,
                                          files=files,
                                          json=json,
                                          stream=False)
            else:
                return requests.post(url,
                                     data=data,
                                     params=params,
                                     verify=False,
                                     headers=self._headers,
                                     proxies=self._proxies,
                                     cookies=self._cookies,
                                     timeout=self._timeout,
                                     allow_redirects=allow_redirects,
                                     files=files,
                                     json=json,
                                     stream=False)
        except requests.exceptions.RequestException:
            if raise_exception:
                raise requests.exceptions.RequestException
            return None

    @staticmethod
    def cookie_parse(cookies_str: str, array: bool = False) -> Union[list, dict]:
        """
        解析cookie，转化为字典或者数组
        :param cookies_str: cookie字符串
        :param array: 是否转化为数组
        :return: 字典或者数组
        """
        if not cookies_str:
            return {}
        cookie_dict = {}
        cookies = cookies_str.split(';')
        for cookie in cookies:
            cstr = cookie.split('=')
            if len(cstr) > 1:
                cookie_dict[cstr[0].strip()] = cstr[1].strip()
        if array:
            cookiesList = []
            for cookieName, cookieValue in cookie_dict.items():
                cookies = {'name': cookieName, 'value': cookieValue}
                cookiesList.append(cookies)
            return cookiesList
        return cookie_dict

    @staticmethod
    def url_parse(url: str) -> str:
        """
        如果是github域名则修改为国内加速域名方式
        """
        if url.startswith('https://github.com/'):
            return url.replace('https://github.com/', 'https://mirror.ghproxy.com/https://github.com/')
        if url.startswith('https://raw.githubusercontent.com/'):
            return url.replace('https://raw.githubusercontent.com/', 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/')
        return url

**Comment by ZACKLZ** [comment]
移除该映射后，恢复正常了！感谢大佬指点！

**Comment by ZACKLZ** [comment]
@InfinityPacer 
移除该映射后，恢复正常了！感谢大佬指点！

**Comment by InfinityPacer** [comment]
> @InfinityPacer 
> 
> 移除该映射后，恢复正常了！感谢大佬指点！

请求服务前两个版本重构了，现在也可以配置Github代理，后续不需要单独映射调整了，具体可以看下wiki。
