### ISSUE TITLE
名称识别

### ISSUE THREAD

**Issue by xwxw098** [jxxghp/MoviePilot#1844]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

01.Lupin.III.The.Castle.of.Cagliostro.1979.BluRay.1080p.10bit.DTS-HD.MA.1.0.x265-beAst
关于电影名称有01.这种开头的，无法识别，去掉可以识别，可否改进，因为换了名称无法保种
![QQ截图20240408094027](https://github.com/jxxghp/MoviePilot/assets/113512030/eaffc84e-583c-49e7-a366-a72a99d89908)
![QQ截图20240408094014](https://github.com/jxxghp/MoviePilot/assets/113512030/8f5b745c-4c20-402e-a58e-663f7f003b4f)

**Comment by Z2112** [comment]
希望能增加自定义删除名称识别的地方，
比如【[2024年4月新番] 关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 第01集 内封中字】
会被识别为S03E03。因为有一个“第3期”在01集的前面。
【[2024年1月新番] 月光下的异世界之旅 第二幕 / 月が導く異世界道中 第二幕 第13集 内封中字】
会被识别为S02E02。因为有一个“第二幕”在13集的前面。

**Comment by BlueflameLi** [comment]
这些不都可以通过自定义识别词来实现吗
比如
`01.Lupin.III.The.Castle.of.Cagliostro => Lupin.III.The.Castle.of.Cagliostro`
`关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 第(\d\d)集 => 关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 - S03E\1`

**Comment by BlueflameLi** [comment]
> > 这些不都可以通过自定义识别词来实现吗 比如 `01.Lupin.III.The.Castle.of.Cagliostro => Lupin.III.The.Castle.of.Cagliostro` `关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 第(\d\d)集 => 关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 - S03E\1`
> 
> 不知道是我的问题还是什么，自定义识别词感觉没有生效，《关于我转生变成史莱姆这档事》把“第三期”屏蔽就可以正常识别的，但是我在自定义识别里面填写了“第三期”也还是识别到03集。
![image](https://github.com/jxxghp/MoviePilot/assets/58543957/5264a193-d38e-4e42-a071-07c838f90693)

自定义识别词生效的话，名称识别测试时是会显示的，不知道你是怎么写的，“第三期”和“第3期”是不一样的，你可以随便找个在线的正则测试网站试试。
另外，自定义识别词按理来说应该尽可能的具体，直接屏蔽“第3期”很容易影响其他种子识别的

**Comment by Z2112** [comment]
> > > 这些不都可以通过自定义识别词来实现吗 比如 `01.Lupin.III.The.Castle.of.Cagliostro => Lupin.III.The.Castle.of.Cagliostro` `关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 第(\d\d)集 => 关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 - S03E\1`
> > 
> > 
> > 不知道是我的问题还是什么，自定义识别词感觉没有生效，《关于我转生变成史莱姆这档事》把“第三期”屏蔽就可以正常识别的，但是我在自定义识别里面填写了“第三期”也还是识别到03集。
> 
> ![image](https://private-user-images.githubusercontent.com/58543957/320488179-5264a193-d38e-4e42-a071-07c838f90693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjExOTMsIm5iZiI6MTcxMjY2MDg5MywicGF0aCI6Ii81ODU0Mzk1Ny8zMjA0ODgxNzktNTI2NGExOTMtZDM4ZS00ZTQyLWEwNzEtMDdjODM4ZjkwNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDExMDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMjE1ODNiMjJmNjM2Nzc4MWIyOTE0Zjk5NGJiMzVhYmE2MmM4OGQ2MTk1ZjVlOWI4NmVjMzVmNzQ5ODY0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JjRQ-vN736aZfDoz21RahdncbdwdDT3cUKDctn4eODE)
> 
> 自定义识别词生效的话，名称识别测试时是会显示的，不知道你是怎么写的，“第三期”和“第3期”是不一样的，你可以随便找个在线的正则测试网站试试。 另外，自定义识别词按理来说应该尽可能的具体，直接屏蔽“第3期”很容易影响其他种子识别的

原来“自定义识别词”只是生效在主标题里，副标题不生效导致的屏蔽失败。主标题是
“Tensei shitara Slime Datta Ken S03 1080p Crunchyroll WEB-DL H264 AAC-CHDWEB”
副标题是
“[2024年4月新番] 关于我转生变成史莱姆这档事 第三季 / 転生したらスライムだった件 第3期 第01集 内封中字”
就没有办法屏蔽和识别了。

**Comment by BlueflameLi** [comment]
@Z2112 看了下，目前逻辑确实是不处理副标题的，你可以开个issue提下意见试试
