### ISSUE TITLE
[错误报告]: 蓝光原盘电影整理识别错误重新整理的话带出来得默认目录会少一级

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#1848]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

蓝光原盘电影整理识别错误重新整理的话带出来得默认目录会少一级，比如奥本海默这部电影，首次整理完成后，第二次重新整理打开界面就少了/电影目录
<img width="1055" alt="iShot_2024-04-08_20 19 18" src="https://github.com/jxxghp/MoviePilot/assets/34505611/66e65f40-0061-4ff5-8130-b6292aa8a640">
<img width="1027" alt="iShot_2024-04-08_20 19 33" src="https://github.com/jxxghp/MoviePilot/assets/34505611/df584824-ce55-47c4-94ce-08c2603e37fc">

**Comment by cng10001** [comment]
https://github.com/jxxghp/MoviePilot/issues/1650  haha 我也提过

**Comment by cng10001** [comment]
看起来v1.8.1版本修复了
