### ISSUE TITLE
[错误报告]: 过滤规则 国语配音如果选择反而给国语的排除了。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#185]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.2

### 问题类型

主程序运行问题

### 问题描述

过滤规则 国语配音如果选择反而给国语的排除了。
![动画](https://github.com/jxxghp/MoviePilot/assets/44762565/2cef8c5e-8eb6-4cc9-b4ce-aa41682787b3)

**Comment by loveu5522** [comment]
最新1.0.3还是有这个bug 国语配音 ，设为排除 不能排除国语片源， 设为选中，就搜索不到了

**Comment by jxxghp** [comment]
@loveu5522 给种子示例，不然分析啊

**Comment by loveu5522** [comment]
> @loveu5522 给种子示例，不然分析啊

大佬 钢铁侠3 你试试
