### ISSUE TITLE
[Feature Request]: 历史记录菜单优化

### ISSUE THREAD

**Issue by dh336699** [jxxghp/MoviePilot#1851]
### 当前程序版本

v1.7.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![telegram-cloud-photo-size-1-4947278777524792598-y](https://github.com/jxxghp/MoviePilot/assets/32675044/372692f6-da7e-45d9-bd45-ec674acded1a)
这一建议优化下:
1.如果有个电视剧 有几百集, 想全部展示 批量删除, 页面会非常卡顿, 建议采用requestIdleCallback或者requestAnimationFrame结合fragement进行优化下 
2.其次筛选条件 太简单, 无法根据文件夹进行筛选;场景: 比如我想批量把movie下的所有记录源文件链接删除

**Comment by jxxghp** [comment]
@dh336699 用的是vuetify的datatableserver组件，会改的话pr下吧

**Comment by dh336699** [comment]
ok, 已经提了pr




┍爺╄→們↗
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jxxghp/MoviePilot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jxxghp/MoviePilot] [Feature Request]: 历史记录菜单优化 (Issue #1851)





 
@dh336699 用的是vuetify的datatableserver组件，会改的话pr下吧

**Comment by dh336699** [comment]
@jxxghp 👌🏻 已经提了pr
