### ISSUE TITLE
[错误报告]: 下载和搜索集数显示识别错误

### ISSUE THREAD

**Issue by LHuaQ** [jxxghp/MoviePilot#1853]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载和搜索集数显示识别错误，如图所示
![image](https://github.com/jxxghp/MoviePilot/assets/56777446/b6aaa9ae-60c1-4d1b-b390-c1ed9b9a4130)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-04-09 23:52:28,169 - chain - 发送消息：channel=None，title=追风者 (2024) S01 E13-E264 开始下载, text=用户：豆瓣榜单
【INFO】2024-04-09 23:52:25,135 - download.py - 馒头 - War of Faith S01E13-E16 2024 1080p WEB-DL AAC H.264-JKCT 选中集数：{16, 15}
【INFO】2024-04-09 23:52:25,134 - download.py - 馒头 - WarofFaithS01E13-E1620241080pWEB-DLAACH.264-JKCT 解析文件集数：[16, 13, 14, 15]
【INFO】2024-04-09 23:52:13,753 - download.py - 获取到下载地址：
```

**Comment by jxxghp** [comment]
@LHuaQ 检查你的自定义识别词
