### ISSUE TITLE
[Feature Request]: 连续进行手动刮削的时候希望有可选的记忆功能

### ISSUE THREAD

**Issue by fhyxz001** [jxxghp/MoviePilot#1856]
### 当前程序版本

1.7.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前有些资源的自动刮削效果不好，需要手动刮削，例如
在找到 xxxx 第一话 .mkv 的文件之后，点击整理，手动搜索选择TMDBID之后，再手动选择季，手动选择集，提交之后，mp进入整理状态，之后点击 xxxx 第二话 .mkv ，之前选择的TMDBID 季 集都会清空，然后需要重新选择，在电视剧文件过多的情况下，要手动改、整理  近100多次才能完成。
所以我想这里是不是可以加个记忆的功能，以优化连续进行手动刮削的情况

**Comment by jxxghp** [comment]
@fhyxz001 同一部剧的多集用集数定位一次操作就搞定了呀，不同剧tmdbid等都不一样，记忆没有意义。

**Comment by fhyxz001** [comment]
> @fhyxz001 同一部剧的多集用集数定位一次操作就搞定了呀，不同剧tmdbid等都不一样，记忆没有意义。

卧槽，还真是。。。之前从来没点开这个功能用过   是我没仔细用了。
