### ISSUE TITLE
[错误报告]: 默认过滤规则-排除规则设置后未生效，是否是我设置问题呢？

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/MoviePilot#1857]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

设置的排除规则杜比世界|蓝光原盘|UHD|REMUX|杜比全景声|BLURAY|3D|Dovi|DoVi|Dolby|Vision|DV|3D|HDR|MiniBD|花絮|预告|偏色|设备|枪版|BDMV|ISO|幕后记录|幕后制作|制作幕后|Pad|iPad|Trailer|Trailers|TELESYNC|telesync|抢版|CAM|HDTV

**Comment by jxxghp** [comment]
是搜索吗？是的话下个版本修复。

**Comment by Linyue-GitHub** [comment]
抱歉老大，没说完整，刚才想换行按错了。
是订阅那边的默认排除规则
杜比世界|蓝光原盘|UHD|REMUX|杜比全景声|BLURAY|3D|Dovi|DoVi|Dolby|Vision|DV|3D|HDR|MiniBD|花絮|预告|偏色|设备|枪版|BDMV|ISO|幕后记录|幕后制作|制作幕后|Pad|iPad|Trailer|Trailers|TELESYNC|telesync|抢版|CAM|HDTV

我按这个规则写，还是下到了60fps的资源
![3d8d550939175de6608caeda6146a3ec](https://github.com/jxxghp/MoviePilot/assets/71179298/2ff4eca7-3838-4920-b35b-c80b136fbf8a)

**Comment by jxxghp** [comment]
没发现问题在哪里，检查你这个订阅里是不是设置过了，如果有会优先使用这个订阅的。
