### ISSUE TITLE
[错误报告]: 微信发送剧名，返回获取微信access_token失败

### ISSUE THREAD

**Issue by edwardostara** [jxxghp/MoviePilot#186]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.2

### 问题类型

主程序运行问题

### 问题描述

微信发送剧名，返回获取微信access_token失败

### 发生问题时系统日志和配置文件

```bash
2023-08-19 15:57:58,574 - media.py -【INFO】开始搜索媒体信息：满江红
2023-08-19 15:57:59,261 - media.py -【INFO】满江红 搜索到 2 条相关媒体信息
2023-08-19 15:57:59,261 - message.py -【INFO】搜索到 2 条相关媒体信息
2023-08-19 15:58:19,619 - wechat.py -【ERROR】获取微信access_token失败，请检查参数配置
2023-08-19 15:58:20,127 - wechat.py -【ERROR】获取微信access_token失败，错误信息：Expecting value: line 1 column 1 (char 0)
2023-08-19 15:58:20,128 - wechat.py -【ERROR】获取微信access_token失败，请检查参数配置
```

**Comment by zraxx** [comment]
核对微信回调地址：http://域名:port/api/v1/message/?token=moviepilot

**Comment by edwardostara** [comment]
好的，删掉WECHAT_ADMINS和WECHAT_PROXY变量后，确实好了。感谢

**Comment by lisankai93** [comment]
删掉WECHAT_PROXY变量后提示： wechat.py - 发送请求失败，错误信息：not allow to access from your ip, hint: [***], from ip: ***, more info at https://open.work.weixin.qq.com/devtool/query?e=***

**Comment by RiddleHJX** [comment]
删掉WECHAT_PROXY变量后提示： wechat.py - 发送请求失败，错误信息：not allow to access from your ip, hint: [***], from ip: , more info at https://open.work.weixin.qq.com/devtool/query?e=

我也是相同的问题，有老哥解决了没

**Comment by zousoooo** [comment]
> 删掉WECHAT_PROXY变量后提示： wechat.py - 发送请求失败，错误信息：not allow to access from your ip, hint: [***], from ip: , more info at https://open.work.weixin.qq.com/devtool/query?e=
> 
> 我也是相同的问题，有老哥解决了没

https://github.com/jxxghp/MoviePilot/issues/2315
我也是相同的问题，现在解决了，你检查是否配置了 /var/run/docker.sock
