### ISSUE TITLE
馒头无法IMDB搜索

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#1860]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

https://github.com/jxxghp/MoviePilot/assets/142991330/3e9aa23b-7118-48fe-8665-9fa1acaeaef8

![1712766392462](https://github.com/jxxghp/MoviePilot/assets/142991330/77098362-2b53-4a95-8343-911cc812725b)
馒头是有资源的

**Comment by jxxghp** [comment]
mt有提供使用IMDBID搜索的功能？ 新架构没看到。而且这个是要在发种时关联imdbid的，mt一直也没有吧？
