### ISSUE TITLE
[错误报告]: 订阅-默认过滤规则-排除规则  不匹配的种子名称系统判断为匹配

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/MoviePilot#1863]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

日志已贴 老大麻烦看下

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-04-11 10:46:31,346 - torrent.py - Blossoms in Adversity 2024 S01E19-E20 2160p WEB-DL HEVC AAC-QHstudIo 匹配排除规则 UHD|60fps|60FPS|Dovi|DoVi|Dolby|Vision|DV|3D|HDR|MiniBD|杜比视界|花絮|预告|偏色|设备|枪版|BDMV|ISO|幕后记录|幕后制作|制作幕后|Pad|iPad|Trailer|Trailers|TELESYNC|telesync|抢版|CAM|HDTV
```

**Comment by jxxghp** [comment]
dv命中了
