### ISSUE TITLE
[错误报告]: 剧集搜索出来的集数把与分辨率或编码上的数字一起识别上去

### ISSUE THREAD

**Issue by cb1994927** [jxxghp/MoviePilot#1865]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.7.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![52e6ccb1d84024e9489ff0b1849e39b0](https://github.com/jxxghp/MoviePilot/assets/166683340/fff7ee55-56fe-405c-b64e-f0c0da51e6df)

**Comment by jxxghp** [comment]
@cb1994927 自定义识别词被乱改了

**Comment by cb1994927** [comment]
> @cb1994927 自定义识别词被乱改了

还真是，感谢作者。开了云共享识别
