### ISSUE TITLE
QBitTorrent下载出错

### ISSUE THREAD

**Issue by Jerry-Geng** [jxxghp/MoviePilot#1866]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

QBitTorrent连接正常，刷流也正常，但是通过搜索下载资源会报未知错误

### 发生问题时系统日志和配置文件

```bash
ERROR	15:00:27,918	
download.py
	沙丘2 (2024) 添加下载任务失败：Dune Part Two 2024 1080p WEB-DL H.264 AAC-HDH - https://pt.btschool.club/download.php?id=139479，未知错误
```

**Comment by cddjr** [comment]
经过测试，学校站点同一个种子暂时没有复现，可以正常搜索并推送到QB下载。
