### ISSUE TITLE
[Feature Request]: rclone能否设置多线程，现在只能一次只能复制一个文件

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot#1867]
### 当前程序版本

v1.8.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

rclone能否设置多线程，现在只能一次只能复制一个文件

**Comment by jxxghp** [comment]
@shixiaolong777 可通过环境变量设置，具体查看rclone官方文档。
