### ISSUE TITLE
[Feature Request]: 希望想NT一样添加自定义下载文件到指定文件夹功能

### ISSUE THREAD

**Issue by Zhangqian0375** [jxxghp/MoviePilot#1872]
### 当前程序版本

1.8.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

因为想做一些专辑收藏，如果增加自定义下载文件夹功能后，种子保存的位置更自由，也方便刮削，谢谢

### 参考资料

![微信截图_20240411220446](https://github.com/jxxghp/MoviePilot/assets/54308056/227c5249-86e4-4639-8407-24b308c9fe40)
leisi类似NT的这样功能 谢谢

**Comment by jxxghp** [comment]
不会支持的，有计划的话早做了。
