### ISSUE TITLE
[Feature Request]: 同一电影不同版本可否放在不同文件夹？

### ISSUE THREAD

**Issue by AutunnoLL** [jxxghp/MoviePilot#1874]
### 当前程序版本

1.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前同一电影的不同版本都被硬链到了同一个文件夹下（电影名 日期），emby在删除其中一个版本时会将整个文件夹一起删除，导致另外的版本也被删掉。能否在硬链接时将不同版本硬链接到不同文件夹，文件夹命名可遵循电影的命名规则。
感谢大佬的奉献！

**Comment by jxxghp** [comment]
@AutunnoLL 命名规则是你自己设置的，包括目录都可以

**Comment by AutunnoLL** [comment]
> @AutunnoLL 命名规则是你自己设置的，包括目录都可以

感谢大佬，已用命名规则解决
