### ISSUE TITLE
[错误报告]: 日志ERROR:插件module不存在

### ISSUE THREAD

**Issue by MDCY9008** [jxxghp/MoviePilot#1889]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/54255527/b1e0d4b4-0b1b-45fc-bfed-2fb09d7d3502)

**Comment by BlueflameLi** [comment]
#1801 和这个一样，就是这两个插件需要额外的依赖，你没装这两个插件就会有这个报错，应该没什么影响

**Comment by jiezaizone** [comment]
我也遇到这个问题，同时更新后，plex的媒体同步、媒体webhook通知都异常了，不知道是否有关联

**Comment by jxxghp** [comment]
插件的依赖问题，无法自动安装的情况下要么手动安装。
只影响这个插件用不了。
