### ISSUE TITLE
要求进行身份认证，无法登录

### ISSUE THREAD

**Issue by jklm23** [jxxghp/MoviePilot#1890]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

群晖安装套件版后，要求进行身份认证，使用超级密码无效
<img width="448" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/30951259/12985a0d-4ecb-4c7f-b65e-875dc5f1c9c3">

**Comment by cddjr** [comment]
你的反代问题吧？ 看着像又加了一层验证

**Comment by jklm23** [comment]
> 你的反代问题吧？ 看着像又加了一层验证

直接绕过IP访问还是这个问题，不知道是不是浏览器缓存还是其他原因

**Comment by cddjr** [comment]
试试直接访问内网ip

**Comment by jklm23** [comment]
> 试试直接访问内网ip

解决了，有一个docker的端口和它有冲突，停止容器以后正常了
