### ISSUE TITLE
[Feature Request]: 希望增加各插件联动，即当前任务执行完成后下一步关联任务

### ISSUE THREAD

**Issue by fishensl** [jxxghp/MoviePilot#1891]
### 当前程序版本

1.8.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望增加各插件联动，在整理完成后增加选项下一步执行的任务（比如整理完成后执行strm生成插件）。

strm生成插件执行完成后下一步任务也可以选择入库，这样就可以根据不同用户使用环境定制出不同的工作流了。

目前版本下，很多插件缺乏相关联动导致只能靠计划任务解决，但是这样时效性是一个问题，资源占用也是问题。

例如本人工作流如下：
MP 下载完成整理到115》完成后下一任务是生成strm》完成后刷新媒体库入库，

在现有版本要完成这样的工作流靠strm插件计划任务有时效性问题，还有就是整理完成已经入库了，

在strm生成之前了，导致只能再手动刷新媒体库才行。

**Comment by jxxghp** [comment]
MP支持事件机制，要插件实现，处理完后发送下一个事件，具体需求跟对应插件提。

**Comment by fishensl** [comment]
> MP支持事件机制，要插件实现，处理完后发送下一个事件，具体需求跟对应插件提。

这个和插件作者提过，改了3 5个版本还是会出现这样那也的bug后来回退了，所以我才想在主程序提可能更简单。

因为本身插件不做任何修改，手动执行插件是没有任何bug的，所以想着在MP主程序提供定制联动执行，这样能减少插件bug导致的问题，毕竟和手动直接没太大区别。
