### ISSUE TITLE
[站点搜索适配bug]: 部分站点在搜索时的链接有错误，导致无法正确搜索想要的内容，而是返回站点首页种子

### ISSUE THREAD

**Issue by ACE-830** [jxxghp/MoviePilot#1893]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在使用搜索功能时，部分站点无法返回正确的结果，查看日志发现是该站点用的搜索链接有错误，因此不管搜索什么都无法正确返回搜索的种子列表，只能返回站点首页的种子列表。
根据我有的站点，目前发现两个站点有问题，分别是filelist和hdcity（城市）。

- filelist站点：
当前搜索日志：
`spider.py - 开始请求：https://filelist.io/browse.php?search_mode=0&search_area=0&page=0&notnewword=1&search_field=要搜索的名称&c=M`
应该修改为 `https://filelist.io/browse.php?search_mode=0&search_area=0&page=0&notnewword=1&search=要搜索的名称&c=M`，即将`search_field`替换为`search`即可。

- hdcity站点（城市）：
当前搜索日志：
`spider.py - 开始请求：https://hdcity.city/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=要搜索的名称&cat402=1&cat403=1&cat404=1&cat405=1`
应该修改为 `https://hdcity.city/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&iwannaseethis=要搜索的名称&cat402=1&cat403=1&cat404=1&cat405=1`，即将`search`替换为`iwannaseethis`即可。

**Comment by jxxghp** [comment]
感谢提醒，我调一下
