### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by yokunnyang** [jxxghp/MoviePilot#1894]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

你好，作者，首先感谢你能听取我的反馈。在新版本更新目录过滤之后，我马上使用了下，发现使用目录过滤，存在问题如下：
我感觉这次更新的目录过滤其实就是筛选功能。但是大家普遍刮削的历史记录会有成千上万条。这个过滤只能过滤点开历史记录的第一页，翻页就失效了，即使下面改成了显示all（条目少选择ALL只卡一会，随着条目多，甚至会网页卡死），然后再进行过滤目录，也会不起作用。
我之前反馈所说的就是想要搜索栏添加目录，让搜索可以正常搜索到全部历史记录的目录（因为我一次性下的东西多，集数多，自动刮削动漫条目会特别多，目录又全是长长的英文，刮削错误还会很难找），这样就方便可以复制长串的目录地址来搜索出所有的历史记录。手动刮削也就不用那么难找了，还请能添加此功能，谢谢

### 发生问题时系统日志和配置文件

```bash
翻页历史记录使用目录过滤无效，目录过滤无法过滤所有的历史记录，建议改为搜索目录（全部历史记录），而非单页
```

**Comment by jxxghp** [comment]
重新改了，-1版本打包中。
