### ISSUE TITLE
[错误报告]: 文件管理页面搜索关键字出错

### ISSUE THREAD

**Issue by madswaord** [jxxghp/MoviePilot#1898]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

之前在文件管理页面用ctrl+f可以搜索全页的文件名 现在这个版本只能搜索当前显示的内容，如果该剧集没有下滑在当前视窗则无法搜索，我不知道这样子表达是否能理解，我贴了两张图，
![截屏2024-04-15 21 14 37](https://github.com/jxxghp/MoviePilot/assets/86275875/8c5cb8bb-aefe-4b19-be9b-da0d7247cdb0)第一张是刚进TVSHOWS路径的时候搜索毛骗提示结果为0，
![截屏2024-04-15 21 15 14](https://github.com/jxxghp/MoviePilot/assets/86275875/a0f7f81c-28e8-4141-9c13-1ce547dfd41b)当我把页面下滑至能显示该片的位置，再次搜索关键词就能搜索到了。我记得上次该文件管理页面之前是直接进入该路径之后直接搜索关键词就能定位出该文件夹的

**Comment by jxxghp** [comment]
为了避免卡死的情况，元素的演染是递进式的，刚进页面等一会试试

**Comment by madswaord** [comment]
> 为了避免卡死的情况，元素的演染是递进式的，刚进页面等一会试试

我试了几次 如果不向下拉动的话是搜不到显示界面外的文字的，拉到哪 搜索范围才能覆盖到哪。你那边不能复现这个状况吗

**Comment by cng10001** [comment]
其实能不能把内置的搜索也改成不区分英文大小写的模糊搜索就行了，就不用Ctrl+F了

**Comment by jxxghp** [comment]
> > 为了避免卡死的情况，元素的演染是递进式的，刚进页面等一会试试
> 
> 我试了几次 如果不向下拉动的话是搜不到显示界面外的文字的，拉到哪 搜索范围才能覆盖到哪。你那边不能复现这个状况吗

无法复现，可以全局过滤
