### ISSUE TITLE
[Feature Request]: 对标题中BD、UHD的识别

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#1899]
### 当前程序版本

1.8.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

举个例子标题 _Moon.2009.COMPLETE.UHD.BLURAY-TERMiNAL_ 
如果标题中没有具体的像1080p或2160p这种具体数字，那么有 _BD识别成BD.1080p_ 
 _UHD别成UHD.2160p_ 是否合理

**Comment by shanyan-wcx** [comment]
BD、UHD和分辨率不是对应关系吧，1080p UHD和2160p BD都是存在的。

**Comment by cng10001** [comment]
> BD、UHD和分辨率不是对应关系吧，1080p UHD和2160p BD都是存在的。

是的 
所以说如果标题中720p 1080p 2160p等数字缺失的时候默认成bd就是1080p uhd就是2160p如何
