### ISSUE TITLE
[Feature Request]: 多域名适配pt站点

### ISSUE THREAD

**Issue by Waynenet** [jxxghp/MoviePilot#190]
### 当前程序版本

v1.0.3

### 功能改进

某些站点有多个域名站点。馒头现主站点为https://xp.m-team.io/，MoviePilot还尚未匹配。作为江苏用户，只能主站点访问，其它https://xp.m-team.cc/等域名只能翻墙访问。希望能多域名适配。

**Comment by dlovew** [comment]
打开ipv6试试，如果有的话。江苏联通好像没有，移动电信都有
