### ISSUE TITLE
[错误报告]: 历史记录整理的几个问题

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#1900]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

大佬每次都是史诗级更更新，这次对历史记录功能又增加了功能，但是随之也带来了一些问题，我看到有人也提了相关。
我也发现4个问题：
**①电影类型的整理都变成了xxxs01**
![电影变s01](https://github.com/jxxghp/MoviePilot/assets/115156545/de4947c3-5b89-4ee0-929c-ba734763c3d0)
**②默认情况下，历史记录搜索只能显示10条**
把50改成100才能全部显示
![只显示10条](https://github.com/jxxghp/MoviePilot/assets/115156545/bf583498-c2b6-4dff-9dce-7b82e698dcc9)
**③我用original_name的情况下，多了个文件扩展名。**
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/8c952ffa-edb6-44f3-8215-b59f45fba5e0)
**④带文件扩展名的资源重新整理默认路径会到资源文件夹那一层，直接整理的话会导致又创建一层文件夹**
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/e144c44e-b4bb-4426-b29c-c12781b30fe1)

### 发生问题时系统日志和配置文件

```bash
我的重命名规则
{{title}} {{original_title}} ({{year}})/{% if part %}{{part}}-{% endif %}{{videoFormat}}{% if releaseGroup %}.{{releaseGroup}}{% endif %}{% if fileExt %}{{fileExt}}{% endif %}/{{original_name}}
```

**Comment by jxxghp** [comment]
历史记录显示的问题，original_name多后缀的问题，-1版本重新改了。
正在打包。。。

**Comment by cng10001** [comment]
> 历史记录显示的问题，original_name多后缀的问题，-1版本重新改了。 正在打包。。。

6舔舔大佬，剩下最后一个问题，以前bdmv格式蓝光历史记录重新整理默认路径会有点问题，现在变成带文件扩展名的资源历史记录点重新整理，默认路径会有点问题
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/8d6a390e-2b5d-4289-ae7a-d90ac1f4f94d)
