### ISSUE TITLE
[Feature Request]: 能不能支持一下ntfy作为消息提醒

### ISSUE THREAD

**Issue by luckjiawei** [jxxghp/MoviePilot#1903]
### 当前程序版本

v1.8.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

增加Ntfy作为消息提醒
https://ntfy.sh/

### 参考资料

https://ntfy.sh/

**Comment by EkkoG** [comment]
https://github.com/jxxghp/MoviePilot-Plugins/blob/main/plugins/ntfymsg/__init__.py 已经有了
