### ISSUE TITLE
[Feature Request]: RSS订阅的订阅模式在添加订阅时，可不可以指定站点，传递包含或者排除关键字

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#191]
### 当前程序版本

1.0.3

### 功能改进

RSS订阅的订阅模式在添加订阅时，可不可以指定站点，传递包含或者排除关键字，类似nt那样

**Comment by dlovew** [comment]
[embyserver-63828106740.txt](https://github.com/jxxghp/MoviePilot/files/12387379/embyserver-63828106740.txt)

**Comment by cng10001** [comment]
现在这个功能是不是已经有了
![Uploading 360截图20230902003737812.jpg…]()

**Comment by dlovew** [comment]
> 现在这个功能是不是已经有了 ![360截图20230902003737812](https://user-images.githubusercontent.com/115156545/265078761-a9dc164a-0f73-41c9-a035-01a26bd91863.jpg)

我说的是rss订阅插件，这个自定义订阅可以不指定标题么？是直接下载还是添加订阅到电影或者电视剧订阅？

**Comment by cng10001** [comment]
- - 。nt我也没用明白自定义订阅里的“下载”和“订阅”是什么区别。

**Comment by dlovew** [comment]
怕大佬忘了，顶一顶，希望早日提上日程

**Comment by dlovew** [comment]
佬，这个功能还在日常之上么
