### ISSUE TITLE
[错误报告]: 订阅-默认过滤规则 正则表达式匹配种子名称有问题

### ISSUE THREAD

**Issue by Linyue-GitHub** [jxxghp/MoviePilot#1910]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用的默认包含规则为
\b(中字|中文|简繁|双语|中英|简+繁|繁体|繁英|简中|繁中|国英|简英|国粤|国配|国语|粤英|特效|简)\b
明明是匹配的种子名称，系统判断为不匹配。
错误日志已贴
![1713276934317](https://github.com/jxxghp/MoviePilot/assets/71179298/bed3e411-79a4-40fc-a6e2-9c047977e09c)

### 发生问题时系统日志和配置文件
```bash
【INFO】2024-04-16 21:57:14,528 - torrent.py - Shooting Stars 2024 S01 E05-E06 1080p WEB-DL H264 AAC-PTerWEB[群星闪耀时/Shooting Stars/When the Stars Shine 第5-6集 | 导演: 万里扬 主演: 李现 任敏 周游  | [国语中字][内封多国字幕]] 不匹配包含规则 \b(中字|中文|简繁|双语|中英|简+繁|繁体|繁英|简中|繁中|国英|简英|国粤|国配|国语|粤英|特效|简)\b
【INFO】2024-04-16 21:57:08,416 - torrent.py - Lovely Runner S01 2024 1080p IQ WEB-DL AAC H264-HDSWEB[韩剧: 背着善在跑吧 / 背着善宰跑 / 선재 업고 튀어 第02-03集 | 主演: 边佑锡 / 金惠奫 / 宋建熙 / 李承協 [内封简繁中字]] 不匹配包含规则 \b(中字|中文|简繁|双语|中英|简+繁|繁体|繁英|简中|繁中|国英|简英|国粤|国配|国语|粤英|特效|简)\b
【INFO】2024-04-16 21:57:03,642 - torrent.py - Shogun S01E09 2160p Disney WEB-DL DDP 5 1 H 265-CHDWEB [幕府将军 第一季 第09集 /Shōgun | 类型:剧情/历史/战争/冒险 | 4K SDR | 主演:真田广之/柯斯莫贾维斯/泽井杏奈/浅野忠信/二阶堂富美] 内封中文字幕 8.13 GB 不匹配包含规则 \b(中字|中文|简繁|双语|中英|简+繁|繁体|繁英|简中|繁中|国英|简英|国粤|国配|国语|粤英|特效|简)\b
```

**Comment by cddjr** [comment]
少用”人工弱智“，\b不支持中文单词的分割。
把两端的`\b`替换为`.{1}`，变成`.{1}(中字|中文|..略..|特效).{1}`
或者直接去掉`\b()\b`，变成`中字|中文|..略..|特效`
