### ISSUE TITLE
[Feature Request]: 通过程序内的搜索，下载的电影，入库时识别成错误的名字。

### ISSUE THREAD

**Issue by tony3080** [jxxghp/MoviePilot#1911]
### 当前程序版本

v1.8.1-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否在搜索并下载时，记录搜索时tmdb的id，入库时，直接使用这个id，不会导致识别错误。

**Comment by jxxghp** [comment]
现在就有这个逻辑，有不对的情况你要举具体的例子和日志
