### ISSUE TITLE
[错误报告]: 订阅剧集时，发生重复订阅问题（先自动整理成了英文剧集目录，然后重新整理了一份中文的，下载了两次）

### ISSUE THREAD

**Issue by lzcer** [jxxghp/MoviePilot#1912]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

经历：
1、上周订阅了《幕府将军》，然后正常执行下载的，已经下载了7集 目录名称为：Shōgun
2、昨天突然重新从第一集开始下载，先下载了第8集，然后下载了12，随后补全了1-8 目录名为：幕府将军
查看日志：
日志截图贴到下方
![a7c49ef704d3254d8ce5583aa65b172](https://github.com/jxxghp/MoviePilot/assets/49141481/1dfaf183-542e-4855-99e8-97f796b947c1)
![14afec483b5bb0aaf018f60bd8dfe42](https://github.com/jxxghp/MoviePilot/assets/49141481/69768868-5d67-48a1-8b45-ed3178495f62)
### 发生问题时系统日志和配置文件

```bash

```

**Comment by jxxghp** [comment]
TMDB中的名声变化导致的，可以关闭 新增剧集随TMDB名称变化 SCRAP_FOLLOW_TMDB 来规避（但会一直使用第一次的名字）
