### ISSUE TITLE
[错误报告]: 搜索结果中更多资源左右箭头无法点击

### ISSUE THREAD

**Issue by gravitation-ch** [jxxghp/MoviePilot#1918]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

资源搜索结果中，由之前的列表改成横向条目折叠以后，左右箭头无法正常点击，点击就是直接提示下载。

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/e1ee3ef2db9f10f45fb6a9f536ee0d3670e58bb1
