### ISSUE TITLE
Monika站点刷流，发布时间和促销的识别问题。

### ISSUE THREAD

**Issue by torashen** [jxxghp/MoviePilot#1922]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

莫妮卡无法正确识别促销状态以及种子发布时间
![1713493043981](https://github.com/jxxghp/MoviePilot/assets/153890345/9feea1dd-7d2b-4055-acb3-affaabf4a694)

**Comment by whogh** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/26213608/56201b89-6961-43cb-ab4b-9e04f95db3de)
发布时间这里减反了吧

**Comment by whogh** [comment]
2 changes: 1 addition & 1 deletion2  
[app/utils/string.py](https://github.com/jxxghp/MoviePilot/commit/316f61bf69060b562a403e913fcee73fd7e7fc98#diff-b1df0d2bacb0252ac5b1b379ab69a5d717cfa6f1d3661fcd990c1296df73e112)
@@ -743,7 +743,7 @@ def diff_time_str(time_str: str):
        try:
            time_obj = datetime.datetime.strptime(time_str, '%Y-%m-%d %H:%M:%S')
        except ValueError:
            return ''
            return time_str
        now = datetime.datetime.now()
        **diff = time_obj - now**
        diff_seconds = diff.seconds

**Comment by jxxghp** [comment]
@whogh monika就不是标准的时间，不会走到这里啊，网站显示是啥就是啥，不是吗？

**Comment by whogh** [comment]
但是其他站也出问题吧， 应该 发布时间间隔=当前时间 -  网站上显示的发布时间
因为之前一直是负数，日志显示 brushflow - 种子没有通过刷流条件校验，原因：发布时间 0 分钟前，不在指定范围内
diff =  now - time_obj

**Comment by jxxghp** [comment]
@whogh 举个例子？其它站抓取的是免费到期时间啊
