### ISSUE TITLE
[错误报告]: qingwa网站域名更新，重启后无法认证

### ISSUE THREAD

**Issue by Nelson-Wcg** [jxxghp/MoviePilot#1926]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

ERROR:   singleton.py - qingwa认证出错：无法连接站点
ERROR:   singleton.py - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！

**Comment by Nelson-Wcg** [comment]
青蛙的问题 被🧱了

**Comment by zzzop** [comment]
现在还是不可以吗
