### ISSUE TITLE
[错误报告]: original_name,刮削115的库时会多加一个.mp4，.mkv这些的名字，导致有两个mp4或者mkv

### ISSUE THREAD

**Issue by zengjiu** [jxxghp/MoviePilot#1930]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

**刮削改名的最后是保留原视频文件名{original_name}，刮削115的库时会多加一个.mp4，.mkv这些的名字，导致我有两个mp4或者mkv,115是通过docker cd2挂载的**
![Cache_-6772230a9ad4fe23](https://github.com/jxxghp/MoviePilot/assets/73211620/042e6dbf-d80b-48da-b75b-bbd3e4530371)

**Comment by cddjr** [comment]
你的配置问题

**Comment by zengjiu** [comment]
{{title}}{% if year %} ({{year}}) {% endif %}{tmdb-{{tmdbid}}} [tmdbid={{tmdbid}}]/Season {{season}}/{{original_name}}配置是这个没问题本地的文件命名正常，就挂载115的里的文件会多后缀，能否增加一下不包含后缀的original_name参数

**Comment by wei9527633** [comment]
同样的问题，使用original_name参数就会使115里的文件多一个后缀，希望能解决。
