### ISSUE TITLE
下载器都是连接错误

### ISSUE THREAD

**Issue by lili890527** [jxxghp/MoviePilot#1933]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.2.20:9091/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f31e8a24d10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))

两个下载器都是这样的问题。用nastool连接是正常的

### 发生问题时系统日志和配置文件

```bash
transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.2.20:9091/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f31e8a24d10>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
```

**Comment by fineconey** [comment]
can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url:   :9091/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at >: Failed to resolve 'http' ([Errno -5] No address associated with hostname)"))
