### ISSUE TITLE
[Feature Request]: 希望电视剧重命名格式中的`season`的数字改为两位数的格式

### ISSUE THREAD

**Issue by s-leeq** [jxxghp/MoviePilot#1934]
### 当前程序版本

v1.8.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

如题，现在我的电视剧重命名格式为：`{{en_title}}/S{{season}}/...`，重命名完输出的是`xxx/S1`的格式，希望将其改为与`season_episode`中相同的`Sxx`格式，谢谢！

**Comment by jxxghp** [comment]
jinja2语法，自己在格式里配。
