### ISSUE TITLE
bash: line 1: /app/start.sh: No such file or directory

### ISSUE THREAD

**Issue by xiaosagemisery** [jxxghp/MoviePilot#194]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.3

### 问题类型

主程序运行问题

### 问题描述

使用portainer拉取最新镜像并启动后，无法进入WebUI,在日志中显示bash: line 1: /app/start.sh: No such file or directory
进入控制台，在app目录下确实没有发现start.sh文件。
![image](https://github.com/jxxghp/MoviePilot/assets/57939882/82f3cd7f-6b23-4604-bfa6-c77fb2031c18)
![image](https://github.com/jxxghp/MoviePilot/assets/57939882/4cbdf262-8a50-4231-b641-44c5c4e63e6e)

### 发生问题时系统日志和配置文件

```bash
日志文件已经在上面了。
拉取最新镜像时配置文件没改过，应该不是配置文件的问题。
```

**Comment by zraxx** [comment]
映射目录 /config，试试

**Comment by xiaosagemisery** [comment]
> 

![image](https://github.com/jxxghp/MoviePilot/assets/57939882/5be31a15-fd72-4960-b3b4-2defa3a81058)
我把NAS里的一个目录映射到了/config

**Comment by zraxx** [comment]
> > 
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/57939882/5be31a15-fd72-4960-b3b4-2defa3a81058)
> 我把NAS里的一个目录映射到了/config

有可能镜像提取不完整，建议重新安装一次

**Comment by mjsoftking** [comment]
![1692516990325](https://github.com/jxxghp/MoviePilot/assets/23021469/8e5a23be-642c-465f-a75d-3300080656c3)
好像这个位置变了，我是重新建了一遍好的

**Comment by xiaosagemisery** [comment]
> ![1692516990325](https://user-images.githubusercontent.com/23021469/261838523-8e5a23be-642c-465f-a75d-3300080656c3.png) 好像这个位置变了，我是重新建了一遍好的

![image](https://github.com/jxxghp/MoviePilot/assets/57939882/d8a70bb7-9338-46ac-9bca-9b40479277d1)
谢谢，在portainer里把entrypoint改成默认，进去就变成了您发的这个，就可以启动了
