### ISSUE TITLE
[Feature Request]: 备份功能优化

### ISSUE THREAD

**Issue by sword0922** [jxxghp/MoviePilot#1944]
### 当前程序版本

1.8

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

增加webdav备份，并且可以webdav拉取还原配置。就和ptpp备份逻辑一样。望作者大大开发一哈，真的很实用的😘

**Comment by InfinityPacer** [comment]
> 可以有

存在第三包依赖，已加到个人仓库

**Comment by jxxghp** [comment]
@sword0922 这个项目里的人跟群管理是两波人

**Comment by sword0922** [comment]
从nastool一直到moviepilot，群里人有问问题我也会帮忙解决，但是就刚刚我发的贴吧某人讨论该项目我转发被封并且导致我的moviepilot ip也被封禁，某些群管理莫名其妙的做法，我也不想多说。我也不想在进群，我只求把我的ip解封。对于某个群管理的做法，作为一个老pt和作者项目支持者，实在是太寒心了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: 备份功能优化 (Issue #1944)




 
@sword0922 这个项目里的人跟群管理是两波人

**Comment by jxxghp** [comment]
@sword0922 ip被封是啥意思？

**Comment by sword0922** [comment]
具体就是，我的tg通知和tg号是同一个，群聊被踢出后，我的moviepilot就用不了了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 晚上6:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: 备份功能优化 (Issue #1944)




 
@sword0922 ip被封是啥意思？

**Comment by jxxghp** [comment]
@sword0922 没有这种功能啊，MP开源，没有也不可能有这样的代码

**Comment by sword0922** [comment]
重启后容器都进不去了😓



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 晚上6:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: 备份功能优化 (Issue #1944)




 
@sword0922 没有这种功能啊，MP开源，没有也不可能有这样的代码

**Comment by jxxghp** [comment]
@sword0922 有一说一，群里的事没有依据的情况下别跟项目扯上关系（没有关联关系）。被踢的事如何确实是误解我找人加回来

**Comment by sword0922** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 晚上6:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: 备份功能优化 (Issue #1944)




 
@sword0922 没有这种功能啊，MP开源，没有也不可能有这样的代码

**Comment by jxxghp** [comment]
@sword0922 提供下tg号
