### ISSUE TITLE
[错误报告]: 仪表板Jellyfin跳转播放链接时页面空白

### ISSUE THREAD

**Issue by zbqsfs** [jxxghp/MoviePilot#1945]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

关联问题 #1876 ，首先吐槽一下目前jellyfin latest版本的跳转链接实际上还是#!/，只是nightly版本变成了#/，另外在 https://github.com/jxxghp/MoviePilot/commit/906325710b978fe3ae58b3bb24a1ddd8bd1a1957 中只修改了媒体库的跳转链接，没修改媒体播放的跳转链接，所以导致了目前使用latest版本的jellyfin时媒体播放跳转正常，媒体库跳转空白，而使用nightly版本的jellyfin时媒体库跳转正常，媒体播放跳转空白，十分尴尬...

**Comment by jxxghp** [comment]
@zbqsfs 以哪个版本为准？

**Comment by zbqsfs** [comment]
> @zbqsfs 以哪个版本为准？

我觉得应该以latest版本为准，nightly都没正式发布，也不稳定，而且大部分人用的应该也是latest版本吧
