### ISSUE TITLE
[错误报告]: IYUU自动辅种插件馒头站点报错

### ISSUE THREAD

**Issue by wkeylin** [jxxghp/MoviePilot#1950]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

IYUU自动辅种插件馒头站点报错

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-04-24 19:55:22,746 - qbittorrent.py - 添加种子出错：错误：'torrent__0' 不是一个有效的 torrent 文件。
【INFO】2024-04-24 19:55:22,739 - iyuuautoseed - 添加下载任务：https://kp.m-team.cc/api/torrent/genDlToken?https=1 ...
【ERROR】2024-04-24 19:55:22,736 - torrent.py - 种子文件解析失败：Unable to interpret `{` char.
```

**Comment by yellowstrong** [comment]
很久了

**Comment by jxxghp** [comment]
插件已更新，跑下看看。有问题请贴日志。

**Comment by yellowstrong** [comment]
![iShot_2024-04-26_13 43 26](https://github.com/jxxghp/MoviePilot/assets/34505611/dd06a4a7-3c66-43a7-86ed-08a061582a80)
清除缓存功能又没用了
