### ISSUE TITLE
[错误报告]: 馒头站连通性测试成功，但是无法正常使用

### ISSUE THREAD

**Issue by fengjiajun0806** [jxxghp/MoviePilot#1951]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

站点用的是：https://xp.m-team.io/
cookie是从浏览器的F12里复制的
连通性测试成功，但是好像无法浏览站点

![image](https://github.com/jxxghp/MoviePilot/assets/32607966/011977f3-9f85-4977-99c9-53741404190e)
![image](https://github.com/jxxghp/MoviePilot/assets/32607966/b97cc92a-d3c4-41f6-8a8a-1a616e1f1f01)

搜索资源也搜索不到
![image](https://github.com/jxxghp/MoviePilot/assets/32607966/3abddd89-5829-4ace-b034-1423e16f0b12)
![image](https://github.com/jxxghp/MoviePilot/assets/32607966/45175b8d-de3a-4cd6-bd22-d50c0369306d)

站点数据统计，刷流什么的都没有馒头
其他pt站都可以正常使用

**Comment by heshan410** [comment]
去馒头站领个秘钥就行了

**Comment by fengjiajun0806** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/32607966/125a9d7d-b115-45b2-a740-14190b78eef4)
解决了确实是这个原因

**Comment by fengjiajun0806** [comment]
已解决
