### ISSUE TITLE
套件版mp无法在设定中新增用户，点击后无反应 期待更新改正

### ISSUE THREAD

**Issue by heshan410** [jxxghp/MoviePilot#1952]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

套件版mp无法在设定中新增用户，点击后无反应 期待更新改正

**Comment by jxxghp** [comment]
docker版本无法重现这个问题，我不维护套件版不知道是什么原因。

**Comment by chenyangchina** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/40290444/a6ede830-ce9b-4eae-a337-64a63dcfd4b2)
![image](https://github.com/jxxghp/MoviePilot/assets/40290444/cbdc3b99-60c2-41dd-85f5-04a16af39cde)
我是群晖套件版也遇到这个问题
