### ISSUE TITLE
[错误报告]: 历史记录整理记住上次输入内容

### ISSUE THREAD

**Issue by yokunnyang** [jxxghp/MoviePilot#1953]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

你好，作者，在我提交反馈增加目录搜索之前的版本也就是1.8.1之前的版本都是能够手动历史记录刮削的时候，当成功刮削好一个后，点第二个手动刮削他是能记住上次填写的信息的，自从更新目录搜索后历史记录手动刮，每次点手动都会空白，记不住上次的内容，这导致批量用集数定位时，有些视频 刮不成功的，或者出错的，没法批量手动刮，只能一个个重复输入多个信息，不像以前只要改下集数就可以了（因为之前是能记住上次手动刮削的填写内容）。所以恳请能否把这个功能恢复回来，这样手动刮削多集数的文件时也能更快速，不然实在太难受了！，下图是我集数定位失败的案例。
恳请能手动刮削时记住上次设置，谢谢
![QQ图片20240425183159](https://github.com/jxxghp/MoviePilot/assets/133833844/76425514-0e96-4412-a3cd-8ca28091f474)
![QQ图片20240425183206](https://github.com/jxxghp/MoviePilot/assets/133833844/32c9771a-bafa-437a-90ee-7ed28f207934)

### 发生问题时系统日志和配置文件

```bash
问题已讲明
```

**Comment by jxxghp** [comment]
一部剧的所有文件，写好集数定位，全选只处理一次就可以了吧？

**Comment by yokunnyang** [comment]
是的，但是集数定位不知道为什么有些会有问题，用{a}忽略也不行，还有我碰到的#这类的他感觉也识别不到，所以希望作者能历史记录，单个集数手动整理的时候可以记住上次的设置，这样就能单个改集数就可以了，能快不少，因为之前1.8.1版本以前是有这个功能的，1.8.1之后更新后就开始记不住了
















在 2024-04-26 12:27:48，"jxxghp" ***@***.***> 写道：

一部剧的所有文件，写好集数定位，全选只处理一次就可以了吧？

**Comment by jxxghp** [comment]
#1981
