### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by testniubi1** [jxxghp/MoviePilot#1956]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.3

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

PushDeer插件在1.7.6-1之前的Win版本中可以正常安装使用，在1.7.6-1之后直到1.8.3版本中突然显示“在可执行文件模式下，只能安装本地插件”

**Comment by jxxghp** [comment]
用安装版本的Win吧。
