### ISSUE TITLE
[错误报告]: 部分制作组不显示

### ISSUE THREAD

**Issue by Contrass** [jxxghp/MoviePilot#1972]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

有些制作组不显示 
自定义制作组/字幕组那边添加了也不显示
![微信图片_20240427183015](https://github.com/jxxghp/MoviePilot/assets/77086992/f3b25897-15f6-4607-bf0e-887eb541d2cf)

**Comment by jxxghp** [comment]
HHWEB是内置就支持的，检查你的自定义识别词，是不是把内容标题弄坏了。

<img width="341" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/6cf2453e-7150-4508-8558-5eb42fbde4f1">

<img width="993" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/1bbb1545-9f33-41cf-9bbd-b8be001794f8">
