### ISSUE TITLE
订阅下载符合条件的资源，最终却被过滤

### ISSUE THREAD

**Issue by zjc1994** [jxxghp/MoviePilot#1973]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

电视剧：微暗之火
设置了一些排除的关键词后，最后在有符合条件的资源，最终却被过滤掉

### 发生问题时系统日志和配置文件

```bash
【WARNING】2024-04-28 00:37:19,171 - subscribe.py - 订阅 微暗之火 未搜索到资源
【WARNING】2024-04-28 00:37:19,170 - search.py - 微暗之火 没有符合过滤规则的资源
【INFO】2024-04-28 00:37:19,170 - torrent.py - Tender Light S01E01-E03 2024 2160p WEB-DL H265 DDP5.1-ADWeb 匹配排除规则 DV|HDR|EDR|HQ|60fps
【INFO】2024-04-28 00:37:19,169 - search.py - 开始过滤规则过滤，当前规则：{'include': '', 'exclude': 'DV|HDR|EDR|HQ|60fps', 'quality': None, 'resolution': '4K|2160p|x2160', 'effect': None, 'tv_size': '', 'movie_size': '', 'min_seeders': 0} ...
【INFO】2024-04-28 00:37:19,168 - search.py - 匹配完成，共匹配到 1 个资源
【INFO】2024-04-28 00:37:19,168 - torrent.py - 微暗之火 通过别名或译名匹配到资源：观众 - Tender Light S01E01-E03 2024 2160p WEB-DL H265 DDP5.1-ADWeb
【INFO】2024-04-28 00:37:19,167 - search.py - 开始匹配结果 标题：微暗之火，原标题：微暗之火，别名：['Gone with the Wind', 'Tender Light', '微暗之火']
【INFO】2024-04-28 00:37:19,166 - search.py - 站点搜索完成，有效资源数：1，总耗时 4 秒
【INFO】2024-04-28 00:37:19,165 - search.py - 站点搜索进度：1 / 1
【INFO】2024-04-28 00:37:19,165 - indexer - 观众 搜索完成，耗时 3 秒，返回数据：1
【INFO】2024-04-28 00:37:15,134 - search.py - 开始搜索资源，关键词：微暗之火 ...
```

**Comment by jxxghp** [comment]
你这几个单字母的，误命中的概率很高：'exclude': 'DV|HDR|EDR|HQ|60fps'  只要单词内有这个字段就会匹配，
包含和排除是会匹配副标题的（日志漏打印了副标题）

DV正确的应该是：`[\s.]+DV[\s.]+`

优先级规则里有的，应该尽量用优先级规则配。

**Comment by zjc1994** [comment]
> 你这几个单字母的，误命中的概率很高：'exclude'： 'DV|HDR|EDR|HQ|60fps' 只要单词内有这个字段就会匹配， 包含和排除是会匹配副标题的（日志漏打印了副标题）
> 
> DV正确的应该是：`[\s.]+DV[\s.]+`
> 
> 优先级规则里有的，应该尽量用优先级规则配。

非常感谢大佬的回复！我自己偷懒没用正则，是不是可以新增一个功能，现在的优先级规则是针对所有订阅的，可不可自定义设置多个优先级规则文件，具体场景是，比如国产下饭剧就没必要下dv，而其它的，比如想收藏起来的的，又想下dv的。现在想实现这个场景，就只能在订阅的时候现场编辑录入。是不是可以设置提前编辑好多个订阅规则，在订阅的时候，直接进行下拉选择。
这只是我的个人需求，可能过于小众，大佬谨慎采纳考虑吧
