### ISSUE TITLE
字幕文件转移时，会被改成和视频一样的文件名，导致无法识别语言

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot#1974]
### 当前程序版本

1.8.4

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

字幕文件转移时，会被改成和视频一样的文件名，导致无法识别语言

**Comment by jxxghp** [comment]
原字幕文件名是啥？如果有代表语言的是会保留的。
