### ISSUE TITLE
[错误报告]: 馒头升级系统了，cookie失效了

### ISSUE THREAD

**Issue by QYG2297248353** [jxxghp/MoviePilot#1977]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/56836951/7bf4f9e2-e5c3-467c-b5f2-8876798f4d1c)
![image](https://github.com/jxxghp/MoviePilot/assets/56836951/5183b084-805b-49d7-81e3-5ed91b807741)

### 发生问题时系统日志和配置文件

```bash
馒头升级了，快快适配
```

**Comment by linsmalldragon** [comment]
原来是升级了.我还以为我填错了

**Comment by z3shan33** [comment]
不是老早就适配了，你能不能去tg上看清楚步骤再来提问。

**Comment by happyeddie** [comment]
但是，馒头好像已经不使用 cookie 了？

**Comment by cddjr** [comment]
> 不是老早就适配了，你能不能去tg上看清楚步骤再来提问。

馒头昨晚改了，现在已弃用Cookies，需要类似PTPP那样手动配置ApiKey才行。

另外mp之前通过Cookies更新apikey的做法是不被允许的，所以还是得重新适配

**Comment by Rainsheep** [comment]
希望适配

**Comment by QYG2297248353** [comment]
> 不是老早就适配了，你能不能去tg上看清楚步骤再来提问。

所以你想表达什么？

**Comment by calfolou** [comment]
看了下 tg 感觉应该是已经解决了，但是我升级到最新版本了，编辑站点的地方也没有填写请求头和 apikey 的地方，这是啥原因？

**Comment by maidou0215** [comment]
我填写了鉴权和 key ，连通性成功，但是还是没办法搜索。。

**Comment by 729694419** [comment]
请求头那里填啥呢？

**Comment by calfolou** [comment]
> > 看了下 tg 感觉应该是已经解决了，但是我升级到最新版本了，编辑站点的地方也没有填写请求头和 apikey 的地方，这是啥原因？
> 
> 我也是这样，请问解决了吗？

解决了，我用的 windows 版本，造成这个现象的原因是 nginx 的缓存文件没有刷新，把 nginx 目录里面的 html 或者把整个 nginx 文件夹删掉，重新打开就好了！  我用的 windows 版本。。。其他版本我不知道

**Comment by weida295** [comment]
更新的版本之后清除一下浏览器的缓存，Ctrl+F5一下就好了。
你们请求头 怎么填的啊？

**Comment by 729694419** [comment]
经过一番摸索，在Edge浏览器的开发者工具→网络→bases中找到了Authorization值，填进去后连通性测试成功。不知道对不对

**Comment by ThierryCheng** [comment]
> 更新的版本之后清除一下浏览器的缓存，Ctrl+F5一下就好了。 你们请求头 怎么填的啊？



> 请问馒头的请求头填什么呀？令牌是在网站的实验室中申请的嘛？

请求头就是cookie的值里面有一段auth=xxxx，把等号后面的值复制了就行了。

**Comment by vinoo99** [comment]
> 经过一番摸索，在Edge浏览器的开发者工具→网络→bases中找到了Authorization值，填进去后连通性测试成功。不知道对不对

方法很有效

**Comment by lindaiyu99** [comment]
我这边的auth是在 开发者工具--应用--本地储存空间  里找到的，上面那个网络---bases  我这边没有  chrome116

**Comment by vinoo99** [comment]
谢谢，新的chrome可以中找到auth了

 

发件人: lindaiyu99 ***@***.***> 
发送时间: 2024年7月11日 0:31
收件人: jxxghp/MoviePilot ***@***.***>
抄送: vinoo99 ***@***.***>; Comment ***@***.***>
主题: Re: [jxxghp/MoviePilot] [错误报告]: 馒头升级系统了，cookie失效了 (Issue #1977)

 

我这边的auth是在 开发者工具--应用--本地储存空间 里找到的，上面那个网络---bases 我这边没有 chrome116
