### ISSUE TITLE
个别种子季集信息在副标题中，这种情况未识别出季集

### ISSUE THREAD

**Issue by hotlcc** [jxxghp/MoviePilot#1989]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.5-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="1008" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/14865895/46d05841-3787-453a-b539-783fd631ddd6">
<img width="389" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/14865895/099e143f-cf64-45cb-9963-7efa2eeacd25">

**Comment by jxxghp** [comment]
哪个站？这个站没有索引到副标题导致

**Comment by hotlcc** [comment]
> 哪个站？这个站没有索引到副标题导致

https://ptvicomo.net/ 象站

**Comment by jxxghp** [comment]
象站没有问题，看是不是改了什么站点的设置导致UI变了：
<img width="804" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/ab13054a-8a72-44aa-8f33-32380e1daaf6">
