### ISSUE TITLE
[错误报告]: 站点数据统计插件无法获取馒头的数据

### ISSUE THREAD

**Issue by 99Mr-Z** [jxxghp/MoviePilot#1991]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5-1 最新

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

全新拉取最新镜像进行docker的创建，手动添加请求头和API，已经能正常进行资源检索和下载，使用站点数据统计插件全量执行，确认有选中馒头站点，执行完成后未获取到馒头的数据。
![image](https://github.com/jxxghp/MoviePilot/assets/117721493/36989167-fc47-4fae-8661-4227e74fab39)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-04-30 23:19:06,358 - sitestatistic - 站点数据刷新完成
【WARNING】2024-04-30 23:18:53,852 - siteuserinfo - 青蛙 未登录，跳过后续操作
【INFO】2024-04-30 23:18:53,727 - sitestatistic - 开始刷新站点数据 ...
【INFO】2024-04-30 23:18:50,723 - sitestatistic - 站点数据统计服务启动，立即运行一次
【INFO】2024-04-30 22:41:24,983 - sitestatistic - 站点数据刷新完成
【INFO】2024-04-30 22:41:10,785 - sitestatistic - 开始刷新站点数据 ...
【INFO】2024-04-30 22:41:07,781 - sitestatistic - 站点数据统计服务启动，立即运行一次
【INFO】2024-04-30 22:36:01,290 - sitestatistic - 站点数据刷新完成
【INFO】2024-04-30 22:35:50,129 - sitestatistic - 开始刷新站点数据 ...
【INFO】2024-04-30 22:35:47,125 - sitestatistic - 站点数据统计服务启动，立即运行一次
【INFO】2024-04-30 22:23:33,694 - sitestatistic - 站点数据刷新完成
【ERROR】2024-04-30 22:23:24,069 - sitestatistic - 站点 青蛙 无法访问：https://www.qingwapt.com/
【INFO】2024-04-30 22:23:23,974 - sitestatistic - 开始刷新站点数据 ...
【INFO】2024-04-30 22:23:20,971 - sitestatistic - 站点数据统计服务启动，立即运行一次
```

**Comment by yanbinc** [comment]
我在nas-tool 里面重新添加馒头。然后在馒头的网页里面F12.只能在应用中找到cookie信息。添加后报错cookie过期。

**Comment by 99Mr-Z** [comment]
> 我在nas-tool 里面重新添加馒头。然后在馒头的网页里面F12.只能在应用中找到cookie信息。添加后报错cookie过期。

现在馒头不推荐用cookie信息进行交互
下面是馒头的wiki说明

需登入後test2才可觀看
https://test2.m-team.cc/api/doc.html#/home
(文档有bug，请求数据格式json/form与实际可能不一致；必传参数可能不准确；建议辅以web调用情况使用)

第三方工具請使用 API Access Token 訪問資料介面：可通过【控制台->實驗室->存取令牌】自助获取
http請求頭中通過：x-api-key傳遞

注意：自开放API KEY后，如发现第三方工具仍通过cookie访问接口不排除禁用账户的可能

附不允许第三方调用清单：

/admin/**
/login
/apikey/**
/member/updateLastBrowse
/member/getSessionList
/member/revokeSession
/member/queryUserLoginHistory
/msg/** （未读消息统计除外）

**Comment by yanbinc** [comment]
请问下在MP中
请求头填写 x-api-key
令牌填写  mt里面的存取令牌

是这样吗？谢谢

**Comment by yanbinc** [comment]
馒头在MP中测试连通性，总是报鉴权已过期。

**Comment by 99Mr-Z** [comment]
> 馒头在MP中测试连通性，总是报鉴权已过期。

虽然提示鉴权过期，但是是可以正常检索和获取种子的

**Comment by jxxghp** [comment]
v3.0可以的吧

![image](https://github.com/jxxghp/MoviePilot/assets/51039935/322327fb-da05-40cd-8ed3-44aa43a306c4)

**Comment by 99Mr-Z** [comment]
站点统计插件的确是V3.0的，但不知道为什么没有统计到馒头的信息，青蛙的问题在于无法正常连接，能理解，馒头的不清楚为什么没有被统计到

![image](https://github.com/jxxghp/MoviePilot/assets/117721493/77dea8fa-61b5-48f1-9280-ea2747e53c22)

![image](https://github.com/jxxghp/MoviePilot/assets/117721493/228b4b50-0c2b-45fd-91fe-c9e2d7fa8ec8)

**Comment by dzbl04230302** [comment]
同样的问题，无法获取馒头数据统计，请问楼主解决了吗

**Comment by dongjiqiang** [comment]
同样的问题

**Comment by Suvee** [comment]
> v3.0可以的吧
> 
> ![image](https://private-user-images.githubusercontent.com/51039935/327989206-322327fb-da05-40cd-8ed3-44aa43a306c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTc5NDAsIm5iZiI6MTcxNTI1NzY0MCwicGF0aCI6Ii81MTAzOTkzNS8zMjc5ODkyMDYtMzIyMzI3ZmItZGEwNS00MGNkLThlZDMtNDRhYTQzYTMwNmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZTQ2MWRjMWRjMTljMGFkOWZiODI3MGQ5OWZlNDlkNGE5MzA0ZGJjYTc2OTJlMzNkNjE4NzcxN2JmMGE3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B6BR8l0Ddwzv5RjlpeclffyK61drCV5I5dmnGgTo_Tg)

v3.2还是一样的问题，其他站点正常，馒头读取都是0. 日志文件没有报错。
![图片](https://github.com/jxxghp/MoviePilot/assets/26575609/2dbf42b1-6822-4530-a105-0711d6a65c63)
![图片](https://github.com/jxxghp/MoviePilot/assets/26575609/bd20fce8-11a2-4ca4-b091-95b727c41c27)

**Comment by Devinaille** [comment]
根据我的研究，是因为该插件构建站点信息时必须要cookie，没有配置cookie就直接返回None了，所以根本没去获取数据
```python
def build(self, site_info: CommentedMap) -> Optional[ISiteUserInfo]:
        """
        构建站点信息
        """
        site_cookie = site_info.get("cookie")
        if not site_cookie:
            return None
        ...
```

**Comment by RWDai** [comment]
> 根据我的研究，是因为该插件构建站点信息时必须要cookie，没有配置cookie就直接返回None了，所以根本没去获取数据
> 
> ```python
> def build(self, site_info: CommentedMap) -> Optional[ISiteUserInfo]:
>         """
>         构建站点信息
>         """
>         site_cookie = site_info.get("cookie")
>         if not site_cookie:
>             return None
>         ...
> ```

那是不是只要在这个逻辑之上加上auth和apikey的判断就能解决问题了

**Comment by jxxghp** [comment]
> > 根据我的研究，是因为该插件构建站点信息时必须要cookie，没有配置cookie就直接返回None了，所以根本没去获取数据
> > ```python
> > def build(self, site_info: CommentedMap) -> Optional[ISiteUserInfo]:
> >         """
> >         构建站点信息
> >         """
> >         site_cookie = site_info.get("cookie")
> >         if not site_cookie:
> >             return None
> >         ...
> > ```
> 
> 那是不是只要在这个逻辑之上加上auth和apikey的判断就能解决问题了

赞，我抽空修复下。

**Comment by fanyunxu** [comment]
版本4.1也有这个问题。【ERROR】2024-10-12 01:05:02,452 - sitestatistic - 站点 馒头 连接失败，状态码：403
