### ISSUE TITLE
[Feature Request]: 希望支持mikan的RSS功能

### ISSUE THREAD

**Issue by csu97** [jxxghp/MoviePilot#200]
### 当前程序版本

1.0.3

### 功能改进

目前站点是支持mikan的，但是自定义订阅只能添加每一部番剧的RSS，不支持总体的RSS

**Comment by zero617** [comment]
可以使用rss插件
但我目前使用似乎还是有bug

**Comment by zero617** [comment]
希望尽快支持磁链下载
