### ISSUE TITLE
[错误报告]: TR外网域名访问报错

### ISSUE THREAD

**Issue by ShmilyStar** [jxxghp/MoviePilot#2000]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.5.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![QQ截图20240502180745](https://github.com/jxxghp/MoviePilot/assets/92926599/5ec35423-0977-4718-b08a-579100e8d4d2)

![QQ截图20240502180439](https://github.com/jxxghp/MoviePilot/assets/92926599/5b1e589f-d2a1-4b65-b10f-a1a02cdc79e9)

### 发生问题时系统日志和配置文件

```bash
transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //tr.*******.xyz:6652/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd7f4151810>: Failed to resolve 'https' ([Errno -5] No address associated with hostname)"))
```

**Comment by jxxghp** [comment]
#1614
