### ISSUE TITLE
[错误报告]: 插件 站点刷流 安装失败：可执行文件模式下，只能安装本地插件

### ISSUE THREAD

**Issue by HalcyonDaysssss** [jxxghp/MoviePilot#2005]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5-1

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

下载插件，站点刷流，显示插件 站点刷流 安装失败：可执行文件模式下，只能安装本地插件。其他功能正常使用。
windows环境

**Comment by gaodyoffice** [comment]
找到解决办法了吗？最近刚开始用，也遇见这个问题了。
