### ISSUE TITLE
[错误报告]: 资源搜索未能正确搜索到到青蛙的种子

### ISSUE THREAD

**Issue by 99Mr-Z** [jxxghp/MoviePilot#2007]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5-1 最新

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

查看日志，通过粘贴请求地址验证可以检索出对应资源种子，但MP无法正常获取到种子
![image](https://github.com/jxxghp/MoviePilot/assets/117721493/a66854c5-a1a6-40a9-8df1-2a783b8295ee)
![image](https://github.com/jxxghp/MoviePilot/assets/117721493/52234c6f-88b3-43c0-b8f0-0d4a9560f1ae)

### 发生问题时系统日志和配置文件

```bash
WARNING: indexer - 青蛙 未搜索到数据，耗时 0 秒
INFO:    search.py - 站点搜索进度：1 / 9
WARNING: indexer - 天雪 未搜索到数据，耗时 3 秒
INFO:    search.py - 站点搜索进度：2 / 9
INFO:    indexer - Nyaa 搜索完成，耗时 3 秒，返回数据：16
INFO:    search.py - 站点搜索进度：3 / 9
INFO:    indexer - MiKan 搜索完成，耗时 3 秒，返回数据：5
INFO:    search.py - 站点搜索进度：4 / 9
WARNING: indexer - 莫妮卡 未搜索到数据，耗时 3 秒
INFO:    search.py - 站点搜索进度：5 / 9
INFO:    spider.py - 开始请求：https://www.oshen.win/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=Mad+Men&cat404=1&cat405=1&cat402=1&cat403=1
INFO:    indexer - 馒头 搜索完成，耗时 4 秒，返回数据：170
INFO:    search.py - 站点搜索进度：6 / 9
INFO:    indexer - 红豆饭 搜索完成，耗时 4 秒，返回数据：46
INFO:    search.py - 站点搜索进度：7 / 9
INFO:    spider.py - 开始请求：https://dmhy.org/topics/list?keyword=Mad%20Men
INFO:    indexer - OshenPT 搜索完成，耗时 10 秒，返回数据：6
INFO:    search.py - 站点搜索进度：8 / 9
INFO:    indexer - 动漫花园 搜索完成，耗时 12 秒，返回数据：9
INFO:    search.py - 站点搜索进度：9 / 9
INFO:    search.py - 站点搜索完成，有效资源数：143，总耗时 12 秒
```

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/ef621207-7780-4be8-9895-37bd30e0421d)

**Comment by 99Mr-Z** [comment]
那就应该还是站点没有正常设置生效，目前点击浏览，确实无法正常看到种子文件
