### ISSUE TITLE
[错误报告]: 搜索资源有，但无法搜索到

### ISSUE THREAD

**Issue by yanbinc** [jxxghp/MoviePilot#2008]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我搜索 嗜血法医：杀魔新生  。
该资源HDFans中是有的，我在NASTOOL里面可以搜索到。但在MP中搜索不到。

**Comment by EkkoG** [comment]
请带上日志

**Comment by yanbinc** [comment]
closed
