### ISSUE TITLE
电视剧热门订阅没有入库标识

### ISSUE THREAD

**Issue by shixiaolong777** [jxxghp/MoviePilot#2020]
### 当前程序版本

1.8.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

电视剧热门订阅没有入库标识

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/edb0630a-205e-431b-aed7-226c426932ef)

现在就会显示。

**Comment by jxxghp** [comment]
剧集是有问题，已修复并重新发布。
