### ISSUE TITLE
1ptba认证方式无法成功认证

### ISSUE THREAD

**Issue by Jerry-Geng** [jxxghp/MoviePilot#2023]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

无法认证1ptba，导致站点功能无法使用，我自己尝试过网页登录1ptba站点，发现现在1ptba把“https://1ptba.com”这个地址默认的页面指向了一个自己设计的首页，真正的登录认证页面需要在域名后加上/index.php，请版主检查一下是否这个问题导致的，望尽快修复！

**Comment by jxxghp** [comment]
@Jerry-Geng 认证是站点方提供的单独api接口，并未收到变更通知，需要站点侧确认是否有变化。
