### ISSUE TITLE
可以直接任意用户登录？？？

### ISSUE THREAD

**Issue by 705058548** [jxxghp/MoviePilot#2029]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

只要知道域名或IP，打开了登录界面，随便输入个用户名就可以登录进去（虽然不是管理员账户，但也觉得别扭），后台自动增加了该任意名字的账户。不是后台提前设置好的用户才可以登录吗？这样是否不太安全？

**Comment by jxxghp** [comment]
你在说什么？确定清楚了吗？

**Comment by jxxghp** [comment]
@705058548 麻烦你看下日志， emby/jellyfin的用户只要用户名和密码对会自动同步，避免还要再去建一遍帐号。
搞清楚了再提问题吧。
