### ISSUE TITLE
[Feature Request]: 推荐中的媒体库已存在检测能否使用 TheMovieDb Id 或者 Douban Id 来查询

### ISSUE THREAD

**Issue by yotsubar** [jxxghp/MoviePilot#203]
### 当前程序版本

v1.0.3

### 功能改进

目前已存在检测的接口是用名称来查询的。但是有些电影豆瓣和tmdb中的标题不一致，导致moviepilot里边没有显示已存在。比如《大话西游之大圣娶亲》在tmdb里边的名称是 《大话西游之仙履奇缘》，虽然emby里边的tmdb id, douban id , imdb id都是正确的，但是因为名称不同，结果没能正确检测到。同样的还有 《指环王3：王者归来》和 《指环王3：王者无敌》。如果支持按id来检测，就可以避免这种问题。
是个无关紧要的问题，大佬们有时间可以考虑一下。

**Comment by jxxghp** [comment]
同步媒体库数据后会优先用ID去匹配。
没同步的没这个接口，查不了。
