### ISSUE TITLE
[错误报告]: rm格式的视频不会整理

### ISSUE THREAD

**Issue by BrettDean** [jxxghp/MoviePilot#2030]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.6-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

发现一种名为`.rm`格式的视频，mp整理的时候不会自动整理
![image](https://github.com/jxxghp/MoviePilot/assets/36684698/9e1e346c-2a0d-408a-91d9-896271f9b8bd)

你猜这几个视频的比特率是多少？
48kbps !!
哈哈哈哈哈

**Comment by z3shan33** [comment]
> 可以在环境变量里通过RMT_MEDIAEXT变量添加rm格式

RMT_MEDIAEXT='[".mp4", ".mkv", ".ts", ".iso",".rmvb", ".avi", ".mov", ".mpeg", ".mpg", ".wmv", ".3gp", ".asf",".m4v", ".flv", ".m2ts", ".strm",".tp", ".f4v", ".rm"]'

**Comment by z3shan33** [comment]
> > 可以在环境变量里通过RMT_MEDIAEXT变量添加rm格式
> 
> RMT_MEDIAEXT='[".mp4", ".mkv", ".ts", ".iso",".rmvb", ".avi", ".mov", ".mpeg", ".mpg", ".wmv", ".3gp", ".asf",".m4v", ".flv", ".m2ts", ".strm",".tp", ".f4v", ".rm"]'

得把默认的也加上去，不然到时候只会识别.rm了
