### ISSUE TITLE
[错误报告]: mp发送到qb下载，qb种子状态显示错误

### ISSUE THREAD

**Issue by deardeer7** [jxxghp/MoviePilot#2034]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.6-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在MoviePilot站点页面，进行下载操作；转到qbitorrent页面，种子任务被正常添加，但是状态显示错误，无法下载；尝试手动在pt站下载种子后上传qb下载，正常下载：
![image](https://github.com/jxxghp/MoviePilot/assets/42965045/dcb7700d-cfb9-44d3-81bb-da07487d25dd)

### 发生问题时系统日志和配置文件

```bash
2024/05/08 15:53:15	stdout	[32mINFO:[0m    command.py - 处理事件：notice.message - []
2024/05/08 15:53:15	stdout	描述：时间规划局/我是凡人/止时纪/潜逃时空(港)/现在/钟点战(台) 中英字幕，userid=None
2024/05/08 15:53:15	stdout	Hit&Run：是
2024/05/08 15:53:15	stdout	做种数：32
2024/05/08 15:53:15	stdout	发布时间：2024-05-08 11:58:59
2024/05/08 15:53:15	stdout	种子：In Time 2011 BluRay 1080p x264 DTS 2Audios-CMCT
2024/05/08 15:53:15	stdout	大小：10.72G
2024/05/08 15:53:15	stdout	质量： BluRay 1080p
2024/05/08 15:53:15	stdout	站点：冰淇淋
2024/05/08 15:53:15	stdout	[32mINFO:[0m    chain - 发送消息：channel=None，title=时间规划局 (2011)  开始下载, text=用户：deardeer
2024/05/08 15:53:15	stdout	[32mINFO[0m:     ::1:0 - "[1mGET /api/v1/dashboard/downloader HTTP/1.1[0m" [32m200 OK[0m
```

**Comment by w827** [comment]
解决了吗？我也是这个问题，求解决方法

**Comment by deardeer7** [comment]
> 解决了吗？我也是这个问题，求解决方法

解决了，貌似我当时用的qb镜像有问题，换了linuxserver/qbittorrent，重新配了下就没问题了

**Comment by zousoooo** [comment]
> > 解决了吗？我也是这个问题，求解决方法
> 
> 解决了，貌似我当时用的qb镜像有问题，换了linuxserver/qbittorrent，重新配了下就没问题了

我现在换这个 linuxserver/qbittorrent，还是红种
