### ISSUE TITLE
[Feature Request]: 新插件 将在看的剧集自动同步到豆瓣书影音档案

### ISSUE THREAD

**Issue by RWDai** [jxxghp/MoviePilot#2039]
### 当前程序版本

v1.8.6-1

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

emby在看剧集或看完剧集/电影时，自动同步到豆瓣（默认不打星）

**Comment by kingcard1131** [comment]
好像有个类似插件，你试试

**Comment by kingcard1131** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/53737003/ff784040-9957-4ef2-bc40-b0e857910216)

**Comment by RWDai** [comment]
> 好像有个类似插件，你试试

我好像没在插件市场里面找到这个哎
