### ISSUE TITLE
[Feature Request]: (订阅规则自动填充) 增加原始语言填充

### ISSUE THREAD

**Issue by ihnic** [jxxghp/MoviePilot#2044]
### 当前程序版本

1.8.7

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

能否在插件[订阅规则自动填充]增加TMDB的原始语言的控制

### 参考资料

![微信截图_20240510093054](https://github.com/jxxghp/MoviePilot/assets/32432943/a1d508f9-9619-44a4-9b99-d2da91f4b3fc)

**Comment by jxxghp** [comment]
向插件对应的库提
