### ISSUE TITLE
[Feature Request]: 历史记录删除源文件，过度删除

### ISSUE THREAD

**Issue by iceucn** [jxxghp/MoviePilot#2046]
### 当前程序版本

1.8.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

历史记录删除源文件，如果下载分类目录就这一个文件，会把分类下载目录一起删除，
比如电视剧下载目录是/downloads/tv，订阅下载会下载到/downloads/tv/电视剧名字这个目录，经过整理后，需要在历史记录删除源文件，如果/downloads/tv目录下就这一部电视剧，会带着 tv 目录一起删除，系统健康检查就会报错~

### 参考资料
![1](https://github.com/jxxghp/MoviePilot/assets/134840291/7983e428-af75-4459-a63f-fec09c9db5b2)

![2](https://github.com/jxxghp/MoviePilot/assets/134840291/c3b18081-5ee8-4606-9843-2674380a77d6)

![3](https://github.com/jxxghp/MoviePilot/assets/134840291/e30c12b4-d801-45f5-be48-6ae48ab80371)

![4](https://github.com/jxxghp/MoviePilot/assets/134840291/21a41dd9-6e4d-4b93-bf73-1a63eeff0ac3)

![5](https://github.com/jxxghp/MoviePilot/assets/134840291/3f234bd0-18fc-41e7-99f6-2e1f7a95a226)

![6](https://github.com/jxxghp/MoviePilot/assets/134840291/aed9df3c-ef60-4a7e-b503-edaa9887d470)

**Comment by DzAvril** [comment]
@iceucn 检查下是不是安装了清理硬链接插件，这个插件会删除空目录。可以在这个插件里配置“不删除目录”

**Comment by iceucn** [comment]
> @iceucn检查下是不是安装了清理硬链接插件，这个插件会删除空目录。可以在这个插件里配置“不删除目录”

没有装这样的插件

**Comment by jxxghp** [comment]
判断要到哪一层比较复杂，正常也不会只有一部电影吧？

**Comment by iceucn** [comment]
> 判断要到哪一层比较复杂，正常也不会只有一部电影吧？

MP设定的下载目录就不要删除了，到这级就行；
我这边是下载资源到NVME，然后整理入库复制到HDD，过段时间就通过删除历史记录+源文件来清理下载盘，就会出现这个问题；
应该也有类似使用习惯的用户
