### ISSUE TITLE
[Feature Request]: 通过下载器监控入库的通知信息优化

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#205]
### 当前程序版本

1.0.3

### 功能改进
![1123303792](https://github.com/jxxghp/MoviePilot/assets/59035223/c016148c-1387-45dc-b609-8a7526e204fd)

通过下载器监控文件入库通知信息只有季信息，没有集信息，对于追剧稍有不便，不能即时获取订阅到多少集

**Comment by dlovew** [comment]
测试了一下，发现通过mp下载的入库通知有集数信息，通过别的途径下载的资源（打上MOVIEPILOT标签）可以正常入库，但是入库通知只有季信息，无集信息

**Comment by jxxghp** [comment]
其他方式下载的没有额外信息，种子名称没有的话就没有。

**Comment by dlovew** [comment]
> 其他方式下载的没有额外信息，种子名称没有的话就没有。

确实，我看了，标题有集信息，文件名有集信息，就是种子没有集信息
