### ISSUE TITLE
[Feature Request]: 处理长时间下载不动的种子

### ISSUE THREAD

**Issue by BrettDean** [jxxghp/MoviePilot#2052]
### 当前程序版本

v1.8.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

qb下载列表中存在上百个长时间下载不动的种子
![image](https://github.com/jxxghp/MoviePilot/assets/36684698/d1605a4f-1578-4e61-81b0-a7c3be8ad6a7)

希望可以识别种子`有效时间`大于特定数值（如7天），并且剩余时间是无穷的种子，

重新搜索资源下载，

如果搜索到了和当前种子不同的种子，那就将下不动的种子删除并加入黑名单，然后开始下载新搜索到的种子，

如果搜索不到可替代资源，那么就保持原样 ~~说不定过几个月就有我能连通的ip做种了~~

**Comment by jxxghp** [comment]
可以通过开发插件支持
