### ISSUE TITLE
[错误报告]: MoviePilot重启容器自动更新失败

### ISSUE THREAD

**Issue by longweiqiang** [jxxghp/MoviePilot#2060]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.5-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### docker compose文件内容如下
```YAML
# 重启时自动更新，true/release/dev/false，默认release，需要能正常连接Github 注意：如果出现网络问题可以配置PROXY_HOST
- 'MOVIEPILOT_AUTO_UPDATE=release'
```

### 手动重启容器后触发自动更新模式，报错LOG如下
```
INFO:     Shutting down
INFO:     Waiting for connections to close. (CTRL+C to force quit)
不使用代理更新程序
Release 更新模式
当前版本号：v1.8.5-1
最新版本号：v1.8.7
发现新版本，开始自动升级...
正在下载 https://github.com/jxxghp/MoviePilot/archive/refs/tags/v1.8.7.zip...
Archive:  -
unzip: invalid zip magic 20746F4E
后端程序下载失败，继续使用旧的程序来启动...
usermod: no changes
Proxy dockerbackend started.
Proxy dockerfrontend started.
INFO:     Started server process [64]
INFO:     Waiting for application startup.
INFO:    singleton.py - 站点资源版本：1.3.5
INFO:    singleton.py - 认证资源版本：1.2.8
INFO:    singleton.py - iyuu 用户认证成功！
```

**Comment by longweiqiang** [comment]
已确认过，机器可以连通github
<img width="631" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/22344864/cd2a44ed-b4ef-4c63-a651-fba37c80c5f6">

**Comment by JohnweeP** [comment]
同问，遇到同样的问题

**Comment by shiyue-and-siyue** [comment]
同问，我也是一样的问题，群晖docker部署的

**Comment by JohnweeP** [comment]
已解决，是GitHub token的问题，检查是否过期或者权限没勾选全，或者直接删掉token

> 同问，我也是一样的问题，群晖docker部署的

**Comment by god1ong** [comment]
把 github token 的权限Select scopes 对应的repo 启用，就可以更新了。

Scopes define the access for personal tokens. [Read more about OAuth scopes.](https://docs.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/)

repoFull control of private repositories
repo:statusAccess commit status
repo_deploymentAccess deployment status
public_repoAccess public repositories
repo:inviteAccess repository invitations
security_eventsRead and write security events
