### ISSUE TITLE
[Feature Request]: 不知道在搜索优先级哪里的排序能否支持拖动排序。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#2066]
### 当前程序版本

v1.8.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

类似这个项目前端可以这样操作，项目地址https://github.com/hslr-s/sun-panel

![recording](https://github.com/jxxghp/MoviePilot/assets/44762565/12e261de-9139-4ff8-b8aa-0a10f93eb27a)

**Comment by jxxghp** [comment]
@loveu5522 仪表版的组件已经支持了，稍后将扩展到优先级设置上

**Comment by loveu5522** [comment]
收到！
