### ISSUE TITLE
【订阅BUG】tmdb的季数错误导致无法订阅

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#2068]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1、tmdb的季数错误导致无法订阅
2、希望在订阅界面可以自定义设置季数
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/2f8818b3-744c-4c6f-a41b-e109b5d462df)
实际上【家族荣耀之继承者（2024）】是【家族荣耀（2022）】续集。
但是tmdb上显示为第1季。导致无法订阅【PT站点都把（家族荣耀之继承者）正确的归为第2部】

**Comment by Whichbfj28** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/47915665/6233996b-817e-4307-b1c1-e47ab8d76409)
如果使用【家族荣耀】这个关键词进行订阅第二部的话 使用官方的电视剧命名变量出来是这样的。
【{{title}}{% if year %} ({{year}}) {% endif %}第{{season}}部{% if en_title %} - {{en_title}}{% endif %} (S{{season}}){% if videoFormat %}.{{videoFormat}}{% endif %}{% if releaseGroup %}-{{releaseGroup}}{% endif %}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if episode %} - 第 {{episode}} 集{% endif %} - {% if edition %}{{edition}}{% endif %}{% if videoCodec %}.{{videoCodec}}{% endif %}{% if audioCodec %}.{{audioCodec}}{% endif %}{{fileExt}}】
中文名字、年份、英文名跟tmdb的不一致。

**Comment by dlovew** [comment]
这部剧有两个条目，你仔细看看，完全可以订阅家族荣耀第二季

**Comment by Whichbfj28** [comment]
> 这部剧有两个条目，你仔细看看，完全可以订阅家族荣耀第二季
按照你所说订阅后的 。电视剧重命名标题跟tmdb不一致。看回复1

https://github.com/jxxghp/MoviePilot/issues/2068#issuecomment-2109370018

**Comment by Whichbfj28** [comment]
> > 这部剧有两个条目，你仔细看看，完全可以订阅家族荣耀第二季
 按照你所说订阅后的 。电视剧重命名标题跟tmdb不一致。看回复
> [#2068 (comment)](https://github.com/jxxghp/MoviePilot/issues/2068#issuecomment-2109370018)
