### ISSUE TITLE
[错误报告]: 星空无法通过cookie验证

### ISSUE THREAD

**Issue by naoki66** [jxxghp/MoviePilot#2076]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

正常配置该站点的cookie和User-Agent，却一直无法通过连通性测试
修改站点地址无效

**Comment by linglichao** [comment]
域名后面加上这个/torrents.php，应该就能访问了，因为主域名会去到宝贝回家

**Comment by naoki66** [comment]
> 修改站点地址无效

修改站点地址无效，保存后又自动去除/后的地址

**Comment by linglichao** [comment]
![QQ截图20240516102327](https://github.com/jxxghp/MoviePilot/assets/20856711/7ed3ba7f-36bc-4bed-9dfb-00eba4fb174a)
我这边是可以的，但是是以前手动改的，不知道是不是新版本不允许改
