### ISSUE TITLE
[功能建议]: 电影和剧集重命名格式能够增加 一个显示帧率变量，比如60fps和120fps。

### ISSUE THREAD

**Issue by 404ZenX** [jxxghp/MoviePilot#2079]
### 当前程序版本

v1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

MOVIE_RENAME_FORMAT：  电影和剧集重命名格式能够增加 一个显示帧率变量，比如60fps和120fps。

![截图_20240515145636](https://github.com/jxxghp/MoviePilot/assets/44762565/d3d353ee-9527-4166-85ac-8cb169e3532b)

**Comment by ArthurSmoke** [comment]
+1 现在国产剧资源中 60fps的资源越来越多了
