### ISSUE TITLE
[Feature Request]: 增加订阅连载剧集时自动选择固定制作组下载

### ISSUE THREAD

**Issue by Tatsumi-Ryuu** [jxxghp/MoviePilot#2085]
### 当前程序版本

1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

# 目前的问题
在订阅连载剧集时，如果是使用bot添加或是没有特意在订阅中二次设置的情况下，很容易下到来自不同制作组的资源
![ae0f70c232dfa4e258664993d2d1ac3f](https://github.com/jxxghp/MoviePilot/assets/67691236/15494729-f79c-42eb-b5cf-cb52730cd092)
这样会导致在最后完结的时候，需要重新下载一遍制作组打包的资源，将原本不是同一个制作组的资源替换掉

# 希望的改进
如果能够根据第一集下载资源的制作组，自动固定后续剧集也下载同样的制作组的资源，就可以无需在完结时再次洗版
也能解决在订阅时需要再进行设置，或者是使用bot订阅之后，还要进入web界面再设置筛选的麻烦

**Comment by dlovew** [comment]
第三方插件已经有了，叫订阅规则自动填充

**Comment by Tatsumi-Ryuu** [comment]
> 第三方插件已经有了，叫订阅规则自动填充

看了下，确实挺符合需求的，感谢感谢
