### ISSUE TITLE
【功能改进】能否加快面板的加载速度

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#2088]
### 当前程序版本

1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

进入面板的速度很慢。基本都要几秒才进入面板
希望可以实现qbittorrent这样的秒开效果。
不然心里总觉得打开MP很费劲。要订阅新电影的时候。不想动

**Comment by jxxghp** [comment]
加了缓存，去除了一些无用的包，下个版本应该就飞快了（非第一次登录的情况下）
