### ISSUE TITLE
[错误报告]: 订阅会重复下载问题

### ISSUE THREAD

**Issue by jeffry88** [jxxghp/MoviePilot#2092]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅会同时多个站重复下载资源，是不是程序判断逻辑有点问题
<img width="602" alt="微信图片_20240516202526" src="https://github.com/jxxghp/MoviePilot/assets/25890075/42a0c80e-ecac-462f-a986-f0453c64f8a2">
<img width="968" alt="微信图片_20240516202537" src="https://github.com/jxxghp/MoviePilot/assets/25890075/1eb5a42f-24cb-4d49-95ff-63a697ca3550">
<img width="948" alt="微信图片_20240516202550" src="https://github.com/jxxghp/MoviePilot/assets/25890075/743d771d-7a94-4043-95b8-b876abaab2a5">

**Comment by thsrite** [comment]
@jeffry88 确认下下载的4个种子是拆包了吧，没有重复下载

**Comment by jeffry88** [comment]
> @jeffry88 确认下下载的4个种子是拆包了吧，没有重复下载

4个种子是不同站下的，前面两个分别是第一集和第二集，后面两个种子是1-4集和1-5集，这个是不是有重复了

**Comment by jxxghp** [comment]
> > @jeffry88 确认下下载的4个种子是拆包了吧，没有重复下载
> 
> 4个种子是不同站下的，前面两个分别是第一集和第二集，后面两个种子是1-4集和1-5集，这个是不是有重复了

查看下载任务的文件，是不是有拆包只下载了部分集的文件。
现在是按设置的优先来依次匹配的，如果只有2集的这个种子或者站点优先，就会先下载这2集，但后面发现低优先级的又有1-5，则会在1-5中挑剩下的3集下载，以此类推。

你这个情况的下个种子，正常情况下下载的文件应该是：1-2、3-4、5
