### ISSUE TITLE
[Feature Request]: 缩略图功能

### ISSUE THREAD

**Issue by a1257636709** [jxxghp/MoviePilot#2094]
### 当前程序版本

V1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否添加nastool中转移文件时生成缩略图功能  增加用户体验 这些 功能截图去下
![d4f109ade80769a9c559a2f2c9d86024](https://github.com/jxxghp/MoviePilot/assets/96871333/5c3247cf-434c-40de-992b-643578fbef4e)

### 参考资料

Nastool中的功能

**Comment by a1257636709** [comment]
能否提供插件名称

**Comment by jxxghp** [comment]
你猜的吧，不能先用下看么？

**Comment by a1257636709** [comment]
我是通过插件设置界面 只有定时扫描周期  定时扫描路径 不知道怎么设置配合转移使用  请指教 谢谢

**Comment by a1257636709** [comment]
![Uploading IMG_5973.png…]()

**Comment by jxxghp** [comment]
开关打开就会实时处理，同时也有全亮扫描的功能

**Comment by a1257636709** [comment]
谢谢

**Comment by a1257636709** [comment]
再次感谢大佬回复  还有一个问题 现在mp有一个模块报错 请问是什么引起的 怎么处理这个问题  谢谢 辅报错图
![IMG_5978](https://github.com/jxxghp/MoviePilot/assets/96871333/7ff872ce-4b83-4109-9cc7-4281860bfee9)
