### ISSUE TITLE
云盘Strm生成的插件，大写无法识别

### ISSUE THREAD

**Issue by lifujie25** [jxxghp/MoviePilot#2095]
### 当前程序版本

1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

云盘Strm生成的插件，如后缀为大写，无法识别，之前联系一个大佬，给了一段代码，加到env可以识别，但是重启的时候无法启动mp，RMT_MEDIAEXT=['.mp4', '.mkv', '.ts', '.iso', '.rmvb', '.avi', '.mov', '.mpeg', '.mpg', '.wmv', '.3gp', '.asf', '.m4v', '.flv', '.m2ts', '.strm', '.tp', '.f4v']
而且没有目前是没有实时监控功能，看其他网盘工具都有实时监控
这个软件挺好用，希望能修复和有实时监控

**Comment by jxxghp** [comment]
这个插件就不在这个库里，去插件作者的库里提。
