### ISSUE TITLE
[错误报告]: mp有一个模块报错

### ISSUE THREAD

**Issue by a1257636709** [jxxghp/MoviePilot#2096]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

最新版

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

mp有一个模块报错 请问是什么引起的 怎么处理这个问题 谢谢 辅报错图
![IMG_5978](https://github.com/jxxghp/MoviePilot/assets/96871333/12bc2961-f2ce-48bc-9255-7f407952c687)

**Comment by jxxghp** [comment]
重新设置一下优先级规则或者默认过滤规则，不是共性问题，不确认你维护了什么值
