### ISSUE TITLE
[Feature Request]: 多盘的硬连接

### ISSUE THREAD

**Issue by cosmotown** [jxxghp/MoviePilot#2097]
### 当前程序版本

1.8.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

现在情况是这样的，最近添加了新的硬盘，但mp下载目录只能设置一个，因为硬连接不能分别映射，qb下载又想下载在两个不同的卷里进行硬连接，导致多卷硬连接无法正常运行，

### 参考资料

原来一个卷的时候只需要qb和mp同时映射一个downloads文件夹，然后下面自己建立文件夹分好link和源文件的文件夹就行。现在两个卷后就把动漫分到了卷2，这时问题就来了，qb需要分别映射两个卷来下载资源，动漫单独一个，这时由于硬连接不能分别映射，导致失效，请问可以像以前nastool一样设置多个下载器，或让mp设置多个下载目录，实现多盘情况下自动订阅也能硬连接吗？

**Comment by cng10001** [comment]
这个能设置3个不一样的盘
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/68f8d6d1-221a-4f85-9a12-c1bd796b0cc5)

**Comment by cosmotown** [comment]
> 不知道我有没有理解对 你把2个盘分别设置媒体库就行了 ![image](https://private-user-images.githubusercontent.com/115156545/331466776-1d18d19a-61a7-4b7a-9b68-7652bf4c4adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTc2OTcsIm5iZiI6MTcxNTk1NzM5NywicGF0aCI6Ii8xMTUxNTY1NDUvMzMxNDY2Nzc2LTFkMThkMTlhLTYxYTctNGI3YS05YjY4LTc2NTJiZjRjNGFkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmNkMzg3Mjg3ZTExMjAyOTE2ODZkZDI5MzExYWI5OWM4OTI2ZWE0ZjQ4MzYzMDZiZDAyZmFjYzMwNjE0NDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TW_SIOtHOhNZNENOb6ZlUTCOvPgCP0yf0vSlHSnL97A)

**Comment by cosmotown** [comment]
> > 不知道我有没有理解对 你把2个盘分别设置媒体库就行了 ![image](https://private-user-images.githubusercontent.com/115156545/331466776-1d18d19a-61a7-4b7a-9b68-7652bf4c4adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTc2OTcsIm5iZiI6MTcxNTk1NzM5NywicGF0aCI6Ii8xMTUxNTY1NDUvMzMxNDY2Nzc2LTFkMThkMTlhLTYxYTctNGI3YS05YjY4LTc2NTJiZjRjNGFkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNDQ5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmNkMzg3Mjg3ZTExMjAyOTE2ODZkZDI5MzExYWI5OWM4OTI2ZWE0ZjQ4MzYzMDZiZDAyZmFjYzMwNjE0NDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TW_SIOtHOhNZNENOb6ZlUTCOvPgCP0yf0vSlHSnL97A)

这样不行，我现在就是动漫和电影电视分别设置的媒体库，但由于qb下载也要分开映射，还是不能够形成硬连接，你可以测试一下

**Comment by cng10001** [comment]
下载器下载到不同的盘，本身就需要映射。你表达的意思，qb分开映射和不能形成硬链接应该不是你想表达的逻辑关系吧。
不太明白你说的硬链接不能映射是什么意思。
你最好把你的配置贴上来 让大家看看

**Comment by cosmotown** [comment]
> 下载器下载到不同的盘，本身就需要映射。你表达的意思，qb分开映射和不能形成硬链接应该不是你想表达的逻辑关系吧。 不太明白你说的硬链接不能映射是什么意思。 你最好把你的配置贴上来 让大家看看

可能我表达的不太清楚，具体是这样的，比如我qb映射是/volume1/电影:/downloads/电影，/volume2/动漫:/downloads/动漫。既电影和动漫分别下载在不同的两个盘里。这时由于mp下载文件夹是必填的而且直接填一个。我该怎么映射能使两个盘分别形成电影和动漫的硬连接？我尝试了分别映射发现不行，又不能像原来单盘那样只映射一个downloads文件夹。所以有没有成功的范例？

**Comment by cng10001** [comment]
黑裙辉吗
你下载器映射文件夹感觉分很细啊，直接映射一级文件夹就行了，就是最大的那个共享文件夹。这样你可以在里面创建很多子文件夹，随便你想创建电影文件夹还是downloads文件夹啊
不管你单独划了一个电影文件夹，还是在downloads/电影都是随便你的
/电影:/电影
假如你分的盘是downloads，你就映射/downloads:/downloads 因为你可以在downloads下创建电影文件夹啊
我是这样映射的
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/551846cf-1a4a-4a6e-aab2-f8cefe5e57f0)

**Comment by cosmotown** [comment]
> 黑裙辉吗 你下载器映射文件夹感觉分很细啊，直接映射一级文件夹就行了，就是最大的那个共享文件夹。这样你可以在里面创建很多子文件夹，随便你想创建电影文件夹还是downloads文件夹啊 不管你单独划了一个电影文件夹，还是在downloads/电影都是随便你的 /电影:/电影 假如你分的盘是downloads，你就映射/downloads:/downloads 因为你可以在downloads下创建电影文件夹啊 我是这样映射的 ![image](https://private-user-images.githubusercontent.com/115156545/331817228-0533be52-22c6-481d-bec9-957b73207edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODU1NjEsIm5iZiI6MTcxNjA4NTI2MSwicGF0aCI6Ii8xMTUxNTY1NDUvMzMxODE3MjI4LTA1MzNiZTUyLTIyYzYtNDgxZC1iZWM5LTk1N2I3MzIwN2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMjIxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjg5YjQxYWE0YTgyOTEyZjcxMDI2NjRjNmM4OTVlN2EzZTQ4ODJlODJhZDE0NTE1NGVjMGM2ZjMzMmY4Yjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iv--7NmT8o25SM6h3Rzqen730hFhJZSCDjEsajbOOXk) 我可以直接分一个动漫盘 也可以把动漫直接放到/video下，只需要映射了video，后续可以在软件里面设置/video/动漫就可以

单卷确实可以这么做，我以前也是这么做的，现在问题是两块硬盘了，如果只映射一个downloads，怎么把动漫和电影下载到两个不同的硬盘里？我理解到硬连接应该是源文件占空间吧？硬连接后的不占。

**Comment by cng10001** [comment]
第一块硬盘Adownloads 第二款硬盘也一样啊 Bdownloads
我图片上也不止一块硬盘啊

**Comment by cosmotown** [comment]
> 黑裙辉吗 你下载器映射文件夹感觉分很细啊，直接映射一级文件夹就行了，就是最大的那个共享文件夹。这样你可以在里面创建很多子文件夹，随便你想创建电影文件夹还是downloads文件夹啊 不管你单独划了一个电影文件夹，还是在downloads/电影都是随便你的 /电影:/电影 假如你分的盘是downloads，你就映射/downloads:/downloads 因为你可以在downloads下创建电影文件夹啊 我是这样映射的 ![image](https://private-user-images.githubusercontent.com/115156545/331817228-0533be52-22c6-481d-bec9-957b73207edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODYwNjUsIm5iZiI6MTcxNjA4NTc2NSwicGF0aCI6Ii8xMTUxNTY1NDUvMzMxODE3MjI4LTA1MzNiZTUyLTIyYzYtNDgxZC1iZWM5LTk1N2I3MzIwN2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMjI5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjI3OTZkOTAzOWViZGVlMDA5NjA0Zjk4ZGUzZjIyYWNiYzIyMTBjZDRmNzAyMjM0MTNlMDk5NzY2ZjM1ZWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SiqSuEi96rbbr_fr1uZUspSILagFOFiQF48MluN_re4) 我可以直接分一个动漫盘 也可以把动漫直接放到/video下，只需要映射了video，后续可以在软件里面设置/video/动漫就可以

我是爱速特，还是那个问题，我这样单卷可以操作，比如我卷1创建个共享文件夹downloads，然后qb和mp同时映射这个文件夹，这样我只需要在downloads下创建各种电影 电视剧 动漫 link文件夹就可以正常工作了，但现在是双盘，怎么把两个盘映射进同一个文件夹呢？我现在只能映射进同一个文件夹的子文件夹，但那样硬连接就失效了。

**Comment by cosmotown** [comment]
> 第一块硬盘Adownloads 第二款硬盘也一样啊 Bdownloads 我图片上也不止一块硬盘啊

意思是可以这样吗？第一第二块盘都设置downloads共享文件夹，然后volume1/downloads:/downloads ;/volume2/downloads:/downloads？就是两个盘映射同一个文件夹？

**Comment by cosmotown** [comment]
> > 第一块硬盘Adownloads 第二款硬盘也一样啊 Bdownloads 我图片上也不止一块硬盘啊
> 
> 意思是可以这样吗？第一第二块盘都设置downloads共享文件夹，然后volume1/downloads:/downloads ;/volume2/downloads:/downloads？就是两个盘映射同一个文件夹？


> 黑裙辉吗 你下载器映射文件夹感觉分很细啊，直接映射一级文件夹就行了，就是最大的那个共享文件夹。这样你可以在里面创建很多子文件夹，随便你想创建电影文件夹还是downloads文件夹啊 不管你单独划了一个电影文件夹，还是在downloads/电影都是随便你的 /电影:/电影 假如你分的盘是downloads，你就映射/downloads:/downloads 因为你可以在downloads下创建电影文件夹啊 我是这样映射的 ![image](https://private-user-images.githubusercontent.com/115156545/331817228-0533be52-22c6-481d-bec9-957b73207edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODY3MTMsIm5iZiI6MTcxNjA4NjQxMywicGF0aCI6Ii8xMTUxNTY1NDUvMzMxODE3MjI4LTA1MzNiZTUyLTIyYzYtNDgxZC1iZWM5LTk1N2I3MzIwN2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMjQwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVmYmVhMmY0MDc4ZTU3NjYzNmVkMTgzOTIwMTNiZjAwYTlmNjA5NmI1OTI1MjM1Yzg1ODQ1NmE4Yjk5OTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sl5CLiOKyfb30flB_lq_GXFUUi2kpxt_l4HvtHCer_I) 我可以直接分一个动漫盘 也可以把动漫直接放到/video下，只需要映射了video，后续可以在软件里面设置/video/动漫就可以

还有您这么做，mp下载文件夹怎么设置？那个我看只能设置一个，没法设置第二个文件夹，比如你图里动漫在动漫文件夹，电影如果在media1文件夹，mp里怎么设置把内容下到这两个不同文件夹里，其实我就这里看不懂，因为它的下载文件夹只能填一个，比如以你的图为例子，我填了/media1，它后面有三个，电影 动漫 电视剧文件夹是不是只能填/media1文件夹下的文件夹？还是我可以无视这个必填的下载文件夹，直接动漫那里填/动漫

**Comment by cng10001** [comment]
两个盘映射进同一个文件夹？你是想盘1和盘2个盘组raid扩大容量吗
如果你直接添加第二款硬盘新加卷的话是下面这个意思
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/66f5e9e9-34f7-4dd6-9407-e8e98b6eb135)

**Comment by cosmotown** [comment]
> 两个盘映射进同一个文件夹？你是想盘1和盘2个盘组raid扩大容量吗 如果你直接添加第二款硬盘新加卷的话是下面这个意思 ![image](https://private-user-images.githubusercontent.com/115156545/331843795-66f5e9e9-34f7-4dd6-9407-e8e98b6eb135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODc2MjIsIm5iZiI6MTcxNjA4NzMyMiwicGF0aCI6Ii8xMTUxNTY1NDUvMzMxODQzNzk1LTY2ZjVlOWU5LTM0ZjctNGRkNi05NDA3LWU4ZTk4YjZlYjEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMjU1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTU3ZjM4NGIxZjcyYmQ1MTRlMTExYzBhYWQ1NjQ4ODNiNTE0NGE1YTlkZDg4N2UyOWM4YTQwMGY4YmUyYjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GmI4dyXMQKPdtddFctsK2eFkOU85Vr2Jn_CQiGDcs4U)

我有点理解你的意思了，这样在qbmp里就只看到一个downloads文件夹，我一直以为这样是不可以的，所以才分别映射了下级的子文件夹，回去我试一下，谢谢

**Comment by cng10001** [comment]
> > > 第一块硬盘Adownloads 第二款硬盘也一样啊 Bdownloads 我图片上也不止一块硬盘啊
> > 
> > 
> > 意思是可以这样吗？第一第二块盘都设置downloads共享文件夹，然后volume1/downloads:/downloads ;/volume2/downloads:/downloads？就是两个盘映射同一个文件夹？
> 
> > 黑裙辉吗 你下载器映射文件夹感觉分很细啊，直接映射一级文件夹就行了，就是最大的那个共享文件夹。这样你可以在里面创建很多子文件夹，随便你想创建电影文件夹还是downloads文件夹啊 不管你单独划了一个电影文件夹，还是在downloads/电影都是随便你的 /电影:/电影 假如你分的盘是downloads，你就映射/downloads:/downloads 因为你可以在downloads下创建电影文件夹啊 我是这样映射的 ![image](https://private-user-images.githubusercontent.com/115156545/331817228-0533be52-22c6-481d-bec9-957b73207edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODY3MTMsIm5iZiI6MTcxNjA4NjQxMywicGF0aCI6Ii8xMTUxNTY1NDUvMzMxODE3MjI4LTA1MzNiZTUyLTIyYzYtNDgxZC1iZWM5LTk1N2I3MzIwN2VkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQwMjQwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVmYmVhMmY0MDc4ZTU3NjYzNmVkMTgzOTIwMTNiZjAwYTlmNjA5NmI1OTI1MjM1Yzg1ODQ1NmE4Yjk5OTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sl5CLiOKyfb30flB_lq_GXFUUi2kpxt_l4HvtHCer_I) 我可以直接分一个动漫盘 也可以把动漫直接放到/video下，只需要映射了video，后续可以在软件里面设置/video/动漫就可以
> 
> 还有您这么做，mp下载文件夹怎么设置？那个我看只能设置一个，没法设置第二个文件夹，比如你图里动漫在动漫文件夹，电影如果在media1文件夹，mp里怎么设置把内容下到这两个不同文件夹里，其实我就这里看不懂，因为它的下载文件夹只能填一个，比如以你的图为例子，我填了/media1，它后面有三个，电影 动漫 电视剧文件夹是不是只能填/media1文件夹下的文件夹？还是我可以无视这个必填的下载文件夹，直接动漫那里填/动漫
是的软件里可以单独设置下载路径的，我上面说过的 
你看她描述“设置单独下载保存目录”你只要把你想下载的文件映射进去就行了。
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/8e830cf7-f006-4897-bf13-faa13759005d)
