### ISSUE TITLE
[错误报告]: 同步cookiecloud一直报错

### ISSUE THREAD

**Issue by ChenArno** [jxxghp/MoviePilot#2102]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

定时任务 cookiecloud 执行失败：'str' object has no attribute 'get' - Traceback (most recent call last):

### 发生问题时系统日志和配置文件

```bash
用了群晖的cookiecloude
```

**Comment by jxxghp** [comment]
提供完整日志

**Comment by makabakg** [comment]
同样错误，目前有解决方法了吗
