### ISSUE TITLE
[错误报告]: FileTransferModule 模块执行出错

### ISSUE THREAD

**Issue by Aqr-K** [jxxghp/MoviePilot#2106]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载庆余年2的时候，下载文件成功，后台的文件夹也有刮削成功的文件，理论上来说这整个任务应该是完成了，但是最终的结果无法汇报并记录，历史记录里是没有关于这次下载的内容

### 发生问题时系统日志和配置文件

```bash
ERROR:   chain - 运行模块 media_exists 出错：FileTransferModule - Encountered unknown tag 'endif'.
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 101, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 777, in media_exists
    rel_path = self.get_rename_path(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/filetransfer/__init__.py", line 683, in get_rename_path
    template = Template(template_string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1211, in __new__
    return env.from_string(source, template_class=cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1108, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
```

**Comment by jxxghp** [comment]
@Aqr-K 这不明显是你的自定义命名规则语法错误吗？

**Comment by Aqr-K** [comment]
感谢解答，我检查了一下，确实是语法错了，明明以前改成过最新的版本的，不知道是怎么回事，它自己退回到了古早的没有{% endif %}的语法版本了，之前没下载电视剧就没报错

**Comment by Aqr-K** [comment]
顺便求教一下，现在的插件支持上传文件吗？
我写一个小插件，调用VFileInput的时候发现，该组件API直接json格式的话，

在网页里只是实现打开了文件上传的文件管理器，并上传到浏览器缓存里，但是插脚后台获取到的数据是个{}的空值，
我查了一下其他插件，暂时没有找到同类型的使用了文件上传的插件，请教一下怎么解决？需要绑定events事件吗？
```
                                    {
                                        'component': 'VFileInput',
                                        'props': {
                                            'model': 'file',
                                            'label': '上传配置文件',
                                            'show-size': '1024',
                                            'small-chips': True,
                                        },
                                    }
```

**Comment by jxxghp** [comment]
> 顺便求教一下，现在的插件支持上传文件吗？ 我写一个小插件，调用VFileInput的时候发现，该组件API直接json格式的话，
> 
> 在网页里只是实现打开了文件上传的文件管理器，并上传到浏览器缓存里，但是插脚后台获取到的数据是个{}的空值， 我查了一下其他插件，暂时没有找到同类型的使用了文件上传的插件，请教一下怎么解决？需要绑定events事件吗？
> 
> ```
>                                     {
>                                         'component': 'VFileInput',
>                                         'props': {
>                                             'model': 'file',
>                                             'label': '上传配置文件',
>                                             'show-size': '1024',
>                                             'small-chips': True,
>                                         },
>                                     }
> ```

目前应该是不支持，插件自己实现的API可以支持文件上传，但是UI配置后可能无法实现调用。
