### ISSUE TITLE
整理失败

### ISSUE THREAD

**Issue by W1lsp0** [jxxghp/MoviePilot#2107]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在整理完成后，历史记录没有显示，注意这个地方整理的是第1集，且是在下午4点整理的，历史记录最新的是在下午3.30。
现在整理无法选择季度，因为有一些源季度为错误的需要手动指定季度。
![image](https://github.com/jxxghp/MoviePilot/assets/57605626/1846cba2-df7f-4752-943a-332c3739d1ad)
![image](https://github.com/jxxghp/MoviePilot/assets/57605626/185fdc61-8764-4dc6-9d5b-050a54038ffe)

**Comment by jxxghp** [comment]
提问题贴日志
