### ISSUE TITLE
[错误报告]: 清理硬链接插件出现的问题

### ISSUE THREAD

**Issue by szdino** [jxxghp/MoviePilot#2108]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

目录设置：
  - 源文件目录：/media/downloads/complete
  - 硬链接目录：/media/link

清理硬链接插件设置：
  - 将上述两个目录均填入 “监控目录”，其他留空。

问题：
  - 从源文件目录删除文件时，对应的硬链接目录没有同步删除。
  - 当MP主程序文件刮削错误，重新手动整理，此时操作步骤应是将刮削错误硬链接文件删除，同时建立刮削正确的新硬链接文件。但实际操作中，在删除刮削错误硬链接文件时，就同步删除了源文件。。。
  - 若将源文件目录填写入 “不删除目录” ，则在上面的手动整理操作中，可顺利完成。但会导致删除硬链接目录时，对应的源文件目录保持不变，没有达到同步删除的目的。
  - 对插件设置上有什么理解错误还是程序的逻辑问题？

感谢作者的辛苦付出，多谢指导！

**Comment by jxxghp** [comment]
重新整理应该通过历史记录处理，会自动处理旧目录。
插件的想法请找插件作者讨论。

**Comment by szdino** [comment]
我是通过历史记录重新整理的。自动处理旧目录时，同步删除了源文件，所以建立新的硬链接目录就会提示找不到源文件。

**Comment by anooki-c** [comment]
> 我是通过历史记录重新整理的。自动处理旧目录时，同步删除了源文件，所以建立新的硬链接目录就会提示找不到源文件。

我也碰到这个问题
