### ISSUE TITLE
[订阅问题]: 媒体季详情展示问题

### ISSUE THREAD

**Issue by wylc12138** [jxxghp/MoviePilot#2111]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.9

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

奔跑吧兄弟季订阅问题，tmdb中为奔跑吧兄弟共计4季，奔跑吧共计8季，当前应为奔跑吧第8季，订阅最新季时为S12，导致无法正常匹配资源下载。
![WX20240518-232221@2x](https://github.com/jxxghp/MoviePilot/assets/49614071/a43715b5-4f34-4863-a478-de8e29650ca5)
![WX20240518-232539@2x](https://github.com/jxxghp/MoviePilot/assets/49614071/b381b1ef-4e5c-4117-adf7-98892dd1135e)
![WX20240518-232549@2x](https://github.com/jxxghp/MoviePilot/assets/49614071/b428c705-22d1-4763-bdae-4d8d109a009e)

**Comment by cng10001** [comment]
加这2个试试
Keep.Running.S08E => Keep.Running.S12E
Keep Running S08 2024 => Keep Running S12 2024

**Comment by jxxghp** [comment]
themoviedb的数据问题，提这个项目的问题有什么用？
