### ISSUE TITLE
[错误报告]: 标题带有集数的无法订阅成功，只能匹配到对应资源，不会自动下载

### ISSUE THREAD

**Issue by XiaYi1002** [jxxghp/MoviePilot#2112]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.8.9

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

搜索规则和订阅规则相同的情况下，标题带有集数的无法订阅成功，只能匹配到对应资源，不会自动下载，容器镜像删除重新拉取，依旧是这个样子，也没有明确的错误提示（未修改过识别词）
Joy of Life S02 2019 1080p DSNP WEB-DL AAC2 0 H264（此可正常订阅下载）
Joy of Life S02E08 2024 1080p DSNP WEB-DL H264 AAC-DramaS（此能匹配到资源，但不会添加下载，也没有明确的错误提示）Joy of Life S02E07 2024 1080p WeTV WEB-DL H264 AAC（此能匹配到资源，但不会添加下载，也没有明确的错误提示）

### 发生问题时系统日志和配置文件

```bash
以下就是匹配到对应资源，但是没有进行提交下载，并无明确的错误提示

以下就是匹配到对应资源，但是没有

【ERROR】2024-05-18 23:42:59,181 - browser.py - 获取网页源码失败: Timeout 30000ms exceeded.
【INFO】2024-05-18 23:42:41,458 - subscribe.py - 庆余年 (2019) 季 2 更新缺失集数为36 ...
【INFO】2024-05-18 23:42:41,457 - subscribe.py - 庆余年 (2019) 未下载完整，继续订阅 ...
【INFO】2024-05-18 23:42:41,451 - search.py - 优先级规则/剧集过滤完成，剩余 8 个资源
【INFO】2024-05-18 23:42:41,450 - filter - 种子 人人人 - Joy of Life 2019 S01 WEB-DL 2160p H265 AAC-ADWeb 包含季 [1] 不是需要的季 dict_keys([2])
【INFO】2024-05-18 23:42:41,449 - filter - 种子 人人人 - Joy of Life S02E02 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,448 - filter - 种子 人人人 - Joy of Life S02E03 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,446 - filter - 种子 人人人 - Joy of Life S02E04 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,445 - filter - 种子 人人人 - Joy of Life S02E01 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,443 - filter - 种子 人人人 - Joy of Life S02E05 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,442 - filter - 种子 人人人 - Joy of Life S02E07 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,441 - filter - 种子 人人人 - Joy of Life S02E06 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,439 - filter - 种子 人人人 - Joy of Life S02E08 2024 1080p DSNP WEB-DL H264 AAC-DramaS 优先级为 1
【INFO】2024-05-18 23:42:41,436 - search.py - 开始优先级规则/剧集过滤，当前规则： CNSUB  ...
【INFO】2024-05-18 23:42:41,435 - search.py - 过滤规则过滤完成，剩余 9 个资源
```

**Comment by cng10001** [comment]
【ERROR】2024-05-18 23:42:59,181 - browser.py - 获取网页源码失败: Timeout 30000ms exceeded.
有个报错
最好有个人人人的帮你试试哈哈

**Comment by XiaYi1002** [comment]
> 【ERROR】2024-05-18 23：42：59,181 - browser.py - 获取网页源码失败： Timeout 30000ms exceededed. 有个报错 最好有个人人人的帮你试试哈哈

我最早是使用堡，出现这个问题，就换了人人人做了测试，那个错误，只是不巧碰到了，但是后面的是没有的，

**Comment by jxxghp** [comment]
有没有设置其它的过滤项？ 这处种子的副标题也贴一下。
另外现在日志太少，我DEV加了些日志。

**Comment by XiaYi1002** [comment]
> 有没有设置其它的过滤项？ 这个种子的副标题也贴一下。 另外现在日志太少，我DEV加了些日志。

[LOG.txt](https://github.com/jxxghp/MoviePilot/files/15367470/LOG.txt)
这是我开了dev，所生成的日志，好像跟没开dev差不多哦

**Comment by jxxghp** [comment]
@XiaYi1002 是要更新到dev分支

**Comment by XiaYi1002** [comment]
> @XiaYi1002 是要更新到dev分支

[devlog.txt](https://github.com/jxxghp/MoviePilot/files/15367490/devlog.txt)
已切换到dev分支，这是搜索后的log，优先级 那里 我只有勾选了 中文字幕 订阅规则 填了 包含 DV 和 开始集数 7

**Comment by InfinityPacer** [comment]
log文件只会记录info日志，如果需要看debug日志，需要使用Console，或者修改 app.log.py中的setup_logger
```python
file_handler.setLevel(logging.DEBUG)
```

**Comment by InfinityPacer** [comment]
@InfinityPacer

**Comment by XiaYi1002** [comment]
> log文件只会记录info日志，如果需要看debug日志，需要使用Console，或者修改 app.log.py中的setup_logger
> 
> ```python
> file_handler.setLevel(logging.DEBUG)
> ```

好吧 这确实超出能力范围了  嘿嘿

**Comment by jxxghp** [comment]
程序逻辑核对了下没有错误。
在MP里的名称识别测试，试一下这个名字识别的是什么ID，正常应该是`95842 `，但tmdb里有两个词条，刚好这个种子年份是写的2024，我怀疑你的订阅识别缓存是识别为了第二条 `254676 ` 了。

可以清理一下缓存再试一下。

<img width="837" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/49466e74-d25c-4aa6-8ea6-23b2a3cf606d">
<img width="1257" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/501c156b-6030-40c6-8a6f-ec1d13bd547e">

**Comment by cng10001** [comment]
我没有人人人 但是根据你下面两个无法下载的标题，实际都能订阅到
**Joy of Life S02E08 2024 1080p DSNP WEB-DL H264 AAC-DramaS** 
_可在馒头订阅到_
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/c44f2676-93b5-4966-8b10-b3f650055898)

**Joy of Life S02E07 2024 1080p WeTV WEB-DL H264 AAC** 
_是we-dl wetv ob发布组的种子_
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/81425c67-263f-4e8a-b571-1622017661b8)
