### ISSUE TITLE
Emby发给MoviePilot的webhook的消息是空的。。。是哪里的设置不对？求教

### ISSUE THREAD

**Issue by 705058548** [jxxghp/MoviePilot#2114]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Emby发给MoviePilot的webhook的消息是空的。。。是哪里的设置不对？求教
Emby与MoviePilot之间的通信是通的，能收到消息，但是空的     webhook.message - []
3000和3001的端口，都是空的
![QQ截图20240519105728](https://github.com/jxxghp/MoviePilot/assets/125120868/c1c2144e-a1ae-48b2-b2f8-3498f17bd6aa)
![QQ截图20240519105747](https://github.com/jxxghp/MoviePilot/assets/125120868/b7de938d-7a18-496f-97a6-15dd1878644b)
![QQ截图20240519105759](https://github.com/jxxghp/MoviePilot/assets/125120868/cd5e6cb1-7443-431c-aea8-ece0230d07da)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-05-19 10:53:01,767 - command.py - 处理事件：webhook.message - []
```

**Comment by jxxghp** [comment]
不是收到的是空的，而是你现在没有安装和开启能处理这个事件的插件。

**Comment by 705058548** [comment]
哦哦，原来是需要安装  媒体服务器 通知，才可以啊，多些前辈
