### ISSUE TITLE
[Feature Request]: 希望添加“刮削元数据及图片”的开/关功能

### ISSUE THREAD

**Issue by samuncleorange** [jxxghp/MoviePilot#2121]
### 当前程序版本

1.8.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

这个功能是nastools有的，希望作者大大能够加回来。
我的场景却是比较小众，这个不痛不痒的功能对我来说却是刚需，所以就一直坚持nt没升级。

**Comment by ainas999** [comment]
> ### 当前程序版本
> 1.8.9
> 
> ### 运行环境
> Docker
> 
> ### 功能改进类型
> 主程序
> 
> ### 功能改进
> 这个功能是nastools有的，希望作者大大能够加回来。 我的场景却是比较小众，这个不痛不痒的功能对我来说却是刚需，所以就一直坚持nt没升级。
> 
> ### 参考资料
> _No response_

在设定---系统里面有选项的：自动刮削媒体信息

**Comment by samuncleorange** [comment]
> > ### 当前程序版本
> > 1.8.9
> > ### 运行环境
> > Docker
> > ### 功能改进类型
> > 主程序
> > ### 功能改进
> > 这个功能是nastools有的，希望作者大大能够加回来。 我的场景却是比较小众，这个不痛不痒的功能对我来说却是刚需，所以就一直坚持nt没升级。
> > ### 参考资料
> > _No response_
> 
> 在设定---系统里面有选项的：自动刮削媒体信息

现在没有“系统”了，怎么办
