### ISSUE TITLE
[Feature Request]: 全新架构PT站YemaPT欢迎适配

### ISSUE THREAD

**Issue by yamapt** [jxxghp/MoviePilot#2123]
### 当前程序版本

最新

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

尊敬的MoviePilot作者，您好：
我是YemaPT的站长，本站从2023年开始开发，于5月1号正式上线运行。由于是新架构，和np不兼容，目前还不支持MoviePilot，站内的用户都希望能够适配影视墙。因此特开一个issue，希望能和您一起共建，具体来说，我这边能够给您提供账号、接口文档，如果有需要可以给您单独提供新接口。

希望得到您的回复~

### 参考资料

无

**Comment by jxxghp** [comment]
@yamapt 请tg联系 jxxghp

**Comment by BigDaBoluo** [comment]
站长，可以发个邀请码么 838797782@qq.com
