### ISSUE TITLE
[错误报告]: 下载目录不符

### ISSUE THREAD

**Issue by xxtyyq** [jxxghp/MoviePilot#2126]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

QB里设置的默认下载目录为/volume2/video/下载/手动
MP里设置的下载目录为/volume2/video/下载
MP里设置的电影下载目录为/volume2/video/下载/电影，以此类推电视剧和动漫的目录
可是不管订阅下载还是直接搜索下载，都会按照QB默认路径下载，比如下载欧美剧，下载目录就成了/volume2/video/下载/手动/欧美剧
不知道哪里设置问题？
NT里我也是这么设置的，一直没有发生这种情况
麻烦帮忙看下，谢谢！

**Comment by jxxghp** [comment]
QB开了自动管理？
这种问题自己研究下，属于基础功能都多久没变化过了。界面上的小字认真看，有问题大家都有问题！

**Comment by xxtyyq** [comment]
找到了，是MP中QB的自动分类管理不能开，谢谢
