### ISSUE TITLE
[Feature Request]: 希望添加订阅功能的自动下载开关

### ISSUE THREAD

**Issue by Qm-jmz** [jxxghp/MoviePilot#2129]
### 当前程序版本

v1.8.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前订阅的默认逻辑似乎会自动下载种子，但有时候识别错误会导致下载的种子不对，希望添加订阅功能的自动下载开关，以实现订阅只负责自动推送种子到下载器，而后在下载器人工审核是否下载该种子。

**Comment by dlovew** [comment]
直接在下载器设置不自动开始多简单

**Comment by Qm-jmz** [comment]
> 直接在下载器设置不自动开始多简单

事实是我下载器的设置一直是不自动
![image](https://github.com/jxxghp/MoviePilot/assets/50917637/f79300b7-6a59-4083-8e0e-bedb47527040)
