### ISSUE TITLE
[错误报告]: 合集类文件无法正确整理

### ISSUE THREAD

**Issue by awyer-song** [jxxghp/MoviePilot#2131]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.0

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

下载了几个合集类的文件，文件夹内有3个文件，但目录监控只刮削整理其中一个，并提示“已有质量更好文件”

**Comment by jxxghp** [comment]
你要贴出你的目录结构文件名、日志，不然不知道在说的啥

**Comment by awyer-song** [comment]
当文件整理完成后，历史记录提示如图：
![1](https://github.com/jxxghp/MoviePilot/assets/28851569/1ad7bbca-88ed-4c32-85ca-32fc2896890a)
mp将第二部的文件整理好后，检测到第三部的文件质量更优，所以做了替换；再想整理第一部的文件时，因质量不如第三部的文件，所以入库失败，提示“媒体库中已存在，且质量更好”

实际下载目录结构如下：
![2](https://github.com/jxxghp/MoviePilot/assets/28851569/ec2b06ca-e03f-4ab3-9aa4-277a7d019d9d)

整理后目录结构如下，文件为第三部的文件：
![3](https://github.com/jxxghp/MoviePilot/assets/28851569/36d96102-2f78-496c-a70f-f10543d94d81)

**Comment by jxxghp** [comment]
作这是同一部电影，要都保留你要改重命名规则，加上可以区分命名的要素。

**Comment by awyer-song** [comment]
> 你这是同一部电影，要都保留你要改重命名规则，加上可以区分命名的要素。

再次测试了一遍，使用MP自带的入库是没问题的，使用插件“目录监控”是不行的。
感谢dev回复，谢谢。
