### ISSUE TITLE
[Feature Request]: Plex部分刷新

### ISSUE THREAD

**Issue by BrettDean** [jxxghp/MoviePilot#2132]
### 当前程序版本

v1.9.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

`媒体库服务器刷新`对plex部分刷新的支持
目前插件好像是整体刷新，部分刷新可以通过api调用

---

### Partially Scan a Library

If the content location you have specified for a library has subdirectories, then it’s possible to specify a particular path to use for the action. This requires Plex Media Server version 1.20.0.3125 or newer. For instance, we saw earlier that the “Movies” library had `/Users/plexuser/Movies/Media/Movies` specified as the content location.

Now, imagine that the user has subdirectories under that for different resolution content (e.g. `.../Media/Movies/720p` and `.../Media/Movies/1080p`). It’s possible to tell the server to scan only a particular subdirectory.

- Determine the Library ID to scan
- For example, the **Movies** library above has an ID=29
- Know the path of the subdirectory of the content location you wish to scan

```
http://[PMS_IP_ADDRESS]:32400/library/sections/29/refresh?path=/Users/plexuser/Movies/Media/Movies/1080p&X-Plex-Token=YourTokenGoesHere
```

**Tip!**: If you’re using the URL in a script or app, you need to make sure that you “URL Encode” the path you specify first. If you’re using this in a browser address bar, then the browser will automatically do so for you.

### 参考资料

https://support.plex.tv/articles/201638786-plex-media-server-url-commands/

文章最后`Partially Scan a Library`部分

**Comment by jxxghp** [comment]
现在的代码逻辑中包含了按库刷新：
```
    def refresh_library_by_items(self, items: List[schemas.RefreshMediaItem]) -> bool:
        """
        按路径刷新媒体库 item: target_path
        """
        if not self._plex:
            return False
        result_dict = {}
        for item in items:
            file_path = item.target_path
            lib_key, path = self.__find_librarie(file_path, self._libraries)
            # 如果存在同一剧集的多集,key(path)相同会合并
            result_dict[path] = lib_key
        if "" in result_dict:
            # 如果有匹配失败的,刷新整个库
            self._plex.library.update()
        else:
            # 否则一个一个刷新
            for path, lib_key in result_dict.items():
                logger.info(f"刷新媒体库：{lib_key} - {path}")
                self._plex.query(f'/library/sections/{lib_key}/refresh?path={quote_plus(path)}')
```
