### ISSUE TITLE
[错误报告]: 站点仿真问题

### ISSUE THREAD

**Issue by BackspaceM** [jxxghp/MoviePilot#2133]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.0

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

因最近新增天气插件，通过插件日志查看始终无法截图，于是换了个思路，发现站点在开启仿真后，均无法浏览站点（种子列表），已尝试降级1.8.7然后1.8.8再升级回来，也删除过.cache触发重新下载浏览器内核，但还未解决，希望大佬有空时候帮助小第一波（下方日志域名已替换为中文）

### 发生问题时系统日志和配置文件

MP日志：
【WARNING】2024-05-21 12:53:14,119 - indexer - 我堡 未搜索到数据，耗时 7 秒
【INFO】2024-05-21 12:53:07,038 - spider.py - 开始请求：https://我堡.club/torrents.php
【INFO】2024-05-21 12:53:07,026 - torrents.py - 开始获取站点 ourbits.club 最新种子 ...
【WARNING】2024-05-21 12:53:04,739 - indexer - 猫站 未搜索到数据，耗时 9 秒
【INFO】2024-05-21 12:52:55,259 - spider.py - 开始请求：https://猫站.com/torrents.php
【INFO】2024-05-21 12:52:55,244 - torrents.py - 开始获取站点 pterclub.com 最新种子 ...
【WARNING】2024-05-21 12:52:52,626 - indexer - 天空 未搜索到数据，耗时 9 秒
【INFO】2024-05-21 12:52:42,617 - spider.py - 开始请求：https://天空.me/torrents.php
【INFO】2024-05-21 12:52:42,601 - torrents.py - 开始获取站点 hdsky.me 最新种子 ...
【WARNING】2024-05-21 12:52:09,823 - indexer - 人人人 未搜索到数据，耗时 21 秒
【INFO】2024-05-21 12:51:48,448 - spider.py - 开始请求：https://人人人.me/torrents.php
【INFO】2024-05-21 12:51:48,434 - torrents.py - 开始获取站点 audiences.me 最新种子 ...

天气日志：
【INFO】2024-05-21 12:12:47,436 - weatherwidget - 运行完毕，用时 70.852274 秒
【INFO】2024-05-21 12:12:47,199 - weatherwidget - 截图记录更新，发生错误，最后一次截图时间重置为None

navigating to "https://www.qweather.com/weather/qinhuai-101190109.html", waiting until "load"

【ERROR】2024-05-21 12:12:47,171 - weatherwidget - desktop 截图失败，URL: https://www.qweather.com/weather/qinhuai-101190109.html, 错误：Timeout 30000ms exceeded.
【INFO】2024-05-21 12:12:16,410 - weatherwidget - 截图记录更新，最后一次截图时间重置为 2024-05-21 12:12:16
【INFO】2024-05-21 12:12:16,405 - weatherwidget - 开始加载 desktop 页面: https://www.qweather.com/weather/qinhuai-101190109.html
【INFO】2024-05-21 12:12:16,400 - weatherwidget - desktop 正在启动 screenshot ...
【INFO】2024-05-21 12:12:16,395 - weatherwidget - 运行完毕，用时 39.818041 秒
【INFO】2024-05-21 12:12:16,030 - weatherwidget - 截图记录更新，发生错误，最后一次截图时间重置为None

navigating to "https://www.qweather.com/weather/qinhuai-101190109.html", waiting until "load"

【ERROR】2024-05-21 12:12:16,023 - weatherwidget - mobile 截图失败，URL: https://www.qweather.com/weather/qinhuai-101190109.html, 错误：Timeout 30000ms exceeded.
【INFO】2024-05-21 12:11:42,638 - weatherwidget - 截图记录更新，最后一次截图时间重置为 2024-05-21 12:11:42
【INFO】2024-05-21 12:11:42,631 - weatherwidget - 开始加载 mobile 页面: https://www.qweather.com/weather/qinhuai-101190109.html
【INFO】2024-05-21 12:11:42,628 - weatherwidget - mobile 正在启动 screenshot ...
【INFO】2024-05-21 12:11:36,575 - weatherwidget - 截图记录更新，最后一次截图时间重置为 2024-05-21 12:11:32
【INFO】2024-05-21 12:11:36,573 - weatherwidget - 正在准备截图服务，playwright服务启动中
【INFO】2024-05-21 12:11:32,785 - weatherwidget - 截图记录更新，最后一次截图时间重置为 2024-05-21 12:11:32
【INFO】2024-05-21 11:33:40,867 - weatherwidget - 运行完毕，用时 69.64179 秒
【INFO】2024-05-21 11:33:40,824 - weatherwidget - 截图记录更新，发生错误，最后一次截图时间重置为None

**Comment by jxxghp** [comment]
这是环境问题，重新拉镜像重置，删除/moviepilot映射目录，重启重新下载内核。

**Comment by BackspaceM** [comment]
> 这是环境问题，重新拉镜像重置，删除/moviepilot映射目录，重启重新下载内核。

已重拉亦已重建，但是问题依旧，目前用的设备是威联通，不知道是不是跟这个有关，另外一个是vware workstation pro新建的黑裙也是一样
