### ISSUE TITLE
[错误报告]: 搜索过滤严重BUG，可多人多版本复现。

### ISSUE THREAD

**Issue by kimcaiyuan** [jxxghp/MoviePilot#2136]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索栏中搜索 碰撞搜查线 这部韩剧并点击放大镜开始搜索站点资源 可以搜索出很多其他不相关资源，
且在识别词中添加识别词后，会起到反效果，搜到更多其他资源。
env中有一项 模糊搜索的选项，默认打开，也尝试了关闭，没有效果
在NT中没有任何问题。
![photo_2024-05-21_21-36-50](https://github.com/jxxghp/MoviePilot/assets/166335432/3496f010-93d9-4a1c-bfc0-77dc27e1a95d)
![photo_2024-05-21_21-38-39](https://github.com/jxxghp/MoviePilot/assets/166335432/937ad78f-cc18-4cdf-bf00-1fed5654266e)
![photo_2024-05-21_21-36-36](https://github.com/jxxghp/MoviePilot/assets/166335432/d84aae27-dbee-40e5-ad85-dbfde99b9002)
![photo_2024-05-21_21-35-50](https://github.com/jxxghp/MoviePilot/assets/166335432/c2f4de9c-c349-4ece-98bf-0cb2648ca1c2)
![photo_2024-05-21_21-37-42](https://github.com/jxxghp/MoviePilot/assets/166335432/7b1ff348-2d6f-4a89-a340-75e27f40d7f9)

### 发生问题时系统日志和配置文件

```bash
运行日志你自己试一次就有了，不是个人问题。已经让多人多版本验证过了 1.9.0 1.8.9 都存在
我看日志是先去站点搜索资源 ，然后再进行关键词匹配，这样会造成搜索到站点很多正确的资源。

感觉现在的搜索逻辑很有问题。
既然是 搜索栏里输入影片名称之后 关联到TMDB，从TMDB那获取 影片年份 别名 影片原产地名称， 
不应该是先拿 影片名称+年份去 各个站点搜索才对么？ 这样应该能避免掉很多误搜吧？
```

**Comment by jxxghp** [comment]
@kimcaiyuan 这个剧的别名Crash过短导致误匹配了，你还识别词改成Crash，这当然更严重了。。。
Dev分支代码已经改过了，应该修好了。

**Comment by kimcaiyuan** [comment]
> @kimcaiyuan 这个剧的别名Crash过短导致误匹配了，你还识别词改成Crash，这当然更严重了。。。 Dev分支代码已经改过了，应该修好了。

因为这个剧的英文名字就叫Crash，所以我在识别词那里这样写的， 我以为是 把Crash替换成碰撞搜查线。

总之 谢谢大佬及时解决
