### ISSUE TITLE
[错误报告]: 系统健康检查 Transmission 从未检查到过

### ISSUE THREAD

**Issue by kimcaiyuan** [jxxghp/MoviePilot#2137]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

这个问题虽然不影响使用，但是一直都存在，如图 从这个功能推出的时候就这样。
具体原因不明。但是询问过别人好像是可以检测的到。
![2024-05-21_22-02-13](https://github.com/jxxghp/MoviePilot/assets/166335432/f78bb2e8-86e4-43f2-b92c-53f967a613d8)
![2024-05-21_22-02-44](https://github.com/jxxghp/MoviePilot/assets/166335432/adcac472-b188-46d0-9893-2e18404b3c9a)
![2024-05-21_22-03-08](https://github.com/jxxghp/MoviePilot/assets/166335432/46c2618c-83b2-4409-b863-ec0c3f6da7f0)
![2024-05-21_22-04-54](https://github.com/jxxghp/MoviePilot/assets/166335432/1c53e32b-a90d-4d45-833e-92e3b89c9ddd)

**Comment by jxxghp** [comment]
下载器设置里选上。
