### ISSUE TITLE
无法搜索是为什么呢？

### ISSUE THREAD

**Issue by chenhao2424** [jxxghp/MoviePilot#2138]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

大佬好，在mp主界面的上方搜索框内，如果直接搜索某个节目或者电影，就会进入无限转圈圈如图所示的状态，不知道这个是正常还是有问题？该怎么解决？尝试重建了容器也依然如此。

感谢大佬写出mp，真的方便很多。感谢。

![CleanShot 2024-05-22 at 00 16 57](https://github.com/jxxghp/MoviePilot/assets/13376049/974071f5-2244-4e30-8670-bba10e858e9e)

**Comment by cng10001** [comment]
强制刷新浏览器缓存 或者在无痕模式下试试

**Comment by chenhao2424** [comment]
> 强制刷新浏览器缓存 或者在无痕模式下试试

谢谢，确实可以了。
