### ISSUE TITLE
[Feature Request]: 希望搜索结果添加缓存

### ISSUE THREAD

**Issue by pogame** [jxxghp/MoviePilot#2145]
### 当前程序版本

1.9.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

现状：每次搜索完成添加下载，跳转正在下载页查看下载进度后，再次返回搜索结果页会导致重新触发搜索。
建议：搜索结果添加缓存，每次进入展示上次搜索结果的缓存，防止每次进入搜索都会请求数据，响应慢且易导致请求频繁。

**Comment by cng10001** [comment]
其实是有缓存的，你昨天搜索的这个资源，今天打开能直接显示，但是你说的这个情况也是存在的，搜索后直接后退感觉还是又搜索了一遍。
具体什么逻辑呢，能不能请开发大佬能不能再梳理一下

**Comment by sq8422779** [comment]
> 其实是有缓存的，你昨天搜索的这个资源，今天打开能直接显示，但是你说的这个情况也是存在的，搜索后直接后退感觉还是又搜索了一遍。 具体什么逻辑呢，能不能请开发大佬能不能再梳理一下

不能点返回，要在下拉菜单里点资源搜索

**Comment by pogame** [comment]
> > 其实是有缓存的，你昨天搜索的这个资源，今天打开能直接显示，但是你说的这个情况也是存在的，搜索后直接后退感觉还是又搜索了一遍。 具体什么逻辑呢，能不能请开发大佬能不能再梳理一下
> 
> 不能点返回，要在下拉菜单里点资源搜索

啊，我试了下，发现原来搜索页用的GET请求，怪不得后退操作又搜索一次。。
