### ISSUE TITLE
[错误报告]: 未升级系统，直接升级插件，导致系统错误无法进入

### ISSUE THREAD

**Issue by zhnnan** [jxxghp/MoviePilot#2150]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

升级了签到插件和刷流插件，重启系统无法进入
后台日志显示无法获取系统版本，重复锁死（重装了，具体内容没了）

**Comment by zhnnan** [comment]
不使用代理更新程序
Release 更新模式
当前版本号：v1.9.0
最新版本号：v1.9.0
未发现新版本，跳过更新步骤...
usermod: no changes
Traceback (most recent call last):
  File "/app/app/main.py", line 23, in <module>
    from app.core.plugin import PluginManager
  File "/app/app/core/plugin.py", line 19, in <module>
    from app.helper.sites import SitesHelper
ModuleNotFoundError: No module named 'app.helper.sites'

**Comment by jxxghp** [comment]
是不是开了重启自动更新？
这种情况是网络不好，连github下载升级文件时中断了，文件损坏。

**Comment by zhnnan** [comment]
好的，我把这个设置关上
