### ISSUE TITLE
[Feature Request]: 求助企业微信可信IP的问题

### ISSUE THREAD

**Issue by zhaoyanxiang** [jxxghp/MoviePilot#2152]
### 当前程序版本

1.9.0

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

我家不是固定ip，所以路由器重启后ip就变了，导致自建企业微信应用就失效了
但是我有一台固定ip的服务器，如何可以设置让企业微信先推送消息到我的服务器，再转发消息到我的nas下呢，nginx转发可以实现吗，求教该怎么配置

**Comment by ThierryCheng** [comment]
https://pt-helper.notion.site/50a7b44e255d40109bd7ad474abfeba5
