### ISSUE TITLE
[Feature Request]: 希望支持站点ToSky

### ISSUE THREAD

**Issue by halehal** [jxxghp/MoviePilot#2153]
### 当前程序版本

1.9.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望添加站点ToSky 地址：https://t.tosky.club/ ，标准nexusphp框架，Movie，TV，分类id均未变动

**Comment by kingcard1131** [comment]
同希望

**Comment by jxxghp** [comment]
给我弄个账号，马上适配。

**Comment by kingcard1131** [comment]
已联系站长给您开个养老号

**Comment by jxxghp** [comment]
@kingcard1131 邮箱 jxxghp@gmail.com
