### ISSUE TITLE
[Feature Request]: 在站点管理界面，希望可以通过拖动调整站点的顺序来调整站点优先级，比较直观和高效！

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#2159]
### 当前程序版本

前端版本：v1.9.0，后端版本：v19.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

在站点管理界面，希望可以通过拖动调整站点的顺序来调整站点优先级，比较直观和高效！

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/52cf517a910c78b1108a880257f700bf0c42f27c

**Comment by mayziran** [comment]
> [jxxghp/MoviePilot-Frontend@52cf517](https://github.com/jxxghp/MoviePilot-Frontend/commit/52cf517a910c78b1108a880257f700bf0c42f27c)

v2好像拖动以后会弹回去
