### ISSUE TITLE
[Feature Request]: 目录监控的逻辑能否修改

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [jxxghp/MoviePilot#2163]
### 当前程序版本

v1.9.1-beta

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

现版本的目录监控只有不指定目的目录才能使用二级，但比如我有两个盘，盘1和盘2,我下到了盘2的资源肯定希望它硬连接到盘2，但是如果盘1的媒体库目录在前面就会优先转移到盘1了，个人认为这个逻辑不太好，而且此处会显示是由盘2硬连接到盘1的
![image](https://github.com/jxxghp/MoviePilot/assets/78670748/a6f5a1ba-7174-480e-a15a-a88f5ff83ad8)

**Comment by Putarku** [comment]
你可以在媒体库目录里面加一个盘2的地址，这样就会转移到盘2了。

**Comment by SchrodingerBarbatos** [comment]
> 你可以在媒体库目录里面加一个盘2的地址，这样就会转移到盘2了。

不会啊，如果盘1的媒体库目录排在盘2前面就会优先转移到盘1

**Comment by jxxghp** [comment]
主框架设定我加了个同盘优先的开关，这个插件不改了。
