### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by Putarku** [jxxghp/MoviePilot#2165]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.1-beta

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

历史记录中使用重新整理不会再判定一次二级目录，而是按之前的错误目录重新刮削整理。
只有删除历史记录，进文件管理中手动触发一次整理，才能按正确的目录转移。

**Comment by jxxghp** [comment]
@Putarku 清理浏览器缓存了吗？重新整理的时候，现在是默认目的路径那里是空的吧？

**Comment by jifengguo** [comment]
同样碰到，就是历史记录重新整理时，不会生成二级分类目录。必须删除历史记录，手动重新整理才可以。

**Comment by Putarku** [comment]
确认清理过了，另外还发现了和[#2163](https://github.com/jxxghp/MoviePilot/issues/2163)相同的问题。此前媒体库路径设置两个盘的根目录，自动整理时会往对应盘的媒体库内整理。但现在却变成了哪个目录的优先级高就往哪边传。
下面是我手动调整这两个电视剧目录以后的转移结果，哪个在前面就转到哪个目录了。
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/669ce099-bdd8-414a-ba13-3e0c5ff01984)
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/6f49ba1a-cf01-46b6-9e45-a5c537e28c87)

**Comment by jxxghp** [comment]
知道原因了，改了
