### ISSUE TITLE
[错误报告]: 动画电影会被分类到动漫的一级分类里

### ISSUE THREAD

**Issue by Kev1nT** [jxxghp/MoviePilot#2166]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/49979564/0d6cf1b9-f495-4a72-b63c-1279ab04b476)
![image](https://github.com/jxxghp/MoviePilot/assets/49979564/9bf943b5-c919-4331-83ec-34fbdc66ad74)
![image](https://github.com/jxxghp/MoviePilot/assets/49979564/5f3759e5-774c-4fc9-a1bb-f0df9a771ac2)
![image](https://github.com/jxxghp/MoviePilot/assets/49979564/62c51453-1871-4bbe-a167-c6905a8bd9f6)
![image](https://github.com/jxxghp/MoviePilot/assets/49979564/93b2c1a3-a46e-44f6-b726-ab6dc349a9b0)

尝试过多种策略，一种情况是这样分类到anime/动漫里，如果不自动分类的话，会提示找不到分类目录
实际上电影类型应该一级分类是电影才对，不应该分到anime/动漫里面

**Comment by ShawsonBian** [comment]
同样的问题

**Comment by qsxazcv** [comment]
一样
