### ISSUE TITLE
[错误报告]:补分浏览器版本没有目录设置选项，默认关闭自动分类

### ISSUE THREAD

**Issue by Enderiose** [jxxghp/MoviePilot#2174]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Telegram里搜到更新日志
```
【新版目录的设置示例】

* 假设根目录为：/video，存量的会自动更新不需要手工维护。

1、需要一二级自动分类

- 路径：/video
  类型：全部
  类别：全部
  自动分类：开
  
2、一级手动分类，二级自动分类

- 路径：/video/电影
  类型：电影
  类别：全部
  自动分类：开

- 路径：/video/电视剧
  类型：电视剧
  类别：全部
  自动分类：开
```
因为一级分类是默认关闭手动开启 
在 `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0`版本无法设置，没有目录选项
在`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`可以正常设置识别

其他功能都没有太影响使用

**Comment by cng10001** [comment]
啥意思
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/424c39f4-dad2-4856-9302-4e4215b4e2e8)
咋会跟浏览器版本有关系呢

**Comment by Enderiose** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月25日(周六) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [错误报告]:补分浏览器版本没有目录设置选项，默认关闭自动分类 (Issue #2174)




 
啥意思
 image.png (view on web)
 咋会跟浏览器版本有关系呢

**Comment by Enderiose** [comment]
<img width="1769" alt="mmexport1716608377505" src="https://github.com/jxxghp/MoviePilot/assets/7955819/28c08fc3-a9ee-4531-8d7e-2ae14e997bf7">
<img width="1646" alt="mmexport1716608383131" src="https://github.com/jxxghp/MoviePilot/assets/7955819/a2486ec5-022a-480b-be34-554819d9edf0">

**Comment by cng10001** [comment]
> <img alt="mmexport1716608377505" width="1769" src="https://private-user-images.githubusercontent.com/7955819/333769971-28c08fc3-a9ee-4531-8d7e-2ae14e997bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDkxNTUsIm5iZiI6MTcxNjYwODg1NSwicGF0aCI6Ii83OTU1ODE5LzMzMzc2OTk3MS0yOGMwOGZjMy1hOWVlLTQ1MzEtOGQ3ZS0yYWUxNGU5OTdiZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDM0NzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNjYjNkMTg0ZjY0YTM3MTFkOTc4NTBhNDRjOTFmODNlNWFiMmIzNzdkZjEyYmQ0NzU1ZTdjOGExNWU2YjIzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xQjS5CIEFpLBw6aro3NQTX7SYnla0q9Y6UXwLAAiMQw"> <img alt="mmexport1716608383131" width="1646" src="https://private-user-images.githubusercontent.com/7955819/333770039-a2486ec5-022a-480b-be34-554819d9edf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDkxNTUsIm5iZiI6MTcxNjYwODg1NSwicGF0aCI6Ii83OTU1ODE5LzMzMzc3MDAzOS1hMjQ4NmVjNS0wMjJhLTQ4MGItYmUzNC01NTQ4MTlkOWVkZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDM0NzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY5YzUyYTM0M2E4OGExMjVlOGJkODM2ZDg0MTk3ODEwMWY2NmQyYzkxOTFlYmZhMTM0ZGQ3NzgxZTNkMTg5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W8e_-4Y8s2lf4ofAhJuteTe-23Z2mHBZDVCFFyCKsk4">

你浏览器有没有强制刷新缓存啊

**Comment by Enderiose** [comment]
> > <img alt="mmexport1716608377505" width="1769" src="https://private-user-images.githubusercontent.com/7955819/333769971-28c08fc3-a9ee-4531-8d7e-2ae14e997bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDkxNTUsIm5iZiI6MTcxNjYwODg1NSwicGF0aCI6Ii83OTU1ODE5LzMzMzc2OTk3MS0yOGMwOGZjMy1hOWVlLTQ1MzEtOGQ3ZS0yYWUxNGU5OTdiZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDM0NzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjNjYjNkMTg0ZjY0YTM3MTFkOTc4NTBhNDRjOTFmODNlNWFiMmIzNzdkZjEyYmQ0NzU1ZTdjOGExNWU2YjIzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xQjS5CIEFpLBw6aro3NQTX7SYnla0q9Y6UXwLAAiMQw"> <img alt="mmexport1716608383131" width="1646" src="https://private-user-images.githubusercontent.com/7955819/333770039-a2486ec5-022a-480b-be34-554819d9edf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDkxNTUsIm5iZiI6MTcxNjYwODg1NSwicGF0aCI6Ii83OTU1ODE5LzMzMzc3MDAzOS1hMjQ4NmVjNS0wMjJhLTQ4MGItYmUzNC01NTQ4MTlkOWVkZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMDM0NzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY5YzUyYTM0M2E4OGExMjVlOGJkODM2ZDg0MTk3ODEwMWY2NmQyYzkxOTFlYmZhMTM0ZGQ3NzgxZTNkMTg5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W8e_-4Y8s2lf4ofAhJuteTe-23Z2mHBZDVCFFyCKsk4">
> 
> 你浏览器有没有强制刷新缓存啊

刷了然后好了……正好在更新节点装好的

**Comment by Enderiose** [comment]
正好更新节点前后部署配置，CTRL F5已解决……
