### ISSUE TITLE
[Feature Request]: 还是推荐改成手机安装APP效果,前进后退按钮效果意义不大。

### ISSUE THREAD

**Issue by Awhitedressy** [jxxghp/MoviePilot#2175]
### 当前程序版本

v1.9.1-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

还是推荐改成手机安装APP效果,前进后退按钮效果意义不大。网页安装到桌面，打开看起来就跟网页一样，还是之前的效果看着舒服。实话说 前进后退显示出来，没什么意思。

**Comment by jxxghp** [comment]
@Awhitedressy 已经回退过了呀，最新版是app效果

**Comment by Awhitedressy** [comment]
> @Awhitedressy已经回退了呀，最新版是app效果

可能是我缓存没清理。

**Comment by Awhitedressy** [comment]
> @Awhitedressy已经回退了呀，最新版是app效果

可能是我缓存没清理。

**Comment by Awhitedressy** [comment]
> @Awhitedressy已经回退了呀，最新版是app效果

可能是我缓存没有清理。
