### ISSUE TITLE
[Feature Request]: 能否把目录监控 目的地下的媒体库也自动分类啊,真的好难受

### ISSUE THREAD

**Issue by yokunnyang** [jxxghp/MoviePilot#2177]
### 当前程序版本

1.9.1-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否把目录监控 目的地下的媒体库也自动分类啊，以前目录监控用的好好的，改版后，就不分类了，我是同个盘有多个目录，必须用目录监控指定目的地，现在改版了，指定了，目的地就会不分类，能否跟以前一样，目录监控还是可以分类，不然会刮到 别的地方去，每次还得自己手动移位置。

**Comment by jxxghp** [comment]
是你没搞懂怎么用，现在就能实现。

**Comment by yokunnyang** [comment]
请问如何实现啊？你看我这个他不分 日番 什么的2ji级分类

![3ffb7c71ca8160a1dae03d744baa578](https://github.com/jxxghp/MoviePilot/assets/133833844/159937ce-9ab5-4285-8dd9-10447b8cdc66)
![ef4dd3578599bbcf3186c8778d56099](https://github.com/jxxghp/MoviePilot/assets/133833844/db7dbb42-2b57-42f1-9783-d3f94ac8ce23)
![image](https://github.com/jxxghp/MoviePilot/assets/133833844/05cce81f-69c2-48bd-a0cd-89832fa544c4)

**Comment by yokunnyang** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/133833844/2b1c0f48-fc35-455c-bc01-b9667aecfccd)
我哪怕设置成这样自动分类，他还是不分类

**Comment by foreveruand** [comment]
目录监控往下滑，有一段文字”监控目录指定了目的目录时，将直接整理到对应目录，v1.9.1-beta前会自动创建一级目录，v1.9.1-beta+不会自动创建一二级分类目录，建议不设置目的目录，在系统的设定中灵活设置好媒体库目录及分类“
你在指定了日番媒体类别的时候，都已经指定二级分类了，自然不会分类。为什么不能把目录改为/downloads/link/strm/日番 呢

**Comment by yokunnyang** [comment]
因为除了日番还有其他类别，不是一个类别，所以我要他分类。

**Comment by foreveruand** [comment]
> 因为除了日番还有其他类别，不是一个类别，所以我要他分类。

https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98

https://blog.ddsrem.com/archives/mediadirconfig

两个教程，你看一下吧

**Comment by yokunnyang** [comment]
> > 因为除了日番还有其他类别，不是一个类别，所以我要他分类。
> 
> https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98
> 
> https://blog.ddsrem.com/archives/mediadirconfig
> 
> 两个教程，你看一下吧

二级分类策略我有用这插件，是这样的，我一个盘有多个目录媒体库是 动漫这个类别，要他分类，请看
/downloads/1:/downloads/link/web#link
/downloads/VCB:/downloads/link/ANIME#link
/downloads/ANIME:/downloads/link/ANIME#link
/downloads/TV:/downloads/link/TV#link
/d2/ANIME2:/d2/link2/ANIME2#link

我不是只有一个目录 分类动漫，以前有目录监控，这几个路径可以都分类，现在设置了多个路径，他只会去优先权最高的那个，哪怕我设置了后面strm自动分类，他也不分类

**Comment by foreveruand** [comment]
> > > 因为除了日番还有其他类别，不是一个类别，所以我要他分类。
> > 
> > 
> > https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98
> > https://blog.ddsrem.com/archives/mediadirconfig
> > 两个教程，你看一下吧
> 
> 二级分类策略我有用这插件，是这样的，我一个盘有多个目录媒体库是 动漫这个类别，要他分类，请看 /downloads/1:/downloads/link/web#link /downloads/VCB:/downloads/link/ANIME#link /downloads/ANIME:/downloads/link/ANIME#link /downloads/TV:/downloads/link/TV#link /d2/ANIME2:/d2/link2/ANIME2#link
> 
> 我不是只有一个目录 分类动漫，以前有目录监控，这几个路径可以都分类，现在设置了多个路径，他只会去优先权最高的那个，哪怕我设置了后面strm自动分类，他也不分类

”监控目录指定了目的目录时，将直接整理到对应目录，v1.9.1-beta前会自动创建一级目录，v1.9.1-beta+不会自动创建一二级分类目录，建议不设置目的目录，在系统的设定中灵活设置好媒体库目录及分类“

多个目录好像还是有点问题，不会按根目录匹配。你可能只能目录监控里面自己二级分类了

**Comment by yokunnyang** [comment]
> 多个目录好像还是有点问题，不会按根目录匹配。你可能只能目录监控里面自己二级分类了

对，就是这个原因，因为我还用ANI插件，他下下来的资源有国漫 有日漫 ，还是需要分类下，但是都在一个strm文件夹内，要二级分类 还得自己手动分，光用目录监控，他之后都放根目录不分类。
所以我才发这个贴，让作者能恢复之前的目录监控功能，写了目的地，一样能分类。
我自己是 没组raid，都是单盘，多盘，多目录，同一个磁盘动漫 分 BD跟web 还有一个ANI的那个strm，有的还分了VCB的资源。这次改动，基本上只针对一个目录 一个类别。没考虑到 我这种多目录情况

**Comment by foreveruand** [comment]
不是没考虑，最下面有优先同根目录选项。理论上是可以多目录的。只是现在好像有一点问题

**Comment by yokunnyang** [comment]
> 不是没考虑，最下面有优先同根目录选项。理论上是可以多目录的。只是现在好像有一点问题

优先同根 比如都在downloads下，我3个目录，downloads/link/ANIME，/downloads/link/web，/downloads/link/strm，按他现在的方式，他没办法识别我到底选择哪个目录，因为我没跟目录监控一样指定目的地。而指定了目的地，就会不分类，所以问题出在这

**Comment by yokunnyang** [comment]
其实我的想法是在目录里，新增3个downloads/link/ANIME，/downloads/link/web，/downloads/link/strm，类别都是电视剧，勾选自动分类。然后目录监控 填写目的地，根据目录里填写的这3个路径，如果符合就自动分类，不符合就不分类，这样就可以自定义了。

**Comment by yokunnyang** [comment]
我昨天在群里这问这个事，还被T了，现在也只能在这写写帖子，哎，看作者心情了，他愿意改，完善下还好，不改我也没办法

**Comment by foreveruand** [comment]
> 我昨天在群里这问这个事，还被T了，现在也只能在这写写帖子，哎，看作者心情了，他愿意改，完善下还好，不改我也没办法

你问法不对。不大可能改回去。你不如问同盘优先能不能匹配到多级目录。
一般同盘用的就一个媒体库，很少区分strm web什么的，建好几个媒体库。也就不需要目录监控指定。

**Comment by yokunnyang** [comment]
> > 我昨天在群里这问这个事，还被T了，现在也只能在这写写帖子，哎，看作者心情了，他愿意改，完善下还好，不改我也没办法
> 
> 你问法不对。不大可能改回去。你不如问同盘优先能不能匹配到多级目录。 一般同盘用的就一个媒体库，很少区分strm web什么的，建好几个媒体库。也就不需要目录监控指定。

群里太杂了，问了，有的理睬，有的无视，然后从中间看的人还会不理解我的情况。开始跟我讲怎么怎么样，我还要在解释几次。他们不理解我用多个目录，而且很可能会误解成，类别不同的多个目录，其实我是同个动漫类别多个目录需要分类。
没办法，我先降回1.9.0了，新版手动刮削还有不刮信息的问题。
