### ISSUE TITLE
[错误报告]: 站点管理-憨憨不能用了

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#218]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.4

### 问题类型

主程序运行问题

### 问题描述

憨憨无法使用， 站点管理中-浏览 数据为空

实际搜索种，站点获取不到资源

点击测试倒是可以测试成功

**Comment by jxxghp** [comment]
@paysenyu 憨憨的UI一直在变，昨天上午刚适配好，又不行了。

**Comment by paysenyu** [comment]
> @paysenyu 憨憨的UI一直在变，昨天上午刚适配好，又不行了。

幸苦老大了。。憨憨刚改版，估计还有得搞
