### ISSUE TITLE
获取微信access_token失败，未获取到返回信息

### ISSUE THREAD

**Issue by yinshuiji1** [jxxghp/MoviePilot#2182]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.1-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

wechat.py 获取微信access_token失败，请检查参数配置
wechat.py 获取微信access_token失败，错误信息：获取微信access_token失败，网络连接失败
wechat.py 获取微信access_token失败，未获取到返回信息
检查了微信配置，以及域名地址，无问题。
![79fc9d78c2bdfc50709536456d1d14d](https://github.com/jxxghp/MoviePilot/assets/167011928/6f4b3219-775c-4f96-93b4-79eeb5709504)

### 发生问题时系统日志和配置文件

```bash
21:27:48,815	
transfer.py
/downloads/源文件/电视剧/国产剧/Joy.of.Life.S02.2024.Chinese.EP20-21.1080P.Disney.WEB-DL.H265.DDP2.0-tt 转移完成，共 2 个文件，失败 0 个，跳过 0 个
INFO	21:27:48,815	
command.py
处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f7e36567240>, <function EpisodeGroupMeta.scrap_rt at 0x7f7e3615c220>, <function PersonMeta.scrap_rt at 0x7f7e3608b100>]
ERROR	21:27:48,806	
wechat.py
获取微信access_token失败，请检查参数配置
ERROR	21:27:48,801	
wechat.py
获取微信access_token失败，错误信息：获取微信access_token失败，网络连接失败
ERROR	21:27:48,796	
wechat.py
获取微信access_token失败，未获取到返回信息
INFO	21:27:08,724	
command.py
处理事件：notice.message - [<function IyuuMsg.send at 0x7f7e361b0180>]
INFO	21:27:08,717	
chain
发送消息：channel=None，title=庆余年 (2019) S02 E20-E21 已入库, text=评分：7.9，类型：电视剧，类别：国产剧，质量： WEB-DL 1080p，共2个文件，大小：3.07G，userid=None
```

**Comment by yinshuiji1** [comment]
微信交互没有问题，MP能收到微信发的消息，但是无法回传消息，此微信应用同样用于青龙面板，接收消息正常
![1](https://github.com/jxxghp/MoviePilot/assets/167011928/dbc02acd-76eb-4c3d-8568-10e5524a47fc)
![2](https://github.com/jxxghp/MoviePilot/assets/167011928/0da095ca-d8a4-4957-8892-c4d91c5514e7)
![3](https://github.com/jxxghp/MoviePilot/assets/167011928/3539c096-47ae-4ac9-88be-16decead4944)

**Comment by quentinztq** [comment]
你解决了么？我的也是这样的

**Comment by 735876214** [comment]
你好，你那边问题解决了吗？我这也遇到同样的问题

**Comment by YoghurtGuy** [comment]
我也遇到了同样的问题，本来正常，添加代理后就不正常了

**Comment by Michael-CD** [comment]
> 我也遇到了同样的问题，本来正常，添加代理后就不正常了。 应该是分流时分错了？修改规则后一切正常了

求问具体修改规则是哪个地址？走代理还是直连？遇到了同样的问题，不过没有修改规则，更换了节点就正常了，也有可能是之前的节点失效了没有及时更新？

**Comment by cutety** [comment]
> > 我也遇到了同样的问题，本来正常，添加代理后就不正常了。 应该是分流时分错了？修改规则后一切正常了
> 
> 求问具体修改规则是哪个地址？走代理还是直连？遇到了同样的问题，不过没有修改规则，更换了节点就正常了，也有可能是之前的节点失效了没有及时更新？

同问

**Comment by YoghurtGuy** [comment]
> > 我也遇到了同样的问题，本来正常，添加代理后就不正常了。 应该是分流时分错了？修改规则后一切正常了
> 
> 求问具体修改规则是哪个地址？走代理还是直连？遇到了同样的问题，不过没有修改规则，更换了节点就正常了，也有可能是之前的节点失效了没有及时更新？

抱歉，没有看到，时间太久远，我当时应该是后缀qq.com的设为直连就好了
希望对你有用
@cutety

**Comment by cutety** [comment]
> > > 我也遇到了同样的问题，本来正常，添加代理后就不正常了。 应该是分流时分错了？修改规则后一切正常了
> > 
> > 
> > 求问具体修改规则是哪个地址？走代理还是直连？遇到了同样的问题，不过没有修改规则，更换了节点就正常了，也有可能是之前的节点失效了没有及时更新？
> 
> 抱歉，没有看到，时间太久远，我当时应该是后缀qq.com的设为直连就好了 希望对你有用 [@cutety](https://github.com/cutety)

感谢回复，我刚才试着给qyapi相关的设置为直连也可以了
