### ISSUE TITLE
[错误报告]: 目录中没有动漫的选项……

### ISSUE THREAD

**Issue by chenhao2424** [jxxghp/MoviePilot#2189]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

就是下载目录的媒体类型下来选项中没有动漫……我已经清空了缓存，换了浏览器也有一样的问题。

![CleanShot 2024-05-26 at 16 57 36](https://github.com/jxxghp/MoviePilot/assets/13376049/4deb6c81-dba7-4c9d-97a6-7a7ed80339f2)

**Comment by huanyingbaye** [comment]
不看更新的么？

**Comment by chenhao2424** [comment]
> 不看更新的么？

懂了懂了……感谢大佬
