### ISSUE TITLE
[错误报告]: 下载器监控入库以后会改变标签

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#2192]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.2-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载器监控入库以后，种子得标签会变成已整理，但是会将其他标签都覆盖，
比如原来有插件添加得站点，媒体名等标签，整理入库以后只剩一个已整理得标签

**Comment by dlovew** [comment]
补充：希望已整理标签可以是新增，而不会覆盖原有标签，下载器是transmission

**Comment by dlovew** [comment]
最新版1.9.2还是和原来一样

**Comment by dlovew** [comment]
麻烦大佬看一下，1.9.2这个问题还是存在，刚添加的下载通过其他插件添加了站点和资源名的标签，下载器监控入库以后只剩一个已整理的标签了

**Comment by cng10001** [comment]
同，
用了一下，发现qb是整理后同时保留MoviePilot和已整理标签的。
但是transmission还是不行，只会都变成已整理

**Comment by dlovew** [comment]
> 同， 用了一下，发现qb是整理后同时保留MoviePilot和已整理标签的。 但是transmission还是不行，只会都变成已整理

所以我现在已经用qb了，现在qb辅种也能跳过校验，种子不多就用qb吧。一两千还行，多了web界面会卡

**Comment by cng10001** [comment]
tr有数据目录 感觉好用哎
