### ISSUE TITLE
[错误报告]: 新版本媒体库目录，在历史记录内删除历史记录、源文件和媒体库文件是会连同上级目录一并删除。

### ISSUE THREAD

**Issue by ShiharaX** [jxxghp/MoviePilot#2193]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [x] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

新版本媒体库目录，在历史记录内删除历史记录、源文件和媒体库文件是会连同上级目录一并删除。
<img width="1351" alt="截屏2024-05-27 10 08 19" src="https://github.com/jxxghp/MoviePilot/assets/61444826/bb88840a-aea8-4307-8fa3-2249e6c2fc6a">

**Comment by jxxghp** [comment]
你的媒体库目录是怎么设置的，贴出来看看
