### ISSUE TITLE
[Feature Request]: 希望添加延后订阅功能

### ISSUE THREAD

**Issue by vigorZX** [jxxghp/MoviePilot#2197]
### 当前程序版本

1.9.3beta

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

PT一般都是先出1080p或者无字幕版本，一般就直接匹配最低的订阅规则订阅了。但是PT基本会在3-5内更新完大部分的版本，在这个时候重新筛选会有更好的版本。如果开启洗版的功能会导致下载多次，所以如果是检测到资源有了后，按照自定义的时间，比如3天后再订阅，基本就能满足这个需求了

**Comment by cddjr** [comment]
订阅可以过滤分辨率、质量
