### ISSUE TITLE
[Feature Request]: 站点管理 - 浏览 增加下载

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#220]
### 当前程序版本

1.0.4

### 功能改进

站点管理 - 浏览 目前只能下载种子到本地，然后下载器手动添加

希望增加一键mp 自动下载。

**Comment by cend1s** [comment]
有同样的需求，还有是不是可以考虑把站点内的搜索也增加上。
或者在正在下载处增加可以通过链接的方式下载，有些文件通过自动化可能搜索不到，这样可以人为添加一些资源，并能通过MP统一管理。
