### ISSUE TITLE
[插件问题]: 添加了第三方库，安装的是官方演职人员刮削v1.3，提示有更新，更新后变成第三插件了

### ISSUE THREAD

**Issue by qhly2010** [jxxghp/MoviePilot#2202]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

添加第三方插件库https://github.com/audichuang/MoviePilot-Plugins  ，安装的是官方演职人员刮削v1.3,插件提示有更新，更新后变成了演员刮削v1.5非官方插件了，卸载插件后能在插件市场看到这两个插件

### 发生问题时系统日志和配置文件

```bash
无
```

**Comment by jxxghp** [comment]
没理解你的问题，要用低版本不升级就行了。
有人改了官方的插件升高了版本号在自已库里存放，但没改插件名字就会有这个情况。
