### ISSUE TITLE
[Feature Request]: 推荐增加系统通知到微信TG或其他

### ISSUE THREAD

**Issue by Awhitedressy** [jxxghp/MoviePilot#2204]
### 当前程序版本

v1.9.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

因代理有可能随时不连接，TMDB会出现连通性问题。建议作者增加系统错误通知到微信TG或其他。发现此错误，我可以第一时间处理。谢谢！

**Comment by InfinityPacer** [comment]
不错，下来整个插件。

**Comment by jxxghp** [comment]
> 不错，下来整个插件。

要放个事件出来吗，不然估计不好做。

**Comment by InfinityPacer** [comment]
> > 不错，下来整个插件。
> 
> 
> 
> 要放个事件出来吗，不然估计不好做。

现在系统消息用的Queue，看来是得开个事件才行，这样看来是两个需求。
一个是系统消息通过消息渠道推送
一个是后台定时健康检查+连通性测试

**Comment by InfinityPacer** [comment]
> > > 不错，下来整个插件。
> > 
> > 
> > 
> > 要放个事件出来吗，不然估计不好做。
> 
> 现在系统消息用的Queue，看来是得开个事件才行，这样看来是两个需求。
> 一个是系统消息通过消息渠道推送
> 一个是后台定时健康检查+连通性测试

我先整一个定时健康检查的，系统消息的，J大再帮忙看看，是主程序开事件合适还是什么方案合适。

**Comment by Awhitedressy** [comment]
> > > > 不错，下来整个插件。
> > > 
> > > 
> > > 要放个事件出来吗，不然估计不好做。
> > 
> > 
> > 现在系统消息用的Queue，看来是得开个事件才行，这样看来是两个需求。
> > 一个是系统消息通过消息渠道推送
> > 一个是后台定时健康检查+连通性测试
> 
> 我先整一个定时健康检查的，系统消息的，J大再帮忙看看，是主程序开事件合适还是什么方案合适。

大佬，已经做出来了么？我看到插件市场有个诊断连通性的“自动诊断插件”

**Comment by Awhitedressy** [comment]
> > > > > 不错，下来整个插件。
> > > > 
> > > > 
> > > > 要放个事件出来吗，不然估计不好做。
> > > 
> > > 
> > > 现在系统消息用的Queue，看来是得开个事件才行，这样看来是两个需求。
> > > 一个是系统消息通过消息渠道推送
> > > 一个是后台定时健康检查+连通性测试
> > 
> > 
> > 我先整一个定时健康检查的，系统消息的，J大再帮忙看看，是主程序开事件合适还是什么方案合适。
> 
> 大佬，已经做出来了么？我看到插件市场有个诊断连通性的“自动诊断插件”

感谢大佬！
