### ISSUE TITLE
豆瓣榜单订阅失败

### ISSUE THREAD

**Issue by dzbl04230302** [jxxghp/MoviePilot#2205]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

使用豆瓣榜单订阅失败，提示：“未能通过豆瓣ID 1293792 获取到TMDB信息”
![332281437-1b852ea1-59e9-4c5c-b717-72da949ffd65](https://github.com/jxxghp/MoviePilot/assets/29794974/fa48f420-f9c7-40d7-92f8-3bd5bf109f2a)
![332281443-027063b6-dbfe-497d-aaf2-4440d19c1065](https://github.com/jxxghp/MoviePilot/assets/29794974/f4249c42-4707-42c0-8a0d-3cdfe68a0532)

**Comment by jxxghp** [comment]
我这边挺正常的，豆瓣的榜单什么的可以访问吗？

**Comment by dzbl04230302** [comment]
> 我这边挺正常的，豆瓣的榜单什么的可以访问吗？

可以访问的
![微信图片_20240528165042](https://github.com/jxxghp/MoviePilot/assets/29794974/fe9ef040-c8d6-491c-9349-7198adc11956)

**Comment by jxxghp** [comment]
@dzbl04230302 不是这个，我是指MP上的有豆瓣相关的推荐是否能出来，如果也不能，可能是ip被黑名单了。

**Comment by dzbl04230302** [comment]
> 我这边挺正常的，豆瓣的榜单什么的可以访问吗？

能出来的
![image](https://github.com/jxxghp/MoviePilot/assets/29794974/bd13e907-d972-46a9-8857-f2551a6fdf23)

**Comment by yejialiango** [comment]
这个问题解决了吗？我也遇到类似的问题🥹
