### ISSUE TITLE
更新最新版后，动漫库的耳机二级分类有没有办法设置，我分的日番 国创

### ISSUE THREAD

**Issue by yxb900211** [jxxghp/MoviePilot#2207]
### 当前程序版本

1.9.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

更新最新版后，动漫库的耳机二级分类有没有办法设置，我分的日番 国创，现在只能把所有动漫分到一起了

### 参考资料

更新最新版后，动漫库的耳机二级分类有没有办法设置，我分的日番 国创

**Comment by jxxghp** [comment]
@yxb900211 看群或者看频道的置顶
