### ISSUE TITLE
[错误报告]: 更新最新的版本之后，下载文件整理进程会提示动漫整理失败

### ISSUE THREAD

**Issue by LmanTs** [jxxghp/MoviePilot#2208]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载文件整理就会报这个执行失败
![photo_2024-05-28_11-45-23](https://github.com/jxxghp/MoviePilot/assets/40474635/603eba1d-f85b-49c3-8598-47c6cc39a1f6)
目录全设置为了自动分类，配置文件
![Screenshot 2024-05-28 120846](https://github.com/jxxghp/MoviePilot/assets/40474635/1a82c2ce-ee07-4393-82aa-481e51574b5c)
消息通知也是能正常提示已经整理入库
![Screenshot 2024-05-28 120206](https://github.com/jxxghp/MoviePilot/assets/40474635/4b227048-6b1e-48a9-956d-c27acffdb281)
配置文件已经注释了以前的变量设置
![Screenshot 2024-05-28 101346](https://github.com/jxxghp/MoviePilot/assets/40474635/65d3a00b-0626-4c4c-bd94-8f00ec684d99)

**Comment by jxxghp** [comment]
提供一下日志

**Comment by InfinityPacer** [comment]
这种看频道置顶就能解决的问题…就不用提ISSUE了吧，还标记BUG…

这明显二级分类的配置没改过来吧…

**Comment by LmanTs** [comment]
【ERROR】2024-05-28 07:44:49,264 - scheduler.py - 定时任务 下载文件整理 执行失败：'动漫' is not a valid MediaType - Traceback (most recent call last):
  File "/app/app/scheduler.py", line 367, in start
    job["func"](*args, **kwargs)
  File "/app/app/chain/transfer.py", line 70, in process
    mtype = MediaType(downloadhis.type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: '动漫' is not a valid MediaType

**Comment by jxxghp** [comment]
@LmanTs 你是通过插件补的下载记录吗？记录里为什么有类型是动漫的数据。

**Comment by LmanTs** [comment]
我确实补了动漫，使用的是下载任务分类与标签插件
![Screenshot 2024-05-28 122329](https://github.com/jxxghp/MoviePilot/assets/40474635/7d754e96-8d99-4b8c-b9f9-bee0e13c58c1)

**Comment by jxxghp** [comment]
@LmanTs 那就是这个原因了，不能这么补

**Comment by InfinityPacer** [comment]
哈哈哈，小丑竟是我自己，还是J大英明神武，洞穿问题本质
