### ISSUE TITLE
分辨率匹配处代码未能切分循环关键字，全部匹配导致订阅自动不能有效执行。

### ISSUE THREAD

**Issue by Puwong** [jxxghp/MoviePilot#2210]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

https://t.me/moviepilot_official/581736

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅的是动画片，永生，4k优先，pt助手搜索，自己的站点里有匹配的资源，但是订阅一周仍未下载，找了一个懂代码的同学看了下，给出问题所在：这个地方没有切分，做了全量匹配，这样肯定不行啊。辛苦修复！
![img_v3_02ba_55b547a2-83cf-4676-ae38-7acffd1cc21g](https://github.com/jxxghp/MoviePilot/assets/16173186/f4bbdc4f-96fd-4769-aa6c-c6e5d1ab6088)

### 发生问题时系统日志和配置文件

```bash
Immortality S01 2022 1080p WEB-DL AAC H264-HDSWEB 不匹配分辨率规则 4K\|2160p\|x2160
```

**Comment by cddjr** [comment]
建议你还是多学习学习mp的优先级是怎么配置的吧。。。

**Comment by jxxghp** [comment]
这。。。先懂代码再来提吧，不然容易闹笑话。
1、这是正则式匹配，这么写是对的。
2、1080p怎么就能匹配你的4K了

**Comment by Puwong** [comment]
我用模拟器装的t，不好贴图，我这里回复一下。
我只想下载4k的，所以之前都是设置4k的优先级，别的没有设置，这不冲突吧？这是我订阅的仙逆及下载的数据情况。

![image](https://github.com/jxxghp/MoviePilot/assets/16173186/22084a24-41a2-401a-9914-1c36450a375b)

![image](https://github.com/jxxghp/MoviePilot/assets/16173186/432b5018-faf6-4fcf-b14b-6f61fcd4b2c3)

![image](https://github.com/jxxghp/MoviePilot/assets/16173186/3d391652-7395-44b5-98c0-8c0bf66bf3bd)

![image](https://github.com/jxxghp/MoviePilot/assets/16173186/e95a2556-9a11-4b51-adf3-cbb697b4a17c)


今天觉得有问题，是我订阅的另外一部剧集：遮天，这个一直没有进度，所以想着把订阅条件修改了一下，把4k限定条件去掉了，结果不仅下载回来数据了，而且一部分是4k的，所以反推可能有问题，就找人看了下代码，发现这个情况。
各位大侠还请指教。

**Comment by Puwong** [comment]
尴尬了，我问了下同事，他说他水了，确实看错了，正则没问题。

**Comment by zoffyultraman** [comment]
直接close吧

**Comment by Puwong** [comment]
行，我先close了，我再看看我的配置，打扰各位了！
