### ISSUE TITLE
原1级目录“动漫”无法配置。

### ISSUE THREAD

**Issue by torashen** [jxxghp/MoviePilot#2211]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

原一级目录“动漫”无法配置。动漫二级目录也无法设置了。
暂时通过修改自定义二级目录打到需求。
但是希望还是能回到以前3个一级目录的配置方式。
![a8de0ba2460c67618df7824ff4c3f5d](https://github.com/jxxghp/MoviePilot/assets/153890345/e1a1cedf-90dd-4949-9e24-66c0a34e6762)

**Comment by jxxghp** [comment]
动漫二级目录也无法设置了——怎么就无法设置了？

**Comment by zoffyultraman** [comment]
动漫整体回到剧集下面了，目前最简单的理解，剧集和电影为1级，剩下全为二级，剧集的2级目录可以有日番 国漫，日韩剧等等，开启自动分类即可，插件中安装二级分类插件启动。jellyfin emby plex添加二级分类目录，达到以前的效果即可

**Comment by torashen** [comment]
媒体类型现在只能选择到，“全部”"电影”“电视剧”。
![0001](https://github.com/jxxghp/MoviePilot/assets/153890345/ce1e3375-3228-40b1-a2d4-2eb67f18d253)
二级目录插件，设置分类后，也没有作用。
![002](https://github.com/jxxghp/MoviePilot/assets/153890345/463526bb-c3ef-46cb-8a7f-b94f35c54e3e)

**Comment by foreveruand** [comment]
看教程，二级分类文件里面动漫是要放到tv下面，但文件夹怎么排的看你媒体库目录配置

**Comment by zoffyultraman** [comment]
> 动漫整体回到剧集下面了，目前最简单的理解，剧集和电影为1级，剩下全为二级，剧集的2级目录可以有日番 国漫，日韩剧等等，开启自动分类即可，插件中安装二级分类插件启动。jellyfin emby plex添加二级分类目录，达到以前的效果即可

请仔细阅读以上回答，动漫目前属于tv分类，把国漫日番放到tv下即可

**Comment by zoffyultraman** [comment]
> 动漫整体回到剧集下面了，目前最简单的理解，剧集和电影为1级，剩下全为二级，剧集的2级目录可以有日番 国漫，日韩剧等等，开启自动分类即可，插件中安装二级分类插件启动。jellyfin emby plex添加二级分类目录，达到以前的效果即可

还是这样吧。媒体服务器添加具体子目录即可

**Comment by torashen** [comment]
我研究下，没太搞得清楚逻辑。 谢谢各路大佬。

**Comment by zoffyultraman** [comment]
> 我研究下，没太搞得清楚逻辑。 谢谢各路大佬。

提issue没问题，这种明显不是bug的就不要带bug了，多看下日志。
