### ISSUE TITLE
在历史记录里手动整理电视剧，集数偏移功能无法使用，不管填的是正数还是负数整理出来的依然是原有的集数

### ISSUE THREAD

**Issue by zibuqingyan** [jxxghp/MoviePilot#2212]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我有一部电视剧命名是s02e09 我通过指定类型和tmbdid和指定第一季来手动整理  集数偏移填的46［其他任何数字正负都不行］ 整理后得到了s01E09  集数偏移没有生效

### 发生问题时系统日志和配置文件

```bash
没有找到相关日志的位置
```

**Comment by jxxghp** [comment]
截个图看下你乍填的，集数偏移要在集数定位的基础上使用。

**Comment by zoffyultraman** [comment]
如文件命为：   鬼灭之刃s02e09.mp4
你应该在集数定位中输入：鬼灭之刃s02e{ep}.mp4
然后在集数便宜中填写偏移数字
