### ISSUE TITLE
[错误报告]: 1.9.1开始刮削失败？

### ISSUE THREAD

**Issue by zhnnan** [jxxghp/MoviePilot#2214]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

最近在追某剧，之前一直都是好好的，1.9.2发现刮削部分的设置界面变了，也不自动刮削了

<img width="397" alt="Snipaste_2024-05-29_00-28-27" src="https://github.com/jxxghp/MoviePilot/assets/4023201/1a19483b-3be3-4f41-a8db-48c62da35904">

**Comment by zoffyultraman** [comment]
你好，贴一下日志呢，测一下连通性也截图发一下

**Comment by zhnnan** [comment]
发现问题了，连通性问题，原来版本有个设置选项是可以更改imdb的url的，我把默认更改成了api.tmdb.org，现在这个设置项找不到了

**Comment by AisukaYuki** [comment]
> 发现问题了，连通性问题，原来版本有个设置选项是可以更改imdb的url的，我把默认更改成了api.tmdb.org，现在这个设置项找不到了

安装配置中心插件，里面可改。不然就手动改app.env

**Comment by zhnnan** [comment]
> > 发现问题了，连通性问题，原来版本有个设置选项是可以更改imdb的url的，我把默认更改成了api.tmdb.org，现在这个设置项找不到了
> 
> 安装配置中心插件，里面可改。不然就手动改app.env

我找到这个配置项了，发现配置没错，api.tmdb.org，所以看起来不是这个问题

**Comment by zhnnan** [comment]
另一个视频的日志，电视剧可以被转移和识别，但是不能被刮削
【INFO】2024-05-29 14:08:10,835 - media.py - Acapulco S03 2021 2160p ATVP WEB-DL DDP5.1 Atmos DV HDR H 265-HHWEB[阿卡普高 第三季 | 第06集 | 4K HDR+杜比视界 | 类型: 喜剧 | 主演: 恩里克·阿里宗/欧赫尼奥·德尔维斯 | By ATU_Tool] 识别到媒体信息：电视剧 阿卡普尔科 (2021)
【INFO】2024-05-29 14:08:10,834 - themoviedb - Acapulco TMDB识别结果：电视剧 阿卡普尔科 (2021) 133727
【INFO】2024-05-29 14:08:10,826 - themoviedb - Acapulco 使用TMDB识别缓存：阿卡普尔科
【INFO】2024-05-29 14:08:10,810 - torrents.py - 处理资源：Acapulco S03 2021 2160p ATVP WEB-DL DDP5.1 Atmos DV HDR H 265-HHWEB[阿卡普高 第三季 | 第06集 | 4K HDR+杜比视界 | 类型: 喜剧 | 主演: 恩里克·阿里宗/欧赫尼奥·德尔维斯 | By ATU_Tool] ...

**Comment by AisukaYuki** [comment]
目录监控插件里面的刮削按钮，看看是不是不小心关了

**Comment by zhnnan** [comment]
> 目录监控插件里面的刮削按钮，看看是不是不小心关了

找到了这个按钮，原来不记得有这个按钮啊，现在应该可以了。
非常感谢各位
