### ISSUE TITLE
[错误报告]: 添加任务到下载器失败

### ISSUE THREAD

**Issue by niumeng07** [jxxghp/MoviePilot#2215]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

从搜索页面添加任务到下载器报错。
错误信息：未知错误，userid=None

重建MP后正常，但重启后会报此错误，所有站点均如此，数据统计、签到等正常。

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-05-29 08:49:42,243 - download.py - 电影名字 添加下载任务失败：种子名字 - 种子未知错误
【INFO】2024-05-29 08:49:42,270 - chain - 发送消息：channel=None，title=添加下载任务失败：电影名字, text=站点：
种子名称：省略
错误信息：未知错误，userid=None
```

**Comment by anyishusheng** [comment]
同样的问题，不知道怎么处理

**Comment by evafans** [comment]
v1.9.2 Windows
同样的问题

**Comment by kofeisen** [comment]
同样问题，我的MP在docker，下载器在宿主机，之前正常下载。更新了MP image后现在不能下载

**Comment by Katou-Kouseki** [comment]
v1.9.3 同样的问题

**Comment by jinghua625** [comment]
关注，也遇到了

**Comment by jinlin-teck** [comment]
我也出现了这个问题，原因是我把qb的端口改成了80，改回8080就行了，不知道具体是什么原因无法用80端口的qb
