### ISSUE TITLE
在主程序-整理-正在下载界面，没有关联到下载器的内容，始终显示“没有任务”。

### ISSUE THREAD

**Issue by einstotle** [jxxghp/MoviePilot#2216]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2套件版

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在主程序-整理-正在下载界面，没有关联到下载器的内容，始终显示“没有任务”。请帮忙解决

**Comment by zoffyultraman** [comment]
请确认是mp添加的任务无法显示吗

**Comment by geneyuriy** [comment]
同样的问题。mp添加的任务，正在下载不显示，手动添加MOVIEPILOT标签也不行。

**Comment by fyu0h** [comment]
同样遇到这个问题，请问你解决了吗？

**Comment by wxpftd** [comment]
同样遇到这个问题。在mp订阅的下载任务，使用transmission下载，没有展示在 正在下载 页面上。

**Comment by fyu0h** [comment]
> 同样遇到这个问题。在mp订阅的下载任务，使用transmission下载，没有展示在 正在下载 页面上。

试试4.0.5版本的tr
linuxserver/transmission:4.0.5
