### ISSUE TITLE
[Feature Request]: 电视剧订阅，当达到总集数时不自动删除订阅

### ISSUE THREAD

**Issue by Yirenxs** [jxxghp/MoviePilot#2219]
### 当前程序版本

1.9.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

1. 问题：

目前“电视剧”的订阅逻辑是，订阅后自动在“订阅规则”里添加总集数（数据猜测取自TMDB，但我在TMDB上没找到只能看到当前有几集），但国产综艺或者一些冷门记录片推出时TMDB的总集数是错的，导致我还在追剧呢，但我库里的集数因为达到了错误的总集数就被MP自动删除了订阅。

2. 举例：

我正在追《解释鸿沟》，当天订阅时自动取得总集数4集，TMDB上已经推出6集了，我实际下载了6集，一订阅后就自动被删除订阅。

3. 改进逻辑：

- 总集数自动从TMDB取得错误的没关系，但达到总集数时不自动删除订阅，留一个观察期，比如半个月后如果TMDB总集数有更改就自动修改订阅里的总集数，或者TMDB当前集数超过总集数时以当前集数为总集数，或者这2个数据都没变化时但半个月内还是订阅有效，还是允许自动下载（如果一旦在总集数错误的情况下还能自动下载到新的1集，半个月观察期再延长半个月）。

- 超过半个月以上都没有变化时，自动删除生效。

4. 追加信息：

国产综艺或者一些冷门记录片TMDB上总集数是错误的其中一个原因，国产综艺喜欢搞上下集，即使总集数是10集，因一分上下集，实际的EP就超过10集了。

**Comment by jxxghp** [comment]
@wqzvic88 你说的这个问题早就给出了解决方案，订阅里面可以手工改集数，后台服务里面也有个定时刷新数据的服务，先看一下

**Comment by zoffyultraman** [comment]
> @wqzvic88 你说的这个问题早就给出了解决方案，订阅里面可以手工改集数，后台服务里面也有个定时刷新数据的服务，先看一下

问下佬，也就是说订阅元数据更新这个服务，会定期的刷新订阅的元数据，会自动更新订阅的剧集的集数是吗

**Comment by jxxghp** [comment]
@zoffyultraman 对，间隔6小时

**Comment by Yirenxs** [comment]
> @wqzvic88 你说的这个问题早就给出了解决方案，订阅里面可以手工改集数，后台服务里面也有个定时刷新数据的服务，先看一下

是的，我现在就是采用手工修订集数的办法，但这有几个问题：
1. 大多数新手，包括我，都不知道需要修改这个总集数，碰到突然被删订阅才不停的排查原因，最后才知道需要修改总集数。
2. 每订阅1个新剧时，用户的心理就会产生不安感，不知道这个自动填写的总集数是不是对的，需不需要修订总集数，否则可能被删订阅，最后可能养成每订阅1个新剧就干脆填写99。

另外，您说的订阅元数据更新，我翻了下通知，显示“'NoneType' object has no attribute 'update'”。不知道为什么会失败，假设可以成功的话，会自动将我被删的订阅恢复出来么，包括我在订阅里填写的订阅站点及分辨率指定之类的也会自动恢复么？

**Comment by jxxghp** [comment]
@cng10001 订阅的数据有问题，类型为容，改过数据库的数据吗？或者这个订阅是怎么添加的。

**Comment by cng10001** [comment]
啊这~没有改过数据库- -，订阅都是正常添加~ 
是某一个订阅的问题吗

**Comment by Camellia0821** [comment]
我也刚想上来提这个问题，版本v1.9.7，我的建议是要是能在电视剧订阅里，上方两个分栏(我的订阅和热门订阅)旁边增加个已完成的分栏就好了，如果订阅入了这个分栏，mp不再搜索订阅了，若是发现集数错了，还能通过修改总集数，把该已完成的订阅转移到我的订阅中，继续订阅

**Comment by Putarku** [comment]
> 我也刚想上来提这个问题，版本v1.9.7，我的建议是要是能在电视剧订阅里，上方两个分栏(我的订阅和热门订阅)旁边增加个已完成的分栏就好了，如果订阅入了这个分栏，mp不再搜索订阅了，若是发现集数错了，还能通过修改总集数，把该已完成的订阅转移到我的订阅中，继续订阅

现在订阅的右下角实际上已经有了订阅完成的历史记录，如果提前结束可以从里面修改总集数以后重新添加

**Comment by Camellia0821** [comment]
> > 我也刚想上来提这个问题，版本v1.9.7，我的建议是要是能在电视剧订阅里，上方两个分栏(我的订阅和热门订阅)旁边增加个已完成的分栏就好了，如果订阅入了这个分栏，mp不再搜索订阅了，若是发现集数错了，还能通过修改总集数，把该已完成的订阅转移到我的订阅中，继续订阅
> 
> 现在订阅的右下角实际上已经有了订阅完成的历史记录，如果提前结束可以从里面修改总集数以后重新添加

咦  我看到  谢谢提醒  这样跟我想的也差不多  真是太棒了  要是有个订阅完结通知那更完美了

**Comment by Putarku** [comment]
> > > 我也刚想上来提这个问题，版本v1.9.7，我的建议是要是能在电视剧订阅里，上方两个分栏(我的订阅和热门订阅)旁边增加个已完成的分栏就好了，如果订阅入了这个分栏，mp不再搜索订阅了，若是发现集数错了，还能通过修改总集数，把该已完成的订阅转移到我的订阅中，继续订阅
> > 
> > 
> > 现在订阅的右下角实际上已经有了订阅完成的历史记录，如果提前结束可以从里面修改总集数以后重新添加
> 
> 咦 我看到 谢谢提醒 这样跟我想的也差不多 真是太棒了 要是有个订阅完结通知那更完美了
订阅完结也是有通知的
![image](https://github.com/jxxghp/MoviePilot/assets/66679443/e4cce7d4-5098-415d-b93a-68e870ea87f3)

**Comment by Camellia0821** [comment]
> > > > 我也刚想上来提这个问题，版本v1.9.7，我的建议是要是能在电视剧订阅里，上方两个分栏(我的订阅和热门订阅)旁边增加个已完成的分栏就好了，如果订阅入了这个分栏，mp不再搜索订阅了，若是发现集数错了，还能通过修改总集数，把该已完成的订阅转移到我的订阅中，继续订阅
> > > 
> > > 
> > > 现在订阅的右下角实际上已经有了订阅完成的历史记录，如果提前结束可以从里面修改总集数以后重新添加
> > 
> > 
> > 咦 我看到 谢谢提醒 这样跟我想的也差不多 真是太棒了 要是有个订阅完结通知那更完美了
> 
> 订阅完结也是有通知的 ![image](https://private-user-images.githubusercontent.com/66679443/342863048-e4cce7d4-5098-415d-b93a-68e870ea87f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzk2MDUsIm5iZiI6MTcxOTMzOTMwNSwicGF0aCI6Ii82NjY3OTQ0My8zNDI4NjMwNDgtZTRjY2U3ZDQtNTA5OC00MTVkLWI5M2EtNjhlODcwZWE4N2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE4MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmFmYjRkNzlhMjNkNmFhMTZmNzgxNTcyNTJjMGYzNzBkMmYzYzI1ZGI0NjcyMzcwYmM1MGFmMTZkYzlhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AWxQQhGNSktr32Iylot1wRxL0Zs8jztG--ss55Hs0VI)

哦哦  好的  原来是搞这种通知啊  我有时间去捣鼓下  谢谢啦
