### ISSUE TITLE
[错误报告]: 馒头无法搜索

### ISSUE THREAD

**Issue by leigeuo** [jxxghp/MoviePilot#2221]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

用pt馒头站点进行搜索时报错，其他pt站点搜索正常，也问了其他群友，好像就我一个人有这种情况
![111](https://github.com/jxxghp/MoviePilot/assets/103514244/6683d11f-a248-42de-9fbe-3a1d32e1f97c)

**Comment by HeatonZ** [comment]
+1

**Comment by ThierryCheng** [comment]
+1

**Comment by YUNJinQ** [comment]
同样出现类似问题，馒头已填写请求头 填写令牌 连通性正常，但是无法搜索
![image](https://github.com/user-attachments/assets/fb524bad-11e5-48c9-a4cd-fc4aa9ac1d40)
点击浏览是空白
搜索是空白
![image](https://github.com/user-attachments/assets/0c360705-b16e-4bbb-8c26-65ef5565fe13)

**Comment by rush7991** [comment]
+1

**Comment by glovanni** [comment]
同样的问题同样的错误，馒头搜不出结果，其他站点都正常。
你们最后是怎么解决的？
我的mp是最新版本v1.9.17

**Comment by luoleiusers** [comment]
后面大家是怎么解决的？求个方法

**Comment by leigeuo** [comment]
> 后面大家是怎么解决的？求个方法

后面某个版本自己就好了
