### ISSUE TITLE
[错误报告]: 开启了emby联动删除源文件，在主机目录里手动删除硬链接文件，也会联动删除源文件

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#223]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.4

### 问题类型

主程序运行问题

### 问题描述

如图，这个逻辑可否改一下，容易造成误操作

**Comment by paysenyu** [comment]
手动删 - emby 扫库发现没了 - 生成删除日志 - mp 读取到日志 - 删除源文件。

重新梳理一下你自己用这个插件的逻辑吧。

**Comment by loveu5522** [comment]
> 手动删 - emby 扫库发现没了 - 生成删除日志 - mp 读取到日志 - 删除源文件。
> 
> 重新梳理一下你自己用这个插件的逻辑吧。

我记得之前NT好像不会

**Comment by thsrite** [comment]
@loveu5522 nt一样的

**Comment by loveu5522** [comment]
好的，那就是我搞错了
