### ISSUE TITLE
[Feature Request]: sqllite3老死锁，希望增加其他数据库的支持，例如mysql等由用户指定数据库

### ISSUE THREAD

**Issue by iamckun** [jxxghp/MoviePilot#2234]
### 当前程序版本

v1.9.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

sqllite3老死锁，希望增加其他数据库的支持，例如mysql等由用户指定数据库
![image](https://github.com/jxxghp/MoviePilot/assets/65990499/c48981df-40a8-478f-939f-8a3dbe36caff)

**Comment by iamckun** [comment]
#3035 
麻烦可以看看合适吗

**Comment by iamckun** [comment]
@jxxghp 大佬球球了支持一下吧

**Comment by dezhishen** [comment]
请问有进展吗？

**Comment by iamckun** [comment]
> 请问有进展吗？

我这边已经用起来了作者没有审

**Comment by dezhishen** [comment]
> > 请问有进展吗？
> 
> 我这边已经用起来了作者没有审

有无构建好的镜像,我想试试

**Comment by iamckun** [comment]
> > > 请问有进展吗？
> > 
> > 
> > 我这边已经用起来了作者没有审
> 
> 有无构建好的镜像,我想试试

等我推送一份到阿里云

**Comment by iamckun** [comment]
> > > 请问有进展吗？
> > 
> > 
> > 我这边已经用起来了作者没有审
> 
> 有无构建好的镜像,我想试试
registry.cn-hangzhou.aliyuncs.com/iamckun/moviepilot
试试
环境变量
DB_TYPE 数据库类型 mysql
DB_HOST 数据库地址 
DB_USER 数据库用户名
DB_PASSWORD 数据库密码
DB_PORT 数据库端口
DB_NAME 数据库名称
![image](https://github.com/user-attachments/assets/7a599585-3657-4dfd-950a-d6328a38d9ad)

**Comment by Aqr-K** [comment]
@iamckun 其实死锁开，wal能缓解

**Comment by DDSRem** [comment]
目前暂未有开发计划，后续再看吧
