### ISSUE TITLE
我用iyuu和hhclub认证，日志都显示认证成功，但是在moviepilot里面却并没有任何站点，这是什么情况？

### ISSUE THREAD

**Issue by Link-KXL** [jxxghp/MoviePilot#2236]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我用iyuu和hhclub认证，日志都显示认证成功，但是在moviepilot里面却并没有任何站点，这是什么情况？
![QQ截图20240531113339](https://github.com/jxxghp/MoviePilot/assets/168751500/33c38904-d784-4fd0-8c95-04d76731ee44)
![QQ截图20240531113416](https://github.com/jxxghp/MoviePilot/assets/168751500/188fcc23-a521-426f-8e22-f82ad7de2bb1)
![QQ截图20240531113456](https://github.com/jxxghp/MoviePilot/assets/168751500/0b9b51d0-1e6b-4754-b52e-ffda47553e97)

**Comment by zoffyultraman** [comment]
认证只是为你启用站点相关功能，并不会添加站点，请自行在站点管理内添加。
