### ISSUE TITLE
[错误报告]: 订阅添加下载失败时仅通知到微信不通知到TG，手动下载失败时，两个渠道都有通知

### ISSUE THREAD

**Issue by niumeng07** [jxxghp/MoviePilot#2238]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅添加下载失败时仅通知到微信不通知到TG，手动下载失败时，两个渠道都有通知

### 发生问题时系统日志和配置文件

【ERROR】2024-05-31 14:28:27,929 - telegram.py - 发送消息失败：A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

**Comment by zoffyultraman** [comment]
建议贴上“仅通知到微信不通知到TG”的日志

**Comment by niumeng07** [comment]
> 建议贴上“仅通知到微信不通知到TG”的日志

已补充

**Comment by zoffyultraman** [comment]
看起来这个似乎和chat id有关，目前这个问题还能复现吗？

**Comment by niumeng07** [comment]
因为非订阅情况下发送没问题，目前没办法触发，我再观察一下看看 。

**Comment by niumeng07** [comment]
> 看起来这个似乎和chat id有关，目前这个问题还能复现吗？


因为非订阅情况下发送没问题，目前没办法触发，我再观察一下看看 。
