### ISSUE TITLE
修改自定义主题后，无法正常试用，请问如何通过文件代码改回默认主题

### ISSUE THREAD

**Issue by leeima** [jxxghp/MoviePilot#2239]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/84554107/b5204870-2f99-467b-8b2b-0fb9223fa891)
修改如图所示100%为0%后，webui无法正常试用，也无法修改回默认主题，改完刷新还是不变

**Comment by hotlcc** [comment]
@leeima 进浏览器控制台改回来啊

**Comment by leeima** [comment]
> @leeima 进浏览器控制台改回来啊

改不回去啊，点自定义没反应了，左边按钮也全没了，可以修改本地文件改回去吗

**Comment by hotlcc** [comment]
> > @leeima 进浏览器控制台改回来啊
> 
> 改不回去啊，点自定义没反应了，左边按钮也全没了，可以修改本地文件改回去吗

进浏览器控制台把你改的样式该回去，然后应该就能点击自定义了，然后点自定义再清空数据。终极解决方案用sqlite工具打开user.db文件删除systemconfig表中的自定义主题数据。

**Comment by leeima** [comment]
> > > @leeima 进浏览器控制台改回来啊
> > 
> > 
> > 改不回去啊，点自定义没反应了，左边按钮也全没了，可以修改本地文件改回去吗
> 
> 进浏览器控制台把你改的样式该回去，然后应该就能点击自定义了，然后点自定义再清空数据。终极解决方案用sqlite工具打开user.db文件删除systemconfig表中的自定义主题数据。

好了好了，感谢大佬。F12改回去，删除代码，切换回默认好了，谢谢。
