### ISSUE TITLE
请问微信自定义菜单多久生成？

### ISSUE THREAD

**Issue by leeima** [jxxghp/MoviePilot#2240]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

企业微信无菜单，已重启过，是需要时间的吗？大概多久

**Comment by leeima** [comment]
好了，感谢大佬，我用的官方的代理地址同步上目录之后，又改回自己的代理地址。

**Comment by simonchen1992** [comment]
> 好了，感谢大佬，我用的官方的代理地址同步上目录之后，又改回自己的代理地址。

我也是同样的问题，请问是怎么解决的呢
