### ISSUE TITLE
[错误报告]: 设置后好了之后，点击下载提示“ERROR:   download.py - 未找到下载目录：电视剧 西游记后传 (2000)”

### ISSUE THREAD

**Issue by JedMasterYoda** [jxxghp/MoviePilot#2241]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

点击下载提示下载失败，ERROR:   download.py - 未找到下载目录：电视剧 西游记后传 (2000)
通过MP的WEB界面，能够在映射的目录进行创建文件夹等操作，QB手动也能下载到映射的目录。说明权限无问题。
QB和MP映射的目录均一致。
![目录](https://github.com/jxxghp/MoviePilot/assets/120118198/7bb7c9d7-19f8-4af2-ada4-e85cd35ee4c5)

![下载失败](https://github.com/jxxghp/MoviePilot/assets/120118198/67e969b3-22b3-4e59-9711-273bca5d23a7)
![MP目录设置](https://github.com/jxxghp/MoviePilot/assets/120118198/12c057d1-1c4f-4d50-bdad-be1ba083b9b7)

### 发生问题时系统日志和配置文件

```bash
日志见上面的图。
```

**Comment by Putarku** [comment]
不要用全部-全部，电视剧和电影分开写两个，例如电视剧-全部，电影-全部

**Comment by JedMasterYoda** [comment]
> 不要用全部-全部，电视剧和电影分开写两个，例如电视剧-全部，电影-全部

感谢，没想到这个。

已经解决。
