### ISSUE TITLE
[错误报告]: 随机性出现硬链接错误

### ISSUE THREAD

**Issue by TyxTang** [jxxghp/MoviePilot#2243]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在目录同步时 随机性出现硬链接错误：-1

目录同步日志：
![c303763b0f38bce8b0c17dfc44352e4](https://github.com/jxxghp/MoviePilot/assets/90897955/dfd18b27-ee3b-4fb3-97c1-359f2c1350a6)
（打码仅为站点名称）

其中一条报错（红色圈出）显示的文件在下载目录不存在，像是错误刮削
同步出错后 在历史记录界面选择重新整理 能正常硬链接转移

没有出现跨盘，权限全都是777
应该是v1.9.0后发现的问题，之前一切正常，最近较频繁

不是全部都会这样 是随机出现的，没办法复现得到更多的日志内容

以下为配置截图：
![image](https://github.com/jxxghp/MoviePilot/assets/90897955/becc1eff-d586-4518-8cdd-df5432a997ba)
![image](https://github.com/jxxghp/MoviePilot/assets/90897955/d6c447c4-160c-4d82-b9e1-0a7f178767f6)

感谢作者回复

**Comment by Exlany** [comment]
这个报错我也碰到过几次，最近还有link目录下的又整理一遍到link目录，可是我的link监控目录都是指定了目的目录的。

**Comment by Putarku** [comment]
有开下载器监控吗，如果开了就没必要开目录同步，两者可能会同时触发导致重复整理

**Comment by TyxTang** [comment]
> 有开下载器监控吗，如果开了就没必要开目录同步，两者可能会同时触发导致重复整理

没开，因为我有多个下载器所以只用了目录同步
且目录同步 不管有没有指定目的目录 都会出现这个问题
