### ISSUE TITLE
[错误报告]: MP会占用威联通的HDMI显示程序PID使之无法工作

### ISSUE THREAD

**Issue by werran2** [jxxghp/MoviePilot#2247]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

latest

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

威联通的HDMI显示程序HD station不显示，经与威联通工程师沟通，是MP占用了HD station的PID所致，必须在MP启动之前启动HD station，否则程序黑屏。工程师说从NT时代就是这样了。

**Comment by zoffyultraman** [comment]
端口映射为其他端口即可，这个不属于bug的范畴啊？

**Comment by werran2** [comment]
> 端口映射为其他端口即可，这个不属于bug的范畴啊？

PID不是端口啊

**Comment by zoffyultraman** [comment]
> > 端口映射为其他端口即可，这个不属于bug的范畴啊？
> 
> PID不是端口啊
不好意思，盲僧了。
但是pid一般为系统自动按id递增分配。

**Comment by werran2** [comment]
> > > 端口映射为其他端口即可，这个不属于bug的范畴啊？
> > 
> > 
> > PID不是端口啊
> > 不好意思，盲僧了。
> > 但是pid一般为系统内核自动按id递增分配。

嗯，但威联通的HDMI显示程序HD station貌似只认固定的PID，被占用则无法启动。MP则不然。

**Comment by zoffyultraman** [comment]
有一个解决方案，或许你可以看看HD station的启动脚本。一般在/etc/init.d/下以程序名命名的。手动启动看下报错，确认是pid问题，应该可以通过编辑该脚本来解决
