### ISSUE TITLE
[错误报告]: 订阅问题（自动下载洗版）（订阅错误的剧集，不会重新下载）

### ISSUE THREAD

**Issue by a1055104544** [jxxghp/MoviePilot#2248]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1.自动下载洗版。订阅中的剧集，如果第一次下载的是1080p，之后有了4k资源它会自动下载4k的，但是我并没有打开洗版开关。
2.订阅错误的剧集，不会重新下载。假如我正在追怪兽八号这个番剧，现在已经出了8集，但是pt站有人发布错误资源，发布了9，10,11集，那么订阅会自动下载，我发现是错误的剧集之后，我把剧集删了，并且把订阅进度重新调整为8/12，那么下周更新了第九集之后，mp不会自动订阅下载这一集了。

**Comment by zoffyultraman** [comment]
剧集删除是指直接删除种子和下载文件吗，历史记录中是否还存在记录的硬链接呢，如果有要一并删除，

**Comment by jxxghp** [comment]
提问题带日志和截图。
第二个不是问题，清订阅缓存或者重新加一下订阅，要么自已手动删的手动下载回去。
