### ISSUE TITLE
[错误报告]: 下载记录一闪就没，历史记录也看不到，请问是什么权限没给到位么？ 谢谢大佬

### ISSUE THREAD

**Issue by xuzhuocool** [jxxghp/MoviePilot#2252]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

载记录一闪就没，历史记录也看不到，请问是什么权限没给到位么？ 谢谢大佬

### 发生问题时系统日志和配置文件

```bash

INFO | 16:02:50,792 | command.py | 处理事件：download.added - []
-- | -- | -- | --
INFO | 16:02:45,065 | command.py | 处理事件：notice.message - []
INFO | 16:02:45,060 | chain | 发送消息：channel=None，title=庆余年 (2019) S02 E26-E27 开始下载, text=用户：admin


```

**Comment by wrlove97** [comment]
Ctrl+F5试下

**Comment by xuzhuocool** [comment]
试过了 不行哈

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月02日 17:51 |
| 收件人 | jxxghp/MoviePilot ***@***.***> |
| 抄送人 | Sky ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jxxghp/MoviePilot] [错误报告]: 下载记录一闪就没，历史记录也看不到，请问是什么权限没给到位么？ 谢谢大佬 (Issue #2252) |

Ctrl+F5试下

**Comment by Govenry** [comment]
> 找到问题了 来回复下，是文件路径配置错误，之前配置的相对路径，改成绝对路径就解决了。

请问是怎么修改的？我的是套件版，也是没有下载记录。谢谢

**Comment by xuzhuocool** [comment]
> > 找到问题了 来回复下，是文件路径配置错误，之前配置的相对路径，改成绝对路径就解决了。
> 
> 请问是怎么修改的？我的是套件版，也是没有下载记录。谢谢

我换回nastools 了，没发给您截图了，只能文字描述了。

之前用的是/mdeia/xxx/xxx   换成 /volume1/media/xxx/xxx

**Comment by Govenry** [comment]
> > > 找到问题了 来回复下，是文件路径配置错误，之前配置的相对路径，改成绝对路径就解决了。
> > 
> > 
> > 请问是怎么修改的？我的是套件版，也是没有下载记录。谢谢
> 
> 我换回nastools 了，没发给您截图了，只能文字描述了。
> 
> 之前用的是/mdeia/xxx/xxx 换成 /volume1/media/xxx/xxx

谢谢
