### ISSUE TITLE
站点认证出错，实在找不到原因了

### ISSUE THREAD

**Issue by baiyefeiyu** [jxxghp/MoviePilot#2255]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1.站点认证失败，新增了几个认证站点还是失败。环境变量应该是没问题的。
2.我卸载豆瓣想看后，无法在插件市场找到豆瓣想看插件了（其他的都还有），我不知道这两个问题有没有关联。

检查了能查的配置，实在找不到问题了，电报群问大家，也没遇到这个问题。
![image](https://github.com/jxxghp/MoviePilot/assets/112963200/f78c8f98-6f0a-41f6-9f6b-c3564f5d5a22)
![image](https://github.com/jxxghp/MoviePilot/assets/112963200/61fe7b3c-a0c6-479b-9499-79165147a49a)

### 发生问题时系统日志和配置文件

```bash
2024/06/02 22:00:26	stdout	[32mINFO:[0m    resource.py - 所有资源已最新，无需更新
2024/06/02 22:00:26	stdout	[32mINFO:[0m    resource.py - 最新资源包版本：v22
2024/06/02 22:00:25	stdout	[32mINFO:[0m    resource.py - 开始检测资源包版本...
2024/06/02 22:00:25	stdout	[31mERROR:[0m   singleton.py - 未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！
2024/06/02 22:00:25	stdout	[31mERROR:[0m   singleton.py - iyuu认证出错：无法连接站点
2024/06/02 22:00:05	stdout	[31mERROR:[0m   singleton.py - zmpt认证出错：无法连接站点
2024/06/02 21:59:45	stdout	[31mERROR:[0m   singleton.py - hdkyl认证出错：无法连接站点
2024/06/02 21:59:25	stdout	[31mERROR:[0m   singleton.py - agsvpt认证出错：无法连接站点
2024/06/02 21:59:05	stdout	[31mERROR:[0m   singleton.py - hhclub认证出错：无法连接站点
2024/06/02 21:58:45	stdout	[32mINFO:[0m    singleton.py - 认证资源版本：1.2.8
2024/06/02 21:58:45	stdout	[32mINFO:[0m    singleton.py - 站点资源版本：1.4.0
2024/06/02 21:58:44	stdout	[32mINFO[0m:     Waiting for application startup.
```

**Comment by zoffyultraman** [comment]
无法链接站点，连通性测试如何呢

**Comment by baiyefeiyu** [comment]
> 无法链接站点，连通性测试如何呢

站点都可以正常登录。
而且现在也没办法正常索引了

**Comment by baiyefeiyu** [comment]
应当是路由器端shellcrash更新后某些规则导致的，现在都添加fake-ip例外，目前正常了。
