### ISSUE TITLE
[错误报告]: 文件管理显示空白

### ISSUE THREAD

**Issue by Anoiing** [jxxghp/MoviePilot#2256]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用最新的镜像启动docker，文件管理显示空白，已经给了特权模式，PUID,PGID都是0。浏览器清过缓存，控制台没有任何报错。
并且试了一下从低版本升级也会有同样的问题。是我哪里设置不对吗？低版本是可以正常显示内容的。
![image](https://github.com/jxxghp/MoviePilot/assets/23634208/b6e1a837-f151-4986-8759-f0f6fb8831b0)

**Comment by zoffyultraman** [comment]
旧版升级的话，注意一下目录设置，重新设置一下下载目录应该就有了？大概

**Comment by jxxghp** [comment]
清浏览器缓存
