### ISSUE TITLE
[Feature Request]: 希望增加搜索方案

### ISSUE THREAD

**Issue by davincilll** [jxxghp/MoviePilot#2257]
### 当前程序版本

最新

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望能够增加搜索方案的选项，对于比较大众的资源只需要使用常用的几个站点就可以了，还可以增加搜索速度，对于比较小众的资源才用全站搜索。
希望能够在结果筛选页增加体积筛选。
希望在季集的筛选将合集放在最上面，这样可能会快速找到自己想要的资源。比如优先将s1-s4放最前面进行筛选。
以上问题是我在手头上站点越来越多的情况下逐渐感觉到的痛点。一开始站少觉得怎么这也没有那也没有😂站多了就感觉这么多资源选起来好麻烦😂

**Comment by cng10001** [comment]
![560F9832](https://github.com/jxxghp/MoviePilot/assets/115156545/daaad22a-213a-4bd5-a99c-2176d1fb97a0)
