### ISSUE TITLE
动漫目录无法添加到指定下载目录

### ISSUE THREAD

**Issue by jkelove** [jxxghp/MoviePilot#2258]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

按照配置文件进行分类后，将动漫统一下载到指定文件夹，但是下载动漫还是会找电视剧这个下载目录
![image](https://github.com/jxxghp/MoviePilot/assets/119661718/ba050aa5-78c8-4868-ade0-2ab6e2f48331)
![Uploading 0ab40c3f-ae13-47da-ae0f-7114b1a67207.jpg…](
![b7a4cacc-1a26-43f2-bf82-105d025d11b4](https://github.com/jxxghp/MoviePilot/assets/119661718/e88b9563-af87-4033-932e-d38a46636d97)
![c513add6-23a4-4c08-8010-df537043dcae](https://github.com/jxxghp/MoviePilot/assets/119661718/1cca9206-fdfa-4d05-88c5-06098f471b28)
![ee258e2a-7424-4ffe-a396-d0cbd836bdee](https://github.com/jxxghp/MoviePilot/assets/119661718/8d42fb57-0c0b-4486-be59-da1d8707ef19)
)

**Comment by HelloKieth** [comment]
同样的问题

**Comment by Mark-li521** [comment]
急需修改这个bug，目前很影响使用

**Comment by interestingexm** [comment]
印象里之前是有动漫的媒体类型的，现在没了

**Comment by cosmotown** [comment]
现在你指定任意目录，然后把动漫目录下面的类型改成电视剧，后面类别改成动漫，最后把这个下载分类放在第一个，就是要在电视剧那个目录前面就可以了

**Comment by Travel2Here** [comment]
+1 前几天有人反馈 被指出tmdb是什么归类就是什么。。。我也是无语了（以往正常呢）。
问题就是本帖这么个问题。求修复~

**Comment by Putarku** [comment]
> +1 前几天有人反馈 被指出tmdb是什么归类就是什么。。。我也是无语了（以往正常呢）。 问题就是本帖这么个问题。求修复~

[近期新问题](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=_194%e7%89%88%e6%9c%ac%e6%9b%b4%e6%96%b0%e5%90%8e%e7%a1%ac%e9%93%be%e6%8e%a5%e8%bd%ac%e7%a7%bb%e5%87%ba%e7%8e%b0-1%e7%9a%84%e6%8a%a5%e9%94%99)

**Comment by Travel2Here** [comment]
> > +1 前几天有人反馈 被指出tmdb是什么归类就是什么。。。我也是无语了（以往正常呢）。 问题就是本帖这么个问题。求修复~
> 
> [近期新问题](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=%e4%bb%8e%e8%80%81%e7%9a%84%e7%9b%ae%e5%bd%95%e9%85%8d%e7%bd%ae%e6%9b%b4%e6%8d%a2%e4%b8%ba%e6%96%b0%e7%9a%84%e7%9b%ae%e5%bd%95)

没错，就是这变化，希望还是保留动漫 甚至建立更多一级分类，而不是都规在电视剧下。
观看体验 分类实用性降低了很多。一团糟~

**Comment by Putarku** [comment]
> > > +1 前几天有人反馈 被指出tmdb是什么归类就是什么。。。我也是无语了（以往正常呢）。 问题就是本帖这么个问题。求修复~
> > 
> > 
> > [近期新问题](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=%e4%bb%8e%e8%80%81%e7%9a%84%e7%9b%ae%e5%bd%95%e9%85%8d%e7%bd%ae%e6%9b%b4%e6%8d%a2%e4%b8%ba%e6%96%b0%e7%9a%84%e7%9b%ae%e5%bd%95)
> 
> 没错，就是这变化，希望还是保留动漫 甚至建立更多一级分类，而不是都规在电视剧下。 观看体验 分类实用性降低了很多。一团糟~

你自己按原来的样子重新设定一下目录就行了，自己适应项目不是让项目适应你

**Comment by Travel2Here** [comment]
> > > > +1 前几天有人反馈 被指出tmdb是什么归类就是什么。。。我也是无语了（以往正常呢）。 问题就是本帖这么个问题。求修复~
> > > 
> > > 
> > > [近期新问题](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=%e4%bb%8e%e8%80%81%e7%9a%84%e7%9b%ae%e5%bd%95%e9%85%8d%e7%bd%ae%e6%9b%b4%e6%8d%a2%e4%b8%ba%e6%96%b0%e7%9a%84%e7%9b%ae%e5%bd%95)
> > 
> > 
> > 没错，就是这变化，希望还是保留动漫 甚至建立更多一级分类，而不是都规在电视剧下。 观看体验 分类实用性降低了很多。一团糟~
> 
> 你自己按原来的样子重新设定一下目录就行了，自己适应项目不是让项目适应你

重按新规设定可以解决问题，但开发项目的目的不是更好的服务需求么？
比如wiki共识的内容分类，电视剧不是跟其他属于并列吗？怎么就属于包含关系了？
<img width="1756" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/99887507/48c21a1a-0346-4f74-a429-1627c9122760">

**Comment by 892899273** [comment]
> 现在你指定任意目录，然后把动漫目录下面的类型改成电视剧，后面类别改成动漫，最后把这个下载分类放在第一个，就是要在电视剧那个目录前面就可以了

我就是这么设置的啊，看我图片说明

**Comment by Putarku** [comment]
> > 现在你指定任意目录，然后把动漫目录下面的类型改成电视剧，后面类别改成动漫，最后把这个下载分类放在第一个，就是要在电视剧那个目录前面就可以了
> 
> 我就是这么设置的啊，看我图片说明

更新一下版本，把动漫的目录拖到最前面
