### ISSUE TITLE
[错误报告]: 订阅重复下载

### ISSUE THREAD

**Issue by Exlany** [jxxghp/MoviePilot#2261]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅采用的RSS，间隔是10min，现状是任务已经在下载中，但是还是会重新的订阅同一个种子下载。或者有时候重复下载同一集数的其他种子。
![1717390266275](https://github.com/jxxghp/MoviePilot/assets/22867870/6fa238dc-2bf8-4d4a-b0ea-47936501961f)

![1717390535850](https://github.com/jxxghp/MoviePilot/assets/22867870/3edf39c5-9ca7-4f17-a4de-4a9c16a0206f)

10分钟之后
![1717390617972](https://github.com/jxxghp/MoviePilot/assets/22867870/11d87bd4-b674-4a2b-94ac-37a9b5ee7597)

**Comment by a1055104544** [comment]
+1
我也是跟你一模一样的问题，情况完全一样

**Comment by Z2112** [comment]
+1
我也是一直订阅一个，但是删除再重新订阅后有概率就每天只订阅一次，不然每小时都在重复订阅同个或者不同的种子。

**Comment by siren44** [comment]
+1
最新1.9.4-1版本，还是有这样的问题，订阅重复下载，我把RSS时间改成半小时还会重复。只能重置订阅，然后订阅那里选手动搜素。

**Comment by lzcer** [comment]
今天也遇到这个问题了，版本v1.9.4-1，之前好像会从下载器获取正在下载的任务来判断是否已经下载，不过最近的日志好像没看到这个逻辑了，是不是逻辑改了

**Comment by jxxghp** [comment]
连媒体库服务器了吗？ 正常是通过媒体库服务器来判重的。

**Comment by jxxghp** [comment]
连媒体服务器了吗？整季的下载是通过检查媒体服务器控重的。

**Comment by jxxghp** [comment]
正在洗版啊，你开了洗版啊。
