### ISSUE TITLE
[Feature Request]: 修改剧集订阅操作流程

### ISSUE THREAD

**Issue by dalamudx** [jxxghp/MoviePilot#2262]
### 当前程序版本

v1.9.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

当前订阅操作流程是，订阅剧集->选中要订阅的季即完成订阅，如果需要进一步修改订阅比如订阅起始集，就得去剧集订阅里修改订阅。
能否改成订阅剧集选中要订阅的季进行订阅，这个时候再弹出来编辑订阅的功能窗口，修改完毕后保存完成剧集订阅操作。
对于前者，有时候稍微慢一点，订阅可能已经生效了，配置还没来得及改，看有没有机会修改成后者这种流程

**Comment by x1186176868** [comment]
这个功能早就有了，老铁，自己去电视剧选项的右下角开启订阅时编辑选项，但是目前存在bug，需要在第一层搜索结果处对着封面点击订阅，已经提交issues让作者修复bug

**Comment by dalamudx** [comment]
好吧，这个还真不知道。。。😅
