### ISSUE TITLE
[错误报告]: 我堡cookie同步正常，MP也能正常获取种子列表，添加下载失败（其他站点均成功）

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [jxxghp/MoviePilot#2263]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.13

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我堡连通性什么的都正常，然后在站点管理那边也能正常获取站点种子列表。然后下载的时候显示失败

已知，站点正常能够下载种子，且账户也在正常使用，没有被ban。
cookie同步正常

![image](https://github.com/jxxghp/MoviePilot/assets/77047823/4acfaba2-7086-4207-a299-4d76a1ce2325)
![image](https://github.com/jxxghp/MoviePilot/assets/77047823/c1e0bc06-f296-4bf8-aebc-11e41aaf9ce2)

![image](https://github.com/jxxghp/MoviePilot/assets/77047823/2ed64195-ab60-4dfa-8e58-3cab84245cc4)
启用debug模式报错

![image](https://github.com/jxxghp/MoviePilot/assets/77047823/486c254f-3650-4d13-a45f-c457f779602e)

在站点列表里启用仿真模式，获取失败 空列表

项目部署在国外服务器，不存在和站点连通性相关的问题，容器内部均能ping通和curl到网站信息

已尝试过增加超时，没有起效

### 发生问题时系统日志和配置文件

```bash
ERROR:   download.py - 下载种子文件失败：NieR Automata Ver1.1a 2023 S01 1080p BluRay x265 FLAC 2.0-7³ACG@OurBits - https://ourbits.club/download.php?id=261102
INFO:    chain - 发送消息：channel=None，title=NieR Automata Ver1.1a 2023 S01 1080p BluRay x265 FLAC 2.0-7³ACG@OurBits 种子下载失败！, text=错误信息：无法打开链接
站点：我堡，userid=None
DEBUG:   event.py - 发送事件：notice.message - {'channel': None, 'type': <NotificationType.Manual: '手动处理通知'>, 'title': 'NieR Automata Ver1.1a 2023 S01 1080p BluRay x265 FLAC 2.0-7³ACG@OurBits 种子下载失败！', 'text': '错误信息：无法打开链接\n站点：我堡', 'image': None, 'userid': None}
INFO:    command.py - 处理事件：notice.message - []
DEBUG:   chain - 请求模块执行：post_message ...


ERROR:   download.py - 下载种子文件失败：Frieren Beyond Journey's End S01 2023 REPACK 1080p ABEMA WEB-DL H264 AAC-OurTV - https://ourbits.club/download.php?id=253961
INFO:    chain - 发送消息：channel=None，title=Frieren Beyond Journey's End S01 2023 REPACK 1080p ABEMA WEB-DL H264 AAC-OurTV 种子下载失败！, text=错误信息：无法打开链接
站点：我堡，userid=None
DEBUG:   event.py - 发送事件：notice.message - {'channel': None, 'type': <NotificationType.Manual: '手动处理通知'>, 'title': "Frieren Beyond Journey's End S01 2023 REPACK 1080p ABEMA WEB-DL H264 AAC-OurTV 种子下载失败！", 'text': '错误信息：无法打开链接\n站点：我堡', 'image': None, 'userid': None}
INFO:    command.py - 处理事件：notice.message - []
DEBUG:   chain - 请求模块执行：post_message ...
INFO:     103.149.249.237:0 - "POST /api/v1/download/ HTTP/1.1" 200 OK
```

**Comment by 907739769** [comment]
一样的问题 怎么解决的？

**Comment by AJHarris-Large** [comment]
> > 一样的问题 怎么解决的？
> 
> 首种没点掉

抱歉小白有点没听明白，怎么点到啊？
谢谢大神！

**Comment by xzdbadboy** [comment]
> > 一样的问题 怎么解决的？
> 
> 首种没点掉

什么首种啊，不理解啊

**Comment by jinshenganyuci** [comment]
> > 同样的问题怎么解决的？
> 
> 首种没点掉

哥们这个是啥意思

**Comment by manbading** [comment]
在日志里查看报错，把链接打开是一个首次下载的提示，点一下之后下载就不会报错了
