### ISSUE TITLE
[错误报告]: 自动转移做种插件连接TR失败

### ISSUE THREAD

**Issue by Devinaille** [jxxghp/MoviePilot#2264]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

不确定是主程序还是插件导致的问题。
在【设定】-【连接】-【Transmission】页面中设置TR的地址为`http://192.168.0.10:10109`

![image](https://github.com/jxxghp/MoviePilot/assets/10932565/1205e066-098b-41fc-9aa0-fdf9ff61dd10)

但自动转移做种插件读到的地址是`http`，把剩下的`//192.168.0.10:10109`读成了url，怀疑是切字符串定位错误

将TR地址设置为`192.168.0.10:10109`就能正常了

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-06-04 08:27:50,398 - transmission.py - transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.0.10:10109/transmission/rpc (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f44146c1290>: Failed to resolve 'http' ([Errno -2] Name or service not known)"))
```

**Comment by AisukaYuki** [comment]
下方提示备注应该是历史遗留，代码改了备注没有改，地址只要 域名 or IP +端口就行，不只tr，qb的也是一样的。

**Comment by Devinaille** [comment]
但实际上qb按以前的写法工作正常

**Comment by AisukaYuki** [comment]
> 但实际上qb按以前的写法工作正常

https://github.com/jxxghp/MoviePilot/blob/0fc7d883c028535b36a5e3dff33cac4d1c5d0ecc/app/modules/transmission/transmission.py#L34

**Comment by Devinaille** [comment]
了解，等更新

**Comment by HalcyonDaysssss** [comment]
怎么解决的？
