### ISSUE TITLE
[Feature Request]: 希望增加一些Py依赖库配置和github源码下载的代理

### ISSUE THREAD

**Issue by weni09** [jxxghp/MoviePilot#2268]
### 当前程序版本

1.9.3

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前的https://mirror.ghproxy.com/只代理了raw.githubusercontent.com， 希望增加Py依赖库配置项可自定义配置源,如国内的阿里和豆瓣，github源码下载是也大量消耗代理流量，建议增加设置github.com代理的功能；如此就能放心大胆开户自动更新，不怕流量消耗了

**Comment by htyjswf** [comment]
作者更新了

**Comment by weni09** [comment]
> 作者更新了

配置那个只代理了 [raw.githubusercontent.com]， 希望增加pypi.org、github.com，api.telegram.org的代理自定义配置
