### ISSUE TITLE
[Feature Request]: 希望增强优先级规则的扩展能力

### ISSUE THREAD

**Issue by jsl9208** [jxxghp/MoviePilot#2269]
### 当前程序版本

v1.9.3

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

MP是很棒的项目，敬佩大佬的工作。个人使用上感觉目前的优先级规则不太够用，比如希望不同媒体目录选用不同优先级（如电视剧、电影区分规则），或者规则本身想要有更多扩展性（如按指定制作组洗版）、或者矩阵优先级（如希望分辨率优先4K，同分辨率优先杜比等等，目前规则下需要很复杂的配置才能实现）。
我阅读FilterModule源码发现目前逻辑是比较定死的，是否考虑允许通过插件扩展这部分规则？如果有这个想法的话我可以contribute

**Comment by loveu5522** [comment]
是的，比如一些其他如“字幕”能否添加一个全局默认匹配规则，就不要在每一个规则上添加，直接设置一个全局规则比如 特效字幕》中文字幕》无字幕这样。
