### ISSUE TITLE
订阅搜索报错

### ISSUE THREAD

**Issue by aiwu12** [jxxghp/MoviePilot#227]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5-1.0.8

### 问题类型

主程序运行问题

### 问题描述
必现问题
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/aab9bffb-b774-46ef-871a-997b070f31ae)
![image](https://github.com/jxxghp/MoviePilot/assets/61082200/1b6b259b-a4ec-443a-945e-0137f603d5f8)

**Comment by jxxghp** [comment]
#330
