### ISSUE TITLE
[错误报告]: 用不了资源搜索

### ISSUE THREAD

**Issue by Wuyingman** [jxxghp/MoviePilot#2271]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/89672551/b1766cd8-4ae7-42ca-a6e2-9ff4b8f954b7)
![f5542736d0ed576b90b43fe32e2e81f2](https://github.com/jxxghp/MoviePilot/assets/89672551/4c12f3f2-bd56-405e-95f6-09593baaa2dd)
![e3c1cfb9c06ff6fa35e8ac42099f03d1](https://github.com/jxxghp/MoviePilot/assets/89672551/d716927a-7dca-4933-9971-7ac11b576853)

**Comment by jxxghp** [comment]
看更新说明
