### ISSUE TITLE
[错误报告]: 订阅电视剧 修改订阅站点无效

### ISSUE THREAD

**Issue by chenpt0809** [jxxghp/MoviePilot#2273]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅电视剧后，修改订阅站点单选保存成功后，点击该订阅搜索后，保存的订阅站点信息丢失。

**Comment by chenpt0809** [comment]
[img]https://img.gejiba.com/images/7ffc4c5ce30f1925e786ef8922442e5a.png[/img]
[img]https://img.gejiba.com/images/60f0b3191c20a9f17115fc80e4930b14.png[/img]

**Comment by jxxghp** [comment]
那个站点没在订阅站点范围内了吧

**Comment by chenpt0809** [comment]
> 那个站点没在订阅站点范围内

抱歉 我查看了一下的确是的，看到后台有RSS日志我以为不选择是默认全部。
