### ISSUE TITLE
模块 EmbyModule.media_exists与模块ileTransferModule.media_exists老是报错

### ISSUE THREAD

**Issue by leisurelydeer** [jxxghp/MoviePilot#2274]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

模块 EmbyModule.media_exists与模块ileTransferModule.media_exists老是报错，我也尝试过重置仍然报这个错误

### 发生问题时系统日志和配置文件

```bash
2024/06/06 12:59:16	stdout	AttributeError: 'dict' object has no attribute 'category'
2024/06/06 12:59:16	stdout	[31mERROR:[0m   chain - 运行模块 FileTransferModule.media_exists 出错：'dict' object has no attribute 'category'
2024/06/06 12:59:16	stdout	AttributeError: 'dict' object has no attribute 'type'
2024/06/06 12:59:16	stdout	[31mERROR:[0m   chain - 运行模块 EmbyModule.media_exists 出错：'dict' object has no attribute 'type'
```

**Comment by leisurelydeer** [comment]
<html>
<body>

2024/06/06 12:59:16 | stdout |  
-- | -- | --
2024/06/06 12:59:16 | stdout | AttributeError: 'dict' object has no attribute 'category'
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | if not target_dir.category and target_dir.auto_category and mediainfo.category:
2024/06/06 12:59:16 | stdout | File "/app/app/modules/filetransfer/__init__.py", line 426, in __get_dest_dir
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | target_dir = self.__get_dest_dir(mediainfo=mediainfo, target_dir=dest_path)
2024/06/06 12:59:16 | stdout | File "/app/app/modules/filetransfer/__init__.py", line 714, in media_exists
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | result = func(*args, **kwargs)
2024/06/06 12:59:16 | stdout | File "/app/app/chain/__init__.py", line 107, in run_module
2024/06/06 12:59:16 | stdout | Traceback (most recent call last):
2024/06/06 12:59:16 | stdout | [31mERROR:[0m   chain - 运行模块 FileTransferModule.media_exists 出错：'dict' object has no attribute 'category'
2024/06/06 12:59:16 | stdout | [32mINFO:[0m    command.py - 处理事件：system.error - []
2024/06/06 12:59:16 | stdout |  
2024/06/06 12:59:16 | stdout | AttributeError: 'dict' object has no attribute 'type'
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | if mediainfo.type == MediaType.MOVIE:
2024/06/06 12:59:16 | stdout | File "/app/app/modules/emby/__init__.py", line 72, in media_exists
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | result = func(*args, **kwargs)
2024/06/06 12:59:16 | stdout | File "/app/app/chain/__init__.py", line 107, in run_module
2024/06/06 12:59:16 | stdout | Traceback (most recent call last):
2024/06/06 12:59:16 | stdout | [31mERROR:[0m   chain - 运行模块 EmbyModule.media_exists 出错：'dict' object has no attribute 'type'
2024/06/06 12:59:16 | stdout | [32mINFO:[0m    command.py - 处理事件：system.error - []
2024/06/06 12:59:16 | stdout |  
2024/06/06 12:59:16 | stdout | AttributeError: 'dict' object has no attribute 'category'
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | if not target_dir.category and target_dir.auto_category and mediainfo.category:
2024/06/06 12:59:16 | stdout | File "/app/app/modules/filetransfer/__init__.py", line 426, in __get_dest_dir
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | target_dir = self.__get_dest_dir(mediainfo=mediainfo, target_dir=dest_path)
2024/06/06 12:59:16 | stdout | File "/app/app/modules/filetransfer/__init__.py", line 714, in media_exists
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | result = func(*args, **kwargs)
2024/06/06 12:59:16 | stdout | File "/app/app/chain/__init__.py", line 107, in run_module
2024/06/06 12:59:16 | stdout | Traceback (most recent call last):
2024/06/06 12:59:16 | stdout | [31mERROR:[0m   chain - 运行模块 FileTransferModule.media_exists 出错：'dict' object has no attribute 'category'
2024/06/06 12:59:16 | stdout | [32mINFO:[0m    command.py - 处理事件：system.error - []
2024/06/06 12:59:16 | stdout |  
2024/06/06 12:59:16 | stdout | AttributeError: 'dict' object has no attribute 'type'
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | if mediainfo.type == MediaType.MOVIE:
2024/06/06 12:59:16 | stdout | File "/app/app/modules/emby/__init__.py", line 72, in media_exists
2024/06/06 12:59:16 | stdout | ^^^^^^^^^^^^^^^^^^^^^
2024/06/06 12:59:16 | stdout | result = func(*args, **kwargs)
2024/06/06 12:59:16 | stdout | File "/app/app/chain/__init__.py", line 107, in run_module
2024/06/06 12:59:16 | stdout | Traceback (most recent call last):
2024/06/06 12:59:16 | stdout | [31mERROR:[0m   chain - 运行模块 EmbyModule.media_exists 出错：'dict' object has no attribute 'type'


</body>
</html>

具体docker日志如上

**Comment by jxxghp** [comment]
查不到原因，是使用官方的镜像且没有修改代码吗，从日志看一些class都变成了dict，原因不明。

**Comment by leisurelydeer** [comment]
是的，使用的是官方镜像并且没有修改代码，这是我的mp的全部日志jxxghp-moviepilot (3).txt - 蓝奏云 (lanzn.com)，因为兰奏云的限制我把后缀名改为txt了。如果还是查不到原因的话就不用浪费开发者你的时间了，辛苦你了开发者


Agoin゛
***@***.***




愿你我未来可期~


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jxxghp/MoviePilot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月14日(星期五) 上午9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jxxghp/MoviePilot] 模块 EmbyModule.media_exists与模块ileTransferModule.media_exists老是报错 (Issue #2274)





 
查不到原因，是使用官方的镜像且没有修改代码吗，从日志看一些class都变成了dict，原因不明。

**Comment by xiaobaiwaf** [comment]
哈哈哈，我也有这个问题
