### ISSUE TITLE
[错误报告]: 媒体库目录配置无效

### ISSUE THREAD

**Issue by gxterry** [jxxghp/MoviePilot#2280]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/25121242/8797f9a0-fb87-4b54-ac68-9a796a071d56)
媒体库配置网盘  综艺目录 为 /115/媒体库
![image](https://github.com/jxxghp/MoviePilot/assets/25121242/16e4b2a0-1895-4437-9f39-85586d6b1219)
整理刮削后 转移目录并非 /115/媒体库  而是 /115/媒体库/电视剧
按目录配置来说，综艺目录不是高于电视剧目录吗？

**Comment by cng10001** [comment]
综艺改成/115/媒体库/综艺

**Comment by gxterry** [comment]
> 综艺改成/115/媒体库/综艺

好我试试，上个版本这个配置可以，带上综艺不行，好哒这个版本我试过

**Comment by gxterry** [comment]
无解并没用，怎么试都不行...感觉只能默认目录规则了

**Comment by cng10001** [comment]
照理按你转移目录，也应该是/115/媒体库/克拉克森的农场（2023） 是吧！

你上面那个qbdowns也不正常吗

看到是有挺多人贴的媒体库目录顺序是对的，但是似乎二级分类没生效的，那可能是docker环境其他地方配置问题了- -

**Comment by gxterry** [comment]
> 照理按你转移目录，也应该是/115/媒体库/克拉克森的农场（2023） 是吧！
> 
> 你上面那个qbdowns也不正常吗
> 
> 看到是有挺多人贴的媒体库目录顺序是对的，但是似乎二级分类没生效的，那可能是docker环境其他地方配置问题了- -
按目录的意思应该是/115/媒体库/综艺/克拉克森的农场（2023）
当然我也尝试了配置成 /115/媒体库/综艺
![image](https://github.com/jxxghp/MoviePilot/assets/25121242/1b11b248-61b4-44b7-8924-1af614cf2b50)
为啥配置成/115/媒体库 呢是因为上两个版本我发现配置 /115/媒体库/综艺  出来的结果是/115/媒体库/综艺/综艺/克拉克森的农场（2023）
下载目录没测试,应该没啥问题本来也不分
但是这个 媒体库 就离大谱
我检查了 app.evn 把相关的配置都删除了, 检查了user.db  LibraryDirectories的内容也web页面显示一致
就是不生效.....

**Comment by gxterry** [comment]
@jxxghp   求解答

**Comment by gxterry** [comment]
@thsrite  大佬可能是云盘实时监控 v2.1 插件的问题
测试下来 正常走本地下载没问题 能命中分类到动漫到一级目录
但是云盘监控这边不行- -无论怎么配置，都是走的云盘媒体库的根目录并默认分类 如上图

**Comment by cng10001** [comment]
意思就是你qbdowns就是正常能分类的是吧？
而且你qbdowns也分了综艺的
你不早试一下

**Comment by gxterry** [comment]
> 意思就是你qbdowns就是正常能分类的是吧？ 而且你qbdowns也分了综艺的 你不早试一下

草率了，一直以为插件在整理的时候调用的同一个方法，直到看了 mp 的代码感觉没啥问题，才去看插件的.....

**Comment by thsrite** [comment]
> @thsrite 大佬可能是云盘实时监控 v2.1 插件的问题 测试下来 正常走本地下载没问题 能命中分类到动漫到一级目录 但是云盘监控这边不行- -无论怎么配置，都是走的云盘媒体库的根目录并默认分类 如上图

插件配置 监控目录加上`@False`。试试
