### ISSUE TITLE
[错误报告]: 下载器监控媒体库自动二级目录分类，有时灵有是不灵

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#2281]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

有时会自动分类，有时不会
![截图_20240607001132](https://github.com/jxxghp/MoviePilot/assets/44762565/e484fc3d-71f8-49b3-b3ca-ec1f5a658c2e)

**Comment by Travel2Here** [comment]
+1，不仅是二级类目整理，一级分类也会如此 比如动漫作品 有时候会归去电视剧…

**Comment by cddjr** [comment]
> +1，不仅是二级类目整理，一级分类也会如此 比如动漫作品 有时候会归去电视剧…

这个取决于TMDB上配置的什么分类

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/5741e8e8-1e3d-4c2f-bd34-1909c11e79c6)
会不会是网络问题

**Comment by zoffyultraman** [comment]
我觉得第一个怎么是目录监控链接的，你没有开启这个插件吗，因为他并没有识别这个电影是不是外语电影。当然，也有可能是楼上所说的网络问题。

**Comment by LunaticXJ** [comment]
我也有这种情况，我理解就算出现了网络问题没有识别成功，那也应该放在未分类文件夹中，以便后续网络好了，可以直接手动重新整理未分类下的文件，建议优化下哈

**Comment by yejialiango** [comment]
我也遇到了这个问题，有时候好使有时候不好使，自己手工再去识别二级分类是能识别出来的

**Comment by PittsAi** [comment]
遇到了同样的问题，我还以为是哪里设置错了
