### ISSUE TITLE
[错误报告]: 豆瓣想看的插件在豆瓣添加想看，太多的话不会更新也不会订阅

### ISSUE THREAD

**Issue by lifujie25** [jxxghp/MoviePilot#2282]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

[错误报告]: 豆瓣想看的插件在豆瓣添加想看，太多的话不会更新也不会订阅

**Comment by jxxghp** [comment]
只会更新最近10条，仅用于增量内容的刷新。
