### ISSUE TITLE
[错误报告]: 容器重启后，微信通知就会失效。

### ISSUE THREAD

**Issue by 26930555** [jxxghp/MoviePilot#2285]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

重启后，微信就不接收各类信息了

### 发生问题时系统日志和配置文件

```bash
系统健康检查 微信正常
```

**Comment by gxterry** [comment]
1. 是否正确映射了配置文件目录相关文件夹
2. 不知道你的重启指什么~如果是路由器 公网IP是否变动，是否配置了微信代理 
自查相关信息，这里应该不存在BUG
