### ISSUE TITLE
[错误报告]: 搜索到的内容不全，站点有的并没有显示在搜索结果里

### ISSUE THREAD

**Issue by ck-drink** [jxxghp/MoviePilot#2290]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

搜索到的内容不全，站点有的并没有显示在搜索结果里

**Comment by lovefan-fan** [comment]
请问一下是什么原因呢，我目前也遇到了这样的情况，使用pptp和站点手动查询的数据都比mp搜到的多
