### ISSUE TITLE
[错误报告]: Movie Pilot团队的大佬们，你们好！请求移除认证站点PTLSP～

### ISSUE THREAD

**Issue by PTLSP** [jxxghp/MoviePilot#2291]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

～

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

Movie Pilot团队，你们好！

感谢作者当初您当初对我的雪中送炭，二话不说就支持了PTLSP的认证站请求
真的非常感谢你们！这给了我继续维护建设站点很大的动力！
我也很早以前就是Nastools的忠实用户，当时就享受到了很多大佬的提供的帮助
感谢你们做的这款软件，给了我们那么好的观影体验。

直到我有能力做点什么，也想着喝水不忘挖井人，尽可能的不给你们添麻烦的同时，能出一份自己的力。
但因为我的个人恩怨，导致站点无法再继续运营下去了，我终于可以解放不在牵连我在意的人了～
所以我再次来向你们表示感谢，同时请求你们把PTLSP默默移出适配站点就好了。
祝福你们能够好好继续做下去，一定要保护好自己！我会继续支持你们的！！！

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by yangtao521** [comment]
默哀
