### ISSUE TITLE
[错误报告]: 新版入库错误码：-1

### ISSUE THREAD

**Issue by Secular2020** [jxxghp/MoviePilot#2293]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

更新1.9.4后 电影 剧集 入库均提示 错误码：-1

### 发生问题时系统日志和配置文件

```bash
18:50:45,525	
transfer.py
末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v 入库失败：错误码：-1
ERROR	18:50:45,524	
filetransfer
文件 /Media/电影/华语电影/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v 转移失败，错误码：-1
ERROR	18:50:45,522	
filetransfer
文件 /Media/电影/华语电影/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v link失败，错误码：-1
ERROR	18:50:45,520	
filetransfer
[Errno 18] Invalid cross-device link: '/Media/电影/华语电影/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v' -> '/link/Media/电影/华语电影/末路狂花钱 (2024)/末路狂花钱 (2024) - 2160p.m4v.mp'
INFO	18:50:45,518	
filetransfer
正在转移文件：/Media/电影/华语电影/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB/末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v 到 /link/Media/电影/华语电影/末路狂花钱 (2024)/末路狂花钱 (2024) - 2160p.m4v
INFO	18:50:45,509	
filetransfer
获取转移目标路径：/link/Media/电影/华语电影
INFO	18:50:45,504	
transfer.py
末路狂花钱.The.Last.Frenzy.2024.2160p.WEB-DL.DDP5.1.H265.DV-HDSWEB.m4v 识别为：电影 末路狂花钱 (2024)
```

**Comment by Secular2020** [comment]
在 MOVIEPILOT 文件管理中 查看保存目录下看不到新增加的影视剧集文件，在NAS文件管理里是有的，并且可以正常播放。

**Comment by cddjr** [comment]
Invalid cross-device link说的很明显了，跨盘了。

**Comment by Secular2020** [comment]
> 跨设备链接无效说的响了，硬链接跨盘失败了

其实并没有跨盘，是同盘。

**Comment by Putarku** [comment]
> > 跨设备链接无效说的响了，硬链接跨盘失败了
> 
> 其实并没有跨盘，是同盘。

你的目录配置一直都错了，应该是/media/download转移到/media/link才对，直接/download转移到/link就是错误的

**Comment by Secular2020** [comment]
WARNING | 20:14:34,852 | transfer.py | Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 入库失败：错误码：-1
-- | -- | -- | --
ERROR | 20:14:34,851 | filetransfer | 文件 /Media/动漫/斗破苍穹.Fights.Break.Sphere.2022.S05.WEB-DL.2160p.H265.AAC-PTerWEB/Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 转移失败，错误码：-1
ERROR | 20:14:34,850 | filetransfer | 文件 /Media/动漫/斗破苍穹.Fights.Break.Sphere.2022.S05.WEB-DL.2160p.H265.AAC-PTerWEB/Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 link失败，错误码：-1
ERROR | 20:14:34,848 | filetransfer | [Errno 18] Invalid cross-device link: '/Media/动漫/斗破苍穹.Fights.Break.Sphere.2022.S05.WEB-DL.2160p.H265.AAC-PTerWEB/Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4' -> '/link/Media/动漫/斗破苍穹 (2017)/Season 5/斗破苍穹 - S05E100 - 第 100 集.mp4.mp'
INFO | 20:14:34,846 | filetransfer | 正在转移文件：/Media/动漫/斗破苍穹.Fights.Break.Sphere.2022.S05.WEB-DL.2160p.H265.AAC-PTerWEB/Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 到 /link/Media/动漫/斗破苍穹 (2017)/Season 5/斗破苍穹 - S05E100 - 第 100 集.mp4
INFO | 20:14:34,842 | filetransfer | 获取转移目标路径：/link/Media/动漫
INFO | 20:14:34,831 | transfer.py | Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 识别为：电视剧 斗破苍穹 (2017)
INFO | 20:14:34,825 | media.py | Fights.Break.Sphere.2022.S05E100.2160p.WEB-DL.H265.AAC-PTerWEB.mp4 识别到媒体信息：电视剧 斗破苍穹 (2017)
INFO | 20:14:34,820 | themoviedb | Fights Break Sphere TMDB识别结果：电视剧 斗破苍穹 (2017) 79481
INFO | 20:14:34,815 | themoviedb | Fights Break Sphere 使用TMDB识别缓存：斗破苍穹

**Comment by cddjr** [comment]
> > 跨设备链接无效说的响了，硬链接跨盘失败了
> 
> 其实并没有跨盘，是同盘。

在Docker看来，就属于跨盘了。你重新映射路径吧，别犟，问就是Docker设定如此。

**Comment by Secular2020** [comment]
> > > 原文链接：https://www.youtube.com/watch?v= 1
> > 
> > 
> > 其实并没有跨盘，是同盘。
> 
> 在Docker看来，就属于跨盘了。你重新映射路径吧，别问，就是设定Docker如此。

好我重新映射下目录

**Comment by Secular2020** [comment]
> > > 原文链接：https://www.youtube.com/watch?v= 1
> > 
> > 
> > 其实并没有跨盘，是同盘。
> 
> 你的目录配置一直都错误，应该是/media/download导致/media/link才对，直接/download导致/link就是错误

这不只是目录名字顺序的问题吗？
MP自动分类下载 /Media/电影/华语电影/ 后 自动链接至 /link/Media/电影/华语电影/ 下

**Comment by Secular2020** [comment]
> > > 原文链接：https://www.youtube.com/watch?v= 1
> > 
> > 
> > 其实并没有跨盘，是同盘。
> 
> 在Docker看来，就属于跨盘了。你重新映射路径吧，别问，就是设定Docker如此。

重新映射后还是如此，我觉得是MP找不到文件的问题，因为MP的文件管理里根本就看到到新加入的资源，但实际是存在的。。。NAS是极空间，这个版本提到了针对极空间的优化，是不是哪里出了问题，1.9.3是正常的。

**Comment by Secular2020** [comment]
![Uploading Snipaste_2024-06-08_20-35-48.jpg…]()

**Comment by Secular2020** [comment]
![Uploading Snipaste_2024-06-08_20-35-48.jpg…]()

**Comment by InfinityPacer** [comment]
https://github.com/jxxghp/MoviePilot/issues/735

**Comment by Secular2020** [comment]
> https://github.com/jxxghp/MoviePilot/issues/735

大致看懂了这个讨论的目录问题，但是之前版本都正常，更新一个版本就出问题了，媒体库路径修改起来会牵扯很多东西，属实挺头大，不行就只能退回1.9.3版本了 。。。

**Comment by InfinityPacer** [comment]
@Secular2020 如果你这个版本有问题，说明你的之前大概率有问题，快用自动诊断插件看下吧。

**Comment by Secular2020** [comment]
> @Secular2020 如果你这个版本有问题，说明你的之前大概率有问题，快用自动诊断插件看下吧。

我直接将根目录映射进了MP这样媒体存储和硬连接的目录就都在一个主目录下了，之后再次测试，正常了。

**Comment by log-time** [comment]
老问题了，如果是NT过来的，就应该知道，docker目录映射的时候应该映射源文件目录和硬链文件目录共同的上级目录给MP，以避免报错误码-1（跨盘错误）。这个是作者一开始的时候就提醒过的。

**Comment by shanmaoss** [comment]
感谢楼上各位老哥 我也是新版本之后入库错误码-1  仔细对照后发现确实是跨盘复制了

**Comment by lijiai** [comment]
我也是这个问题，1.9.4之前的版本没有任何问题，昨天更新了1.9.4后 各种入库失败，看日志是硬链接失败，我的设备是威联通，之前一直都没有这个问题，仔细查看更新日志中有对别的品牌nas创建硬链接的优化，估计是改什么了，哎

**Comment by Putarku** [comment]
> 我也是这个问题，1.9.4之前的版本没有任何问题，昨天更新了1.9.4后 各种入库失败，看日志是硬链接失败，我的设备是威联通，之前一直都没有这个问题，仔细查看更新日志中有对别的品牌nas创建硬链接的优化，估计是改什么了，哎

有错误代表你之前就有配置错误的情况，这次更新以后才暴露出来，爬楼看看别人怎么配置的吧

**Comment by cddjr** [comment]
> 我也是这个问题，1.9.4之前的版本没有任何问题，昨天更新了1.9.4后 各种入库失败，看日志是硬链接失败，我的设备是威联通，之前一直都没有这个问题，仔细查看更新日志中有对别的品牌nas创建硬链接的优化，估计是改什么了，哎

说明你之前都是意外变成复制转移了，有时间在这里哎来哎去，也不愿意看看别人是怎么解决这个问题的，还在这里瞎猜个啥。

**Comment by Putarku** [comment]
> 1.9.4版本之前确实没有这个问题，都设置成media目录下硬链接是可以了，但是自动订阅下载时推送给qb的目录变成media了，显然不对。那映射downloads目录有什么用呢？nt下载器目录那里有设置下载目录和nas访问目录的设置，mp没有。

所以不要映射download目录啊，映射一个大的父目录，媒体库和下载目录都包含在里面就行。另外mp和qb的目录映射应保持一致，这样mp发送的下载路径两者才都可以正常识别

**Comment by lijiai** [comment]
> > 我也是这个问题，1.9.4之前的版本没有任何问题，昨天更新了1.9.4后 各种入库失败，看日志是硬链接失败，我的设备是威联通，之前一直都没有这个问题，仔细查看更新日志中有对别的品牌nas创建硬链接的优化，估计是改什么了，哎
> 
> 说明你之前都是意外变成复制转移了，有时间在这里哎来哎去，也不愿意看看别人是怎么解决这个问题的，还在这里瞎猜个啥。

首先，软件具有很高的容错性、兼容性才是正道，单一的最求所谓的正确配置并不可取，其次，你怎么知道我没有解决这个问题呢？我只是与有相同经历的人一起共勉，还有你既然没有帮助别人解决问题的能力，那回复的意义又是什么呢？

**Comment by linxc-0515** [comment]
> > 1.9.4版本之前确实没有这个问题，都设置成media目录下硬链接是可以了，但是自动订阅下载时推送给qb的目录变成media了，显然不对。那映射downloads目录有什么用呢？nt下载器目录那里有设置下载目录和nas访问目录的设置，mp没有。
> 
> 所以不要映射download目录啊，映射一个大的父目录，媒体库和下载目录都包含在里面就行。另外mp和qb的目录映射应保持一致，这样mp发送的下载路径两者才都可以正常识别

就是这个问题了，以前就是不希望qb访问下载目录以外的地方才没有把上级的media目录映射进去，以前的ns也可以设置ns下载目录对应qb的下载目录。换到mp以后为了保持mp和qb的下载目录一致才单独映射了download

1.9.4问题暴露出来了，只能重新整理了，一方面是不知道占用了多少重复空间，另一方面换成正确的映射qb的路径就出问题了

**Comment by phxufeng** [comment]
我原来正常的。更新到这个版本后，我也遇到同样的问题了。我的路径还是参照以前 tool 的方法设置路径的。

**Comment by InfinityPacer** [comment]
@phxufeng 请使用自动诊断插件进行验证，如有异常，请按自动诊断配置页提示，参阅 #735 后调整目录映射
