### ISSUE TITLE
[错误报告]: 主页推荐内点击“流行趋势”‘’正在热映“等报错、文件管理无法打开

### ISSUE THREAD

**Issue by chaojiec** [jxxghp/MoviePilot#2294]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

主页推荐内点击“流行趋势”‘’正在热映“等报错，日志里没有说明问题，实在是整不明白了，望作者能解答疑惑。
文件管理则是点不开，上方一直在读条。
![1238190046](https://github.com/jxxghp/MoviePilot/assets/128401073/bcf3196d-4cf3-4364-9a59-922a1d69ac2c)

**Comment by cddjr** [comment]
ctrl+f5 试试看

**Comment by chaojiec** [comment]
> Ctrl+F5 试试看

感谢感谢朋友真的可以，我比较小白不太懂原理，但是解决了！！！谢谢您！！

**Comment by cddjr** [comment]
> > Ctrl+F5 试试看
> 
> 感谢感谢朋友真的可以，我比较小白不太懂原理，但是解决了！！！谢谢您！！

mp每次更新后，最好都这样操作，让浏览器强制刷新。

**Comment by cng10001** [comment]
出问题的大部分都不记得看更新日志- -
