### ISSUE TITLE
每次重启容器后，设定的下载和媒体库目录不能锁定，会变更

### ISSUE THREAD

**Issue by cosmotown** [jxxghp/MoviePilot#2297]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

现在情况是这样，就是自从新版本更改目录结构后，我设置了独立目录，然后每次重启，设置的目录就没有了，多了好多个我没有设置的目录，也不知道为什么。比如我下载这样设置的，/downloads/电影，/downloads/电视剧，/anime/动漫，其中动漫那个是独立的盘，设置的分类是电视剧-动漫，然后重启后动漫那个盘变成了动漫-全部，下面又多了个下载目录/downloads。媒体库目录更夸张，我只设了三个盘的link，然后重启后它在我动漫那个盘下面分别建立了电视剧和电影的媒体库，分类也改了，我也不知道问题在哪

**Comment by zoffyultraman** [comment]
我觉得是你的app.env导致的，可以检查一下。

**Comment by x1186176868** [comment]
尝试删除app.env或者环境变量中的相关配置，环境变量＞app.env＞webui
建议重新配置moviepilot

**Comment by jxxghp** [comment]
环境变量里面的优先级高于所有配置文件和界面里的设置

**Comment by cosmotown** [comment]
我去看了下，我的环境变量并没有配置下载目录，app.env这个文件也没有在安装目录看到，蛮奇怪的，我在变量里加入目录看看

**Comment by cosmotown** [comment]
我已经删除了.env下的媒体库目录变量，环境变量那里也没有配置目录，然后重启容器，它任然在我的/downloads下创建了动漫目录，并且在anime目录下增加了电视剧与电影目录，我原来设置的动漫目录也变了，并且目录类型变成了新的目录结构已经不存在的动漫，正常应该只有电视剧和电影的。然后如果我在环境变量里增加了目录的变量，重启后也没有任何变化
