### ISSUE TITLE
[Feature Request]: 自定义管理员账号

### ISSUE THREAD

**Issue by xmxu2022** [jxxghp/MoviePilot#2303]
### 当前程序版本

*

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前只能使用admin作为管理员账号，希望可以自定义管理员账号及增加设置添加的账号可以作为管理员，这样可以增强外网访问的安全性，防止被暴力破解密码。

### 参考资料

nastool

**Comment by jifengguo** [comment]
可以定义啊，部署前至少认真读一次README吧。

❗SUPERUSER： 超级管理员用户名，默认admin，安装后使用该用户登录后台管理界面，注意：启动一次后再次修改该值不会生效，除非删除数据库文件！
