### ISSUE TITLE
[错误报告]: 目录监控功能整理文件时系统抓取识别词错误无法识别准确信息

### ISSUE THREAD

**Issue by lovemustardy** [jxxghp/MoviePilot#2304]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

使用目录监控功能时遇到识别问题，且频率较高。系统截取识别词不准确导致无法正确识别tmdb信息。
如Big.Mouth.S01E14.2022.Disney+.WEB-DL.1080p.H264.AAC-.mkv以Big Mouth识别可正确识别相关内容，系统采用的识别词为Big Outh与实际不符
如The Sound of Your Heart S01E01 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv系统识别词采用He Sound Of Our Heart与实际不符
又比如Kung.Fu.Yoga不按Kung Fu Yoga识别，按Kung Fu Oga识别，识别不到。又比如To.Kill.with.Intrigue按O Kill With Intrigue识别无法识别准确信息。
尝试修改识别词加入中文名称可正常识别，但考虑工作量巨大，故寻求除自定义此表和手动识别外的更佳解决方案

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-06-09 22:12:07,889 - chain - 发送消息：channel=None，title=Big.Mouth.S01E14.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息，无法入库！, text=回复：
【WARNING】2024-06-09 22:12:07,803 - transfer.py - /media/影视源文件/日韩剧/Big.Mouth.S01.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV/Big.Mouth.S01E14.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息
【WARNING】2024-06-09 22:12:07,801 - media.py - Big.Mouth.S01E14.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息
【INFO】2024-06-09 22:12:07,800 - themoviedb - Big Outh 未匹配到TMDB媒体信息
【INFO】2024-06-09 22:12:07,785 - themoviedb - 正在识别 Big Outh 第1季 ...
【INFO】2024-06-09 22:12:07,661 - command.py - 处理事件：notice.message - []
``` 手动识别转移。，userid=None
/redo 535 [tmdbid]|[类型]
【INFO】2024-06-09 22:12:07,656 - chain - 发送消息：channel=None，title=Big.Mouth.S01E11.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息，无法入库！, text=回复：```
【WARNING】2024-06-09 22:12:07,569 - transfer.py - /media/影视源文件/日韩剧/Big.Mouth.S01.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV/Big.Mouth.S01E11.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息
【WARNING】2024-06-09 22:12:07,568 - media.py - Big.Mouth.S01E11.2022.Disney+.WEB-DL.1080p.H264.AAC-HDCTV.mkv 未识别到媒体信息
【INFO】2024-06-09 22:12:07,567 - themoviedb - Big Outh 未匹配到TMDB媒体信息
【INFO】2024-06-09 22:12:07,552 - themoviedb - 正在识别 Big Outh 第1季 ...
【INFO】2024-06-09 22:12:07,394 - command.py - 处理事件：notice.message - []
``` 手动识别转移。，userid=None
【INFO】2024-06-09 21:53:47,866 - chain - 发送消息：channel=None，title=The Sound of Your Heart S01E01 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息，无法入库！, text=回复：```
【WARNING】2024-06-09 21:53:47,781 - transfer.py - /media/影视源文件/日韩剧/The Sound of your Heart S01 1080p NF WEB-DL DDP2.0 x264-ARiN/The Sound of Your Heart S01E01 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息
【WARNING】2024-06-09 21:53:47,780 - media.py - The Sound of Your Heart S01E01 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息
【INFO】2024-06-09 21:53:47,778 - themoviedb - He Sound Of Our Heart 未匹配到TMDB媒体信息
【INFO】2024-06-09 21:53:47,770 - themoviedb - 正在识别 He Sound Of Our Heart 第1季 ...
【INFO】2024-06-09 21:53:47,646 - command.py - 处理事件：notice.message - []
``` 手动识别转移。，userid=None
/redo 243 [tmdbid]|[类型]
【INFO】2024-06-09 21:53:47,641 - chain - 发送消息：channel=None，title=The Sound of Your Heart S01E09 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息，无法入库！, text=回复：```
【WARNING】2024-06-09 21:53:47,564 - transfer.py - /media/影视源文件/日韩剧/The Sound of your Heart S01 1080p NF WEB-DL DDP2.0 x264-ARiN/The Sound of Your Heart S01E09 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息
【WARNING】2024-06-09 21:53:47,563 - media.py - The Sound of Your Heart S01E09 1080p NF WEB-DL DDP2.0 x264-ARiN.mkv 未识别到媒体信息
【INFO】2024-06-09 21:53:47,562 - themoviedb - He Sound Of Our Heart 未匹配到TMDB媒体信息
【INFO】2024-06-09 21:53:47,554 - themoviedb - 正在识别 He Sound Of Our Heart 第1季 ...
【INFO】2024-06-09 21:53:47,413 - command.py - 处理事件：notice.message - []
``` 手动识别转移。，userid=None
```

**Comment by jxxghp** [comment]
@lovemustardy 不会有这么低级的错误的，检查下你的自定义识别词，是不是写错了内容。

**Comment by lovemustardy** [comment]
> @lovemustardy 不会有这么低级的错误的，检查下你的自定义识别词，是不是写错了内容。

额果然低级错误。使用了共享识别词，此前发现词表中有无用字符，因不知是否有特殊含义未进行修改。官方共享识别词中出现错误导致刮削异常。https://movie-pilot.org/etherpad/p/MoviePilot_Anime_Words中最下面混入了一段无用字符，现已删除官方词表中的相关内容。
异常内容如下：
G
M
T
Y
检测语言上索布语世界语中文（文学）中文简体中文繁体丹麦语乌克兰语乌兹别克语乌兹别克语 (西里尔文)乌尔都语乌德穆尔特语亚美尼亚语伊博语伊洛卡诺低地文德语俄语保加利亚语信德语修纳语僧伽罗语克丘亚语克林贡语（拉丁语）克罗地亚语克里奥冰岛语加利西亚语加泰罗尼亚语匈牙利语南非祖鲁语博杰普尔语卡纳达语卢森堡语印地语印尼巽他语印尼爪哇语印尼语古吉拉特语吉尔吉斯语哈萨克语哈萨克语（拉丁语）因纽特语因纽特语（拉丁语）因纽纳克通土库曼语土耳其语基尼亚卢旺达语塔加洛语塔吉克语塞佩迪塞尔维亚语塞尔维亚语 (西里尔文)塞尔维亚语（拉丁语）塞索托语夏威夷语多格里大友奎太郎大溪地語奥罗莫语奥迪亚（奥里亚）威尔士语孔卡尼语孟加拉语宿务语尤卡坦玛雅人尼昂加语尼泊尔语巴什基尔语巴斯克语布尔语(南非荷兰语)希伯来语希腊语帕皮亚门托语库尔德语（库尔曼吉语）库尔德语（索拉尼语）廣州話（繁体）弗里西语德语意大利语意第绪语拉丁语拉脱维亚语挪威语捷克语提格里尼亚语斐濟語斯洛伐克语斯洛文尼亚语斯瓦希里语旁遮普语日语普什图语暮東加語林加拉语格鲁吉亚语梅特隆（马尼普里）梵文楚瓦什语母羊毛利语法罗语法语法语（加拿大）波兰语波斯尼亚语波斯语泰卢固语泰米尔语泰语海地克里奥尔语润迪爱尔兰语爱沙尼亚语特松加班巴拉语瑞典语甘达白俄罗斯语科萨科西嘉语立陶宛语简体中文 英国米佐索马里语约鲁巴语维吾尔语缅甸语罗马尼亚语老挝语艾马拉语芬兰语苏格兰盖尔语苗语英语茨瓦纳荷兰语菲律宾语萨摩亚语葡萄牙语（巴西）葡萄牙语（葡萄牙）蒙古语蒙古语（繁体）藏语表情符号西班牙语豪萨语越南语达里迈蒂利语迪维希阿塞拜疆语阿姆哈拉语阿尔巴尼亚语阿拉伯语阿萨姆语雅库特鞑靼语韩语马其顿语马尔加什语马拉地语马拉雅拉姆语马来语马耳他语马里山马里语高棉语齐切瓦语
英语-------- [ 所有 ] --------上索布语世界语中文（文学）中文简体中文繁体丹麦语乌克兰语乌兹别克语乌兹别克语 (西里尔文)乌尔都语乌德穆尔特语亚美尼亚语伊博语伊洛卡诺低地文德语俄语保加利亚语信德语修纳语僧伽罗语克丘亚语克林贡语（拉丁语）克罗地亚语克里奥冰岛语加利西亚语加泰罗尼亚语匈牙利语南非祖鲁语博杰普尔语卡纳达语卢森堡语印地语印尼巽他语印尼爪哇语印尼语古吉拉特语吉尔吉斯语哈萨克语哈萨克语（拉丁语）因纽特语因纽特语（拉丁语）因纽纳克通土库曼语土耳其语基尼亚卢旺达语塔加洛语塔吉克语塞佩迪塞尔维亚语塞尔维亚语 (西里尔文)塞尔维亚语（拉丁语）塞索托语夏威夷语多格里大友奎太郎大溪地語奥罗莫语奥迪亚（奥里亚）威尔士语孔卡尼语孟加拉语宿务语尤卡坦玛雅人尼昂加语尼泊尔语巴什基尔语巴斯克语布尔语(南非荷兰语)希伯来语希腊语帕皮亚门托语库尔德语（库尔曼吉语）库尔德语（索拉尼语）廣州話（繁体）弗里西语德语意大利语意第绪语拉丁语拉脱维亚语挪威语捷克语提格里尼亚语斐濟語斯洛伐克语斯洛文尼亚语斯瓦希里语旁遮普语日语普什图语暮東加語林加拉语格鲁吉亚语梅特隆（马尼普里）梵文楚瓦什语母羊毛利语法罗语法语法语（加拿大）波兰语波斯尼亚语波斯语泰卢固语泰米尔语泰语海地克里奥尔语润迪爱尔兰语爱沙尼亚语特松加班巴拉语瑞典语甘达白俄罗斯语科萨科西嘉语立陶宛语简体中文 英国米佐索马里语约鲁巴语维吾尔语缅甸语罗马尼亚语老挝语艾马拉语芬兰语苏格兰盖尔语苗语英语茨瓦纳荷兰语菲律宾语萨摩亚语葡萄牙语（巴西）葡萄牙语（葡萄牙）蒙古语蒙古语（繁体）藏语表情符号西班牙语豪萨语越南语达里迈蒂利语迪维希阿塞拜疆语阿姆哈拉语阿尔巴尼亚语阿拉伯语阿萨姆语雅库特鞑靼语韩语马其顿语马尔加什语马拉地语马拉雅拉姆语马来语马耳他语马里山马里语高棉语齐切瓦语 
文本转语音功能仅限200个字符
选项 : 历史 : 反馈 : Donate关闭
G
M
T
Y
检测语言上索布语世界语中文（文学）中文简体中文繁体丹麦语乌克兰语乌兹别克语乌兹别克语 (西里尔文)乌尔都语乌德穆尔特语亚美尼亚语伊博语伊洛卡诺低地文德语俄语保加利亚语信德语修纳语僧伽罗语克丘亚语克林贡语（拉丁语）克罗地亚语克里奥冰岛语加利西亚语加泰罗尼亚语匈牙利语南非祖鲁语博杰普尔语卡纳达语卢森堡语印地语印尼巽他语印尼爪哇语印尼语古吉拉特语吉尔吉斯语哈萨克语哈萨克语（拉丁语）因纽特语因纽特语（拉丁语）因纽纳克通土库曼语土耳其语基尼亚卢旺达语塔加洛语塔吉克语塞佩迪塞尔维亚语塞尔维亚语 (西里尔文)塞尔维亚语（拉丁语）塞索托语夏威夷语多格里大友奎太郎大溪地語奥罗莫语奥迪亚（奥里亚）威尔士语孔卡尼语孟加拉语宿务语尤卡坦玛雅人尼昂加语尼泊尔语巴什基尔语巴斯克语布尔语(南非荷兰语)希伯来语希腊语帕皮亚门托语库尔德语（库尔曼吉语）库尔德语（索拉尼语）廣州話（繁体）弗里西语德语意大利语意第绪语拉丁语拉脱维亚语挪威语捷克语提格里尼亚语斐濟語斯洛伐克语斯洛文尼亚语斯瓦希里语旁遮普语日语普什图语暮東加語林加拉语格鲁吉亚语梅特隆（马尼普里）梵文楚瓦什语母羊毛利语法罗语法语法语（加拿大）波兰语波斯尼亚语波斯语泰卢固语泰米尔语泰语海地克里奥尔语润迪爱尔兰语爱沙尼亚语特松加班巴拉语瑞典语甘达白俄罗斯语科萨科西嘉语立陶宛语简体中文 英国米佐索马里语约鲁巴语维吾尔语缅甸语罗马尼亚语老挝语艾马拉语芬兰语苏格兰盖尔语苗语英语茨瓦纳荷兰语菲律宾语萨摩亚语葡萄牙语（巴西）葡萄牙语（葡萄牙）蒙古语蒙古语（繁体）藏语表情符号西班牙语豪萨语越南语达里迈蒂利语迪维希阿塞拜疆语阿姆哈拉语阿尔巴尼亚语阿拉伯语阿萨姆语雅库特鞑靼语韩语马其顿语马尔加什语马拉地语马拉雅拉姆语马来语马耳他语马里山马里语高棉语齐切瓦语
英语-------- [ 所有 ] --------上索布语世界语中文（文学）中文简体中文繁体丹麦语乌克兰语乌兹别克语乌兹别克语 (西里尔文)乌尔都语乌德穆尔特语亚美尼亚语伊博语伊洛卡诺低地文德语俄语保加利亚语信德语修纳语僧伽罗语克丘亚语克林贡语（拉丁语）克罗地亚语克里奥冰岛语加利西亚语加泰罗尼亚语匈牙利语南非祖鲁语博杰普尔语卡纳达语卢森堡语印地语印尼巽他语印尼爪哇语印尼语古吉拉特语吉尔吉斯语哈萨克语哈萨克语（拉丁语）因纽特语因纽特语（拉丁语）因纽纳克通土库曼语土耳其语基尼亚卢旺达语塔加洛语塔吉克语塞佩迪塞尔维亚语塞尔维亚语 (西里尔文)塞尔维亚语（拉丁语）塞索托语夏威夷语多格里大友奎太郎大溪地語奥罗莫语奥迪亚（奥里亚）威尔士语孔卡尼语孟加拉语宿务语尤卡坦玛雅人尼昂加语尼泊尔语巴什基尔语巴斯克语布尔语(南非荷兰语)希伯来语希腊语帕皮亚门托语库尔德语（库尔曼吉语）库尔德语（索拉尼语）廣州話（繁体）弗里西语德语意大利语意第绪语拉丁语拉脱维亚语挪威语捷克语提格里尼亚语斐濟語斯洛伐克语斯洛文尼亚语斯瓦希里语旁遮普语日语普什图语暮東加語林加拉语格鲁吉亚语梅特隆（马尼普里）梵文楚瓦什语母羊毛利语法罗语法语法语（加拿大）波兰语波斯尼亚语波斯语泰卢固语泰米尔语泰语海地克里奥尔语润迪爱尔兰语爱沙尼亚语特松加班巴拉语瑞典语甘达白俄罗斯语科萨科西嘉语立陶宛语简体中文 英国米佐索马里语约鲁巴语维吾尔语缅甸语罗马尼亚语老挝语艾马拉语芬兰语苏格兰盖尔语苗语英语茨瓦纳荷兰语菲律宾语萨摩亚语葡萄牙语（巴西）葡萄牙语（葡萄牙）蒙古语蒙古语（繁体）藏语表情符号西班牙语豪萨语越南语达里迈蒂利语迪维希阿塞拜疆语阿姆哈拉语阿尔巴尼亚语阿拉伯语阿萨姆语雅库特鞑靼语韩语马其顿语马尔加什语马拉地语马拉雅拉姆语马来语马耳他语马里山马里语高棉语齐切瓦语 
文本转语音功能仅限200个字符
选项 : 历史 : 反馈 : Donate关闭
