### ISSUE TITLE
[错误报告]: 在搜索详情对着季点击订阅按钮，无法编辑订阅详情

### ISSUE THREAD

**Issue by x1186176868** [jxxghp/MoviePilot#2305]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在搜索详情对着季点击订阅按钮，无法编辑订阅详情，会指向一个空白订阅。但是取消订阅的按钮却可以取消订阅
![c25f6f8764185cf95722e0e619d2293](https://github.com/jxxghp/MoviePilot/assets/30969849/a1b17d76-052f-46e0-a3cd-785ced0d2e99)

**Comment by jxxghp** [comment]
已修
