### ISSUE TITLE
[Feature Request]: 想要动漫一级目录，二级目录确实不方便观影

### ISSUE THREAD

**Issue by nathandingx** [jxxghp/MoviePilot#2306]
### 当前程序版本

v1.9.3

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望能设置动漫一级目录，并且能同时收纳整理动漫电影和剧集

**Comment by Putarku** [comment]
现在本来就可以任意设置动漫和动漫电影的保存位置和媒体库位置，没必要专门分出来一个一级目录。

**Comment by lijiai** [comment]
确实不习惯也不太方便
