### ISSUE TITLE
[错误报告]: 硬连接失败，SSH里面手动硬连接成功

### ISSUE THREAD

**Issue by Zayia** [jxxghp/MoviePilot#2314]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新程序后，发现所有硬连接均失败，提示日志如下，但是手动在SSH里面硬连接却成功
ln "/hdd/downloads/movie/Robot Dreams (2023).mkv" "/hdd/media/movie/动画电影/机器人之梦 (2023)/机器人之梦 (2023).mkv"

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-06-10 21:47:42,085 - transfer.py - /downloads/movie/Robot Dreams (2023).mkv 转移完成，共 1 个文件，失败 1 个，跳过 0 个
【INFO】2024-06-10 21:47:41,707 - command.py - 处理事件：notice.message - [<function WorkWechatMsg.send at 0x7d73e048e5c0>]
【INFO】2024-06-10 21:47:41,706 - chain - 发送消息：channel=None，title=机器人之梦 (2023)  入库失败！, text=原因：错误码：-1，userid=None
【WARNING】2024-06-10 21:47:41,699 - transfer.py - Robot Dreams (2023).mkv 入库失败：错误码：-1
【ERROR】2024-06-10 21:47:41,698 - filetransfer - 文件 /downloads/movie/Robot Dreams (2023).mkv 转移失败，错误码：-1
【ERROR】2024-06-10 21:47:41,698 - filetransfer - 文件 /downloads/movie/Robot Dreams (2023).mkv link失败，错误码：-1
【ERROR】2024-06-10 21:47:41,697 - filetransfer - [Errno 18] Invalid cross-device link: '/downloads/movie/Robot Dreams (2023).mkv' -> '/media/movie/动画电影/机器人之梦 (2023)/机器人之梦 (2023).mkv.mp'
【INFO】2024-06-10 21:47:41,696 - filetransfer - 正在转移文件：/downloads/movie/Robot Dreams (2023).mkv 到 /media/movie/动画电影/机器人之梦 (2023)/机器人之梦 (2023).mkv
【INFO】2024-06-10 21:47:41,694 - filetransfer - 获取转移目标路径：/media/movie/动画电影
【INFO】2024-06-10 21:47:41,692 - transfer.py - Robot Dreams (2023).mkv 识别为：电影 机器人之梦 (2023)
【INFO】2024-06-10 21:47:41,689 - media.py - Robot Dreams (2023).mkv 识别到媒体信息：电影 机器人之梦 (2023)
【INFO】2024-06-10 21:47:41,688 - themoviedb - Robot Dreams TMDB识别结果：电影 机器人之梦 (2023) 838240
【INFO】2024-06-10 21:47:41,681 - themoviedb - Robot Dreams 使用TMDB识别缓存：机器人之梦
【INFO】2024-06-10 21:47:41,676 - transfer.py - 手动转移：/downloads/movie/Robot Dreams (2023).mkv ...
```

**Comment by InfinityPacer** [comment]
@Zayia 请使用自动诊断插件验证

**Comment by Zayia** [comment]
> @Zayia 请使用自动诊断插件验证

验证什么？




- /downloads/movie -> /media/movie，异常信息：Invalid cross-device link
目录硬链接测试：异常
- 硬链接，异常信息：历史记录文件个数：10，硬链接：0 个，非硬链接：10 个
【INFO】2024-06-10 21:22:03,745 - autodiagnosis - 历史记录硬链接检查：异常
【ERROR】2024-06-10 21:22:03,744 - autodiagnosis - /downloads/movie -> /media/movie: 硬链接测试失败 - Invalid cross-device link

**Comment by Zayia** [comment]
> @Zayia 请按自动诊断插件提示，参阅 #735

感谢，在MP里面把下载目录和媒体目录的上级目录映射到MP里面就可以了

不过为什么之前是可以硬连接的，今天才不行的

**Comment by InfinityPacer** [comment]
@Zayia 诊断结果说明历史的硬链接是失败的
