### ISSUE TITLE
重启显示API错误

### ISSUE THREAD

**Issue by cosmotown** [jxxghp/MoviePilot#2315]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新到1.9以后就不能在软件内重启了，只能直接重启容器，软件内重启就显示如图的错误，请大佬们看看这是什么问题？
![Screenshot_20240610_220927_com android chrome_edit_137825567846589](https://github.com/jxxghp/MoviePilot/assets/48054349/584a7e6f-bf76-4167-874a-bab87028b1e0)

**Comment by jxxghp** [comment]
检查是否有映射 /var/run/docker.sock

**Comment by cosmotown** [comment]
> 检查是否有映射 /var/run/docker.sock

![Screenshot_20240616_201500_com android chrome_edit_223885447724697](https://github.com/jxxghp/MoviePilot/assets/48054349/6f94bca9-988b-4ffe-a75d-11edf502a2b9)
有这样映射，1.8几的时候没这问题，1.9开始就这样了。也不清楚哪里不对

**Comment by jinghua625** [comment]
docker版本，已经映射docker.sock，每次重启后API都会失效，进入插件里的配置中心再启用一次就恢复正常了

**Comment by JavaZeroo** [comment]
truenas里面用的是k3s 没有docker.sock怎么办呀
