### ISSUE TITLE
希望能够自定义 订阅搜索补全 该模块的时间

### ISSUE THREAD

**Issue by jkelove** [jxxghp/MoviePilot#2320]
### 当前程序版本

1.9.4

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

如题

**Comment by cng10001** [comment]
就是简化了的，想要自定义时间？目前24小时补全一次没毛病吧

**Comment by jkelove** [comment]
> 就是简化了的，想要自定义时间？目前24小时补全一次没毛病吧

主要是发现并没有自动24小时进行搜索，例如玫瑰的故事 站点都更新发布4集了，还没有进行下载，手动点击该按钮才进行补全，能不能像NT一样，自定义6个小时也好

**Comment by cng10001** [comment]
那你查查日志，定位下到底哪里问题。
之前我也提过订阅不到的问题，作者修复过一轮匹配机制和tmdb缓存方面的问题，我目前正常了。
我觉得tmdb连通性影响挺大的。

至于你说的24小时没进行补全搜索，我认为是可能性不大。

**Comment by jkelove** [comment]
> 那你查查日志，定位下到底哪里问题。 之前我也提过订阅不到的问题，作者修复过一轮匹配机制和tmdb缓存方面的问题，我目前正常了。 我觉得tmdb连通性影响挺大的。
> 
> 至于你说的24小时没进行补全搜索，我认为是可能性不大。

我自己改好了，只是希望作者能帮忙修改下而已
![7e17779db1eb210e18d517cb9086d4a8](https://github.com/jxxghp/MoviePilot/assets/119661718/f3cef43f-36e3-4ef2-844a-30c902385da2)

**Comment by HalcyonDaysssss** [comment]
> > 那你查查日志，定位下到底哪里问题。 之前我也提过订阅不到的问题，作者修复过一轮匹配机制和tmdb缓存方面的问题，我目前正常了。 我觉得tmdb连通性影响挺大的。
> > 至于你说的24小时没进行补全搜索，我认为是可能性不大。
> 
> 我自己改好了，只是希望作者能帮忙修改下而已 ![7e17779db1eb210e18d517cb9086d4a8](https://private-user-images.githubusercontent.com/119661718/338811697-f3cef43f-36e3-4ef2-844a-30c902385da2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMDc4ODMsIm5iZiI6MTczNjMwNzU4MywicGF0aCI6Ii8xMTk2NjE3MTgvMzM4ODExNjk3LWYzY2VmNDNmLTM2ZTMtNGVmMi04NDRhLTMwYzkwMjM4NWRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwMzM5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2VkZDQ3OGUwNDk3ZmIyN2JlMTFhNzllOGY5ZmYxODg1NzE1MzVlMjNkZjlmODQ3YThiNjNjNmE3M2MwNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xgaAdM6SW5cg58aDx1tSqbRJAz73g8JQiaf-z8V4b18)

大佬，怎么改的？
