### ISSUE TITLE
文件监控目录功能缺陷，文件不完整即进行转移导致文件损坏无法播放

### ISSUE THREAD

**Issue by choujay665** [jxxghp/MoviePilot#2321]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.8.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

文件监控目录功能缺陷，文件不完整即进行转移导致文件损坏无法播放

**Comment by AisukaYuki** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/40f1e59d-6609-4701-ab8d-0ae388c72022)

**Comment by zoffyultraman** [comment]
建议使用下载器监控

**Comment by Putarku** [comment]
三个解决方法任选其一
1️⃣用下载器监控不用目录监控
2️⃣在文件整理屏蔽词中增加!qb，并同时在qb中开启这个功能
3️⃣在qb中开启“保存未完成的torrent到”这个功能，并设置到其他目录，这样qb会在下载完成后才会转移到下载路径，此时mp才会触发整理
