### ISSUE TITLE
[错误报告]: 硬链接、软链接、rclone复制也失败，只能复制

### ISSUE THREAD

**Issue by KGDJudy** [jxxghp/MoviePilot#2323]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

硬链接、软链接、rclone复制也失败，都提示错误码：-1。只能复制成功

### 发生问题时系统日志和配置文件

```bash
ARiC/Connection.S01E01.1080p.friDay.WEB-DL.AAC2.0.H.264-ARiC.mkv link失败，错误码：-1
【ERROR】2024-06-12 11:31:40,243 - filetransfer - [Errno 18] Invalid cross-device link: '/Media/download/电视剧/Connection.S01.1080p.friDay.WEB-DL.AAC2.0.H.264-ARiC/Connection.S01E01.1080p.friDay.WEB-DL.AAC2.0.H.264-ARiC.mkv' -> '/Media/link/电视剧/日韩剧/联结 (2024)/Season 1/联结 - S01E01 - 第 1 集.mkv.mp'
【INFO】2024-06-12 11:31:40,241 - filetransfer - 正在转移文件：/Media/download/电视剧/Connection.S01.1080p.friDay.WEB-DL.AAC2.0.H.264-ARiC/Connection.S01E01.1080p.friDay.WEB-DL.AAC2.0.H.264-ARiC.mkv 到 /Media/link/电视剧/日韩剧/联结 (2024)/Season 1/联结 - S01E01 - 第 1 集.mkv
【INFO】2024-06-12 11:31:40,238 - filetransfer - 获取转移目标路径：/Media/link/电视剧/日韩剧
```

**Comment by InfinityPacer** [comment]
@KGDJudy 请使用自动诊断插件进行验证，如有异常，请按自动诊断配置页提示，参阅 #735 后调整目录映射

**Comment by KGDJudy** [comment]
> @KGDJudy使用自动诊断插件进行验证，如有异常，请按自动诊断配置页提示，参阅#735后调整目录映射

还是不行，

**Comment by Sraw** [comment]
我也有这个问题，用的docker，在群晖上无法硬连接了。

**Comment by vvnocode** [comment]
我也是这个问题。软件版本 v1.9.4-1

INFO:    filetransfer - 正在转移文件：/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 到 /media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4
[Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp'
ERROR:   filetransfer - [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp'
ERROR:   filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 link失败，错误码：-1
ERROR:   filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 转移失败，错误码：-1
WARNING: transfer.py - 狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 入库失败：错误码：-1

**Comment by Putarku** [comment]
> 我也是这个问题。软件版本 v1.9.4-1
> 
> INFO: filetransfer - 正在转移文件：/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 到 /media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4 [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 link失败，错误码：-1 ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 转移失败，错误码：-1 WARNING: transfer.py - 狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 入库失败：错误码：-1

[你的路径配置错了](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=_194%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E5%90%8E%E7%A1%AC%E9%93%BE%E6%8E%A5%E8%BD%AC%E7%A7%BB%E5%87%BA%E7%8E%B0-1%E7%9A%84%E6%8A%A5%E9%94%99)

**Comment by vvnocode** [comment]
> > 我也是这个问题。软件版本 v1.9.4-1
> > INFO: filetransfer - 正在转移文件：/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 到 /media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4 [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 link失败，错误码：-1 ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 转移失败，错误码：-1 WARNING: transfer.py - 狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 入库失败：错误码：-1
> 
> [你的路径配置错了](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=_194%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E5%90%8E%E7%A1%AC%E9%93%BE%E6%8E%A5%E8%BD%AC%E7%A7%BB%E5%87%BA%E7%8E%B0-1%E7%9A%84%E6%8A%A5%E9%94%99)

看了下，貌似下载和转移目的地要一个共享文件。但是为啥之前的版本可以硬连接呢？

**Comment by Putarku** [comment]
> > > 我也是这个问题。软件版本 v1.9.4-1
> > > INFO: filetransfer - 正在转移文件：/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 到 /media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4 [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 link失败，错误码：-1 ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 转移失败，错误码：-1 WARNING: transfer.py - 狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 入库失败：错误码：-1
> > 
> > 
> > [你的路径配置错了](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=_194%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E5%90%8E%E7%A1%AC%E9%93%BE%E6%8E%A5%E8%BD%AC%E7%A7%BB%E5%87%BA%E7%8E%B0-1%E7%9A%84%E6%8A%A5%E9%94%99)
> 
> 看了下，貌似下载和转移目的地要一个共享文件。但是为啥之前的版本可以硬连接呢？

因为以前路径配置错误就无法硬链接，会自动改为复制，只是错误显示成硬链接。你之前的硬链接实质都是复制

**Comment by vvnocode** [comment]
> > > > 我也是这个问题。软件版本 v1.9.4-1
> > > > INFO: filetransfer - 正在转移文件：/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 到 /media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4 [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - [Errno 18] Invalid cross-device link: '/moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4' -> '/media/电视剧/国产剧/狐妖小红娘月红篇 (2024)/Season 1/狐妖小红娘月红篇 - S01E34 - 第 34 集.mp4.mp' ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 link失败，错误码：-1 ERROR: filetransfer - 文件 /moviepilot_downloads/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01.2024.1080p.WEB-DL.H264.AAC-ADWeb/狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 转移失败，错误码：-1 WARNING: transfer.py - 狐妖小红娘月红篇.Fox.Spirit.Matchmaker.Yue.Hong.S01E34.2024.1080p.WEB-DL.H264.AAC-ADWeb.mp4 入库失败：错误码：-1
> > > 
> > > 
> > > [你的路径配置错了](https://putarku.github.io/MoviePilot-Help/#/docs/%E8%BF%91%E6%9C%9F%E6%96%B0%E9%97%AE%E9%A2%98?id=_194%E7%89%88%E6%9C%AC%E6%9B%B4%E6%96%B0%E5%90%8E%E7%A1%AC%E9%93%BE%E6%8E%A5%E8%BD%AC%E7%A7%BB%E5%87%BA%E7%8E%B0-1%E7%9A%84%E6%8A%A5%E9%94%99)
> > 
> > 
> > 看了下，貌似下载和转移目的地要一个共享文件。但是为啥之前的版本可以硬连接呢？
> 
> 因为以前路径配置错误就无法硬链接，会自动改为复制，只是错误显示成硬链接。你之前的硬链接实质都是复制

原来如此，谢谢。

**Comment by Sraw** [comment]
看了一下确实如此，以前虽然选了硬连接但其实都是复制的。

**Comment by KGDJudy** [comment]
解决了，确实是映射问题，
硬链接的目录要在download目录下
如下图
![Uploading WX20240612-164656@2x.png…]()
