### ISSUE TITLE
可能是错了一个比较关键的字

### ISSUE THREAD

**Issue by hn315** [jxxghp/MoviePilot#2324]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.3

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

MP项目越来越好用，感谢作者的付出。今天再翻作者github主页，访问官方Wiki：https://wiki.movie-pilot.org/，介绍更官方全面细致，点个赞。但官方Wiki首页的这一行“请务在任何国内平台发布或引用此wiki任何相关内容，请尽量避免在国内公共场合提及MoviePilot全称，如确实有需要请使用简称：MP。”中的“务”字好像不太妥，有务必的意思，可能应该是“勿”吧，不要的意思。供参考。

**Comment by cng10001** [comment]
访问官方Wiki：https://wiki.movie-pilot.org/ 能否再注释下：（wiki目前仍在建设中）

哈哈哈
