### ISSUE TITLE
[错误报告]: 大概是识别到特殊字符的tmdb模块报错

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#2325]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

The Human Condition Iii A Soldier'S Prayer今天碰到两次名称里带  'S 的出现识别报错的问题

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-06-12 20:41:46,144 - command.py - 处理事件：system.error - []

TypeError: 'NoneType' object is not iterable
    for cast in _credits.get("cast"):
  File "/app/app/core/context.py", line 350, in __directors_actors
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
    self.directors, self.actors = __directors_actors(info)
  File "/app/app/core/context.py", line 433, in set_tmdb_info
    self.set_tmdb_info(self.tmdb_info)
  File "/app/app/core/context.py", line 246, in __post_init__
  File "<string>", line 56, in __init__
                ^^^^^^^^^^^^^^^^^^^^^^^^^
    mediainfo = MediaInfo(tmdb_info=info)
  File "/app/app/modules/themoviedb/__init__.py", line 177, in recognize_media
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 107, in run_module
Traceback (most recent call last):
【ERROR】2024-06-12 20:41:46,140 - chain - 运行模块 TheMovieDbModule.recognize_media 出错：'NoneType' object is not iterable
【INFO】2024-06-12 20:41:46,130 - themoviedb - 正在识别 The Human Condition Iii A Soldier'S Prayer ...
【INFO】2024-06-12 20:41:46,119 - subscribe.py - 猫站 - The Human Condition III-A Soldier's Prayer 1961 CC BluRay 1080p x265 10bit FLAC MNHD-FRDS
```

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/be11132a-ad12-43bf-8207-efefbcfe9a0e)
你这是什么模式 
我添加了这部订阅 新增订阅搜索倒是没有问题

**Comment by dlovew** [comment]
> ![image](https://private-user-images.githubusercontent.com/115156545/339028505-be11132a-ad12-43bf-8207-efefbcfe9a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzg0MzgsIm5iZiI6MTcxODIzODEzOCwicGF0aCI6Ii8xMTUxNTY1NDUvMzM5MDI4NTA1LWJlMTExMzJhLWFkMTItNDNiZi04MjA3LWVmZWZiY2ZlOWEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODQ5ZTNhMjhjOTRhMzljYWY3MjNjMmQ3NDAxYzY2YzVhOTk3ODJhNzFiMWJiMzQ0OWU2Y2JlOGU2MTMxNzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cxo4BHpsmihhA22DZWIH3hIzfFY5gQL4GB8o_DhC6q8) 你这是什么模式 我添加了这部订阅 新增订阅搜索倒是没有问题

看日志是一批没识别的文件在重新识别
【INFO】2024-06-12 14:57:06,511 - subscribe.py - 观众 - Where Is the Friend's Home 1987 V2 1080p Criterion Collection BluRay AVC LPCM 1.0-DIY@Audies[何处是我朋友的家 / 踏破铁鞋无觅处(港) / Where Is the Friend's Home? / Khane-ye doust kodjast?  【BDJ菜单新增按钮】【CC原盘DIY/双语简繁字幕】*The Koker Trilogy-001* AudiesCC#990 ] 订阅缓存为未识别状态，尝试重新识别...
【INFO】2024-06-12 14:57:06,522 - themoviedb - 正在识别 Where Is The Friend'S Home ...
【ERROR】2024-06-12 14:57:06,550 - chain - 运行模块 TheMovieDbModule.recognize_media 出错：'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 107, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/themoviedb/__init__.py", line 177, in recognize_media
    mediainfo = MediaInfo(tmdb_info=info)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 56, in __init__
  File "/app/app/core/context.py", line 246, in __post_init__
    self.set_tmdb_info(self.tmdb_info)
  File "/app/app/core/context.py", line 433, in set_tmdb_info
    self.directors, self.actors = __directors_actors(info)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/core/context.py", line 350, in __directors_actors
    for cast in _credits.get("cast"):
TypeError: 'NoneType' object is not iterable

【INFO】2024-06-12 14:57:06,554 - command.py - 处理事件：system.error - []
【WARNING】2024-06-12 14:57:06,555 - subscribe.py - 观众 - Where Is the Friend's Home 1987 V2 1080p Criterion Collection BluRay AVC LPCM 1.0-DIY@Audies[何处是我朋友的家 / 踏破铁鞋无觅处(港) / Where Is the Friend's Home? / Khane-ye doust kodjast?  【BDJ菜单新增按钮】【CC原盘DIY/双语简繁字幕】*The Koker Trilogy-001* AudiesCC#990 ] 重新识别失败，尝试通过标题匹配...

**Comment by dlovew** [comment]
看着是在匹配订阅之前，每次都要重新识别一次那些没被识别的种子，然后在重新识别的过程中报错，正常情况下就是单纯的识别不了，但是种子里带'S好像就报错了

**Comment by dlovew** [comment]
另外我的订阅模式是rss

**Comment by cng10001** [comment]
你tmdb有问题吧

**Comment by dlovew** [comment]
> 你tmdb有问题吧

这有什么问题，不能识别都是一些奇怪命名比如
Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe S01 2016 2160p WEB-DL H.264 AAC 2.0-FROGWeb

**Comment by dlovew** [comment]
> 你tmdb有问题吧

绝大多数都是可以正常识别，有一小部分命名问题的不能识别，这些不能识别的好像会周期性重新识别，其中个别名字里面带有'S的才会报错

**Comment by cng10001** [comment]
> > 你tmdb有问题吧
> 
> 这有什么问题，不能识别都是一些奇怪命名比如 Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe S01 2016 2160p WEB-DL H.264 AAC 2.0-FROGWeb

这个肯定就是**Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe**这个标题本身有问题啊。要匹配tmdb的话应该是**gg bond s11**

**Comment by dlovew** [comment]
> > > 你tmdb有问题吧
> > 
> > 
> > 这有什么问题，不能识别都是一些奇怪命名比如 Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe S01 2016 2160p WEB-DL H.264 AAC 2.0-FROGWeb
> 
> 这个肯定就是**Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe**这个标题本身有问题啊。要匹配tmdb的话应该是**gg bond s11**

大兄弟你连我反馈的什么问题都没搞清楚，就别搁着讨论了。虽然这个问题几乎没什么影响。

**Comment by dlovew** [comment]
> > > 你tmdb有问题吧
> > 
> > 
> > 这有什么问题，不能识别都是一些奇怪命名比如 Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe S01 2016 2160p WEB-DL H.264 AAC 2.0-FROGWeb
> 
> 这个肯定就是**Zhu Zhu Xia Zhi Guang Ming Shou Wei Zhe**这个标题本身有问题啊。要匹配tmdb的话应该是**gg bond s11**

我反馈的不是识别不了，是个别标题可能因为命名问题识别不了，这是命名的问题，但是mp会周期性的重新识别这些未识别的标题，而在重新识别的过程中，又有些极个别的标题带有  'S  导致识别模块报错。所以我说这个问题几乎没有影响，最大的影响就是会在系统通知里提醒你，运行过程中出过错误。

**Comment by Putarku** [comment]
你给的两个带"'s"例子我这边测试没问题不会报错

**Comment by dlovew** [comment]
> 你给的两个带"'s"例子我这边测试没问题不会报错

我在反馈之前也测试了，直接复制名称做名称测试并不会报错，只有在程序自己周期性重新识别的时候会报错

**Comment by dlovew** [comment]
> 你给的两个带"'s"例子我这边测试没问题不会报错

其实我就碰到这两个文件名会这样，因为订阅匹配周期是十分钟，所以大概会十分钟报错一次，无关紧要的小问题。我这就关了issue，不然显得我吹毛求疵- -

**Comment by cddjr** [comment]
这个问题貌似前两天突然冒出来的。
 chain - 运行模块 TheMovieDbModule.recognize_media 出错：'NoneType' object is not iterable

手动识别也能触发这个bug。

比如手动识别`In The Realm Of The Senses`，日志就会显示这个报错了。
