### ISSUE TITLE
[错误报告]: 订阅重复下载正在下载的剧集

### ISSUE THREAD

**Issue by lzcer** [jxxghp/MoviePilot#2327]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅的剧集15:35开始下载1-3集，16:13又开始下载其他站点的1-3集

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-06-13 16:13:39,779 - chain - 发送消息：channel=None，title=黑袍纠察队 (2019) S04 E01-E03 开始下载, text=用户：xxx
【INFO】2024-06-13 16:13:34,385 - download.py - 开始下载 [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb ...
【INFO】2024-06-13 16:13:34,383 - download.py - 开始电视剧完整集匹配：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 16:13:34,382 - download.py - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb 解析文件集数发现不是完整合集，先放弃这个种子
【INFO】2024-06-13 16:13:34,381 - download.py - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb 解析种子文件集数为 [1, 2, 3]
【INFO】2024-06-13 16:13:30,605 - download.py - 开始下载种子 [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb ...
【INFO】2024-06-13 16:13:30,605 - download.py - 缺失整季：{76479: [4]}
【INFO】2024-06-13 16:13:30,604 - download.py - 开始匹配电视剧整季：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 16:13:30,603 - subscribe.py - 黑袍纠察队 (2019) 匹配完成，共匹配到1个资源
【INFO】2024-06-13 16:13:30,595 - subscribe.py - 黑袍纠察队 (2019) 匹配成功：[Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb
【INFO】2024-06-13 16:13:30,588 - subscribe.py - 黑袍纠察队 (2019) 通过媒体信ID匹配到资源：麒麟 - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb
【INFO】2024-06-13 16:13:30,585 - subscribe.py - 订阅 黑袍纠察队 (2019) S04 缺失集：[]
【INFO】2024-06-13 16:13:30,583 - filetransfer - 黑袍纠察队 (2019) 文件系统已存在：{1: [1], 2: [1]}
【INFO】2024-06-13 16:13:30,544 - emby - 黑袍纠察队 (2019) 在媒体库中不存在
【INFO】2024-06-13 16:13:30,539 - themoviedb - 黑袍纠察队 TMDB识别结果：电视剧 黑袍纠察队 (2019) 76479
【INFO】2024-06-13 16:13:30,533 - subscribe.py - 开始匹配订阅，标题：黑袍纠察队 ...
【INFO】2024-06-13 15:35:46,376 - subscribe.py - 黑袍纠察队 (2019) 季 4 更新缺失集数为5 ...
【INFO】2024-06-13 15:35:46,348 - download.py - 成功下载种子数：1，剩余未下载的剧集：{76479: {4: NotExistMediaInfo(season=4, episodes=[4, 5, 6, 7, 8], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 15:35:46,344 - download.py - 开始电视剧多集拆包匹配：{76479: {4: NotExistMediaInfo(season=4, episodes=[4, 5, 6, 7, 8], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 15:35:46,341 - download.py - 季 4 剩余需要集：[4, 5, 6, 7, 8]
【INFO】2024-06-13 15:35:46,339 - download.py - The Boys S04 1080p AMZN WEB-DL DDP 5.1 H.264-CHDWEB 添加下载成功
【INFO】2024-06-13 15:35:46,337 - command.py - 处理事件：download.added - [<function DownloadSiteTag.DownloadAdded at 0x7ff590ae53a0>]
【INFO】2024-06-13 15:35:44,067 - command.py - 处理事件：notice.message - []
描述：美剧：黑袍纠察队 第四季 第01-03集 | 类型:剧情/动作/科幻/犯罪 | 主演:卡尔厄本/杰克奎德 | 内封官方中字，userid=None
做种数：11
发布时间：2024-06-13 15:27:46
种子：The Boys S04 1080p AMZN WEB-DL DDP 5.1 H.264-CHDWEB
大小：10.95G
质量： WEB-DL 1080p
站点：UBits
【INFO】2024-06-13 15:35:44,065 - chain - 发送消息：channel=None，title=黑袍纠察队 (2019) S04 E01-E03 开始下载, text=用户：xxx
【INFO】2024-06-13 15:35:39,797 - download.py - 开始下载 The Boys S04 1080p AMZN WEB-DL DDP 5.1 H.264-CHDWEB ...
【INFO】2024-06-13 15:35:39,796 - download.py - 开始电视剧完整集匹配：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 15:35:39,795 - download.py - 缺失整季：{76479: [4]}
【INFO】2024-06-13 15:35:39,795 - download.py - 开始匹配电视剧整季：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 15:35:39,794 - search.py - 搜索完成，共 2 个资源
【INFO】2024-06-13 15:35:39,791 - search.py - 优先级规则/剧集过滤完成，剩余 2 个资源
【INFO】2024-06-13 15:35:39,536 - search.py - 开始优先级规则/剧集过滤，当前规则： SPECSUB & 1080P & BLURAY & H265 & H264 > SPECSUB & 1080P > CNSUB & 1080P & BLURAY & H265 & H264 > CNSUB & 1080P > SPECSUB & 4K & BLURAY > SPECSUB & 4K > CNSUB & 4K & BLURAY > CNSUB & 4K > SPECSUB & 720P & BLURAY & H265 & H264 > SPECSUB & 720P > CNSUB & 720P & BLURAY & H264 & H265 > CNSUB & 720P > 1080P & BLURAY & H265 & H264 > 1080P > 4K & BLURAY & H264 & H265 > 4K > BLURAY & H265 & H264 & 720P > 720P  ...
```

**Comment by lzcer** [comment]
补充，16:33又发起一次下载

【INFO】2024-06-13 16:33:26,077 - chain - 发送消息：channel=None，title=黑袍纠察队 (2019) S04 E01-E03 开始下载, text=用户：lzcer
【INFO】2024-06-13 16:33:19,163 - download.py - 开始下载 [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb ...
【INFO】2024-06-13 16:33:19,162 - download.py - 开始电视剧完整集匹配：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 16:33:19,160 - download.py - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb 解析文件集数发现不是完整合集，先放弃这个种子
【INFO】2024-06-13 16:33:19,158 - download.py - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb 解析种子文件集数为 [1, 2, 3]
【INFO】2024-06-13 16:33:17,222 - download.py - 开始下载种子 [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb ...
【INFO】2024-06-13 16:33:17,221 - download.py - 缺失整季：{76479: [4]}
【INFO】2024-06-13 16:33:17,220 - download.py - 开始匹配电视剧整季：{76479: {4: NotExistMediaInfo(season=4, episodes=[], total_episode=8, start_episode=1)}}
【INFO】2024-06-13 16:33:17,219 - subscribe.py - 黑袍纠察队 (2019) 匹配完成，共匹配到1个资源
【INFO】2024-06-13 16:33:17,213 - subscribe.py - 黑袍纠察队 (2019) 匹配成功：[Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb
【INFO】2024-06-13 16:33:17,205 - subscribe.py - 黑袍纠察队 (2019) 通过媒体信ID匹配到资源：麒麟 - [Audiences] The Boys S04 2024 2160p AMZN WEB-DL H265 HDR DDP5.1-ADWeb
【INFO】2024-06-13 16:33:17,204 - subscribe.py - The Boys S04E01 Department of Dirty Tricks 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv 对应剧集 [1] 已下载过
【INFO】2024-06-13 16:33:17,197 - subscribe.py - 黑袍纠察队 (2019) 通过媒体信ID匹配到资源：红豆饭 - The Boys S04E01 Department of Dirty Tricks 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv
【INFO】2024-06-13 16:33:17,196 - subscribe.py - The Boys S04E03 Well Keep the Red Flag Flying Here 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv 对应剧集 [3] 已下载过
【INFO】2024-06-13 16:33:17,189 - subscribe.py - 黑袍纠察队 (2019) 通过媒体信ID匹配到资源：红豆饭 - The Boys S04E03 Well Keep the Red Flag Flying Here 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv
【INFO】2024-06-13 16:33:17,188 - subscribe.py - The Boys S04E02 Life Among the Septics 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv 对应剧集 [2] 已下载过
【INFO】2024-06-13 16:33:17,181 - subscribe.py - 黑袍纠察队 (2019) 通过媒体信ID匹配到资源：红豆饭 - The Boys S04E02 Life Among the Septics 2160p AMZN WEB-DL DDP5.1 H 265-FLUX mkv
【INFO】2024-06-13 16:33:17,180 - subscribe.py - 订阅 黑袍纠察队 (2019) S04 缺失集：[]
【INFO】2024-06-13 16:33:17,178 - filetransfer - 黑袍纠察队 (2019) 文件系统已存在：{1: [1, 2], 2: [1, 2], 3: [1]}
【INFO】2024-06-13 16:33:16,782 - emby - 黑袍纠察队 (2019) 在媒体库中不存在
【INFO】2024-06-13 16:33:16,775 - themoviedb - 黑袍纠察队 TMDB识别结果：电视剧 黑袍纠察队 (2019) 76479
【INFO】2024-06-13 16:33:16,768 - subscribe.py - 开始匹配订阅，标题：黑袍纠察队 ..

**Comment by lzcer** [comment]
相同问题已提交过 #2261

**Comment by lzcer** [comment]
#2261 是洗版，估计情况不一样，我这个是没下载完成的情况，还没入库，重复下载了，日志里面没发现从下载器获取下载记录的逻辑

**Comment by siren44** [comment]
我之前也有这样的问题。搜了很久改了很多设置，后面发现是下载器的原因，之前用的tr下载的，但是遇到一些站点订阅下载种子后没有下载速度，0%直接显示做种了。资源没有入库，导致订阅刷新时间到了后又重复下载。换成qb下载就正常了。

**Comment by jxxghp** [comment]
看下了，貌似是入库太慢了导致重复下载，我看看是否可以优化下。

**Comment by lzcer** [comment]
> 看下了，貌似是入库太慢了导致重复下载，我看看是否可以优化下。

感谢回复

我印象中，好像在日志中看到过 ：拉取下载器正在下载的任务，来判断是否需要下载，但是在最近的日志中没有看到类似的逻辑，是不是改了？

感觉获取正在下载的任务来判断还是挺合理的，毕竟订阅周期一般不会太久，一般都是半个小时以内，但是一些新种下载比较慢，如果第二次周期开始还没下完，就是反复下载了

ps: 昨天回家又被下载了一次

**Comment by lzcer** [comment]
> 我之前也有这样的问题。搜了很久改了很多设置，后面发现是下载器的原因，之前用的tr下载的，但是遇到一些站点订阅下载种子后没有下载速度，0%直接显示做种了。资源没有入库，导致订阅刷新时间到了后又重复下载。换成qb下载就正常了。

感谢回复

我有确认下载器的情况，是正在下载的状态，也有速度，也是用的qb，应该和你遇到的问题不一样
