### ISSUE TITLE
始终无法设置目录

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#2328]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

更新版本后设立目录里始终无法选择也无法输入，只能显示根目录
![Clip_2024-06-13_20-32-49](https://github.com/jxxghp/MoviePilot/assets/67105838/15f7d67e-73aa-4ef8-9c07-004f936dcee6)
这是我的配置，使用的是unraid
![Clip_2024-06-13_20-33-59](https://github.com/jxxghp/MoviePilot/assets/67105838/2790a1c9-b6f1-44a1-8d75-7c0d1f47cdd2)

**Comment by cddjr** [comment]
有没有试过ctrl+f5强刷一下页面

**Comment by zero617** [comment]
> 有没有试过ctrl+f5强刷一下页面

试过 缓存也清理过

**Comment by Arexh** [comment]
点击文件夹图标打开，默认只显示根目录

**Comment by Aqr-K** [comment]
无痕模式试试，再不行就重启一下mp，再无痕模式，ctrl+f5强清刷新不是万能的

**Comment by kettly1260** [comment]
你解决了吗？我也无法设置目录
