### ISSUE TITLE
[错误报告]: 北洋园发布时间获取失败

### ISSUE THREAD

**Issue by EkkoG** [jxxghp/MoviePilot#2332]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

软件版本 v1.9.4 前端版本 v1.9.4 认证资源版本 1.2.8 站点资源版本 1.4.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

同一次搜索，观众种子的发布时间正常，北洋园的是空
![CleanShot 2024-06-14 at 10 31 39@2x](https://github.com/jxxghp/MoviePilot/assets/3138493/b29e95cb-7034-4270-9855-f469f7e93ea4)

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Resources/commit/780f2ca27a6a62a4190a50deae658e28ba7b2169

**Comment by EkkoG** [comment]
升级到 1.4.2 试了一下和之前一样
![CleanShot 2024-06-14 at 11 02 34@2x](https://github.com/jxxghp/MoviePilot/assets/3138493/46a2b2a9-8606-4e3d-8bbe-ffd64a6bffeb)
![CleanShot 2024-06-14 at 11 03 53@2x](https://github.com/jxxghp/MoviePilot/assets/3138493/6eb3ccae-d078-4038-a353-7d4c4f3456fe)
