### ISSUE TITLE
[错误报告]: 梓喵和rousi无法连通

### ISSUE THREAD

**Issue by yikexiaoyao** [jxxghp/MoviePilot#2333]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

梓喵和rousi无法连通，但是网页能正常打开，没有二级验证，尝试通过cookiecloud更新cookie还是不行，手动修改cookie也不行，刷流和签到也无法进行，没找到相关的后台日志信息，希望大佬能帮忙看一下什么问题，谢谢

**Comment by ohmyharry** [comment]
rousi 的问题，补充一下，我这里可以连通，cookiecloud也可用，可以签到，但从站点获取资源，无法连通。
好像是爬虫的方式不可用。
我用nastool的rss链接方式，是可以获取资源的。

贴一下详细的日志（好像也没什么可参考的）
【WARNING】2024-06-16 17:52:13,241 - indexer - Rousi 未搜索到数据，耗时 5 秒
【INFO】2024-06-16 17:52:07,319 - spider.py - 开始请求：https://rousi.zip/torrents.php
【INFO】2024-06-16 17:52:07,313 - torrents.py - 开始获取站点 rousi.zip 最新种子 ...
