### ISSUE TITLE
筛选季集有问题

### ISSUE THREAD

**Issue by syscc** [jxxghp/MoviePilot#2335]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

筛选季集默认列表下筛s几e几集没有问题，筛选s几 应该有问题，具体我只测试了s01 没反应，切换显示方式可以正常筛选
<img width="1386" alt="mp-1" src="https://github.com/jxxghp/MoviePilot/assets/65939241/63f67944-58ce-4873-bdd4-30775a98e91e">
<img width="1416" alt="mp-2" src="https://github.com/jxxghp/MoviePilot/assets/65939241/5c68a0e2-316f-46fe-af66-0aad4a5cfef3">
<img width="1364" alt="mp-3" src="https://github.com/jxxghp/MoviePilot/assets/65939241/98983eae-f57c-421e-bcf0-71b315f0fbf6">
<img width="1370" alt="mp-4" src="https://github.com/jxxghp/MoviePilot/assets/65939241/d16dcbd6-43dd-4d3e-8184-6a6f819d6123">

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/95f1ba01-c5b0-4b37-b001-4ef4afb27f18)
是这个意思吧 筛选季，选集也会出现

**Comment by syscc** [comment]
是完全没反应，正常应该是跟图4一样只有季，频道里有人测试也一样，我还清空缓存试了
