### ISSUE TITLE
[错误报告]: 订阅多季变订阅1季、自动入库不刮削、搜索资源后卡死、历史记录不更新

### ISSUE THREAD

**Issue by 15622162922** [jxxghp/MoviePilot#2336]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.4-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1. 当我订阅一部剧集的多个季时，最终订阅的结果仅为选中的一季（日志也显示仅订阅一季）
![image](https://github.com/jxxghp/MoviePilot/assets/49612681/b09fee6d-6e35-437a-886f-d4ab3ca243d4)
2. 当我搜索某个资源时，进度条会在“搜索完成，共XX个资源”处卡死
3. 使用目录监控插件，下载好的内容自动入库成功，但却没有出现nfo文件。在文件管理中重新整理并勾选刮削元数据后正常生成nfo文件。
4. 在文件管理中重新整理一整个文件夹（文件夹中包含了整季剧集），最终仅入库第一集。
![image](https://github.com/jxxghp/MoviePilot/assets/49612681/741693dc-052d-4702-be73-67011305e67e)
![image](https://github.com/jxxghp/MoviePilot/assets/49612681/f86db526-e007-420c-a55e-6e0a8e25919e)

5. 无论以何种方式入库，历史记录均没有新内容。
![image](https://github.com/jxxghp/MoviePilot/assets/49612681/5ee8bcfb-e7cc-4d65-a0e6-1fa8b639ec5d)

**Comment by 15622162922** [comment]
补充搜索资源卡死截图：
![1718347221406](https://github.com/jxxghp/MoviePilot/assets/49612681/fa6a4bcc-221c-4dba-ada3-8bab4bef30dd)
![1718347221410](https://github.com/jxxghp/MoviePilot/assets/49612681/b6359d34-d55e-4d68-ae51-e186cd462ff6)

**Comment by jxxghp** [comment]
1、一次性提交订阅的，正常：
<img width="1091" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/2dfa84a3-6014-4af2-9001-cfb7ed8ec542">
2、检查你的反向代理，是不是超时时间过短。

**Comment by 15622162922** [comment]
> 1、一次性提交订阅的，正常： <img alt="image" width="1091" src="https://private-user-images.githubusercontent.com/51039935/339663868-2dfa84a3-6014-4af2-9001-cfb7ed8ec542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDc4MTAsIm5iZiI6MTcxODM0NzUxMCwicGF0aCI6Ii81MTAzOTkzNS8zMzk2NjM4NjgtMmRmYTg0YTMtNjAxNC00YWYyLTkwMDEtY2ZiN2VkOGVjNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA2NDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZWUzYjk3MWM3YjBmNzcwMWI0MzkyNzc4MmQwN2Q1MGUwYjEyMDI1MmFjNDM2YTQxODU3YWI1ZTE3YmRjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.44RAexfH4DqDzDOHHZb_ttyKubQi781B6Ef5G-cSzgc"> 2、检查你的反向代理，是不是超时时间过短。

为何是检查反代呢，我配置了反代mp但我是用的内网IP直接访问的
