### ISSUE TITLE
[Feature Request]: jackett support

### ISSUE THREAD

**Issue by yaochenfeng** [jxxghp/MoviePilot#2339]
### 当前程序版本

1.9.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望支持 jackett 接入

### 参考资料

像nastools 一样

**Comment by dlovew** [comment]
这个不可能的，nastools官方版后来也不支持jackett的，支持的都是魔改版了

**Comment by yaochenfeng** [comment]
> 这个不可能的，nastools官方版后来也不支持jackett的，支持的都是魔改版了

这个不支持是有什么版权还是什么限制吗？
