### ISSUE TITLE
[错误报告]: 识别有误的，在历史记录里重新识别后，原识别错误的硬链接不会自动删除

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#234]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5

### 问题类型

主程序运行问题

### 问题描述

重新识别原硬链接不会删除

还有这个重新识别建议添加重新识别而不是手动输入TMDB编号呢。

**Comment by jxxghp** [comment]
v1.0.6
