### ISSUE TITLE
[错误报告]: 通过微信下载不能自动分类

### ISSUE THREAD

**Issue by renbaoxu** [jxxghp/MoviePilot#2340]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.9.5

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

我在网页上搜索下载的时候能够自动下载到分类好的目录中（/media/downloads/电影/外语电影），但是我通过发微信下载的内容就不能自动下载到分类好的目录内，而是直接在/media/downloads/电影。并且通过微信下载的硬链接之后也没有自动分类。目录设置这里我都选择的自动分类
![image_2024-06-15_10-26-21](https://github.com/jxxghp/MoviePilot/assets/84167945/98a698ae-0586-4a60-bc7f-f41ad35713dc)
上图中的种子，一个是通过网页下载的，可以自动分类，硬链接也能够自动分类。另一个种子是通过微信下载的，不能自动分类，硬链接也不能正确分类。
![photo_2024-06-15_10-43-57](https://github.com/jxxghp/MoviePilot/assets/84167945/9997283a-e8b6-4493-856c-dc082750acae)
上图是我目录设置的内容。

**Comment by qzj-123-zsd** [comment]
我也是遇到这个问题了，老哥解决没有？

**Comment by cheny95** [comment]
我和你的情况差不多但是又有不一样。
我在MP上搜索下载的时候，下载目录是（/media/downloads/外语电影），但是企业微信下载的也是直接在/media/downloads/电影。但是我硬链接后有分类。我已经重新装2次了。。。
![image](https://github.com/jxxghp/MoviePilot/assets/6293952/90464d50-988b-4fb7-9bfe-c99078a90668)
这是我这今天热乎的截图。
![image](https://github.com/jxxghp/MoviePilot/assets/6293952/061ce3d3-093b-4f13-b363-1d395b7da50c)
![image](https://github.com/jxxghp/MoviePilot/assets/6293952/d88170b0-b85a-4c0f-982f-a0a4bc3f3d1d)

**Comment by Putarku** [comment]
不要使用全部-全部，只保留电视剧-全部和电影-全部即可

**Comment by qzj-123-zsd** [comment]
我刚才通过微信下载好像又可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月23日(周日) 凌晨0:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [错误报告]: 通过微信下载不能自动分类 (Issue #2340)




 
我和你的情况差不多但是又有不一样。我的版本是1.9.7
 我在MP上搜索下载的时候，下载目录是（/media/downloads/外语电影），但是企业微信下载的也是直接在/media/downloads/电影。但是我硬链接后有分类。我已经重新装2次了。。。
 image.png (view on web)
 这是我这今天热乎的截图。
 image.png (view on web)
 image.png (view on web)
