### ISSUE TITLE
[错误报告]: 手动整理，指定part的使用疑问

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#2341]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

wiki上面说指定part 写法需要在规定的范围内，基本都是part1，dvd1这些
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/160a36b0-8005-4676-9ba5-d3d65de57103)
实际上，我下面随便弄了一个标题测试下，任何输入的字符好像都行啊
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/3c670172-d9d0-473a-ba03-080c91c63d5f)

还有一个问题对于电影类整理，如果要指定part，也必须在指定集数方框内填写集数，不然就不会生效。但电影都是单独个体，没有集数概念的吧，用的时候一开始没想到，试了几次才在指定集数方框内填了数字才成功
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/9f8d761f-d535-45bd-be2a-c5d85e67d3ac)

目前是我这个指定part的使用感受，请j大答疑

**Comment by MICSAD117** [comment]
另外一个问题是，如果指定part的蓝光电视剧，会覆盖已经整理好的part

**Comment by cng10001** [comment]
> 另外一个问题是，如果指定part的蓝光电视剧，会覆盖已经整理好的part

蓝光电视剧本身没法支持吧，没办法知道disc1 disk2到底包含几集电视剧，如果每个都手动实在没必要了吧

**Comment by MICSAD117** [comment]
但是有的资源下载下来就是分为part的，就不一定需要分集，就能正确刮削分类放进去就行，最近下了好几个大包，不知道咋处理
