### ISSUE TITLE
登录失败，请检查网络连接

### ISSUE THREAD

**Issue by stone100010** [jxxghp/MoviePilot#2344]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

jxxghp/moviepilot:1.9.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用参数里面提到的账号密码，并不能登陆
同时还显示：登录失败，请检查网络连接？？？？我本地电脑搭建的，我什么网络连接？？

### 发生问题时系统日志和配置文件

```bash
WARNING: login.py - 用户 admin 登录失败！
INFO:     172.18.0.1:0 - "POST /api/v1/login/access-token HTTP/1.1" 401 Unauthorized
INFO:     172.18.0.1:0 - "GET /api/v1/login/wallpaper HTTP/1.1" 200 OK
INFO:     172.18.0.1:0 - "GET /api/v1/user/otp/admin HTTP/1.1" 200 OK
WARNING: login.py - 用户 admin 登录失败！
INFO:     172.18.0.1:0 - "POST /api/v1/login/access-token HTTP/1.1" 401 Unauthorized
INFO:     172.18.0.1:0 - "GET /api/v1/login/access-token HTTP/1.1" 405 Method Not Allowed
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    scheduler.py - 用户未认证，正在尝试重新认证...
ERROR:   scheduler.py - 环境变量 AUDIENCES_UID 未设置！
INFO:    transfer.py - 没有获取到已完成的下载任务
ERROR:   scheduler.py - 环境变量 AUDIENCES_PASSKEY 未设置！
ERROR:   scheduler.py - audiences认证出错：不存在该用户或者此用户被封禁
ERROR:   scheduler.py - 用户认证失败：未能完成用户认证，请检查认证参数、站点连通性或站点用户状态是否正常！，共失败 1 次
```

**Comment by Kirk-77** [comment]
我也遇到了：登录失败，请检查网络连接

<img width="520" alt="屏幕截图 2024-06-15 211629" src="https://github.com/jxxghp/MoviePilot/assets/66934610/5621c2cb-a118-4eca-aa8c-92b99801c9ab">

**Comment by Joezhong111** [comment]
同样的问题

**Comment by Joezhong111** [comment]
别找了，密码再log里面
