### ISSUE TITLE
彩虹岛无法获取数据

### ISSUE THREAD

**Issue by cosmotown** [jxxghp/MoviePilot#2350]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.6

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

更新后彩虹岛无法获取数据了，显示连通性正常，但右上角图标黄色，点浏览是空的，搜索时也无法获取数据，不知道是对方网站更新了什么照成的还是我个例，求各位大大给个解决方法

**Comment by cosmotown** [comment]
cookie已经重新获取过了，没有什么作用

**Comment by cng10001** [comment]
没问题啊，大概率是你的个例吧，群里有人反应同样的的问题吗
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/d9b32db1-10c7-43a8-8b12-34426a9c756f)

**Comment by cosmotown** [comment]
> 没问题啊，大概率是你的个例吧，群里有人反应同样的的问题吗 ![image](https://private-user-images.githubusercontent.com/115156545/340756459-d9b32db1-10c7-43a8-8b12-34426a9c756f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjA0NzAsIm5iZiI6MTcxODg2MDE3MCwicGF0aCI6Ii8xMTUxNTY1NDUvMzQwNzU2NDU5LWQ5YjMyZGIxLTEwYzctNDNhOC04YjEyLTM0NDI2YTljNzU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNTA5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDNlYjg5OGUwNDdiMzZiZWZkYmVkOTFkN2FlNWVlNzU1NzY0YmIwOWRhOTRiNzA2MDk2YmJlZGJlNzhlNWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qQttNvJieojuyBpURxl46YkGJOhRdmCW64yYkBE5nu8)

我重新安装后已经正常了
