### ISSUE TITLE
订阅的电影，反复推送下载通知

### ISSUE THREAD

**Issue by Tuo05** [jxxghp/MoviePilot#2353]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![微信图片_20240617143319](https://github.com/jxxghp/MoviePilot/assets/172877228/90487ba6-222a-44b8-a6c7-3ec01abcf6f9)
使用的Slack推送通知，所有订阅的电影，开始下载之后，就会反复推送下载通知，一天可以推送七八条重复的内容

**Comment by jxxghp** [comment]
提供日志

**Comment by Tuo05** [comment]
> 提供日志
我以今天的疯狂的麦克斯为例，一上午已经推送了五次，我把最近两次的日志复制如下：

**第一次（9:20）**
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>描述：疯狂的麦克斯：狂暴女神/Furiosa:&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga/疯狂的麦克斯：弗瑞奥萨/芙莉欧莎：疯狂麦斯传奇篇章(台)/芙莉欧..，userid=None
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>做种数：107
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>发布时间：2024-06-24&nbsp;07:31:41
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>种子：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>大小：7.57G
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>质量：&nbsp;WEB-DL&nbsp;1080p
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>站点：猫站
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:12</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;chain&nbsp;-&nbsp;发送消息：channel=None，title=疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;&nbsp;开始下载,&nbsp;text=用户：admin
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:11</td><td>stdout</td><td>[33mWARNING:[0m&nbsp;qbittorrent&nbsp;-&nbsp;下载器中已存在该种子任务：c6cc68704ffaac664ce58a98c3cfff8e582e47b0&nbsp;-&nbsp;Furiosa.A.Mad.Max.Saga.2024.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;download.py&nbsp;-&nbsp;开始下载电影&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX&nbsp;...
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配完成，共匹配到5个资源
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB&nbsp;H264-FuriousMax
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB&nbsp;H264-FuriousMax
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;HDR&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;HDR&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;themoviedb&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;TMDB识别结果：电影&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;786892
</td></tr>
<tr><td>2024/06/24&nbsp;09:20:10</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;开始匹配订阅，标题：疯狂的麦克斯：狂暴女神&nbsp;...
</td></tr>


**第二次（10:33）**
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>描述：疯狂的麦克斯：狂暴女神/Furiosa:&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga/疯狂的麦克斯：弗瑞奥萨/芙莉欧莎：疯狂麦斯传奇篇章(台)/芙莉欧..，userid=None
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>做种数：107
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>发布时间：2024-06-24&nbsp;07:31:41
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>种子：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>大小：7.57G
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>质量：&nbsp;WEB-DL&nbsp;1080p
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>站点：猫站
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;chain&nbsp;-&nbsp;发送消息：channel=None，title=疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;&nbsp;开始下载,&nbsp;text=用户：admin
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:22</td><td>stdout</td><td>[33mWARNING:[0m&nbsp;qbittorrent&nbsp;-&nbsp;下载器中已存在该种子任务：c6cc68704ffaac664ce58a98c3cfff8e582e47b0&nbsp;-&nbsp;Furiosa.A.Mad.Max.Saga.2024.1080p.WEB-DL.DDP5.1.Atmos.H.264-FLUX.mkv
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;download.py&nbsp;-&nbsp;开始下载电影&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX&nbsp;...
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配完成，共匹配到6个资源
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5&nbsp;1&nbsp;Atmos&nbsp;H&nbsp;264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：听听歌&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5&nbsp;1&nbsp;Atmos&nbsp;H&nbsp;264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;H.264-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB&nbsp;H264-FuriousMax
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;1080p&nbsp;WEB&nbsp;H264-FuriousMax
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;匹配成功：Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;HDR&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;通过媒体信ID匹配到资源：猫站&nbsp;-&nbsp;Furiosa&nbsp;A&nbsp;Mad&nbsp;Max&nbsp;Saga&nbsp;2024&nbsp;2160p&nbsp;WEB-DL&nbsp;DDP5.1&nbsp;Atmos&nbsp;DV&nbsp;HDR&nbsp;H.265-FLUX
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;themoviedb&nbsp;-&nbsp;疯狂的麦克斯：狂暴女神&nbsp;TMDB识别结果：电影&nbsp;疯狂的麦克斯：狂暴女神&nbsp;(2024)&nbsp;786892
</td></tr>
<tr><td>2024/06/24&nbsp;10:33:20</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;subscribe.py&nbsp;-&nbsp;开始匹配订阅，标题：疯狂的麦克斯：狂暴女神&nbsp;...
