### ISSUE TITLE
无法查看资源详情，无法进入推荐页

### ISSUE THREAD

**Issue by skylovezr** [jxxghp/MoviePilot#2363]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

点击左侧推荐无任何反应；在搜索页的电视剧点击没有任何反应，无法进入详情（可订阅及取消订阅）；已订阅的电视剧点查看详情无任何反应（其余的按钮可正常响应）；以上无反应的操作在日志页面也没有日志；新版更新后已重启docker，重启容器，ctrl+f5操作

**Comment by cddjr** [comment]
更新版本后记得 ctrl+f5

**Comment by skylovezr** [comment]
感谢大佬回复，但是已经ctrl+f5多次了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jxxghp/MoviePilot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 上午9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jxxghp/MoviePilot] 无法查看资源详情，无法进入推荐页 (Issue #2363)





 
更新版本后记得 ctrl+f5

**Comment by skylovezr** [comment]
> 如果ctrl+f5不行，尝试隐私模式，如果正常了说明还是缓存问题。

6，隐私模式是ok的。大佬流批
