### ISSUE TITLE
目录同步设置问题

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/MoviePilot#2366]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

想问下为什么如下配置，我放在阿里云盘的dowloads文件夹下的影片会被同步到迅雷网盘，是哪一块地方配置有问题么。另外，一级分类只能是电影电视剧，但是这两个文件夹的名称可以自定义吗，因为我的需求其实就是把每个盘的download文件夹的东西整理到对应盘的TV 和Movies文件夹，以前是直接把二级目录的名称改为TV Movies
![MoviePilot](https://github.com/jxxghp/MoviePilot/assets/51586004/2eb97da1-f710-49d0-af11-5fe6385a4a7b)

**Comment by zoffyultraman** [comment]
你需要理解，二级分类是程序用来识别的，至于目录，你可以指定一个/video/sssssss为电影，/video/xxxxx为电视
