### ISSUE TITLE
[错误报告]: 下载种子， 提示未找到下载目录， 已在设定/目录/下载目录中添加映射在容器中的目录

### ISSUE THREAD

**Issue by CharisLee** [jxxghp/MoviePilot#2377]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

**资源搜索中下载种子文件时， 提示添加下载任务失败：**
![image](https://github.com/jxxghp/MoviePilot/assets/12951832/40bd609a-2ae8-4ebf-ad64-d1b620015a46)

**查看日志， 提示未找到下载目录：**
![image](https://github.com/jxxghp/MoviePilot/assets/12951832/6d492b3c-cc9e-4aea-aa98-87c00913a003)

**健康检查未发现问题：**
![image](https://github.com/jxxghp/MoviePilot/assets/12951832/53d48432-0221-4547-b578-8c0e30f7b568)

**下载目录如下：**
/download/media/
![image](https://github.com/jxxghp/MoviePilot/assets/12951832/66a5b5a0-e499-4556-a36c-61664ee08c0b)

**使用插件 “添加种子下载v1.0” 可以添加下载任务到qbittorrent**

**Comment by zoffyultraman** [comment]
请不要使用全部-全部分类，使用电影-全部和电视剧-全部，应该就可以了

**Comment by xmlijian** [comment]
> 请不要使用全部-全部分类，使用电影-全部和电视剧-全部，应该就可以了

牛了个大了。 搞了半天一直不知道是什么原因。。。哎。瞎折腾啊。

**Comment by lindaiyu99** [comment]
> 请不要使用全部-全部分类，使用电影-全部和电视剧-全部，应该就可以了

哭了，感谢

**Comment by luowentaogo** [comment]
哭了，真的是这样，一下子就好了

**Comment by dalaosec** [comment]
试了还是不行，鸟用不顶

**Comment by mzl5920** [comment]
> 试了还是不行，鸟用不顶

改了 电影-全部  不行  后来发现是 添加订阅的时候 下载器选错了
