### ISSUE TITLE
下载器限速

### ISSUE THREAD

**Issue by Wangsc1** [jxxghp/MoviePilot#2379]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.7

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

下载器没有限速功能，因为是搭建在盒子上面的，所以有些热门影片订阅到之后上传速度会爆表，容易被站点ban，在issues #1436 看到同样反馈，我看状态是close as completed，但是我在连接下载器那边以及搜索了所有插件没有看到相关功能，麻烦大佬能给加个功能，谢谢

**Comment by zoffyultraman** [comment]
下载器如果都没有限速，那mp没法限制啊，除非你qb或者tr带限速功能。
