### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by gzAaron** [jxxghp/MoviePilot#2387]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.7

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

硬连接的问题，为什么我在目录里面并没有配置的下载目录，结果QB下载到该目录里，却被硬连接了。

**Comment by zoffyultraman** [comment]
下载目录是mp传递任务给qb的时候用的。你这个应该检查是否使用了目录监控插件，或者开启了下载器监控后，给任务打了mp的标签。
