### ISSUE TITLE
[错误报告]: 搜索页面，家园的种子不会显示正确的视频体积，显示的是种子文件体积

### ISSUE THREAD

**Issue by FAN-LION** [jxxghp/MoviePilot#2389]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索页面，家园的种子不会显示正确的视频体积，显示的是种子文件体积

### 发生问题时系统日志和配置文件

```bash
INFO: 172.17.0.1:0-"GET /api/v1/dashboard/memory HTTP/1.1" 200 OK
```

**Comment by jxxghp** [comment]
没问题，检查站点的控制面板是不是改了什么设置导致UI变化。

<img width="1257" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/5a0c8724-3cdf-45f5-8bfa-1be346016c2d">

<img width="746" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/7004e12e-7924-44fd-a803-4e0431b80f7b">
