### ISSUE TITLE
[错误报告]: 转移了sample文件

### ISSUE THREAD

**Issue by sungamma** [jxxghp/MoviePilot#239]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5

### 问题类型

主程序运行问题

### 问题描述

直接用mp搜索下载了一个电影，电影带sample文件，而且该文件应该是先下载好，被mp直接识别转移了。随后又识别到正片，但由于不能覆盖，导致出错。最终入库的只是sample文件

### 发生问题时系统日志和配置文件
![image](https://github.com/jxxghp/MoviePilot/assets/33790/9f4b21ae-4c20-469a-be74-e6c8565659e2)

_No response_

**Comment by developer-wlj** [comment]
日志贴的不对，这是电报连接超时，不是搜索日志，一般只要不是 一直都是很慢的样子，不用管它
