### ISSUE TITLE
[错误报告]: 文件管理打不开，路径无法正确识别，也无法新建目录

### ISSUE THREAD

**Issue by Ailina0728** [jxxghp/MoviePilot#2390]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.7

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

更新后，之前稳定使用的路径无法识别，文件管理页面无法打开，之前创建好的路径自己变成了奇怪的形式。在设置--目录中新建路径也无法自动读取根目录。
<img width="812" alt="bug5" src="https://github.com/jxxghp/MoviePilot/assets/24652865/e5f0338f-69d0-46ee-92fd-78c344e21333">
<img width="294" alt="bug4" src="https://github.com/jxxghp/MoviePilot/assets/24652865/b4280286-8e73-4c8e-8455-36930a7af4da">
<img width="826" alt="bug3" src="https://github.com/jxxghp/MoviePilot/assets/24652865/923124ed-c27d-4df0-b336-f7e933ec6c46">
<img width="548" alt="bug2" src="https://github.com/jxxghp/MoviePilot/assets/24652865/cf9b3aa8-19ea-45f5-b82a-143cfab7688c">
<img width="767" alt="bug1" src="https://github.com/jxxghp/MoviePilot/assets/24652865/e9e4b7db-eda0-49cf-92a1-7907f5eabb58">

### 发生问题时系统日志和配置文件

```bash
DEBUG:   chain - 请求模块执行：downloader_info ...
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/system/setting/DownloadDirectories HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/filebrowser/list?path=H%3A%5CShares%2F%E4%B8%8B%E8%BD%BD%E7%AB%99%2F&sort=name HTTP/1.1" 404 Not Found
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/cpu HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/qbittorrent HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/memory HTTP/1.1" 200 OK
DEBUG:   chain - 请求模块执行：downloader_info ...
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/cpu HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/cpu HTTP/1.1" 200 OK
INFO:     192.168.10.20:0 - "GET /api/v1/dashboard/memory HTTP/1.1" 200
```

**Comment by jxxghp** [comment]
清浏览器缓存文件
