### ISSUE TITLE
[错误报告]: 下载文件整理 执行失败

### ISSUE THREAD

**Issue by BianTan** [jxxghp/MoviePilot#2392]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

通过MP进行资源下载后通知提示：
下载文件整理 执行失败
unterminated character set at position 31
![1719018883560](https://github.com/jxxghp/MoviePilot/assets/13924889/7c9c4520-a924-4df8-bd07-0778afcd9606)

**Comment by cng10001** [comment]
你看看是不是重命名格式错了啊- -
