### ISSUE TITLE
[Feature Request]: 刮削时是否可选择自动添加.plexmatch文件辅助plex匹配

### ISSUE THREAD

**Issue by kiritoxjf** [jxxghp/MoviePilot#2393]
### 当前程序版本

v1.9.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

因为Plex使用TMDB数据进行识别时，往往存在非常严重的识别错误，需要挨个手动识别，如果能在文件整理时就写入.plexmatch文件，在其中书写tmdbid，可以非常有效得帮助plex匹配

**Comment by zoffyultraman** [comment]
那为什么不直接使用mp的刮削呢

**Comment by kiritoxjf** [comment]
> 那为什么不直接使用mp的刮削呢

Plex不会使用本地的刮削文件的啊，它是独立存储的

**Comment by zoffyultraman** [comment]
我用过plex，他是可以识别本地的nfo之类的文件的

**Comment by InfinityPacer** [comment]
https://github.com/InfinityPacer/MoviePilot-Plugins/commit/5e36e9d0e6006c7ae07fd06cf1fe5562e81acabf
已加个人插件库
