### ISSUE TITLE
PT、BT标签没有自动添加

### ISSUE THREAD

**Issue by xhg2866** [jxxghp/MoviePilot#2394]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.7

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在订阅时添加的种子没有打上BT或者PT的标签，之前好像没啥问题

**Comment by jxxghp** [comment]
找对应的插件库提问题
