### ISSUE TITLE
[Feature Request]: 页面加载的时候增加loading效果

### ISSUE THREAD

**Issue by 907739769** [jxxghp/MoviePilot#2399]
### 当前程序版本

v1.9.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

页面加载的时候增加loading效果，发现页面数据加载比较慢，页面点进去是默认没有数据的，没有loading效果，感觉是数据没有了一样，过了一段时间数据才加载出来。

**Comment by jxxghp** [comment]
是哪个页面加载慢？目前几个主要页面都是keep-alive，应该是秒开的吧
