### ISSUE TITLE
[错误报告]: 阿里云盘备份盘整理以及重命名文件失败

### ISSUE THREAD

**Issue by XINMENG96** [jxxghp/MoviePilot#2400]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.8-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

阿里云盘重命名失败，备份盘，自动识别名称-确定，显示报错
![屏幕截图 2024-06-23 145530](https://github.com/jxxghp/MoviePilot/assets/124113779/f6710e8e-04a1-4908-85af-5240ea3b523a)

### 发生问题时系统日志和配置文件

```bash
【WARNING】2024-06-23 15:07:59,450 - aliyun.py - Aliyun 重命名文件失败：NotFound.File - The resource File cannot be found. file not exist, trashed or deleted
【INFO】2024-06-23 15:07:58,625 - themoviedb - Tenet TMDB识别结果：电影 信条 (2020) 577922
【INFO】2024-06-23 15:07:58,618 - themoviedb - Tenet 使用TMDB识别缓存：信条
```

**Comment by ChampionChann** [comment]
+1
![image](https://github.com/jxxghp/MoviePilot/assets/74972604/3d8ce0f2-875c-4e27-a5ed-823c7a3f8918)

**Comment by XINMENG96** [comment]
整理也是显示报错的

> 【ERROR】2024-06-23 16:25:54,273 - transfer.py - /备份盘/Emby/电视剧/东瀛大宝荐 (2023)/ 重命名失败
【WARNING】2024-06-23 16:25:54,270 - aliyun.py - Aliyun 重命名文件失败：NotFound.File - The resource File cannot be found. file not exist, trashed or deleted
【INFO】2024-06-23 16:25:54,009 - transfer.py - 正在重命名 /备份盘/Emby/电视剧/东瀛大宝荐 (2023)/ => 东瀛大宝荐 (2023) ...
【INFO】2024-06-23 16:25:53,770 - themoviedb - 东瀛大宝荐 TMDB识别结果：电视剧 东瀛大宝荐 (2023) 240685

**Comment by XINMENG96** [comment]
资源库是没有问题的
