### ISSUE TITLE
[错误报告]: /api/v1/message/接口时好时坏

### ISSUE THREAD

**Issue by sword0922** [jxxghp/MoviePilot#2404]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.8-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

这接口总是shi'hao'shi'huai是好是坏。导致微信容易失联无法互动

### 发生问题时系统日志和配置文件

```bash
status": "ERROR"
```

**Comment by sword0922** [comment]
![微信图片_20240623222625](https://github.com/jxxghp/MoviePilot/assets/83168236/bbdfda82-1c12-4253-bf3c-6f489cd7e7a3)
![微信图片_20240623222628](https://github.com/jxxghp/MoviePilot/assets/83168236/08554faf-e2aa-4cc4-8838-31ccfc8711ee)

**Comment by jinghua625** [comment]
可能和#2315 是类似的情况
