### ISSUE TITLE
PT站 天空问题[Feature Request]: 

### ISSUE THREAD

**Issue by dalanchongjun** [jxxghp/MoviePilot#2405]
### 当前程序版本

1.9.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

最近我的空一直收到警告，限制搜索功能，经过排查 我才发现是  因为我天空  一个小时搜索次数超过20次，被警告。原因如下：
1、我的MP中 订阅电影 电视剧较多。（动漫较多）
     服务中有一项，24小时自动搜索补全订阅。MP每搜索一个订阅，会随机休眠100多秒。大多数不超过180秒。
2、HD天空有一项规定，一个小时内搜索次数不得超过20次
3、导致这一个小时补全订阅的过程中，HD天空搜索次数可能会超过20次，引发系统警告，故能不能请求调整，搜索间隔改成3~4分钟，这样才不会引发警告！  （不然可能天空可能会封号）。
感谢大大关注一下 谢谢

**Comment by Putarku** [comment]
站点设置里面本身就有站点的流控规则，可以限制单位周期的访问次数，自己配置下就好了

**Comment by dalanchongjun** [comment]
我设置了流控规则了 还是没用

**Comment by dalanchongjun** [comment]
> 站点设置里面本身就有站点的流控规则，可以限制单位周期的访问次数，自己配置下就好了

我设置了流控规则了 还是没用

**Comment by dalanchongjun** [comment]
大佬 我顶一下  看一下能不能解决呀

**Comment by Ladavian** [comment]
同样碰到这个问题，空经常弹出警告
