### ISSUE TITLE
建议给刷流增加个功能

### ISSUE THREAD

**Issue by xxtyyq** [jxxghp/MoviePilot#2417]
### 当前程序版本

1.9.8

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望在刷流（低频）里的统一设置中增加个功能，限制各站点正在下载任务数。目前手里四个站点，同时下载任务数20（不想设置过多任务），有时候到了第二个站点就满了…所以如果有限制各站点任务数功能，比如限制5，这样就能保证每个站点都在下载了。个人想法~

**Comment by InfinityPacer** [comment]
关闭顺序刷流即可

**Comment by xxtyyq** [comment]
谢谢！
