### ISSUE TITLE
[错误报告]: 站点自动签到

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#242]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.5

### 问题类型

插件问题

### 问题描述

有CF验证的站点，实际未签到成功，插件通知签到成功

受影响的站点包括不限于 ：
我堡
自由农场

**Comment by 9606** [comment]
+1

**Comment by iarthit** [comment]
【BUG】冬樱也一样，插件提示签到成功，实际未签到成功
