### ISSUE TITLE
[Feature Request]: 能否在提交给QB下载器的时候，提交分类信息。

### ISSUE THREAD

**Issue by yangc-vip** [jxxghp/MoviePilot#2436]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否在提交给QB下载器的时候，提交分类信息，以便让QB按照提交的分类自动保存到提前设置好的目录。
目前自动订阅后提交的下载，在QB中都显示未分类。因为我关闭了自动分类。使用的都是手动在QB设置的分类。
分类名称可以以目录设置里的别名为准。

比如“目录设置”“下载目录”里有一个“动画电影”的别名，其媒体类别设为“动画电影”，当自动订阅识别到电影与此项配置匹配后，提交给QB只包含种子与分类名“动画电影”具体下载目录让QB自动使用设置好的相应分类的下载目标目录。
 
谢谢。

**Comment by Putarku** [comment]
![Uploading image.png…]()
你把这个开关打开就会传递分类了，但需要配置好qb那边分类的保存路径。打开这个开关以后mp只会传递分类而不会传递路径了

**Comment by yangc-vip** [comment]
> ![图像](https://private-user-images.githubusercontent.com/66679443/343237229-70540c92-005b-4241-a8c3-f81e4ba96a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjE4MDMsIm5iZiI6MTcxOTQ2MTUwMywicGF0aCI6Ii82NjY3OTQ0My8zNDMyMzcyMjktNzA1NDBjOTItMDA1Yi00MjQxLWE4YzMtZjgxZTRiYTk2YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA0MTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTFkZjcwYjc2NTM2ZTU4MzFiNzJiOWI1MDRjODU3YjhkMGZmZTBmMWUyY2M0OGM4YTJiMzZjNjIwYTZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v_WQyFprCqtm95VnHAIygltAwS8ZW40dtScoffkh7U) 你把这个开关打开就会传递分类，但需要配置好qb那边分类的保存路径。打开这个开关以后mp只会与传递路径一起传递分类

请问这个分类的来源依据是MP自动生成的，还是目录设置里“下载目录”或者 “媒体库目录”里的别名？我想要自定义分类名称，比如“国漫”与“日番”类别的剧，我提交到QB的时候分类名为“动漫”放到一个库里了。如果是系统自动生成，是否有配置文件可以尝试自定义更改以实现这个功能？

**Comment by Putarku** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/66679443/343237229-70540c92-005b-4241-a8c3-f81e4ba96a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjE4MDMsIm5iZiI6MTcxOTQ2MTUwMywicGF0aCI6Ii82NjY3OTQ0My8zNDMyMzcyMjktNzA1NDBjOTItMDA1Yi00MjQxLWE4YzMtZjgxZTRiYTk2YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA0MTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTFkZjcwYjc2NTM2ZTU4MzFiNzJiOWI1MDRjODU3YjhkMGZmZTBmMWUyY2M0OGM4YTJiMzZjNjIwYTZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v_WQyFprCqtm95VnHAIygltAwS8ZW40dtScoffkh7U) 你把这个开关打开就会传递分类，但需要配置好qb那边分类的保存路径。打开这个开关以后mp只会与传递路径一起传递分类
> 
> 请问这个分类的来源依据是MP自动生成的，还是目录设置里“下载目录”或者 “媒体库目录”里的别名？我想要自定义分类名称，比如“国漫”与“日番”类别的剧，我提交到QB的时候分类名为“动漫”放到一个库里了。如果是系统自动生成，是否有配置文件可以尝试自定义更改以实现这个功能？

这个分类我记得应该是传递的二级分类，也就是国漫日漫、国产剧欧美剧这种

**Comment by yangc-vip** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/66679443/343237229-70540c92-005b-4241-a8c3-f81e4ba96a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjE4MDMsIm5iZiI6MTcxOTQ2MTUwMywicGF0aCI6Ii82NjY3OTQ0My8zNDMyMzcyMjktNzA1NDBjOTItMDA1Yi00MjQxLWE4YzMtZjgxZTRiYTk2YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA0MTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTFkZjcwYjc2NTM2ZTU4MzFiNzJiOWI1MDRjODU3YjhkMGZmZTBmMWUyY2M0OGM4YTJiMzZjNjIwYTZmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v_WQyFprCqtm95VnHAIygltAwS8ZW40dtScoffkh7U) 你把这个开关打开就会传递分类，但需要配置好qb那边分类的保存路径。打开这个开关以后mp只会与传递路径一起传递分类
> > 
> > 
> > 请问这个分类的来源依据是MP自动生成的，还是目录设置里“下载目录”或者 “媒体库目录”里的别名？我想要自定义分类名称，比如“国漫”与“日番”类别的剧，我提交到QB的时候分类名为“动漫”放到一个库里了。如果是系统自动生成，是否有配置文件可以尝试自定义更改以实现这个功能？
> 
> 这个分类我记得应该是传递的二级分类，也就是国漫日漫、国产剧欧美剧这种

那就是自动生成，，好尴尬，谢谢
