### ISSUE TITLE
选择目录没有挂载磁盘的目录

### ISSUE THREAD

**Issue by 137054853a** [jxxghp/MoviePilot#2438]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

环境：ubuntu虚拟机中，docker运行，版本号 v1.9.9。
虚拟机挂载了一块磁盘，映射到/data下
设置下载目录，媒体目录时候没有data这个目录

**Comment by 137054853a** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/10253622/7f1bf91f-84fb-4f0d-b902-ddbb16374fcf)
无/data 目录，在容器命令上已经添加 --privileged=true 参数

**Comment by 137054853a** [comment]
sudo docker run -itd \
    --name moviepilot \
    --hostname moviepilot \
    --privileged=true \
    -p 3000:3000 \
    -v /data/public/media:/media \
    -v /opt/moviepilot/config:/config \
    -v /opt/moviepilot/core:/moviepilot/.cache/ms-playwright \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -e 'NGINX_PORT=3000' \
    -e 'PORT=3001' \
    -e 'PUID=0' \
    -e 'PGID=0' \
    -e 'UMASK=000' \
    -e 'TZ=Asia/Shanghai' \
    -e 'AUTH_SITE=iyuu' \
    -e 'IYUU_SIGN=xxxx' \
    -e 'SUPERUSER=admin' \
    -e 'API_TOKEN=moviepilot' \
    --log-driver "json-file" \
    --log-opt "max-size=5m" \
    --restart always \
    jxxghp/moviepilot:latest

**Comment by singer1026** [comment]
> sudo docker run -itd --name moviepilot --hostname moviepilot --privileged=true -p 3000:3000 -v /data/public/media:/media -v /opt/moviepilot/config:/config -v /opt/moviepilot/core:/moviepilot/.cache/ms-playwright -v /var/run/docker.sock:/var/run/docker.sock:ro -e 'NGINX_PORT=3000' -e 'PORT=3001' -e 'PUID=0' -e 'PGID=0' -e 'UMASK=000' -e 'TZ=Asia/Shanghai' -e 'AUTH_SITE=iyuu' -e 'IYUU_SIGN=xxxx' -e 'SUPERUSER=admin' -e 'API_TOKEN=moviepilot' --log-driver "json-file" --log-opt "max-size=5m" --restart always jxxghp/moviepilot:latest

尝试重启下docker容器

**Comment by 137054853a** [comment]
> > sudo docker run -itd --name moviepilot --hostname moviepilot --privileged=true -p 3000：3000 -v /data/public/media：/media -v /opt/moviepilot/config：/config -v /opt/moviepilot/core：/moviepilot/.cache/ms-playwright -v /var/run/docker.sock：/var/run/docker.sock：ro -e 'NGINX_PORT=3000' -e 'PORT=3001' -e 'PUID=0' -e 'PGID=0' -e 'UMASK=000' -e 'TZ=Asia/Shanghai' -e 'AUTH_SITE=iyuu' -e 'IYUU_SIGN=xxxx' -e 'SUPERUSER=admin' -e 'API_TOKEN=moviepilot' --log-driver “json-file” --log-opt ”max-size=5m“ --始终重新启动 jxxghp/moviepilot：latest
> 
> 尝试重启下docker容器

已经重启过很多次了，无效

**Comment by zoffyultraman** [comment]
“/data/public/media:/media”
虽然但是你虚拟机映射了data，但是容器内的路径是media，是否存在这个路径，这个路径内容是否和你本机的/data/public/media目录内容一致

**Comment by nzmkNARUTO** [comment]
> sudo docker run -itd --name moviepilot --hostname moviepilot --privileged=true -p 3000:3000 -v /data/public/media:/media -v /opt/moviepilot/config:/config -v /opt/moviepilot/core:/moviepilot/.cache/ms-playwright -v /var/run/docker.sock:/var/run/docker.sock:ro -e 'NGINX_PORT=3000' -e 'PORT=3001' -e 'PUID=0' -e 'PGID=0' -e 'UMASK=000' -e 'TZ=Asia/Shanghai' -e 'AUTH_SITE=iyuu' -e 'IYUU_SIGN=xxxx' -e 'SUPERUSER=admin' -e 'API_TOKEN=moviepilot' --log-driver "json-file" --log-opt "max-size=5m" --restart always jxxghp/moviepilot:latest

你把容器外部的/data/public/media目录映射到容器内部的/media，那你应该在容器内部找/media这个目录。你容器内是否有/media这个目录？
