### ISSUE TITLE
[错误报告]: 添加馒头显示不支持

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#244]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.5

### 问题类型

主程序运行问题

### 问题描述

馒头无法同步，也无法手动添加，显示不支持

![image](https://github.com/jxxghp/MoviePilot/assets/67105838/77416d5c-8d9c-47ef-a1ed-12236d33198d)
![image](https://github.com/jxxghp/MoviePilot/assets/67105838/29db8862-05a1-47da-9db3-701b57d13cd1)

**Comment by dlovew** [comment]
添加主域名这个是备用地址
