### ISSUE TITLE
[错误报告]: 文件管理，没有阿里云和115网盘

### ISSUE THREAD

**Issue by yonly1314** [jxxghp/MoviePilot#2440]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

文件管理，没有阿里云和115网盘，更新版本后，阿里云和115不见了。清理缓存，无痕模式，换浏览器，PC，手机浏览器，都不行
![image](https://github.com/jxxghp/MoviePilot/assets/83340866/bab87e88-74d0-47cf-9d6d-72e35e742abb)

**Comment by singer1026** [comment]
我也遇到和你一样的问题，用docker第一次装MoviePilot，也没有出现115 阿里云盘，群里说要删缓存，问题是我是一次装 哪里有缓存，后面我尝试过，删浏览器缓存，换浏览器，删除docker image 删除容器  删除mp的所有文件，完全重新pull，再后面还用过朋友的设备装，装了3台设备都没有出来这个网盘选项

**Comment by jxxghp** [comment]
先完成用户认证
