### ISSUE TITLE
在文件管理里手动点击已经分类管理好的剧集的刮削按钮，刮削完的图片会在剧集目录的根目录

### ISSUE THREAD

**Issue by MuseYkh** [jxxghp/MoviePilot#2444]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在文件管理里手动点击已经分类管理好的剧集的刮削按钮，刮削完的图片会在剧集目录的根目录
例如：tv>国产剧>XXX(2024) 点击刮削
刮削完的图片会存在tv目录下，即 tv>background.jpg

**Comment by YanTaocheng** [comment]
我也遇到了，电影点刮削是没这个问题的，只有电视剧会这样
