### ISSUE TITLE
[Feature Request]: 自动重命名格式增加：季年份

### ISSUE THREAD

**Issue by Fzlwhyc** [jxxghp/MoviePilot#2447]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

有些节目季数很多，而距离首播年份遥远，希望可以增加季年份的格式，方便整理文件时观察。TMDB自带季年份数据，命名带季年份，在媒体客户端执行刮削时指向也会更准确。
比如用{season_year}代表季年份，格式设置为：{year} {title}/{title}S{season:0>2}.{season_year}/{title}{season_episode}，
就可以实现：2013 歌手/歌手S09.2024/歌手S09E01.ts
而现版本只有{year}这一个格式，重命名格式设置为：{year} {title}/{title}S{season:0>2}.{year}/{title}{season_episode}，
就会得到：2013 歌手/歌手S09.2013/歌手S09E01.ts
歌手第九季是今年播出的，这样就不准确了。。

软件很好用，希望更完美！

### 参考资料

![image](https://github.com/jxxghp/MoviePilot/assets/173179378/abd576af-523a-4c6e-b8dd-b4fe2be76d2f)

**Comment by AisukaYuki** [comment]
[自定义重命名](https://wiki.movie-pilot.org/zh/advanced#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%87%8D%E5%91%BD%E5%90%8D)

**Comment by Fzlwhyc** [comment]
> [自定义重命名](https://wiki.movie-pilot.org/zh/advanced#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%87%8D%E5%91%BD%E5%90%8D)

看了好多遍，所以是支持的吗？请求指教。。

**Comment by AisukaYuki** [comment]
season_years在做年份匹配的时候有用到。但是命名相关的代码没有做这个参数的出来。MediaInfo没有对这个值做定义。不能直接用。

![image](https://github.com/jxxghp/MoviePilot/assets/17586327/f775a390-c5ab-4f6a-987e-0b3c6c83b6aa)

**Comment by AisukaYuki** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/703dfbcb-954e-4f05-bcdc-d5a9dd568cca)
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/5babed69-6b31-43eb-9c00-a4142a9c9e42)
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/bbbc008c-36b4-4838-b6e4-9788c8437879)
你想实现的就是这样吧。
修改 app\modules\filetransfer\__init__.py 增加两行代码就能实现。

```
增加 L655: season_year = mediainfo.season_years.get(meta.begin_season, None)
增加 L695: # 季年份
                 "season_year": season_year,
```
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/46c424b2-f730-40e4-8d8e-c770ecc07075)
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/8e152eaa-510e-40de-b837-7c3451adfdd5)

**Comment by Fzlwhyc** [comment]
> ![image](https://private-user-images.githubusercontent.com/17586327/344363040-703dfbcb-954e-4f05-bcdc-d5a9dd568cca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzYyNzcsIm5iZiI6MTcxOTYzNTk3NywicGF0aCI6Ii8xNzU4NjMyNy8zNDQzNjMwNDAtNzAzZGZiY2ItOTU0ZS00ZjA1LWJjZGMtZDVhOWRkNTY4Y2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyYWYyZmRhNDk2MDZlYWYzNjY4ZWE2ZDQxNzBmNGNlZWQ5Y2QyMTI5MTk3YTE3YThkMDA1NDlkYWE1YjM3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfFiikXe54ozVyRcookSw-iuovLN8L_GAIPKCnMcKZ8) ![image](https://private-user-images.githubusercontent.com/17586327/344363100-5babed69-6b31-43eb-9c00-a4142a9c9e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzYyNzcsIm5iZiI6MTcxOTYzNTk3NywicGF0aCI6Ii8xNzU4NjMyNy8zNDQzNjMxMDAtNWJhYmVkNjktNmIzMS00M2ViLTljMDAtYTQxNDJhOWM5ZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNGE2NjMxMzRjYmM5ODE2M2ViMjQwYzYzOTBiZjkwNzg0M2Y3MjFhMzhjZjk5NTBkNzVhN2VjZjBiMmZiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lXKNNyV-uK-pySIGJOZ8rk6oQDfBtzML8bPStr6fu8U) ![image](https://private-user-images.githubusercontent.com/17586327/344363125-bbbc008c-36b4-4838-b6e4-9788c8437879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzYyNzcsIm5iZiI6MTcxOTYzNTk3NywicGF0aCI6Ii8xNzU4NjMyNy8zNDQzNjMxMjUtYmJiYzAwOGMtMzZiNC00ODM4LWI2ZTQtOTc4OGM4NDM3ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0N2Y2MjhjY2E1OWQ0NmZhYzhiOTNhYmEyYmU1ZDgxMjgwZTA5ODlhYzM2YjU3ZmJhMjYzNDc0ZjExMTk0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GHkMoSC2q7pJACOO3D7tK9AV691piV-zvc5pqFT4f-g) 你想实现的就是这样吧。 这是我自己用的重命名格式，改了一下。 `{{title}}{% if year %} ({{year}}){% endif %}/{{title}} S{{ "%02d" | format(season | int) }}.{% if season_year %}{{season_year}}{% endif %}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if episode %} - 第 {{episode}} 集{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}} `
> 
> 修改 /app/app/modules/filetransfer/**init**.py 增加1行代码就能实现。
> 
> ```
> 增加 L693: # 季年份根据season值获取
>             "season_year": mediainfo.season_years.get(int(meta.season_seq), None),
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/17586327/344364487-0cd65054-a11e-46e6-b2ab-69251881e7c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzYyNzcsIm5iZiI6MTcxOTYzNTk3NywicGF0aCI6Ii8xNzU4NjMyNy8zNDQzNjQ0ODctMGNkNjUwNTQtYTExZS00NmU2LWIyYWItNjkyNTE4ODFlN2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OGE4M2YzNTBjOGNhNDRkNmUwYTZkZmJiNTBhMjE4Y2RkOGYxMDAzMDEwNDMyODQwNTlhNDUzZjc1YTZmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSNSm5_2NCZdE447Hla-kgnrHOoXVKESOq0Govv933E)
> 
> ![image](https://private-user-images.githubusercontent.com/17586327/344364543-b101c228-5e9a-4b23-80bd-8a9ab0df5735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzYyNzcsIm5iZiI6MTcxOTYzNTk3NywicGF0aCI6Ii8xNzU4NjMyNy8zNDQzNjQ1NDMtYjEwMWMyMjgtNWU5YS00YjIzLTgwYmQtOGE5YWIwZGY1NzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjY0NWVjM2MxMGYyMGYxNDEzNjcyY2ViNTY5NjA1ZjQ4YmI1N2UwN2UwNWMxNmE5NjczNzZkNjQzMjkxNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYv-RNss9dckF5shm0Zi6pr-DLdhyvSJg1_Ku4CSgnw)

真的做出来了！！！66666666666，NT也可以这样改吗？负责文件重命名的字典文件是哪个呀？

**Comment by AisukaYuki** [comment]
> 真的做出来了！！！66666666666，NT也可以这样改吗？负责文件重命名的字典文件是哪个呀？

NT已经我很久没用了。

**Comment by Fzlwhyc** [comment]
> > 真的做出来了！！！66666666666，NT也可以这样改吗？负责文件重命名的字典文件是哪个呀？
> 
> NT已经我很久没用了。

那好吧！感谢大神！！！

**Comment by Fzlwhyc** [comment]
> > > 真的做出来了！！！66666666666，NT也可以这样改吗？负责文件重命名的字典文件是哪个呀？
> > 
> > 
> > NT已经我很久没用了。
> 
> 那好吧！感谢大神！！！后续这个有机会在更新版本中以更傻瓜化的方式实现吗？比如直接{season_year}就可以定义了，不用修改文件

**Comment by AisukaYuki** [comment]
```
nas-tools/app/filetransfer.py

get_format_dict

增加一个 

"season_year": media_year,
```

nt改这里应该可以吧。

另外我提了PR至于会不会有bug，能不能merge，要看作者。

**Comment by Fzlwhyc** [comment]
> ```
> nas-tools/app/filetransfer.py
> 
> get_format_dict
> 
> 增加一个 
> 
> "season_year": media.year,
> ```
> 
> nt改这里应该可以吧。
> 
> 另外我提了PR至于会不会有bug，能不能merge，要看作者。

嗯嗯！那太好了！修改文件适合已经停止更新的NT 期待MP上线新功能 那就可以NT MP双修了

**Comment by Fzlwhyc** [comment]
> **init**.py

大佬你还在吗？我在NT中修改了这个文件，然而测试的时候报错，完整的日志我截图下来了：
<img width="468" alt="报错" src="https://github.com/jxxghp/MoviePilot/assets/173179378/eac571de-9bd7-4775-897c-9880f774228f">，MetaVideoV2 对象没有 media_year 属性？

**Comment by Fzlwhyc** [comment]
> ```
> nas-tools/app/filetransfer.py
> 
> get_format_dict
> 
> 增加一个 
> 
> "season_year": media.media_year,
> ```
> 
> nt改这里应该可以吧。
> 
> 另外我提了PR至于会不会有bug，能不能merge，要看作者。

大佬你还在吗？我在NT中修改了这个文件，然而测试的时候报错，完整的日志我截图下来了：
<img width="468" alt="报错" src="https://github.com/jxxghp/MoviePilot/assets/173179378/332662ae-e031-4e09-a29a-e2cfc81529cb">
MetaVideoV2 对象没有 media_year 属性？

**Comment by AisukaYuki** [comment]
找其他fork了有在维护nt的人提issues吧，我也没法测试。这里是mp就不要讨论nt了。

**Comment by Fzlwhyc** [comment]
> 找其他fork了有在维护nt的人提issues吧，我也没法测试。这里是mp就不要讨论nt了。

好的 抱歉...
