### ISSUE TITLE
自定义【免登录时长】

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#2454]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

比如7天、14天免登录这样的。避免每天都要输入密码登录

**Comment by z3shan33** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/66009942/2d522d18-2bc2-4946-b904-11cff5c0c419)
默认8天免密

**Comment by Whichbfj28** [comment]
这就奇怪了。为什么我的iphone使用app模式后 基本天天要登录。

**Comment by z3shan33** [comment]
> 这就奇怪了。为什么我的iphone使用app模式后 基本天天要登录。

正常情况下，你只要不是在前端去手动重启系统，或者手机有定时清理浏览器缓存，是不需要再次登录的。

**Comment by InfinityPacer** [comment]
重启了MoviePilot就要重新登录
