### ISSUE TITLE
[Feature Request]: 关于手动搜索资源结果中的下载功能，不能和 订阅功能中已订阅服务里 设置的 保存路径 相互联动

### ISSUE THREAD

**Issue by MidnightShake** [jxxghp/MoviePilot#2459]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

关于手动搜索资源结果中的下载功能，不能和 订阅功能中已订阅服务里 设置的 保存路径 相互联动，结果就是有个小问题：手动点击了下载，就会下载到初始默认的分类（比如电影或电视剧分类）下载文件夹中，而没有参考 订阅设置里 指定的保存路径 来下载数据，（这个需要下载的媒体已经设置了订阅和指定保存路径，且平时能正常自动下载到指定路径）， 希望大佬们能优化一下这个小问题

**Comment by cng10001** [comment]
意思就是想【资源搜索】也能手动选择设置的下载目录路径呗

**Comment by MidnightShake** [comment]
> 意思就是想【资源搜索】也能手动选择设置的下载目录路径呗
也是这么个意思，那就更美好了

**Comment by zengmiaokun** [comment]
好像下载路径没有生效，实际下载目录是qBittorrent里面的默认路径

**Comment by zengmiaokun** [comment]
好像下载路径没有生效，实际下载目录是qBittorrent里面的默认路径

**Comment by MidnightShake** [comment]
就都是默认下载器设置的几个默认下载路径，经常手动搜索补全下载的时候，就多一个步骤，要手动去下载器迁移数据存储目录，或者手动下载种子手动下载
