### ISSUE TITLE
[错误报告]: 身份认证失败次数过多，封禁了我本地ip，导致无法登陆，提示401unauthorized

### ISSUE THREAD

**Issue by Only-silence** [jxxghp/MoviePilot#2462]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

因为修改了qbittorrent密码，导致认证失败次数过多，登录的时候没有任何反应，控制台显示 用户***登录成功，然后401unauthorized

![IMG_0207](https://github.com/jxxghp/MoviePilot/assets/28682238/d547ff56-c71d-482d-9f3a-00a2afc505b2)

**Comment by Only-silence** [comment]
![IMG_0208](https://github.com/jxxghp/MoviePilot/assets/28682238/bdc9fbd1-3a5b-4574-8c51-dc85566e8cbd)

**Comment by jxxghp** [comment]
qb锁了你来这里提问题有什么用？

**Comment by Only-silence** [comment]
是moviepilot一直登录不进去，我换了容器都IP才能进去

**Comment by kanmanli** [comment]
重启qb一下就好...大概
