### ISSUE TITLE
[Feature Request]:刷流插件是否可以一键转成正常留存任务

### ISSUE THREAD

**Issue by MICSAD117** [jxxghp/MoviePilot#2464]
### 当前程序版本

v1.9.9

### 运行环境

Docker

### 功能改进类型

插件

### 功能改进

在刷流界面有时可以看到自己想留存的资源，但是需要进qbit修改标签，并修改分类来更改保存位置，感觉有点儿繁琐，是否可以直接转换为正常下载任务来分类刮削保存。

**Comment by InfinityPacer** [comment]
请使用刷流种子整理插件
