### ISSUE TITLE
[Feature Request]: 电视剧订阅功能优化

### ISSUE THREAD

**Issue by sword0922** [jxxghp/MoviePilot#2466]
### 当前程序版本

最新版

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

比如我已经看了23集了，但想下下来观看，可以选择从某一集开始订阅吗

### 参考资料

若无，可否实现此功能

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/f154dc1a-78d4-46ac-8a0c-6184d26ce27c)
这个不是吗

**Comment by sword0922** [comment]
唐突了😓😓😓😓😥😥😥😥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月30日(周日) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: 电视剧订阅功能优化 (Issue #2466)




 
image.png (view on web)
 这个不是吗

**Comment by sword0922** [comment]
😓😓
