### ISSUE TITLE
[Feature Request]: 希望可以设定自定义分隔符，或修改默认分隔符为小数点

### ISSUE THREAD

**Issue by Fzlwhyc** [jxxghp/MoviePilot#2470]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

**参考这篇**https://github.com/jxxghp/MoviePilot/issues/1491

感觉比起默认分隔符“@”，小数点“.”作为默认自定义分隔符更大众化，但如果可以让用户直接在UI界面按自己的喜好自由修改分隔符就更好了（像以前的“自定义占位符”插件那样）。二月份的issues，不知道为什么没人理，个人认为MP最基础最重要的作用还是文件管理，再提一次。

### 参考资料
![image](https://github.com/jxxghp/MoviePilot/assets/173179378/ffa58077-4eed-470a-afbe-88723638c2ac)
![image](https://github.com/jxxghp/MoviePilot/assets/173179378/46f5b8ea-a494-44aa-a442-023ff5a0f33c)

**Comment by Fzlwhyc** [comment]
> 电影电视剧命名规则里面不是可以直接添加分割符号吗。除了占位符以外其他的字符都会保持原状啊，你写的是什么字符重命名后就会留下什么字符

不一样的~占位符可以获取多组，如DV HDR 60fps 10bits等。而在命名规则里是不能够在多组占位符【之间】添加分隔符的。就好比我有一个龙之家族的影片，同时具备高帧率，点亮杜比和HDR，在命名规则里面添加分隔符，最多能得到：龙之家族S01E01.DV@HDR@60fps.mkv

**Comment by cng10001** [comment]
这个插件大佬很久没出现了。
