### ISSUE TITLE
[错误报告]: 部分插件打开后只有保存和关闭按钮，无法配置

### ISSUE THREAD

**Issue by ZACKLZ** [jxxghp/MoviePilot#2475]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.9

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![微信截图_20240701113816](https://github.com/jxxghp/MoviePilot/assets/82872715/c59121a0-0990-4433-9dc2-1d57d06636a3)
![微信截图_20240701112308](https://github.com/jxxghp/MoviePilot/assets/82872715/fa0480f4-91d7-49b7-bf5d-812f63e0efd6)
![微信截图_20240701112259](https://github.com/jxxghp/MoviePilot/assets/82872715/a9dc43f4-1b9f-44c1-a834-85c133d2393e)
以上插件打开后都是这个效果，通过日志查看还在运行，但无法配置了

**Comment by cng10001** [comment]
版本更新都一周了，普遍问题肯定会有反馈的。肯定自己环境的问题啦
