### ISSUE TITLE
[错误报告]：acg.rip和mikan无法连通

### ISSUE THREAD

**Issue by SakuraYuki56** [jxxghp/MoviePilot#2477]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

站点管理里，同为bt站的动漫花园可以正常连通和使用，acg.rip和mikan无法连通，mikan已填写cookie和ua

### 发生问题时系统日志和配置文件

```bash
INFO	15:19:44,465	
site.py
缓存站点 ACG.RIP 图标成功
ERROR	15:19:44,458	
site.py
获取站点页面失败：http://acg.rip/
INFO	15:19:24,334	
transfer.py
没有获取到已完成的下载任务
INFO	15:19:24,007	
transfer.py
开始执行下载器文件转移 ...
INFO	15:19:14,397	
site.py
开始缓存站点 ACG.RIP 图标 ...
INFO	15:19:14,356	
command.py
处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x7fa65362a0>, <function SiteChain.clear_site_data at 0x7fa638d8a0>]
INFO	15:18:53,272	
site.py
缓存站点 MiKan 图标成功
ERROR	15:18:53,265	
site.py
获取站点页面失败：http://mikanani.me/
INFO	15:18:23,173	
site.py
开始缓存站点 MiKan 图标 ...
```

**Comment by zoffyultraman** [comment]
目前测试正常，可考虑为蜜柑开启仿真

**Comment by cng10001** [comment]
https://mikanani.me
 挂个代理？
