### ISSUE TITLE
[错误报告]: 插件内容在管理员账号正常显示，普通账号没有这个插件显示

### ISSUE THREAD

**Issue by zzj6666** [jxxghp/MoviePilot#2479]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.10

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

https://github.com/jxxghp/MoviePilot/assets/101039599/696566c0-761d-4056-b97a-5f74b63c1ce0
视频可以看到，在普通账户里并没有那个插件

**Comment by InfinityPacer** [comment]
目前设计上，普通用户应该没有权限使用插件相关功能。

**Comment by zzj6666** [comment]
> 目前已设计完毕，普通用户没有权限使用插件功能。

好吧，期待以后这种优化webui的插件能所有账户都能看到
