### ISSUE TITLE
[Feature Request]: 希望支持站点：CD File

### ISSUE THREAD

**Issue by Winnie0408** [jxxghp/MoviePilot#2481]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望能够添加站点`CD File`的支持，地址：`https://pt.cdfile.org/`，使用标准nexusphp框架；
已尝试联系站点管理组给账号到邮箱：`jxxghp@gmail.com`

### 参考资料

CD File - 专注于Blu-Ray、DVD、CD等高品质光盘镜像资源，致力于打造光盘档案室

**Comment by jxxghp** [comment]
@Winnie0408 收到邀请后就加
