### ISSUE TITLE
[错误报告]: 没有自动诊断插件

### ISSUE THREAD

**Issue by Laeoo** [jxxghp/MoviePilot#2485]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.910

### 运行环境

Windows

### 问题类型

插件问题

### 问题描述

过滤作者后只有两个插件
![image](https://github.com/jxxghp/MoviePilot/assets/41740567/21b233d1-e474-4468-9cc7-349626ccaa14)

**Comment by InfinityPacer** [comment]
请参考 [Wiki](https://wiki.movie-pilot.org/zh/plugin)，添加插件库 `https://github.com/InfinityPacer/MoviePilot-Plugins` 后重启

**Comment by Laeoo** [comment]
默认配置以有此库，在appWindow.env重新添加此库也没有

**Comment by InfinityPacer** [comment]
建议检查日志排查

**Comment by Laeoo** [comment]
启动日志无异常，重新安装后显示插件正常，导入备份的user.db和配置后就消失了。

**Comment by Laeoo** [comment]
是Windows安装版的原因，我清除了所有的配置文件重装后，发现插件界面和exe版本不一样
![image](https://github.com/jxxghp/MoviePilot/assets/41740567/c12c2754-8cfd-4548-9fb8-2276c8c9a18f)

**Comment by Laeoo** [comment]
这是exe版本
![image](https://github.com/jxxghp/MoviePilot/assets/41740567/90937203-3695-4e41-bfef-172e3cc66e8a)
