### ISSUE TITLE
[错误报告]: 硬链接转移失败，错误-1，已指定TMDBid，只是某几集且非随机出现，总是这几集。

### ISSUE THREAD

**Issue by Fzlwhyc** [jxxghp/MoviePilot#2486]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.10

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/173179378/dd5ae55c-8240-488f-98ec-798551189187)

一、《凡人修仙传》只有这些集出了问题，其他可以正常转：
凡人修仙传-(2)燕家堡之战，（共4集）
凡人修仙传-(4)再别天南，（共14集）
凡人修仙传-(6)星海飞驰序章，（共4集）

二、该动漫的目录结构形如：
凡人修仙传\凡人修仙传-(2)燕家堡之战\凡人修仙传 燕家堡之战 总集第18集 重制版 - WHfoimptor.mp4
凡人修仙传\凡人修仙传-(4)再别天南\凡人修仙传 再别天南 总集第47集  - WHfoimptor
凡人修仙传\凡人修仙传-(6)星海飞驰序章\凡人修仙传 星海飞驰序章 总集第73集  - WHfoimptor

三、原文件目录为： /media/影视资源库/Link/番剧/
       目标目录为： /media/影视资源库/Juiceroom/番剧/

四、用NT手动转测试正常。MP不行。

五、群晖7.2。

### 发生问题时系统日志和配置文件

```bash
INFO	03:36:29,449	
transfer.py
/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 转移完成
INFO	03:36:29,448	
transfer.py
/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 转移完成，共 1 个文件，失败 1 个，跳过 0 个
INFO	03:36:25,832	
command.py
处理事件：notice.message - []
INFO	03:36:25,830	
chain
发送消息：channel=None，title=凡人修仙传 (2020) S01 E47 入库失败！, text=原因：错误码：-1，userid=None
WARNING	03:36:21,331	
transfer.py
凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 入库失败：错误码：-1
ERROR	03:36:21,330	
filetransfer
文件 /media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 转移失败，错误码：-1
ERROR	03:36:21,329	
filetransfer
文件 /media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 link失败，错误码：-1
ERROR	03:36:21,328	
filetransfer
[Errno 18] Invalid cross-device link: '/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4' -> ' /media/影视资源库/Juiceroom/番剧/2020 凡人修仙传/凡人修仙传S01.2020/凡人修仙传S01E47.mp4.mp'
INFO	03:36:21,326	
filetransfer
正在转移文件：/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 到 /media/影视资源库/Juiceroom/番剧/2020 凡人修仙传/凡人修仙传S01.2020/凡人修仙传S01E47.mp4
INFO	03:36:21,321	
filetransfer
获取转移目标路径： /media/影视资源库/Juiceroom/番剧
INFO	03:36:21,301	
transfer.py
凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 识别为：电视剧 凡人修仙传 (2020)
INFO	03:36:21,291	
themoviedb
106449 TMDB识别结果：电视剧 凡人修仙传 (2020)
INFO	03:36:21,281	
transfer.py
手动转移：/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4 ...
INFO	03:36:21,273	
transfer.py
开始删除文件以及空目录： /media/影视资源库/Juiceroom/番剧/2020 凡人修仙传/凡人修仙传S01.2020/凡人修仙传S01E47.mp4 ...
```

**Comment by InfinityPacer** [comment]
```
[Errno 18] Invalid cross-device link: '/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4' -> ' /media/影视资源库/Juiceroom/番剧/2020  #凡人修仙传/凡人修仙传S01.2020/凡人修仙传S01E47.mp4.mp'
```

- 可尝试分别在宿主机以及容器中，通过 `ln` 命令硬链接该文件，并通过 `ls -l` 命令进行验证
- 如不是通过smb挂载并映射docker，也可通过`自动诊断`插件，测试对应目录的硬链接情况

**Comment by Fzlwhyc** [comment]
> ```
> [Errno 18] Invalid cross-device link: '/media/影视资源库/Link/番剧/凡人修仙传/凡人修仙传-(4)再别天南/凡人修仙传 再别天南 总集第47集 - WHfoimptor.mp4' -> ' /media/影视资源库/Juiceroom/番剧/2020  #凡人修仙传/凡人修仙传S01.2020/凡人修仙传S01E47.mp4.mp'
> ```
> 
> * 可尝试分别在宿主机以及容器中，通过 `ln` 命令硬链接该文件，并通过 `ls -l` 命令进行验证
> * 如不是通过smb挂载并映射docker，也可通过`自动诊断`插件，测试对应目录的硬链接情况

哦那就不是软件bug，是目录或文件的问题。那没事，昨晚我用nt已经链接好了。。
