### ISSUE TITLE
在主业头像点击重启，确认后提示重启失败。日志无显示

### ISSUE THREAD

**Issue by ZmmLAOBiao** [jxxghp/MoviePilot#2490]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

设备是威联通TS-464C，docker部署。
在主页头像点击重启，确认后提示重启时发生错误。查看日志内容无其他显示。
该端口并未被占用。防火墙关闭。网络改成host模式重新部署也出现同样问题。
![Snipaste_2024-07-02_17-19-06](https://github.com/jxxghp/MoviePilot/assets/131415589/ff976ad6-9da9-4782-908e-7a89641c211c)
![Snipaste_2024-07-02_17-18-26](https://github.com/jxxghp/MoviePilot/assets/131415589/9be2c4c5-95d3-4c84-ab13-ad32a685912f)
![Snipaste_2024-07-02_17-23-30](https://github.com/jxxghp/MoviePilot/assets/131415589/c187c0b0-a162-44df-b0df-92e9fb84cbc9)

**Comment by baozaodetudou** [comment]
@ZmmLAOBiao 看文档，docker要支持重启，得映射
