### ISSUE TITLE
[Feature Request]: 站点管理-同一站点作名称区分

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#2491]
### 当前程序版本

v1.9.10

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

有的站点比如馒头经常会出现连接性问题，所以不止添加了一个域名，但是不同域名名字统一都是馒头，新增同一站点的时候希望可以变成比如馒头1和馒头2……

这样在其他功能插件里比如签到插件选择的时候就好作区分了。

![image](https://github.com/jxxghp/MoviePilot/assets/115156545/795895af-a4d5-4bdc-b23b-cc430c617f83)
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/378e95a9-051f-4d3d-ba1a-db085cb86730)

**Comment by Putarku** [comment]
在cookiescloud的同步黑名单里面加上其他几个域名，只保留一个可以正常同步的域名即可

**Comment by cng10001** [comment]
> 在cookiescloud的同步黑名单里面加上其他几个域名，只保留一个可以正常同步的域名即可

cookiecloud的话一次性同步所有站点后，关闭cc同步反而会用得比较稳。接下来手动反而方便。
我江苏地区馒头和彩虹岛域名经常轮流抽风，添加多个域名联不通时只要选择性开启或停用域名就行了，不需要再在搜索、订阅、插件里再设置了。
