### ISSUE TITLE
电视剧订阅自动整理、手动整理，提示文件转移模块运行失败。

### ISSUE THREAD

**Issue by ZmmLAOBiao** [jxxghp/MoviePilot#2492]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.10-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

电视剧订阅自动整理、手动整理，提示文件转移模块运行失败。电影搜索下载自动整理正常。重启Docker后仍然显示失败
![Snipaste_2024-07-02_22-26-03](https://github.com/jxxghp/MoviePilot/assets/131415589/b4840e47-3bcb-4147-8ab1-75b8fc013a73)
![Snipaste_2024-07-02_22-31-00](https://github.com/jxxghp/MoviePilot/assets/131415589/56ace4b3-6181-41b2-a249-1bebcbbcc17e)
![Snipaste_2024-07-02_22-30-42](https://github.com/jxxghp/MoviePilot/assets/131415589/0b373708-7eb8-4874-a22f-229f57116456)
![Snipaste_2024-07-02_22-43-05](https://github.com/jxxghp/MoviePilot/assets/131415589/668ef366-32f0-4cef-8ea1-85b3dd4b0170)
![Snipaste_2024-07-02_22-27-51](https://github.com/jxxghp/MoviePilot/assets/131415589/1725c868-e130-48bc-a695-26dfcfa908e6)
![Snipaste_2024-07-02_22-31-33](https://github.com/jxxghp/MoviePilot/assets/131415589/848fb0a3-5527-46bf-8dd9-fee6d1173093)

**Comment by cng10001** [comment]
有没有动过重命名格式

**Comment by ZmmLAOBiao** [comment]
通过配置重新重新改为默认的重命名格式，正常了，谢谢

**Comment by Camellia0821** [comment]
我也是这问题  还是上来看下好  果然有同样的问题啊  之前不小心给删了重命名的设置
