### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 172908710** [jxxghp/MoviePilot#2496]
### 当前程序版本

我不是矿神套件最新版

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

订阅多季，不能搜索下载到站点的多季合集资源，只能搜索下载到站点的各个单季资源

### 参考资料

![微信截图_20240703233856](https://github.com/jxxghp/MoviePilot/assets/78930344/5137ab21-1754-41ec-80ef-b72515ee1596)

**Comment by cng10001** [comment]
已完结影视你直接手动搜索一下不就行了，我看是你图片上的都能搜索到的
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/2ce4f2ae-307d-4e6e-94c2-a2581d0dc385)
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/f56bd730-d42d-4ed6-a438-d8533d6424b4)
