### ISSUE TITLE
[Feature Request]: 通过“指定季数+指定集数"，订阅在tmdb上不存在的季

### ISSUE THREAD

**Issue by ershiyi21** [jxxghp/MoviePilot#2500]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

# **希望能够订阅不存在的季**

### 1. 部分动漫比如吞噬星空，其最新季度S04，在tmdb上S04剧集被归到S01中，不存在S04；但实际上pt站以S04命名发布，moviepilot无法指定添加S04订阅，添加订阅直接订阅成第一季
![wXp5e9TSat.png](https://i.imgur.com/qi38MXi.png)
时光代理人在tmdb上有三季，故可以指定订阅的季度
![](https://i.imgur.com/sZMCmzP.png)

#### a.通过自定义识别词的”**季数替换+集数偏移**”可以实现全部将pt站的非S01命名一一对应改为tmdb上的S01命名；
缺点：”季数替换+集数偏移”针对每一部动漫的规则可能都不一样，有时需要正则匹配，正则匹配规则不是每一个都会；而且部分动漫动辄一百多集，全部在S01降低emby观看体验，翻页都太长了；分季也反应了制作人、制作水平、制作时间的变化，不利于观看选择；
#### b.能够订阅不存在的季
在tmdb有该电视剧情况下，通过编辑订阅时“指定季+指定集数”**能够订阅不存在的季**
比如可以增加订阅tmdb存在的词条的，不存在的季度
#### c.**修改tmdb数据**
由于tmdb严格按照视频网站进行命名，部分电视剧由于争议过大【比如租借女友】，季度编辑锁定的，无法修改，修改本身就不符合平台规矩；而且即便能够修改，部分人也不一定都喜欢“不按照官方命名，反而分季度命名“的方式；

求同存异，希望能够改进一下moviepilot功能，在tmdb有该电视剧条目的情况下，通过“指定季+指定集数"，订阅不存在的季
指定不存在的季度，有利于分季度命名，个人感觉有必要。

### 参考资料

[ [功能改进]: 通过“指定季数+指定集数"，订阅在tmdb上不存在的季 #508 ](https://github.com/hsuyelin/nas-tools/issues/508)

**Comment by cng10001** [comment]
那届时有的剧，真出了tmdb标准的下一季，原先自定义的的季集又何去何从呢

**Comment by cofan24** [comment]
这个问题其实是现在TMDB把剧集关系给改了，在首页里所有季都放在第一季里，显示总集数，但是里面实际是分了季的。这就导致了mp在识别的时候，只认外面的总集数，不能识别到分季。我好多番都没法订阅，因为只能订阅第一季，整理的时候是可以正确识别第二季，第三季的。不知道这个问题怎么解决。
![Snipaste_2024-11-13_17-51-17](https://github.com/user-attachments/assets/311975e9-760e-4929-a5f4-daf057c1dcfb)
![Snipaste_2024-11-13_17-51-38](https://github.com/user-attachments/assets/3a0f0a66-802b-431d-8591-4f110d7bd4a0)

**Comment by ershiyi21** [comment]
> 这个问题其实是现在TMDB把剧集关系给改了，在首页里所有季都放在第一季里，显示总集数，但是里面实际是分了季的。这就导致了mp在识别的时候，只认外面的总集数，不能识别到分季。我好多番都没法订阅，因为只能订阅第一季，整理的时候是可以正确识别第二季，第三季的。不知道这个问题怎么解决。 ![Snipaste_2024-11-13_17-51-17](https://private-user-images.githubusercontent.com/119946352/385701024-311975e9-760e-4929-a5f4-daf057c1dcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDI0LTMxMTk3NWU5LTc2MGUtNDkyOS1hNWY0LWRhZjA1N2MxZGNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY2ZmNjM2MxNGExNzQ0YzcwN2YzZTA3YzVhZTg0MTMwMTZlMzc0OTY3NmU2ZjAzNTM1ZDA3MDBmMDhkZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xy_PkBGzZwvG8Oy0faZgXLp6PgzUWgIZo-ijU1l3BI0) ![Snipaste_2024-11-13_17-51-38](https://private-user-images.githubusercontent.com/119946352/385701039-3a0f0a66-802b-431d-8591-4f110d7bd4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDM5LTNhMGYwYTY2LTgwMmItNDMxZC04NTkxLTRmMTEwZDdiZDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjYwZTY2YzJjNWJiOTAzMDdmMjY1OWVjZGE5YTYwNTk5ODI4ZTg3Y2MyMTM2ZmI4NWY1ZTEwZTY0ZDE2MGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mx16sW3q9yS1YtzNW6l9e8EXsCrgQSjmBakCdH7ViZ8)

对于需要分季度的剧集，弃用mp的订阅下载，换用qbittorrent 的rss 关键词订阅下载，搭配mp的自动入库整理，参考
https://www.yetpage.com/archives/487#toc-head-9

**Comment by cofan24** [comment]
> > 这个问题其实是现在TMDB把剧集关系给改了，在首页里所有季都放在第一季里，显示总集数，但是里面实际是分了季的。这就导致了mp在识别的时候，只认外面的总集数，不能识别到分季。我好多番都没法订阅，因为只能订阅第一季，整理的时候是可以正确识别第二季，第三季的。不知道这个问题怎么解决。 ![Snipaste_2024-11-13_17-51-17](https://private-user-images.githubusercontent.com/119946352/385701024-311975e9-760e-4929-a5f4-daf057c1dcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDI0LTMxMTk3NWU5LTc2MGUtNDkyOS1hNWY0LWRhZjA1N2MxZGNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY2ZmNjM2MxNGExNzQ0YzcwN2YzZTA3YzVhZTg0MTMwMTZlMzc0OTY3NmU2ZjAzNTM1ZDA3MDBmMDhkZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xy_PkBGzZwvG8Oy0faZgXLp6PgzUWgIZo-ijU1l3BI0) ![Snipaste_2024-11-13_17-51-38](https://private-user-images.githubusercontent.com/119946352/385701039-3a0f0a66-802b-431d-8591-4f110d7bd4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDM5LTNhMGYwYTY2LTgwMmItNDMxZC04NTkxLTRmMTEwZDdiZDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjYwZTY2YzJjNWJiOTAzMDdmMjY1OWVjZGE5YTYwNTk5ODI4ZTg3Y2MyMTM2ZmI4NWY1ZTEwZTY0ZDE2MGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mx16sW3q9yS1YtzNW6l9e8EXsCrgQSjmBakCdH7ViZ8)
> 
> 目前官方似乎没有关注这个问题，个人的解决办法如下，比较笨，可以参考一下 对于需要分季度的剧集，弃用mp的订阅下载，换用qbittorrent 的rss 关键词订阅下载，搭配mp的自动入库整理，参考 https://www.yetpage.com/archives/487#toc-head-9

太有用了！好多正则表达式我都不太会，学习了。

**Comment by cofan24** [comment]
> > 这个问题其实是现在TMDB把剧集关系给改了，在首页里所有季都放在第一季里，显示总集数，但是里面实际是分了季的。这就导致了mp在识别的时候，只认外面的总集数，不能识别到分季。我好多番都没法订阅，因为只能订阅第一季，整理的时候是可以正确识别第二季，第三季的。不知道这个问题怎么解决。 ![Snipaste_2024-11-13_17-51-17](https://private-user-images.githubusercontent.com/119946352/385701024-311975e9-760e-4929-a5f4-daf057c1dcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDI0LTMxMTk3NWU5LTc2MGUtNDkyOS1hNWY0LWRhZjA1N2MxZGNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY2ZmNjM2MxNGExNzQ0YzcwN2YzZTA3YzVhZTg0MTMwMTZlMzc0OTY3NmU2ZjAzNTM1ZDA3MDBmMDhkZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xy_PkBGzZwvG8Oy0faZgXLp6PgzUWgIZo-ijU1l3BI0) ![Snipaste_2024-11-13_17-51-38](https://private-user-images.githubusercontent.com/119946352/385701039-3a0f0a66-802b-431d-8591-4f110d7bd4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDM5LTNhMGYwYTY2LTgwMmItNDMxZC04NTkxLTRmMTEwZDdiZDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjYwZTY2YzJjNWJiOTAzMDdmMjY1OWVjZGE5YTYwNTk5ODI4ZTg3Y2MyMTM2ZmI4NWY1ZTEwZTY0ZDE2MGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mx16sW3q9yS1YtzNW6l9e8EXsCrgQSjmBakCdH7ViZ8)
> 
> 目前官方似乎没有关注这个问题，个人的解决办法如下，比较笨，可以参考一下 对于需要分季度的剧集，弃用mp的订阅下载，换用qbittorrent 的rss 关键词订阅下载，搭配mp的自动入库整理，参考 https://www.yetpage.com/archives/487#toc-head-9

看了你的经验分享，利用种子标题和视频文件标题不一致的特点，在订阅的时候，把种子标题利用自定义识别次+集偏移，改成第一季，视频文件下载后，因为文件名略有不同，不符合自定义识别词规则，MP再按照原名字去识别，就实现了按第一季下载，按实际季整理的功能。真不容易。
(?<=\[ANi] 香格里拉・開拓異境.*?)(第二季).*?(([0-9]{2}).*?)(?=\[CHT]\[MP4]) => S01E\2 && S01E <> \[1080P] >> EP+25
种子名：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ 第二季 - 05 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4]
自定义识别词：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ S01E05 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] EP+25
文件名：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ 第二季 - 05 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4
其实名字就差一点
[
![Snipaste_2024-11-14_13-58-32](https://github.com/user-attachments/assets/f0e47379-76cd-44d3-9c4f-892e81f707ba)
](url)

**Comment by ershiyi21** [comment]
> > > 这个问题其实是现在TMDB把剧集关系给改了，在首页里所有季都放在第一季里，显示总集数，但是里面实际是分了季的。这就导致了mp在识别的时候，只认外面的总集数，不能识别到分季。我好多番都没法订阅，因为只能订阅第一季，整理的时候是可以正确识别第二季，第三季的。不知道这个问题怎么解决。 ![Snipaste_2024-11-13_17-51-17](https://private-user-images.githubusercontent.com/119946352/385701024-311975e9-760e-4929-a5f4-daf057c1dcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDI0LTMxMTk3NWU5LTc2MGUtNDkyOS1hNWY0LWRhZjA1N2MxZGNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGY2ZmNjM2MxNGExNzQ0YzcwN2YzZTA3YzVhZTg0MTMwMTZlMzc0OTY3NmU2ZjAzNTM1ZDA3MDBmMDhkZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xy_PkBGzZwvG8Oy0faZgXLp6PgzUWgIZo-ijU1l3BI0) ![Snipaste_2024-11-13_17-51-38](https://private-user-images.githubusercontent.com/119946352/385701039-3a0f0a66-802b-431d-8591-4f110d7bd4a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQxNTIsIm5iZiI6MTczMTQ5Mzg1MiwicGF0aCI6Ii8xMTk5NDYzNTIvMzg1NzAxMDM5LTNhMGYwYTY2LTgwMmItNDMxZC04NTkxLTRmMTEwZDdiZDRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QxMDMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjYwZTY2YzJjNWJiOTAzMDdmMjY1OWVjZGE5YTYwNTk5ODI4ZTg3Y2MyMTM2ZmI4NWY1ZTEwZTY0ZDE2MGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Mx16sW3q9yS1YtzNW6l9e8EXsCrgQSjmBakCdH7ViZ8)
> > 
> > 
> > 目前官方似乎没有关注这个问题，个人的解决办法如下，比较笨，可以参考一下 对于需要分季度的剧集，弃用mp的订阅下载，换用qbittorrent 的rss 关键词订阅下载，搭配mp的自动入库整理，参考 https://www.yetpage.com/archives/487#toc-head-9
> 
> 看了你的经验分享，利用种子标题和视频文件标题不一致的特点，在订阅的时候，把种子标题利用自定义识别次+集偏移，改成第一季，视频文件下载后，因为文件名略有不同，不符合自定义识别词规则，MP再按照原名字去识别，就实现了按第一季下载，按实际季整理的功能。真不容易。 (?<=[ANi] 香格里拉・開拓異境._?)(第二季)._?(([0-9]{2}).*?)(?=[CHT][MP4]) => S01E\2 && S01E <> [1080P] >> EP+25 种子名：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ 第二季 - 05 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] 自定义识别词：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ S01E05 [1080P][Baha][WEB-DL][AAC AVC][CHT][MP4] EP+25 文件名：[ANi] 香格里拉・開拓異境～糞作獵手挑戰神作～ 第二季 - 05 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4 其实名字就差一点 [ ![Snipaste_2024-11-14_13-58-32](https://private-user-images.githubusercontent.com/119946352/386063454-f0e47379-76cd-44d3-9c4f-892e81f707ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjYzNDMsIm5iZiI6MTczMTU2NjA0MywicGF0aCI6Ii8xMTk5NDYzNTIvMzg2MDYzNDU0LWYwZTQ3Mzc5LTc2Y2QtNDRkMy05YzRmLTg5MmU4MWY3MDdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNjM0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGRhY2NlY2I0MzVjNTZkY2ZkZGRjMDUxNDIzYjg5ODcyYzNjN2MxNzFiY2Q5ZjRjYjA1MDY0YWRmNzQzN2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.63-VCSL96x3teXr7AoBs9FFZ39rU6S7GApSzF2FAfnc) ](url)

不错的思路
利用种子标题与内部视频文件的命名差异，标题用于订阅，视频文件名称用于整理入库，挺好。
但订阅时注意，可能存在以下情况，针对标题的识别词不能适用于多剧集的种子【S03EXX-XX这种】，多剧集种子mp会解析与识别内部视频文件名称，最后选择下载订阅需要的剧集，但明显内部视频为非第一季、因此不能识别为第一季，所以订阅下载失败。
