### ISSUE TITLE
订阅优先级中希望加入按电影/剧集文件大小制定优先级策略的功能

### ISSUE THREAD

**Issue by Jerry-Geng** [jxxghp/MoviePilot#2505]
### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

需求：订阅的过程中，我的磁盘空间有限，又希望保存尽可能高质量的视频，所以希望电影资源在2-5GB范围内优选尽可能大的视频，最大不超过5G，最小不低于2G，如果存在多个符合条件的资源，则筛选最大的。
可能的解决方案：在优先级选项中添加文件大小选项，可以选择一个**文件大小范围**，并且还可以指定**优选最大文件**还是**优选最小文件**。

**Comment by cddjr** [comment]
一般是优先4k+dv（如果你设备支持的话），其次4k+hdr，再其次4k这个优先级顺序来。
对资源大小敏感的，可以限定分辨率1080

以上是基于现有的订阅优先级方案实现，我觉得已经足够了。
