### ISSUE TITLE
 [Feature Request]: 不同路径 支持 不同整理方式

### ISSUE THREAD

**Issue by uploadrclone** [jxxghp/MoviePilot#2510]
### 当前程序版本

1.9.10-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否在 整理模式按照指定路径设置
比如
路径为/download/hr 整理模式设置为 复制
路径为/download/tmp 整理模式设置为 软链接

**Comment by rootvd** [comment]
如截图

**Comment by rootvd** [comment]
抱歉没有写标题请关闭，重新开了一个

**Comment by cng10001** [comment]
这个用原来的**目录监控**插件可以吧

**Comment by uploadrclone** [comment]
但目录监控设置移动的话 文件刮削移动完成后 种子并不会停止做种
