### ISSUE TITLE
[错误报告]: 正在下载和历史纪录中都看不到数据，但是下载器中能正常下载，下载完后能正常入库

### ISSUE THREAD

**Issue by zht826** [jxxghp/MoviePilot#2511]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.10-1 最新

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

正在下载和历史纪录中都看不到数据，但是下载器中能正常下载，下载完后能正常入库。

### 发生问题时系统日志和配置文件

```bash
[32mINFO[0m:     172.17.0.1:0 - "[1mGET /api/v1/history/transfer?page=1&count=50 HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     172.17.0.1:0 - "[1mGET /api/v1/download/ HTTP/1.1[0m" [32m200 OK[0m
```

**Comment by red3** [comment]
+1

**Comment by zht826** [comment]
> +1

@red3 找到原因了吗

**Comment by fyu0h** [comment]
同样遇到这个问题，请问解决了吗
