### ISSUE TITLE
韩剧《BIG》无法正确搜索到站点资源

### ISSUE THREAD

**Issue by aaseud** [jxxghp/MoviePilot#2517]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.10

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

利用标题搜索韩剧《big》（孔刘主演）时，无法搜索到资源，而切换为imdb链接后可以搜索到，但搜索不全，馒头站内的无法被搜索到（有人保种且馒头站内其他影视可以正常搜索下载），其他资源目前无此问题

**Comment by AisukaYuki** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/abb7521a-2b04-4ef8-9d01-92d39def52b9)
![image](https://github.com/jxxghp/MoviePilot/assets/17586327/d1c786bb-e96c-4a31-9208-57fcbf9359c2)
直接标题搜索的结果。

**Comment by aaseud** [comment]
您好，我尝试了以下几种搜索：

AisukaYuki ***@***.***> 于2024年7月7日周日 09:33写道：

**Comment by aaseud** [comment]
您好，不好意思刚刚邮件未编辑完发送过去了，以下为完整内容（另之前发送了一版带附件截图的邮件，提示过大无法发送，于是我把图片去掉了，如有需要我会再找其他方法发送）
针对该影视（BIG，TMDB：43083，IMDB：tt2441802），我利用现有的几种搜索方式进行了穷举：
*一、选择“搜索相关的电影电视剧”*
1.搜索BIG，会出现30部影视，但不包括这部韩剧；
2.搜索真爱上错身，没有数据；
3.搜索爱情上错身，没有数据。
*二、选择“搜索相关的演职人员”，搜索裴秀智，*
1.在其参演作品中直接点击《BIG》作品左下角的搜索，会搜索出三个资源，但均不是此韩剧；
2.在其参演作品中点进《BIG》详情页，再点击搜索资源，选择“标题”，与1结果相同，为三个无关资源；
3.在《BIG》详情页，点击搜索资源，选择“IMDB链接”，会正确搜索出两个此韩剧资源，但无“馒头”站点资源；
*三、选择“搜索相关的站点资源”*
1.搜索BIG，出现大量资源，在筛选站点为“馒头”、制作组为“Ao”的情况下是，无任何资源，仅筛选站点为“馒头”的情况下，同样无此韩剧；
2.搜索真爱上错身，出现四个资源，均为正确资源，且两部为馒头站点资源，但相较第二步第3条的搜索结果，缺少了某站点的资源（该资源未标记该中文名），多出了另一个站点的资源（二.3的另一资源与其归为了同一资源，被显示在“更多来源”里）；
3.搜索爱情上错身，出现三个资源，均为正确资源，同步骤2相比，缺少了馒头站点135.88G版本的资源；
4.根据您截图的启发，搜索了“爱 上错身”，同步骤2，为四个正确资源。

*综上所述：*
1.如果要搜索该影视，目前利用moviepilot没有办法能够搜索到我所拥有的站点中的所有版本（已知的已有5个版本，目前最多仅能搜索到4个）；
2.同时，此影视资源仅能通过“搜索相关的演职人员”和“搜索相关的站点资源”搜索到，无法通过最便捷的“搜索相关的电影电视剧”搜索到，也只能通过中文译名搜索到。

*关于您所提到的日志及打开链接等操作，我尝试了上述步骤二.1中日志的某站链接，确实能够搜索到正确资源，但由于包含“BIG”此名字的资源太多，所以排名非常靠后，估计就是这个原因导致未能在moviepilot搜索结果中显示，同时基于此，我认为其他操作应该也是由于类似相似标题数量太多这个问题导致未能找到正确资源。*

最后，十分感谢作者开发出了这么好用的工具，这个问题也只是我个人所遇到的一个小问题，实际上并不怎么影响使用体验，但还是希望作者能在有条件的情况下进行进一步的改进和优化，谢谢！

AisukaYuki ***@***.***> 于2024年7月7日周日 09:33写道：

**Comment by Putarku** [comment]
检索了一下tmdb，发现这部剧没有简体中文的译名，所以你用“真爱上错身”“爱情上错身”搜不到很正常。另外MP在检索资源的时候也会通过剧名原名和译名来检索，但恰好这部剧没有中文这块的译名，所以搜索的时候就没有使用“真爱上错身”“爱情上错身”了。
因为mp是依赖于tmdb的数据，如果你发现检索不到或是有问题，一般来说都是tmdb的数据上可能存在错漏。
我刚刚已经在tmdb上补充了译名，在缓存刷新以后可能会解决你的问题

**Comment by Putarku** [comment]
对于剧名就较为简单的比如这次的“big”，其检索效果很依赖于站点补充的副标题信息
