### ISSUE TITLE
使用jellyseerr提交电视剧请求时，发送给moviepilot无法完成订阅

### ISSUE THREAD

**Issue by cuijun8200** [jxxghp/MoviePilot#252]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.6

### 问题类型

其他问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/28519505/79b2fbb7-db89-4cfc-8195-38df08bb5c7c)
![image](https://github.com/jxxghp/MoviePilot/assets/28519505/f53fff23-e8cc-4381-a0a6-5b5bff515115)

使用jellyseerr提交电视剧请求时，发送给moviepilot无法完成订阅，电影订阅正常，系统日志识别不了的有一点反应，能识别的无任何无任何反应

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-08-24 12:57:12,442 - tmdbapi.py - 232248 查询结果：冰雪尖刀连
【INFO】2023-08-24 12:57:12,443 - __init__.py - Winter And Lion 识别结果：电视剧 冰雪尖刀连 (2023) 232248
【INFO】2023-08-24 12:57:26,892 - __init__.py - 开始获取TVDB信息: 376751 ...
```

**Comment by jxxghp** [comment]
原因是TVDB连不上，最新版本已支持使用内置代理。

**Comment by AdoShan** [comment]
请问一下现在咋连接MoviePilot呢
