### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by WINDYQWQ** [jxxghp/MoviePilot#2523]
### 当前程序版本

1.9.10-1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

建议改进改进下目录功能，让设置的下载文件夹和媒体文件夹一一对应，下载来的文件固定整理到设置好的地方，我这边按顺序设置了电影、电视剧、动漫、综艺，结果有的综艺放电影里，有的电视剧也被丢到电影里，然后动漫全放电视剧里面了。
![QQ截图20240707084244](https://github.com/jxxghp/MoviePilot/assets/92260406/f00abedf-0a6f-446d-b974-58d6eb8b190d)
![QQ截图20240707085039](https://github.com/jxxghp/MoviePilot/assets/92260406/6f332fe3-2da4-4857-b682-689f33f11832)

**Comment by Putarku** [comment]
第一你想要综艺，你这里就不应该是电视剧-全部，而是电视剧-综艺。
第二，这个目录匹配是按顺序来的，你应该把最小的分类比如动漫和综艺放到最前面。如果把电视剧放在前面，那么匹配到这条就不会继续往后走了，直观的影响就是动漫会丢到电视剧里面。
现在的目录设置其实已经能够满足你的需求，只是你没配置好，可以再自己参考下wiki
