### ISSUE TITLE
[错误报告]: 	11:13:16,193	 download.py 未找到下载目录：电影 心花路放 (2014)

### ISSUE THREAD

**Issue by aass132ssaa** [jxxghp/MoviePilot#2524]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

qb下载目录和MP下载目录一致，qb账号密码也对，下载目录    映射目录  都是一致的   
![MP](https://github.com/jxxghp/MoviePilot/assets/156285259/92f16120-4e14-45f4-833d-0498fc65daf0)
![qb](https://github.com/jxxghp/MoviePilot/assets/156285259/8f261d7c-c185-4800-a3d1-063c9780442e)
![下载目录](https://github.com/jxxghp/MoviePilot/assets/156285259/150ac5f5-b9df-4adb-b5ab-a2554a8e2cc5)

### 发生问题时系统日志和配置文件

```bash
2024/7/7 11:13:42  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/system/env HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:42  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/system/setting/TorrentsPriority HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:42  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/system/env HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:42  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/system/setting/TorrentsPriority HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:40  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/user/ HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:40  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/user/current HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:22  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjEwMTMwMjUsInN1YiI6IjEiLCJ1c2VybmFtZSI6ImFkbWluIiwic3VwZXJfdXNlciI6dHJ1ZSwibGV2ZWwiOjJ9.y9xCabah4CxrNxJ283uK9kgSs7z54dm7-CqevG7i6q0 HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:20  [32mINFO[0m:     192.168.3.4:0 - "[1mGET /api/v1/site/statistic/zmpt.cc HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:16  [32mINFO[0m:     192.168.3.4:0 - "[1mPOST /api/v1/download/add HTTP/1.1[0m" [32m200 OK[0m
2024/7/7 11:13:16  [31mERROR:[0m   download.py - 未找到下载目录：电影 心花路放 (2014)
2024/7/7 11:13:14  [32mINFO:[0m    themoviedb - Breakup Buddies TMDB识别结果：电影 心花路放 (2014) 284298
```

**Comment by ljr78** [comment]
我也出现同样的问题，不知道怎么解决。

**Comment by Putarku** [comment]
不要用全部-全部，最起码要把电影和电视剧分开，这些在其他不止一个issue中有提到了

**Comment by aass132ssaa** [comment]
不好意思，我的 &nbsp; tg群问了一个上午 &nbsp;没人理我 &nbsp; &nbsp;后面 &nbsp;到了中午 &nbsp; 有人教我尝试了 &nbsp; &nbsp;会了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Putarku ***@***.***&gt;
发送时间: 2024年7月7日 19:42
收件人: jxxghp/MoviePilot ***@***.***&gt;
抄送: aass132ssaa ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jxxghp/MoviePilot] [错误报告]:  11:13:16,193  download.py 未找到下载目录：电影 心花路放 (2014) (Issue #2524)





 
不要用全部-全部，最起码要把电影和电视剧分开，这些在其他不止一个issue中有提到了
