### ISSUE TITLE
[错误报告]: 订阅失败: 识别媒体信息时未提供元数据名称

### ISSUE THREAD

**Issue by whitebrise** [jxxghp/MoviePilot#2525]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅动漫时无法订阅，显示未识别到媒体信息。这部动漫一开始tmdb上是显示2季s01(11集)+s02(13集)的，这几天更新成一季s01(24集)了，可能其他平台上(tvdb，douban)还显示2季分组，现在就无法订阅了。
![Snipaste_2024-07-07_13-38-13](https://github.com/jxxghp/MoviePilot/assets/55422869/2b343119-7b65-4b5b-872f-52f337b24da2)
在这个页面直接右上叫点击搜索能直接搜索到站点资源
![Snipaste_2024-07-07_13-34-12](https://github.com/jxxghp/MoviePilot/assets/55422869/94accd41-5d65-4e9c-9787-aa786f275414)

### 发生问题时系统日志和配置文件

```bash
WARNING	13:44:46,223	
subscribe.py
未识别到媒体信息，标题：【我推的孩子】，tmdbid：203737，doubanid：None
WARNING	13:44:46,222	
themoviedb
识别媒体信息时未提供元数据名称
INFO	13:44:46,214	
subscribe.py
开始添加订阅，标题：【我推的孩子】 ...
```

**Comment by AisukaYuki** [comment]
自定义识别字加上
【我推的孩子】 => 我推的孩子
重新订阅

**Comment by whitebrise** [comment]
> 自定义识别字加上 【我推的孩子】 => 我推的孩子 重新订阅 不知道怎么回事，原来有【】也能识别，新版现在不识别。

可以了，看来确实是【】的问题

**Comment by KrystalC** [comment]
感谢，确实可以

**Comment by alkalixin** [comment]
感谢

**Comment by alkalixin** [comment]
> 自定义识别字加上 【我推的孩子】 => 我推的孩子 重新订阅 不知道怎么回事，原来有【】也能识别，新版现在不识别。

感谢
