### ISSUE TITLE
[错误报告]: 电视剧类型分类错误并且无法手动修改

### ISSUE THREAD

**Issue by j506130598** [jxxghp/MoviePilot#2535]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

电视剧入库自动分类的类型错误，并且无法手动修改
例如：戴洛奇小镇会变成未分类类型（应该是欧美剧）、寻味贵辣被分入国产剧（应该是纪录片）

**Comment by cng10001** [comment]
因为黛洛奇小镇是澳大利亚的电视剧？默认没算在欧美剧里
你把澳大利亚的代号AU放在欧美剧分类里应该就可以。
