### ISSUE TITLE
[Feature Request]: MoviePilot 实现独立下载盘和媒体库盘分离及自动整理问题

### ISSUE THREAD

**Issue by diny0310** [jxxghp/MoviePilot#2538]
### 当前程序版本

1.9.11

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

我现在有一个需求，已经基于当前版本的MP 和群晖的两个套件实现了，但是总觉得不够优雅，而且这套方法局限于群晖了。

#### 需求背景
mp 在 docker 部署的时候，受 docker 的限制，下载目录和媒体库目录必须在同盘同父目录下，否则无法实现硬链接。
这就造成一个问题，即用户只能用一块硬盘来承载下载和自动整理这两个动作。根据硬盘的性质，也即要么用 SSD，要么用机械硬盘。

我想很多人都了解这么一点，机械硬盘在下载PT 时，面临如下几个问题：
- 碎片化写入，这将会导致机械硬盘出现很多碎片文件。
- 读写同时，加大了机械硬盘的磁头工作负载，进而硬盘发热，均影响机械硬盘寿命。
- 即使保种期的读，也使得机械硬盘不能获得休息。长时间的保种，使得机械硬盘无法休眠，磁头一直工作，影响硬盘寿命，加大损坏几率。

而 SSD 恰恰没有这个问题，读几乎对SSD 无影响，读写同时也没问题，写影响 SSD 寿命，但绝大多数正规品牌的 SSD 的写寿命其实都足够长。

这就使得很多人，根据磁盘特性，采取用 SSD 做下载盘，而机械硬盘做仓库盘的方案，也即 SSD 下载完毕后，将整个文件复制/移动到机械盘存储，这样既避免碎片化写入问题，后期机械硬盘也基本只面临偶尔的读的问题，大大降低了机械硬盘的负载。

但是当前版本的 mp，无法实现这种 SSD 和机械硬盘的自动化协作问题。

如果只用 SSD，现在 SSD 容量普遍不大，且成本比较高，限制了 PT 下载和保种的空间。
如果只用机械盘，则又面临机械盘寿命消耗的问题，且一些人使用的企业盘不停工作的话，发热是个大问题，还有噪音问题。

#### 需求描述
希望 mp 可以实现：
- 配置单独的下载目录A，但同盘同父母录下不必配置媒体库目录
- 配置媒体库自动整理目录，包括下载文件同步目录B和整理后的媒体库目录（硬链接目录）
- 实现自动的目录 A->目录 B 的文件同步，可以设置同步条件（指定哪些子目录），或者直接设置多条同步，路径配置具体目录（比如子目录）。目录 A 和目录 B 可以同盘（不同路径），也可以不同盘（这次的核心需求）。

以上目录均可以映射到 docker 容器里。

具体策略是：
自动监控下载目录 A，当发现配置的指定同步目录有新文件时，自动同步到目录 B，同步方法可以是 copy（有保种需求的情况下），move 等，总之目的是让目录 B 有 A里的源文件。

自动监控下载目录 B，当发现有新文件时，启动 mp 内置的自动整理功能，整理相关文件到媒体库目录。这部分就是现有功能。

上面这个策略可以兼容当前的同盘同父目录方案，也可以考虑单独一套设置。

#### 我当下的方案
我当前的方案是：
- SSD->仓库盘，是用群晖的 cloud sync+webdav 实现本机两块内置磁盘的实时自动同步（单向同步，仅复制新文件，源文件仍要留 SSD 保种用，后面根据需要单独处理保种文件问题，可以独立操作）
- USB 移动硬盘->仓库盘，由于群晖 cloud sync 不支持USB 移动硬盘作为同步的源盘，所以只能在计划任务里使用 rsync定时执行指令，实现定时同步

同时，关闭了 mp 的自动整理功能（牺牲了一个很好的功能），开启了目录监控插件，用插件来实现仓库盘下载文件目录的自动整理。

目前从效果来看，堪堪可用，但不优雅，且群晖的同步还有点小问题，正在找原因。

综上，假如 mp 能够在内部实现这个功能，实现全自动化操作，显然要比我的方案优雅很多。考虑到下载盘和仓库盘分离这事其实挺普遍的，所以觉得还是提出一个需求来，看看作者是否可以考虑。

非常感谢。

**Comment by InfinityPacer** [comment]
qb支持下载临时目录中转

**Comment by diny0310** [comment]
> qb支持下载临时目录中转

是的，但是 qb 是移动，如果有保种需求，那就意味着保种的文件移动到仓库盘了，导致仓库盘仍然在长时间读的工作状态。
我希望仓库盘不用于保种，保种用 SSD，因为读对 SSD 基本没影响，不利用很可惜。

**Comment by Putarku** [comment]
qb的临时下载目录就已经可以解决碎片文件这个问题了。用SSD保种成本太高不太现实，绝大多数人还是使用机械盘来保种。

**Comment by InfinityPacer** [comment]
那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
- HDD ，转移使用Copy
- SSD，转移使用Link

**Comment by diny0310** [comment]
> qb的临时下载目录就已经可以解决碎片文件这个问题了。用SSD保种成本太高不太现实，绝大多数人还是使用机械盘来保种。

考虑到 SSD 的价格长期来看是下降趋势（排除最近一年的涨价），SSD 的使用还是越来越普遍，即便是群晖也支持用 SSD 做缓存来解决写的速度问题。我在一些硬盘社区也看到很多人都是这样 SSD 和 HDD 配合使用的，作用上来讲，SSD 主要还是“缓存”文件的用处，长期保存文件大家还是保存到机械硬盘。

保种成本方面，比如我用一块2T 的 SSD，其实足够用了，因为可能会定时清理一些超长时间保种的文件，当然，如果有巨量保种需求的，是要考虑成本问题。

主要还是考虑长时间大量保种对机械硬盘寿命影响问题。

**Comment by diny0310** [comment]
> 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> 
> * HDD ，转移使用Copy
> * SSD，转移使用Link

如果使用 copy 的话，那就是占了双倍空间，不太合理啊。
我目前保种用 SSD，媒体库在 HDD

**Comment by InfinityPacer** [comment]
> > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > 
> > * HDD ，转移使用Copy
> > * SSD，转移使用Link
> 
> 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD

难道你目前保种SSD，媒体库HDD，不是双份空间

**Comment by diny0310** [comment]
> > > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > > 
> > > * HDD ，转移使用Copy
> > > * SSD，转移使用Link
> > 
> > 
> > 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD
> 
> 难道你目前保种SSD，媒体库HDD，不是双份空间

这个还是有些区别，SSD 保种我是可以随时清理的，不影响媒体库。HDD 纯做存储和整理。

**Comment by InfinityPacer** [comment]
> > > > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > > > 
> > > > * HDD ，转移使用Copy
> > > > * SSD，转移使用Link
> > > 
> > > 
> > > 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD
> > 
> > 
> > 难道你目前保种SSD，媒体库HDD，不是双份空间
> 
> 这个还是有些区别，SSD 保种我是可以随时清理的，不影响媒体库。HDD 纯做存储和整理。

没有理解你的需求，现在你保种SSD，媒体库HDD，SSD也是随时清理，带来了什么问题。

**Comment by diny0310** [comment]
> > > > > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > > > > 
> > > > > * HDD ，转移使用Copy
> > > > > * SSD，转移使用Link
> > > > 
> > > > 
> > > > 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD
> > > 
> > > 
> > > 难道你目前保种SSD，媒体库HDD，不是双份空间
> > 
> > 
> > 这个还是有些区别，SSD 保种我是可以随时清理的，不影响媒体库。HDD 纯做存储和整理。
> 
> 没有理解你的需求，现在你保种SSD，媒体库HDD，SSD也是随时清理，带来了什么问题。

带来的问题就是这种 SSD->HDD的文件 copy同步，是我使用群晖的套件实现的，对 mp 追求的全自动观影的目标来讲，中间一个关键环节，被迫让用户用第三方手段实现，且不一定稳定靠谱。所以，如果 mp 能将全过程实现，自然最优雅最好。

**Comment by InfinityPacer** [comment]
> > > > > > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > > > > > 
> > > > > > * HDD ，转移使用Copy
> > > > > > * SSD，转移使用Link
> > > > > 
> > > > > 
> > > > > 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD
> > > > 
> > > > 
> > > > 难道你目前保种SSD，媒体库HDD，不是双份空间
> > > 
> > > 
> > > 这个还是有些区别，SSD 保种我是可以随时清理的，不影响媒体库。HDD 纯做存储和整理。
> > 
> > 
> > 没有理解你的需求，现在你保种SSD，媒体库HDD，SSD也是随时清理，带来了什么问题。
> 
> 带来的问题就是这种 SSD->HDD的文件 copy同步，是我使用群晖的套件实现的，对 mp 追求的全自动观影的目标来讲，中间一个关键环节，被迫让用户用第三方手段实现，且不一定稳定靠谱。所以，如果 mp 能将全过程实现，自然最优雅最好。

现在整理方式选择Copy，不是可以吗

**Comment by diny0310** [comment]
> > > > > > > 那你的SSD保种期间，你的媒体文件存放的媒体库，是在HDD，还是SSD
> > > > > > > 
> > > > > > > * HDD ，转移使用Copy
> > > > > > > * SSD，转移使用Link
> > > > > > 
> > > > > > 
> > > > > > 如果使用 copy 的话，那就是占了双倍空间，不太合理啊。 我目前保种用 SSD，媒体库在 HDD
> > > > > 
> > > > > 
> > > > > 难道你目前保种SSD，媒体库HDD，不是双份空间
> > > > 
> > > > 
> > > > 这个还是有些区别，SSD 保种我是可以随时清理的，不影响媒体库。HDD 纯做存储和整理。
> > > 
> > > 
> > > 没有理解你的需求，现在你保种SSD，媒体库HDD，SSD也是随时清理，带来了什么问题。
> > 
> > 
> > 带来的问题就是这种 SSD->HDD的文件 copy同步，是我使用群晖的套件实现的，对 mp 追求的全自动观影的目标来讲，中间一个关键环节，被迫让用户用第三方手段实现，且不一定稳定靠谱。所以，如果 mp 能将全过程实现，自然最优雅最好。
> 
> 现在整理方式选择Copy，不是可以吗

现在的 copy，只能在同盘同父目录进行，但我现在是跨盘 copy 需求，现在的 mp 无法实现。

**Comment by InfinityPacer** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/160988576/6457c579-105c-4f58-8412-a1fb221618bf)
已测试，未发现问题。

**Comment by diny0310** [comment]
> ![image](https://private-user-images.githubusercontent.com/160988576/346814662-6457c579-105c-4f58-8412-a1fb221618bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDMzNzIsIm5iZiI6MTcyMDUwMzA3MiwicGF0aCI6Ii8xNjA5ODg1NzYvMzQ2ODE0NjYyLTY0NTdjNTc5LTEwNWMtNGY1OC04NDEyLWExZmIyMjE2MThiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNTMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjU5NWZhMzMxOGNmNmVmYTc4MzAxM2NkMzAwOTg5ODgxYTdlNTE0MGY0OGZjN2IxMDA5Yjg5NjhmYmQ5YWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KBF89FhN5L_gCzbPmwi6EHJeWj-qMM2qcp8mBEr9G_U) 已测试，未发现问题。

我按照你的图片，尝试了一下，mp 确实是能跨盘拷贝，那实在太好了，之前我一直认为无论是硬链接、软连接、copy、move 均需要在同盘同父目录下，才有了这个需求。

如此我设置一下，继续观察看看是否都正常。

**Comment by diny0310** [comment]
wiki 里着重说了硬链接需要在同盘同父目录，我理解错了，因为其它方式，copy/move 等皆需要同盘同父目录。

感谢 @InfinityPacer 的多次回复，最终我确认 copy 是可以跨盘的，可以满足我的需求。

问题解决，关闭此 issue。

**Comment by totobo** [comment]
copy、软链接、move都是可以跨盘的。
只有硬链接不行，硬链接为什么不行，简单了解下它的实现原理就知道了
