### ISSUE TITLE
[错误报告]: 同步识别词后，会出现[电影名] => None  的问题，导致订阅搜索经常失败

### ISSUE THREAD

**Issue by ZACKLZ** [jxxghp/MoviePilot#2542]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.11

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![4d53a4bb3d7828587487b76fb74108c](https://github.com/jxxghp/MoviePilot/assets/82872715/1fe4fa8a-a52b-406c-b28a-9bea6234903c)
上周发现订阅的电视剧一直不更新，查了日志才发现问题，就卸载了同步识别词的插件，然而mp容器本身也会定期同步识别词····
是否可以提供关闭同步识别词的功能或者修复一下该问题

（截图中猩球崛起电影的识别词我在自定义识别词词表中查了并没有）

**Comment by Putarku** [comment]
你把错误的识别词删掉就行了，公开的那两个识别词列表有人经常捣乱

**Comment by ZACKLZ** [comment]
> mp本身并没有同步识别词的功能。 你把错误的识别词删掉就行了，或者全删掉，公开的那两个识别词列表有人经常捣乱

可能是上次刚卸载同步识别词插件，服务中还可以看到同步识别词的服务，现在的确看不到了，感谢感谢
