### ISSUE TITLE
[Feature Request]: 请求除媒体入库通知外的其他通知只发给管理员即可。

### ISSUE THREAD

**Issue by NikoYomi** [jxxghp/MoviePilot#2543]
### 当前程序版本

v1.9.11

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

设想一下，爸妈拿着手机问你这是什么？！
屏幕赫然是MP微信端发来的通知；
你於 2024-07-10 16:03 下載完成的種子：(不可描述词汇)【日本】【无码】(ID: xxxx) H&R 已達標，恭喜！

除此之外的其他通知例如站点流量、站点消息等管理员知道就好了，其他人不懂也不关心，会很打扰其他用户。
他们只需要关心今天入库了哪些电影电视。

**Comment by jxxghp** [comment]
@NikoYomi 开关别打开呀，每类消息发送的渠道是你自己设置的吧，设置了不生效？

**Comment by NikoYomi** [comment]
> @NikoYomi 开关别打开呀，每类消息发送的渠道是你自己设置的吧，设置了不生效？

我只使用了企业微信这一个通知渠道，我的家人也只使用这个交互渠道。
但我作为管理员又想通过这个渠道来接受所有消息，但对于其他人来说只想接受媒体下载和入库的消息。😭

**Comment by thsrite** [comment]
@NikoYomi 微信消息转发插件，转发到不同的企微应用不就解决问题

**Comment by NikoYomi** [comment]
> @NikoYomi 微信消息转发插件，转发到不同的企微应用不就解决问题

天才！

**Comment by NikoYomi** [comment]
> @NikoYomi 微信消息转发插件，转发到不同的企微应用不就解决问题

这个插件只可以设置站点签到这些消息，其他的插件配置了无效。也可能是我设置的问题，暂时没找到可行的教程。

**Comment by thsrite** [comment]
@NikoYomi 插件可以实现把mp的消息分发到不同微信应用。
可以一个应用只接收入库消息，企业微信后台设置该应用权限给需要看到的人，其他微信应用设置权限只给管理员可见。
其他自行研究。

**Comment by NikoYomi** [comment]
> @NikoYomi 插件可以实现把mp的消息分发到不同微信应用。 可以一个应用只接收入库消息，企业微信后台设置该应用权限给需要看到的人，其他微信应用设置权限只给管理员可见。 其他自行研究。

入库消息也不显示，只显示签到和站点流量信息。
