### ISSUE TITLE
[错误报告]: 获取微信access_token失败，错误信息：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by bainw2023** [jxxghp/MoviePilot#2565]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.11

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在微信交互中，moviepilot能正常接收到微信传入的信息，但是无法传出到微信，报错误“获取微信access_token失败，错误信息：Expecting value: line 1 column 1 (char 0)”。
![Uploading screenshot-1720944512925.png…]()

**Comment by bainw2023** [comment]
![screenshot-1720944512925](https://github.com/user-attachments/assets/336df6bd-35b6-42bb-b21d-832d32b1d153)

**Comment by zousoooo** [comment]
https://github.com/jxxghp/MoviePilot/issues/2315 
参考一下是否配置了/var/run/docker.sock

**Comment by zero617** [comment]
> ![screenshot-1720944512925](https://github.com/user-attachments/assets/336df6bd-35b6-42bb-b21d-832d32b1d153)

这是怎么解决的 我也遇到了这个问题

**Comment by lvfu** [comment]
> > ![screenshot-1720944512925](https://github.com/user-attachments/assets/336df6bd-35b6-42bb-b21d-832d32b1d153)
> 
> 这是怎么解决的 我也遇到了这个问题

检查下nginx那块   能收到消息企业微信这块应该就没问题了。我目前也是报这个错，查了下原因是服务端nginx80端口被别的项目占用了，删掉那个项目重启下mp就好了
