### ISSUE TITLE
[错误报告]: 重命名提示词匹配错误

### ISSUE THREAD

**Issue by Akimio521** [jxxghp/MoviePilot#2567]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.11

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用正则表达式匹配关键词然后指定tmdbid，表达式匹配成功，但是搜索出的结果是错误的，甚至id都不同
![image](https://github.com/user-attachments/assets/aa85c98c-8c56-49c9-9085-ac1fc90b2517)

**Comment by HankunYu** [comment]
我用一样的配置在我这边测试可行
大概率需要清一下缓存？
![CleanShot 2024-07-16 at 11 24 16@2x](https://github.com/user-attachments/assets/05e125c3-a0dd-473c-9ebf-2acab4b59a0c)

**Comment by Akimio521** [comment]
可能是吧，现在我也恢复正常了，应该是mp的tmdb缓存引起的，现在好像是直接根据文件名直接命中缓存？

**Comment by LevineWoo** [comment]
我的也是这样，得每一次他识别后就清缓存，不然的话只要是在词条里加的自定义识别，后面所有识别的其他剧就总是使用第一个缓存的剧名。

**Comment by Akimio521** [comment]
已在 #3030 解决
