### ISSUE TITLE
docker安装的MoviePilot，使用nginx proxy manager 反向代理，当会话过期时，页面始终空白，无法打开，控制台有报错。

### ISSUE THREAD

**Issue by zhoufla** [jxxghp/MoviePilot#2574]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.12

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

docker安装的MoviePilot，使用nginx proxy manager 反向代理，当会话过期时，页面始终空白，无法打开，控制台有报错。
当清除全部浏览器缓存或者开启无痕模式时又可以跳转到登录界面，但是当后续会话过期时，此问题再次发生。

![image](https://github.com/user-attachments/assets/818d0242-275f-42f3-bac0-f1f572618972)

### 发生问题时系统日志和配置文件
代理设置：
![image](https://github.com/user-attachments/assets/12a2a55e-3d3e-48a0-964e-69287de766ac)

![image](https://github.com/user-attachments/assets/7ed6e631-7b60-4b67-8ab9-c4a4036999fe)

```
location / {
    proxy_pass http://192.168.10.135:13000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

_No response_

**Comment by zhoufla** [comment]
PS：之前使用nastool无此问题。

**Comment by rheatin** [comment]
> 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。

是的，总是这个样子，用起来真的很恶心

**Comment by jxxghp** [comment]
> > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> 
> 是的，总是这个样子，用起来真的很恶心

恶心你就别用啊？！用nginx和群晖内置代理都没问题，用npm就有问题，你不动脑子想想是不是你代理没配对或者npm有什么特殊？跑这来恶心？

**Comment by rheatin** [comment]
> > > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> > 
> > 
> > 是的，总是这个样子，用起来真的很恶心
> 
> 恶心你就别用啊？！用nginx和群晖内置代理都没问题，用npm就有问题，你不动脑子想想是不是你代理没配对或者npm有什么特殊？跑这来恶心？

为什么这么暴跳如雷呢，我只是说这件事很恶心，大家和我遇到了一样的问题，我用的也是nginx，我甚至都没有提issue，觉得可以忍受，为什么你却如此恶意满满？

**Comment by jxxghp** [comment]
> > > > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> > > 
> > > 
> > > 是的，总是这个样子，用起来真的很恶心
> > 
> > 
> > 恶心你就别用啊？！用nginx和群晖内置代理都没问题，用npm就有问题，你不动脑子想想是不是你代理没配对或者npm有什么特殊？跑这来恶心？
> 
> 为什么这么暴跳如雷呢，我只是说这件事很恶心，大家和我遇到了一样的问题，我用的也是nginx，我甚至都没有提issue，觉得可以忍受，为什么你却如此恶意满满？

你是什么巨婴，你跟别人说恶心，我还得跟你说好话？

**Comment by minichar** [comment]
> > > > > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> > > > 
> > > > 
> > > > 是的，总是这个样子，用起来真的很恶心
> > > 
> > > 
> > > 恶心你就别用啊？！用nginx和群晖内置代理都没问题，用npm就有问题，你不动脑子想想是不是你代理没配对或者npm有什么特殊？跑这来恶心？
> > 
> > 
> > 为什么这么暴跳如雷呢，我只是说这件事很恶心，大家和我遇到了一样的问题，我用的也是nginx，我甚至都没有提issue，觉得可以忍受，为什么你却如此恶意满满？
> 
> 你是什么巨婴，你跟别人说恶心，我还得跟你说好话？

你这个情绪不太稳定

**Comment by jxxghp** [comment]
> > > > > > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 是的，总是这个样子，用起来真的很恶心
> 
> > > > 
> 
> > > > 
> 
> > > > 恶心你就别用啊？！用nginx和群晖内置代理都没问题，用npm就有问题，你不动脑子想想是不是你代理没配对或者npm有什么特殊？跑这来恶心？
> 
> > > 
> 
> > > 
> 
> > > 为什么这么暴跳如雷呢，我只是说这件事很恶心，大家和我遇到了一样的问题，我用的也是nginx，我甚至都没有提issue，觉得可以忍受，为什么你却如此恶意满满？
> 
> > 
> 
> > 你是什么巨婴，你跟别人说恶心，我还得跟你说好话？
> 
> 
> 
> 你这个情绪不太稳定

还换马甲。。。

**Comment by zhoufla** [comment]
作者大大 别生气 我是确实没找到解决办法才提的issue，群晖的反代是可以的，我切换到群晖去用好了

**Comment by jxxghp** [comment]
@zhoufla 没有生你的气，提问题正常。但说 “总是这个样子，用起来真的很恶心” 这种话的人，我没有这么大的气度，容忍不了。

**Comment by log-time** [comment]
@jxxghp 尝试把npm的缓存关掉？
我的mp+npm目前使用似乎是正常的，只是偶尔前端升级后需要删除页面缓存。

**Comment by goxofy** [comment]
> > 之前使用nastool无此问题，转为MoviePilot以来，该问题一直存在。
> 
> 是的，总是这个样子，用起来真的很恶心

可以不用的

**Comment by InfinityPacer** [comment]
- advanced 相关配置，供参考，timeout 请自行评估，不了解的话建议移除
```
gzip on;
gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
gzip_proxied any;
gzip_min_length 256;
gzip_vary on;
gzip_comp_level 6;
proxy_connect_timeout 60s;
proxy_read_timeout 60s;
proxy_send_timeout 60s;
```

![image](https://github.com/user-attachments/assets/23f4c1a2-5219-48e9-8d21-bbf6aeed05f4)
![image](https://github.com/user-attachments/assets/abef775d-9503-433f-b205-07e4b8f752cf)

**Comment by zhoufla** [comment]
> * advanced 相关配置，供参考，timeout 请自行评估，不了解的话建议移除
> 
> ```
> gzip on;
> gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
> gzip_proxied any;
> gzip_min_length 256;
> gzip_vary on;
> gzip_comp_level 6;
> proxy_connect_timeout 60s;
> proxy_read_timeout 60s;
> proxy_send_timeout 60s;
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/160988576/349592276-23f4c1a2-5219-48e9-8d21-bbf6aeed05f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTQ2OTksIm5iZiI6MTcyMTMxNDM5OSwicGF0aCI6Ii8xNjA5ODg1NzYvMzQ5NTkyMjc2LTIzZjRjMWEyLTUyMTktNDhlOS04ZDIxLWJiZjZhZWVkMDVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxNDUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGNiOTYzNDczYTM2YTA3NGE5MzRkNDM2YWQ1ZDNhZmI3MWIyZDVkYjA3N2RhYTk4YjcwNjRjMmFhMzljNmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BQj-Nj_cZbgMAYP1yvQtKR5ahTU43Vuf8R-s1uZyLW0) ![image](https://private-user-images.githubusercontent.com/160988576/349592342-abef775d-9503-433f-b205-07e4b8f752cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTQ2OTksIm5iZiI6MTcyMTMxNDM5OSwicGF0aCI6Ii8xNjA5ODg1NzYvMzQ5NTkyMzQyLWFiZWY3NzVkLTk1MDMtNDMzZi1iMjA1LTA3ZTRiOGY3NTJjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxNDUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDIyODU2YzBhYTRiNzA3NGZhNzUzOTIyNzk0NjBjNTcxNTc3MmYwYmM2NjZmYmYyZjczZjk0N2IzZmE3N2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gS73Bx3iET5omj51RFFYh-IXoIHL01l9paLO3mTGmKY)

似乎关掉Cache Assets就可以了。才试了两天，再多观察几天。

**Comment by xyqjay817** [comment]
哎，我也是不行。看到暴躁老哥， 不敢说话。

**Comment by cddjr** [comment]
搞那么复杂，一个lucky就可以傻瓜式、一键式就搞定反代了。

**Comment by zhoufla** [comment]
> 哎，我也是不行。看到暴躁老哥， 不敢说话。

![Image](https://github.com/user-attachments/assets/fe2d77b1-5a59-4b04-a853-589913ff8728)
关掉缓存即可，npm设置的问题
