### ISSUE TITLE
[错误报告]: 搜索中结果中使用了豆瓣的数据源，但订阅和搜索资源时如果没有tmdb id，就会导致订阅失败或搜索资源失败

### ISSUE THREAD

**Issue by Jason0816** [jxxghp/MoviePilot#2576]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.11

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

搜索动漫时，搜索结果中会出现，应该是从豆瓣获取数据源，但是搜索资源或者订阅的时候，会显示tmdb id不存在，因为TMDB还没有对应数据
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/1159d8ea-1977-48a7-8500-bfee6e27265c">
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/b8338aa9-fd45-48a0-a9ac-9f578507cb5f">
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/ba737f99-e787-489e-bd71-df17a8cdb99e">
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/c808936c-cf1f-4407-ad0b-1bd0ac233126">

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/69921a77-daed-4f53-8d52-db3f653d86b9">

**Comment by AisukaYuki** [comment]
![image](https://github.com/user-attachments/assets/192434ef-6961-455a-a82d-7b66079f9bc1)

**Comment by Travel2Here** [comment]
问题同遭遇，解决方式如楼上。
