### ISSUE TITLE
[Feature Request]: 服务定时作业统一管理

### ISSUE THREAD

**Issue by xiongzwen** [jxxghp/MoviePilot#2579]
### 当前程序版本

1.9.1

### 运行环境

Windows

### 功能改进类型

主程序

### 功能改进

![image](https://github.com/user-attachments/assets/dbd34551-193c-404b-a350-6cf002dbad03)

- 这个服务栏，是服务管理，可以单独操作立即执行一次调度任务，要是可以加两列分别控制任务调度周期和是否调度就好了。统一服务管理的收口，此处开关的优先级最高
- 比如cookiecloud定时同步和壁纸刷新任务等我并不想启用它们，但是他默认就会发生调度，增加资源消耗

**Comment by Travel2Here** [comment]
+1

**Comment by heiyumiao** [comment]
+1
