### ISSUE TITLE
[错误报告]: 朱同在三年级丢失了超能力在机器人发送全名没有反应

### ISSUE THREAD

**Issue by CleverMod** [jxxghp/MoviePilot#2580]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.10-1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

朱同在三年级丢失了超能力这个影片发送全名没有反应 发送部分名称没有问题
![微信图片_20240717161223](https://github.com/user-attachments/assets/bf531aba-8fc1-425c-854b-b9d9cea1b4fa)

### 发生问题时系统日志和配置文件

```bash
INFO	16:13:12,458	
command.py
处理事件：user.message - []
INFO	16:13:11,902	
message.py
收到用户消息内容，用户：buding，内容：朱同在三年级丢失了超能力
INFO	16:13:11,900	
wechat
收到微信消息：userid=buding, text=朱同在三年级丢失了超能力
INFO	16:13:08,982	
command.py
处理事件：user.message - []
INFO	16:13:08,976	
message.py
收到用户消息内容，用户：buding，内容：朱同在三年级丢失了超能力
INFO	16:13:08,975	
wechat
收到微信消息：userid=buding, text=朱同在三年级丢失了超能力
INFO	16:13:06,427	
command.py
处理事件：user.message - []
INFO	16:13:06,420	
message.py
收到用户消息内容，用户：buding，内容：朱同在三年级丢失了超能力
INFO	16:13:06,419	
wechat
收到微信消息：userid=buding, text=朱同在三年级丢失了超能力
```

**Comment by CleverMod** [comment]
更新成最新版v1.9.12也是一样

**Comment by jxxghp** [comment]
少输几个字，字太多会转去chatpgt
