### ISSUE TITLE
【感谢作者的奉献】但是可以不要更新那么频繁吗。

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#2582]
### 当前程序版本

1.9.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

1、感谢作者给我们提供的软件 让我们更方便。
2、作者可以不要更新那么频繁吗。
3、更新频繁不是问题。问题是更新那么快，**每次更新修复问题。然后又会导致出现新问题。**
4、作者可以提供预览版渠道。
5、老实说，新版本功能让我心动的时候。我都都不太敢更新了。担心又是一大堆bug。

**Comment by xyswordzoro** [comment]
@Whichbfj28 召唤神龙，你许愿成功了

**Comment by baozaodetudou** [comment]
@Whichbfj28 你真牛，哈哈哈哈

**Comment by 17376022661** [comment]
牛逼

**Comment by jxxghp** [comment]
@Whichbfj28 好的，我记下了

**Comment by cng10001** [comment]
@Whichbfj28 hahaha 你可真是个好人啊~
