### ISSUE TITLE
[Feature Request]: 规则优先级复制

### ISSUE THREAD

**Issue by fanhuahrg** [jxxghp/MoviePilot#2583]
### 当前程序版本

1.9.12

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

在做优先级的时候每个都设置过去不容易找到想要的，希望添加订阅和洗版优先级复制的功能。

**Comment by zoffyultraman** [comment]
订阅右上角三个点 分享，然后洗版右上角三个点，导入
