### ISSUE TITLE
[错误报告]: 同步转移更新1.0.6后大部分失败，偶尔成功。

### ISSUE THREAD

**Issue by HamBosco** [jxxghp/MoviePilot#261]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.6

### 问题类型

主程序运行问题

### 问题描述
之前下载了4个资源，睡醒后发现只有1个入库成功。因为没有及时发现，没有保存log。在closed issues里有看到别人发类似问题，但是没看到解决方吗。请问如何解决？

### 发生问题时系统日志和配置文件

```bash
```

**Comment by jxxghp** [comment]
@HamBosco 解决了，拉最新镜像
