### ISSUE TITLE
[错误报告]: 目录监控无法识别媒体时未产生历史记录无法手动转移

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#262]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.6

### 问题类型

插件问题

### 问题描述

目录监控无法识别媒体时未产生历史记录无法手动转移。

未启用下载监控转移，不清楚是否会发生相同问题

日志信息如下
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/bf966cb6-308f-487b-915f-5a405a1ced5c)

历史记录如下
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/9ca9eae9-8b9a-4046-a1af-6331c9c23e76)

目前是使用的nastool的媒体整理进行手动入库的

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-08-25 09:04:24,646 - __init__.py - 正在识别 变形金刚5 ...
【INFO】2023-08-25 09:04:25,134 - tmdbapi.py - 正在查询TMDB电影：335988 ...
【INFO】2023-08-25 09:04:25,717 - tmdbapi.py - 335988 查询结果：变形金刚5：最后的骑士
【INFO】2023-08-25 09:04:27,473 - tmdbapi.py - 正在查询TMDB电影：335988 ...
【INFO】2023-08-25 09:04:27,476 - tmdbapi.py - 335988 查询结果：变形金刚5：最后的骑士
【INFO】2023-08-25 09:04:27,477 - __init__.py - 变形金刚5 未匹配到媒体信息
【WARNING】2023-08-25 09:04:27,477 - __init__.py - 未识别到媒体信息，标题：变形金刚5
【INFO】2023-08-25 09:04:27,478 - __init__.py - 发送消息：channel=None，title=变形金刚5.2017.1080P.国英.中英@FST.mp4 未识别到媒体信息，无法入库！, text=None，userid=None
【INFO】2023-08-25 09:04:27,478 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7fbfb488bc40>, <function WebHook.send at 0x7fbfb48193a0>]
```

**Comment by jxxghp** [comment]
#285
