### ISSUE TITLE
[错误报告]:极空间nas中docker容器创建后，别名有两个是空的

### ISSUE THREAD

**Issue by libashanxi** [jxxghp/MoviePilot#263]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.6

### 问题类型

Docker或运行环境问题

### 问题描述

容器创建好后，会在别名这里有两个是空的，如果想要在编辑容器，就必须要删除掉。等创建好后会自动又生成这两个别名。
对于docker的别名不太懂，因此在这里报一下。
![image](https://github.com/jxxghp/MoviePilot/assets/65264574/f49b58f6-7f39-435b-89b9-a0208df2e6e7)

**Comment by Smart-zsw** [comment]
这个删了，或者随便填个0就可以
