### ISSUE TITLE
[Feature Request]: 建议在连接界面增加测试按钮或者保存时自动测试一下

### ISSUE THREAD

**Issue by chinafuxi** [jxxghp/MoviePilot#2678]
### 当前程序版本

v1.9.15

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![image](https://github.com/user-attachments/assets/22364865-7afe-4b0b-939e-c88c5194df2d)
刚才测试，删除emby的apikey也可以保存成功，建议增加一个测试按钮，或者点保存时自动测试一下连通性，如果调用识别给一个提示

**Comment by Akimio521** [comment]
保存成功和通过测试是两个概念，需要测试是否通过，可以在“系统健康检查”中查看
