### ISSUE TITLE
[Feature Request]: 目录监控下载目录为媒体库目录子目录问题

### ISSUE THREAD

**Issue by echowiz** [jxxghp/MoviePilot#268]
### 当前程序版本

1.0.7

### 功能改进

当前目录结构为
Media
  |——downloads
  |——电影
  |——电视剧
![image](https://github.com/jxxghp/MoviePilot/assets/42895319/d28fc8c0-2933-49bf-aba1-8d1c74cb3d44)

在设置目录监控时，提示downloads目录为媒体库子目录无法监控
这种目录结构下不会造成数据紊乱
只需要媒体目录不是下载目录的子目录就可以
希望可以调整一下判断逻辑

**Comment by werran2** [comment]
我从NT转过来的，媒体目录就是下载目录的子目录，怎么办呢，现在无法使用目录监控插件。
