### ISSUE TITLE
[Feature Request]:订阅时能否给剧集加一个仅下载全集

### ISSUE THREAD

**Issue by 522654518** [jxxghp/MoviePilot#2681]
### 当前程序版本

v1.9

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

[Feature Request]:订阅时能否给剧集加一个仅下载全集，这个功能很重要，又简单，能否考虑加一下呢

**Comment by 522654518** [comment]
一订阅剧集，它自己乱下，一个剧集竟然好几个小组的作品，太难受了。

**Comment by Putarku** [comment]
你可以在“包含”选定想要下的小组。或者是打开“洗板”，需要注意的是打开这个，就只会下载全集的种子，分集的种子不会触发下载

**Comment by cddjr** [comment]
这种的话，可以通过关键词来过滤，比如标题或副标题必须包含“全集”二字
