### ISSUE TITLE
[错误报告]: 微信下载电影或者电视剧无法自动分类到指定目录

### ISSUE THREAD

**Issue by chenmdg** [jxxghp/MoviePilot#2682]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.15

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在企业微信应用下载指定种子后，无法自动分类。看下载的种子没有添加分类标签，导致需要手动移动位置。

**Comment by chenmdg** [comment]
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/bc8a9f1c-2971-4afb-8b17-8312a89f9e7b">

**Comment by chenmdg** [comment]
在网页上下载种子都是可以正常分类的，但企业微信上面的不行。
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/c93115e8-3b6b-4ddd-a488-2376b2e46c09">

**Comment by zoffyultraman** [comment]
贴下日志

**Comment by chenmdg** [comment]
> 贴下日志

问题已经在新版本解决了

**Comment by zoffyultraman** [comment]
> > 贴下日志
> 
> 问题已经在新版本解决了

那就关闭吧
