### ISSUE TITLE
[错误报告]: 已经配置IYUU_SIGN，提示用户认证失败

### ISSUE THREAD

**Issue by blackappleD** [jxxghp/MoviePilot#2685]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.15

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

已经配置了AUTH_SITE和IYUU_TOKEN, 提示认证失败，随后重试提示 站点认证参数未设置，无法进行用户认证！；
![image](https://github.com/user-attachments/assets/0f40f245-2a3c-4b4e-8d32-0b95cad793e4)

### 发生问题时系统日志和配置文件

```bash
日志：
【INFO】2024-09-05 11:42:30,415 - chain - 发送消息：channel=None，title=MoviePilot用户认证, text=用户认证失败，站点相关功能将无法使用！，userid=None
【INFO】2024-09-05 11:42:30,422 - command.py - 处理事件：notice.message - []
【INFO】2024-09-05 11:42:33,477 - doh.py - 已解析 [api.tmdb.org] 为 [18.238.192.8]
【INFO】2024-09-05 11:43:29,909 - site.py - 开始同步CookieCloud站点 ...
【ERROR】2024-09-05 11:43:29,911 - site.py - CookieCloud同步失败：未从本地CookieCloud服务加载到cookie数据，请检查服务器设置、用户KEY及加密密码是否正确
【INFO】2024-09-05 11:47:29,906 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-05 11:47:29,912 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-05 11:47:30,336 - mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
【INFO】2024-09-05 11:47:30,363 - mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：0
【INFO】2024-09-05 11:51:57,636 - login.py - 用户 admin 登录成功！
【INFO】2024-09-05 11:52:29,917 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-05 11:52:29,918 - scheduler.py - 用户未认证，正在尝试重新认证...
【ERROR】2024-09-05 11:52:29,927 - scheduler.py - 用户认证失败：站点认证参数未设置，无法进行用户认证！，共失败 1 次
【INFO】2024-09-05 11:52:29,933 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-05 11:53:54,211 - doh.py - 已解析 [api.github.com] 为 [140.82.116.5]
【INFO】2024-09-05 11:53:55,233 - doh.py - 已解析 [api.github.com] 为 [140.82.116.5] (缓存)
【INFO】2024-09-05 11:55:40,769 - main.py - 站点资源版本：1.4.7
【INFO】2024-09-05 11:55:40,773 - main.py - 认证资源版本：1.3.2
【ERROR】2024-09-05 11:55:40,777 - main.py - 站点认证参数未设置，无法进行用户认证！
```

**Comment by blackappleD** [comment]
排查了一下，app.env配置未生效，修改系统环境变量可以生效；ps：我是通过windows安装版进行安装的

**Comment by blackappleD** [comment]
> 看wiki说明，各认证站点对应参数配置，只能在环境变量里设置 env配置文件不起作用，我也折腾了半天

没有把，wiki上是说 环境变量、env配置文件、WEB界面三种方式都能生效，只是有优先级关系

**Comment by snowwalk** [comment]
![image](https://github.com/user-attachments/assets/a57fc4a2-6f2a-48e3-866f-a52abe23cba8)
文档更新估计有些滞后，但根据实际的情况看，确实 用户认证的参数要放到环境变量了的。
对于 PROXY_HOST 这个参数，好像放在配置文件里也可，我就是放在配置文件里的。

**Comment by blackappleD** [comment]
> ![image](https://private-user-images.githubusercontent.com/15061082/365555816-a57fc4a2-6f2a-48e3-866f-a52abe23cba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjgxNDMsIm5iZiI6MTcyNTg2Nzg0MywicGF0aCI6Ii8xNTA2MTA4Mi8zNjU1NTU4MTYtYTU3ZmM0YTItNmYyYS00OGUzLTg2NmYtYTUyYWJlMjNjYmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA3NDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTJkYmNmY2EyMDVmNzg2NzAwYjhmMjIwODNlNDAwYWE3N2RhMDM2ZDZlODFkZjcwOTMzYTQ5YmY0NjgxYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dAFIbt3ATx8hEu6q57N-HMEV9OQaCDjhAmKe73QyPBE)文档更新估计有些滞后，但根据实际的情况看，确实 用户认证的参数要放到环境变量了的。 对于 PROXY_HOST 这个参数，好像放在配置文件里也可，我就是放在配置文件里的。

还真是

**Comment by LM4217** [comment]
在Windows端，个人测试需要将认证参数填写到appWindows.env文件才能正常认证
