### ISSUE TITLE
[错误报告]: 启动时提示错误：Nomodule named'app.helper.sites

### ISSUE THREAD

**Issue by jeffrey0326** [jxxghp/MoviePilot#2688]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.15

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/user-attachments/assets/97eb556a-0b59-4116-98da-3bf3ffbe7568)
在重启时提示上述错误

**Comment by jeffrey0326** [comment]
找到原因了，更新时https://github.com/jxxghp/MoviePilot-Resources/archive/refs/heads/main.zip下载失败，希望能在启动时自动重试下载解压

**Comment by zhangbaiquan** [comment]
确实挺难受的，构建好的镜像仍要依赖网络资源，重启就可能再也起不来了

**Comment by myownsword** [comment]
大佬我也遇到这个问题了 现在重启一直不这个错 解决方案是什么啊
