### ISSUE TITLE
[错误报告]: 始终无法开始自动下载，日志没有任何和订阅或者下载相关的内容

### ISSUE THREAD

**Issue by blackappleD** [jxxghp/MoviePilot#2723]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

已经配置了站点和订阅，始终没有开始下载：
![image](https://github.com/user-attachments/assets/99b7620f-6ec2-4a87-9565-1fe578ef6fca)
![image](https://github.com/user-attachments/assets/43c7c370-000e-401d-bce7-5de09649b63b)
![image](https://github.com/user-attachments/assets/543d70df-c8c3-4b7a-abd3-abf36471b088)

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-09-16 12:51:12,460 - login.py - 用户 admin 登录成功！
【INFO】2024-09-16 12:52:11,465 - site.py - 开始同步CookieCloud站点 ...
【WARNING】2024-09-16 12:52:12,336 - site.py - 站点 YemaPT 登录失败，没有该站点账号或Cookie已失效，无法添加站点
【INFO】2024-09-16 12:52:12,981 - site.py - 站点【冰淇淋】连通性正常，不同步CookieCloud数据
【WARNING】2024-09-16 12:52:14,272 - site.py - 站点 麒麟 登录失败，没有该站点账号或Cookie已失效，无法添加站点
【WARNING】2024-09-16 12:52:17,365 - site.py - 站点 艾薇 登录失败，没有该站点账号或Cookie已失效，无法添加站点
【INFO】2024-09-16 12:52:19,151 - site.py - 站点【Nyaa】连通性正常，不同步CookieCloud数据
【INFO】2024-09-16 12:52:20,814 - site.py - 新增站点 ACG.RIP ...
【INFO】2024-09-16 12:52:20,935 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x000001D5B18E0CC0>, <function SiteChain.clear_site_data at 0x000001D5B17BA340>]
【INFO】2024-09-16 12:52:20,949 - site.py - 开始缓存站点 ACG.RIP 图标 ...
【INFO】2024-09-16 12:52:22,388 - site.py - 新增站点 动漫花园 ...
【INFO】2024-09-16 12:52:22,544 - command.py - 处理事件：site.updated - [<function SiteChain.cache_site_icon at 0x000001D5B18E0CC0>, <function SiteChain.clear_site_data at 0x000001D5B17BA340>]
【INFO】2024-09-16 12:52:22,557 - site.py - 开始缓存站点 动漫花园 图标 ...
【INFO】2024-09-16 12:52:23,291 - site.py - 缓存站点 ACG.RIP 图标成功
【INFO】2024-09-16 12:52:24,096 - site.py - 站点【MiKan】连通性正常，不同步CookieCloud数据
【INFO】2024-09-16 12:52:24,109 - site.py - CookieCloud同步成功：更新了0个站点，新增了2个站点，3个站点添加失败，下次同步时将重试，也可以手动添加
【INFO】2024-09-16 12:52:24,798 - site.py - 缓存站点 动漫花园 图标成功
【INFO】2024-09-16 12:56:11,468 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-16 12:56:11,488 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-16 12:56:11,707 - mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
【INFO】2024-09-16 12:56:11,728 - mediaserver.py - 正在同步 jellyfin 媒体库 电影 ...
【INFO】2024-09-16 12:56:12,977 - mediaserver.py - jellyfin 媒体库 电影 同步完成，共同步数量：8
【INFO】2024-09-16 12:56:12,979 - mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：8
【INFO】2024-09-16 13:01:11,476 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-16 13:01:11,526 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-16 13:02:40,022 - indexer - Nyaa 搜索完成，耗时 1 秒，返回数据：75
【INFO】2024-09-16 13:02:40,027 - search.py - 站点搜索进度：1 / 1
【INFO】2024-09-16 13:02:40,029 - search.py - 站点搜索完成，有效资源数：75，总耗时 2 秒
【INFO】2024-09-16 13:06:11,466 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-16 13:06:11,501 - transfer.py - 没有获取到已完成的下载任务
```

**Comment by hbq0405** [comment]
你订阅了啥？

**Comment by hbq0405** [comment]
标题过滤又是啥玩意？

**Comment by blackappleD** [comment]
> 标题过滤又是啥玩意？

看日志 没有执行订阅相关的任务

**Comment by hbq0405** [comment]
+++[FHD]这是啥意思？有这样的种子名字吗？

**Comment by blackappleD** [comment]
> +++[FHD]这是啥意思？有这样的种子名字吗？

去掉了，依然没有日志

**Comment by hbq0405** [comment]
也许是公开站点的问题，你试试订阅正常PT站

**Comment by blackappleD** [comment]
> 也许是公开站点的问题，你试试订阅正常PT站

订阅了冰淇淋，还是没有相关下载任务

**Comment by hbq0405** [comment]
日志呢？有没有？

**Comment by blackappleD** [comment]
> 日志呢？有没有？

【INFO】2024-09-17 15:59:03,265 - mediaserver.py - 正在同步 jellyfin 媒体库 电影 ...
【INFO】2024-09-17 15:59:04,408 - mediaserver.py - jellyfin 媒体库 电影 同步完成，共同步数量：8
【INFO】2024-09-17 15:59:04,415 - mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：8
【INFO】2024-09-17 16:04:02,805 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:04:02,828 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:09:02,808 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:09:02,819 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:13:20,177 - login.py - 用户 admin 登录成功！
【INFO】2024-09-17 16:14:02,807 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:14:02,819 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:19:02,806 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:19:02,834 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:24:02,807 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:24:02,818 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:29:02,801 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:29:02,828 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:34:02,812 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:34:02,853 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:39:02,812 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:39:02,842 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:44:02,819 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:44:02,851 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:49:02,815 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:49:02,842 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:54:02,800 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:54:02,835 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:59:02,813 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 16:59:02,824 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 16:59:03,262 - mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
【INFO】2024-09-17 16:59:03,292 - mediaserver.py - 正在同步 jellyfin 媒体库 电影 ...
【INFO】2024-09-17 16:59:04,680 - mediaserver.py - jellyfin 媒体库 电影 同步完成，共同步数量：8
【INFO】2024-09-17 16:59:04,681 - mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：8
【INFO】2024-09-17 17:04:02,796 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:04:02,831 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:09:02,813 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:09:02,833 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:14:02,797 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:14:02,830 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:19:02,812 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:19:02,840 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:24:02,802 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:24:02,832 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:29:02,801 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:29:02,828 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:34:02,805 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:34:02,818 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:39:02,813 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:39:02,825 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:44:02,819 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:44:02,867 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:49:02,807 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:49:02,850 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:54:02,809 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:54:02,840 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:59:02,814 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 17:59:02,836 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 17:59:03,251 - mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
【INFO】2024-09-17 17:59:03,276 - mediaserver.py - 正在同步 jellyfin 媒体库 电影 ...
【INFO】2024-09-17 17:59:04,617 - mediaserver.py - jellyfin 媒体库 电影 同步完成，共同步数量：8
【INFO】2024-09-17 17:59:04,625 - mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：8
【INFO】2024-09-17 18:04:02,816 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 18:04:02,863 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 18:09:02,807 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 18:09:02,834 - transfer.py - 没有获取到已完成的下载任务
【INFO】2024-09-17 18:14:02,803 - transfer.py - 开始执行下载器文件转移 ...
【INFO】2024-09-17 18:14:02,838 - transfer.py - 没有获取到已完成的下载任务

**Comment by blackappleD** [comment]
> 日志呢？有没有？

请问除了站点和订阅，是我还漏掉了什么配置吗
