### ISSUE TITLE
[Feature Request]: 是否考虑添加一个开关

### ISSUE THREAD

**Issue by blackappleD** [jxxghp/MoviePilot#2747]
### 当前程序版本

1.9.17

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

问题：不少视频不在TMDB、豆瓣、Bangumi等媒体库中，导致很多个人制作的mv无法通过mp下载和整理，是否考虑：
1. 在媒体库数据源配置模块，添加一个媒体库匹配开关，默认开启，关闭则通过订阅获取到的种子不匹配媒体库，直接进行后续的订阅匹配、下载和洗版；
2. 为每个站点添加媒体库匹配开关，方便根据需要，区分配置那些站点的资源不需要匹配媒体库；
3. 媒体库数据源配置模块的开关优先级大于各站点开关

**Comment by hbq0405** [comment]
想多了，你都搞不清订阅原理就空想一通
没有TMDB等数据做支持，只能手动下载、整理
