### ISSUE TITLE
[错误报告]: 刷流插件无法获取到我堡前50的免费种子

### ISSUE THREAD

**Issue by slightrain** [jxxghp/MoviePilot#2757]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.17

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

刷流插件无法获取到前50中的免费种子，之前有人提问解决了，现在好像又出现了。nt用同样rss能获取到。

### 发生问题时系统日志和配置文件

```bash
日志无异常，提示插件正常运行。
```

**Comment by coderZoe** [comment]
同问题，无法刷流我堡

**Comment by LongShengWen** [comment]
我也遇到相同问题
