### ISSUE TITLE
[错误报告]: 青蛙站点地址已更新，无法在站点中新增青蛙站点

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#2767]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.15

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

在站点管理里面新增青蛙站点提示无效，无法新增站点
站点地址：https://new.qingwa.pro/

![image](https://github.com/user-attachments/assets/bab01659-3d4e-4a8f-9528-289488cc83a0)

**Comment by dlovew** [comment]
用这个站点https://www.qingwapt.com/

**Comment by carolcoral** [comment]
> 用这个站点https://www.qingwapt.com/

好的，谢谢，已经加上了，但是还是建议把新地址加上，便于后面要切地址了
