### ISSUE TITLE
[Feature Request]: WebUI的搜索结果中，MTeam站点无法查看详情

### ISSUE THREAD

**Issue by arho14** [jxxghp/MoviePilot#2770]
### 当前程序版本

1.9.17

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

由于MTeam使用API接入MP，导致在MP的搜索结果中无法通过点击“查看详情”跳转到详情页。
虽然通过手动把域名中的api改成kp就能访问，但还是希望能在站点配置中加一个非必填项用作访问详情页，就更完美了。

**Comment by cng10001** [comment]
站点地址不就是让你填kp的吗 - -

**Comment by arho14** [comment]
> 站点地址不就是让你填kp的吗 - -

对哦，原来可以填kp哈
