### ISSUE TITLE
[错误报告]: 自定义识别词校正后，tmdb刮削异常

### ISSUE THREAD

**Issue by hbzjwyz** [jxxghp/MoviePilot#2785]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自定义识别词校正后，tmdb刮削异常。
当前待识别目录文件：
[BIO][仮面ライダークウガ][Special Episode 01][BDrip][1080P][X264 AAC].mp4
[BIO][仮面ライダークウガ][Special Episode 02][BDrip][1080P][X264 AAC].mp4
自定义识别词设定：
\[仮面ライダークウガ\]\[Special Episode 01\] => {[tmdbid=584605;type=movie]}
\[仮面ライダークウガ\]\[Special Episode 02\] => {[tmdbid=586510;type=movie]}
异常现象：
[BIO][仮面ライダークウガ][Special Episode 01][BDrip][1080P][X264 AAC].mp4正常刮削584605
![image](https://github.com/user-attachments/assets/0266731e-8f4b-45ba-807b-daf2e8e76caf)

[BIO][仮面ライダークウガ][Special Episode 02][BDrip][1080P][X264 AAC].mp4异常刮削584605
![image](https://github.com/user-attachments/assets/c74c3fae-151e-4220-9e72-d6763be520aa)

**Comment by ljw1412** [comment]
这个bug好像是TMDB的缓存问题。被替换后两个文件的识别名称都变成了“[BIO][BDrip][1080P][X264 AAC]”，导致取缓存时被认为是同一个key因此都返回了第一次的结果。

**我也遇到了类似的问题：**
![列表](https://github.com/user-attachments/assets/c08fc7cb-f7ba-4359-a36d-d7e23b0ef0a8)
![文件1](https://github.com/user-attachments/assets/f32ea171-8f19-4b62-9b2c-0cb23f248873)
![文件2](https://github.com/user-attachments/assets/2dfe3ea3-2203-4dd0-85b0-4c5f379d86b3)
![文件3](https://github.com/user-attachments/assets/a12b52e5-ed7f-4169-904f-d89af6dbcfa3)

**暂时个人的解决方法**(就是让key值不重复)
![自定义识别词](https://github.com/user-attachments/assets/2ba08e28-dda2-44b7-8416-9af4ff6d50d8)
![文件2](https://github.com/user-attachments/assets/b09d1956-bbc1-4082-81b5-ba610c673f72)

**Comment by Akimio521** [comment]
已在 #3030 解决
