### ISSUE TITLE
[错误报告]: 城市无法正确下载文件

### ISSUE THREAD

**Issue by sakurasep** [jxxghp/MoviePilot#2806]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在添加了城市这个站点之后，没有办法通过mp去下载影视资源，想知道城市有什么特殊设置吗？
![image](https://github.com/user-attachments/assets/cb21281d-cd24-4001-bcde-7411039f8ff4)
![image](https://github.com/user-attachments/assets/9992a6f2-03e5-4eff-856f-52822c438ff4)
无论是qb还是tr我都试了一下，只有城市出现了这个问题，其他站点可以正常添加下载。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-10-04 00:49:11,746 - themoviedb - Bad Boys 4 Ride Or Die TMDB识别结果：电影 绝地战警：生死与共 (2024) 573435
【INFO】2024-10-04 00:49:10,880 - themoviedb - Bad Boys 4 Ride Or Die 使用TMDB识别缓存：绝地战警：生死与共
【INFO】2024-10-04 00:49:08,146 - indexer - 城市 搜索完成，耗时 2 秒，返回数据：48
【INFO】2024-10-04 00:49:05,932 - spider.py - 开始请求：https://hdcity.city/torrents.php
【INFO】2024-10-04 00:49:05,928 - torrents.py - 开始获取站点 hdcity.city 最新种子 ...
```

**Comment by sakurasep** [comment]
奇怪的是日志中并没有说明哪里出现问题了

**Comment by lzcer** [comment]
v2.1.0也是这样

**Comment by miaozhi363955289** [comment]
我也遇到了相同问题很奇怪，能搜索站点资源，但是下载种子就报错 ，其他站点正常

**Comment by miaozhi363955289** [comment]
[INFO] 当前版本号：v2.5.9-4

[INFO] 最新的v2后端版本号：v2.5.9-4

INFO:    [moviepilot] 2025-07-02 17:40:14,491 monitor.py - 目录监控启动完成: 本地监控 0 个，远程监控 0 个

INFO:    [pluginautoupdate] 2025-07-02 17:42:55,358 pluginautoupdate - 插件更新任务开始

INFO:    [pluginautoupdate] 2025-07-02 17:42:55,435 plugin.py - 共获取到 223 个线上插件

INFO:    [pluginautoupdate] 2025-07-02 17:42:55,461 pluginautoupdate - 所有插件已是最新版本

ERROR:   [bilibilidiscover] 2025-07-02 17:43:24,526 bilibilidiscover - 获取哔哩哔哩数据失败: 无法连接哔哩哔哩，请检查网络连接！

ERROR:   [bilibilidiscover] 2025-07-02 17:43:24,527 bilibilidiscover - 无法连接哔哩哔哩，请检查网络连接！

INFO:    [autodiagnosis] 2025-07-02 17:44:20,143 autodiagnosis - 没有选择模块进行健康检查

INFO:    [autodiagnosis] 2025-07-02 17:44:20,144 autodiagnosis - 没有选择域名进行网络连通性测试

ERROR:   [autodiagnosis] 2025-07-02 17:45:15,704 autodiagnosis - 域名 qyapi.weixin.qq.com 测试结果：错误，详细信息：网络连接失败！

ERROR:   [autodiagnosis] 2025-07-02 17:45:15,829 autodiagnosis - 域名 frodo.douban.com 测试结果：错误，详细信息：网络连接失败！

INFO:     171.213.243.117:0 - "GET /api/v1/plugin/?state=market&force=false HTTP/1.1" 200 OK

INFO:    [autodiagnosis] 2025-07-02 17:46:43,532 autodiagnosis - 域名 api.themoviedb.org 测试结果：正常，详细信息：840ms

INFO:    [autodiagnosis] 2025-07-02 17:46:45,470 autodiagnosis - 域名 api.tmdb.org 测试结果：正常，详细信息：1937ms

INFO:    [autodiagnosis] 2025-07-02 17:46:46,068 autodiagnosis - 域名 www.themoviedb.org 测试结果：正常，详细信息：596ms

INFO:    [autodiagnosis] 2025-07-02 17:46:46,346 autodiagnosis - 域名 api.thetvdb.com 测试结果：正常，详细信息：277ms

ERROR:   [autodiagnosis] 2025-07-02 17:46:51,367 autodiagnosis - 域名 webservice.fanart.tv 测试结果：错误，详细信息：网络连接失败！

ERROR:   [autodiagnosis] 2025-07-02 17:46:53,202 autodiagnosis - 域名 qyapi.weixin.qq.com 测试结果：错误，详细信息：网络连接失败！

ERROR:   [autodiagnosis] 2025-07-02 17:46:53,358 autodiagnosis - 域名 frodo.douban.com 测试结果：错误，详细信息：网络连接失败！

ERROR:   [autodiagnosis] 2025-07-02 17:46:53,503 autodiagnosis - 域名 slack.com 测试结果：错误，详细信息：网络连接失败！

INFO:    [moviepilot] 2025-07-02 18:06:49,633 torrents.py - 开始获取站点 m-team.cc 最新种子 ...

INFO:    [moviepilot] 2025-07-02 18:06:50,657 indexer - 馒头 搜索完成，耗时 0 秒，返回数据：100

INFO:     171.222.185.168:0 - "GET /api/v1/site/resource/3?cat= HTTP/1.1" 200 OK

INFO:     171.222.185.168:0 - "GET /api/v1/download/clients HTTP/1.1" 200 OK

INFO:     171.222.185.168:0 - "GET /api/v1/system/setting/Directories HTTP/1.1" 200 OK

INFO:    [moviepilot] 2025-07-02 18:06:52,824 themoviedb - 正在识别 Interstellar ...

INFO:    [moviepilot] 2025-07-02 18:06:54,899 themoviedb - Interstellar TMDB识别结果：电影 星际穿越 (2014) 157336

ERROR:   [moviepilot] 2025-07-02 18:06:55,040 download.py - Interstellar.2014.IMAX.Bluray.2160p.HDR.x265.DTS-HD.MA.5.1.2Audio-MTeam 无法获取下载地址：[eyJtZXRob2QiOiAicG9zdCIsICJjb29raWUiOiBmYWxzZSwgInBhcmFtcyI6IHsiaWQiOiAiOTg5OTU3In0sICJoZWFkZXIiOiB7IlVzZXItQWdlbnQiOiAiTW96aWxsYS81LjAg==]https://api.m-team.cc/api/torrent/genDlToken！
