### ISSUE TITLE
iyuu认证提示失败，提示未绑定合作站点

### ISSUE THREAD

**Issue by wilson0929** [jxxghp/MoviePilot#2807]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

docke环境变量中配置IYUU认证方式和IYUU_SIGN，通过IYUU API 测试确实绑定过
![image](https://github.com/user-attachments/assets/eaf06415-cf04-4dad-9800-eb6db7688f55)

![image](https://github.com/user-attachments/assets/7aabf8d4-4022-4553-a46f-9f331f1f7190)

![image](https://github.com/user-attachments/assets/e79cd8d1-3f90-4d1a-b585-aa01ee5b4b45)

**Comment by novolife** [comment]
老哥你怎么解决的？我也卡在这了

**Comment by z979054461** [comment]
老哥，我也卡这里了   有没有大佬邀请个pt站点啊😢
