### ISSUE TITLE
mp v2 订阅使用优先级规则组，资源被错误过滤

### ISSUE THREAD

**Issue by termzh** [jxxghp/MoviePilot#2816]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.0-alpha

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

<img width="894" alt="截屏2024-10-08 11 54 17" src="https://github.com/user-attachments/assets/dcb29831-0a9c-4ab2-b782-2da6a3961116">
<img width="638" alt="截屏2024-10-08 11 54 35" src="https://github.com/user-attachments/assets/87a2e357-4ee3-49ec-b6b0-fa33299aaa65">
<img width="1284" alt="截屏2024-10-08 11 54 49" src="https://github.com/user-attachments/assets/2dc0acfd-5d22-42cd-9b9b-d9ffabbf2f03">
按照规则设置，种子 People's Police S01E01-E03 2024 2160p WEB-DL AAC 应该是符合规则的，但结果却被过滤了

**Comment by hbq0405** [comment]
资源大于你设定的值，被过滤掉了

**Comment by termzh** [comment]
> 资源大于你设定的值，被过滤掉了

大于指的是什么？我没有限制大小啊

**Comment by hbq0405** [comment]
![image](https://github.com/user-attachments/assets/70c720c5-1bf7-4dec-9d4f-d901305b3f98)
wen'jian文件体积范围，理解不了吗？你觉得能下载到小于10M的剧集？

**Comment by hbq0405** [comment]
哈，没注意
这个好像是V2的一个BUG，你先去掉自定义，然后再重新添加自定义就行了
