### ISSUE TITLE
[错误报告]: 订阅自定义修改集数无效，还是按tmdb来

### ISSUE THREAD

**Issue by wq2020wdm** [jxxghp/MoviePilot#284]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.7

### 问题类型

主程序运行问题

### 问题描述

我订阅了乐队的夏天，tmdb数据只有6，我修改了自定义集数为20，但是依旧提示订阅完成

**Comment by xuanqb** [comment]
一样，我现在临时用自定义订阅了

**Comment by jxxghp** [comment]
修改后界面显示有变化吗？

**Comment by xuanqb** [comment]
界面有变化，贴下当时的日志
> 【WARNING】2023-08-25 22:39:00,479 - search.py - 乐队的夏天 没有符合过滤条件的资源
【WARNING】2023-08-25 22:39:00,480 - subscribe.py - 订阅 乐队的夏天 未搜索到资源
【INFO】2023-08-25 22:39:00,480 - subscribe.py - 乐队的夏天 (2019) 季 3 更新缺失集数为16 ...
【INFO】2023-08-25 22:39:58,092 - subscribe.py - 开始搜索订阅，标题：乐队的夏天 ...
【INFO】2023-08-25 22:39:58,094 - __init__.py - 乐队的夏天 使用识别缓存：乐队的夏天
【INFO】2023-08-25 22:39:58,094 - tmdbapi.py - 正在查询TMDB电视剧：90756 ...
【INFO】2023-08-25 22:39:58,095 - tmdbapi.py - 90756 查询结果：乐队的夏天
【INFO】2023-08-25 22:39:58,096 - __init__.py - 乐队的夏天 识别结果：电视剧 乐队的夏天 (2019) 90756
【INFO】2023-08-25 22:39:58,135 - __init__.py - 乐队的夏天 (2019) 在媒体库中不存在
【INFO】2023-08-25 22:39:58,136 - subscribe.py - 订阅 乐队的夏天 (2019) S03 缺失集：[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:39:58,137 - search.py - 开始搜索资源，关键词：乐队的夏天 ...
【INFO】2023-08-25 22:39:58,146 - spider.py - 开始请求：https://hhanclub.top/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E4%B9%90%E9%98%9F%E7%9A%84%E5%A4%8F%E5%A4%A9&cat404=1&cat405=1&cat402=1&cat403=1
【INFO】2023-08-25 22:40:00,045 - __init__.py - 憨憨 搜索完成，耗时 1 秒，返回数据：8
【INFO】2023-08-25 22:40:00,046 - search.py - 站点搜索进度：1 / 1
【INFO】2023-08-25 22:40:00,047 - search.py - 站点搜索完成，有效资源数：8，总耗时 1 秒
【INFO】2023-08-25 22:40:00,048 - search.py - 开始过滤资源，当前规则： SPECSUB & !BLU & !720P & !DOLBY > !BLU & CNSUB & !720P & !DOLBY > 720P  ...
【INFO】2023-08-25 22:40:00,066 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:00,069 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 集 [3, 4] 没有需要的集：[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:40:00,084 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:00,087 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 集 [3, 4] 没有需要的集：[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:40:00,104 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:00,106 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 集 [1] 没有需要的集：[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:40:00,123 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:00,138 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 集 [1, 2] 没有需要的集：[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:40:00,157 - __init__.py - 种子 憨憨 - The Big Band S00 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:00,165 - __init__.py - 种子 憨憨 - The Big Band S00 2023 2160p WEB-DL H265 DDP2.0-HHWEB 不是需要的季
【INFO】2023-08-25 22:40:00,188 - __init__.py - 种子 憨憨 - The Big Band 2019 S01 Complete 2160p WEB-DL HEVC AAC-QHstudIo 优先级为 2
【INFO】2023-08-25 22:40:00,192 - __init__.py - 种子 憨憨 - The Big Band 2019 S01 Complete 2160p WEB-DL HEVC AAC-QHstudIo 不是需要的季
【INFO】2023-08-25 22:40:00,208 - __init__.py - 种子 憨憨 - The Big Band 2020 S02 Complete 1080p WEB-DL H.265 AAC-PTerWEB 优先级为 2
【INFO】2023-08-25 22:40:00,211 - __init__.py - 种子 憨憨 - The Big Band 2020 S02 Complete 1080p WEB-DL H.265 AAC-PTerWEB 不是需要的季
【INFO】2023-08-25 22:40:00,228 - __init__.py - 种子 憨憨 - The Big Band Repack 2019 S01 Complete 1080p WEB-DL H.265 AAC-PTerWEB 优先级为 2
【INFO】2023-08-25 22:40:00,233 - __init__.py - 种子 憨憨 - The Big Band Repack 2019 S01 Complete 1080p WEB-DL H.265 AAC-PTerWEB 不是需要的季
【WARNING】2023-08-25 22:40:00,234 - search.py - 乐队的夏天 没有符合过滤条件的资源
【WARNING】2023-08-25 22:40:00,238 - subscribe.py - 订阅 乐队的夏天 未搜索到资源
【INFO】2023-08-25 22:40:00,239 - subscribe.py - 乐队的夏天 (2019) 季 3 更新缺失集数为16 ...
【INFO】2023-08-25 22:40:29,971 - subscribe.py - 开始搜索订阅，标题：乐队的夏天 ...
【INFO】2023-08-25 22:40:29,973 - __init__.py - 乐队的夏天 使用识别缓存：乐队的夏天
【INFO】2023-08-25 22:40:29,973 - tmdbapi.py - 正在查询TMDB电视剧：90756 ...
【INFO】2023-08-25 22:40:29,974 - tmdbapi.py - 90756 查询结果：乐队的夏天
【INFO】2023-08-25 22:40:29,975 - __init__.py - 乐队的夏天 识别结果：电视剧 乐队的夏天 (2019) 90756
【INFO】2023-08-25 22:40:30,020 - __init__.py - 乐队的夏天 (2019) 在媒体库中不存在
【INFO】2023-08-25 22:40:30,021 - subscribe.py - 订阅 乐队的夏天 (2019) S03 缺失集：[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
【INFO】2023-08-25 22:40:30,022 - search.py - 开始搜索资源，关键词：乐队的夏天 ...
【INFO】2023-08-25 22:40:30,032 - spider.py - 开始请求：https://hhanclub.top/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E4%B9%90%E9%98%9F%E7%9A%84%E5%A4%8F%E5%A4%A9&cat404=1&cat405=1&cat402=1&cat403=1
【INFO】2023-08-25 22:40:31,758 - __init__.py - 憨憨 搜索完成，耗时 1 秒，返回数据：8
【INFO】2023-08-25 22:40:31,759 - search.py - 站点搜索进度：1 / 1
【INFO】2023-08-25 22:40:31,760 - search.py - 站点搜索完成，有效资源数：8，总耗时 1 秒
【INFO】2023-08-25 22:40:31,761 - search.py - 开始过滤资源，当前规则： SPECSUB & !BLU & !720P & !DOLBY > !BLU & CNSUB & !720P & !DOLBY > 720P  ...
【INFO】2023-08-25 22:40:31,784 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:31,804 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:31,827 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:31,847 - __init__.py - 种子 憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:31,866 - __init__.py - 种子 憨憨 - The Big Band S00 2023 2160p WEB-DL H265 DDP2.0-HHWEB 优先级为 2
【INFO】2023-08-25 22:40:31,868 - __init__.py - 种子 憨憨 - The Big Band S00 2023 2160p WEB-DL H265 DDP2.0-HHWEB 不是需要的季
【INFO】2023-08-25 22:40:31,885 - __init__.py - 种子 憨憨 - The Big Band 2019 S01 Complete 2160p WEB-DL HEVC AAC-QHstudIo 优先级为 2
【INFO】2023-08-25 22:40:31,888 - __init__.py - 种子 憨憨 - The Big Band 2019 S01 Complete 2160p WEB-DL HEVC AAC-QHstudIo 不是需要的季
【INFO】2023-08-25 22:40:31,905 - __init__.py - 种子 憨憨 - The Big Band 2020 S02 Complete 1080p WEB-DL H.265 AAC-PTerWEB 优先级为 2
【INFO】2023-08-25 22:40:31,915 - __init__.py - 种子 憨憨 - The Big Band 2020 S02 Complete 1080p WEB-DL H.265 AAC-PTerWEB 不是需要的季
【INFO】2023-08-25 22:40:31,931 - __init__.py - 种子 憨憨 - The Big Band Repack 2019 S01 Complete 1080p WEB-DL H.265 AAC-PTerWEB 优先级为 2
【INFO】2023-08-25 22:40:31,935 - __init__.py - 种子 憨憨 - The Big Band Repack 2019 S01 Complete 1080p WEB-DL H.265 AAC-PTerWEB 不是需要的季
【INFO】2023-08-25 22:40:31,938 - search.py - 开始匹配，总 4 个资源 ...
【INFO】2023-08-25 22:40:31,945 - search.py - 乐队的夏天 匹配到资源：憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB
【INFO】2023-08-25 22:40:31,951 - search.py - 乐队的夏天 匹配到资源：憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB
【INFO】2023-08-25 22:40:31,956 - search.py - 乐队的夏天 匹配到资源：憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB
【INFO】2023-08-25 22:40:31,963 - search.py - 乐队的夏天 匹配到资源：憨憨 - The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB
【INFO】2023-08-25 22:40:31,964 - search.py - 匹配完成，共匹配到 4 个资源
【INFO】2023-08-25 22:40:41,406 - __init__.py - 发送消息：channel=None，title=乐队的夏天 (2019) S03 E03-E04 开始下载, text=站点：憨憨
质量： WEB-DL 2160p
大小：14.66G
种子：The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB
做种数：105
促销：普通
描述：乐队的夏天 第三季 第03-04集（第二期） | 4k高码率 | 类型:音乐/真人秀 | 主演:大张伟/高叶/马东/那英/彭磊，userid=None
【INFO】2023-08-25 22:40:41,411 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f9648794fe0>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 22:40:44,839 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 22:40:56,974 - __init__.py - 发送消息：channel=None，title=乐队的夏天 (2019) S03 E01-E02 开始下载, text=站点：憨憨
质量： WEB-DL 2160p
大小：16.13G
种子：The Big Band S03 2023 2160p WEB-DL H265 DDP2.0-HHWEB
做种数：77
促销：普通
描述：乐队的夏天 第三季 第01-02集（第1期） | 4k高码率 | 类型:音乐/真人秀 | 主演:大张伟/高叶/马东/那英/彭磊，userid=None
【INFO】2023-08-25 22:40:56,974 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f9648794fe0>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 22:40:58,640 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 22:40:59,601 - subscribe.py - 乐队的夏天 (2019) 未下载未完整，继续订阅 ...
【INFO】2023-08-25 22:40:59,611 - subscribe.py - 乐队的夏天 (2019) 季 3 更新缺失集数为16 ...
INFO】2023-08-25 23:03:05,039 - transfer.py - 获取到 2 个已完成的下载任务
【INFO】2023-08-25 23:03:05,478 - tmdbapi.py - 正在查询TMDB电视剧：90756 ...
【INFO】2023-08-25 23:03:05,493 - tmdbapi.py - 90756 查询结果：乐队的夏天
【INFO】2023-08-25 23:03:05,524 - __init__.py - 90756 识别结果：电视剧 乐队的夏天 (2019)
【INFO】2023-08-25 23:03:05,525 - transfer.py - 乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB 识别为：电视剧 乐队的夏天 (2019)
【WARNING】2023-08-25 23:03:05,531 - __init__.py - 没有获取到 乐队的夏天 (2019) 的Fanart图片数据
【INFO】2023-08-25 23:03:05,533 - tmdbapi.py - 正在获取电视剧图片：90756...
【INFO】2023-08-25 23:03:05,882 - __init__.py - 正在转移文件：/download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv 到 /download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E03 - 第 3 集 - 2160p - HHWEB.mkv
【INFO】2023-08-25 23:03:05,903 - __init__.py - 文件 /download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv link完成
【INFO】2023-08-25 23:03:05,919 - __init__.py - 正在转移文件：/download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E01.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv 到 /download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E01 - 第 1 集 - 2160p - HHWEB.mkv
【INFO】2023-08-25 23:03:05,921 - __init__.py - 文件 /download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E01.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv link完成
【INFO】2023-08-25 23:03:05,937 - __init__.py - 正在转移文件：/download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E02.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv 到 /download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E02 - 第 2 集 - 2160p - HHWEB.mkv
【INFO】2023-08-25 23:03:05,938 - __init__.py - 文件 /download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E02.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv link完成
【INFO】2023-08-25 23:03:05,954 - __init__.py - 正在转移文件：/download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E04.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv 到 /download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E04 - 第 4 集 - 2160p - HHWEB.mkv
【INFO】2023-08-25 23:03:05,955 - __init__.py - 文件 /download2/qb/tv/乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB/The.Big.Band.S03E04.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB.mkv link完成
【INFO】2023-08-25 23:03:06,589 - emby.py - 开始刷新Emby媒体库...
【INFO】2023-08-25 23:03:07,345 - __init__.py - 发送消息：channel=None，title=乐队的夏天 (2019) S03 E03-E04 已入库, text=评分：8.7，类型：电视剧，类别：综艺，质量： WEB-DL 2160p，共4个文件，大小：30.78G，userid=None
【INFO】2023-08-25 23:03:07,348 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f9648794fe0>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 23:03:12,175 - command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f96488ced40>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 23:03:12,446 - tmdbapi.py - 正在查询TMDB电视剧：90756 ...
【INFO】2023-08-25 23:03:12,447 - tmdbapi.py - 90756 查询结果：乐队的夏天
【INFO】2023-08-25 23:03:12,476 - __init__.py - 90756 识别结果：电视剧 乐队的夏天 (2019)
【INFO】2023-08-25 23:03:12,477 - transfer.py - 乐队的夏天.The.Big.Band.S03.2023.2160p.WEB-DL.H265.DDP2.0-HHWEB 识别为：电视剧 乐队的夏天 (2019)
【WARNING】2023-08-25 23:03:12,477 - __init__.py - 没有获取到 乐队的夏天 (2019) 的Fanart图片数据
【INFO】2023-08-25 23:03:12,478 - tmdbapi.py - 正在获取电视剧图片：90756...
【WARNING】2023-08-25 23:03:12,586 - __init__.py - 文件已存在：/download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E03 - 第 3 集 - 2160p - HHWEB.mkv
【WARNING】2023-08-25 23:03:12,598 - __init__.py - 文件已存在：/download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E01 - 第 1 集 - 2160p - HHWEB.mkv
【WARNING】2023-08-25 23:03:12,613 - __init__.py - 文件已存在：/download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E02 - 第 2 集 - 2160p - HHWEB.mkv
【WARNING】2023-08-25 23:03:12,627 - __init__.py - 文件已存在：/download2/resources/tv/综艺/乐队的夏天 (2019)/Season 3/乐队的夏天 - S03E04 - 第 4 集 - 2160p - HHWEB.mkv
【INFO】2023-08-25 23:03:13,104 - emby.py - 开始刷新Emby媒体库...
【INFO】2023-08-25 23:03:13,184 - __init__.py - 发送消息：channel=None，title=乐队的夏天 (2019) S03 E01-E02 已入库, text=评分：8.7，类型：电视剧，类别：综艺，质量： WEB-DL 2160p，共4个文件，大小：30.78G，userid=None
【INFO】2023-08-25 23:03:13,184 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f9648794fe0>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-25 23:03:14,750 - command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f96488ced40>, <function WebHook.send at 0x7f96487c2660>]
【INFO】2023-08-26 04:50:23,019 - subscribe.py - 开始搜索订阅，标题：乐队的夏天 ...
【INFO】2023-08-26 04:50:23,021 - __init__.py - 乐队的夏天 使用识别缓存：乐队的夏天
【INFO】2023-08-26 04:50:23,021 - tmdbapi.py - 正在查询TMDB电视剧：90756 ...
【INFO】2023-08-26 04:50:23,023 - tmdbapi.py - 90756 查询结果：乐队的夏天
【INFO】2023-08-26 04:50:23,024 - __init__.py - 乐队的夏天 识别结果：电视剧 乐队的夏天 (2019) 90756
【INFO】2023-08-26 04:50:23,379 - __init__.py - 乐队的夏天 (2019) 媒体库中已存在：{3: [1, 2, 3, 4]}
【INFO】2023-08-26 04:50:23,380 - subscribe.py - 订阅 乐队的夏天 (2019) S03 缺失集：[5]
【INFO】2023-08-26 04:50:23,381 - search.py - 开始搜索资源，关键词：乐队的夏天 ...
【INFO】2023-08-26 04:50:23,391 - spider.py - 开始请求：https://hhanclub.top/torrents.php?search_mode=0&search_area=0&page=0&notnewword=1&search=%E4%B9%90%E9%98%9F%E7%9A%84%E5%A4%8F%E5%A4%A9&cat404=1&cat405=1&cat402=1&cat403=1
