### ISSUE TITLE
[站点同步]: 柠檬本月18号回归，是不是要做下新域名的站点更新啊

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#2841]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.13

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

柠檬站点说本月（10月18）回归，站点域名发生了变更，是不是要做下同步啊，不然MP里面很多功能都用不了柠檬

**Comment by ZevAlain** [comment]
+1 或者有别的途径支持吗

**Comment by carolcoral** [comment]
https://lemonhd.club/

**Comment by ZevAlain** [comment]
> https://lemonhd.club/

自定义站点已经用上了。去站点上生成rss填mp里就能刷种了。

**Comment by Aqr-K** [comment]
支持前两天就已经做好了，更新一下资源包就行了

**Comment by carolcoral** [comment]
> 支持前两天就已经做好了，更新一下资源包就行了

重启容器服务么，还是怎么更新

**Comment by zhaoyibo** [comment]
> > 支持前两天就已经做好了，更新一下资源包就行了
> 
> 重启容器服务么，还是怎么更新

确实是重启容器，我重启后在日志里看到了资源包更新

```
INFO:    resource.py - 开始检测资源包版本...
INFO:    resource.py - 最新资源包版本：v35
INFO:    resource.py - user.sites.bin 资源包有更新，最新版本：v1.5.1
INFO:    resource.py - 开始更新资源文件：user.sites.bin ...
INFO:    resource.py - 资源包更新完成，开始重启服务...
```
