### ISSUE TITLE
[错误报告]: edge浏览器无法使用已保存的用户名密码

### ISSUE THREAD

**Issue by dlk48920101** [jxxghp/MoviePilot#2847]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

持续一段时间了，突然有一次更新后发现PC端无法正常使用保存的用户名密码一键输入然后登录。
WIN11 EDGE浏览器更换电脑也一样。手机端的EDGE是可以正常的。但是登录的时候会偶尔出现点击登录后但是没有进入，还是在登录界面，刷新一下浏览器就进入了（手机这个问题一直都有但是不怎么太影响使用，PC端每次都要输入密码就有点麻烦了）

**Comment by dlk48920101** [comment]
补充一下，手机是IOS

**Comment by dlovew** [comment]
bitwarden也没法自动填充账号密码，edge自带的密码填充也不行

**Comment by cng10001** [comment]
是edge的问题吗
我edge也不提示保存。

**Comment by dlk48920101** [comment]
应该是BUG，有概率能弹出来的。我今天重复刷新界面，有一定的概率能弹出来，大概率是弹不出来的。不要清楚能弹出来的情况是怎么样

**Comment by Jsszlee0724** [comment]
我也遇到了这个问题，用火狐是没问题的 能保存和提示

**Comment by MeikleNas** [comment]
我的win11Edge不能记住密码，ios17可以记住密码

**Comment by dsfdfsfds** [comment]
v2版本也是无法填充

**Comment by Jsszlee0724** [comment]
今天发现奇怪的事，PC端安装bitwarden之后，edge也手动新增好账号密码，然后就自己会填充了。。。

**Comment by leo19821119** [comment]
提醒保存账号必须是带正常可验证的证书的https协议的，否则不会提醒自动填充的

**Comment by cng10001** [comment]
> 提醒保存账号必须是带正常可验证的证书的https协议的，否则不会提醒自动填充的

![扣扣_2025-01-08_14-46-05](https://github.com/user-attachments/assets/a95ea27e-523a-44d5-a315-813116b7d05f)
我这个nas自带的域名算是吗

**Comment by leo19821119** [comment]
> > 提醒保存账号必须是带正常可验证的证书的https协议的，否则不会提醒自动填充的
> 
> ![扣扣_2025-01-08_14-46-05](https://private-user-images.githubusercontent.com/115156545/401036956-a95ea27e-523a-44d5-a315-813116b7d05f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMTkzMTAsIm5iZiI6MTczNjMxOTAxMCwicGF0aCI6Ii8xMTUxNTY1NDUvNDAxMDM2OTU2LWE5NWVhMjdlLTUyM2EtNDRkNS1hMzE1LTgxMzExNmI3ZDA1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwNjUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmMwZGYxYTQ3NWJhZTNjYzFjYTZlMTc1N2RhYTY2OTNjMTg2MTIzZDkxZjVlMWU0OTdjYTljYjBkOWY2NDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K5nD1NxC7tbVxlol1jyCey4ZJIjNxV6zkgMBNIVUhz0) 我这个nas自带的域名算是吗

证书看起来来是没有问题的，如果只是某一个浏览器不能自动填写密码和账号，应该是浏览器配置问题，需要另外找原因

**Comment by cng10001** [comment]
> > > 提醒保存账号必须是带正常可验证的证书的https协议的，否则不会提醒自动填充的
> > 
> > 
> > ![扣扣_2025-01-08_14-46-05](https://private-user-images.githubusercontent.com/115156545/401036956-a95ea27e-523a-44d5-a315-813116b7d05f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMTkzMTAsIm5iZiI6MTczNjMxOTAxMCwicGF0aCI6Ii8xMTUxNTY1NDUvNDAxMDM2OTU2LWE5NWVhMjdlLTUyM2EtNDRkNS1hMzE1LTgxMzExNmI3ZDA1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwNjUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmMwZGYxYTQ3NWJhZTNjYzFjYTZlMTc1N2RhYTY2OTNjMTg2MTIzZDkxZjVlMWU0OTdjYTljYjBkOWY2NDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K5nD1NxC7tbVxlol1jyCey4ZJIjNxV6zkgMBNIVUhz0) 我这个nas自带的域名算是吗
> 
> 证书看起来来是没有问题的，如果只是某一个浏览器不能自动填写密码和账号，应该是浏览器配置问题，需要另外找原因

那就是edge的问题吧，手动添加了也不会跳出来。还好不怎么用edge

**Comment by dlk48920101** [comment]
> > > > 提醒保存账号必须是带正常可验证的证书的https协议的，否则不会提醒自动填充的
> > > 
> > > 
> > > ![扣扣_2025-01-08_14-46-05](https://private-user-images.githubusercontent.com/115156545/401036956-a95ea27e-523a-44d5-a315-813116b7d05f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzMTkzMTAsIm5iZiI6MTczNjMxOTAxMCwicGF0aCI6Ii8xMTUxNTY1NDUvNDAxMDM2OTU2LWE5NWVhMjdlLTUyM2EtNDRkNS1hMzE1LTgxMzExNmI3ZDA1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOFQwNjUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmMwZGYxYTQ3NWJhZTNjYzFjYTZlMTc1N2RhYTY2OTNjMTg2MTIzZDkxZjVlMWU0OTdjYTljYjBkOWY2NDdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K5nD1NxC7tbVxlol1jyCey4ZJIjNxV6zkgMBNIVUhz0) 我这个nas自带的域名算是吗
> > 
> > 
> > 证书看起来来是没有问题的，如果只是某一个浏览器不能自动填写密码和账号，应该是浏览器配置问题，需要另外找原因
> 
> 那就是edge的问题吧，手动添加了也不会跳出来。还好不怎么用edge

但是我记得很久之前是没有这个问题的。不知道那次更新后出现的。但是手机端就很正常都是能弹出。而且并不是百分百弹不出来。是大概率出不来。偶尔刷新几次界面就出来了。

**Comment by blacklips** [comment]
<img width="855" height="150" alt="Image" src="https://github.com/user-attachments/assets/48dd851d-8e34-4983-b8d3-61d60c13695d" />
bitwarden zen浏览器无法自动填充，Chrome可以

**Comment by SouLXH** [comment]
> <img alt="Image" width="855" height="150" src="https://private-user-images.githubusercontent.com/60835856/510567114-48dd851d-8e34-4983-b8d3-61d60c13695d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI1MjA5MDcsIm5iZiI6MTc2MjUyMDYwNywicGF0aCI6Ii82MDgzNTg1Ni81MTA1NjcxMTQtNDhkZDg1MWQtOGUzNC00OTgzLWI4ZDMtNjFkNjBjMTM2OTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTA3VDEzMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YjI4Y2NmYjEyNGM3MWY3ZTJkYzZhZmVmMmJiNDU3MDM1ZTNlMDM1MmRiODk2MTYwNzg4ZWI0MzgyZWY1NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.958USSgDByZYFK8UszUr_A4RKciq-qjjo-mVZRd_uaE"> bitwarden zen浏览器无法自动填充，Chrome可以

我之前一直用的2.5.7版本，可以用bitwarden 快速填充，刚才更新了2.8.1版本 发现bitwarden不能填充了 和你一样的情况。
