### ISSUE TITLE
[错误报告]: 下载的时候出现未知错误的问题

### ISSUE THREAD

**Issue by dadiYazZ** [jxxghp/MoviePilot#2859]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/user-attachments/assets/a69d2dcd-c707-42c3-85dd-8239377c8a55)
![image](https://github.com/user-attachments/assets/c49c750d-734b-48a6-bb2e-a70e30d06daa)

下载的时候出现未知错误的问题,系统检测也都没有问题

**Comment by dadiYazZ** [comment]
![image](https://github.com/user-attachments/assets/c85cefd3-c5dd-4082-ae97-13fd4e100ef3)

**Comment by qin9125** [comment]
<img width="794" alt="image" src="https://github.com/user-attachments/assets/c26cd98e-1aba-48e6-899f-79d6cb3faf8b">
你自己的问题，
