### ISSUE TITLE
[错误报告]: tmdb数据错误导致订阅单季失败

### ISSUE THREAD

**Issue by Devinaille** [jxxghp/MoviePilot#2866]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

问题现象：订阅Re: 从零开始的异世界生活 第三季的时候发现无法订阅到第三季的内容

排查：tmdb上是把所有集都放到了Season 1里，但是又再剧集组里分了1-3季。
现在情况就尴尬在订阅的时候他会按照总集数寻找，但站点里的信息都是按照第三季来分的，所以按照总集数搜索不到对应的集，但是手动整理下载好的单季又能刮削成第三季。

疑问：现在不知道这个逻辑具体是什么样的。或者我应该怎么正确的让订阅起作用

**Comment by shyblacktea** [comment]
不如试试mp-设定-服务-清理缓存？

**Comment by Devinaille** [comment]
@shyblacktea 感觉不是缓存的问题，我感觉是订阅没用TMDB剧集组的数据，但刮削用到了。所以会出现订阅不到数据但是能刮削到数据的情况

**Comment by l429609201** [comment]
现在TMDB管理员在奉行他们的动漫指南，以“绝对序号”来排布，就连海贼王都是他们眼中的一季度。我也是发现刮削器通常以TMDB剧集主页的剧集排序来刮削，具体分好剧集的剧集组没有被刮削器使用到，希望大佬们能增加使用TMDB聚集组刮削的功能。

**Comment by 954708775** [comment]
我也有这个问题，有的时候订阅就是好的，很挑时候，今天打算订阅夏目友人帐也出现了这个问题，现在不知道该怎么办

**Comment by Mister-album** [comment]
> 现在TMDB管理员在奉行他们的动漫指南，以“绝对序号”来排布，就连海贼王都是他们眼中的一季度。我也是发现刮削器通常以TMDB剧集主页的剧集排序来刮削，具体分好剧集的剧集组没有被刮削器使用到，希望大佬们能增加使用TMDB聚集组刮削的功能。

支持，剧集组刮削有很大的便利之处，很多剧tmdb官方的编排很奇怪，又锁定了不让编辑，如果是能刮削指定剧集组的话会好用很多

**Comment by l429609201** [comment]
> > 现在TMDB管理员在奉行他们的动漫指南，以“绝对序号”来排布，就连海贼王都是他们眼中的一季度。我也是发现刮削器通常以TMDB剧集主页的剧集排序来刮削，具体分好剧集的剧集组没有被刮削器使用到，希望大佬们能增加使用TMDB聚集组刮削的功能。
> 
> 支持，剧集组刮削有很大的便利之处，很多剧tmdb官方的编排很奇怪，又锁定了不让编辑，如果是能刮削指定剧集组的话会好用很多

现在已经有支持剧集组刮削的插件了，作者是叮叮当，插件搜索TMDB剧集组刮削    官方仓库有

**Comment by Mister-album** [comment]
> > > 现在TMDB管理员在奉行他们的动漫指南，以“绝对序号”来排布，就连海贼王都是他们眼中的一季度。我也是发现刮削器通常以TMDB剧集主页的剧集排序来刮削，具体分好剧集的剧集组没有被刮削器使用到，希望大佬们能增加使用TMDB聚集组刮削的功能。
> > 
> > 
> > 支持，剧集组刮削有很大的便利之处，很多剧tmdb官方的编排很奇怪，又锁定了不让编辑，如果是能刮削指定剧集组的话会好用很多
> 
> 现在已经有支持剧集组刮削的插件了，作者是叮叮当，插件搜索TMDB剧集组刮削 官方仓库有

感谢，已经用上了
