### ISSUE TITLE
天空站点签到失败

### ISSUE THREAD

**Issue by dfbb9216** [jxxghp/MoviePilot#287]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.7

### 问题类型

插件问题

### 问题描述

天空签到失败，连续两天，失败后重试一次依然失败，仿真开启关闭。手动点击空的签到，会先出现一个提示，然后才出现验证码，不知道和这个又没有关系。
![QQ截图20230827092054](https://github.com/jxxghp/MoviePilot/assets/64184911/d7689661-2d08-46bc-b433-73b6ef6f7774)
![QQ截图20230827091916](https://github.com/jxxghp/MoviePilot/assets/64184911/8d5fefaf-7247-4f62-acff-130a219f201e)
![QQ截图20230827091945](https://github.com/jxxghp/MoviePilot/assets/64184911/98525df0-ceb5-4719-9a78-3b6ea808cc14)
![QQ截图20230827091957](https://github.com/jxxghp/MoviePilot/assets/64184911/0bdb3d45-519f-49bc-a241-c0d02bd19626)

**Comment by dfbb9216** [comment]
![QQ截图20230828091007](https://github.com/jxxghp/MoviePilot/assets/64184911/5750d91e-4320-4da0-9987-a2b42319717b)
今天的，其他成功，只剩天空

**Comment by thsrite** [comment]
@dfbb9216 更新下cookie和ua试试

**Comment by dfbb9216** [comment]
> @dfbb9216 更新下cookie和ua试试

好的，我试试，明天再看结果

**Comment by dfbb9216** [comment]
![QQ截图20230829092008](https://github.com/jxxghp/MoviePilot/assets/64184911/d815cc00-6e2d-4375-9279-108bb344b999)
可以了
