### ISSUE TITLE
[Feature Request]: 关于历史记录的功能改进请求

### ISSUE THREAD

**Issue by NieRNEST** [jxxghp/MoviePilot#2870]
### 当前程序版本

1.9.17

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

1. 群里看到一些人同样也有重建媒体库的需求，因此开一个请求。目前整理分为刮削和非刮削模式，这两者都需要再跑一次tmdb查数据才能重新硬链接，对于一些手动整理才成功的记录就会变回失败。希望可以增加一个模式，按照现有记录直接重建并覆盖硬链接。
2. 目前【文件整理屏蔽词】通常很好用，但由于是直接跳过整理且只在日志提示，对于一些路径会有误伤，希望可以在现有的【失败】【成功】的基础上，增加一个【跳过】标签，便于管理记录。

最后感谢开发者一直以来的工作。

**Comment by mitlearn** [comment]
> 群里看到一些人同样也有重建媒体库的需求，因此开一个请求。目前整理分为刮削和非刮削模式，这两者都需要再跑一次tmdb查数据才能重新硬链接，对于一些手动整理才成功的记录就会变回失败。希望可以增加一个模式，按照现有记录直接重建并覆盖硬链接。

v2的 `历史记录 - 重新整理` 已支持 如有需求建议切换
![image](https://github.com/user-attachments/assets/dfd52cb4-c083-4d4a-8273-73d596225381)
