### ISSUE TITLE
[错误报告]: 套件版相对于docker 版缺失了很多插件

### ISSUE THREAD

**Issue by zjuht** [jxxghp/MoviePilot#2874]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

群辉套件版，缺少了入自动签到，药丸签到等插件

**Comment by mitlearn** [comment]
plugin_market变量是否填写[足够多的仓库](https://wiki.movie-pilot.org/zh/plugin#%E6%8F%92%E4%BB%B6%E5%B8%82%E5%9C%BA)
套件非此仓库维护 建议尽快更换为Docker版 [安装参考](https://wiki.movie-pilot.org/zh/install)
