### ISSUE TITLE
关于自动更新的功能改进[Feature Request]: 

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/MoviePilot#288]
### 当前程序版本

v1.0.7 and v1.0.8

### 参考资料

同上

**Comment by dfbb9216** [comment]
docker pull jxxghp/moviepilot:latest
docker rm -f MoviePilot
docker run -d \
  --name MoviePilot \
  -v 你想要的目录1:/config \
  -v 你想要的目录2:/moviepilot \
  -p 你想要的端口号:3000 \
  --restart=always \
  -e 环境变量1 \
  -e 环境变量2 \
  ……
  -e 环境变量n \
  jxxghp/moviepilot:latest
docker rmi $(docker images | grep 'none' | grep 'moviepilot' | awk '{print $3}')
目前手动更新用的这个，我是用的openwrt的docker，复制粘贴到ttyd终端就可以了

**Comment by dfbb9216** [comment]
手动更新，只在openwrt里的DOCKER里用过

拉镜像
删容器
建容器（容器名称，挂载目录，访问端口，重启策略，环境变量）
删老镜像

docker pull jxxghp/moviepilot:latest
docker rm -f MoviePilot
docker run -d \
  --name MoviePilot \
  -v 你想要的目录:/config \
  -v 你想要的目录:/moviepilot \
  -p 你想要的端口:3000 \
  --restart=always \
  -e 环境变量1 \
  -e 环境变量2 \
  ......
  -e 环境变量n \
  jxxghp/moviepilot:latest
docker rmi $(docker images | grep 'none' | grep 'moviepilot' | awk '{print $3}')

**Comment by jxxghp** [comment]
现在自动更新会自动安装依赖
