### ISSUE TITLE
[Feature Request]: 作者有计划支持，自定义多下载库和媒体库支持么。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#290]
### 当前程序版本

1.0.8

### 功能改进

比如下载保存路径1 路径2 这样，对应的也是媒体库1 和媒体库2
可以在下载的时候选择下载到 路径1 或者路径2
媒体库和下载库也是一一对应的这样。
可以增加变量选择开启多库功能这样的

**Comment by mjsoftking** [comment]
@kekylin 可以考虑映射一个基础目录(任选一个磁盘位置)如：/downloads，磁盘A的电影目录映射给/downloads/电影，磁盘B的电视剧目录映射给/downloads/电视剧，同时你的下载器目录配置需要与这个结构相同

**Comment by werran2** [comment]
同意。我的nt三个下载目录对应三个媒体库，想转到mp工作量好大
