### ISSUE TITLE
[错误报告]: 优先级测试不能使用

### ISSUE THREAD

**Issue by 4Nest** [jxxghp/MoviePilot#2902]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

捷径中优先级测试不能使用，卡在正在测试
![image](https://github.com/user-attachments/assets/c870c77f-c686-4509-b6d2-8294231c44d1)

### 发生问题时系统日志和配置文件

```bash
INFO:     192.168.2.5:0 - "GET /api/v1/system/ruletest?title=%E8%BE%B9%E6%B0%B4%E5%BE%80%E4%BA%8B.Escape.from.the.Trilateral.Slopes.S01.2024.2160p.WEB-DL.H265.AAC-ADWeb&subtitle=&ruletype=1 HTTP/1.1" 422 Unprocessable Entity
```

**Comment by cng10001** [comment]
422 你网络不好吧
