### ISSUE TITLE
[错误报告]: 剧集根目录名字多一个很长的空格

### ISSUE THREAD

**Issue by syscc** [jxxghp/MoviePilot#293]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.8

### 问题类型

其他问题

### 问题描述

link硬链接，电影那边没问题，电视剧这边根目录名字都是一个长空格开头
[https://img.aazze.com/file/4533cf341dbcadb9954fc.jpg](url)

**Comment by jxxghp** [comment]
检查自己的重命名配置

**Comment by syscc** [comment]
抱歉portainer面板里面没看出重命名配置问题
在群晖docker管理里面看确实是我得变量多了个空格
