### ISSUE TITLE
[错误报告]: 历史记录无法删除源文件和媒体文件

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#2941]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.0-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

直接在历史记录里删除源文件报错，但是只删除历史记录是可以的
![屏幕截图_25-10-2024_19359_192 168 2 3](https://github.com/user-attachments/assets/e4aad627-5911-481e-9002-0f88666ec67d)
![屏幕截图_25-10-2024_19452_192 168 2 3](https://github.com/user-attachments/assets/a44f0540-0316-41cf-98d2-637f379d903b)

### 发生问题时系统日志和配置文件

DEBUG:   chain - 请求模块执行：delete_file ...

DEBUG:   chain - 请求模块执行：get_file_item ...

DEBUG:   chain - 请求模块执行：list_files ...

**Comment by cng10001** [comment]
好像是昨天的更新好了，今天更新后又出问题了- -

**Comment by sunbroke555** [comment]
我也遇到了  仅删除历史记录正常。  后面三个都是undefined

**Comment by mitlearn** [comment]
同情况 [4fced92feb8e](https://hub.docker.com/layers/jxxghp/moviepilot-v2/latest/images/sha256-4fced92feb8e829c43db341328b1fe8a1e980f99d3e30ef82490281e268b79ac?context=explore)版本仍有此问题

并且还有整理方式为软链接 实为复制的问题
![image](https://github.com/user-attachments/assets/f3243537-989d-43c2-9385-e6178469b5e5)
E25、E27为v1软链接整理 其余为v2软链接整理
与此同时的日志

> 【INFO】2024-10-25 23:50:56,840 - transfer.py - /mnt/media/剧集/锦绣安宁.The.Rise.of.Ning.S01.2024.1080p.WEB-DL.H265.AAC-*****/ 整理完成，共 5 个文件，失败 2 个，跳过 0 个
【INFO】2024-10-25 23:50:56,802 - chain - 发送消息：channel=None，source=None,title=锦绣安宁 (2024) S01 E26、E28-E29 已入库, text=评分：8.0，类型：电视剧，类别：国产剧，质量： WEB-DL 1080p，共3个文件，大小：1.98G，userid=None
【INFO】2024-10-25 23:50:56,681 - filemanager - 文件 /mnt/media/剧集/锦绣安宁.The.Rise.of.Ning.S01.2024.1080p.WEB-DL.H265.AAC-*****/锦绣安宁.The.Rise.of.Ning.S01E29.2024.1080p.WEB-DL.H265.AAC-*****.mp4 整理成功
【INFO】2024-10-25 23:50:55,626 - filemanager - 正在整理文件：【local】/mnt/media/剧集/锦绣安宁.The.Rise.of.Ning.S01.2024.1080p.WEB-DL.H265.AAC-*****/锦绣安宁.The.Rise.of.Ning.S01E29.2024.1080p.WEB-DL.H265.AAC-*****.mp4 到 【local】/mnt/path/TVs/国产剧/锦绣安宁 (2024)  [tmdbid=229036]/Season 1/锦绣安宁 - S01E29 - *****.mp4
【INFO】2024-10-25 23:50:55,623 - filemanager - 获取整理目标路径：【local】/mnt/path/TVs/国产剧
【INFO】2024-10-25 23:50:55,615 - transfer.py - 锦绣安宁.The.Rise.of.Ning.S01E29.2024.1080p.WEB-DL.H265.AAC-*****.mp4 识别为：电视剧 锦绣安宁 (2024)
【WARNING】2024-10-25 23:50:55,612 - fanart - 没有获取到 锦绣安宁 (2024) 的fanart图片数据
【INFO】2024-10-25 23:50:55,608 - media.py - 锦绣安宁.The.Rise.of.Ning.S01E29.2024.1080p.WEB-DL.H265.AAC-*****.mp4 识别到媒体信息：电视剧 锦绣安宁 (2024)
【INFO】2024-10-25 23:50:55,607 - themoviedb - 锦绣安宁 TMDB识别结果：电视剧 锦绣安宁 (2024) 229036
【INFO】2024-10-25 23:50:55,604 - themoviedb - 锦绣安宁 使用TMDB识别缓存：锦绣安宁
【INFO】2024-10-25 23:50:55,571 - filemanager - 文件 /mnt/media/剧集/锦绣安宁.The.Rise.of.Ning.S01.2024.1080p.WEB-DL.H265.AAC-*****/锦绣安宁.The.Rise.of.Ning.S01E28.2024.1080p.WEB-DL.H265.AAC-*****.mp4 整理成功
【INFO】2024-10-25 23:50:54,804 - filemanager - 正在整理文件：【local】/mnt/media/剧集/锦绣安宁.The.Rise.of.Ning.S01.2024.1080p.WEB-DL.H265.AAC-*****/锦绣安宁.The.Rise.of.Ning.S01E28.2024.1080p.WEB-DL.H265.AAC-*****.mp4 到 【local】/mnt/path/TVs/国产剧/锦绣安宁 (2024)  [tmdbid=229036]/Season 1/锦绣安宁 - S01E28 - *****.mp4
【INFO】2024-10-25 23:50:54,801 - filemanager - 获取整理目标路径：【local】/mnt/path/TVs/国产剧
【INFO】2024-10-25 23:50:54,793 - transfer.py - 锦绣安宁.The.Rise.of.Ning.S01E28.2024.1080p.WEB-DL.H265.AAC-*****.mp4 识别为：电视剧 锦绣安宁 (2024)
【WARNING】2024-10-25 23:50:54,791 - fanart - 没有获取到 锦绣安宁 (2024) 的fanart图片数据
【INFO】2024-10-25 23:50:54,787 - media.py - 锦绣安宁.The.Rise.of.Ning.S01E28.2024.1080p.WEB-DL.H265.AAC-*****.mp4 识别到媒体信息：电视剧 锦绣安宁 (2024)
【INFO】2024-10-25 23:50:54,786 - themoviedb - 锦绣安宁 TMDB识别结果：电视剧 锦绣安宁 (2024) 229036
【INFO】2024-10-25 23:50:54,783 - themoviedb - 锦绣安宁 使用TMDB识别缓存：锦绣安宁

**Comment by dlovew** [comment]
@wikrin 
大佬你好，感谢修复，现在可以在历史记录里正常删除历史记录，媒体库文件和源文件了
但是我发现同步删除插件仍然不能正常工作，好像是源文件如果删除，那么在数据库downloadfiles这个表里会把数据状态调整成state为0，但是现在好像的程序并没有这么工作，下面是我从表里复制出来的，这个文件已经被我删除了，但是表里的状态仍然是1
/vol2/1000/Media/Download/坠落画境的你.Fall.For.You.2024.S01.2160p.WEB-DL.HEVC.AAC-ZmWeb	坠落画境的你.Fall.For.You.2024.S01E15.2160p.WEB-DL.HEVC.AAC-ZmWeb.mp4	坠落画境的你.Fall.For.You.2024.S01.2160p.WEB-DL.HEVC.AAC-ZmWeb.torrent	1

**Comment by wikrin** [comment]
可以再提一个 `issue`
