### ISSUE TITLE
[错误报告]: V2版本_订阅_正则排除不生效

### ISSUE THREAD

**Issue by lk6607** [jxxghp/MoviePilot#2945]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

1.订阅电视剧《花儿与少年》第6季
2.点开《花儿与少年》订阅-进阶，输入排除关键字“好友记”并保存
3.仍然会下到好友记相关资源

**Comment by cng10001** [comment]
![image](https://github.com/user-attachments/assets/20153ddf-e7a9-491e-bf7c-fc36ef786fb3)
反馈：包含和排除都未生效

**Comment by dlovew** [comment]
这个确实存在
