### ISSUE TITLE
[错误报告]: 源文件删除但是user.db里downloadfiles表中state没有更新的问题

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#2948]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

截至提问时的最新V2镜像

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

一、我发现同步删除插件不能正常工作，然后发现历史记录不能删除的bug #2941 已由大佬修复
二、但是同步删除仍然不行，经过测试发现，源文件如果删除，那么在数据库downloadfiles这个表里会把数据状态调整成state为0，但是现在好像程序并没有这么工作，下面是我从表里复制出来的一行记录，这个源文件已经被我删除了，但是表里的状态仍然是1
/vol2/1000/Media/Download/坠落画境的你.Fall.For.You.2024.S01.2160p.WEB-DL.HEVC.AAC-ZmWeb 坠落画境的你.Fall.For.You.2024.S01E15.2160p.WEB-DL.HEVC.AAC-ZmWeb.mp4 坠落画境的你.Fall.For.You.2024.S01.2160p.WEB-DL.HEVC.AAC-ZmWeb.torrent 1

**Comment by thsrite** [comment]
@dlovew 这个电影的转移记录发下看看 transferhistory

**Comment by dlovew** [comment]
好像因为文件被删除了，所以transferhistory没了，downloadhistory还在

**Comment by thsrite** [comment]
<img width="1338" alt="image" src="https://github.com/user-attachments/assets/614fd041-2e55-429d-bd60-6be4e0c4b3f3">
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/3ff8b5bd-de0b-46d7-84f7-a4e536921fdd">
刚测试了 没问题

**Comment by dlovew** [comment]
【INFO】2024-10-26 18:01:30,324 - mediasyncdel - 同步删除 电影 第八个嫌疑人 1133013 完成！
【ERROR】2024-10-26 18:01:30,323 - mediasyncdel - 删种失败： ChainBase.stop_torrents() got an unexpected keyword argument 'download'
【INFO】2024-10-26 18:01:30,323 - mediasyncdel - 查询到 a245b2614fd75c150d07d50a21b1502557f60b8d 辅种历史 [{'downloader': 'Qbittorrent', 'torrents': ['7f8a43085ed9eff04d047d0ab683db21640c8b71', '2a6bf2496bd5889ad4cee6f6b7ed744a9e92ad06']}]
【INFO】2024-10-26 18:01:30,315 - mediasyncdel - 暂停源下载器下载任务：Qbittorrent - a245b2614fd75c150d07d50a21b1502557f60b8d
【INFO】2024-10-26 18:01:30,315 - mediasyncdel - 查询种子任务 a245b2614fd75c150d07d50a21b1502557f60b8d 存在 1 个未删除文件，执行暂停种子操作
【INFO】2024-10-26 18:01:30,310 - mediasyncdel - 查询到 Qbittorrent-a245b2614fd75c150d07d50a21b1502557f60b8d 转种历史 None
【INFO】2024-10-26 18:01:30,292 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-10-26 18:01:30,289 - mediasyncdel - 正在同步删除电影 第八个嫌疑人 1133013

**Comment by dlovew** [comment]
我的qb是4.6.5，mp是v2最新的镜像，自动分类是交给qb下载器处理的

**Comment by thsrite** [comment]
【ERROR】2024-10-26 18:01:30,323 - mediasyncdel - 删种失败： ChainBase.stop_torrents() got an unexpected keyword argument 'download'
你这都报错了，qb版本问题？ 我439

**Comment by dlovew** [comment]
a245b2614fd75c150d07d50a21b1502557f60b8d	Qbittorrent	/vol2/1000/Media/Download/第八个嫌疑人.Dust.To.Dust.2023.2160p.WEB-DL.H265.DDP5.1-ADWeb/第八个嫌疑人.Dust.To.Dust.2023.2160p.WEB-DL.H265.DDP5.1-ADWeb.mkv	/vol2/1000/Media/Download/第八个嫌疑人.Dust.To.Dust.2023.2160p.WEB-DL.H265.DDP5.1-ADWeb	第八个嫌疑人.Dust.To.Dust.2023.2160p.WEB-DL.H265.DDP5.1-ADWeb.mkv	Dust To Dust 2023 2160p WEB-DL H265 DDP5.1-ADWeb	1

**Comment by dlovew** [comment]
刚刚删除的电影state也是1，等下我换成4.3.9试试

**Comment by dlovew** [comment]
折腾了半天，换了低版本qb，不过没拉到4.3.9的镜像，试了4.4.3，4.4.5，都不行，重装了mpv2也不行，正好qb我种子多，webui卡，我换到transmission4.0.5了，试了两个文件，完美删除。qb我不折腾了，等以后看看咋样吧

**Comment by cng10001** [comment]
我用的“下载器助手”插件，qBittorrent和Transimission都没问题

**Comment by dlovew** [comment]
> 我用的“下载器助手”插件，qBittorrent和Transimission都没问题

我用tr删了几部剧都没问题，我彻底投入tr怀抱了，而且我种子也多，tr确实比qb流畅

**Comment by dlovew** [comment]
因为transmission客户端被温州ip的pcdn吸血的问题导致我被电信限速，所以我又用回qb了4.6.7，然后我没做任何设置，只是把qb通过curl "http://192.168.2.3:3001/api/v1/transfer/now?token=xxxxxx"整理变成目录监控，然后一切qb也正常了。这个issue我关了
