### ISSUE TITLE
[错误报告]: 文件管理不识别文件夹

### ISSUE THREAD

**Issue by WOWLZG** [jxxghp/MoviePilot#295]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.8

### 问题类型

主程序运行问题

### 问题描述

文件管理不识别文件夹，文件夹名为[BeanSub&FZSD][BLEACH_Sennen_Kessen-hen][12-13][GB][1080P][MP4]，猜测原因是不识别特殊符号&，日志信息在&之后就断掉了

### 发生问题时系统日志和配置文件

```bash
【ERROR】2023-08-27 13:58:44,725 - filebrowser.py - 目录不存在：/D/System/Videos/下载/动漫/[BeanSub
【ERROR】2023-08-27 13:58:57,463 - filebrowser.py - 目录不存在：/D/System/Videos/下载/动漫/[BeanSub
【ERROR】2023-08-27 13:58:58,926 - filebrowser.py - 目录不存在：/D/System/Videos/下载/动漫/[BeanSub
【ERROR】2023-08-27 13:58:59,420 - filebrowser.py - 目录不存在：/D/System/Videos/下载/动漫/[BeanSub
```

**Comment by jxxghp** [comment]
代码已修复，下个版本更新
