### ISSUE TITLE
[错误报告]: 始终无法连接qbittorrent。

### ISSUE THREAD

**Issue by 683599** [jxxghp/MoviePilot#2952]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

新搭建的2.0环境，始终无法连接qbittorrent。

### 发生问题时系统日志和配置文件

```bash
10:44:56,426	
qbittorrent.py
qbittorrent 连接出错：Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded while calling a Python object')
```

**Comment by zzc-tongji** [comment]
遇到了完全一样的问题。

**Comment by zzc-tongji** [comment]
莫名其妙地解决了。

首先去掉qBittorrent里面的安全设置。

![image](https://github.com/user-attachments/assets/38504755-9651-411f-9cff-8170cc879372)

然后重启 qbittorrent，再重启 moviepilot，执行健康度检查（最好用 docker rebuild ）。

多试几次总会成功的（太玄学了）。

**Comment by zzc-tongji** [comment]
希望下载器连接这块能够开启更加详细的日志，以便查找问题。

**Comment by ljkdcc** [comment]
V2.0.2一样问题，去掉安全设置，重启了几遍，还是不行，希望下个版本修复好

**Comment by alifsaputrahakim** [comment]
v2.0.2 出现了一样的问题

**Comment by ljkdcc** [comment]
目前V2.0.3还是出现同样问题

**Comment by alifsaputrahakim** [comment]
> 目前V2.0.3还是出现同样问题

嗯，我升级到2.0.3 还是有这个问题

**Comment by TaoRone** [comment]
同样的问题
我怀疑是qb中的下载文件太多
导致递归超出栈限制
ERROR:   qbittorrent.py - qbittorrent 连接出错：Failed to connect to qBittorrent. Unknown Error: RecursionError('maximum recursion depth exceeded while calling a Python object')

**Comment by alifsaputrahakim** [comment]
找到原因了，看了下qb的日志。mp存在多次重试的情况。 qb默认配置。重试多次失败后。就会禁用登录ip.此时mp会一直登录失败。 需要在qb那边把ip解禁。这也是为什么过一段时间后，有的人就能用了原因

**Comment by ljkdcc** [comment]
补充下，确实是楼上的封禁IP的原因，还有可能是qb设置界面用户名那里会提示填写admin，实际上是空白的，记得填写下

**Comment by yoofa** [comment]
> 补充下，确实是楼上的封禁IP的原因，还有可能是qb设置界面用户名那里会提示填写admin，实际上是空白的，记得填写下

>> PPS
如果还不行, 保证qbittorrent映射的端口号和WEBUI_PORT 一致
我看到下面的log后改成一致解决.

(N) 2024-12-11T17:20:16 - 成功加载了所选语言环境 (zh_CN) 的 WebUI 翻译
(N) 2024-12-11T17:20:16 - Web UI：正在监听 IP：*，端口：8080 
(I) 2024-12-11T17:20:17 - 检测到外部 IP。IP：“117.89.41.223”
(N) 2024-12-11T17:21:51 - WebAPI 登录成功。IP：::ffff:192.168.253.149
(W) 2024-12-11T17:22:24 - WebUI：无效的 Host header，端口不匹配。请求的来源 IP：“::ffff:172.21.0.1”。服务器端口：“8080”。收到的 Host header：“192.168.253.149:41001”
(W) 2024-12-11T17:22:24 - WebUI：无效的 Host header，端口不匹配。请求的来源 IP：“::ffff:172.21.0.1”。服务器端口：“8080”。收到的 Host header：“192.168.253.149:41001”
