### ISSUE TITLE
[错误报告]: v2 目录设置为 “不自动整理” 时，无法获取到下载目录

### ISSUE THREAD

**Issue by AAEE86** [jxxghp/MoviePilot#2963]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.0-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![图片_20241028163825](https://github.com/user-attachments/assets/0267dda5-3eb7-42a5-a941-bceebe1756e6)
目录设置为“不自动整理”，报错未找到下载目录
必须修改“自动整理”然后设置“媒体库目录”才可以识别到下载目录

**Comment by wikrin** [comment]
可以设置`媒体库目录`后再改成`不自动整理`

**Comment by AAEE86** [comment]
> 可以设置`媒体库目录`后再改成`不自动整理`

我觉得可以在设置为```不自动整理```时，也就是媒体库目录不存在时，直接使用下载目录设置为媒体库目录
```
if library_path = not
 download_path = library_path 
```

**Comment by AAEE86** [comment]
> 可以设置`媒体库目录`后再改成`不自动整理`

最近的镜像，按照你说的 设置媒体库目录后再改成不自动整理，依旧不行

![QQ截图20241030094515](https://github.com/user-attachments/assets/021e30a8-30a5-42eb-867e-4b9554e0ddbe)
