### ISSUE TITLE
[错误报告]: 偶发性文件下载完成后不进行整理

### ISSUE THREAD

**Issue by Fangzuzuzu** [jxxghp/MoviePilot#2985]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

偶发性文件下载完成后不进行整理

（订阅番剧时出现。）

### 发生问题时系统日志和配置文件

```bash
为未发现整理时会产生的记录。仅有下载种子记录。

（同时还有偶尔出现的电影文件硬链接了，但是没有生成刮削文件的情况，手动整理之后正常）

（同时搜索结果展示目前没找到在哪默认根据条件顺序排序，只能转换成列表模式后选择规则。
并且，手机端无法选择侧边规则栏）
```

**Comment by Fangzuzuzu** [comment]
目录监控报错：Inotify watch limit reached

**Comment by mjsoftking** [comment]
可能和这个配置有关：目录监控不自动整理文件
https://wiki.movie-pilot.org/zh/troubleshooting

**Comment by Fangzuzuzu** [comment]
> 可能和这个配置有关：目录监控不自动整理文件
> https://wiki.movie-pilot.org/zh/troubleshooting

目前解决方案是：echo fs.inotify.max_user_watches=5242880 | sudo tee -a /etc/sysctl.conf
echo fs.inotify.max_user_instances=5242880 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

在宿主机输入这个命令，但是这个bug在v1版本好像是修复过的吧

**Comment by rehack** [comment]
我的媒体目录是NFS挂载的，请问需要在宿主机进行如下修改吗？
``` bash
echo fs.inotify.max_user_watches=5242880 | sudo tee -a /etc/sysctl.conf
echo fs.inotify.max_user_instances=5242880 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```
