### ISSUE TITLE
[错误报告]: 设定的下载目录无法生效

### ISSUE THREAD

**Issue by AlexFastAll** [jxxghp/MoviePilot#2987]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.0-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

配置了下载目录， 但是不能够生效
比如配置了下载目录 /vo1/data/download/tv 但是还是下载到/Downloads/国产剧

**Comment by cng10001** [comment]
如果不确定是软件问题的话，最好把docker配置和mp的目录配置发出来让大家看看

**Comment by ethan522** [comment]
是用qbittorrent下载的吧？我也遇到了同样的问题，感觉是由于qbittorrent里设置了根据分类自动分配下载路径导致的，而且感觉mp里设置的下载目录如果和实际目录对不上，文件整理也无法正常工作。
