### ISSUE TITLE
[错误报告]: 搜索中文感叹号电影时搜索不出来

### ISSUE THREAD

**Issue by DDSDerek** [jxxghp/MoviePilot#299]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.8

### 问题类型

主程序运行问题

### 问题描述

搜索默认用的是英文的感叹号，在搜索中文感叹号电影时会搜索不出来。
比如说《我爱你！》这个电影就是中文感叹号，导致搜索不出来
测试天空和馒头都有问题

**Comment by cng10001** [comment]
额，其实这个不算mp的问题吧，应该是有的站点搜索引擎问题，不支持一些字符，我试了下ob  ptclub是好的
