### ISSUE TITLE
[错误报告]: 插件中的短剧自动分类不生效，且插件无日志生成

### ISSUE THREAD

**Issue by LongShengWen** [jxxghp/MoviePilot#2990]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.0-beta

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

插件中的短剧自动分类不生效，且插件无日志生成，小于设置时长的短剧还是会分类到电视剧

**Comment by cng10001** [comment]
也许还没适配v2版本呢?!
