### ISSUE TITLE
[错误报告]: V2版本媒体服务器 配置同步媒体库时 只能选择部分媒体库

### ISSUE THREAD

**Issue by AceCandy** [jxxghp/MoviePilot#3005]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V2.0.0-beta

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

通过 设定 → 连接 → 媒体服务器 中配置emby服务的 同步媒体库 时，发现17个媒体库只能选择其中11个，F12查看mp调用的接口返回时就只返回了11个，不清楚时哪块的问题
<img width="687" alt="image" src="https://github.com/user-attachments/assets/256604d7-33c9-4d67-b040-8954c5680a78">

**Comment by Nelson-Wcg** [comment]
v2.0.1这个bug还在

**Comment by AceCandy** [comment]
2.0.2依旧有，希望这个能修复下

**Comment by Nelson-Wcg** [comment]
这个问题解决了？ @AceCandy 你的好了吗

**Comment by AceCandy** [comment]
> 这个问题解决了？ @AceCandy 你的好了吗

之前没有 但是前段时间我大概猜到问题了  应该是有混合库识别出错了到时候混合库之后的库也都识别不了  所以我暂时把库改成了电影/电视剧库就能正常识别到  后来就没关注了

**Comment by Nelson-Wcg** [comment]
补充一下我的问题和解决方法
问题原因：MoviePilot会查询emby所有的用户，然后用查询到的名为admin的用户或者第一个拥有管理员权限的用户去查询媒体库信息，我的emby没有admin用户，又正好设置了一个拥有管理权限但没有媒体库权限的用户，最终造成了数据查询缺失
解决方法：去掉这个用户的管理权限 或者给这个用户所有的媒体库访问权限 或者创建一个名为admin有所有媒体库权限的用户

**Comment by rosystain** [comment]
> 补充一下我的问题和解决方法 问题原因：MoviePilot会查询emby所有的用户，然后用查询到的名为admin的用户或者第一个拥有管理员权限的用户去查询媒体库信息，我的emby没有admin用户，又正好设置了一个拥有管理权限但没有媒体库权限的用户，最终造成了数据查询缺失 解决方法：去掉这个用户的管理权限 或者给这个用户所有的媒体库访问权限 或者创建一个名为admin有所有媒体库权限的用户

我也遇到了这个问题，Emby 没有向 Moviepilot 返回对管理员用户隐藏的媒体库，同时 Moviepilot 也无法主动选择其他管理员。把默认被查询的用户的管理员权限取消后解决了。
