### ISSUE TITLE
[错误报告]: V2搜索资源推送到下载器显示添加任务失败（突然又好了，请忽略）

### ISSUE THREAD

**Issue by dvdrm** [jxxghp/MoviePilot#3006]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

V2搜索资源推送到下载器显示添加任务失败，相同配置V1正常。

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-11-05 20:57:35,542 - user.py - 用户 admin 通过密码认证成功
【ERROR】2024-11-05 20:57:52,171 - download.py - 牧神记 (2024) 添加下载任务失败：Tales of Qin Mu S01E01~03 2024 2160p WEB-DL AVC AAC 2.0-HDKWeb - https://hdfans.org/download.php?id=124114，无法连接qbittorrent下载器
【INFO】2024-11-05 20:57:52,172 - chain - 发送消息：channel=None，source=None,title=添加下载任务失败：牧神记 (2024) S01 E01-E03, text=站点：红豆饭
种子名称：Tales of Qin Mu S01E01~03 2024 2160p WEB-DL AVC AAC 2.0-HDKWeb
错误信息：无法连接qbittorrent下载器，userid=None
```

**Comment by cng10001** [comment]
地址是不是多空格了
