### ISSUE TITLE
[Feature Request]: 关于文件识别的逻辑问题

### ISSUE THREAD

**Issue by lsc272** [jxxghp/MoviePilot#3008]
### 当前程序版本

v2.0.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

https://github.com/jxxghp/MoviePilot/blob/ec183b6d0dcdf240d458e00d6479ca6e01cfd151/app/core/meta/metavideo.py#L34

上述代码中，UHD和REMUX都不算是视频的特效部分，都是属于source的范畴，使用{{resourceType}}{{videoFormat}}{{effect}}这种格式进行重命名的时候，就会出现识别不规范的情况。
例如：DogMan.2023.UHD.BluRay.2160p.REMUX.HEVC.DoVi.HDR.TrueHD7.1
就会识别成：狗神 (2023) BluRay 2160p HDR DoVi REMUX UHD HEVC TrueHD 7.1
规范的名称应该是：狗神 (2023) UHD BluRay REMUX 2160p HDR DoVi HEVC TrueHD 7.1
其中，只有HDR DoVi才算是{{effect}}，UHD BluRay REMUX这整个都算是{{resourceType}}

将33行的代码改成如下格式是否可行？
`_source_re = r"^UHD$| ^BLURAY$| ^REMUX$| ^HDTV$|^UHDTV$|^HDDVD$|^WEBRIP$|^DVDRIP$|^BDRIP$|^BLU$|^WEB$|^BD$|^HDRip$" `

![20241105235950](https://github.com/user-attachments/assets/f6d3733a-8760-43c9-9a70-29271be03e66)

**Comment by lsc272** [comment]
https://github.com/jxxghp/MoviePilot/blob/87bbee8c36ed879ced9580a477f8eb1a2e1bd6f7/app/core/meta/metavideo.py#L33

@jxxghp 更新到最新的2.0.2版本后，UHD和Remux不识别了，是否是因为_source_re的值具有唯一性，匹配到BlueRay后，就不匹配UHD和Remux了，另外这行代码改成下面这个格式感觉更合适一点：

`_source_re = r"^UHD$|^BLURAY$|^REMUX$|^HDTV$|^UHDTV$|^HDDVD$|^WEBRIP$|^DVDRIP$|^BDRIP$|^BLU$|^WEB$|^BD$|^HDRip$|^REPACK$"`

**Comment by lsc272** [comment]
上述例子中，
文件名：
DogMan.2023.UHD.BluRay.2160p.REMUX.HEVC.DoVi.HDR.TrueHD7.1
会被识别成：
狗神 (2023) UHD 2160p HDR DoVi HEVC TrueHD 7.1.mkv

**Comment by hwt1997215** [comment]
UHD BluRay和BluRay才属于source吧，单独的UHD命名可以直接当作UHD BluRay处理。REMUX、REPACK识别成特效部分是合理的
