### ISSUE TITLE
v2版本rclone上传问题

### ISSUE THREAD

**Issue by 0oo000** [jxxghp/MoviePilot#3013]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

v2版本填写好rclone挂载后可以正常识别，但是整理上传文件时 mp:/电影/a 会识别位：mp:/电影a而且上传到网盘也是：电影a

**Comment by 4Nest** [comment]
目录设置中也可以复现
应该是/Anime/日番
变成了/Anime日番
![image](https://github.com/user-attachments/assets/8a226817-99ea-4328-838d-85e6e4642f94)
