### ISSUE TITLE
[Feature Request]: 规则增加一个排除自定义的关键词功能

### ISSUE THREAD

**Issue by leo8912** [jxxghp/MoviePilot#302]
### 当前程序版本

1.0.8

### 功能改进

emby tv端无法播放60fps的高帧率视频。
能否在规则处增加一个自定义关键词，这样可以按自己需求屏蔽了。。

**Comment by hbq0405** [comment]
你可以利用词表里的自定义识别词来达到目的，例如你本身过滤规则排除了杜比视界，那么你就可以加一条替换规则
60fps => 杜比视界
这样可以达到同样的效果

**Comment by loveu5522** [comment]
是的，emby TV端播放不了60帧的，解决办法要么用jellyfin 要么plex都可以

**Comment by leo8912** [comment]
> 你可以利用词表里的自定义识别词来达到目的，例如你本身过滤规则排除了杜比视界，那么你就可以加一条替换规则 60fps => 杜比视界 这样可以达到同样的效果

好思路

**Comment by leo8912** [comment]
> 你可以利用词表里的自定义识别词来达到目的，例如你本身过滤规则排除了杜比视界，那么你就可以加一条替换规则 60fps => 杜比视界 这样可以达到同样的效果

但是好像订阅不走词表的自定义识别词。。。
![image](https://github.com/jxxghp/MoviePilot/assets/22719866/b4b0b946-9b93-4619-89eb-8a7c38e9d24e)

**Comment by evolsnow** [comment]
求支持订阅也走词表的自定义识别词。
使用场景：
- 默认过滤规则过滤了60fps、HQ等
- 电视剧订阅时如果有4k选择4k

这样就导致配置了分辨率的订阅，不再使用默认过滤规则，需要手动再填入60fps、HQ的过滤

设想的解决方案：
1. 订阅走自定义识别词，然后60fps=>DV, HQ=>DV这种骚操作
2. 支持全局自定义过滤规则（即merge全局+单电视剧的规则）
