### ISSUE TITLE
[错误报告]: 文件管理中手动重命名无效

### ISSUE THREAD

**Issue by yfdoor** [jxxghp/MoviePilot#3050]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

文件管理中手动重命名，可以识别出正确的名字，但是点击确定后，无法生效，且log 中没有错误记录
![image](https://github.com/user-attachments/assets/f9c7e3c1-cf88-4453-bd03-88d7ae55e572)

![image](https://github.com/user-attachments/assets/ca5920cd-b041-411d-b8dd-4d94b4a8d348)

**Comment by heartacker** [comment]
不知道是否已经有发布，我也遇到同样的问题，知道是权限问题还是需要升级版本
```
2024/11/12 13:16:49  [32mINFO[0m:     172.16.0.22:0 - "[1mGET /api/v1/system/message HTTP/1.1[0m" [32m200 OK[0m
2024/11/12 13:16:31  [32mINFO[0m:     172.16.0.22:0 - "[1mPOST /api/v1/storage/list?sort=name HTTP/1.1[0m" [32m200 OK[0m
2024/11/12 13:16:26  [32mINFO[0m:     172.16.0.22:0 - "[1mPOST /api/v1/storage/list?sort=name HTTP/1.1[0m" [32m200 OK[0m
2024/11/12 13:16:26  [32mINFO[0m:     172.16.0.22:0 - "[1mPOST /api/v1/storage/rename?new_name=%E6%B5%B7%E5%BA%95%E6%80%BB%E5%8A%A8%E5%91%983D HTTP/1.1[0m" [32m200 OK[0m
2024/11/12 13:16:14  [32mINFO[0m:     172.16.0.22:0 - "[1mGET /api/v1/media/recognize_file?path=%2FPT%2FMovies%2F3D%2F[3D%E7%94%B5%E5%BD%B1][k3d.cn][%E5%AE%8C%E7%BE%8E%E4%B8%AD%E5%AD%97]%E6%B5%B7%E5%BA%95%E6%80%BB%E5%8A%A8%E5%91%983D.mkv%2F HTTP/1.1[0m" [32m200 OK[0m
```
