### ISSUE TITLE
[Feature Request]: 希望v2版本可以单独设置媒体库目录

### ISSUE THREAD

**Issue by Mister-album** [jxxghp/MoviePilot#3060]
### 当前程序版本

v2.0.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

目前下载目录与媒体库目录进行了绑定，需要设置下载目录并开启目录监控或者下载器监控才可以设置媒体库目录，这样设置起来不太灵活，某些情况下只需要媒体库目录就可以进行一些操作，比如手动整理
应该不少人是只使用mp的手动整理功能的，手动下载后使用mp来整理，目前v2版本卡在了媒体库目录这边

不过我也试过不设置下载目录，然后设置成目录监控或者下载器监控，再指定媒体库目录，但那样手动整理会提示未找到有效的媒体库目录，不清楚是bug还是一定要设置下载目录才能使媒体库目录生效的问题了

**Comment by heartacker** [comment]
同样的需求
