### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by 18722890332** [jxxghp/MoviePilot#3066]
### 当前程序版本

V1 V2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

建议增加根据大小进行订阅的规则，比如最大g，最小g

**Comment by cng10001** [comment]
![image](https://github.com/user-attachments/assets/e229458d-100d-4938-bdb7-ba133b5fae2d)
v2版这个应该可以实现吧

**Comment by 18722890332** [comment]
不是，我也的意思是，比如春花焰32集，有1g/集，3g/集，10g/集，在不考虑杜比60fps这些特效帧率方面的问题，让规则去实现订阅最大的资源（10g/集）
