### ISSUE TITLE
[错误报告]: v2版本插件没有日志

### ISSUE THREAD

**Issue by Devinaille** [jxxghp/MoviePilot#3076]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

插件执行网页上看不到日志，看文件有很多插件日志（我没有安装的也有），但大小都是0

**Comment by Devinaille** [comment]
需要关掉compose里stdin_open和tty配置，建议修改安装指引的默认配置

**Comment by zhaiyaa** [comment]
同样的问题，大佬能说详细点吗？或者哪里有资料，萌新一枚
