### ISSUE TITLE
[错误报告]: 电视剧订阅重复下载媒体库中已存在的剧集

### ISSUE THREAD

**Issue by yotsubar** [jxxghp/MoviePilot#308]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.8

### 问题类型

主程序运行问题

### 问题描述

呃，在编辑issue的过程中，想截个图，却发现订阅进度又显示正确了...但中间确实存在过问题，可能是编辑订阅后还没有同步媒体库就开始订阅搜索了，也有可能是其他问题。

早期版本使用没有问题，1-5是手动下载，6-8是nt订阅，9-11集是mp订阅下载的。中间某个版本升级后，显示的订阅进度就跟实际不符，从11/14变成7/14，而且重复添加了两集下载。因为早期的下载已经转移到tr里边，qb里的新订阅下载都是同一种子报错了，没有实际下载，当时就没有管他。今天发现订阅进度还是7/14，取消订阅后重新订阅，进度变成0/14了，上午又重复下载了很多集。订阅配置中没有开启洗版。现在是手动设置开始集数来处理这个问题。
查了一下，11集是2023-08-26 02:07:25订阅下载的，到2023-08-26 13:46:52又下载了一遍，应该是这个时间附近开始有的问题。

### 发生问题时系统日志和配置文件

【INFO】2023-08-28 11:00:47,025 - __init__.py - 密室大逃脱 使用识别缓存：密室大逃脱
【INFO】2023-08-28 11:00:47,025 - tmdbapi.py - 正在查询TMDB电视剧：89861 ...
【INFO】2023-08-28 11:00:47,025 - tmdbapi.py - 89861 查询结果：密室大逃脱
【INFO】2023-08-28 11:00:47,026 - __init__.py - 密室大逃脱 识别结果：电视剧 密室大逃脱 (2019) 89861
【INFO】2023-08-28 11:00:47,033 - __init__.py - 密室大逃脱 (2019) 媒体库中已存在：{5: [2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11]}
【INFO】2023-08-28 11:00:47,033 - subscribe.py - 订阅 密室大逃脱 (2019) S05 缺失集：[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
【INFO】2023-08-28 11:00:47,033 - search.py - 开始搜索资源，关键词：密室大逃脱 ...

**Comment by HamBosco** [comment]
我也有同样的问题。而且如我之前[issue](https://github.com/jxxghp/MoviePilot/issues/270)说的，设置了21集开始，但是刚才依旧是下载了之前的1-5集。这个任务已经下了4次了……
<img width="511" alt="Screen Shot 2023-08-28 at 12 31 36 AM" src="https://github.com/jxxghp/MoviePilot/assets/139821230/d1e0506f-1462-49b0-9d4e-c58778bfc5b8">
<img width="1045" alt="Screen Shot 2023-08-28 at 12 32 06 AM" src="https://github.com/jxxghp/MoviePilot/assets/139821230/514677dd-b491-4a69-9a5c-06c01974f74a">
