### ISSUE TITLE
[错误报告]: 目录手动刮削电视剧，会把封面等信息刮到 电视剧/ 这个顶级目录下。

### ISSUE THREAD

**Issue by zyt0339** [jxxghp/MoviePilot#3081]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

目录手动刮削电视剧，会把封面等信息刮到 电视剧/ 这个顶级目录下。 之前这个功能是好的
我发现是我刮了个 140 集的电视剧，记录显示都刮成功了，我去文件夹看毛都没有。好嘛，全刮到电视剧/下了，第二集的封面覆盖了第一集，最终只留了第 140 集的封面在那。。。
![image](https://github.com/user-attachments/assets/3ad2eb69-5aa1-4a0a-8105-e7699e9f6d8a)

### 发生问题时系统日志和配置文件

```bash
如上方截图
```

**Comment by wikrin** [comment]
#3254 已修复
