### ISSUE TITLE
[错误报告]: 自定义规则疑似未生效  ？？

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#3086]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

[{"id":"RULE1","name":"排除只有 DV 而没有 HDR","include":"(HDR|DV.*HDR|HDR.*DV)","exclude":"(DV(?!.*HDR)|120[fF][pP][sS])"}] 

同时我反复尝试了以下3种正则组合 ，均未成功，不排除我和gpt的正则水平不过关的可能。

[{"id":"RULE1","name":"排除只有 DV 而没有 HDR","include":"(HDR|DV.*HDR|HDR.*DV)","exclude":"(DV(?!.*HDR)|120[fF][pP][sS])"},{"id":"RULE2","name":"规则2","include":"(HDR|DV.*HDR|HDR.*DV)","exclude":"DV(?!.*HDR)"},
{"id":"RULE3","name":"规则3","include":"(HDR|DV.*HDR|HDR.*DV)","exclude":"(?i)(DV(?!.*HDR)|120fps)"}]

这是我的规则，我的本意是排除只有DV的文件，只留下HDR或者 HDR DV 组合的文件，用GPT 帮忙写的正则。

Arcane S02E01-E03 2024 2160p WEB-DL H265 10bit DV DDP5.1 Atmos 2Audio-OurTV 理论上这个文件名应该会被排除掉，实际搜索结果中呈现了。 

### 发生问题时系统日志和配置文件

```bash
【INFO】2024-11-13 23:19:29,076 - torrent.py - 英雄联盟：双城之战 通过标题匹配到资源：我堡 - Arcane S02E01-E03 2024 2160p WEB-DL H265 10bit DV DDP5.1 Atmos 2Audio-OurTV
【INFO】2024-11-13 23:19:29,026 - torrent.py - 英雄联盟：双城之战 通过标题匹配到资源：我堡 - Arcane S01 REPACK 2160p BluRay TrueHD 5.1 DV HDR10 x265-MainFrame
【INFO】2024-11-13 23:19:28,969 - search.py - 开始匹配结果 标题：英雄联盟：双城之战，原标题：Arcane，别名：['آركين', 'Arcane - League of Legends (2021)', 'არკეინი', '奧術', 'アーケイン', 'Аркейн: League of Legends', 'Arcane', 'Arcane: League of Legends', '아케인', 'Аркейн', '英雄联盟：双城之战', 'ארקיין', 'Аркејн', 'อาร์เคน: ตำนานลีกออฟเลเจ็นดส์', 'Arkayn', 'آرکین: لیگ افسانه\u200cها', 'არკანი']
【INFO】2024-11-13 23:19:28,968 - search.py - 过滤规则/剧集过滤完成，剩余 177 个资源
【INFO】2024-11-13 23:19:21,750 - filter - 加载自定义规则 RULE1 - 排除只有 DV 而没有 HDR
【INFO】2024-11-13 23:19:21,748 - search.py - 开始过滤规则/剧集过滤，使用规则组：['gpt - 搜索 '] ...
```

**Comment by cng10001** [comment]
自己写了吗，dv和hdr选项内置可以勾选的啊

**Comment by paysenyu** [comment]
> 自己写了吗，dv和hdr选项内置可以勾选的啊

我想的效果是，仅排除DV的，  但是现在有很多资源，它是DV + HDR 自适应的，这种我也不希望排除。。。 因为这种资源emby可以正常播放，emby不能放的是仅DV的。。

所以自带的勾选如果勾了排除DV，那么 DV&HDR 也会被杀掉

**Comment by cng10001** [comment]
那你优先级选择一个hdr啊

**Comment by cng10001** [comment]
![Screenshot_2024-11-14-12-09-34-763_com android chrome](https://github.com/user-attachments/assets/5bbddc0f-b764-47df-80bd-463191b68967)
类似这样排除dv最为优先级最低的兜底 dv和hdr都不会匹配到，但是普通264、265不受影响
上一级优先级的hdr，如果资源是单hdr或者，hdr+dv 都符合你要求

**Comment by paysenyu** [comment]
> ![Screenshot_2024-11-14-12-09-34-763_com android chrome](https://private-user-images.githubusercontent.com/115156545/386040626-5bbddc0f-b764-47df-80bd-463191b68967.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTgxNDAsIm5iZiI6MTczMTU1Nzg0MCwicGF0aCI6Ii8xMTUxNTY1NDUvMzg2MDQwNjI2LTViYmRkYzBmLWI3NjQtNDdkZi04MGJkLTQ2MzE5MWI2ODk2Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNDE3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTQzMDU0NTAzZTdhMmM0OGFjNzVhN2Q5MjZiYTMwZGI0YzhhMTgxNmZkN2U2NzFiMTgwOTgyNWU1ZGE4MDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rx0_87Bvd99fgpIzA_Ky6UY411IjMKr06l2M5k5Llu0) 类似这样排除dv为优先级最低的兜底 dv肯定不会匹配到，但是普通264、265不受影响 上一级优先级的hdr，如果资源是单hdr或者，hdr+dv 都符合你要求
> 
> 图上优先级互换也可以

<img width="1746" alt="image" src="https://github.com/user-attachments/assets/a27603ed-de85-4cf1-a63e-ae1a4999db6a">

这是我的优先级设定，这是实际搜索的排序。。

<img width="1781" alt="image" src="https://github.com/user-attachments/assets/bd47e2cf-bc03-49a6-b8a0-9857a25ccd9c">

依旧是DV 拍在第一。。。。

**Comment by paysenyu** [comment]
同时我这个过滤规则似乎没有把种子排在第一，也有点问题？

 CNSUB & !REMUX & !BLU & 4K & HDR & H265 & WEB-DL > CNSUB & !REMUX & !BLU & 4K & HDR & H264 & WEB-DL > CNSUB & !REMUX & !BLU & 4K & HDR & H265 & UHD > CNSUB & !REMUX & !BLU & 4K & HDR & H264 & UHD > CNSUB & !REMUX & !BLU & 4K & H265 & WEB-DL > CNSUB & !REMUX & !BLU & 4K & H264 & WEB-DL > CNSUB & !REMUX & !BLU & 4K & H265 & UHD > CNSUB & !REMUX & !BLU & 4K & H264 & UHD > CNSUB & !REMUX & !BLU & 1080P & HDR & H265 & WEB-DL > CNSUB & !REMUX & !BLU & 1080P & HDR & H264 & WEB-DL > CNSUB & !REMUX & !BLU & 1080P & HDR & H265 & UHD > CNSUB & !REMUX & !BLU & 1080P & HDR & H264 & UHD > CNSUB & !REMUX & !BLU & 1080P & H265 & WEB-DL > CNSUB & !REMUX & !BLU & 1080P & H264 & WEB-DL > CNSUB & !REMUX & !BLU & 1080P & H265 & UHD > CNSUB & !REMUX & !BLU & 1080P & H264 & UHD > CNSUB & !REMUX & !BLU & 4K > CNSUB & !REMUX & !BLU & 1080P
 > !BLU & !REMUX 

理论上标题  Arcane S02E01-E03 2024 2160p WEB-DL H265 10bit HDR DDP5.1 Atmos 2Audio-OurTV
副标题 腾讯版 | 英雄联盟：双城之战 / 奥肯 / 奥术 第二季 / 英雄联盟：双城之战最终季 第01-03集 | 类型: 剧情 / 动作 / 科幻 / 动画 / 奇幻 / 冒险 | [国英双语/内嵌简中/4K/HDR Vivid/杜比全景声] 

应该是匹配第一优先级，结果显示匹配到了第17优先级。。
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/22958ee0-1868-44ff-ae71-7bc83b8892fa">
<img width="585" alt="image" src="https://github.com/user-attachments/assets/9efc8c1f-1109-4b15-942c-d531c272675f">
