### ISSUE TITLE
站点索引报错

### ISSUE THREAD

**Issue by mizb** [jxxghp/MoviePilot#3090]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.03

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

时间不定时，有时候间隔差不多1小时报错一次。不影响正常使用

### 发生问题时系统日志和配置文件

```bash
【ERROR】2024-11-14 01:40:20,100 - chain - 运行模块 IndexerModule.refresh_userdata 出错：Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 112, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/indexer/__init__.py", line 258, in refresh_userdata
    site_obj.parse()
  File "/app/app/modules/indexer/parser/__init__.py", line 177, in parse
    self._parse_user_detail_info(
  File "/app/app/modules/indexer/parser/tnode.py", line 39, in _parse_user_detail_info
    detail = json.loads(html_text)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jinghua625** [comment]
【ERROR】2025-03-16 11:00:48,948 - chain - 运行模块 IndexerModule.refresh_userdata 出错：Expecting value: line 1 column 1 (char 0)
20549 Traceback (most recent call last): 
20550   File "/app/app/chain/__init__.py", line 115, in run_module 
20551     result = func(*args, **kwargs)
20552              ^^^^^^^^^^^^^^^^^^^^^ 
20553   File "/app/app/modules/indexer/__init__.py", line 286, in refresh_userdata
20554     site_obj.parse()
20555   File "/app/app/modules/indexer/parser/__init__.py", line 205, in parse
20556     self._parse_seeding_pages()
20557   File "/app/app/modules/indexer/parser/__init__.py", line 258, in _parse_seeding_pages
20558     next_page = self._parse_user_torrent_seeding_info(
20559                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
20560   File "/app/app/modules/indexer/parser/tnode.py", line 66, in _parse_user_torrent_seeding_info
20561     seeding_info = json.loads(html_text)
20562                    ^^^^^^^^^^^^^^^^^^^^^
20563   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
20564     return _default_decoder.decode(s)
20565            ^^^^^^^^^^^^^^^^^^^^^^^^^^
20566   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode 
20567     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
20568                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
20569   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
20570     raise JSONDecodeError("Expecting value", s, err.value) from None
20571 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

每隔几个小时还会偶尔遇到
