### ISSUE TITLE
[错误报告]: 历史记录中对错误动漫执行重新整理报错，未找到有效的媒体库目录

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#3093]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.3

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

如图，定义的目录结构如下
![longshot20241114134451](https://github.com/user-attachments/assets/604faea5-98ae-4023-8b51-c8aa8e392fd7)
对该条记录进行重新整理，不做任何参数变化
![longshot20241114134517](https://github.com/user-attachments/assets/5bdaa022-571c-406e-9f36-4ddaf6de9255)
![longshot20241114134510](https://github.com/user-attachments/assets/3e540e2e-54b1-46d7-a7f5-3206b1bc7c7d)
会报错
![longshot20241114134529](https://github.com/user-attachments/assets/5535a835-1acd-4405-83a9-b6886504e4aa)

### 发生问题时系统日志和配置文件

```bash
INFO:    transfer.py - 手动整理：/media/downloads/诛仙.Jade.Dynasty.S01.2022.2160p.WEB-DL.H265.AAC-HHWEB/诛仙.Jade.Dynasty.S01E52.2022.2160p.WEB-DL.H265.AAC-HHWEB.mp4 ...
INFO:    transfer.py - 正在整理 1 个文件...
INFO:    themoviedb - 诛仙 使用TMDB识别缓存：诛仙
INFO:    themoviedb - 诛仙 TMDB识别结果：电视剧 诛仙 (2022) 206484
INFO:    media.py - 诛仙.Jade.Dynasty.S01E52.2022.2160p.WEB-DL.H265.AAC-HHWEB.mp4 识别到媒体信息：电视剧 诛仙 (2022)
WARNING: fanart - 没有获取到 诛仙 (2022) 的fanart图片数据
INFO:    transfer.py - 诛仙.Jade.Dynasty.S01E52.2022.2160p.WEB-DL.H265.AAC-HHWEB.mp4 识别为：电视剧 诛仙 (2022)
ERROR:   filemanager - 电视剧 诛仙 (2022) 未找到有效的媒体库目录，无法整理文件，源路径：/media/downloads/诛仙.Jade.Dynasty.S01.2022.2160p.WEB-DL.H265.AAC-HHWEB/诛仙.Jade.Dynasty.S01E52.2022.2160p.WEB-DL.H265.AAC-HHWEB.mp4
WARNING: transfer.py - 诛仙.Jade.Dynasty.S01E52.2022.2160p.WEB-DL.H265.AAC-HHWEB.mp4 入库失败：未找到有效的媒体库目录
INFO:    chain - 发送消息：channel=None，source=None,title=诛仙 (2022) S01 E52 入库失败！, text=原因：未找到有效的媒体库目录，userid=None
```

**Comment by yellowstrong** [comment]
手动指定目的路径为动漫路径时，不会报错，但是不做任何变动的情况下重新整理就会报错

**Comment by yellowstrong** [comment]
如果整理时指定类型为电视剧并根据电视剧名称搜索出tmdbID填入编号，再进行整理，可成功整理

**Comment by LongShengWen** [comment]
同样的问题

**Comment by hunksone** [comment]
同样的问题，必须指定类型才能成功
