### ISSUE TITLE
[错误报告]: 媒体文件同步删除插件无法联动删除源文件 

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#3104]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

mpv2的 文件管理 - 手动定位曾经下载过的文件 - 整理

此时在历史记录中生成了对应的搜刮记录， 有源文件路径及媒体库路径

emby中该文件已正常入库 - emby中操作删除

媒体文件同步删除插件发送通知已删除文件和种子

实际情况是源文件和种子均未被删除。  历史记录和媒体库文件已经被删除。

ps:
1、如果手动从“历史记录“ 中操作 ”删除历史记录、源文件和媒体库文件“ 那么源文件是会被删除的
2、从mpv2 全新下载一个资源，然后emby联动删除源文件，是正常删除的。

目前我这边仅限于手动整理的文件，以及v1迁移到v2的文件，源文件不会被联动删除。  但日志里显示为已删除

源文件的权限已经检查过，是nobody rw rw rw  应该是没问题的

按个人目前的排除法，似乎可能问题出在 “请求模块执行：delete_file ... ” 这一步里面 关于源文件？

### 发生问题时系统日志和配置文件

```bash
【DEBUG】2024-11-15 11:16:54,756 - tmdbapi.py - 1019828 查询结果：默杀：无声之地
【DEBUG】2024-11-15 11:16:54,755 - tmdbapi.py - 正在查询TMDB电影：1019828 ...
【DEBUG】2024-11-15 11:16:54,753 - chain - 请求模块执行：obtain_specific_image ...
【DEBUG】2024-11-15 11:16:54,505 - tmdbapi.py - 1019828 查询结果：默杀：无声之地
【DEBUG】2024-11-15 11:16:54,505 - tmdbapi.py - 正在查询TMDB电影：1019828 ...
【DEBUG】2024-11-15 11:16:54,504 - chain - 请求模块执行：obtain_specific_image ...
【INFO】2024-11-15 11:16:54,503 - mediasyncdel - 同步删除 电影 默杀：无声之地 1019828 完成！
【INFO】2024-11-15 11:16:54,503 - mediasyncdel - 查询到 0b51adf935edfaef144cb1524943739746ffafe7 辅种历史 []
【DEBUG】2024-11-15 11:16:54,501 - chain - 请求模块执行：remove_torrents ...
【INFO】2024-11-15 11:16:54,500 - mediasyncdel - 删除源下载器下载任务：qb - 0b51adf935edfaef144cb1524943739746ffafe7
【INFO】2024-11-15 11:16:54,500 - mediasyncdel - 查询种子任务 0b51adf935edfaef144cb1524943739746ffafe7 文件已全部删除，执行删除种子操作
【INFO】2024-11-15 11:16:54,498 - mediasyncdel - 查询到 qb-0b51adf935edfaef144cb1524943739746ffafe7 转种历史 None
【DEBUG】2024-11-15 11:16:54,497 - chain - 请求模块执行：delete_file ...
【INFO】2024-11-15 11:16:54,476 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-11-15 11:16:54,475 - mediasyncdel - 正在同步删除电影 默杀：无声之地 1019828
```

**Comment by thsrite** [comment]
@paysenyu 想办法把v1的数据库里的downloadfiles表数据同步到v2 或者用下载器文件同步重新同步

**Comment by paysenyu** [comment]
> @paysenyu 想办法把v1的数据库里的downloadfiles表数据同步到v2 或者用下载器文件同步重新同步

下载器文件同步重新同步  我是用了的，而且一直定时在跑的。

【INFO】2024-11-13 06:05:42,139 - syncdownloadfiles - 下载器任务文件记录已同步完成。总耗时 0 秒
【INFO】2024-11-13 06:05:42,115 - syncdownloadfiles - 下载器种子文件同步完成！
【INFO】2024-11-13 06:05:42,114 - syncdownloadfiles - 最后同步时间2024-11-12 22:29:06, 之前种子已被同步，结束当前下载器 tr 任务
【INFO】2024-11-13 06:05:42,114 - syncdownloadfiles - 下载器 tr 去除辅种，获取到源种子数：1567
【INFO】2024-11-13 06:05:42,107 - syncdownloadfiles - 下载器 tr 已完成种子数：3936
【INFO】2024-11-13 06:05:41,524 - syncdownloadfiles - 开始扫描下载器 tr ...
【INFO】2024-11-13 06:05:41,506 - syncdownloadfiles - 开始同步下载器任务文件记录


所以我手动整理的文件删除的时候，日志里面是有记录种子任务相关 “【INFO】2024-11-15 11:16:54,500 - mediasyncdel - 查询种子任务 0b51adf935edfaef144cb1524943739746ffafe7 文件已全部删除，执行删除种子操作” 

我去文件管理里面手动整理的文件，理论上应该是不会在插件日志里面有记录种子相关信息的吧

**Comment by thsrite** [comment]
同步删除更新1.8.5再试下

**Comment by paysenyu** [comment]
> 同步删除更新1.8.5再试下

非常感谢，更新完之后就成功了。。 


【INFO】2024-11-15 13:09:23,452 - mediasyncdel - 同步删除 电影 默杀 1300945 完成！
【INFO】2024-11-15 13:09:23,452 - mediasyncdel - 查询到 f58b0adea6b9147765656272b443609501f031e8 辅种历史 []
【INFO】2024-11-15 13:09:23,448 - mediasyncdel - 删除源下载器下载任务：qb - f58b0adea6b9147765656272b443609501f031e8
【INFO】2024-11-15 13:09:23,448 - mediasyncdel - 查询种子任务 f58b0adea6b9147765656272b443609501f031e8 文件已全部删除，执行删除种子操作
【INFO】2024-11-15 13:09:23,445 - mediasyncdel - 查询到 qb-f58b0adea6b9147765656272b443609501f031e8 转种历史 None
【INFO】2024-11-15 13:09:23,443 - mediasyncdel - 开始删除源文件 /Media/downloads/movie/华语电影/默杀.A.Place.Called.Silence.2024.2160p.WEB-DL.H265.DDP2.0-ADWeb/默杀.A.Place.Called.Silence.2024.2160p.WEB-DL.H265.DDP2.0-ADWeb.mkv
【INFO】2024-11-15 13:09:23,430 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-11-15 13:09:23,430 - mediasyncdel - 正在同步删除电影 默杀 1300945

另外有一个非常非常小的问题，就是源文件删除之后，目录"默杀.A.Place.Called.Silence.2024.2160p.WEB-DL.H265.DDP2.0-ADWeb" 还会保留，如果可以的话，目录也删掉最好了。。

**Comment by thsrite** [comment]
更新1.8.6

**Comment by paysenyu** [comment]
> 更新1.8.6

再次感谢，一切运行都完美了
