### ISSUE TITLE
[错误报告]: Webhook插件在v2版本没有生效

### ISSUE THREAD

**Issue by chenvd** [jxxghp/MoviePilot#3108]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.4

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

在V2版本中，Webhook插件似乎没有生效，点击插件的日志是完全空白的，看主程序运行的log也没有相关错误。webhook对应的地址是V1版本一直在使用的，接口方也没有接收到请求。因为完全没有日志，所以无从判断错误的大概方向。

![image](https://github.com/user-attachments/assets/34b3505d-4527-42c3-89fb-cdac31c2b504)

**Comment by LWWD** [comment]
借楼问一下楼主，webhook插件有文档吗？比如传入的字段什么的？

**Comment by chenvd** [comment]
> 借楼问一下楼主，webhook插件有文档吗？比如传入的字段什么的？

我是写了一个接口抓了一下报文，就是一个json，不同的事件字段body里的data会有不同，不过大同小异，类似这样的
```json
[
  {
    "headers": {
      "host": "10.1.1.200:5678",
      "user-agent": "python-urllib3/2.0.7",
      "accept-encoding": "gzip, deflate",
      "connection": "keep-alive",
      "content-type": "application/json",
      "content-length": "655"
    },
    "params": {},
    "query": {},
    "body": {
      "type": "name.recognize",
      "data": {
        "title": "Cells at Work!! Movie 2020 2160p WEB-DL AVC DDP 5.1-HDKWeb[はたらく細胞!! 最強の敵、再び。体の中は“腸”大騒ぎ！ / 工作细胞：细胞大作战 / 工作细胞！！强菌袭来，人体肠道大骚动！ | 类型：喜剧 / 动画 | 演员：花泽香菜 / 前野智昭 / 小野大辅 / 井上喜久子 / 长绳麻理亚]"
      }
    },
    "webhookUrl": "http://localhost:5678/webhook/8482c463-af25-41d7-9413-0894a1d79b5f",
    "executionMode": "production"
  }
]
```

**Comment by LWWD** [comment]
楼主2.0.5我看更新日志里说修复了，不过我似乎还是不行。请问你的正常了吗？

**Comment by chenvd** [comment]
> 楼主2.0.5我看更新日志里说修复了，不过我似乎还是不行。请问你的正常了吗？

确实还是不能用
