### ISSUE TITLE
[Feature Request]: 请求增加粤语配音过滤规则选项

### ISSUE THREAD

**Issue by jifengguo** [jxxghp/MoviePilot#311]
### 当前程序版本

1.0.8

### 功能改进

如题，希望能在规则里增加粤语配音过滤规则选项，或者增加自定义选项。对部分人来说，香港的电影电视和翻译动画，还是粤语好听些。

**Comment by jxxghp** [comment]
给几个种子的示例，不知道是什么关键字

**Comment by jifengguo** [comment]
一般都是筛选一个“粤”字就可以了，如下图
![岛](https://github.com/jxxghp/MoviePilot/assets/13091805/d8a2b74d-fd1b-4e06-b834-36007ff78858)
![友](https://github.com/jxxghp/MoviePilot/assets/13091805/38b9b423-5179-439b-9aa0-70865aa465d0)
![kong](https://github.com/jxxghp/MoviePilot/assets/13091805/855c53b7-52ae-4ce4-878e-f05fb590fc85)
