### ISSUE TITLE
[错误报告]: 重命名电视剧时无法获取videoFormat videoCodec

### ISSUE THREAD

**Issue by mackerel-12138** [jxxghp/MoviePilot#3114]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

重命名电视剧时无法获取videoFormat videoCodec
![image](https://github.com/user-attachments/assets/08add8c2-7b0b-4616-8d7d-089400d9782b)

**Comment by Aqr-K** [comment]
@mackerel-12138 直接从源文件获取这些信息，涉及到解码，很吃性能的，就算你能解码，视频同时整理的数量一大，服务器分分钟罢工死机

**Comment by mackerel-12138** [comment]
> > > 你原文件名就没这两个信息，怎么获取？
> > 
> > 
> > 视频分辨率 编码不是能直接从源文件拿么，为什么要依赖文件名
> 
> 因为从源文件拿涉及到解码视频，从文件名提取比较简单。

但是不能保证所有的资源都是按照这样的规则命名的啊，如果原资源没有那重命名就只能丢掉这些字段了，但是直接解码获取是肯定有的

**Comment by mackerel-12138** [comment]
> @mackerel-12138 直接从源文件获取这些信息，涉及到解码，很吃性能的，就算你能解码，视频同时整理的数量一大，服务器分分钟罢工死机

用tmm按顺序同时整理几百个视频都没问题
