### ISSUE TITLE
[错误报告]: plex无法同步媒体服务器，媒体库列表正确显示，剧集数量数据无法获取

### ISSUE THREAD

**Issue by blanketbathe** [jxxghp/MoviePilot#3115]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2-latest

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/user-attachments/assets/134325a1-0624-43af-9fe5-f5e7b12c4af8)

**Comment by blanketbathe** [comment]
sequence item 0: expected str instance, int found

**Comment by blanketbathe** [comment]
![image](https://github.com/user-attachments/assets/fc2951ca-2bbd-4243-a12b-cd6db20e3456)
![image](https://github.com/user-attachments/assets/740045bb-7ef3-4940-976f-73228109ff44)

**Comment by Ringoyan** [comment]
同样的问题，更新过了几次plex-token也不行

**Comment by mnwuchao** [comment]
同样问题

**Comment by mnwuchao** [comment]
同样问题
