### ISSUE TITLE
[错误报告]: 自动整理重命名时空文件夹识别错误

### ISSUE THREAD

**Issue by mackerel-12138** [jxxghp/MoviePilot#3120]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用目录监控时，当同时下载一整季，下载完成的第一集下载 刮削 重命名 移动到媒体库目录后，会直接删除季文件夹，导致未下载完成的文件丢失
![image](https://github.com/user-attachments/assets/fdc7accd-1bcb-4acb-bbc7-96994468db94)
![image](https://github.com/user-attachments/assets/20ff04bb-0919-480c-8dcb-42afe9ef187a)

**Comment by mackerel-12138** [comment]
2.0.5版本没有修复，季文件夹仍然会被删除即使里面有文件
![image](https://github.com/user-attachments/assets/88eb5e23-b1c0-4a97-8064-70badefdac42)
@jxxghp

**Comment by jxxghp** [comment]
@mackerel-12138 里面还有媒体文件吗？

**Comment by jxxghp** [comment]
@jxxghp 图片跟nfo不算

**Comment by mackerel-12138** [comment]
> @jxxghp 图片跟nfo不算

qb开了 未完成文件扩展名，mp里文件整理屏蔽词!qB
这个原因？

**Comment by jxxghp** [comment]
@mackerel-12138 v2.0.5，有以下这类文件也会算为有媒体文件，这种情况下应该不会删目录：

# 下载器临时文件后缀
    DOWNLOAD_TMPEXT: list = ['.!qB', '.part']

**Comment by jxxghp** [comment]
@mackerel-12138 知道原因了，大写B的原因
