### ISSUE TITLE
[错误报告]: 移走会自动删除父级目录（文件夹)

### ISSUE THREAD

**Issue by qqcomeup** [jxxghp/MoviePilot#3126]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

佬，现在MP是删除父级文件夹的
比如我下一部电影A在/父级预存文件夹，（因为这部电影的种子没有文件夹）
当我整理转走的时候他会整个预存文件夹（父级/总文件夹）都删除，这是否正常.
目录监控是整个预存文件夹的，删除了预存文件夹（父级）会导致目录监控全部失效。
![QQ图片20241116115714](https://github.com/user-attachments/assets/1c190d6e-8e61-4454-8d6d-b588478a1f00)

### 发生问题时系统日志和配置文件

```bash
V2的
【WARNING】2024-11-16 11:52:14,162 - monitor.py - 删除残留空文件夹：【local】/cd2/CloudDrive/115k/预存/
【INFO】2024-11-16 11:52:14,144 - monitor.py - 丧尸乐园 (2009) .2160p..mkv 入库成功：/cd2/CloudDrive/115k/媒体库/电影/丧尸乐园 (2009)/
【INFO】2024-11-16 11:52:14,143 - filemanager - 文件 /cd2/CloudDrive/115k/预存/丧尸乐园 (2009) .2160p..mkv 整理成功
【INFO】2024-11-16 11:52:14,141 - filemanager - /cd2/CloudDrive/115k/预存/ 目录下没有找到字幕文件...
【INFO】2024-11-16 11:52:10,106 - filemanager - 正在整理文件：【local】/cd2/CloudDrive/115k/预存/丧尸乐园 (2009) .2160p..mkv 到 【local】/cd2/CloudDrive/115k/媒体库/电影/丧尸乐园 (2009)/丧尸乐园 (2009) - 2160p {[tmdbid=19908]}.mkv
【INFO】2024-11-16 11:52:07,238 - filemanager - 获取整理目标路径：【local】/cd2/CloudDrive/115k/媒体库/电影
【INFO】2024-11-16 11:52:07,229 - monitor.py - 丧尸乐园 (2009) .2160p..mkv 识别为：电影 丧尸乐园 (2009)
【INFO】2024-11-16 11:52:06,489 - media.py - 丧尸乐园 (2009) .2160p..mkv 识别到媒体信息：电影 丧尸乐园 (2009)
【INFO】2024-11-16 11:52:06,488 - themoviedb - 丧尸乐园 TMDB识别结果：电影 丧尸乐园 (2009) 19908
【INFO】2024-11-16 11:52:06,158 - themoviedb - 正在识别 丧尸乐园 ...
```

V1的插件目录监控正常的，不会删除父级目录
【INFO】2024-11-16 14:53:21,466 - chain - 发送消息：channel=None，title=香水 (2006)  已入库, text=评分：7.4，类型：电影，类别：外语电影，质量： 2160p，共1个文件，大小：51.87G，userid=None
【INFO】2024-11-16 14:53:21,464 - dirmonitorenhanced - 开始处理媒体 香水 (2006)  消息
【WARNING】2024-11-16 14:53:17,955 - dirmonitorenhanced - 移动模式，删除空目录：/cd2/CloudDrive/115k/预存/香水 (2006)
【INFO】2024-11-16 14:53:17,940 - filetransfer - 文件 /cd2/CloudDrive/115k/预存/香水 (2006)/香水 (2006) - 2160p.mkv 转移成功
【INFO】2024-11-16 14:53:17,933 - filetransfer - 文件 /cd2/CloudDrive/115k/预存/香水 (2006)/香水 (2006) - 2160p.mkv move完成
【INFO】2024-11-16 14:53:11,627 - filetransfer - 正在转移文件：/cd2/CloudDrive/115k/预存/香水 (2006)/香水 (2006) - 2160p.mkv 到 /cd2/CloudDrive/115k/媒体库/电影/香水 (2006)/香水 (2006) - 2160p {[tmdbid=1427]}.mkv
【INFO】2024-11-16 14:53:11,621 - filetransfer - 获取转移目标路径：/cd2/CloudDrive/115k/媒体库/电影
【INFO】2024-11-16 14:53:10,876 - dirmonitorenhanced - 香水 (2006) - 2160p.mkv 识别为：电影 香水 (2006)
【INFO】2024-11-16 14:53:10,875 - themoviedb - 香水 TMDB识别结果：电影 香水 (2006) 1427
【INFO】2024-11-16 14:53:09,936 - themoviedb - 正在识别 香水 ...
【INFO】2024-11-16 14:47:36,468 - chain - 发送消息：channel=None，title=流浪地球2 (2023)  已入库, text=评分：7.2，类型：电影，类别：华语电影，质量： Bluray HDR DoVi REMUX UHD 2160p，共1个文件，大小：106.63G，userid=None
【INFO】2024-11-16 14:47:36,465 - dirmonitorenhanced - 开始处理媒体 流浪地球2 (2023)  消息
【INFO】2024-11-16 14:47:25,148 - filetransfer - 文件 /cd2/CloudDrive/115k/预存/流浪地球2.2023.2160p.CHN.UHD.Bluray.REMUX.DV.HDR.HEVC.TrueHD.Atmos.7.1-老K.mkv 转移成功
【INFO】2024-11-16 14:47:25,140 - filetransfer - 文件 /cd2/CloudDrive/115k/预存/流浪地球2.2023.2160p.CHN.UHD.Bluray.REMUX.DV.HDR.HEVC.TrueHD.Atmos.7.1-老K.mkv move完成
【INFO】2024-11-16 14:47:18,496 - filetransfer - 正在转移文件：/cd2/CloudDrive/115k/预存/流浪地球2.2023.2160p.CHN.UHD.Bluray.REMUX.DV.HDR.HEVC.TrueHD.Atmos.7.1-老K.mkv 到 /cd2/CloudDrive/115k/媒体库/电影/流浪地球2 (2023)/流浪地球2 (2023) - 2160p {[tmdbid=842675]}.mkv
【INFO】2024-11-16 14:47:18,487 - filetransfer - 获取转移目标路径：/cd2/CloudDrive/115k/媒体库/电影
【INFO】2024-11-16 14:47:17,764 - dirmonitorenhanced - 流浪地球2.2023.2160p.CHN.UHD.Bluray.REMUX.DV.HDR.HEVC.TrueHD.Atmos.7.1-老K.mkv 识别为：电影 流浪地球2 (2023)
【INFO】2024-11-16 14:47:17,763 - themoviedb - 流浪地球2 TMDB识别结果：电影 流浪地球2 (2023) 842675
【INFO】2024-11-16 14:47:17,163 - themoviedb - 正在识别 流浪地球2 ...

**Comment by cddjr** [comment]
刚看了眼代码，这种情况下确实会误删整个下载目录。
