### ISSUE TITLE
[错误报告]: V2的订阅下载的路径跟设置的不一样

### ISSUE THREAD

**Issue by rotent** [jxxghp/MoviePilot#3134]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

这是订阅设置的路径
![image](https://github.com/user-attachments/assets/13c830f4-cc26-438d-9bba-41fc13c85400)
这是订阅下载的路径
![image](https://github.com/user-attachments/assets/24cfd2f2-887a-4335-8a58-aa334f482793)

**Comment by rotent** [comment]
![image](https://github.com/user-attachments/assets/7fb1f39f-0fcf-4e81-82dd-e528068ab054)

**Comment by yystian** [comment]
我这也出现情况了，下载和整理都不识别二级目录了，我发现在目录设置的地方，电视剧类型的媒体类别只有一个全部，以前是有很多二级媒体类别的....

**Comment by jxxghp** [comment]
#3141
