### ISSUE TITLE
[Feature Request]: IYUU能直接内置到MP里面吗？这样QB种子迁移到TR也不用特意去TR上删种子了

### ISSUE THREAD

**Issue by nathandingx** [jxxghp/MoviePilot#3140]
### 当前程序版本

V1遗老

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

内置IYUU，或者拉取IYUU从QB转移到TR时的种子数据，解决MP删除媒体库后，还需从TR删除种子的问题

**Comment by jxxghp** [comment]
有相关插件

**Comment by nathandingx** [comment]
插件清理的不干净，能原生支持的话最好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月17日(周日) 中午12:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jxxghp/MoviePilot] [Feature Request]: IYUU能直接内置到MP里面吗？这样QB种子迁移到TR也不用特意去TR上删种子了 (Issue #3140)




 
有相关插件
