### ISSUE TITLE
[错误报告]: 为不完整的文件添加扩展名 .!qB 无响应，一下载就入库。

### ISSUE THREAD

**Issue by eadorothy86** [jxxghp/MoviePilot#3142]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.5

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

为不完整的文件添加扩展名 .!qB没响应，一下载就入库。

**Comment by qin9125** [comment]
这 bug 已经修了，只是还没打包而已，可以关闭这个 issue 了
