### ISSUE TITLE
[错误报告]: 设置-存储目录为空的

### ISSUE THREAD

**Issue by shua1zh** [jxxghp/MoviePilot#3149]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.5.20241117041917.4ffb406

### 运行环境

Windows

### 问题类型

主程序运行问题

### 问题描述

目前使用的是windows版本，最开始部署的时候是显示的，本地和阿里云盘都设置好了，应该是2.0.3升级之后，设置-存储&目录就变成空的了，目前升级到最新版本也没解决这个问题，但是使用都正常，就是看不到目录里面的内容。
![1](https://github.com/user-attachments/assets/1f6dd64d-b795-4497-ab25-5076684f68c6)
![2](https://github.com/user-attachments/assets/9486ab76-48e9-43b3-accd-4cb7893615f2)

**Comment by Thomastow** [comment]
想问一下这个问题怎么解决的，我也遇见这个问题。

**Comment by jxxghp** [comment]
数据库中的内容不对了，不能从V1升级。

**Comment by Thomastow** [comment]
> 数据库中的内容不对了，不能从V1升级。

嗯嗯好的，我是直接装的MP2哈。目前还没找到原因，不过我用NAS弄没问题，但是低配VPS有问题。暂时归因于性能差或者系统有问题把。

**Comment by Aspeternity** [comment]
我也出现了同样的问题，一开始的时候还是又Alist这些选项的，后边突然就空了，不知道为什么

**Comment by Aspeternity** [comment]
> 数据库中的内容不对了，不能从V1升级。

你好大佬，我也遇到了同样的问题，我是直接在NAS里安装的V2版本，没有从V1升级，刚安装的时候是有的，后边应该是自动升级了，存储里就空了，不能设置Alist这些，您能看看是什么问题嘛

**Comment by Aspeternity** [comment]
> > 数据库中的内容不对了，不能从V1升级。
> 
> 嗯嗯好的，我是直接装的MP2哈。目前还没找到原因，不过我用NAS弄没问题，但是低配VPS有问题。暂时归因于性能差或者系统有问题把。

请问您解决了嘛？
