### ISSUE TITLE
[Feature Request]: 馒头站是否能支持全站搜索来补全订阅呢

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#3150]
### 当前程序版本

v2 latest

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

如果错了馒头站的订阅，目前手动点击`搜索`是没有馒头站搜索链接的。

![image](https://github.com/user-attachments/assets/031d4820-edb6-429a-b3bb-d8a90cbf54af)
![image](https://github.com/user-attachments/assets/99e78d58-bd7a-4994-a29b-e064924d615c)

馒头站也能用搜索功能来补全吧
![image](https://github.com/user-attachments/assets/31e83262-21a5-4086-9957-43708874a153)

**Comment by leleji** [comment]
【WARNING】2024-11-17 19:12:47,232 - indexer - 馒头 未搜索到数据，耗时 0 秒
【ERROR】2024-11-17 19:12:47,216 - indexer - 馒头 搜索出错：'NoneType' object has no attribute 'get'
【INFO】2024-11-17 19:12:46,689 - torrents.py - 开始获取站点 m-team.cc 最新种子 ...
【INFO】2024-11-17 19:12:42,779 - indexer - 站点 馒头 开始以 MTorrent 模型解析数据...
我的站点是绿的。搜索错误。你怎么设置的

**Comment by cng10001** [comment]
> 【WARNING】2024-11-17 19:12:47,232 - indexer - 馒头 未搜索到数据，耗时 0 秒 【ERROR】2024-11-17 19:12:47,216 - indexer - 馒头 搜索出错：'NoneType' object has no attribute 'get' 【INFO】2024-11-17 19:12:46,689 - torrents.py - 开始获取站点 m-team.cc 最新种子 ... 【INFO】2024-11-17 19:12:42,779 - indexer - 站点 馒头 开始以 MTorrent 模型解析数据... 我的站点是绿的。搜索错误。你怎么设置的

![image](https://github.com/user-attachments/assets/a5a52e53-1b7e-4888-89b8-c8ee4906a271)
这样

**Comment by leleji** [comment]
> > 【WARNING】2024-11-17 19:12:47,232 - indexer - 馒头 未搜索到数据，耗时 0 秒 【ERROR】2024-11-17 19:12:47,216 - indexer - 馒头 搜索出错：'NoneType' object has no attribute 'get' 【INFO】2024-11-17 19:12:46,689 - torrents.py - 开始获取站点 m-team.cc 最新种子 ... 【INFO】2024-11-17 19:12:42,779 - indexer - 站点 馒头 开始以 MTorrent 模型解析数据... 我的站点是绿的。搜索错误。你怎么设置的
> 
> ![image](https://private-user-images.githubusercontent.com/115156545/386949242-a5a52e53-1b7e-4888-89b8-c8ee4906a271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDQyOTAsIm5iZiI6MTczMTg0Mzk5MCwicGF0aCI6Ii8xMTUxNTY1NDUvMzg2OTQ5MjQyLWE1YTUyZTUzLTFiN2UtNDg4OC04OWI4LWM4ZWU0OTA2YTI3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMTQ2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjdiNzM0OTU0NTRhNGFjZjAzNDkxNzI2MWZhMjBkMDY1N2FlODM3ZDg4MGQzYTA0YzM1OWYxYzE4YTAyZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KJT9bW6MLGJoYQ9lh7Mit_Hd80u5EFXjZzZnFSYTxmo) 这样

我也是这样设置的。但是点浏览获取不到种子

**Comment by cng10001** [comment]
> > > 【WARNING】2024-11-17 19:12:47,232 - indexer - 馒头 未搜索到数据，耗时 0 秒 【ERROR】2024-11-17 19:12:47,216 - indexer - 馒头 搜索出错：'NoneType' object has no attribute 'get' 【INFO】2024-11-17 19:12:46,689 - torrents.py - 开始获取站点 m-team.cc 最新种子 ... 【INFO】2024-11-17 19:12:42,779 - indexer - 站点 馒头 开始以 MTorrent 模型解析数据... 我的站点是绿的。搜索错误。你怎么设置的
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/115156545/386949242-a5a52e53-1b7e-4888-89b8-c8ee4906a271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDQyOTAsIm5iZiI6MTczMTg0Mzk5MCwicGF0aCI6Ii8xMTUxNTY1NDUvMzg2OTQ5MjQyLWE1YTUyZTUzLTFiN2UtNDg4OC04OWI4LWM4ZWU0OTA2YTI3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMTQ2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjdiNzM0OTU0NTRhNGFjZjAzNDkxNzI2MWZhMjBkMDY1N2FlODM3ZDg4MGQzYTA0YzM1OWYxYzE4YTAyZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KJT9bW6MLGJoYQ9lh7Mit_Hd80u5EFXjZzZnFSYTxmo) 这样
> 
> 我也是这样设置的。但是点浏览获取不到种子

删了重新添加一遍，或者把馒头的api地址添加进代理试试

**Comment by cng10001** [comment]
试出来了，可能是因为没开`多名称资源搜索`的原因
![PixPin_2024-11-20_01-00-54](https://github.com/user-attachments/assets/0987753f-fe7a-4c00-9b9e-3046eb8285e3)
