### ISSUE TITLE
[Feature Request]: 微信交换菜单使用权限改进

### ISSUE THREAD

**Issue by kekylin** [jxxghp/MoviePilot#3151]
### 当前程序版本

v2.0.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

关于管理员才能使用微信通知交互菜单有两个疑问：
1、文档中提到的管理员白名单，请问是企业应用中的管理员？还是MoviePilot的管理员？
2、如果是企业应用中的管理员白名单，可否像v1版本时那样，可以设置非管理员用户使用交互菜单？

因一些特殊原因，导致企业微信应用管理员用户不是我常用微信号，需要通过别的微信号使用交互菜单。但在v2中普通用户无法使用，提示“用户无权限执行菜单命令”，找了一圈下来没发现有相关设置的地方，如有还请帮忙指导一下。企业应用中只有一个管理员名单，无法再进行额外添加。

如果可以，希望能设置其他用户使用微信交互菜单，感谢！

MoviePilot文档说明：
管理员白名单
设置后，只有在管理员白名单的用户才可以使用微信应用号的菜单功能。
文档链接：https://wiki.movie-pilot.org/zh/notification

**Comment by gudumuyu** [comment]
可以设置多个的，是企业微信中的用户的账号名称，在“通知设置-企业微信—管理员白名单”中设置，用“,”分隔

**Comment by kekylin** [comment]
> 可以设置多个的，是企业微信中的用户的账号名称，在“通知设置-企业微信—管理员白名单”中设置，用“,”分隔

感谢感谢！已经成功设置了。

**Comment by huangge1199** [comment]
大佬，我这边也有同样的问题，企业微信中的用户的账号名称，这个是微信号吗？能方便截图说明下吗？我这边没弄好
