### ISSUE TITLE
[Feature Request]: 希望新增电视剧及番剧全集订阅功能

### ISSUE THREAD

**Issue by hymmmmma** [jxxghp/MoviePilot#3153]
### 当前程序版本

 v1.9.17

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

希望可以新增电视剧及番剧订阅全集功能，这样对于不追新，一次性订阅观看的较为友好，且全集保种也更为方便。

**Comment by hbq0405** [comment]
打开洗版，就只会下载全集
