### ISSUE TITLE
V2版本微信收不到所有的 插件信息   订阅 和下载正常

### ISSUE THREAD

**Issue by wanpijun2** [jxxghp/MoviePilot#3160]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

所有插件 不推送信息给电报 或者微信 作者 大大救命
![image](https://github.com/user-attachments/assets/cc92a779-f3db-47ae-bf20-de1705d79e11)
![image](https://github.com/user-attachments/assets/44f0b319-bce8-4d96-bcdd-590dfadb3f76)

**Comment by carolcoral** [comment]
同

**Comment by yuhaaitao** [comment]
2.09也是这样的问题

**Comment by carolcoral** [comment]
1. 看看微信设置里面的token，v2版本的token强制要求16位了，应该没有同步
2. 检查微信应用里面的userId，不要纯数字，不要0开头

**Comment by XR-LM** [comment]
![image](https://github.com/user-attachments/assets/12939d96-5073-4f30-8177-6243fada3bff)
v1版本未配置token可正常微信交互。v2版本必须要加上token这个参数才行
