### ISSUE TITLE
[错误报告]: 升级2.0.7后电视剧没有热门订阅按键~！

### ISSUE THREAD

**Issue by zhy648789** [jxxghp/MoviePilot#3173]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

升级2.0.7 电视剧 没有热门订阅了。
升级可以再UI界面设置站点认证，我也没看见那里有。
<img width="846" alt="截屏2024-11-20 上午4 28 50" src="https://github.com/user-attachments/assets/7a3fca99-0ad2-40ad-b690-940ebdf42087">

**Comment by zhy648789** [comment]
清理过浏览器缓存。依旧没有~~热门订阅。

**Comment by cddjr** [comment]
只有没通过站点认证的才能看到设置页面

**Comment by cddjr** [comment]
只有没通过站点认证且当前是管理员，才能看到认证的设置页面
