### ISSUE TITLE
[错误报告]: 手动整理 不会自动创建二级目录

### ISSUE THREAD

**Issue by aliezguy** [jxxghp/MoviePilot#3178]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

手动整理 不会自动创建二级目录  之前的版本会按照设定的目录进行整理并自动创建二级目录
/volume3/CloudNAS/CloudDrive/80003588/emby库/电视剧 该路径为自己设置的媒体库路径,目录监控会正常创建二级文件夹

### 发生问题时系统日志和配置文件

```bash
- /volume3/CloudNAS/CloudDrive/80003588/emby库/电视剧 为自定义路径, 通知将不会发送
【INFO】2024-11-20 14:06:15,379 - filemanager - 获取整理目标路径：【local】/volume3/CloudNAS/CloudDrive/80003588/emby库/电视剧
【INFO】2024-11-20 14:06:15,392 - filemanager - 正在整理文件：【local】/volume3/CloudNAS/CloudDrive/80003588/移动整理/电视剧/国产剧/春花焰(2024)/Season 1 -2160p-WEB-DL-OurTV/春花焰.2024.S01E32.2160p.WEB-DL.H265.DDP 5.1-OurTV.mkv 到 【local】/volume3/CloudNAS/CloudDrive/80003588/emby库/电视剧/春花焰(2024)/Season 1 -2160p-WEB-DL-OurTV/春花焰.2024.S01E32.2160p.WEB-DL.H265.DDP 5.1-OurTV.mkv
【INFO】2024-11-20 14:06:17,406 - filemanager - /volume3/CloudNAS/CloudDrive/80003588/移动整理/电视剧/国产剧/春花焰(2024)/Season 1 -2160p-WEB-DL-OurTV/ 目录下没有找到字幕文件...
【INFO】2024-11-20 14:06:17,409 - filemanager - 文件 /volume3/CloudNAS/CloudDrive/80003588/移动整理/电视剧/国产剧/春花焰(2024)/Season 1 -2160p-WEB-DL-OurTV/春花焰.2024.S01E32.2160p.WEB-DL.H265.DDP 5.1-OurTV.mkv 整理成功
【INFO】2024-11-20 14:06:17,475 - media.py - 开始刮削：/volume3/CloudNAS/CloudDrive/80003588/emby库/电视剧/春花焰(2024) ...
```

**Comment by jxxghp** [comment]
@usherkobe 不指定目的目录时自动识别分类，但如果指定了目的目录，就要指到你想要的那个最里层目录

**Comment by usherkobe** [comment]
@jxxghp 试了下确实是这样，但是它默认跑到第一个目录里面去了，而我有三个目录，我想他跑第三个目录里面去；感觉还是2.0.6版本那种处理比较好

**Comment by usherkobe** [comment]
比如我两个目录，分别是PT和PT2，PT2里的电影我点一下自动整理，不填目录，就跑到PT/电影里面去了，可我想要他去PT2/电影里面

**Comment by jxxghp** [comment]
@usherkobe 问题是又有人说会强制他指的目录，众口难调

**Comment by usherkobe** [comment]
好吧 大佬辛苦了，但是至少pt2目录的得往pt2同目录下自动移动呀

**Comment by heartacker** [comment]
还有疑问
