### ISSUE TITLE
alist整理依然有问题

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/MoviePilot#3180]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

2.0.7版本直接连接alist整理还是出错，可以自动改名但是无法转移，微信提示未找到有效的媒体库目录，但实际上MP已经在目的文件夹建好了文件夹，只是没有移动(我设置的整理方式是move)过去
![IMG_7319](https://github.com/user-attachments/assets/08b9fa64-d424-4ce9-a661-5d2b31ba2ad4)

### 发生问题时系统日志和配置文件

```bash
Chain:运行模块FileManagerModule.transfer
Ш: expected str, bytes or os. PathLike object, not Fileltem

monitor.py:文件转移模块运行失败
```

**Comment by LevineWoo** [comment]
![image](https://github.com/user-attachments/assets/12cabb2a-215d-42a2-9b96-7fa7e6f83ed0)
想请问下我这样设置为嘛日志没有任何整理的记录的。。只是想让他帮忙改名一下。

**Comment by LGuangming** [comment]
> 日志没有任何整理

你有设置改名规则吗，或者去文件夹手动整理看看。
