### ISSUE TITLE
[错误报告]: 如果有两块以上硬盘，把整个mnt映射到media，在v2的目录中无法打开mnt映射media文件夹，v1中没有这个问题。

### ISSUE THREAD

**Issue by huppy941218** [jxxghp/MoviePilot#3183]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.0.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![屏幕截图 2024-11-20 232347](https://github.com/user-attachments/assets/25afbe85-bb7c-409f-b313-f21cdcf439dd)
![屏幕截图 2024-11-20 232408](https://github.com/user-attachments/assets/d765a5b2-a28e-48ae-84b9-fa776dc74bf2)

**Comment by rhettZeng107** [comment]
我还以是我配置的问题，原来是Bub， 大佬抓紧修复吧。

**Comment by cddjr** [comment]
> 我还以是我配置的问题，原来是Bug， 大佬抓紧修复吧。
> 
> 我的NAS是unRAID 7.0 B4 正版，也出现这个这问题，无法打开/mnt文件夹

测试了 unraid 6.12.13 MP 2.0.8，2.1.0，均没有任何问题。

**Comment by rhettZeng107** [comment]
[image: image.png] [image: image.png]
我这里打开是显示空目录。如何加载阵列的存储？ 我unraid 3块1TB的array

景大侠 ***@***.***> 于2024年11月25日周一 20:02写道：

**Comment by Aqr-K** [comment]
@rhettZeng107 你真勇，iyuu token公开给大家用

**Comment by rhettZeng107** [comment]
不小心把token复制过来了，修改了XXX

**Comment by rhettZeng107** [comment]
@Aqr-K  不小心把token复制过来了，修改了XXX

**Comment by hbq0405** [comment]
unraid干嘛映射/mnt?不管多少块硬盘，直接映射共享目录就行。

**Comment by rhettZeng107** [comment]
> unraid干嘛映射/mnt?不管多少块硬盘，直接映射共享目录就行。

/mnt/user/downloads， 这个downloads就是共享目录呀

**Comment by hbq0405** [comment]
那你的后面的/complete是啥意思啊？

**Comment by rhettZeng107** [comment]
> 那你的后面的/complete是啥意思啊？

是downloads下面的子文件夹，下载的资源全部在这里。

**Comment by hbq0405** [comment]
给你个unraid模板吧，修改下网络和目录映射就行，执行这条命令，然后容器-添加-选择这个模板
curl -sL https://gist.githubusercontent.com/hbq0405/8d6ebbeafe5681fc01d03deb04f8f992/raw/moviepilot.xml -o /boot/config/plugins/dockerMan/templates-user/MoviePilot.xml

**Comment by hbq0405** [comment]
直接映射共享目录就行，不要深入到子目录，那是给后期找麻烦

**Comment by rhettZeng107** [comment]
> 直接映射共享目录就行，不要深入到子目录，那是给后期找麻烦

好的，我试一下。多谢！
