### ISSUE TITLE
[错误报告]: MP 下载目录与 QB 的下载目录有设置歧义的问题

### ISSUE THREAD

**Issue by yfdoor** [jxxghp/MoviePilot#3188]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

比如我的
 QB 映射：
/media/download:/downloads

MP 映射：
/media：/media

MP 目录设置中这样设置：
![image](https://github.com/user-attachments/assets/24e03aef-5859-405d-89f2-ed9f17cf7f7d)

这时，我通过订阅，下载任务添加到 QB 中，但是会报错，无法开始 下载。

查看 QB log 文件，发现如下错误，应该是任务想把文件存储在 /media/download/movie/ 下，而在 QB 中的路径应该是 /downloads/movie. 所以因为目录不存在，权限问题导致无法下载

`
文件错误警报。Torrent：“Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb”。文件：“/media/download/movie/Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb/Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb.mkv”。原因：“Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb file_open (/media/download/movie/Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb/Look.Back.2024.1080p.AMZN.WEB-DL.H264.DDP5.1-ADWeb.mkv) error: Permission denied”
`

我猜测应该将上面 MP 的下载目录设置改为 /downloads/movie, 可是这样设置又与 ui 的整体设定有违背，因为 MP 的路径应该都是相对于 MP 来说的而不应该是对 QB 的相对目录。
![image](https://github.com/user-attachments/assets/2b02dbf5-8950-4478-abae-d42a53693ce9)

**Comment by hbq0405** [comment]
所以，你提这个的目的是什么？你自己都知道问题出在哪了，不去纠正自己的错误发什么issues？

**Comment by yfdoor** [comment]
> 所以，你提这个的目的是什么？你自己都知道问题出在哪了，不去纠正自己的错误发什么issues？

界面需要修改啊，我相信很多人会和我一样上面设置的是第一种情况啊

**Comment by hbq0405** [comment]
明明你修改下QB映射就能解决的小问题，你却让MP改？佩服你真敢想，更佩服你敢提issues

**Comment by Putarku** [comment]
#QB 映射：
#/media/download:/downloads

改成
`/media/download:/media/download`
不就行了

**Comment by yfdoor** [comment]
> 明明你修改下QB映射就能解决的小问题，你却让MP改？佩服你真敢想，更佩服你敢提issues

这是软件设计思路问题，就是不同容器间的相对路径关系。我不想和你讨论这个问题，项目负责人认为需要就改，不需要就不改。就这么简单。

**Comment by hbq0405** [comment]
MP不仅仅要和QB配合，还需要和TR、EMBY等等配合，都个性化一个容器一个映射，那还玩个球。
要以MP为中心，其他容器来配合MP，而不是MP去配合其他容器

**Comment by cddjr** [comment]
qb和mp都按相同的路径映射，就不存在任何问题了。你这个问题本质上是对docker的路径映射不熟悉导致

**Comment by DizzyWu** [comment]
这种情况如果在套件版qb上也会出现，而且设置绝对路径后文件无法整理，如果在这里关闭自动整理，最后会直接无法下载

**Comment by Putarku** [comment]
> 这种情况如果在套件版qb上也会出现，而且设置绝对路径后文件无法整理，如果在这里关闭自动整理，最后会直接导致无法下载

将宿主机的实际路径原样映射进mp，并且保证文件夹的权限qb和mp都可以正常操作

**Comment by DizzyWu** [comment]
> > 这种情况如果在套件版qb上也会出现，而且设置绝对路径后文件无法整理，如果在这里关闭自动整理，最后会直接导致无法下载
> 
> 将宿主机的实际路径原样映射进mp，并且保证文件夹的权限qb和mp都可以正常操作

已经映射了，但是如果使用映射后的地址，mp会直接把映射地址发给qb，导致qb无法找到路径而下载失败

**Comment by cddjr** [comment]
> > > 这种情况如果在套件版qb上也会出现，而且设置绝对路径后文件无法整理，如果在这里关闭自动整理，最后会直接导致无法下载
> > 
> > 
> > 将宿主机的实际路径原样映射进mp，并且保证文件夹的权限qb和mp都可以正常操作
> 
> 已经映射了，但是如果使用映射后的路径，mp会直接把映射路径发给qb，导致qb无法找到路径而下载失败。
> 
> 例： /volumn1/media:/media
> 
> 如果我在mp中设置的下载路径是 /media/movie，下载时 qb 会直接使用这个路径下载，而实际路径应该是 /volumn1/media/movie，我目前使用的版本是 v2

mp和qb就应该映射成一样的路径，免得产生一些奇奇怪怪的问题

**Comment by RyouMon** [comment]
这个问题之前有人提过：#1288
我是window下用docker有这个问题，目前是没法通过下载器监控整理的，但可以通过目录监控整理。
我也想过如果qbit也用docker运行应该能解这个问题，但是懒得试了

**Comment by little6neko** [comment]
V1版本是支持moviepilot和qb不同路径映射的，V1里面订阅发给下载器的路径也能转换，V2不知道为什么砍了。路径要不要统一映射成一样应该给个自由选择，有些人喜欢映射不同，有些喜欢映射一样
