### ISSUE TITLE
[错误报告]: 2.0手动整理没有同盘/根目录优先

### ISSUE THREAD

**Issue by dokurorz** [jxxghp/MoviePilot#3191]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.0.8

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

目前挂载了两块硬盘，下载路径分别为:
- `/mnt/硬盘A/downloads/`
- `/mnt/硬盘B/downloads/`

#### 2.x版本
2.x版本中，按以下顺序添加两个目录，整理方式为硬链接:
- `/mnt/硬盘A/downloads/`，整理目录为 `/mnt/硬盘A/media/`
- `/mnt/硬盘B/downloads/`，整理目录为 `/mnt/硬盘B/media/`

自动整理识别错误时，进入文件管理使用手动整理，目的路径留空自动，位于 `/mnt/硬盘B/downloads/`下的文件，获取整理目标路径时只会为第一个，即`/mnt/硬盘A/media/`，硬链接失败。

#### 1.x版本
在1.x版本中，开启目录设置中的`同盘/同根目录优先`，整理方式为硬链接，下载目录添加两块硬盘的路径，媒体目录按顺序添加为:
- `/mnt/硬盘A/media/`
- `/mnt/硬盘B/media/`

在手动整理时，目的路径留空自动，如果是`/mnt/硬盘B/downloads`下的文件，会整理到`/mnt/硬盘B/media`下，反之同理。

顺便一提，2.0.8中，手动整理时，目的路径的弹出路径不显示设置中已添加的目录，只有`/`路径

**Comment by usherkobe** [comment]
试了下2.0.9还是有这个问题

**Comment by yzsxlijunjun** [comment]
我是2.08没问题，2.09有这个问题，2台nas，但是参数完全一致。

**Comment by usherkobe** [comment]
![image](https://github.com/user-attachments/assets/b21d1869-aa55-432f-8f20-a05fce50d90a)
纳闷了，为啥我还是不行，2.0.9的
