### ISSUE TITLE
[错误报告]: 连不上macvlan的qBittorrent

### ISSUE THREAD

**Issue by Noir-Chen** [jxxghp/MoviePilot#3210]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.0.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

想qBittorrent单走网口，设置了macvlan，但是发现连不上macvlan网络的qBittorrent，改回bridge能支持使用。
想请教一下大佬这是bug还是feature？如果是feature的话，后续会支持吗？

**Comment by qin9125** [comment]
是你的问题，macvlan 不支持容器间的连接，请搜教程做桥接就可以

**Comment by Sowevo** [comment]
qBittorrent走macvlan后其他容器也得macvlan才能通信,这个是docker的feature

**Comment by Noir-Chen** [comment]
学到了~感谢大佬们解惑
