### ISSUE TITLE
[下载目录]: 设置了下载目录，但是订阅以及站点浏览资源下载后，qbit的下载目录均为/Downloads/***

### ISSUE THREAD

**Issue by Zzih** [jxxghp/MoviePilot#3212]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.0.8

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

已经设置了下载目录，并且出现这个问题后，也单独设置了订阅的下载目录，但是问题依旧。是我的设置有什么问题吗？麻烦指导一下...感谢
![image](https://github.com/user-attachments/assets/5ee04bb0-4142-49f0-83dc-2e41245ecd40)
![image](https://github.com/user-attachments/assets/fa161d40-d978-4436-a9fa-9402fe01995d)
![image](https://github.com/user-attachments/assets/1f79709a-1ecc-4062-af18-210d155a4f98)
![image](https://github.com/user-attachments/assets/752bb3de-2ceb-4a5b-b455-d253f28506c7)
![image](https://github.com/user-attachments/assets/83d191e0-df22-451a-9a13-072a29e7c6a0)

**Comment by winter0245** [comment]
我遇到一样的问题，解决方法是到 设置-系统-下载器-自动分类整理  关掉就好了

**Comment by luckylss** [comment]
>我遇到了一样的问题，解决方法是去设置-系统-下载器-自动分类整理关掉就好了>我遇到了一样的问题，解决方法是去设置-系统-下载器-自动分类整理关掉就好了不管同
