### ISSUE TITLE
[错误报告]: 即便已配置目录也无法获取目录权限

### ISSUE THREAD

**Issue by suerb** [jxxghp/MoviePilot#3213]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在容器配置里面已经做好目录权限和映射，但是仍然报错
![mp0](https://github.com/user-attachments/assets/3361ad40-80f9-4ef1-be61-afbd6f38de33)
![mp3](https://github.com/user-attachments/assets/7e8be020-8f66-477a-8d14-7157f96dad68)
![mp2](https://github.com/user-attachments/assets/5f2a1630-16c0-4c0b-a6fa-6f5a00a06d22)
![mp1](https://github.com/user-attachments/assets/496c20d8-1e47-4b24-a945-6ddd70d16fca)

通过 Moviepilot 下载了 20 多部内容仍然为空，只要下载完，什么都没了，只有下载中的能看到

![WechatIMG251](https://github.com/user-attachments/assets/f48a27c3-2069-4f5f-8029-8a29f9a295fb)

**Comment by cddjr** [comment]
你要配置映射后的路径，而不是你主机的装载目录
