### ISSUE TITLE
[错误报告]: 文件管理中单集转移在历史记录中显示不正常

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#322]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.9

### 问题类型

主程序运行问题

### 问题描述

文件管理中单集转移在历史记录中显示不正常
![1693311817156](https://github.com/jxxghp/MoviePilot/assets/23021469/02fbc569-bc81-4c36-ab4d-fc78265e35eb)

此种情况下在历史记录中删除选择同步删除文件，会导致那一整个动漫都被删除，就是删除了整个文件夹而不是具体的那一集

**Comment by jxxghp** [comment]
录入ID时，你选的是哪个层面就按哪个层级记日志。
自动识别时，按文件记日志。

**Comment by mjsoftking** [comment]
@jxxghp 点击单集和文件夹历史记录效果一样的，问题不大，就是删除历史时候不要选择删除文件否则文件夹全删了
