### ISSUE TITLE
“订阅搜家补全”死循还的问题解决。

### ISSUE THREAD

**Issue by 88866888** [jxxghp/MoviePilot#3220]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V2 10.0.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

“订阅搜家补全”已经循还轮刷了10多轮了，也没有停下来。我都等了1个小时了，还在轮刷。能不能把“订阅搜家补全”像死循还的问题解决下。

**Comment by 88866888** [comment]
版本写错了是2.0.9

**Comment by cng10001** [comment]
我订阅二十多部，大概就是一个多小时，如果这样看的话也正常。
