### ISSUE TITLE
[错误报告]: IYUU自动辅种V2.2插件，辅的种下载路径错误导致不能正常辅种

### ISSUE THREAD

**Issue by l429609201** [jxxghp/MoviePilot#3225]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V2.0.8  V2.0.9

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

我使用QB作为下载器，辅种用的也是QB，我在更新IYUU自动辅种插件V2.2版本后发现，辅种过去下载器后，种的保存路径为默认路径/downloads（正常来说应该是，我下载的其他站的种假设路径是/downloads/QB/电影，那么辅过其他站的种下载路径也应该是/downloads/QB/电影，下载器才能正常开会校验）,导致下载器不能正常识别校验，弄回去IYUU自动辅种V2.1后才正常

**Comment by hbq0405** [comment]
把QB自动分类管理关了

**Comment by dlovew** [comment]
辅种分类插件对qb自动分类管理无效，类似issue我提过的。可以把插件辅种后分类设置为空或者把QB自动分类管理关了

**Comment by dlovew** [comment]
@jxxghp 麻烦大佬看一下，我更新2.1.0以后也存在同样问题了，本来我打开qb自动分类，同时辅种插件分类设置为空是可以正常辅种的，今天中午更新2.1.0以后，存在路径错误的问题，所有的辅种路径都变成了qb的默认下载路径，例如/vol3/1000/Media_SSD/Download/，实际应该是/vol3/1000/Media_SSD/Download/大陆剧，/vol3/1000/Media_SSD/Download/日番

**Comment by l429609201** [comment]
> 把QB自动分类管理关了

谢谢你，昨天有大佬回复我了

**Comment by hbq0405** [comment]
> @jxxghp 麻烦大佬看一下，我更新2.1.0以后也存在同样问题了，本来我打开qb自动分类，同时辅种插件分类设置为空是可以正常辅种的，今天中午更新2.1.0以后，存在路径错误的问题，所有的辅种路径都变成了qb的默认下载路径，例如/vol3/1000/Media_SSD/Download/，实际应该是/vol3/1000/Media_SSD/Download/大陆剧，/vol3/1000/Media_SSD/Download/日番

再添加个下载器，地址用户名密码都和默认一样，关掉自动分类管理，然后辅种插件选择这个下载器就行了

**Comment by l429609201** [comment]
> > @jxxghp 麻烦大佬看一下，我更新2.1.0以后也存在同样问题了，本来我打开qb自动分类，同时辅种插件分类设置为空是可以正常辅种的，今天中午更新2.1.0以后，存在路径错误的问题，所有的辅种路径都变成了qb的默认下载路径，例如/vol3/1000/Media_SSD/Download/，实际应该是/vol3/1000/Media_SSD/Download/大陆剧，/vol3/1000/Media_SSD/Download/日番
> 
> 再添加个下载器，地址用户名密码都和默认一样，关掉自动分类管理，然后辅种插件选择这个下载器就行了

感谢大佬提供的方法，亲测可用

**Comment by dlovew** [comment]
突然发现最新版本，qb5.0.1设置-下载里 
启用子分类：
在手动模式下使用分类路径：
这两个打勾即可在mp不打开自动分类开关的情况下正常辅种
