### ISSUE TITLE
[错误报告]: v2版本日志接口403

### ISSUE THREAD

**Issue by smartisanyyh** [jxxghp/MoviePilot#3229]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.0.9

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在web界面查看日志 控制台发现/api/v1/system/logging报错
Request Method:GET
状态代码:403 Forbidden

**Comment by smartisanyyh** [comment]
好像所有类型为eventsource的请求都403

**Comment by InfinityPacer** [comment]
@smartisanyyh MP页面，F5即可

**Comment by smartisanyyh** [comment]
可以了 谢谢...我是开发者工具清除网站数据才可以,应该是有缓存,普通的刷新不行
