### ISSUE TITLE
[Feature Request]: 关于直接过滤并忽略识别与转移thumb文件的问题

### ISSUE THREAD

**Issue by yangchris4** [jxxghp/MoviePilot#323]
### 当前程序版本

v1.0.9

### 功能改进

使用环境：威联通docker
使用版本：V1.0.9
问题描述：威联通系统奇葩，会在下载完成后在文件夹目录下新建.@_thumb文件夹，并生成对应的索引或者缩略文件（如图）。这些文件会严重影响mp对电视剧和电影的刮削，a100~s800,通常会被识别成Season 10 和 Season 80。但是之前的nt的文件管理和目录监控功能却能忽略这个文件夹。
希望作者能够再完善一下呢，谢谢啦

**下载完成后会在当前目录生成.@_thumb文件夹**
![2](https://github.com/jxxghp/MoviePilot/assets/13220804/56c8038b-78b0-4bce-99f2-2a0a3101b53c)

**.@_thumb文件夹里面的内容**
![image](https://github.com/jxxghp/MoviePilot/assets/13220804/2591d6d4-1684-4b50-9cc5-38e59dc294c8)

**错误识别**
![微信截图_20230829220511](https://github.com/jxxghp/MoviePilot/assets/13220804/588a1c24-3c67-4da8-9e9c-3dac2ee4ecd1)

**电视剧更糟糕**
![微信图片_20230829220001](https://github.com/jxxghp/MoviePilot/assets/13220804/64f94332-a154-4e6d-ad6a-128924e90611)

**Comment by mjsoftking** [comment]
如果你使用的是目录监控，应该把关键词加入排除列表就行了

**Comment by jxxghp** [comment]
已修复
