### ISSUE TITLE
[错误报告]: 订阅不能集数偏移

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#3246]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2 latest

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

我想针对这个标题来自定义识别词然后订阅：`BLEACH Thousand-Year Blood War S03 1080p Disney+ WEB-DL AAC 2 0 H.264-CHDWEB`
![image](https://github.com/user-attachments/assets/71d2ef98-0398-47e4-8da8-9248a59a4e0f)
死神第三季第一集相当于tmdb上面第二季第二十七集，然后我自定义识别词是这样调整
`BLEACH.Thousand-Year.Blood.War.S03 => BLEACH.Thousand-Year.Blood.War.S02 && S02 <> 1080p >> EP+26 
`
![image](https://github.com/user-attachments/assets/81c4e5f5-8333-45a5-8038-c59ce5148956)
第8集+26=34，名称测试似乎没问题
但是感觉搜索订阅的时候软件虽然检测到了原本的集数，却没有根据自定义识别词的集数偏移EP+26来调整集数
![image](https://github.com/user-attachments/assets/0d3b5a82-6ecd-47d4-b4ed-d008fce9d998)

**Comment by siren44** [comment]
会不是种子的标题里只有S03没有集数的原因。你名称识别里用的是S03E08，实际种子标题只有S03

**Comment by cng10001** [comment]
> 会不是种子的标题里只有S03没有集数的原因。你名称识别里用的是S03E08，实际种子标题只有S03

你看最后一张图片里的日志信息，软件是能识别具体集数信息的，`没有需要的集`前面就是集数信息

**Comment by wikrin** [comment]
首先自定义识别词格式为`被替换词 => 替换词 && 前定位词 <> 后定位词 >> 集偏移量（EP）` , 具体参考 [MoviePilot Wiki/自定义识别词](https://wiki.movie-pilot.org/zh/advanced#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%86%E5%88%AB%E8%AF%8D)
说明一下: `拆包` `全集类`种子识别集使用的`自定义识别词`应当是种子内的`集标题`而不是`全集种子标题`

**Comment by cng10001** [comment]
> 首先自定义识别词格式为`被替换词 => 替换词 && 前定位词 <> 后定位词 >> 集偏移量（EP）` , 具体参考 [MoviePilot Wiki/自定义识别词](https://wiki.movie-pilot.org/zh/advanced#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%86%E5%88%AB%E8%AF%8D) 说明一下: `拆包` `全集类`种子识别集使用的`自定义识别词`应当是种子内的`集标题`而不是`全集种子标题`

佬 是的哎 我自我感觉我设置对哎。
上图中用的就是种子内文件名：`BLEACH.Thousand-Year.Blood.War.S03E08.BABY.HOLD.YOUR.HAND.1080p.Disney+.WEB-DL.AAC.2.0.H.264-CHDWEB.mkv`
我设置的自定义：`BLEACH.Thousand-Year.Blood.War.S03 => BLEACH S02 && S02 <> 1080p >> EP+26`
然后在名称识别测试里也是能正确识别的

**Comment by wikrin** [comment]
> 佬 是的哎 我自我感觉我设置对哎。 上图中用的就是种子内文件名：`BLEACH.Thousand-Year.Blood.War.S03E08.BABY.HOLD.YOUR.HAND.1080p.Disney+.WEB-DL.AAC.2.0.H.264-CHDWEB.mkv` 我设置的自定义：`BLEACH.Thousand-Year.Blood.War.S03 => BLEACH S02 && S02 <> 1080p >> EP+26` 然后在名称识别测试里也是能正确识别的

>> 在订阅检索时，会使用种子的标题来进行检索集数，而这个站点的集数写在副标题里面，因此无法使用识别词进行替换识别； 推荐订阅其他站点，如果非要使用该站点订阅的话，可以使用站点提供的rss搭配mp的rss插件中的下载使用，此时会忽略站点的标题直接下载，下载完成后会按照你的识别词转移刮削。

因为种子标题中没有 `EP`，日志中出现的 `EP` 是从`副标题`中识别出来的。由于`副标题`没有使用`自定义识别词`处理，导致出现`集数偏移/自定义识别词`未生效的错觉。

**Comment by cng10001** [comment]
感谢大佬们答疑 理解了 确实是不支持的
