### ISSUE TITLE
一个目录如果有多种媒体类别，手动整理目录时只会放到一个类别目录里面，而不是按照设置的媒体文件整理目录结构

### ISSUE THREAD

**Issue by ting1e** [jxxghp/MoviePilot#3256]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/user-attachments/assets/1af4ab07-2c0a-4b2e-b1fd-7b7d6fe51384)
![image](https://github.com/user-attachments/assets/f62f772a-2da0-4738-a743-8dfc577ac5c3)
识别到了华语电影和外语电影但都整理到了外语电影目录下，动画电影也是整理到了外语电影目录

**Comment by wikrin** [comment]
在 #3245 已修复
