### ISSUE TITLE
[Feature Request]: V2.1.0版本，手动整理功能中将整理方式默认值添加回来或者设置整理默认方式

### ISSUE THREAD

**Issue by tripewa** [jxxghp/MoviePilot#3258]
### 当前程序版本

V2.1.0

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

手动整理功能中将整理方式默认值添加回来或者设置整理默认方式
![局部截取_20241127_091128](https://github.com/user-attachments/assets/3634d218-d77e-4aea-a663-6956de2a8cc1)
这里整理方式当前版本默认是复制，希望添加自定义默认值
实现效果，根据参数设置，默认移动方式为硬链接，参考前面版本

**Comment by wikrin** [comment]
见 jxxghp/MoviePilot-Frontend#251
