### ISSUE TITLE
关于目录的设置极其难以理解和使用,希望简化设置

### ISSUE THREAD

**Issue by k1z** [jxxghp/MoviePilot#3259]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载资源没有放到期望中的目的地
![Snipaste_2024-11-27_11-04-19](https://github.com/user-attachments/assets/dd3ed43d-f038-4233-ace1-5cc8550fa50c)
![Snipaste_2024-11-27_11-05-04](https://github.com/user-attachments/assets/8d600f3a-ff27-446e-b138-bb5d342a932f)
![Snipaste_2024-11-27_11-05-27](https://github.com/user-attachments/assets/72cda1f0-6e9c-4a72-943a-139fb1fe4aa0)

**Comment by hbq0405** [comment]
![image](https://github.com/user-attachments/assets/5d745a56-28ab-4a97-a179-11ede00c0919)
认识汉字不？

**Comment by k1z** [comment]
> ![image](https://private-user-images.githubusercontent.com/119646284/390255095-5d745a56-28ab-4a97-a179-11ede00c0919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODc4MTQsIm5iZiI6MTczMjY4NzUxNCwicGF0aCI6Ii8xMTk2NDYyODQvMzkwMjU1MDk1LTVkNzQ1YTU2LTI4YWItNGE5Ny1hMTc5LTExZWRlMDBjMDkxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwNjA1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWNmOWY0NDI0MDcyN2ZhMWE0NDg1NGI5NmUxMGI3NTg3OWMyNTUzMTI5MWEwMDRmZDg1NzNkYjM0M2Q5YTk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.icqEityPk9I4nNWGEgbN1_VlkRt87iDAxXqoc65pGa4) 认识汉字不？

这个配置关闭后会自动打开

**Comment by k1z** [comment]
> ![image](https://private-user-images.githubusercontent.com/119646284/390255095-5d745a56-28ab-4a97-a179-11ede00c0919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTkyNjAsIm5iZiI6MTczMjY5ODk2MCwicGF0aCI6Ii8xMTk2NDYyODQvMzkwMjU1MDk1LTVkNzQ1YTU2LTI4YWItNGE5Ny1hMTc5LTExZWRlMDBjMDkxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwOTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjhiZmFlNjhjM2U3MjM1YjFiNThhN2M0ODlkNDJlYTMyYzJjNmQ1M2U0ZjBhMTViM2ExNDhmMzJiZmQ1ODc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.riEidGSwPDtb3ANyeQRPn7V5Q2wlcUxl_A6IZitNBbc) 认识汉字不？

哥 我玻璃心， 你能好好说话不？ qb这个配置我关闭过 然后确定了， 没注意外边还有个确定要点， 所以这个配置没保存成功才这样的。

**Comment by hbq0405** [comment]
> 喷子真是无处不在，人家只是提个建议。说实话不否认这个项目的成功和实用，但是用户引导确实有问题，要不然群里和issue区不会有这么多人问。(当然也有可能是故意为之，提高使用门槛，这就另当别论)

那你意思，回答问题还需要卑微点？
小时候老师教育你，你怎么不说老师是喷子？
三人行必有我师，获取别人的知识不要理所当然。玻璃心就别来提issues了，自己的失误造成的问题，我给你指出问题所在，是不是还要用上谦卑的语气？
直接去问GPT吧，你问他1+1等于几，他也不会喷你。

**Comment by yfdoor** [comment]
> > 喷子真是无处不在，人家只是提个建议。说实话不否认这个项目的成功和实用，但是用户引导确实有问题，要不然群里和issue区不会有这么多人问。(当然也有可能是故意为之，提高使用门槛，这就另当别论)
> 
> 那你意思，回答问题还需要卑微点？ 小时候老师教育你，你怎么不说老师是喷子？ 三人行必有我师，获取别人的知识不要理所当然。玻璃心就别来提issues了，自己的失误造成的问题，我给你指出问题所在，是不是还要用上谦卑的语气？ 直接去问GPT吧，你问他1+1等于几，他也不会喷你。

你也说了是 "回答问题"，可是你这是给人家回答问题吗？回答问题不需要卑微，倒也不用高高在上。
说话的语气往往代表着他的教养，三人行必有我师，师之大者在于传道解惑，而不是自以为稍微比他人懂点就到处口无遮拦。github 的精神在于分享与传递。

我前面也说了这个项目设置很复杂，很多人可能就是会有问题，你若是能给予别人帮助那你获得的一定比现在多。祝好！

**Comment by cng10001** [comment]
还有人帮着说话的，尊重是互相的。不知道作者牵头，众多人提供贡献的项目，看到标题内这样的用词`关于目录的设置极其难以理解和使用,希望简化设置`这样的用户反馈是会更开心还是更有动力呢。
提问前到底有没有好好了解呢，如果只有`极其难用`、`下载有问题`的体验是代表你个人，那其实也大可不必专门来说道吧！如果想提意见反馈问题就应该好好提，不说一定要怎么建设性，但一句`难用，我理解不了，希望简化`是不是跟耍耍嘴皮子没有两样呢？

**Comment by Putarku** [comment]
现在的目录配置已经相当简单了，多看看wiki上的例子，自己手动转移一下，多测试一下真的不难理解

**Comment by Aqr-K** [comment]
@cng10001 各位没必要吵起来。有好的意见和建议，可以大胆提出来，咱会听取的，在合理范围内，会根据泛用性、需求量等因素，进行合理考虑的是否进行优化与更新的；当然了，目前对于wiki的相关更新确实是有点滞后了，后续也会慢慢的补充完整的，会尽量让每个人都能看懂。对于功能的优化方面，毕竟众口难调，每个人都有自己的使用习惯，每个人对项目设置的理解程度不同，肯定是无法做到满足所有人的，咱只能说尽量满足大众化需求；再小提一下，issus目前主要是问题反馈、提出功能改进、功能增加提案为主，所以请提iss的时候，也要做好分类。

**Comment by GilgameshXI** [comment]
采取折中办法吧，在qb创建好分类并且设置路径，要么关闭自动分类管理，qb中没有显示分类但是路径准确

**Comment by k1z** [comment]
> 现在的目录配置已经相当简单了，多看看wiki上的例子，自己手动转移一下，多测试一下真的不难理解

图里边可以看出我的目录设置是没有问题的。 主要问题出在qb自动管理下载目录这里， 因为我记得我这个设置是关闭了的。 所以我一直在尝试调整目录，但是发现都无效。 然后才来提issue。 我才看到qb的这个自动整理功能仍然是打开的， 我以为是一个bug， 这个设置无法关闭。准备再次提issue 的时候才发现在编辑完qb配置， 确定之后 外边还有一个确定要点， 配置才能保存。 
我觉得需要优化的点在这个两次确定这里。 或者目录配置中检测到下载器开启了自动整理，有个提示， 然后不允许修改本地路径这样。   

另外moviepilot确实是很优秀的项目，  也感谢各种开发者们的付出。 祝好！

**Comment by Noshnxindeluoxiaohei** [comment]
> > 现在的目录配置已经相当简单了，多看看wiki上的例子，自己手动转移一下，多测试一下真的不难理解
> 
> 图里边可以看出我的目录设置是没有问题的。 主要问题出在qb自动管理下载目录这里， 因为我记得我这个设置是关闭了的。 所以我一直在尝试调整目录，但是发现都无效。 然后才来提issue。 我才看到qb的这个自动整理功能仍然是打开的， 我以为是一个bug， 这个设置无法关闭。准备再次提issue 的时候才发现在编辑完qb配置， 确定之后 外边还有一个确定要点， 配置才能保存。 我觉得需要优化的点在这个两次确定这里。 或者目录配置中检测到下载器开启了自动整理，有个提示， 然后不允许修改本地路径这样。
> 
> 另外moviepilot确实是很优秀的项目， 也感谢各种开发者们的付出。 祝好！

这个目录设计的是很简单的，你不是也添对了么，不方便理解的是QB那里，其实做个提示就行了，还有就是QB的路径需要对应。还有的问题是选全部就失效。分类这里还是有BUG。
