### ISSUE TITLE
[错误报告]: MPv2在“文件管理”模块中，搜索框使用后，任意目录下的文件将完全消失！！！

### ISSUE THREAD

**Issue by Whys8182** [jxxghp/MoviePilot#3261]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

MPv2在“文件管理”模块中，选择任意一个目录，在搜索框中搜索任意一个存在的文件夹，会导致所有的目录下无法检查到任何文件、资源。
PS：在使用搜索框后，没有找到新生成的docker容器日志文件。

**Comment by hbq0405** [comment]
![image](https://github.com/user-attachments/assets/49655138-6847-46c5-ba97-e693833429b1)
没问题啊

**Comment by Whys8182** [comment]
再点进去
