### ISSUE TITLE
[错误报告]: 手动整理一个含有多种类型资源的目录，目的路径自动匹配不正确

### ISSUE THREAD

**Issue by zxh326** [jxxghp/MoviePilot#3270]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

手动整理一个目录

/media/pt => 含有多种资源，电影，国产剧 欧美剧 日韩剧 动漫

期望整理到

/media/{电影,国产剧，欧美日韩}

结果：

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/fcf9c10b-c39b-4268-875a-ea703842e9f5">

**Comment by wikrin** [comment]
和 #3256 原因一样

**Comment by zxh326** [comment]
我用最新的 v2 分之自己 build 了一个版本测试了下，还是有问题

> 和 #3256 原因一样
