### ISSUE TITLE
[错误报告]: 下载器开启自动分类管理后，影响IYUU自动辅种传递正确下载目录

### ISSUE THREAD

**Issue by GilgameshXI** [jxxghp/MoviePilot#3275]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.0

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

下载器开启自动分类管理后IYUU自动辅种只能下载到qb的默认保持路径，关闭自动分类管理后辅种的下载目录正常
开启前的
![屏幕截图 2024-11-28 172148](https://github.com/user-attachments/assets/707822f9-cd91-4b2c-938a-3ea25736b24b)
关闭后
![image](https://github.com/user-attachments/assets/f3a2ac05-03d8-447c-b49f-d6bccd3e08d7)

**Comment by GilgameshXI** [comment]
在V1版本我也是开启自动分类管理的，使用IYUU自动辅种是可以传递正确下载目录的。现在只能新建一个IYUU辅种专用的下载器关闭自动分类管理

**Comment by dlovew** [comment]
突然发现最新版本，qb5.0.1设置-下载里 
启用子分类：
在手动模式下使用分类路径：
这两个打勾即可在mp不打开自动分类开关的情况下正常辅种

**Comment by refined-fish** [comment]
我也遇到了这个问题，目前只能关闭MP设置中的qb自动分类，请问各位朋友这个问题是解决了还是无法解决呀

**Comment by hbq0405** [comment]
![Image](https://github.com/user-attachments/assets/dfb2385e-3e8a-498b-a128-68a8d7c1369c)
多加一个下载器辅种用，不开启QB自动分类管理
两个下载器是同一个容器，只是配置不同。

**Comment by refined-fish** [comment]
> ![Image](https://github.com/user-attachments/assets/dfb2385e-3e8a-498b-a128-68a8d7c1369c) 多加一个下载器辅种用，不开启QB自动分类管理 两个下载器是同一个容器，只是配置不同。

原来如此，不过我发现好像开启分类复用的话好像也能成功辅种（但前提是被辅种的种子必须已经拥有一个分类），这两者感觉还是新建一个辅种下载器更方便？

**Comment by refined-fish** [comment]
尝试了一下发现如果开启`下载器自动分类管理`，qb就会自己创建MP的各个分类，在MP里面也必须按照各个分类都创建一个目录才行，好像还有点麻烦🤣，不能像以前一样偷懒直接创建一个`全部`的目录

**Comment by hbq0405** [comment]
> 尝试了一下发现如果开启`下载器自动分类管理`，qb就会自己创建MP的各个分类，在MP里面也必须按照各个分类都创建一个目录才行，好像还有点麻烦🤣，不能像以前一样偷懒直接创建一个`全部`的目录

https://t.me/MoviePilot_Wiki/45

**Comment by refined-fish** [comment]
> > 尝试了一下发现如果开启`下载器自动分类管理`，qb就会自己创建MP的各个分类，在MP里面也必须按照各个分类都创建一个目录才行，好像还有点麻烦🤣，不能像以前一样偷懒直接创建一个`全部`的目录
> 
> https://t.me/MoviePilot_Wiki/45

完全懂了，感谢，我知道怎么回事了，如果不开启类型分类，其实就和QB的自动分类一样了

**Comment by refined-fish** [comment]
> https://t.me/MoviePilot_Wiki/45

不好意思再打扰您一下。我现在参考了目录采用“全部”的做法，不开启类型分类，并且开启qb自动分类管理，这样MP和QB都是在根目录创建“日番”“国产剧”之类的分类文件夹。

![Image](https://github.com/user-attachments/assets/16f11c29-7956-47cb-8ba1-8f3e2288adc0)

![Image](https://github.com/user-attachments/assets/346a2d65-ac30-4cb9-ab49-94c9120a2784)

IYUU自动辅种也是可以自动将新添加的种子下载目录正确识别，但是我遇到了一个新问题，就是辅种的种子不会自动开始。我已经尝试过了取消跳过校验，和跳过检验+自动开始，种子行为虽然会校验和不校验改变但是都是停止状态不会自动开始。

![Image](https://github.com/user-attachments/assets/b49fc5ac-1fa5-4d28-8e4f-6b1297cde597)

我已经检查过了插件的日志，日志显示跳过校验/自动开始并没有错误

![Image](https://github.com/user-attachments/assets/daf0aa2b-37a7-40e8-a734-b943511199be)

请问是否还有别的因素会影响这个行为呢🙏

**Comment by hbq0405** [comment]
> > https://t.me/MoviePilot_Wiki/45
> 
> 不好意思再打扰您一下。我现在参考了目录采用“全部”的做法，不开启类型分类，并且开启qb自动分类管理，这样MP和QB都是在根目录创建“日番”“国产剧”之类的分类文件夹。
> 
> ![Image](https://github.com/user-attachments/assets/16f11c29-7956-47cb-8ba1-8f3e2288adc0)
> 
> ![Image](https://github.com/user-attachments/assets/346a2d65-ac30-4cb9-ab49-94c9120a2784)
> 
> IYUU自动辅种也是可以自动将新添加的种子下载目录正确识别，但是我遇到了一个新问题，就是辅种的种子不会自动开始。我已经尝试过了取消跳过校验，和跳过检验+自动开始，种子行为虽然会校验和不校验改变但是都是停止状态不会自动开始。
> 
> ![Image](https://github.com/user-attachments/assets/b49fc5ac-1fa5-4d28-8e4f-6b1297cde597)
> 
> 我已经检查过了插件的日志，日志显示跳过校验/自动开始并没有错误
> 
> ![Image](https://github.com/user-attachments/assets/daf0aa2b-37a7-40e8-a734-b943511199be)
> 
> 请问是否还有别的因素会影响这个行为呢🙏

![Image](https://github.com/user-attachments/assets/1e243e36-f8b0-4a8f-91e6-02dd5f1d7f6b)
开启了自动开始会有校验检查任务，你确认你开启了自动开始？

**Comment by refined-fish** [comment]
>  开启了自动开始会有校验检查任务，你确认你开启了自动开始？

是的

![Image](https://github.com/user-attachments/assets/3fd7a6e3-cde4-4cce-90dd-bf1844f11544)

**Comment by manzhu** [comment]
请问这个问题后来有解决方案了么？
