### ISSUE TITLE
[错误报告]: 自定义站点信息浦园PT，增加站点刷流后，每次重启套件的时候浦园PT不会被默认勾选，每次重启都需要手动勾选站点刷流，，请问这个是BUG吗？

### ISSUE THREAD

**Issue by hhxxc** [jxxghp/MoviePilot#3276]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.9.17

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自定义站点信息浦元PT，增加站点刷流后，每次重启套件的时候浦元PT不会被默认勾选，每次重启都需要手动勾选站点刷流，，请问这个是BUG吗？

**Comment by HUHAIzxc** [comment]
【INFO】2024-11-29 08:51:50,746 - brushflow - 站点刷流Check定时服务启动，时间间隔 5 分钟
【INFO】2024-11-29 08:51:50,746 - brushflow - 站点刷流Brush定时服务启动，时间间隔 10 分钟
}]", "group_site_configs": {} }
    "site_hr_active": true
    "qb_first_last_piece": true,
    "auto_qb_category": true,
    "qb_category": "刷流",
    "proxy_delete": false,
    "proxy_download": false,
    "save_path": "/downloads/site1",
    "seed_inactivetime": "",
    "seed_avgspeed": "",
    "download_time": "",
    "seed_size": "",
    "seed_ratio": "",
    "hr_seed_time": 144,
    "seed_time": 120,
    "pubtime": "5-120",
    "seeder": "1",
    "size": "10-500",
    "exclude": "",
    "include": "",
    "hr": "yes",
    "freeleech": "free",
    "sitename": "站点3",
}, {
    "hr_seed_time": 144
    "proxy_download": true,
    "save_path": "/downloads/site2",
    "seed_time": 96,
    "pubtime": "5-120",
    "seeder": "5-10",
    "size": "10-500",
    "hr": "yes",
    "sitename": "站点2",
}, {
    "hr_seed_time": 144
    "seed_time": 96,
    "sitename": "站点1",
[{
// 注意无关内容需使用 // 注释
// 如与全局保持一致的配置项，请勿在站点配置中配置
【DEBUG】2024-11-29 08:51:50,635 - brushflow - 没有开启站点独立配置，配置信息：{ "enabled": true, "notify": true, "onlyonce": false, "brushsites": [3, 2, 1, 4], "downloader": "qbittorrent", "disksize": 3072, "freeleech": "free", "hr": "yes", "maxupspeed": None, "maxdlspeed": None, "maxdlcount": None, "include": None, "exclude": None, "size": None, "seeder": None, "pubtime": None, "seed_time": 72, "hr_seed_time": None, "seed_ratio": "", "seed_size": None, "download_time": None, "seed_avgspeed": None, "seed_inactivetime": None, "delete_size_range": None, "up_speed": None, "dl_speed": None, "auto_archive_days": None, "save_path": None, "clear_task": false, "archive_task": false, "delete_except_tags": "MOVIEPILOT,H&R", "except_subscribe": true, "brush_sequential": false, "proxy_download": false, "proxy_delete": false, "active_time_range": None, "downloader_monitor": false, "qb_category": None, "auto_qb_category": true, "qb_first_last_piece": false, "site_hr_active": false, "brush_tag": "刷流", "enable_site_config": false, "site_config": "// 以下为配置示例，请参考：https://github.com/InfinityPacer/MoviePilot-Plugins/blob/main/plugins/brushflowlowfreq/README.md 进行配置
【INFO】2024-11-29 08:49:58,168 - brushflow - 站点刷流Check定时服务启动，时间间隔 5 分钟
【INFO】2024-11-29 08:49:58,167 - brushflow - 站点刷流Brush定时服务启动，时间间隔 10 分钟
}]", "group_site_configs": {} }
    "site_hr_active": true
    "qb_first_last_piece": true,
    "auto_qb_category": true,
    "qb_category": "刷流",
    "proxy_delete": false,
    "proxy_download": false,
    "save_path": "/downloads/site1",
    "seed_inactivetime": "",
    "seed_avgspeed": "",
    "download_time": "",
    "seed_size": "",
    "seed_ratio": "",
    "hr_seed_time": 144,
    "seed_time": 120,
    "pubtime": "5-120",
    "seeder": "1",
    "size": "10-500",
    "exclude": "",
    "include": "",
    "hr": "yes",
    "freeleech": "free",
    "sitename": "站点3",
}, {
    "hr_seed_time": 144
    "proxy_download": true,
    "save_path": "/downloads/site2",
    "seed_time": 96,
    "pubtime": "5-120",
    "seeder": "5-10",
    "size": "10-500",
    "hr": "yes",
    "sitename": "站点2",
}, {
    "hr_seed_time": 144
    "seed_time": 96,
    "sitename": "站点1",
[{
// 注意无关内容需使用 // 注释
// 如与全局保持一致的配置项，请勿在站点配置中配置
【DEBUG】2024-11-29 08:49:57,864 - brushflow - 没有开启站点独立配置，配置信息：{ "enabled": true, "notify": true, "onlyonce": false, "brushsites": [3, 2, 1], "downloader": "qbittorrent", "disksize": 3072, "freeleech": "free", "hr": "yes", "maxupspeed": None, "maxdlspeed": None, "maxdlcount": None, "include": None, "exclude": None, "size": None, "seeder": None, "pubtime": None, "seed_time": 72, "hr_seed_time": None, "seed_ratio": "", "seed_size": None, "download_time": None, "seed_avgspeed": None, "seed_inactivetime": None, "delete_size_range": None, "up_speed": None, "dl_speed": None, "auto_archive_days": None, "save_path": None, "clear_task": false, "archive_task": false, "delete_except_tags": "MOVIEPILOT,H&R", "except_subscribe": true, "brush_sequential": false, "proxy_download": false, "proxy_delete": false, "active_time_range": None, "downloader_monitor": false, "qb_category": None, "auto_qb_category": true, "qb_first_last_piece": false, "site_hr_active": false, "brush_tag": "刷流",

**Comment by HUHAIzxc** [comment]
他重启套件不会勾选站点4

**Comment by HUHAIzxc** [comment]
![1732843709351](https://github.com/user-attachments/assets/4e5b0c11-bbc7-46d4-a872-b4fe01105a41)
![1732843720466](https://github.com/user-attachments/assets/6284ae61-c6e1-4dbf-8db6-57b235d6d8bc)

**Comment by HUHAIzxc** [comment]
![Uploading 1732843792853.jpg…]()

**Comment by HUHAIzxc** [comment]
因为浦园是自定义的站点，不在适配站内！

**Comment by HUHAIzxc** [comment]
> 自定义站点时配置"public": false 应该就可以了，因为刷流插件默认排除了公开站点，仅刷PT站。

请问大哥，这个"public": false  在哪个文件类里啊，目录是啥

**Comment by cddjr** [comment]
> > 自定义站点时配置"public": false 应该就可以了，因为刷流插件默认排除了公开站点，仅刷PT站。
> 
> 请问大哥，这个"public": false 在哪个文件类里啊，目录是啥@cddjr

看来你不是自己写的自定义索引规则吧，那直接把索引插件里面那一大串像乱码一样的文本发出来就行了，我修改好了给你试试看

**Comment by HUHAIzxc** [comment]
njtupt.top|ewogICAgImlkIjogIk5KVFVQVCIsCiAgICAibmFtZSI6ICLmtablm60iLAogICAgImRvbWFpbiI6ICJodHRwczovL25qdHVwdC50b3AvIiwKICAgICJlbmNvZGluZyI6ICJVVEYtOCIsCiAgICAicHVibGljIjogZmFsc2UsCiAgICAic2VhcmNoIjogewogICAgICAicGF0aHMiOiBbCiAgICAgICAgewogICAgICAgICAgInBhdGgiOiAidG9ycmVudHMucGhwIiwKICAgICAgICAgICJtZXRob2QiOiAiZ2V0IgogICAgICAgIH0KICAgICAgXSwKICAgICAgInBhcmFtcyI6IHsKICAgICAgICAic2VhcmNoIjogIntrZXl3b3JkfSIsCiAgICAgICAgInNlYXJjaF9hcmVhIjogNAogICAgICB9LAogICAgICAiYmF0Y2giOiB7CiAgICAgICAgImRlbGltaXRlciI6ICIgIiwKICAgICAgICAic3BhY2VfcmVwbGFjZSI6ICJfIgogICAgICB9CiAgICB9LAogICAgImNhdGVnb3J5IjogewogICAgICAibW92aWUiOiBbCiAgICAgICAgewogICAgICAgICAgImlkIjogNDAxLAogICAgICAgICAgImNhdCI6ICJNb3ZpZXMiLAogICAgICAgICAgImRlc2MiOiAiTW92aWVz55S15b2xIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImlkIjogNDA1LAogICAgICAgICAgImNhdCI6ICJBbmltZSIsCiAgICAgICAgICAiZGVzYyI6ICJBbmltYXRpb25z5Yqo5ryrIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImlkIjogNDA0LAogICAgICAgICAgImNhdCI6ICJEb2N1bWVudGFyeSIsCiAgICAgICAgICAiZGVzYyI6ICJEb2N1bWVudGFyaWVz57qq5b2V54mHIgogICAgICAgIH0KICAgICAgXSwKICAgICAgInR2IjogWwogICAgICAgIHsKICAgICAgICAgICJpZCI6IDQwMiwKICAgICAgICAgICJjYXQiOiAiVFYiLAogICAgICAgICAgImRlc2MiOiAiVFYgU2VyaWVz55S16KeG5YmnIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgImlkIjogNDAzLAogICAgICAgICAgImNhdCI6ICJUViIsCiAgICAgICAgICAiZGVzYyI6ICJUViBTaG93c+e7vOiJuiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJpZCI6IDQwNCwKICAgICAgICAgICJjYXQiOiAiRG9jdW1lbnRhcnkiLAogICAgICAgICAgImRlc2MiOiAiRG9jdW1lbnRhcmllc+e6quW9leeJhyIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJpZCI6IDQwNSwKICAgICAgICAgICJjYXQiOiAiQW5pbWUiLAogICAgICAgICAgImRlc2MiOiAiQW5pbWF0aW9uc+WKqOa8qyIKICAgICAgICB9CiAgICAgIF0KICAgIH0sCiAgICAidG9ycmVudHMiOiB7CiAgICAgICJsaXN0IjogewogICAgICAgICJzZWxlY3RvciI6ICJ0YWJsZS50b3JyZW50cyA+IHRyOmhhcyhcInRhYmxlLnRvcnJlbnRuYW1lXCIpIgogICAgICB9LAogICAgICAiZmllbGRzIjogewogICAgICAgICJpZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwiZGV0YWlscy5waHA/aWQ9XCJdIiwKICAgICAgICAgICJhdHRyaWJ1dGUiOiAiaHJlZiIsCiAgICAgICAgICAiZmlsdGVycyI6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICJuYW1lIjogInJlX3NlYXJjaCIsCiAgICAgICAgICAgICAgImFyZ3MiOiBbCiAgICAgICAgICAgICAgICAiXFxkKyIsCiAgICAgICAgICAgICAgICAwCiAgICAgICAgICAgICAgXQogICAgICAgICAgICB9CiAgICAgICAgICBdCiAgICAgICAgfSwKICAgICAgICAidGl0bGVfZGVmYXVsdCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwiZGV0YWlscy5waHA/aWQ9XCJdIgogICAgICAgIH0sCiAgICAgICAgInRpdGxlX29wdGlvbmFsIjogewogICAgICAgICAgIm9wdGlvbmFsIjogdHJ1ZSwKICAgICAgICAgICJzZWxlY3RvciI6ICJhW3RpdGxlXVtocmVmKj1cImRldGFpbHMucGhwP2lkPVwiXSIsCiAgICAgICAgICAiYXR0cmlidXRlIjogInRpdGxlIgogICAgICAgIH0sCiAgICAgICAgInRpdGxlIjogewogICAgICAgICAgInRleHQiOiAieyUgaWYgZmllbGRzWyd0aXRsZV9vcHRpb25hbCddICV9e3sgZmllbGRzWyd0aXRsZV9vcHRpb25hbCddIH19eyUgZWxzZSAlfXt7IGZpZWxkc1sndGl0bGVfZGVmYXVsdCddIH19eyUgZW5kaWYgJX0iCiAgICAgICAgfSwKICAgICAgICAiZGV0YWlscyI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwiZGV0YWlscy5waHA/aWQ9XCJdIiwKICAgICAgICAgICJhdHRyaWJ1dGUiOiAiaHJlZiIKICAgICAgICB9LAogICAgICAgICJkb3dubG9hZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJhW2hyZWYqPVwiZG93bmxvYWQucGhwP2lkPVwiXSIsCiAgICAgICAgICAiYXR0cmlidXRlIjogImhyZWYiCiAgICAgICAgfSwKICAgICAgICAiaW1kYmlkIjogewogICAgICAgICAgInNlbGVjdG9yIjogImRpdi5pbWRiXzEwMCA+IGEiLAogICAgICAgICAgImF0dHJpYnV0ZSI6ICJocmVmIiwKICAgICAgICAgICJmaWx0ZXJzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgIm5hbWUiOiAicmVfc2VhcmNoIiwKICAgICAgICAgICAgICAiYXJncyI6IFsKICAgICAgICAgICAgICAgICJ0dFxcZCsiLAogICAgICAgICAgICAgICAgMAogICAgICAgICAgICAgIF0KICAgICAgICAgICAgfQogICAgICAgICAgXQogICAgICAgIH0sCiAgICAgICAgImRhdGVfZWxhcHNlZCI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZDpudGgtY2hpbGQoNCkgPiBzcGFuIiwKICAgICAgICAgICJvcHRpb25hbCI6IHRydWUKICAgICAgICB9LAogICAgICAgICJkYXRlX2FkZGVkIjogewogICAgICAgICAgInNlbGVjdG9yIjogInRkOm50aC1jaGlsZCg0KSA+IHNwYW4iLAogICAgICAgICAgImF0dHJpYnV0ZSI6ICJ0aXRsZSIsCiAgICAgICAgICAib3B0aW9uYWwiOiB0cnVlCiAgICAgICAgfSwKICAgICAgICAic2l6ZSI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZDpudGgtY2hpbGQoNSkiCiAgICAgICAgfSwKICAgICAgICAic2VlZGVycyI6IHsKICAgICAgICAgICJzZWxlY3RvciI6ICJ0ZDpudGgtY2hpbGQoNikiCiAgICAgICAgfSwKICAgICAgICAibGVlY2hlcnMiOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAidGQ6bnRoLWNoaWxkKDcpIgogICAgICAgIH0sCiAgICAgICAgImdyYWJzIjogewogICAgICAgICAgInNlbGVjdG9yIjogInRkOm50aC1jaGlsZCg4KSIKICAgICAgICB9LAogICAgICAgICJkb3dubG9hZHZvbHVtZWZhY3RvciI6IHsKICAgICAgICAgICJjYXNlIjogewogICAgICAgICAgICAiaW1nLnByb19mcmVlIjogMCwKICAgICAgICAgICAgImltZy5wcm9fZnJlZTJ1cCI6IDAsCiAgICAgICAgICAgICJpbWcucHJvXzUwcGN0ZG93biI6IDAuNSwKICAgICAgICAgICAgImltZy5wcm9fNTBwY3Rkb3duMnVwIjogMC41LAogICAgICAgICAgICAiaW1nLnByb18zMHBjdGRvd24iOiAwLjMsCiAgICAgICAgICAgICIqIjogMQogICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgInVwbG9hZHZvbHVtZWZhY3RvciI6IHsKICAgICAgICAgICJjYXNlIjogewogICAgICAgICAgICAiaW1nLnByb181MHBjdGRvd24ydXAiOiAyLAogICAgICAgICAgICAiaW1nLnByb19mcmVlMnVwIjogMiwKICAgICAgICAgICAgImltZy5wcm9fMnVwIjogMiwKICAgICAgICAgICAgIioiOiAxCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAiZGVzY3JpcHRpb24iOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAidGQ6bnRoLWNoaWxkKDIpID4gdGFibGUgPiB0ciA+IHRkLmVtYmVkZGVkID4gc3BhbltzdHlsZV0iLAogICAgICAgICAgImNvbnRlbnRzIjogLTEKICAgICAgICB9LAogICAgICAgICJsYWJlbHMiOiB7CiAgICAgICAgICAic2VsZWN0b3IiOiAidGQ6bnRoLWNoaWxkKDIpID4gdGFibGUgPiB0ciA+IHRkLmVtYmVkZGVkID4gc3Bhbi50YWdzIgogICAgICAgIH0KICAgICAgfQogICAgfQogIH0=

**Comment by HUHAIzxc** [comment]
> > > 自定义站点时配置"public": false 应该就可以了，因为刷流插件默认排除了公共站点，只能刷PT站。
> > 
> > 
> > 请问大哥，这个“public”: false 在哪个文件类里啊，目录是啥@cddjr
> 
> 看来你不是自己写的自定义索引配置吧，那直接把索引插件里面那一大串像乱码一样的配置文本发出来就行了，我修改一下好给你试试看

辛苦大佬了

**Comment by HUHAIzxc** [comment]
[
![1732846353585](https://github.com/user-attachments/assets/46ae5f43-8deb-4ab2-8a36-2ce2789b1d9a)
](url)

**Comment by cddjr** [comment]
看了下已经是public为false了，可能是别的原因造成，你可以试试v2还会不会有这个问题

**Comment by hhxxc** [comment]
> 查看下已经是public为false了，可能是其他原因造成的，你可以试试v2也不会有这个问题

xiexie 大哥，我测像是插件启动顺序的问题，如果自定义站点禁用或者晚于刷流插件运行 他就抓取不到这个自定义站的信息。。大哥知道在哪可以改插件运行顺序吗？

**Comment by cddjr** [comment]
> > 查看下已经是public为false了，可能是其他原因造成的，你可以试试v2也不会有这个问题
> 
> xiexie 大哥，我测像是插件启动顺序的问题，如果自定义站点禁用或者晚于刷流插件运行 他就抓取不到这个自定义站的信息。。大哥知道在哪可以改插件运行顺序吗？@cddjr

是的，我也怀疑是插件顺序导致的。目前v2有调整过这个启动顺序，或许能解决。 另外v1现在不维护了，所以除非这个bug能在v2重现

**Comment by hhxxc** [comment]
谢谢，我试一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 景大侠 ***@***.***&gt;
发送时间: 2024年11月29日 11:32
收件人: jxxghp/MoviePilot ***@***.***&gt;
抄送: guofuc ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jxxghp/MoviePilot] [错误报告]: 自定义站点信息浦园PT，增加站点刷流后，每次重启套件的时候浦园PT不会被默认勾选，每次重启都需要手动勾选站点刷流，，请问这个是BUG吗？ (Issue #3276)
