### ISSUE TITLE
[Feature Request]: 希望重启后不要重置系统服务的运行时间

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#3280]
### 当前程序版本

v2 latest

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

如果被重启重置更新打断，这些服务重启后都会重新计算时间，能否还是按原来的执行时间，感觉这样更符合使用直觉一些
![PixPin_2024-11-29_09-58-46](https://github.com/user-attachments/assets/0bfea597-ceed-4a0e-98a1-130142776f15)

**Comment by hbq0405** [comment]
![image](https://github.com/user-attachments/assets/e2ca9a3f-a03f-4332-946c-3353a630277e)
更新最新版，用这个插件配置
