### ISSUE TITLE
企业微信突然报错

### ISSUE THREAD

**Issue by xxtyyq** [jxxghp/MoviePilot#3289]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

企业微信早上九点的时候还运行无问题，一上午未通知，突然发现日志里报错，显示“获取微信access_token失败，错误信息：获取微信access_token失败，网络连接失败”，请问这是什么情况？

**Comment by xxtyyq** [comment]
找到问题了，好像是wxchat-Docker出问题了，不通过它代理反而没问题了

**Comment by JavaZeroo** [comment]
我是删除了微信代理,，就报这个错

**Comment by xxtyyq** [comment]
> 我是删除了微信代理,，就报这个错

哈哈，那好奇怪，正好相反
