### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by lingduMOD** [jxxghp/MoviePilot#3294]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.1

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

群晖SA6400--1、web页面一直报目录监控服务异常，ssh执行命令不能恢复
                       2、compose已经映射了重启命令，在web界面重启后，群晖docker会报错,必须docker手动重启

重启后docker报错日志:
MoviePilot
date,stream,content
2024/12/01 10:53:11,stdout,Shutting down...

2024/12/01 10:53:11,stderr,INFO:     Finished server process [74]

2024/12/01 10:53:11,stderr,INFO:     Application shutdown complete.

2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-36, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-33, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-30, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-27, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-24, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-21, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-18, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-15, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-12, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-9, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-6, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[31mERROR:[0m   monitor.py - 停止目录监控服务出现了错误：cannot join thread before it is started

2024/12/01 10:53:11,stderr,"[32mINFO:[0m    monitor.py - 正在停止目录监控服务：<InotifyObserver(Thread-3, initial daemon)>...
"
2024/12/01 10:53:11,stderr,[32mINFO:[0m    scheduler.py - 定时任务停止完成

2024/12/01 10:53:11,stderr,[32mINFO:[0m    scheduler.py - 正在停止定时任务...

2024/12/01 10:53:11,stderr,[32mINFO:[0m    display.py - 虚拟显示已停止

2024/12/01 10:53:11,stderr,[32mINFO:[0m    display.py - 正在停止虚拟显示...

2024/12/01 10:53:11,stderr,[32mINFO:[0m    event.py - 事件处理停止完成

2024/12/01 10:53:08,stderr,[32mINFO:[0m    event.py - 正在停止事件处理...

2024/12/01 10:53:08,stderr,[32mINFO:[0m    plugin.py - 插件停止完成

2024/12/01 10:53:08,stderr,"2024/12/01 10:53:08 [error] 66#66: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.66.21, server: moviepilot, request: \"GET /api/v1/login/wallpapers HTTP/1.1\", upstream: \"http://127.0.0.1:9901/api/v1/login/wallpapers\", host: \"192.168.66.12:9900\"
"
2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 插件服务停止完成

2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 插件未启用缓存，无须清除

2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 尝试清除插件缓存...

2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 插件未启用服务调度器，无须停止

2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 尝试停止插件服务调度器...

2024/12/01 10:53:08,stderr,[32mINFO:[0m    downloaderhelper - 尝试停止插件服务...

2024/12/01 10:53:08,stderr,[32mINFO:[0m    plugin.py - 正在停止所有插件...

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - 所有模块停止完成

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：WechatModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：WebPushModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：VoceChatModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：TransmissionModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：TheTvDbModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：TheMovieDbModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：TelegramModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：SynologyChatModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：SubtitleModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：SlackModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：QbittorrentModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：PlexModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：JellyfinModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：IndexerModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：FilterModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：FileManagerModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：FanartModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：EmbyModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：DoubanModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - Moudle Stoped：BangumiModule

2024/12/01 10:53:08,stderr,[32mINFO:[0m    module.py - 正在停止所有模块...

2024/12/01 10:53:08,stderr,"asyncio.exceptions.CancelledError: Task cancelled, timeout graceful shutdown exceeded
"
2024/12/01 10:53:08,stderr,           ^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,    return await future

2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 2441, in run_sync_in_worker_thread
"
2024/12/01 10:53:08,stderr,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,    return await get_async_backend().run_sync_in_worker_thread(

2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/anyio/to_thread.py\", line 56, in run_sync
"
2024/12/01 10:53:08,stderr,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,"    return await anyio.to_thread.run_sync(func, *args)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/concurrency.py\", line 41, in run_in_threadpool
"
2024/12/01 10:53:08,stderr,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,"    return await run_in_threadpool(dependant.call, **values)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/fastapi/routing.py\", line 165, in run_endpoint_function
"
2024/12/01 10:53:08,stderr,                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,    raw_response = await run_endpoint_function(

2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/fastapi/routing.py\", line 237, in app
"
2024/12/01 10:53:08,stderr,               ^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,    response = await func(request)

2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/routing.py\", line 66, in app
"
2024/12/01 10:53:08,stderr,"    await self.app(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/routing.py\", line 276, in handle
"
2024/12/01 10:53:08,stderr,"    await route.handle(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/routing.py\", line 718, in __call__
"
2024/12/01 10:53:08,stderr,"    await self.app(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py\", line 18, in __call__
"
2024/12/01 10:53:08,stderr,"    await self.app(scope, receive, sender)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 68, in __call__
"
2024/12/01 10:53:08,stderr,"    await self.app(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py\", line 83, in __call__
"
2024/12/01 10:53:08,stderr,"    await self.app(scope, receive, _send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 162, in __call__
"
2024/12/01 10:53:08,stderr,"    await self.middleware_stack(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/starlette/applications.py\", line 122, in __call__
"
2024/12/01 10:53:08,stdout,INFO:     192.168.66.21:0 - "GET /api/v1/system/restart HTTP/1.1" 500 Internal Server Error

2024/12/01 10:53:08,stderr,"    await super().__call__(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/fastapi/applications.py\", line 276, in __call__
"
2024/12/01 10:53:08,stderr,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,"    return await self.app(scope, receive, send)
"
2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 78, in __call__
"
2024/12/01 10:53:08,stderr,             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024/12/01 10:53:08,stderr,    result = await app(  # type: ignore[func-returns-value]

2024/12/01 10:53:08,stderr,"  File \"/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py\", line 428, in run_asgi
"
2024/12/01 10:53:08,stderr,Traceback (most recent call last):

2024/12/01 10:53:08,stderr,ERROR:    Exception in ASGI application

2024/12/01 10:53:08,stderr,INFO:     Waiting for application shutdown.

2024/12/01 10:53:08,stderr,"ERROR:    Cancel 1 running task(s), timeout graceful shutdown exceeded
"
2024/12/01 10:53:06,stderr,"2024/12/01 10:53:06 [error] 64#64: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.66.21, server: moviepilot, request: \"GET /api/v1/system/message HTTP/1.1\", upstream: \"http://127.0.0.1:9901/api/v1/system/message\", host: \"192.168.66.12:9900\"
"
2024/12/01 10:53:03,stderr,INFO:     Waiting for connections to close. (CTRL+C to force quit)

2024/12/01 10:53:02,stderr,INFO:     Shutting down

2024/12/01 10:53:02,stdout,127.0.0.1 - - [01/Dec/2024:10:53:02 +0800] "GET /v1.43/containers/1d2928923f87d3c86e1fce2c3ede8d3167a0f4eaf5c2288ae1224ffcf45f667e/json HTTP/1.1" 200 9358 "-" "docker-sdk-python/6.1.3"

2024/12/01 10:53:02,stdout,127.0.0.1 - - [01/Dec/2024:10:53:02 +0800] "GET /version HTTP/1.1" 200 770 "-" "docker-sdk-python/6.1.3"

compose配置：
services:
  MoviePilot:
    image: jxxghp/moviepilot-v2:latest
    container_name: MoviePilot
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/volume1/docker/MoviePilot_V2/core:/moviepilot'
      - '/volume1/docker/MoviePilot_V2/config:/config'
      - '/volume1/docker/MoviePilot_V2/plugins:/app/plugins'
      - '/volume4/video:/downloads'
      - '/volume1/docker/transmission/data/torrents:/torrents'
      - '/volume1/docker/qbittorrent/appdata/qBittorrent/BT_backup:/BT_backup'
    environment: 
      - 'NGINX_PORT=9900'
      - 'PORT=9901'
      - 'PUID=0'
      - 'PGID=0'
      - 'UMASK=022' 
      - 'TZ=Asia/Shanghai'
      - 'SUPERUSER=MOD'
      - 'PROXY_HOST=http://192.168.66.2:7890'
      - 'AUTH_SITE=iyuu'
      - 'IYUU_SIGN='
      - 'ZMPT_UID='
      - 'ZMPT_PASSKEY='
      - 'API_TOKEN=moviepilot83796668'
      - 'MOVIEPILOT_AUTO_UPDATE=true'
      - 'AUTO_UPDATE_RESOURCE=true'
      - 'DOWNLOAD_SUBTITLE=true'
      #- 'DOH_ENABLE=false'
      #- 'DEBUG=true'
      - 'MOVIE_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/{{title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{% if edition %} - {{edition}}{% endif %}{% if videoCodec %} - {{videoCodec}}{% endif %}{% if audioCodec %} - {{audioCodec}}{% endif %}{% if customization %} - {{customization}}{% endif %}{% if releaseGroup %} - {{releaseGroup}}{% endif %}{{fileExt}}'
      - 'TV_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/Season {{season}}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{% if edition %} - {{edition}}{% endif %}{% if videoCodec %} - {{videoCodec}}{% endif %}{% if audioCodec %} - {{audioCodec}}{% endif %}{% if customization %} - {{customization}}{% endif %}{% if releaseGroup %} - {{releaseGroup}}{% endif %}{{fileExt}}'
      - 'PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins/,https://github.com/thsrite/MoviePilot-Plugins/,https://github.com/honue/MoviePilot-Plugins/,https://github.com/InfinityPacer/MoviePilot-Plugins/,https://github.com/dandkong/MoviePilot-Plugins/,https://github.com/Aqr-K/MoviePilot-Plugins/,https://github.com/AnjoyLi/MoviePilot-Plugins/,https://github.com/WithdewHua/MoviePilot-Plugins/,https://github.com/HankunYu/MoviePilot-Plugins/,https://github.com/baozaodetudou/MoviePilot-Plugins/,https://github.com/almus2zhang/MoviePilot-Plugins/,https://github.com/Pixel-LH/MoviePilot-Plugins/,https://github.com/lightolly/MoviePilot-Plugins/,https://github.com/suraxiuxiu/MoviePilot-Plugins/,https://github.com/gxterry/MoviePilot-Plugins/,https://github.com/hotlcc/MoviePilot-Plugins-Third/,https://github.com/boeto/MoviePilot-Plugins/,https://github.com/xiangt920/MoviePilot-Plugins/,https://github.com/xcehnz/MoviePilot-Plugins/,https://github.com/yideng966/MoviePilot-Plugins/,https://github.com/loongcheung/MoviePilot-Plugins/,https://github.com/kanekicany/MoviePilot-Plugins/,https://github.com/zoffyultraman/MoviePilot-Plugins/,https://github.com/dadinet/MoviePilot-Plugins/,https://github.com/imaliang/MoviePilot-Plugins/，https://github.com/boeto/MoviePilot-Plugins/'
      #- 'DEV=true'
    network_mode: host
    restart: always

### 发生问题时系统日志和配置文件

```bash
sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,963 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,961 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,945 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,943 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,941 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,939 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,937 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,935 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,933 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,930 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,928 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
                             
                             sudo sysctl -p
                             echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf
                             echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
【WARNING】2024-12-01 10:43:53,926 - monitor.py - 目录监控服务启动出现异常：[Errno 28] inotify watch limit reached，请在宿主机上（不是docker容器内）执行以下命令并重启：
```

**Comment by cng10001** [comment]
https://wiki.movie-pilot.org/zh/ready
![扣扣_2024-12-01_12-53-38](https://github.com/user-attachments/assets/4e5fdebc-b7cf-414d-975f-2c20590f5740)
这个命令你好像没有配置
