### ISSUE TITLE
[错误报告]: 正在下载界面Transmission不显示任务

### ISSUE THREAD

**Issue by OpsDarren** [jxxghp/MoviePilot#331]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.9

### 问题类型

主程序运行问题

### 问题描述

下载器我使用的是Transmission 版本：3.00 (bb6b5a062e)，仪表板 > 实时速率显示正常，但是整理 > 正在下载内无法看到内容，显示404。之前测试qBittorrent这里是OK的。
但是目前看来，docker logs也没有显示下载器异常。
实际上造成的结果就是，Transmission下载完成，无法自动硬链接转移入库。

### 发生问题时系统日志和配置文件

```bash
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:    transfer.py - 开始执行下载器文件转移 ...
INFO:    transfer.py - 没有获取到已完成的下载任务
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/processes HTTP/1.1" 200 OK
INFO:     10.255.255.1:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
```

**Comment by OpsDarren** [comment]
补充一下，我现在明明环境参数没有设置qbittorrent，但是日志内依然会显示qbittorrent的连接报错

配置如下
```
  -e DOWNLOADER=transmission \
  -e TR_HOST='trip:trport' \
  -e TR_USER=truser \
  -e TR_PASSWORD=trpass \
```
日志如下
```
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe414456b50>: Failed to establish a new connection: [Errno 111] Connection refused')': /
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe414483650>: Failed to establish a new connection: [Errno 111] Connection refused')': /
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe41447d5d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/auth/login
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4144811d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe4144814d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /
WARNING: connectionpool.py - Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe414438310>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/auth/login
ERROR:   qbittorrent.py - qbittorrent 连接出错：Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe41c1bdf90>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
```

**Comment by mrxiaozuo** [comment]
+1 
当前程序版本
1.1.8

问题依然存在，补充一点，Transmission也是通过docker创建的容器，MoviePilot容器link了Transmission容器，MoviePilot能正常访问Transmission下载器且能添加下载任务。

日志如下
`INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK                                                                                                                                            
INFO:     172.17.0.1:0 - "GET /api/v1/download HTTP/1.1" 307 Temporary Redirect                                                                                                                             
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK  `

**Comment by c77187326** [comment]
我的也不显示  我还以为配置错了

**Comment by ershouqingge** [comment]
我的也是  没法转移下载器文件  正在下载也不显示

**Comment by jxxghp** [comment]
升级tr版本，或者不要配置种子标签

**Comment by OpsDarren** [comment]
> 升级tr版本，或者不要配置种子标签

谢谢大佬，种子标签没有配置，那么就是说，TR3的版本没法支持，需要更新到TR4是吗？

**Comment by jxxghp** [comment]
@OpsDarren 你试试看，我目前没有测试环境测试

**Comment by OpsDarren** [comment]
> @OpsDarren 你试试看，我目前没有测试环境测试

好的，我自己测试一下，谢谢！

**Comment by mrxiaozuo** [comment]
升级到Transmission4.0.4后正常显示正在下载任务列表

**Comment by ershouqingge** [comment]
> 升级到Transmission4.0.4后正常显示正在下载任务列表

标签和下载完会自动整理吗

**Comment by mrxiaozuo** [comment]
> > 升级到Transmission4.0.4后正常显示正在下载任务列表
> 
> 标签和下载完会自动整理吗

我没有配置标签，然后使用的是目录监控，非下载器监控，下载完会自动整理刮削和转移

**Comment by OpsDarren** [comment]
> 升级到Transmission4.0.4后正常显示正在下载任务列表

我也是升级到4.0.4之后解决了，看来就是3.0版本的Transmission不支持

**Comment by fyu0h** [comment]
升级到transmission 4即可解决
