### ISSUE TITLE
[错误报告]: 当站点数据刷新间隔设置为 “永不” 时，实际 站点数据刷新 这个任务会不间断的运行

### ISSUE THREAD

**Issue by wangwei2233** [jxxghp/MoviePilot#3312]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

当站点数据刷新间隔设置为 “永不” 时，实际 站点数据刷新 这个任务会不间断的运行
![PixPin_2024-12-03_13-26-55](https://github.com/user-attachments/assets/354241d8-484b-4f93-b2cd-5b1fb260bea7)

**Comment by hbq0405** [comment]
![image](https://github.com/user-attachments/assets/0dfdd7a1-40ac-4b4c-bf6e-7e69c09a97a5)
