### ISSUE TITLE
[错误报告]: CD2重启后，MP挂载的文件夹内容就为空了，需要重启服务才能看到文件夹内容。

### ISSUE THREAD

**Issue by davidchen73** [jxxghp/MoviePilot#3338]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v2.1.1

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

CD2重启后，MP挂载的文件夹内容就为空了，需要重启服务才能看到文件夹内容。

**Comment by totobo** [comment]
MP启动时候，挂载的CD2目录，需要是rslave权限的才可以
