### ISSUE TITLE
[Feature Request]: 憨憨 备用域名支持

### ISSUE THREAD

**Issue by trott90** [jxxghp/MoviePilot#3339]
### 当前程序版本

v2.1.1

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

憨憨主域名现在连不上，备用域名可以，添加不上，显示站点不支持

**Comment by cng10001** [comment]
+1

**Comment by johnwalke** [comment]
+1 这个迫切需要，浙江，江苏地区最严重，很多人都用备用域名，订阅都无法自动下载。

**Comment by eyasjx** [comment]
希望能早日支持备用域名。

**Comment by cng10001** [comment]
支持了😄

**Comment by cng10001** [comment]
用了憨憨的新域名 大家能正常自动签到吗❓
