### ISSUE TITLE
[错误报告]: 导入自定义规则失败

### ISSUE THREAD

**Issue by JoryPai** [jxxghp/MoviePilot#3340]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.2

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

导入自定义规则失败，测试：新建一个空的自定义规则并复制，导入这个规则，右下角报错
`[{"id":"RULE1","name":"规则1","include":"","exclude":""}]`
![image](https://github.com/user-attachments/assets/2a134905-d3a9-4166-8079-2e142fd5c00b)

**Comment by qin9125** [comment]
+1 回退 2.1.1 导入规则正常，曲线救国再升级 2.1.2，玄学的是群里有的群友 2.1.2可以导入规则有的不行，规则没问题 2.1.1 正常导入，找不到哪的问题
