### ISSUE TITLE
[Feature Request]: 搜刮的海报并不是华语地区的海报

### ISSUE THREAD

**Issue by huojinming-1997** [jxxghp/MoviePilot#335]
### 当前程序版本

1.0.9

### 功能改进

1.希望能优先搜刮华语地区的海报或者有相应的环境变量何以设置优先语言地区项，现在搜刮的默认拉下来的都是英文海报
2.或则像以前那样可以单独设置只生成nfo文件让emby,jellyfin自己去搜刮，因为如果没有nfo文件辅助让emby自己根据文件名和年份
去搜刮的话会有一部分的影片还是搜刮错误并没有MoviePilot的搜刮准确率高

希望能优先实现1这种是最完美的，如果不能的话2这种也问题不大

**Comment by jxxghp** [comment]
v1.1.0已修改

**Comment by sexyfeifan** [comment]
那如果我就是想要英文海报 是否支持用户设置？
