### ISSUE TITLE
[Feature Request]: 通知消息自定义

### ISSUE THREAD

**Issue by uploadrclone** [jxxghp/MoviePilot#337]
### 当前程序版本

1.0.9

### 功能改进

作者您好能否在通知中添加下
种子大小 站点名称 之类的信息 

### 参考资料

无

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/cf0193da-358d-4ff2-9dc5-342e0c27403d)

**Comment by uploadrclone** [comment]
@jxxghp 入库的时候能否添加截图的信息 因为下载器多 pt站点有的时候转载 无法区分哪个下载器下载了哪个种子
