### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by aicenluo** [jxxghp/MoviePilot#340]
### 当前程序版本

v1.0.9

### 功能改进

个人非常感激作者的辛勤工作，希望本项目越来越好！以下是我在使用过程中发现的2个关于交互的优化建议：

![image](https://github.com/jxxghp/MoviePilot/assets/128604492/08672f51-041e-4c5c-9a87-b5b37ce827c6)
1，建议日志按钮放到右上角个人信息菜单下，这样有利于在执行某些操作时，无需离开当前页面即可直接查看日志。
2，切换黑白主题的按钮，因为是非常用功能，也可考虑集成到该二级菜单下，当然放到一级菜单也没什么问题

**Comment by cng10001** [comment]
日志这个确实经常要看，希望和nt一样放在容易打开的入口 ^_^
