### ISSUE TITLE
[错误报告]: 自动删种插件：qb下载器的错误信息关键词不起作用，会命中所有种子

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#343]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.09

### 问题类型

主程序运行问题

### 问题描述

自动删种插件：qb下载器的错误信息关键词不起作用，会命中所有种子
这是我的设置： qb版本是4.5.4
<img width="768" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/10297471/d731dffc-3771-460e-aa7e-daad39463280">

### 发生问题时系统日志和配置文件

```bash
INFO:    __init__.py - 发送消息：channel=None，title=【自动删种任务执行完成】, text=Qbittorrent 共暂停2408个种子
```

**Comment by jxxghp** [comment]
这个字段只适用于TR，我加个说明。
