### ISSUE TITLE
订阅中已下载入库的显示为0，重新搜索从第一集开始下载

### ISSUE THREAD

**Issue by tsymr** [jxxghp/MoviePilot#349]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.9

### 问题类型

主程序运行问题

### 问题描述

![WX20230831-154759](https://github.com/jxxghp/MoviePilot/assets/11868091/69ba583b-95a4-4917-9ed4-573b2b9f9b34)
![WX20230831-154706](https://github.com/jxxghp/MoviePilot/assets/11868091/d1f58acb-bbae-4e5d-a0e4-3334edf2ff54)
![WX20230831-154657](https://github.com/jxxghp/MoviePilot/assets/11868091/2b450d2d-933f-4c73-868e-b24c05973fc3)
![image](https://github.com/jxxghp/MoviePilot/assets/11868091/648bb8cb-fea2-4625-ad66-42463f8ad40e)

**Comment by tsymr** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/11868091/4427f056-c632-40d7-a65b-c1587c3384d7)
emby中也已有剧集

**Comment by tsymr** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/11868091/a9ab7972-dad3-46ed-bf66-9b281af6b366)

**Comment by jxxghp** [comment]
升级到最新程序了吗， 后面专门因为这个问题重新打了次包，但版本号没变。

**Comment by tsymr** [comment]
> 升级到最新程序了吗， 后面专门因为这个问题重新打了次包，但版本号没变。

重新拉取镜像后解决了.
