### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by GUOlei-web** [jxxghp/MoviePilot#3499]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Windows

### 问题类型

其他问题

### 问题描述

绑定不了站点。

**Comment by cng10001** [comment]
🐂🍺

**Comment by GUOlei-web** [comment]
绑定ICC2022站点失败。付上站点配置图。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cng10001 ***@***.***&gt;
发送时间: 2024年12月8日 23:06
收件人: jxxghp/MoviePilot ***@***.***&gt;
抄送: GUOlei-web ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jxxghp/MoviePilot] [错误报告]: 请在此处简单描述你的问题 (Issue #3499)





 
🐂🍺
