### ISSUE TITLE
无法连接下载器

### ISSUE THREAD

**Issue by lllpxxx** [jxxghp/MoviePilot#3500]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

无法连接下载器 TR QB都不行

### 发生问题时系统日志和配置文件

```bash
ERROR:   transmission.py - transmission 连接出错：can't connect to transmission daemon: HTTPConnectionPool(host='10.168.1.77', port=9091): Max retries exceeded with url: /transmission/rpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149f1dfb0f90>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by luckylss** [comment]
解决了么，我qb别的都全部重装了还是不行，我还以为我的问题，现在根本下载不了东西

**Comment by lllpxxx** [comment]
> 解决了么,我四分卫别的都全部重装了还是不行,我还以为我的问题,现在根本下载不了东西
权限问题 改0 0 000

**Comment by MrZhangWeiCe** [comment]
同样连不上，根本没法用啊
