### ISSUE TITLE
[RFC]

### ISSUE THREAD

**Issue by liuyie** [jxxghp/MoviePilot#3504]
### 背景 or 问题

能否实现：qb通过mp进行分类管理下载到固态硬盘内并分类，再将源文件转移到机械硬盘内进行做种

### 目标 & 方案简述

能否实现：A:qb通过mp进行分类管理下载到固态硬盘内并分类，B:再将源文件转移到机械硬盘内进行做种。
现在的功能中，A段只有不进行二级分类，可实现转移到机械硬盘内做种。但要要实现B段，相当于要进行第二次分类或目录管理，现有mp实现不了。

**Comment by hbq0405** [comment]
固态只是中转下，分类的意义何在？

**Comment by liuyie** [comment]
1、便于对源文件的分类管理。
2、减少多线程下载且同时进行媒体库播放时，对硬盘的读取压力。并适度提高对网络带宽的利用率

**Comment by InfinityPacer** [comment]
开启qb临时目录

**Comment by hbq0405** [comment]
你都说了最终保种是在机械硬盘，这点就和固态分类管理风马牛不相及
下载是往固态，播放是在机械，同样是风马牛不相及
提高带宽利用率？这都是哪跟哪
