### ISSUE TITLE
[Feature Request]: 希望新增下载器监控，将手动添加的种子交由MP处理

### ISSUE THREAD

**Issue by envyafish** [jxxghp/MoviePilot#3505]
### 当前程序版本

2.1.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

![image](https://github.com/user-attachments/assets/b68ac068-1800-4d62-a43d-0ede98e261a0)
在目录设置的此处进行监控开启的配置。
开启的状态下，正在下载中可以捕获到下载器中新添加的种子。同时也可以达到在MP中进行手动下载的效果。比如订阅电影标记为已完成，剧集订阅更新到最新入库

**Comment by hbq0405** [comment]
自己打个标签就行了
PTPP下载的更省事，预设标签
