### ISSUE TITLE
[错误报告]: 电视剧 百年孤独(2024)未找到下载目录!

### ISSUE THREAD

**Issue by 954708775** [jxxghp/MoviePilot#3522]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

订阅百年孤独有这个问题，其他订阅一切正常，不知道怎么回事
![WX20241212-121503@2x](https://github.com/user-attachments/assets/92abf2ce-b310-4089-b1c5-4ff47b9975e2)
![WX20241212-121517@2x](https://github.com/user-attachments/assets/1de19ce9-447e-43dd-aeaa-5ea7a1d61e57)

### 发生问题时系统日志和配置文件

```bash
ERROR】2024-12-12 12:08:58,075 - download.py - 未找到下载目录：电视剧 百年孤独 (2024)
【INFO】2024-12-12 12:08:41,979 - search.py - 搜索完成，共 13 个资源
【INFO】2024-12-12 12:08:41,968 - search.py - 匹配完成，共匹配到 13 个资源
【INFO】2024-12-12 12:08:41,967 - torrent.py - 百年孤独 通过别名或译名匹配到资源：**（把站点打码了） - One Hundred Years of Solitude S01 2024 1080p NF WEB-DL DDP5.1 Atmos H264
【INFO】2024-12-12 12:08:41,964 - torrent.py - 百年孤
```

**Comment by cng10001** [comment]
![扣扣_2024-12-12_16-37-46](https://github.com/user-attachments/assets/d748dd2b-0727-4002-9382-16785cd2b922)
是这个标题吗
是的话应该能看出问题了。

**Comment by 954708775** [comment]
> ![扣扣_2024-12-12_16-37-46](https://private-user-images.githubusercontent.com/115156545/395075432-d748dd2b-0727-4002-9382-16785cd2b922.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTMxMTgsIm5iZiI6MTczMzk5MjgxOCwicGF0aCI6Ii8xMTUxNTY1NDUvMzk1MDc1NDMyLWQ3NDhkZDJiLTA3MjctNDAwMi05MzgyLTE2Nzg1Y2QyYjkyMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwODQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjY2ZTQ3Y2U4YTY5MjUwYjAyNjVjYTFhZjE2NzAzMzQwM2Q4MzM5Y2FmOTdlOGEyZjQwYTU3NmNkOWM1NTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yAAfDdRo8QvgzMHA7lsD_q53ZbQ2bR-QeX_FPydRPgI) 是这个标题吗 是的话应该能看出问题了。

好的，所以是因为新电视剧。没有更新是吧

**Comment by cng10001** [comment]
不是 因为tmdb上制作国家是哥伦比亚，国家代码没有在默认的欧美剧分类里

**Comment by 954708775** [comment]
好的，感谢，我去二级分类里面加一下，防止这个问题存在
