### ISSUE TITLE
[错误报告]: Webhook插件在V2版本依旧不可以使用

### ISSUE THREAD

**Issue by chenvd** [jxxghp/MoviePilot#3523]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

在V2版本中，Webhook插件没有生效，也没有日志生成。之前反馈过 #3108 ，显示已经修改，但是经过测试和其他人反馈，这个问题还是依旧存在

**Comment by alifather** [comment]
emby发送webhook测试消息提示Unauthorized

**Comment by chenvd** [comment]
> emby发送webhook测试消息提示Unauthorized

我反馈的这个情况不一样，是MP的事件，通过Webhook插件通知其他系统
