### ISSUE TITLE
[错误报告]:远程反向代理访问Emby并播放，无法触发限速插件

### ISSUE THREAD

**Issue by imortons** [jxxghp/MoviePilot#353]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.9

### 问题类型

插件问题

### 问题描述

在外通过Nginx-proxy-manager的反向代理访问 Emby ，Emby识别IP地址为172.17.0.1 本地局域网，因此未触发播放限速插件。希望帮忙解决。

注：Emby webhook及mp配置均正确，mp可以识别到Emby在播放，并且能通过tg发送通知，开始播放通知如下：
“开始播放剧集 猎魔人 S1E1 结局的开始
用户：wyp
设备：Emby Web Microsoft Edge Windows
IP地址：172.17.0.1 本地局域网
进度：100.0%
剧情：在布拉维坎小镇，充满敌意的小镇居民和一个狡猾的术士接待了杰洛特。当尼弗迦德军队进攻辛特拉城时，希瑞公主意识到她的皇家生活已经走到尽头了。
时间：2023-08-31 22:06:38”

### 发生问题时系统日志和配置文件

```bash
播放开始后，mp的日志如下：
INFO:    command.py - 处理事件：webhook.message - [<function BestFilmVersion.webhook_message_action at 0x152a69987f60>, <function MediaSyncDel.sync_del_by_plugin at 0x152a6955c540>, <function SpeedLimiter.check_playing_sessions at 0x152a694fcb80>, <function WebHook.send at 0x152a694fe7a0>]
INFO:    tmdbapi.py - 正在查询TMDB集图片：114461，季：1，集：1 ...
INFO:    __init__.py - 发送消息：channel=None，title=停止播放剧集 阿索卡 S1E1 师与徒, text=用户：wyp
设备：Emby Web Microsoft Edge Windows
IP地址：172.17.0.1 本地局域网
进度：0.18%
剧情：一名重要的囚犯在新共和国的囚禁下逃脱，追查的过程中令两位老友重逢。
时间：2023-08-31 22:29:12，userid=None
INFO:    command.py - 处理事件：notice.message - [<function MessageForward.send at 0x152a6955d120>, <function WebHook.send at 0x152a694fe7a0>]
```

**Comment by jxxghp** [comment]
IP地址来源于Emby，你要让Emby识别到你的源地址才行。比如在反向代理中添加传递源IP地址的配置。

**Comment by imortons** [comment]
谢谢，以根据您的提示，配置路由器转发和nginx反代正确使用限速功能。再次感谢🙏

**Comment by LoSiTeE** [comment]
> 谢谢，以根据您的提示，配置路由器转发和nginx反代正确使用限速功能。再次感谢🙏

老哥，请问你是如何配置的？

**Comment by imortons** [comment]
> > 谢谢，以根据您的提示，配置路由器转发和nginx反代正确使用限速功能。再次感谢🙏
> 
> 老哥，请问你是如何配置的？
我在用nginxwebui反向代理，emby反代参数里勾选上“Host参数”，emby就能识别我的远程的ip地址，从而mp限速插件能正确限速。不过我现在都用ikuai进行流控了，比限速好用太多

**Comment by LoSiTeE** [comment]
> > > 谢谢，以根据您的提示，配置路由器转发和nginx反代正确使用限速功能。再次感谢🙏
> > 
> > 
> > 老哥，请问你是如何配置的？
> > 我在用nginxwebui反向代理，emby反代参数里勾选上“Host参数”，emby就能识别我的远程的ip地址，从而mp限速插件能正确限速。不过我现在都用ikuai进行流控了，比限速好用太多

好的，感谢

**Comment by imortons** [comment]
你问的是哪部分的配置，还有你现在遇到什么问题了发自我的 iPhone在 2024年2月3日，23:45，LoSiTeE ***@***.***> 写道：﻿

谢谢，以根据您的提示，配置路由器转发和nginx反代正确使用限速功能。再次感谢🙏

老哥，请问你是如何配置的？
