### ISSUE TITLE
[错误报告]: 热门订阅显示无法连接问题。

### ISSUE THREAD

**Issue by qsxazcv** [jxxghp/MoviePilot#3530]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image_2024-12-13_19-15-35](https://github.com/user-attachments/assets/8d5c31d5-8051-49c1-ad08-791ed50f58e0)
![image_2024-12-13_19-16-15](https://github.com/user-attachments/assets/38e2bf9b-a79b-4614-a110-67411267fdc1)
由于进入这个域名的服务器被污染，导致连不上服务器，可以修改一下让这个服务器也走代理吗？
或者有其他办法？？

**Comment by LunaticXJ** [comment]
我是最新的版本也有相同的问题，求解决

**Comment by ITUOUTI** [comment]
一样  有这个问题 看日志是：请求失败: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by LunaticXJ** [comment]
问了TG群，说热门订阅查询的是movie-pilot.org这个域名，这个请求访问是不是没有走proxy_host配置的代理，我把clash的规则加上去还是不行
