### ISSUE TITLE
[RFC]docker镜像每次重启都会下载chromium, 不用代理的情况下，启动时间较长，建议直接内置或者用户给，但是通过docker的参数指定寻找路径

### ISSUE THREAD

**Issue by buzhdiao** [jxxghp/MoviePilot#3539]
### 背景 or 问题

docker镜像每次重启都会下载chromium, 不用代理的情况下，启动时间较长

### 目标 & 方案简述

建议直接内置或者用户给，但是通过docker的参数指定寻找路径

### 方案设计 & 实现步骤

建议直接内置或者用户给，但是通过docker的参数指定寻找路径

**Comment by Putarku** [comment]
参考wiki上的描述，浏览器内核本身就可以持久化存储的，只要设置好路径映射即可
