### ISSUE TITLE
[错误报告]: 搜索完成后搜索结果不能自动展示，插件添加与卸载不自动刷新

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#355]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

主程序运行问题

### 问题描述

https://github.com/jxxghp/MoviePilot/assets/23021469/07728ae7-ef29-42fc-b339-0a6fa3b53346

- 搜索完成后搜索结果不能自动展示，需要切换页面在切换回来后才会展示结果，如果直接按F5刷新则会重新搜索一边，还是不展示结果；
- 插件添加时可能多次点击添加后才会展示添加结果，如果只点击一次关闭并切换页面回来后会正常展示；
- 插件卸载不自动刷新，也是需要切换界面后才会刷新。

**Comment by jxxghp** [comment]
重现不了，把config/temp下面的文件全部删掉重启看看。

**Comment by mjsoftking** [comment]
拉去昨天晚上那版镜像，现在好使了
