### ISSUE TITLE
[错误报告]: 插件站点数据统计，无法统计猫站的数据

### ISSUE THREAD

**Issue by 459633382** [jxxghp/MoviePilot#356]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.0.9

### 问题类型

插件问题

### 问题描述

 #插件站点数据统计，无法统计猫站的数据，并非个例，MP群里也有人出现这个问题
![2](https://github.com/jxxghp/MoviePilot/assets/44571764/d73e3483-3213-47fb-b2d9-863049533c57)

**Comment by dfbb9216** [comment]
有同样的问题
