### ISSUE TITLE
[错误报告]: 插件和订阅新增的排序功能有bug

### ISSUE THREAD

**Issue by Anoyou** [jxxghp/MoviePilot#3568]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

自从2.1.3 更新支持手动排序插件 / 订阅，但手动排序后如果编辑其中的插件/订阅 ，网页卡片就会恢复手动排序前的状态。除非刷新网页。

这个bug 订阅和插件 都是这样。百分百重现。

**Comment by Aqr-K** [comment]
@Anoyou 2.1.4版本无痕模式试试

**Comment by Anoyou** [comment]
> @Anoyou 2.1.4版本无痕模式试试

依旧如此，只要你点开任意一个插件或者订阅卡片，不需要编辑，直接点保存，当前卡片顺序就会变回原来排序前，也就是你订阅的顺序。
