### ISSUE TITLE
[Feature Request]: 储存&目录设置的下载路径细分

### ISSUE THREAD

**Issue by Hirsi-He** [jxxghp/MoviePilot#3570]
### 当前程序版本

2.1.2

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

储存&目录中我设置的电视剧下载路径都是细分了的，我把国漫和日番都放在【/video/downloads/动漫】文件夹下，然后【儿童】放在【/video/downloads/儿童片】中，但是下载未指定保存目录的时候还是下载到/video/downloads/动漫 文件夹下

设置如图
![image](https://github.com/user-attachments/assets/4f9bea2c-71a8-4d46-88d8-8ba6ba893967)

下载的时候没有指定下载目录
![image](https://github.com/user-attachments/assets/fac93ffb-313a-454e-9a24-2430b21c54a0)

下载器的路径
![image](https://github.com/user-attachments/assets/e32cf40f-7033-4b72-ae06-a9081ebb93be)

例如这个百变校巴，是动画、儿童，希望可以根据这个分类，匹配到对应的下载路径
![image](https://github.com/user-attachments/assets/2b5ecb69-6a5b-41bb-beaf-aaa252d0eea4)

**Comment by cng10001** [comment]
![扣扣_2024-12-20_21-07-47](https://github.com/user-attachments/assets/527c362c-9ddc-4fc4-b5e0-00059132d5cb)
因为你这片子除了`儿童`也有`动画`分类啊。
你动画放前面 他就优先匹配动画咯

**Comment by cddjr** [comment]
百变校巴 这个在tmdb上有很多重复的，或许加一个自定义词条强制指定正确的tmdbid才能解决？

`百变校巴 => 百变校巴{[tmdbid=122961;type=tv]}`
