### ISSUE TITLE
[错误报告]: iyuu认证出错：非法请求：用户未绑定合作站点账号！请查阅绑定！

### ISSUE THREAD

**Issue by suerb** [jxxghp/MoviePilot#3572]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

iyuu认证出错：非法请求：用户未绑定合作站点账号！请查阅绑定！

用 v1 的时候还是正常的，最近装了 v2 就不行了，moviepilot 里面的 iyuu_sign 也填上去了，但是还是报错。导致无法添加站点，整个 moviepilot 等于废了，请问怎么解啊？

### 发生问题时系统日志和配置文件

```bash
ERROR:   scheduler.py - iyuu认证出错：非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/

ERROR:   scheduler.py - 用户认证失败：用户认证出错：Expected dict, got str，共失败 8 次
```

**Comment by suerb** [comment]
> IYUU PLUS

没有，请问怎样操作？

**Comment by Jayczee** [comment]
> > IYUU PLUS
> 
> 没有，请问怎样操作？

docker起一个iyuu plus容器，进去之后左边管理面板=》站点=》绑定合作站点 然后选IYUU和你提示没有绑定账号的iyuu token

**Comment by hbq0405** [comment]
不用那么麻烦 ，MP有iyuu绑定插件

**Comment by suerb** [comment]
> 不用那么麻烦 ，MP有iyuu绑定插件

现在是因为无法认证iyuu所以进不去 mp，所以 mp 的认证插件没用
