### ISSUE TITLE
站点认证失败

### ISSUE THREAD

**Issue by xxtyyq** [jxxghp/MoviePilot#3574]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

早上更新到2.1.4，突然站点认证失败~docker配置里一直添加的是红豆饭，rousi，麒麟，之前一直没问题~

**Comment by xxtyyq** [comment]
![IMG_4572](https://github.com/user-attachments/assets/b8826034-26b8-44df-be0a-af26c66c3037)

**Comment by a13720943940** [comment]
Ic2022，我今天突然也这样了

**Comment by xxtyyq** [comment]
> Ic2022，我今天突然也这样了

我在ui里尝试添加认证，也不行，还是提示这个

**Comment by a13720943940** [comment]
> > Ic2022，我今天突然也这样了
> 
> 我在ui里尝试添加认证，也不行，还是提示这个

认证失败:用户认证出错:Expected dict, gotstr昨晚就开始这样了，啥也没动

**Comment by Satanscikle** [comment]
icc2022，同样的问题...

**Comment by devlei** [comment]
更新后，rousi认证同样的问题

**Comment by a568227188** [comment]
一样的问题哦 老版本全部都这样了
