### ISSUE TITLE
更新2.1.4之后，ic2022无法认证，提示：认证失败:用户认证出错:Expected dict, got str

### ISSUE THREAD

**Issue by a13720943940** [jxxghp/MoviePilot#3575]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

昨晚更新2.1.4之后，ic2022无法认证，提示：认证失败:用户认证出错:Expected dict, got str

**Comment by FannyCode-Lib** [comment]
遇到了同样的问题，冰淇淋无法验证通过，我只有这一个能验证的PT站，为什么不加入馒头验证呢，难道这个站还入不了开发者的法眼吗

**Comment by xyswordzoro** [comment]
@FannyCode-Lib 馒头认证iyuu   iyuu认证mp

**Comment by Aqr-K** [comment]
@FannyCode-Lib 📢：目前v1.4.1及以上资源包存在bug问题，可使用 iyuu 临时添加认证的站点辅助认证，或者先退回 v2.1.3，并关闭所有自动更新，使用 v1.4.0 及以前版本的资源包进行认证，等待修复完成后，再重新打开自动更新。目前已经在定位问题，紧急修复中，请各位耐心等候一下

**Comment by a13720943940** [comment]
> @FannyCode-Lib 📢：目前v1.4.1及以上资源包存在bug问题，可使用 iyuu 临时添加认证的站点辅助认证，或者先退回 v2.1.3，并关闭所有自动更新，使用 v1.4.0 及以前版本的资源包进行认证，等待修复完成后，再重新打开自动更新。目前已经在定位问题，紧急修复中，请各位耐心等候一下

退回v2.1.3也不行了

**Comment by a13720943940** [comment]
> @FannyCode-Lib 馒头认证iyuu iyuu认证mp

馒头认证iyuu的话，用户uid是馒头账号 么？站点密钥是实验室那个令牌么
