### ISSUE TITLE
[错误报告]: 在推荐中没有“正在热映”；“豆瓣热门电影”；“豆瓣热门电视剧”等分类，只有“TMDB电影”等分类

### ISSUE THREAD

**Issue by 707214981** [jxxghp/MoviePilot#3576]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.4

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

在推荐中没有“正在热映”；“豆瓣热门电影”；“豆瓣热门电视剧”等分类，只有“TMDB电影”等分类
![微信图片_20241220143506](https://github.com/user-attachments/assets/ec5d8ebd-1524-4697-b376-3e5f29ce55c3)

**Comment by InfinityPacer** [comment]
自行排查网络

**Comment by Yemao7** [comment]
@InfinityPacer 我也是同样的情况，网络连通测试中豆瓣是能联通的。并且同机器下的nastool能看到豆瓣的豆瓣热门电影等数据。
@707214981 请问你找到问题原因了吗？
