### ISSUE TITLE
[错误报告]: 新增站点失败：用户未通过认证，无法使用站点功能！

### ISSUE THREAD

**Issue by suerb** [jxxghp/MoviePilot#3578]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

站点管理总是提示：新增站点失败：用户未通过认证，无法使用站点功能！

iyuu 已经填写好 iyuu_sign，在 V1 版本里面也是能用的。重装为 V2 版本就总是提示认证不通过了

请问要怎么处理？现在什么都用不了啊

**Comment by suerb** [comment]
怎么 close 啦？

**Comment by eponine2012** [comment]
不是提示的很明白了
