### ISSUE TITLE
[错误报告]: 使用规则组不自动下载

### ISSUE THREAD

**Issue by mymoonyue** [jxxghp/MoviePilot#3579]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

用了优先级规则组的剧都不会自动下载，要手动点一下搜索订阅才就可以下载了。其他没加规则组的剧就正常订阅下载。
比如观众4K的沧元图，憨憨4K的猎罪图鉴。

**Comment by InfinityPacer** [comment]
自行检查RSS
