### ISSUE TITLE
[错误报告]: v2.1.5无法下载馒头M-team种子，提示 下载种子出错，状态码：404

### ISSUE THREAD

**Issue by xzyone** [jxxghp/MoviePilot#3587]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.5

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

之前的版本就一直有这个问题，看到 https://github.com/jxxghp/MoviePilot/issues/2480 这个Issue有点类似，下面也有人回复馒头有同样的问题，两周之前被标记已解决，所以以为这个版本更新之后应该会解决。但是现在还有这个问题，所以来提Issue。

搜索馒头的种子、显示馒头数据都正常，只是到了下载种子的时候提示“**下载种子出错，状态码：404**”，但在日志中获取到的下载地址复制到浏览器可以正常下载种子。

### 发生问题时系统日志和配置文件

```bash
INFO:    indexer - 站点 馒头 开始以 MTorrent 模型解析数据...

INFO:     192.168.31.10:0 - "PUT /api/v1/site/ HTTP/1.1" 200 OK

INFO:     192.168.31.10:0 - "GET /api/v1/site/ HTTP/1.1" 200 OK

INFO:    indexer - 站点 馒头 开始以 MTorrent 模型解析数据...

INFO:     192.168.31.10:0 - "GET /api/v1/history/transfer?page=1&count=50 HTTP/1.1" 200 OK

INFO:     192.168.31.10:0 - "GET /api/v1/search/last HTTP/1.1" 200 OK

INFO:     192.168.31.10:0 - "GET /api/v1/download/clients HTTP/1.1" 200 OK

INFO:     192.168.31.10:0 - "GET /api/v1/system/setting/Directories HTTP/1.1" 200 OK

INFO:    download.py - 获取到下载地址：https://api.m-team.cc/api/rss/dlv2?sign=XXX&t=XXX&tid=XXX&uid=XXX

ERROR:   download.py - 下载种子文件失败：Back to 1995 2024 S01 Complete 2160p WEB-DL HEVC DDP 2Audios-QHstudIo - https://api.m-team.cc/api/rss/dlv2?sign=XXX&t=XXX&tid=XXX&uid=XXX

INFO:    chain - 发送消息：channel=None，source=None,title=Back to 1995 2024 S01 Complete 2160p WEB-DL HEVC DDP 2Audios-QHstudIo 种子下载失败！, text=错误信息：下载种子出错，状态码：404

站点：馒头，userid=None
```

**Comment by xzyone** [comment]
> ![image](https://private-user-images.githubusercontent.com/160988576/397944109-e4d9da4b-e17a-42b7-9654-c641b729cc63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDYwMTIsIm5iZiI6MTczNDgwNTcxMiwicGF0aCI6Ii8xNjA5ODg1NzYvMzk3OTQ0MTA5LWU0ZDlkYTRiLWUxN2EtNDJiNy05NjU0LWM2NDFiNzI5Y2M2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxODI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTM1ODQyMzc1NzNkY2Q0MDlhZDczNTM5Y2FjM2RmZTA0NmUyMjVkMTFjYmJlYTI4Y2JkMDFjNGY5YTNiMTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rJGLtYgKMKUhmwTTNlApo8Vn2ChmcthoVGwE6u2bHFM) ![image](https://private-user-images.githubusercontent.com/160988576/397944166-ed889bf5-5c70-4d67-b5c8-04e0f99c82b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDYwMTIsIm5iZiI6MTczNDgwNTcxMiwicGF0aCI6Ii8xNjA5ODg1NzYvMzk3OTQ0MTY2LWVkODg5YmY1LTVjNzAtNGQ2Ny1iNWM4LTA0ZTBmOTljODJiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxODI4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2RlZTRmNGQzYjNkMGJhNmQzNjExNzdiNjRiMWI2NWMwMjUzMTYzNzQzMmI1NjU2YzAwNDQwNTQ3MGUxNzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZBwpbosnPeR9uMvw83sBm_neAQRkVr0BL68qvFaocLc)
> 
> 1. 请检查 MTeam -> 下载偏好 -> 下载种子域名
> 2. 请检查对应下载地址，容器中能否正常 wget 到本地

![局部截取_20241222_023432](https://github.com/user-attachments/assets/95024947-1cd8-4abf-8943-eaae5590a621)
![image](https://github.com/user-attachments/assets/11a9eefb-ee52-4e3d-a633-10ab0349150c)
![局部截取_20241222_024103](https://github.com/user-attachments/assets/c983f2ce-e1ba-4044-a8f7-0d04bf272ff6)

已经检查两个步骤，问题依然存在。

**Comment by cddjr** [comment]
我没遇到过404，只能看看你的站点是怎样配置的了。
比如是否开启了馒头站点的代理访问、浏览器仿真、User-Agent。

**Comment by xzyone** [comment]
> 我没遇到过404，只能看看你的站点是怎样配置的了。 比如是否开启了馒头站点的代理访问、浏览器仿真、User-Agent。

代理访问、浏览器仿真、User-Agent 都没有配置...

**Comment by xzyone** [comment]
卧槽解决了。我浏览器设置了MoviePilot站点禁用缓存，取消这个选项就可以了。

![image](https://github.com/user-attachments/assets/b76e5aa3-a30b-4521-9f39-226de797e9b6)

**Comment by suzukua** [comment]
![Image](https://github.com/user-attachments/assets/d8a2c323-adca-49f0-8786-043bffbe030d)
加了几行日志，不知道为什么馒头返回的302跳转到google去了。。。
![Image](https://github.com/user-attachments/assets/d825272a-2728-406e-af14-fed7b35238ee)

**Comment by suzukua** [comment]
![Image](https://github.com/user-attachments/assets/e355d54b-659f-4eb8-a1b2-a39b6a25cda9)

**Comment by suzukua** [comment]
测试了下wget能正常下载，curl跳转google
