### ISSUE TITLE
[错误报告]: v2.1.5_插件_订阅规则自动填充 插件异常

### ISSUE THREAD

**Issue by cyx222800** [jxxghp/MoviePilot#3594]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.5

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

昨天使用时发现插件失效，通过日志发现最后一次正确填充是12月12日，怀疑是因为版本更新导致的。

之前规则如下：
下载种子填充规则：
特效，资源质量，分辨率，工作组，站点
二级分类填充规则：
category:动画电影#resolution:2160p#include:国语|中字#savepath:/media/PT下载/动漫/{name}
category:外语电影#resolution:2160p#include:国语|中字#savepath:/media/PT下载/电影/{name}
category:华语电影#resolution:2160p#savepath:/media/PT下载/电影/{name}
category:日番#filter_groups:优先4K组#include:国语|中字#savepath:/media/PT下载/动漫/{name}
category:国漫#filter_groups:优先4K组#savepath:/media/PT下载/动漫/{name}
category:综艺,纪录片#filter_groups:优先4K组#savepath:/media/PT下载/综艺/{name}
category:国产剧#resolution:2160p#savepath:/media/PT下载/电视/{name}
category:欧美剧#resolution:2160p#include:国语|中字#savepath:/media/PT下载/电视/{name}
category:日韩剧,儿童#filter_groups:优先4K组#include:国语|中字#savepath:/media/PT下载/电视/{name}

经过排查：发现只要规则中包含resolution这一参数，就会导致二级分类规则填充失效，2160p改为4k问题依旧

后将规则改为：
下载种子填充规则：
特效，资源质量，工作组，站点
二级分类填充规则：
category:动画电影#filter_groups:动画电影#savepath:/media/PT下载/动漫/{name}
category:外语电影#filter_groups:外语电影#savepath:/media/PT下载/电影/{name}
category:华语电影#filter_groups:华语电影#savepath:/media/PT下载/电影/{name}
category:日番#filter_groups:日番#savepath:/media/PT下载/动漫/{name}
category:国漫#filter_groups:国漫#savepath:/media/PT下载/动漫/{name}
category:儿童#filter_groups:儿童#savepath:/media/PT下载/动漫/{name}
category:综艺,纪录片#filter_groups:综艺#savepath:/media/PT下载/综艺/{name}
category:国产剧#filter_groups:国产剧#savepath:/media/PT下载/电视/{name}
category:欧美剧#filter_groups:欧美剧#savepath:/media/PT下载/电视/{name}
category:日韩剧#filter_groups:日韩剧#savepath:/media/PT下载/电视/{name}

修改后，二级分类自动填充功能恢复正常，但是当订阅剧集并完成下载种子后，下载种子自动填充规则依然失效，并不能正确填充 工作组站点等信息

eg：规则组中只包含了：分辨率4k，国语，中字 三条规则。

怀疑是不是分辨率参数进行过调整导致了插件异常，希望大佬可以看看，救救这个灵魂插件

**Comment by thsrite** [comment]
插件更新v2.8.4
