### ISSUE TITLE
[Feature Request]: 希望来个大佬做个给qb打二级分类插件

### ISSUE THREAD

**Issue by shyblacktea** [jxxghp/MoviePilot#3595]
### 当前程序版本

2.1.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

下载任务分类与标签 - 只能分三大类
![image](https://github.com/user-attachments/assets/32f52fa7-6824-4fd9-a6a6-bf2d639b9d6c)

所以希望有大佬做个能按路径填写分类
分类1：日番 路径：/media/qb/日番/
分类2：国漫 路径：/media/qb/国漫/
分类3：儿童 路径：/media/qb/儿童/
分类4
分类5
这样可以自定义qb分类，或者自动读取mp二级分类来给qb分类(支持处理历史,硬看路径分)

![image](https://github.com/user-attachments/assets/a49354b8-2448-46ff-ba84-1317ea86704c)
插件的填写大概为这种填写框
日番#/media/qb/日番/
国漫#/media/qb/国漫/
[分类]#[路径]
'#''只是随便写的 主要看插件要用到什么 看大佬的构思

**Comment by hbq0405** [comment]
https://t.me/MoviePilot_Wiki/45

不需要插件，看我发的教程

**Comment by shyblacktea** [comment]
> https://t.me/MoviePilot_Wiki/45
> 
> 不需要插件，看我发的教程

强哥 自动管理水土不服
