### ISSUE TITLE
[Feature Request]一级目录自定义

### ISSUE THREAD

**Issue by LGuangming** [jxxghp/MoviePilot#3606]
### 当前程序版本

2.1.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否支持一级目录自定义，也就是电视剧，电影这两个分类自定义，可以用现成category二级目录分类文件来实现一级分类。

**Comment by InfinityPacer** [comment]
善用 /

**Comment by InfinityPacer** [comment]
![image](https://github.com/user-attachments/assets/3e3c919b-5726-47f6-b447-bb4824fb86bb)
![image](https://github.com/user-attachments/assets/ba6cddd6-e1ac-413a-8d93-c91f261f4fd0)

**Comment by LGuangming** [comment]
> ![image](https://github.com/user-attachments/assets/3e3c919b-5726-47f6-b447-bb4824fb86bb)
> ![image](https://github.com/user-attachments/assets/ba6cddd6-e1ac-413a-8d93-c91f261f4fd0)

真是小机灵鬼，也没想到能这样用
