### ISSUE TITLE
[错误报告]: 每次进入推介页面，非要等待所有数据返回才能响应！！！

### ISSUE THREAD

**Issue by wintsa123** [jxxghp/MoviePilot#3609]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V2

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

每次进入推介页面，非要等待所有数据返回才能响应！！！
页面是没卡的，但是点击card或者nav都一直没响应，包括刷新页面！
我观察了网络请求，居然一直在等待douban这个接口返回数据。。。。

**能否给这个接口添加一个缓存，或者晚上定时抓取数据直接缓存？进入页面的时候先命中缓存，无法命中再进行抓取。。。。**

**Comment by wintsa123** [comment]
@jxxghp

**Comment by Aqr-K** [comment]
@wintsa123 关掉去高级设置里的全局图片缓存试试

**Comment by jxxghp** [comment]
就你这问题那么多！号我都不太想理你，满满的情绪！

**Comment by jxxghp** [comment]
又不是所有人都有你这个问题。另外，开源项目你有能力就自己改，没能力就客气点，谁欠你什么了吗？
看了让人恼火！
