### ISSUE TITLE
下载转移命名错误

### ISSUE THREAD

**Issue by dandkong** [jxxghp/MoviePilot#361]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

主程序运行问题

### 问题描述

1.1.0订阅下载后，种子中有两个文件，转移以后命名非常怪，而且只有一个文件
后面在文件管理里面重新转移又正常了，
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/bd32477d-92b6-4c35-93b9-9ddb336a92a0)
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/5c19723e-d47b-4650-a730-90baae75a999)

### 发生问题时系统日志和配置文件

```bash
后面才发现这问题，没日志了。。
```

**Comment by jxxghp** [comment]
更新到最新的镜像，重新拉

**Comment by dandkong** [comment]
> 更新到最新的镜像，重新拉

最新的，三四小时前那个
