### ISSUE TITLE
[Feature Request]: 增加验证站

### ISSUE THREAD

**Issue by ptcafe** [jxxghp/MoviePilot#3620]
### 当前程序版本

v1.9.17

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

你好，成为 MoviePilot 验证站需要什么条件，申请咖啡作为验证站，已经向  jxxghp 邮箱发送了 NAS_TOOLS_KEY。

**Comment by jxxghp** [comment]
@ptcafe 收到，下个版本弄一下
