### ISSUE TITLE
[Feature Request]: 能否增加对PTFans站点的支持

### ISSUE THREAD

**Issue by yf-9186** [jxxghp/MoviePilot#3623]
### 当前程序版本

v2.1.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

能否增加PTfans站点支持，https://ptfans.cc/

**Comment by jxxghp** [comment]
给我弄个账号：jxxghp@gmail.com

**Comment by jxxghp** [comment]
已支持
