### ISSUE TITLE
[Feature Request]: 有关自动订阅模式的反馈

### ISSUE THREAD

**Issue by rhettZeng107** [jxxghp/MoviePilot#3627]
### 当前程序版本

v2.1.5

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

有关自动订阅模式，官方文档中描述【会定期通过后台任务的方式检查各站点新出的资源，对这些资源进行逐个识别匹配，并将结果缓存起来，如有符合订阅的资源则添加下载，每次刷新只处理站点新出现的增量资源数据】；

文档的意思是只会对各PT站新出的种子进行识别？匹配成功后才会自动下载；而我订阅的资源可能是好几天/几月之前发布的种子，这样就无法订阅成功并下载。 能否改进一下，当我添加订阅资源后，到各站点中过滤并查找是否有这个资源？有就匹配并自动下载，不要只检查新种子。 比如我想看一部老电影，目前只能手动点资源搜索，再点下载。

**Comment by InfinityPacer** [comment]
https://wiki.movie-pilot.org/zh/subscribe
> 订阅刷新
> 订阅搜索
