### ISSUE TITLE
界面用户认证按钮消失，有时认证选项不完整都是咖啡站

### ISSUE THREAD

**Issue by ALonelyWanderingMind** [jxxghp/MoviePilot#3631]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.15

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

界面用户认证按钮消失，有时认证选项不完整都是咖啡站
![image](https://github.com/user-attachments/assets/6388062f-97f4-4ee0-8022-0bec8a99197e)

**Comment by cddjr** [comment]
如果认证已通过就不显示了

**Comment by ALonelyWanderingMind** [comment]
> 如果认证已通过就不显示了

那如果要认证新站呢

**Comment by cddjr** [comment]
> > 如果认证已通过就不显示了
> 
> 那如果要认证新站呢

目前只能用回老办法，通过环境变量增删改认证站点
