### ISSUE TITLE
今天突然一下热门订阅 无论是电影还是电视剧 都没有内容了。

### ISSUE THREAD

**Issue by zhy648789** [jxxghp/MoviePilot#3643]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v2.1.6 

### 运行环境

Docker

### 问题类型

其他问题

### 问题描述

今天突然一下热门订阅 无论是电影还是电视剧 都没有内容了。
没有数据
未获取到热门订阅数据，未开启数据分享或服务器无法连接。

### 发生问题时系统日志和配置文件

```bash
没有报错。。
```

**Comment by zhy648789** [comment]
![QQ20241230-230753](https://github.com/user-attachments/assets/b1650d8e-4c97-41eb-bf84-419b2c76796f)

**Comment by InfinityPacer** [comment]
自行检查网络配置

**Comment by zhy648789** [comment]
![QQ20241230-233244](https://github.com/user-attachments/assets/11659e49-439b-4988-9fb2-7c45e26a5767)
![QQ20241230-233252](https://github.com/user-attachments/assets/ff79fb47-2069-4888-b07b-159d038169d6)
