### ISSUE TITLE
[Feature Request]: 建议插件播放限速增加自定义限速地址范围功能

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#365]
### 当前程序版本

1.1.0

### 功能改进

先说明一下我的观影环境，在家的话是直连观影没有问题，但是在公司我是通过在openwrt旁路由搭建的wireguard VPN访问家里的影视库，目前情况下如果我在公司观看电影，因为我是通过VPN连回家里，MP会识别我的ip为openwrt的ip在内网观看，不会对播放器进行限速，如果我在家里观看电影电视，此时我是在内网其他ip观看，不需要进行限速，所以希望作者能够在播放限速插件中加入自定义限速地址范围的功能，类似之前NT中的不限速地址范围但是注意是需要限速地址范围，比如我设置192.168.100.2这个地址或者192.168.1.1,192.168.1.2，此时监测到这些地址时对下载器进行限速上传，望大佬参考

**Comment by mjsoftking** [comment]
调整下VPN网段试试，不让他在局域网网段范围内

**Comment by yellowstrong** [comment]
> 调整下VPN网段试试，不让他在局域网网段范围内

与VPN网段无关，与运行VPN的服务端有关，也就是要对openwrt这台设备进行限速

**Comment by zraxx** [comment]
建议支持按nt限速模式，增加ip段

**Comment by WPF0414** [comment]
同建议，通过反代访问的mp和emby，会被认为是内网，不会限速，期望大佬加入nt的ip段，感谢大佬！
