### ISSUE TITLE
[错误报告]: 无法关闭 DoH，显示高级设置保存失败

### ISSUE THREAD

**Issue by boweic** [jxxghp/MoviePilot#3651]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

2.1.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

DoH 无法解析，尝试关闭。点击保存后显示“高级设置保存失败”

### 发生问题时系统日志和配置文件

WARNING | 16:54:46,397 | config.py | 配置项 'DOH_ENABLE' 已在环境变量中设置，请手动更新以保持一致性
-- | -- | -- | --

**Comment by InfinityPacer** [comment]
配置项 'DOH_ENABLE' 已在环境变量中设置，请手动更新以保持一致性
