### ISSUE TITLE
[错误报告]: 签到失败的判断似乎有点问题

### ISSUE THREAD

**Issue by dfbb9216** [jxxghp/MoviePilot#369]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

插件问题

### 问题描述

![0](https://github.com/jxxghp/MoviePilot/assets/64184911/48c770d0-6697-4d68-94de-84de9bd1235b)
今天签到的时间在折腾网络，站点签到没成功，站点打开是没签到状态。
然后设置立即运行一次
![1](https://github.com/jxxghp/MoviePilot/assets/64184911/85099db6-f452-4d2e-b3eb-d481db0cf2e6)
然后修改cron运行
![QQ截图20230902093652](https://github.com/jxxghp/MoviePilot/assets/64184911/4d478ed7-3420-4df1-98a5-813e1290c980)
都是判断签到成功，拒绝重新签到。

**Comment by amtoaer** [comment]
从代码上推断，是因为你设置了重试关键词，但签到失败状态的文本（如“签到失败，无法打开网站！”）没有匹配到重试关键词，导致当日下次签到不会重试这些站点。
一个解决办法是同时勾选这两个选项，重新运行一次。
<img width="406" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/32017007/7f9467e9-0107-4e24-8c5c-a9c210ccecd3">

**Comment by dfbb9216** [comment]
ok了
