### ISSUE TITLE
[错误报告]: 插件用久了，打开后完全变形（翻墙的网络没问题，测试网络全是绿色）

### ISSUE THREAD

**Issue by 459633382** [jxxghp/MoviePilot#383]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.0

### 问题类型

插件问题

### 问题描述

插件用久了，打开后完全变形，不止一个插件 翻墙的网络没问题，测试网络连通性全是绿色

![333](https://github.com/jxxghp/MoviePilot/assets/44571764/e1860f36-48a5-4db2-bde8-b716513ac16b)
![44](https://github.com/jxxghp/MoviePilot/assets/44571764/d364e6e4-1509-4acf-b98c-6b805515a3aa)
![55](https://github.com/jxxghp/MoviePilot/assets/44571764/33157829-90c8-4a87-9e40-a9bcea33296a)

**Comment by jxxghp** [comment]
提供日志
