### ISSUE TITLE
可以添加ssl支持吗？[Feature Request]: 

### ISSUE THREAD

**Issue by dreamPis** [jxxghp/MoviePilot#386]
### 当前程序版本

1.1.0

### 功能改进

添加https 自定义证书

**Comment by amtoaer** [comment]
可以在外层通过 nginx 等 web 服务器做一层反向代理

**Comment by dreamPis** [comment]
> 可以在外层通过 nginx 等 web 服务器做一层反向代理

那我试试把容器的nginx映射出来  修改看看

**Comment by amtoaer** [comment]
不太推荐，后续版本变化容器内部的 nginx 配置可能也会变，最好还是在容器外面再套一层 :rofl:
