### ISSUE TITLE
[错误报告]: 订阅时自定义识别词不起作用

### ISSUE THREAD

**Issue by leo8912** [jxxghp/MoviePilot#389]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

主程序运行问题

### 问题描述

订阅时自定义识别词不起作用。希望能以自定义识别词去匹配订阅，这样可以做到屏蔽某一类型资源

**Comment by jxxghp** [comment]
是指订阅里的包含排除按自定义识别词转换后再过滤吗？没看懂。

**Comment by leo8912** [comment]
> 是指订阅里的包含排除按自定义识别词转换后再过滤吗？没看懂。

就是我想屏蔽60fps资源，其他人提了个想法可以把60fps替换成杜比视界，这样过滤规则排除杜比视界就行。
但实际操作时订阅并没有用词表里去匹配，自定义词表现在只有下下来硬链识别时候才起用。

**Comment by cng10001** [comment]
`60fps`规则现在系统内置了
