### ISSUE TITLE
[错误报告]: 推荐页面部分资源不显示已存在

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#393]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.0

### 问题类型

主程序运行问题

### 问题描述

emby库里面都是已经入库的，但是推荐没显示已入库

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/31958a87-42ae-46f3-ae43-7084773cc5f5)

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/fbdc3ef1-dd81-46ee-955f-660bbeea42f2)

下面是已经订阅的，但是依旧没有小红心。

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/3c7e06e9-2f53-4070-8637-9bbaeadd591a)

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/47eb5546-8589-4433-92ee-0b92cbb12aa7)

**Comment by xp9477** [comment]
历史遗留问题了，nt也是这样
