### ISSUE TITLE
[Feature Request]: 期望增加文件管理打开默认目录配置

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#411]
### 当前程序版本

1.1.1

### 功能改进

期望增加文件管理打开默认目录配置，直接打开需要的目录

**Comment by amtoaer** [comment]
moviepilot 的下载都会在 download path 里，感觉默认打开 download path 还挺合理的。
有点好奇，可以描述下需要默认打开其它目录的场景吗？

**Comment by mjsoftking** [comment]
当前场景download与实际目录不对等，否则不能硬连接了，从NT留下来的结构，不好变了

**Comment by mjsoftking** [comment]
关于此需求我简单做了一下调整，但因为不了解本项目架构和部分问题未找到处理点，所以做了一下修改建议，期望大佬实现一下
@jxxghp @amtoaer 

### 一、MoviePilot 项目

- config.py 添加参数定义

```
    # 文件管理默认打开目录
    FILE_MANAGE_DEFAULT_PATH: str = None
```

![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/32ddee49-d5f9-477b-b3e9-abfbeae14d59)

- README.md 添加描述

FILE_MANAGE_DEFAULT_PATH： 文件管理默认打开目录，未配置则打开 **DOWNLOAD_PATH** 路径。

### 二、MoviePilot-Frontend 项目

- FileBrowserView.vue 修改参数

 result.data?.DOWNLOAD_PATH 替换成 result.data?.FILE_MANAGE_DEFAULT_PATH  

```
// 调用API，加载当前系统环境设置
async function loadSystemSettings() {
  try {
    const result: { [key: string]: any } = await api.get('system/env')
    if (result.success)
      path.value = result.data?.FILE_MANAGE_DEFAULT_PATH  || '/'
    if (path.value && !path.value.endsWith('/'))
      path.value += '/'
  }
  catch (error) {
    console.log(error)
  }
}
```

![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/33a9bd74-5540-4cce-b402-6058733e7fd3)

### 三、未能修改问题

- 未找到环境变量在哪里初始化的，需要在初始化的位置对 **FILE_MANAGE_DEFAULT_PATH** 是否为空判断，若为空是则赋予 **DOWNLOAD_PATH** 环境变量的值；
- 这些修改基于docker外置程序测试，可以正常运行，但因为不是很了解源码架构，若时间允许期望大佬们核对一下并进行调整，感谢大佬们的付出。

**Comment by mjsoftking** [comment]
测试结果如视频所示，浏览器缓存存在需要按 Ctrl+F5 刷新一下后才会有效。
https://github.com/jxxghp/MoviePilot/assets/23021469/123e706c-60e8-4149-979b-a1e4fa616e23


以上代码是使用文本编辑器编辑的外加存在未解决的问题，所以不能提交合并请求
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/076e0125-531e-4914-8a09-3bf14e3aef5b)
