### ISSUE TITLE
[Feature Request]: 可否添加排除“没有中文字幕”选项的过滤原则。

### ISSUE THREAD

**Issue by HamBosco** [jxxghp/MoviePilot#412]
### 当前程序版本

1.1.1

### 功能改进

不知可否添加“排除没有中文字幕”选项的过滤原则。

现在有一些新电影，刚开始的时候很多站会发各个区的资源，里面包含一些没有中文字幕，但是依旧会自动下载并完成订阅。

谢谢。

**Comment by jxxghp** [comment]
不是有了吗？

**Comment by HamBosco** [comment]
> 不是有了吗？

所以只要选了过滤规则里的中文字幕，没有中文字幕的就会被过滤掉是吗？我以为只是一个优先级，如果都没有中文字幕，还是会下载生肉……

**Comment by jxxghp** [comment]
@HamBosco 每一级都选上中文字幕

**Comment by HamBosco** [comment]
好的，谢谢
