### ISSUE TITLE
[错误报告]: 历史记录重新整理问题

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#419]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.2

### 问题类型

主程序运行问题

### 问题描述

对历史记录中成功或者失败的项目进行重新整理，会删除该条历史记录和媒体库目录。但是不会重新整理

**Comment by jxxghp** [comment]
测试了下，会呀。前提是原整理是错的，而不是重新整理后还是原目录。
提供下日志？

**Comment by paysenyu** [comment]
> 测试了下，会呀。前提是原整理是错的，而不是重新整理后还是原目录。 提供下日志？

我也遇到同样的问题了。   

复现问题是
1识别错误 
2重新整理
3识别错误的媒体文件会被删除
4历史记录里面识别错误和重新整理的记录均消失
5只剩emby媒体库那里还保存着重新整理之后的文件


> 【INFO】2023-09-03 18:00:02,914 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f7729efcc20>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:01:24,354 - __init__.py - 
获取到最优ip==>[172.64.229.41]
【INFO】2023-09-03 18:01:24,398 - __init__.py - Cloudflare CDN优选ip [172.64.229.41] 已替换自定义Hosts插件
【INFO】2023-09-03 18:01:24,398 - __init__.py - 通知CustomHosts插件重载 ...
【INFO】2023-09-03 18:01:24,400 - command.py - 处理事件：plugin.reload - [<function CustomHosts.reload at 0x7f772a07d9e0>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:01:24,402 - __init__.py - 更新系统hosts文件成功
【INFO】2023-09-03 18:03:15,878 - mediaserver.py - 开始同步媒体库数据 ...
【INFO】2023-09-03 18:03:15,974 - mediaserver.py - 正在同步媒体库 华语电影 ...
【INFO】2023-09-03 18:03:59,582 - mediaserver.py - 媒体库 华语电影 同步完成，共同步数量：352
【INFO】2023-09-03 18:03:59,582 - mediaserver.py - 正在同步媒体库 外语电影 ...
【INFO】2023-09-03 18:04:20,479 - __init__.py - 正在识别 Veteran ...
【INFO】2023-09-03 18:04:20,898 - tmdbapi.py - 正在查询TMDB电影：571345 ...
【INFO】2023-09-03 18:04:21,431 - tmdbapi.py - 571345 查询结果：老兵
【INFO】2023-09-03 18:04:21,432 - __init__.py - Veteran 识别结果：电影 老兵 (2015) 571345
【INFO】2023-09-03 18:04:21,433 - __init__.py - Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 识别为：电影 老兵 (2015)
【WARNING】2023-09-03 18:04:22,211 - __init__.py - 没有获取到 老兵 (2015) 的Fanart图片数据
【INFO】2023-09-03 18:04:22,211 - tmdbapi.py - 正在获取电影图片：571345...
【INFO】2023-09-03 18:04:22,609 - __init__.py - 正在转移文件：/volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 到 /volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.mkv
【INFO】2023-09-03 18:04:22,614 - __init__.py - 文件 /volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv link完成
【INFO】2023-09-03 18:04:22,623 - __init__.py - 文件 /volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 转移成功
【INFO】2023-09-03 18:04:22,657 - __init__.py - 开始刮削媒体库文件：/volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.mkv ...
【INFO】2023-09-03 18:04:22,658 - scraper.py - 正在生成电影NFO文件：老兵 (2015) - 1080p.mkv
【INFO】2023-09-03 18:04:22,659 - scraper.py - NFO文件已保存：/volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.nfo
【INFO】2023-09-03 18:04:22,660 - scraper.py - 正在下载poster图片：https://image.tmdb.org/t/p/original/jjy3iAHBZalVkqkQrWjSbKNX1RB.jpg ...
【INFO】2023-09-03 18:04:23,834 - scraper.py - 图片已保存：/volume1/Media1/电影/华语电影/老兵 (2015)/poster.jpg
【INFO】2023-09-03 18:04:23,840 - __init__.py - /volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.mkv 刮削完成
【INFO】2023-09-03 18:04:23,841 - emby.py - 开始刷新Emby媒体库...
【INFO】2023-09-03 18:04:23,873 - command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f772a056e80>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:04:30,840 - __init__.py - 开始处理媒体 老兵 (2015)  消息
【INFO】2023-09-03 18:04:30,841 - __init__.py - 发送消息：channel=None，title=老兵 (2015)  已入库, text=类型：电影，类别：华语电影，质量： BluRay 1080p，共1个文件，大小：8.45G，userid=None
【INFO】2023-09-03 18:04:30,845 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f7729efcc20>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:05:16,845 - media.py - 开始识别媒体信息，标题：Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv，副标题： ...
【INFO】2023-09-03 18:05:16,848 - __init__.py - 正在识别 Veteran 2015 ...
【INFO】2023-09-03 18:05:17,641 - tmdbapi.py - 正在查询TMDB电影：346646 ...
【INFO】2023-09-03 18:05:17,642 - tmdbapi.py - 346646 查询结果：老手
【INFO】2023-09-03 18:05:19,321 - tmdbapi.py - 正在查询TMDB电影：346646 ...
【INFO】2023-09-03 18:05:19,323 - tmdbapi.py - 346646 查询结果：老手
【INFO】2023-09-03 18:05:19,324 - tmdbapi.py - 正在从TheDbMovie网站查询：Veteran 2015 ...
【INFO】2023-09-03 18:05:20,494 - tmdbapi.py - Veteran 2015 TMDB网站返回数据过多：2
【INFO】2023-09-03 18:05:20,495 - __init__.py - Veteran 2015 未匹配到媒体信息
【WARNING】2023-09-03 18:05:20,496 - media.py - Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 未识别到媒体信息
【INFO】2023-09-03 18:05:25,381 - media.py - 开始搜索媒体信息：老手
【INFO】2023-09-03 18:05:25,383 - media.py - 老手 搜索到 20 条相关媒体信息
【INFO】2023-09-03 18:05:25,461 - media.py - 开始搜索媒体信息：老手
【INFO】2023-09-03 18:05:25,476 - media.py - 老手 搜索到 20 条相关媒体信息
【INFO】2023-09-03 18:05:25,647 - media.py - 开始搜索媒体信息：老手
【INFO】2023-09-03 18:05:25,682 - media.py - 老手 搜索到 20 条相关媒体信息
【INFO】2023-09-03 18:05:25,768 - media.py - 开始搜索媒体信息：老手
【INFO】2023-09-03 18:05:25,783 - media.py - 老手 搜索到 20 条相关媒体信息
【INFO】2023-09-03 18:05:28,668 - tmdbapi.py - 正在查询TMDB电影：346646 ...
【INFO】2023-09-03 18:05:28,670 - tmdbapi.py - 346646 查询结果：老手
【INFO】2023-09-03 18:05:28,723 - tmdbapi.py - 正在获取电影演职人员：346646...
【INFO】2023-09-03 18:05:28,724 - tmdbapi.py - 正在获取相似电影：346646...
【INFO】2023-09-03 18:05:28,729 - tmdbapi.py - 正在获取推荐电影：346646...
【INFO】2023-09-03 18:05:38,712 - tmdbapi.py - 正在查询TMDB电影：346646 ...
【INFO】2023-09-03 18:05:38,714 - tmdbapi.py - 346646 查询结果：老手
【INFO】2023-09-03 18:05:38,715 - __init__.py - 346646 识别结果：电影 老手 (2015)
【INFO】2023-09-03 18:05:38,715 - transfer.py - 电影 346646 识别为：老手 (2015)
【INFO】2023-09-03 18:05:39,482 - transfer.py - Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 识别为：电影 老手 (2015)
【INFO】2023-09-03 18:05:39,490 - __init__.py - 正在转移文件：/volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 到 /volume1/Media1/电影/外语电影/老手 (2015)/老手 (2015) - 1080p.mkv
【INFO】2023-09-03 18:05:39,491 - __init__.py - 文件 /volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv link完成
【INFO】2023-09-03 18:05:39,495 - __init__.py - 文件 /volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 转移成功
【INFO】2023-09-03 18:05:39,544 - emby.py - 开始刷新Emby媒体库...
【INFO】2023-09-03 18:05:39,545 - command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f772a056e80>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:05:39,571 - __init__.py - 开始刮削媒体库文件：/volume1/Media1/电影/外语电影/老手 (2015)/老手 (2015) - 1080p.mkv ...
【INFO】2023-09-03 18:05:39,572 - scraper.py - 正在生成电影NFO文件：老手 (2015) - 1080p.mkv
【INFO】2023-09-03 18:05:39,579 - scraper.py - NFO文件已保存：/volume1/Media1/电影/外语电影/老手 (2015)/老手 (2015) - 1080p.nfo
【INFO】2023-09-03 18:05:39,580 - scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/y9m021FLQARGxoTyQdJk4C27zCS.jpg ...
【INFO】2023-09-03 18:05:40,970 - scraper.py - 图片已保存：/volume1/Media1/电影/外语电影/老手 (2015)/backdrop.jpg
【INFO】2023-09-03 18:05:40,971 - scraper.py - 正在下载poster图片：https://image.tmdb.org/t/p/original/cFgGG300YnZtDKdAkXKh4eUn6Td.jpg ...
【INFO】2023-09-03 18:05:43,642 - scraper.py - 图片已保存：/volume1/Media1/电影/外语电影/老手 (2015)/poster.jpg
【INFO】2023-09-03 18:05:43,644 - scraper.py - 正在下载logo图片：http://assets.fanart.tv/fanart/movies/346646/hdmovielogo/veteran-571c996530f4a.png ...
【INFO】2023-09-03 18:05:46,271 - scraper.py - 图片已保存：/volume1/Media1/电影/外语电影/老手 (2015)/logo.png
【INFO】2023-09-03 18:05:46,272 - scraper.py - 正在下载thumb图片：http://assets.fanart.tv/fanart/movies/346646/moviethumb/veteran-571c996f9bcaf.jpg ...
【INFO】2023-09-03 18:05:56,770 - scraper.py - 图片已保存：/volume1/Media1/电影/外语电影/老手 (2015)/thumb.jpg
【INFO】2023-09-03 18:05:56,771 - __init__.py - /volume1/Media1/电影/外语电影/老手 (2015)/老手 (2015) - 1080p.mkv 刮削完成
【INFO】2023-09-03 18:05:56,771 - __init__.py - 发送消息：channel=None，title=老手 (2015)  已入库, text=评分：6.9，类型：电影，类别：外语电影，质量： BluRay 1080p，共1个文件，大小：8.45G，userid=None
【INFO】2023-09-03 18:05:56,772 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f7729efcc20>, <function WebHook.send at 0x7f7729ecefc0>]
【INFO】2023-09-03 18:05:58,195 - transfer.py - /volume1/Media1/downloads1/Movies/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai/Veteran.2015.BluRay.1080p.DTS-HD.MA.5.1.x265.10bit-BeiTai.mkv 转移完成，共 1 个文件，成功 1 个，失败 0 个
【INFO】2023-09-03 18:05:58,196 - transfer.py - 开始删除文件以及空目录：/volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.mkv ...
【WARNING】2023-09-03 18:05:58,197 - transfer.py - 文件 /volume1/Media1/电影/华语电影/老兵 (2015)/老兵 (2015) - 1080p.mkv 已删除
【WARNING】2023-09-03 18:05:58,199 - transfer.py - 目录 /volume1/Media1/电影/华语电影/老兵 (2015) 已删除
