### ISSUE TITLE
[错误报告]: chinesesubfinder插件无作用

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#421]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.2

### 问题类型

主程序运行问题

### 问题描述

路径映射：
/我的文件/影音娱乐    /media

日志中显示command.py | 处理事件：transfer.complete | [<function ChineseSubFinder.download at 0x7f1a95ee2b60>, <function WebHook.send at 0x7f1a95dbab60>]

但是chinesesubfinder中并未添加任务

### 发生问题时系统日志和配置文件

```bash
command.py | 处理事件：transfer.complete | [<function ChineseSubFinder.download at 0x7f1a95ee2b60>, <function WebHook.send at 0x7f1a95dbab60>]
```

**Comment by jxxghp** [comment]
后面没有日志了？

插件开关是否打开？

**Comment by xp9477** [comment]
> 后面没有日志了？
> 
> 插件开关是否打开？

没有了，开了

**Comment by loveu5522** [comment]
设置问题，我这边使用无问题

**Comment by WPF0414** [comment]
我这也没问题，检查设置跟日志。

**Comment by xp9477** [comment]
> 设置问题，我这边使用无问题

大佬，可以贴一下你的csf插件设置和csf设置吗

**Comment by xp9477** [comment]
![IMG_0484](https://github.com/jxxghp/MoviePilot/assets/36835224/ebf3d813-a91b-441f-a0bc-aa2e76853fea)
![IMG_0485](https://github.com/jxxghp/MoviePilot/assets/36835224/1333cc0c-c90c-47fc-b02a-1b6c8c3b15dd)
![IMG_0486](https://github.com/jxxghp/MoviePilot/assets/36835224/e46a249f-93eb-46dd-9f9a-8fa61beafb2a)
我之前用nastool的csf插件分别设置了电影和电视剧两个目录映射，使用没问题。mp这个就不知道咋回事

**Comment by xp9477** [comment]
csf自己本身扫描库也没问题

**Comment by WPF0414** [comment]
<img width="854" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/41565284/e657d42e-ba0e-4da0-8f38-2e9a082fa57d">

**Comment by WPF0414** [comment]
参考，上面是mp的volumes, 下面是cf的，最下面是插件

**Comment by xp9477** [comment]
> 参考，上面是mp的volumes, 下面是cf的，最下面是插件

跟我设置的一样呀，难道是英文中文目录名的问题？

**Comment by billconan2017** [comment]
> 参考，上面是mp的volumes, 下面是cf的，最下面是插件

厉害了  谢谢
