### ISSUE TITLE
[Feature Request]:  UI 希望可以适配高分屏

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#423]
### 当前程序版本

1.1.2

### 功能改进

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/333bae45-f004-4ddb-a174-4070187521c2)

win11 自带的高分屏 4k 32寸或以上，会推荐页面缩放150% 

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/f040800b-16e9-49ea-8329-1b7d07dcc0d6)

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/9726b040-5ffb-4433-82c5-e02af614f6ed)

特别是日志页面，哪怕我用 ctrl + 鼠标缩放页面，日志也会显示不全。

另一个问题就是，用浏览器的页面缩放，会导致同域名下，其他端口的docker应用也会被缩放

目前位置其他docker 暂未发现缩放问题，包括NT的界面UI 显示比例也是挺好的

### 参考资料

上代码：

css

css
复制代码
body{
  transform: scale(1,1);
  -ms-transform: scale(1,1); /* IE 9 */
  -webkit-transform: scale(1,1); /* Safari and Chrome */
  transform-origin: left top; /*设置左上角为缩放原点*/
}
js

javascript
复制代码
selfAdaption(){
  this.windowHeight = document.documentElement.clientHeight
  this.windowWidth = document.documentElement.clientWidth
  let heightScale = this.windowHeight/1080
  let widthScale = this.windowWidth/1920
  $('body').css({
    "transform": `scale(${widthScale},${heightScale})`,
    "-ms-transform": `scale(${widthScale},${heightScale})`,
    "-webkit-transform": `scale(${widthScale},${heightScale})`,
  })
  window.onresize = () => { //屏幕尺寸改变时触发
    this.windowHeight = document.documentElement.clientHeight
    this.windowWidth = document.documentElement.clientWidth
    let heightScale = this.windowHeight / 1080
    let widthScale = this.windowWidth / 1920
    $('body').css({
      "transform": `scale(${widthScale},${heightScale})`,
      "-ms-transform": `scale(${widthScale},${heightScale})`,
      "-webkit-transform": `scale(${widthScale},${heightScale})`,
    })
  }
},
优点
css
复制代码
1、此方法是通过在body标签上添加transform：scale（）样式实现的，所以页面的所有元素都会被缩放。
2、复杂程度相较于rem的方式更简便，只需考虑body标签的宽高即可
缺点
复制代码
1、用此方法实现适配的页面在浏览器不能通过ctrl+滚轮缩放页面
2、如果屏幕实际的像素比与设计稿的像素比差别过大，页面会也会被拉伸的比较奇怪

**Comment by jxxghp** [comment]
做过调整了，看看还有什么问题

**Comment by paysenyu** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51367628/56194d7a-8942-448e-9fe2-5e6f38530cf2)


谢谢老大.

像这样.. 32寸的4k显示器, 只能显示4x4 的内容 ...  当然这是因为Windows  系统150% 缩放的问题... 但是如果可以适当的再缩小一些UI尺寸,能大概达到6x6 或者 8x8 的会最好... 

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/e5be6159-834e-489f-b1de-f1c53f0ae87a)

**Comment by paysenyu** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51367628/fcee22f4-2a72-4259-9763-022862b7c36f)

这是手动缩放页面的效果,但是右上角的几个操作按钮就挪到偏中间了.

有空的时候可以研究一下哇, 没适配暂时也不影响使用就是了.
