### ISSUE TITLE
[Feature Request]: 能否给用户多一个选择：增加多库的支持。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#424]
### 当前程序版本

1.1.2

### 功能改进

目前mp默认是单一的下载库和媒体库。
能否多增加一个变量让用户自己选择是否开启多媒体库。
这样也对多盘用户友好，和多媒体库用户需求。默认可以就设置为单库，这样不需要的用户，就还是按照现在这种模式呢。
默认下载源文件库 对应 默认的媒体库link   
下载库2  对应的 媒体库link2  
。。。。
然后每个库都有对应的单独二级目录配置文件呢，可以选择是否开启对应库的二级目录呢。
这样是否会全面些。

**Comment by jxxghp** [comment]
下载支持按不同类型设置不同目录

**Comment by Tsenghan** [comment]
如果两个盘上存的都是电影，目前的版本是不是无法配置目录以应用自动转移？我记得以前nastool有这个功能的

**Comment by Tsenghan** [comment]
> 下载支持按不同类型设置不同目录

如果两个盘上存的都是电影，目前的版本是不是无法配置目录以应用自动转移？我记得以前nastool有这个功能的
