### ISSUE TITLE
[错误报告]: qbittorrent分类自动管理问题

### ISSUE THREAD

**Issue by Waynenet** [jxxghp/MoviePilot#425]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.2

### 问题类型

主程序运行问题

### 问题描述

环境变量配置了QB_CATEGORY: flase则主程序启动不了。
![屏幕截图 2023-09-03 205108](https://github.com/jxxghp/MoviePilot/assets/54445994/326bb9a0-4b23-4071-bbf0-a66424b550ae)

**Comment by jxxghp** [comment]
@Waynenet false ...

**Comment by Waynenet** [comment]
> @Waynenet错误的 ...

好吧，没仔细看，我直接复制了。那你的说明中后面的默认false拼错了。
