### ISSUE TITLE
[Feature Request]: 限速插件可否增加限速地址范围注意不是不限速地址范围

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#432]
### 当前程序版本

V1.1.2

### 功能改进

目前最新代码沿用的还是NT的逻辑可以在限速插件中增加不限速地址范围，可以设置为内网网段，比如192.168.100.0/24，但是有些特殊情况是我需要对内网的某一个IP设备进行限速，以解决类似VPN连接或者FRP穿透回内网的问题，比如我现在在内网的OpenWRT旁路由上开启Wireguard，然后在外面通过Wireguard连回家里通过Jellyfin观看视频，此时我需要jellyfin识别我的ip地址是在旁路由OpenWRT上面，我就需要针对这个IP的播放进行限速，目前的不限速范围地址比较困难实现这一功能，所以可否在额外增加一个限速地址范围，二选一，以更好的应对这种场景的实现呢，谢谢

**Comment by WPF0414** [comment]
x.x.x.x/32就好了

**Comment by yellowstrong** [comment]
> x.x.x.x/32就好了

是只有一个内网地址限速，不是只有一个内网地址不限速
