### ISSUE TITLE
[错误报告]: 站点图标错误

### ISSUE THREAD

**Issue by MyFaith** [jxxghp/MoviePilot#441]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.3

### 问题类型

主程序运行问题

### 问题描述

通过CookieCloud同步完成后，图标对应不上，也试过站点重置，重置后还是错误的

![image](https://github.com/jxxghp/MoviePilot/assets/8826441/5b95a35f-c18b-4a32-bbf1-2ec3367591cb)

**Comment by jxxghp** [comment]
@MyFaith 就是因为重置了对不上，重启，清浏览器缓存
