### ISSUE TITLE
[Feature Request]: 希望电影、电视剧订阅功能可以增加质量选择，分辨率选择，制作组三个可选项

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#445]
### 当前程序版本

V1.1.3

### 功能改进

希望电影、电视剧订阅功能可以增加质量选择，分辨率选择，制作组三个可选项，正则有的时候比较难写，晦涩难懂，希望能直接将这三个常用的选项直接添加进订阅编辑界面供直接选择或者填写，谢谢作者

**Comment by xwxw098** [comment]
正则表达式的逗号要英文，且前后相连不要留空格。比如
Fights Break Sphere S05E60 2022 2160p WEB-DL H265 AAC-DramaS@ADWeb
这是斗破苍穹的名字
正则表达式该这么填
Fights Break Sphere,S0.*,2022,2160p,WEB-DL.H265,AAC-DramaS@ADWeb
这是最完整的填法
其中“.”代表任意一个数据，“*”代表无限个"."  白话就是匹配S0后面的所有数据，直到下一个匹配规则成功匹配

正则表达式比单独拎出来更灵活，更准确

但每次都得这么填确实很麻烦

因此，我觉得更适合的解决方案是可以自己编辑过滤器。每次订阅的时候，先可以选择自己编辑好的过滤器。然后再跳转到左边电视剧订阅栏。  每次点完那个爱心，直接跳进去了，让我措手不及

**Comment by yellowstrong** [comment]
几个比较常用的，拎出来单独设置，个人感觉会更加方便设置，也更易于操作
