### ISSUE TITLE
[错误报告]: 站点数据统计，点立即执行后保存，程序正常执行，但不会发送消息，而且貌似执行周期只能填写一天一次，不能填写一天多次

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#446]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.1.3

### 问题类型

插件问题

### 问题描述

站点数据统计，点立即执行后保存，程序正常执行，但不会发送消息，而且貌似执行周期只能填写一天一次，不能填写一天多次
![iShot_2023-09-05_11 04 34](https://github.com/jxxghp/MoviePilot/assets/34505611/6a737ce9-b30d-4273-a5c6-07994c2d7f06)
如图所示我勾选立即执行后，日志页面获取到了执行信息，但是tg没有收到消息
![iShot_2023-09-05_11 04 16](https://github.com/jxxghp/MoviePilot/assets/34505611/ff4fd314-c821-4f54-be58-f36d629c4176)
而且执行周期只能填写0 9 * * *这种形式，如果我想每6个小时统计一次例如0 */6 * * *也不会按照6小时一次去执行并且发送消息

**Comment by thsrite** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/54088512/ed3cd429-0c14-4e91-868d-1c63e48c6f85)

等更新
#437

**Comment by yellowstrong** [comment]
好的 谢大佬
