### ISSUE TITLE
[Feature Request]: 订阅的搜索，可否添加单独的一个过滤规则，而不是用默认的过滤规则呢。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#447]
### 当前程序版本

1.1.32

### 功能改进

订阅的话因为是自动的，单独设置一个匹配规则的好处在于，比如订阅的不想要1080P的资源，自己手动搜索的话需要1080P的资源，可以手动选择是否下载。

默认搜索过滤规则   订阅搜索过滤规则   洗版过滤规则        感觉这样有3种过滤规则要好一些。

**Comment by cng10001** [comment]
哈，咱也想要，但咱不敢提啊。可能就是mp和nt理念有差异，所以写的就是“设置在搜索和订阅时默认使用的过滤规则”
