### ISSUE TITLE
[Feature Request]: 下载器限速功能

### ISSUE THREAD

**Issue by WPF0414** [jxxghp/MoviePilot#448]
### 当前程序版本

 v1.1.3

### 功能改进

DOWNLOADER=qbittorrent
QB TR都配置了。
1、插件里选择QB限速成功。
2、插件里选择QB，TR，限速只有QB生效，TR不生效。
3、插件里选择TR，不生效。
希望能配置多个下载器限制，不确定是不是bug，所以提了一个改进，大佬有时间看看！

**Comment by zraxx** [comment]
同样问题，qb正常，tr无法限速

**Comment by WPF0414** [comment]
> 

嗯嗯，我是昨天群里反馈了一下，然后看也有人有问题，看git上面没提，我想着我提一下看看！
