### ISSUE TITLE
[错误报告]: 站点数据统计插件不发送通知，并且憨憨有报错

### ISSUE THREAD

**Issue by j506130598** [jxxghp/MoviePilot#455]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.0.13

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/42927502/25706150-11fd-4124-8af8-fc98b3d18644)

**Comment by jxxghp** [comment]
有人提过了，下个版本修复，提问之前先检索一下
