### ISSUE TITLE
[错误报告]: 历史记录同步插件填错了运行后，打开变形无法使用

### ISSUE THREAD

**Issue by 459633382** [jxxghp/MoviePilot#456]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.3

### 问题类型

插件问题

### 问题描述

在插件数据下载器那一栏里，我填错了，填成qbittorrent:transmission并且运行了，之后只要打开历史记录同步插件，就显示成图中那样 重启容器重置容器都无效
![1](https://github.com/jxxghp/MoviePilot/assets/44571764/a6508c42-e08a-435b-8308-fed621a25fdd)

**Comment by jxxghp** [comment]
不给日志，猜不出来

**Comment by 459633382** [comment]
![4](https://github.com/jxxghp/MoviePilot/assets/44571764/9a975192-9c42-42ef-b59a-efd3d261e6b1)

**Comment by 459633382** [comment]
> 不给日志，猜不出来



> 不给日志，猜不出来
> 老大 看看喔
> ![4](https://user-images.githubusercontent.com/44571764/265669926-5684777d-0a6d-4c24-8192-7c5da6bad3c4.jpg)

历史同步插件，只要在数据下载器那一栏填错并运行了，就再也无法正常打开，打开就变形，删除这个插件后重启重置容器都无效
