### ISSUE TITLE
二级分类设置后会出现转移目录重复的情况

### ISSUE THREAD

**Issue by whistle003** [jxxghp/MoviePilot#457]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.3

### 问题类型

Docker或运行环境问题

### 问题描述

你好，我在开启二级分类以后，会出现目录转移时候新建一个同名目录的情况，如国产剧这一分类，已经在/downloads/link/series路径下有该文件夹，但是转移时候又新建了一个/series文件夹，
<img width="1329" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/64147479/8ebab004-3dd6-4a83-959f-7b9247938360">
**环境变量如下：**
```
      - DOWNLOAD_PATH=/downloads/media #下载保存目录，注意：需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移 - 仅供参考
      - DOWNLOAD_MOVIE_PATH=/downloads/media/movies #电影下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_TV_PATH=/downloads/media/series #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_ANIME_PATH=/downloads/media/anime
      - DOWNLOAD_CATEGORY=true #下载二级分类开关，true/false，默认 false,开启后会根据配置 category.yaml 自动在下载目录下建立二级目录分类，因为我不需要这里进行更加详细的分类，电影与剧集两个分类即可，所以可以保持 false，各位可以根据自身需求进行更改
      - DOWNLOAD_SUBTITLE=true #下载站点字幕，true/false，默认true
      - REFRESH_MEDIASERVER=true #入库刷新媒体库，true/false，默认true
      - SCRAP_METADATA=true #刮削入库的媒体文件，true/false，默认true
      - TORRENT_TAG=MOVIEPILOT #种子标签，默认为 MOVIEPILOT，设置后只有 MoviePilot 添加的下载才会处理，留空所有下载器中的任务均会处理
      - LIBRARY_PATH=/downloads/link #媒体库目录，多个目录使用,分隔 - 仅供参考
      - LIBRARY_MOVIE_NAME=movies #电影媒体库目录名，默认电影
      - LIBRARY_TV_NAME=series #电视剧媒体库目录名，默认电视剧
      - LIBRARY_ANIME_NAME=anime
      - LIBRARY_CATEGORY=true # 媒体库二级分类开关，true/false，默认 false，开启后会根据配置 category.yaml 自动在媒体库目录下建立二级目录分类，可以根据自身需求进行更改
```

**Comment by jxxghp** [comment]
无法重现这个问题，也没收到其它反馈，你重启下再试试看。

**Comment by LiuOcean** [comment]
<img width="659" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/20659474/5336f93e-6329-46a0-aef8-2c6acc6513eb">
我这碰到了类似的问题。目前手动二次整理。T^T

我的配置如下：

```yaml
      - DOWNLOAD_PATH=/volume1/视频
      - DOWNLOAD_CATEGORY=false
      - DOWNLOAD_MOVIE_PATH=/volume1/视频/电影
      - DOWNLOAD_TV_PATH=/volume1/视频/电视剧
      - DOWNLOAD_ANIME_PATH=/volume1/视频/日番
      - LIBRARY_PATH=/volume1/视频/link
      - LIBRARY_MOVIE_NAME=电影
      - LIBRARY_TV_NAME=电视剧 
      - LIBRARY_ANIME_NAME=日番
      - LIBRARY_CATEGORY=true 
```

**Comment by whistle003** [comment]
> <img alt="image" width="659" src="https://user-images.githubusercontent.com/20659474/268322602-5336f93e-6329-46a0-aef8-2c6acc6513eb.png">
> 我这碰到了类似的问题，持续了好多版本了，目前是 1.2.1
> 
> 我的配置如下：
> 
> ```yaml
>       - DOWNLOAD_PATH=/volume1/视频
>       - DOWNLOAD_CATEGORY=false
>       - DOWNLOAD_MOVIE_PATH=/volume1/视频/电影
>       - DOWNLOAD_TV_PATH=/volume1/视频/电视剧
>       - DOWNLOAD_ANIME_PATH=/volume1/视频/日番
>       - LIBRARY_PATH=/volume1/视频/link
>       - LIBRARY_MOVIE_NAME=电影
>       - LIBRARY_TV_NAME=电视剧 
>       - LIBRARY_ANIME_NAME=日番
>       - LIBRARY_CATEGORY=true 
> ```

你试一下关闭下载器监控，然后只使用目录同步，我大概就是因为这个才会出现这个问题的。

**Comment by LiuOcean** [comment]
> > <img alt="image" width="659" src="https://user-images.githubusercontent.com/20659474/268322602-5336f93e-6329-46a0-aef8-2c6acc6513eb.png">
> > 我这碰到了类似的问题，持续了好多版本了，目前是 1.2.1
> > 我的配置如下：
> > ```yaml
> >       - DOWNLOAD_PATH=/volume1/视频
> >       - DOWNLOAD_CATEGORY=false
> >       - DOWNLOAD_MOVIE_PATH=/volume1/视频/电影
> >       - DOWNLOAD_TV_PATH=/volume1/视频/电视剧
> >       - DOWNLOAD_ANIME_PATH=/volume1/视频/日番
> >       - LIBRARY_PATH=/volume1/视频/link
> >       - LIBRARY_MOVIE_NAME=电影
> >       - LIBRARY_TV_NAME=电视剧 
> >       - LIBRARY_ANIME_NAME=日番
> >       - LIBRARY_CATEGORY=true 
> > ```
> 
> 你试一下关闭下载器监控，然后只使用目录同步，我大概就是因为这个才会出现这个问题的。

有道理，我应该就关闭下载监控没尝试过。
