### ISSUE TITLE
[错误报告]: 电视剧nfo只能生成每季第一集

### ISSUE THREAD

**Issue by huojinming-1997** [jxxghp/MoviePilot#465]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.4

### 问题类型

主程序运行问题

### 问题描述

电视剧nfo只能生成每季第一集，字幕和集图片也只有第一集，还有季的海报也是错误的苍穹浩瀚
全六季封面图竟然都是一样的
![bug1](https://github.com/jxxghp/MoviePilot/assets/111695498/e82558a2-ecbc-4438-8b5a-4c9b1f028865)
![bug2](https://github.com/jxxghp/MoviePilot/assets/111695498/fba9de53-df5c-4dbb-8ac5-ffd56febc715)
![bug3](https://github.com/jxxghp/MoviePilot/assets/111695498/c919f2a4-6a3d-40ec-8f15-7b9276783674)
![bug4](https://github.com/jxxghp/MoviePilot/assets/111695498/0d8da83a-6ba9-4d39-8b48-aa9009074c57)
![bug5](https://github.com/jxxghp/MoviePilot/assets/111695498/890875c5-bf14-491b-9802-214e38e85957)

### 发生问题时系统日志和配置文件

```bash
ERROR	23:02:48,034	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E07 - 第 7 集.mkv 目录缺失nfo元数据
INFO	23:02:48,034	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E08 - 第 8 集.mkv
ERROR	23:02:48,071	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E08 - 第 8 集.mkv 目录缺失nfo元数据
INFO	23:02:48,072	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E09 - 第 9 集.mkv
ERROR	23:02:48,108	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E09 - 第 9 集.mkv 目录缺失nfo元数据
INFO	23:02:48,108	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E10 - 第 10 集.mkv
ERROR	23:02:48,142	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E10 - 第 10 集.mkv 目录缺失nfo元数据
INFO	23:02:48,142	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E11 - 第 11 集.mkv
ERROR	23:02:48,180	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E11 - 第 11 集.mkv 目录缺失nfo元数据
INFO	23:02:48,180	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E12 - 第 12 集.mkv
ERROR	23:02:48,223	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E12 - 第 12 集.mkv 目录缺失nfo元数据
INFO	23:02:48,224	
__init__.py
通知ChineseSubFinder下载字幕: /media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E13 - 第 13 集.mkv
ERROR	23:02:48,259	
__init__.py
/media/Drama series/苍穹浩瀚 (2015)/Season 3/苍穹浩瀚 - S03E13 - 第 13 集.mkv 目录缺失nfo元数据
```

**Comment by xp9477** [comment]
我也碰到了这个问题，多集只刮削了第一集。
昨天订阅了阿索卡，自动下载了第1-2集，但是只有第一集刮削了。今天出了第3集，自动订阅也是刮削的。就第2集没有
