### ISSUE TITLE
[错误报告]: 存在同英文名电视剧时刮削选择错误

### ISSUE THREAD

**Issue by auosun** [jxxghp/MoviePilot#468]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.4

### 问题类型

主程序运行问题

### 问题描述

刮削 "[鹊刀门传奇].Legend.of.the.Undercover.Chef....." 错误
通过阅读代码，刮削时 第一个[]内名称被删除，使用 "Legend.of.the.Undercover.Chef" 传入TMDB进行刮削，TMDB存在同名剧集
![image](https://github.com/jxxghp/MoviePilot/assets/37408960/16158038-9ce7-471f-b3d3-2c2c2caa8939)
且英文剧集发布日期更新，代码使用倒序排序查询到的结果
![image](https://github.com/jxxghp/MoviePilot/assets/37408960/d79035d0-291d-4495-92ff-4b45f043ee9d)
导致使用英文剧集进行刮削，导致出现错误。
![image](https://github.com/jxxghp/MoviePilot/assets/37408960/c49a1771-c8dd-4df2-98dd-f4ec64680238)

**Comment by auosun** [comment]
是否可以增加更多的排序条件以匹配 目前想到的是传入国家或设置期望语言

**Comment by jxxghp** [comment]
不能以单个剧集的TMDB信息错误导致的识别问题做为调整逻辑的判断标准，如果使用[]内的内容，可能会造成更多其它剧的识别问题，是否有考虑过？
第一个[]内的去除，是NT时大量数据测试过得到的较优解。
倒秩排序也是遇到问题后优化的结果（同名的时候大部门情况下我们都只是在订阅最新的）。
请不要只针对单个数据提问题，根源是TMDB的数据质量，如果算法上有更优解欢迎提供建议（需经过数据证明）。

**Comment by auosun** [comment]
是否可以增加更多的识别参数呢，增加期望识别语言等，遇到这样的问题没有办法通过搜索配置调整识别结果，导致无法入库

**Comment by jxxghp** [comment]
@auosun 识别参数是公共的，调整会影响所有。不是有自定义识别词吗？

**Comment by auosun** [comment]
好的，感谢作者大大，我回去看下自定义识别 词。我是手动整理的时候遇到了，想到可以传入id整理了，非常感谢🙏
