### ISSUE TITLE
[Feature Request]:希望增加直接转移的选项，允许用户使用类似tmm的工具手动整理。

### ISSUE THREAD

**Issue by Next-Page-Vi** [jxxghp/MoviePilot#472]
### 当前程序版本

1.1.4

### 功能改进

由于多种原因，tmdb数据多有恶意锁定和修改的情况存在，数据有效性越来越低，如果存在一种手动削刮的方案将会非常有帮助。
对于mp来说，只需要允许用户整文件夹转移即可，虽然这可以通过指令轻松完成，但是对于很多nas或是特别的设备来说还是有所困难，并且操作有一定的割裂感。

**Comment by jxxghp** [comment]
@Next-Page-Vi 就是不识别重命名，只硬链接？

**Comment by Next-Page-Vi** [comment]
差不多是这个意思，可以说是强制转移或是“仅转移”。然后只链接过去手动削挂，很多tmdb的数据错的离谱。

**Comment by paysenyu** [comment]
请 熟读 readme    

SCRAP_METADATA 这个变量自己去看一下

**Comment by jijidom** [comment]
支持，有很多动漫原盘不能用mp处理，需要手动

**Comment by beyondenvoy** [comment]
@jxxghp 对对很多蓝光原盘，比如一共有10级，分成两个盘（两个文件夹），现在的模式它会合到一个文件夹里，直接没法播放
![image](https://github.com/jxxghp/MoviePilot/assets/99531880/ca7a8b67-bd44-45bf-9361-66cb87df29db)

**Comment by yangn0** [comment]
同求
