### ISSUE TITLE
[Feature Request]: 能否支持如jackett或prowlarr进行搜索下载的支持？

### ISSUE THREAD

**Issue by sebastian0619** [jxxghp/MoviePilot#473]
### 当前程序版本

v1.1.3

### 功能改进

能否支持jackett或prowlarr等索引器进行削刮？

此前没有使用过nastool，用的是jellyseer+radarr+sonarr的方案。

从条件上看，moviepilot要求使用几个pt站，这门槛已经比较高了。我目前有账号的pt站都没有列在认证的站点中。

另外rss的支持感觉也很奇怪？我以为是先收集rss，然后在用户主动搜索要添加订阅的时候，再去rss中找合适的项目？

我尝试把dmhy的rss通过rss插件添加，但是会在电视剧会把那一页的rss全部加入"订阅" ——我不知道是否我理解有误，我觉得他是以为我要把整个rss里的内容都下载下来。

如果是我对项目使用的理解有问题，希望可以尽快协助完善一下wiki。moviepilot吸引我的就是影视一体，并且相比于sonarr，能直接通过tmdb识别中文的元数据。

万分感谢！

**Comment by dlovew** [comment]
不会有的，之前nastool有，后来从nastools剔除，mp不会有这个功能的！

**Comment by sebastian0619** [comment]
> 不会有的，之前nastool有，后来从nastools剔除，mp不会有这个功能的！

那是否可以通过收集下载rss，然后在用户有搜索需求的时候再去下载好的rss里找结果呢？

这样子的话，诸如dmhy, mikan等几个动漫bt站就都没法用了呀

**Comment by yangchris4** [comment]
> > 不会有的，之前nastool有，后来从nastools剔除，mp不会有这个功能的！
> 
> 那是否可以通过收集下载rss，然后在用户有搜索需求的时候再去下载好的rss里找结果呢？
> 
> 这样子的话，诸如dmhy, mikan等几个动漫bt站就都没法用了呀

你说的两个站都是支持的呀
![mikan](https://github.com/jxxghp/MoviePilot/assets/13220804/40766bd0-59ed-4182-a84d-23dd247e3f06)

**Comment by sebastian0619** [comment]
> 

我不知道是不是配置的问题... 我mp的设置用cookiecloud读不到站点。docker-compose down以后换了nastool，就读出来了

**Comment by zero617** [comment]
> > > 不会有的，之前nastool有，后来从nastools剔除，mp不会有这个功能的！
> > 
> > 
> > 那是否可以通过收集下载rss，然后在用户有搜索需求的时候再去下载好的rss里找结果呢？
> > 这样子的话，诸如dmhy, mikan等几个动漫bt站就都没法用了呀
> 
> 你说的两个站应该都是支持的呀

mikan你是怎么配置的，我似乎也不行

**Comment by yangchris4** [comment]
> > > > 不会有的，之前nastool有，后来从nastools剔除，mp不会有这个功能的！
> > > 
> > > 
> > > 那是否可以通过收集下载rss，然后在用户有搜索需求的时候再去下载好的rss里找结果呢？
> > > 这样子的话，诸如dmhy, mikan等几个动漫bt站就都没法用了呀
> > 
> > 
> > 你说的两个站应该都是支持的呀
> 
> mikan你是怎么配置的，我似乎也不行

没特殊配置啊，之前有的版本有时候会同步一些自己没有的站，我就是那时候自动同步过去的mikan，后来一直没管过。cookiecloud不能同步吗？
