### ISSUE TITLE
[Feature Request]: 希望增加单独的插件通知渠道，而不是走媒体服务器通知

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#477]
### 当前程序版本

v1.1.4

### 功能改进

希望增加单独的插件通知渠道，而不是插件通知走媒体服务器通知

### 参考资料

插件设置的通知，但是收不到通知消息，打开了媒体服务器通知开关后才收到插件的通知消息

**Comment by jxxghp** [comment]
按插件数据对应的用途通知，跟站点有关就走站点，跟媒体服务器有关就走媒体服务器。

**Comment by CookieJaySJ** [comment]
> 按插件数据对应的用途通知，跟站点有关就走站点，跟媒体服务器有关就走媒体服务器。

主要是跟emby有关的插件比较多。比如播放限速，就必须打开emby的播放暂停的webhook，同步删除也需要打开emby的webhook。然而这些都打开的话，播放媒体的时候会弹好几条通知，很是头疼。  比方说我只想看限速有没有成功，同时限速是多少，这种情况下还会通知媒体播放详情，这个并不能够关闭。

还是希望老大加一个插件通知分类，统一管理插件的通知。这样自定义程度高一些，使用起来也更舒适一些。
@jxxghp
