### ISSUE TITLE
[错误报告]: 天空的搜索结果做种与下载者数量不正确以及不显示种子大小

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#478]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.4

### 问题类型

主程序运行问题

### 问题描述

天空的搜索结果做种与下载者数量不正确以及不显示种子大小

搜索结果，未显示种子大小
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/96c439e6-8ec6-4ea9-95ee-99c175176a7e)

实际种子的做种与下载者
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/384a18aa-117a-488d-9d15-1335f4f1b1b9)

**Comment by jxxghp** [comment]
<img width="464" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/590dd8fd-2e0f-4749-b430-e9e44c90b223">
我试了下是正常的哦，配置上也没发现有问题

**Comment by mjsoftking** [comment]
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/839dae33-254b-4dc2-b60e-ff2dcfd5e3de)
其他站都正常，就这个不行，清空浏览器缓存，还是一样的
