### ISSUE TITLE
[错误报告]: 企业微信自动添加菜单出错

### ISSUE THREAD

**Issue by leo8912** [jxxghp/MoviePilot#479]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.4

### 问题类型

主程序运行问题

### 问题描述

查了下这错误代码，是说调用的accesstoken对应应用跟传入参数的agentid对应的应用不一致
但是我填写的都是该企业微信应用的信息啊，并且收发通知以及交互也是正常的。

### 发生问题时系统日志和配置文件

```bash
ERROR:   wechat.py - 发送请求失败，错误信息：not allow operate another agent with this accesstoken., hint: [1693989761612132943518721], from ip: ******, more info at https://open.work.weixin.qq.com/devtool/query?e=301002
```

**Comment by Hovenia** [comment]
老哥，你这个解决了吗，我遇到和你一样的问题

**Comment by mzj001** [comment]
兄弟，用的是caddy 2 反代理的吧？，一样的问题，你解决了没？

**Comment by Hovenia** [comment]
> 兄弟，用的是caddy 2 反代理的吧？，一样的问题，你解决了没？

我的解决了，可以检查一下WECHAT_APP_ID是不是填写的有问题，是不是多了空格

**Comment by mzj001** [comment]
> > 兄弟，用的是caddy 2 反代理的吧？，一样的问题，你解决了没？
> 
> 我的解决了，可以检查一下WECHAT_APP_ID是不是填写的有问题，是不是多了空格

果然是多了个空格。。

**Comment by Nick0223** [comment]
ERROR:   [moviepilot] 2026-01-13 13:17:09,304 wechat.py - 发送请求失败，错误信息：not allow operate another agent with this accesstoken., hint: [1768281429499302175003038], from ip: 223.166.31.129, more info at https://open.work.weixin.qq.com/devtool/query?e=301002

我用浏览器拼了这个https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=YOUR_CORPID&corpsecret=YOUR_SECRET 得到的是成功的
{"errcode":0,"errmsg":"ok","access_token":"ACSRovTRQIC14Q0EgmDSEgBH9UhOQSk5huZllH7NZGg0NGkOGGSIZwusOOOrOwupEbAYsWk2O3rhmnFHMdhe_HbQbTrhObTYcLCEEvovtdRtb7-YoYTeBFK8um6EQ5bkf5FdCGYFciQ9F2Z34uHdO1lGzCVHCTm7GO5_XPEDdM-Q13j-63UH1KvgfuGgW022tXgXuObnCy49OfZX_hIiUw","expires_in":7200}

但是mp怎么检查重启都不行，一直报错，求求了，有没有大佬给个思路
