### ISSUE TITLE
[错误报告]: 刷新订阅后台日志报错

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#490]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.1.5

### 问题类型

主程序运行问题

### 问题描述

代码报错信息如图
<img width="1156" alt="iShot_2023-09-07_12 28 31" src="https://github.com/jxxghp/MoviePilot/assets/34505611/76cb4f71-81fa-4d5b-a65a-4e2ab9915699">

**Comment by xp9477** [comment]
![IMG_0525](https://github.com/jxxghp/MoviePilot/assets/36835224/14fa0198-810e-4967-b44f-132e03dfabd0)
同样的问题
