### ISSUE TITLE
资源订阅订阅和搜索是经常出现标题不匹配

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#491]
资源订阅和搜索经常出现标题不匹配，但实际上是匹配的

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xp9477** [comment]
![IMG_0526](https://github.com/jxxghp/MoviePilot/assets/36835224/00688f73-079d-4a2f-bd4b-708466246b71)

**Comment by jxxghp** [comment]
没有年份
