### ISSUE TITLE
[Feature Request]: 能否增加一个手动添加下载入口

### ISSUE THREAD

**Issue by combat60** [jxxghp/MoviePilot#495]
### 当前程序版本

1.1.5

### 功能改进

功能类似nastool
可以手动添加种子或者链接到下载器

**Comment by samyang211** [comment]
+  同需求，有时mp上搜索不到的时候，ptpp上搜到的链接想通过mp来下载和管理

**Comment by huojinming-1997** [comment]
> * 同需求，有时mp上搜索不到的时候，ptpp上搜到的链接想通过mp来下载和管理

这个好啊，假如能把ptpp以插件形式加进来就更好，老实说现在需要挑选资源还是得靠ptpp
