### ISSUE TITLE
[错误报告]: 历史记录里删除剧集同步媒体文件未能同步删除搜刮的图片

### ISSUE THREAD

**Issue by huojinming-1997** [jxxghp/MoviePilot#508]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.6

### 问题类型

主程序运行问题

### 问题描述

历史记录里删除剧集同步媒体文件未能同步删除搜刮的图片，估计是没能删除图片导致文件夹也无法被删除，下图为残留的图片
![bug9](https://github.com/jxxghp/MoviePilot/assets/111695498/f09fcc04-4d0d-4bed-bb6c-3b965e51fa69)

### 发生问题时系统日志和配置文件

```bash
INFO	16:14:47,337	
transfer.py
开始删除文件以及空目录：/media/hlink/Drama series/超异能族 (2023)/Season 1/超异能族 - S01E15 - 第 15 集.mkv ...
WARNING	16:14:47,361	
transfer.py
文件 /media/hlink/Drama series/超异能族 (2023)/Season 1/超异能族 - S01E15 - 第 15 集.mkv 已删除
INFO	16:14:53,360	
transfer.py
开始删除文件以及空目录：/media/hlink/Drama series/超异能族 (2023)/Season 1/超异能族 - S01E14 - 第 14 集.mkv ...
WARNING	16:14:53,387	
transfer.py
文件 /media/hlink/Drama series/超异能族 (2023)/Season 1/超异能族 - S01E14 - 第 14 集.mkv 已删除
WARNING	16:14:53,391	
transfer.py
目录 /media/hlink/Drama series/超异能族 (2023)/Season 1 已删除
```

**Comment by xp9477** [comment]
电视剧也是
