### ISSUE TITLE
[Feature Request]: 历史记录中电视剧的刮削记录能否合并在一个项目中

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#509]
### 当前程序版本

1.1.6

### 功能改进

多集电视剧如果识别错误的话手动整理起来很麻烦。
不知道能否合并在同一行里，点进去再显示单集的历史记录

**Comment by jifengguo** [comment]
这个支持，电视剧的记录太多了。合并一下挺好的。

**Comment by Shurelol** [comment]
@jifengguo 单集识别错误无法排查
