### ISSUE TITLE
洗版成功后没有删除低质量版本

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#517]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.6

### 问题类型

主程序运行问题

### 问题描述

洗版成功后没有删除低质量版本
![IMG_0558](https://github.com/jxxghp/MoviePilot/assets/36835224/0b5103d2-9e5a-4e00-bba7-a57bcac8e8d3)

**Comment by xp9477** [comment]
![IMG_0557](https://github.com/jxxghp/MoviePilot/assets/36835224/0fdc91aa-d7c9-476f-86ea-f517690caf7f)

**Comment by developer-wlj** [comment]
现有方案, 命名规则上去除分辨率, 相同文件名就会覆盖

**Comment by z2561221** [comment]
> 现有方案, 命名规则上去除分辨率, 相同文件名就会覆盖

这样有一个情况出现。两个不同格式的种子，后缀不同，并不会覆盖，会产生两个文件。

**Comment by jxxghp** [comment]
下个版本支持

**Comment by dream10201** [comment]
@jxxghp 问题还是存在，v2.8.1-1

<img width="379" height="128" alt="Image" src="https://github.com/user-attachments/assets/64208230-a154-4283-91be-09a86480696f" />

**Comment by dream10201** [comment]
按道理应该要覆盖才对
<img width="393" height="638" alt="Image" src="https://github.com/user-attachments/assets/c83c4ccd-967e-4beb-b444-e1f8ef11d216" />

**Comment by z2561221** [comment]
> 按道理应该要覆盖才对 <img alt="Image" width="393" height="638" src="https://private-user-images.githubusercontent.com/20334372/500373390-c83c4ccd-967e-4beb-b444-e1f8ef11d216.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAzMzgwODUsIm5iZiI6MTc2MDMzNzc4NSwicGF0aCI6Ii8yMDMzNDM3Mi81MDAzNzMzOTAtYzgzYzRjY2QtOTY3ZS00YmViLWI0NDQtZTFmOGVmMTFkMjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDEzVDA2NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NmNlNTZiZGY0ZDMxY2E4OTgxY2ZmOWMyNmZkMTc4MDBkYjgzMWVkNmFiMDZiZDZhNzE2MGZhNzc4N2FhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uHGuVFU6eGHqjyzq8dobpz_ZhYYFRUuk_daAwTA8L6A">

覆盖方式：仅保留最新
