### ISSUE TITLE
[Feature Request]: 添加下载器下载目录和容器实际访问目录

### ISSUE THREAD

**Issue by guziwen** [jxxghp/MoviePilot#531]
### 当前程序版本

1.1.7

### 功能改进

DOWNLOAD_PATH： 下载保存目录，注意：需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移

我现在使用Windows docker和Windows版本的qb，无法实现映射相同目录，能否添加和nastool一样的下载器下载目录和容器实际访问目录功能？

**Comment by mjsoftking** [comment]
关闭下载转移，使用目录监控就可以，我目前就用的目录监控
