### ISSUE TITLE
建议增加使用代理功能插件

### ISSUE THREAD

**Issue by zraxx** [jxxghp/MoviePilot#533]
### 当前程序版本

1.1.7

### 功能改进

因只在更新程序时，使用代理功能，建议增加使用代理功能插件，可随时关闭和启用。谢谢！

**Comment by dlovew** [comment]
tmdb识别不要代理么？

**Comment by mjsoftking** [comment]
现在没使用代理吗，添加代理去联通性测试一下看看

**Comment by zraxx** [comment]
> 现在没使用代理吗，添加代理去联通性测试一下看看

使用代理，站点认证失败

**Comment by mjsoftking** [comment]
> > 现在没使用代理吗，添加代理去联通性测试一下看看
> 
> 使用代理，站点认证失败

我用的IYUU认证，如果还失败，最好确认下代理配置是否正常
