### ISSUE TITLE
文件整理屏蔽词未生效

### ISSUE THREAD

**Issue by Chen3553887** [jxxghp/MoviePilot#536]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.1.7

### 问题类型

主程序运行问题

### 问题描述

添加完**文件整理屏蔽词**后，整理文件时依然会去识别屏蔽词的内容
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/a93d1e46-ec67-4731-b7cf-d3362aa87b57)
这个是文件名
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/55dece86-4e41-49dc-bd01-c37070671efa)
这个是文件夹中
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/45c07a4a-57c2-4417-bde2-f5ca249b422e)

**Comment by jxxghp** [comment]
是通过什么方式整理的？下载器监控还是手动还是目录同步？

**Comment by Chen3553887** [comment]
> 是通过什么方式整理的？下载器监控还是手动还是目录同步？

手动在**文件管理**里面整理

**Comment by jxxghp** [comment]
方案贴一下文件名吗，我模拟一下

**Comment by Chen3553887** [comment]
> 方案贴一下文件名吗，我模拟一下
设置屏蔽词为：

NCED
NCOP
Bonus
下为文件夹+文件名：

/[BDrip] Yuusha ga Shinda S01 [7³ACG]/NCED.mkv
/[BDrip] Yuusha ga Shinda S01 [7³ACG]/NCOP.mkv
/[LP-Raws] Yosuga no Sora [Ma10p_1080p]\Bonus/[LP-Raws] Yosuga no Sora NCED01 (BDRip 1080p HEVC-YUV420P10 FLAC).mkv
