### ISSUE TITLE
[错误报告]: 凌晨时间段是不是不会刷新新的种子

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#544]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.8

### 问题类型

主程序运行问题

### 问题描述

订阅的动漫很多都是凌晨上传，但是早上起来发现没有订阅到。查看了日志发现凌晨时间段没有刷新各个站点种子的日志，到早上七点二十三左右才开始刷新种子，但是刷到的33个新种子并没有最新的剧集，反而是两天前的种子被刷新到了（处于置顶状态）站点是观众

**Comment by jxxghp** [comment]
不会
