### ISSUE TITLE
[错误报告]: 憨憨网站签到显示成功，实际签不到

### ISSUE THREAD

**Issue by eadorothy86** [jxxghp/MoviePilot#547]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.8

### 问题类型

插件问题

### 问题描述

![photo_2023-09-11_10-19-48](https://github.com/jxxghp/MoviePilot/assets/85786428/ee774193-3e31-4651-9560-6b2569d69d94)
![photo_2023-09-11_10-19-54](https://github.com/jxxghp/MoviePilot/assets/85786428/ec58c405-53c0-4675-aa67-9bc8958081ee)
![1694398974004](https://github.com/jxxghp/MoviePilot/assets/85786428/7ca0355a-6f5b-4679-b8d9-1e749f7384a4)
上述网站显示签到成功，实际是没签到，特意试了几天不点进去签到页面，全部都没签到

**Comment by dlovew** [comment]
不存在这个问题，是不是网络问题

**Comment by eadorothy86** [comment]
> 不存在这个问题，是不是网络问题

怎样测试这个站都是通过的，请问你是如何解决的？谢谢
