### ISSUE TITLE
[Feature Request]: 增加对副标题集数的识别（如果存在集数组，主标题没有相关信息，尝试从副标题提取）

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#548]
### 当前程序版本

1.1.8

### 功能改进

增加对副标题集数的识别（如果存在集数组，主标题没有相关信息，尝试从副标题提取）

### 参考资料

(https://github.com/hsuyelin/nas-tools/releases)

**Comment by jxxghp** [comment]
@dlovew 本来就会啊

**Comment by dlovew** [comment]
> @dlovew 本来就会啊

今天下载了一个单集，标题和种子都不带集信息，下载时推送的信息也没有说xx集，然后没有入库，没有一点反应，自己手动在文件管理入库的

**Comment by dlovew** [comment]
[[HHC].时光音乐会·老友记.Time.Concert.S3.2021.1080p.WEB-DL.H264.AAC-HHWEB.torrent]
时光音乐会 第三季 | 第01期 | 类型:音乐/真人秀 | 主演:张杰/邓紫棋/陈嘉桦/于文文/王源
是不是第xx期不行

**Comment by jxxghp** [comment]
@dlovew 应该是
