### ISSUE TITLE
ios14浏览器无法正常显示登陆窗口

### ISSUE THREAD

**Issue by shanzhoo** [jxxghp/MoviePilot#551]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

118

### 问题类型

主程序运行问题

### 问题描述

![微信图片_20230911154239](https://github.com/jxxghp/MoviePilot/assets/59805346/eb4acdd9-347a-42d9-843e-625ff603e759)

求求大佬修复一下。

**Comment by wanyuxi88** [comment]
作者已明确表示不支持ios14

**Comment by jxxghp** [comment]
没有设备调试，不支持。
