### ISSUE TITLE
[错误报告]: 简短文件名识别问题

### ISSUE THREAD

**Issue by Chen3553887** [jxxghp/MoviePilot#552]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.8

### 问题类型

主程序运行问题

### 问题描述

当文件名较为简洁，不附带年份时可能会导致识别结果正确，但是类型错误（电影识别成电视剧）
案例：
[Haruhana] Tenki no Ko [BDRip][HEVC-10bit 1080p].mkv
[Airota&VCB-Studio] Gekijouban Chuunibyou demo Koi ga Shitai! [Hi10p_1080p][x264_flac].mkv
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/38f18214-43a5-4911-8cb0-34ba1ca26aba)

类型识别成了电视剧、连载动漫。当补足年份时可以正常识别
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/808972d3-96eb-4504-ba68-6b2e7680d0b9)
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/98645295-2772-4eed-ad85-98d509725125)

以及当出现这个bug的时候，多次识别同一个名字会出现缓存问题导致识别错误（清理缓存可以重置bug）
![image](https://github.com/jxxghp/MoviePilot/assets/74977868/21b09b4b-993f-4ab3-851d-418e76225be6)

**Comment by Chen3553887** [comment]
Tenki no Ko这个词条并没有相同别名的影片，只有一部《天气之子》。
识别结果中的tmdbid也是对的，只是最后的识别类型（电影、电视剧）是错误的。

**Comment by jxxghp** [comment]
> Tenki no Ko这个词条并没有相同别名的影片，只有一部《天气之子》。 识别结果中的tmdbid也是对的，只是最后的识别类型（电影、电视剧）是错误的。

这个确实是因为TMDBID相同导致的

**Comment by Chen3553887** [comment]
在《天气之子》的例子中，点击tmdbid跳转到的是地址是https://www.themoviedb.org/tv/568160
可以从链接中看出他识别的是tv，但是目标链接不存在。而《天气之子》的tmdb则是568160，修改tv为movie即可正确访问

**Comment by jxxghp** [comment]
确认有问题，我调整了下，应该正常了：

![image](https://github.com/jxxghp/MoviePilot/assets/51039935/ab127a0a-bb4e-4f95-b7ef-9e9dd0a48239)

**Comment by Chen3553887** [comment]
老大辛苦了
