### ISSUE TITLE
[错误报告]: 删除资源速度非常慢

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#553]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.8

### 问题类型

主程序运行问题

### 问题描述

在unraid 下近期的版本,删除资源速度非常慢

给的权限是 99 100 022 ,  影视数据的权限是 nobody 

![image](https://github.com/jxxghp/MoviePilot/assets/51367628/9cd48901-8030-45c7-8984-fae250c6d38a)

从日志可以看到,从18点29分开始删除,一直到 18:30分10秒才删掉

我只选择了2集进行删除,差不多一集花了 20多秒...

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-09-11 18:29:25,570 - transfer.py - 开始删除文件以及空目录：/Media/hlink/电视剧/国产剧/西出玉门 (2023)/Season 1/西出玉门 - S01E11 - 第 11 集.mp4 ...
【WARNING】2023-09-11 18:29:25,570 - transfer.py - 文件 /Media/hlink/电视剧/国产剧/西出玉门 (2023)/Season 1/西出玉门 - S01E11 - 第 11 集.mp4 已删除
【INFO】2023-09-11 18:30:10,444 - transfer.py - 开始删除文件以及空目录：/Media/hlink/电视剧/国产剧/西出玉门 (2023)/Season 1/西出玉门 - S01E12 - 第 12 集.mp4 ...
【WARNING】2023-09-11 18:30:10,445 - transfer.py - 文件 /Media/hlink/电视剧/国产剧/西出玉门 (2023)/Season 1/西出玉门 - S01E12 - 第 12 集.mp4 已删除
```

**Comment by jxxghp** [comment]
你的系统问题吧
