### ISSUE TITLE
[错误报告]: 有一部动漫一直在反复下载

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#554]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.8

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/59035223/dd32a4ec-3dda-4bb3-80a0-a57d62c7cd72)
其实媒体库已经更新到第10集了，但是订阅信息不正确，只有这部剧这样，同步媒体库也没用，重启一下订阅集数又变了，导致一直在反复下载
![screenshot20230911 (1)](https://github.com/jxxghp/MoviePilot/assets/59035223/a7c5cbab-309b-4427-ba43-28deeb87e855)
历史记录入库一大堆了已经

**Comment by jxxghp** [comment]
这么提问题，是没办法分析的。

**Comment by dlovew** [comment]
日志显示，媒体库这部剧缺了集，然后下载，下载以后看订阅信息到了10/13，但是过一段时间又变成1/13或者x/13，显示缺了某些集，再下载
