### ISSUE TITLE
[错误报告]: 订阅功能包含功能添加正则表达式以后，无法修改或者删除

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#557]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.1.8

### 问题类型

主程序运行问题

### 问题描述

如题，我经过测试发现，目前系统中订阅功能，我添加完成后，首先编辑包含，填入正则表达式如下^(?=.*QHstudIo)(?=.*2160p)(?=.*(?:HDR|DV)).*$点保存，提示更新成功，然后刷新页面，再次修改次订阅包含，填入如下正则^(?=.*(?:不可说|不可说|QHstudIo|HDSWEB))(?=.*(?:2160p|4k))(?=.*(?:HDR|DV)).*$，再次点击保存，未提示更新成功，再次打开页面，显示的是第二次修改结果即^(?=.*(?:不可说|不可说|QHstudIo|HDSWEB))(?=.*(?:2160p|4k))(?=.*(?:HDR|DV)).*$，但是刷新页面以后，就会变回未修改之前的内容，排除也有同样的问题，反而如果只更新订阅站点，可以成功

**Comment by jxxghp** [comment]
提供下后台日志，我使用你的数据测了下，都可以提示保存成功。

**Comment by yellowstrong** [comment]
> 提供下后台日志，我使用你的数据测了下，都可以提示保存成功。

昨天太晚了没来得及录制，以下是操作视频以及日志

![2023-09-12 09 26 29](https://github.com/jxxghp/MoviePilot/assets/34505611/9b2c2ad1-2ac5-450a-b63f-8dc61b3cb49e)

https://github.com/jxxghp/MoviePilot/assets/34505611/39090cb6-5aa9-4686-8985-7d1e116f1de1

**Comment by yellowstrong** [comment]
刚刚发现，是去掉了下面的站点勾选导致的，应该判断去掉以后就是默认搜索全部站点
