### ISSUE TITLE
[错误报告]: SUPERUSER_PASSWORD无效

### ISSUE THREAD

**Issue by ixzhaoo** [jxxghp/MoviePilot#558]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.1.8

### 问题类型

主程序运行问题

### 问题描述

应该跟#317 是同样的问题。
docker安装时，使用环境变量指定密码，该密码无效，使用默认的password可以登录成功。

**Comment by jxxghp** [comment]
问题不存在，自己排查下原因吧。
