### ISSUE TITLE
[错误报告]: 集数定位问题

### ISSUE THREAD

**Issue by Next-Page-Vi** [jxxghp/MoviePilot#559]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.8

### 问题类型

主程序运行问题

### 问题描述

集数定位时{ep}不能正确的识别01这样的集数，以下是例子：
1.[Snow-Raws] とある科学の超電磁砲 第{ep}{a}.mkv
可以识别：[Snow-Raws] とある科学の超電磁砲 第10話 (BD 1920x1080 HEVC-YUV420P10 FLAC).mkv
不能识别：[Snow-Raws] とある科学の超電磁砲 第09話 (BD 1920x1080 HEVC-YUV420P10 FLAC).mkv
2.[Snow-Raws] とある科学の超電磁砲 第0{ep}{a}.mkv
可以识别：[Snow-Raws] とある科学の超電磁砲 第09話 (BD 1920x1080 HEVC-YUV420P10 FLAC).mkv

**Comment by jxxghp** [comment]
因为你的{a}把第一个数字后面给拦掉了，换成这样就行了：
[Snow-Raws] とある科学の超電磁砲 第{ep}話{a}.mkv
