### ISSUE TITLE
[Feature Request]: 豆瓣榜单订阅增加年份

### ISSUE THREAD

**Issue by pengjiann** [jxxghp/MoviePilot#561]
### 当前程序版本

1.1.9

### 功能改进

是否可以在豆瓣榜单订阅里限制一个年份，有时候的需求就是需要自动下载新出的高分影片，经常会下载到90年代的影片

**Comment by mexiaow** [comment]
RSSHUB可以用URL query 过滤内容

比如：[https://rsshub.app/douban/list/movie_real_time_hotest?filter=2023](https://rsshub.app/douban/list/movie_real_time_hotest?filter=2023)
