### ISSUE TITLE
[错误报告]: 手动点击文件整理时，tg重复收到已入库的消息

### ISSUE THREAD

**Issue by Herbertzz** [jxxghp/MoviePilot#568]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1。9

### 问题类型

其他问题

### 问题描述

在文件管理中，对 film（里面包含所有的电影）目录进行文件整理，tg会收到重复整理入库的消息。
处理完第一个电影，会发送一条已入库消息。
处理完第二个，会发送两条已入库消息，其中一条是第一个电影的已入库消息。
第三个，会发送三条，重复发送上述两条的已入库消息。
....
以此类推，第N个电影，会重复发送N条已入库消息。

**Comment by jxxghp** [comment]
无法重现，也没有收到其他人反馈。
