### ISSUE TITLE
[错误报告]: 刮削了sample文件

### ISSUE THREAD

**Issue by xp9477** [jxxghp/MoviePilot#570]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.9

### 问题类型

主程序运行问题

### 问题描述

<img width="1295" alt="截屏2023-09-12 19 08 36" src="https://github.com/jxxghp/MoviePilot/assets/36835224/8dd098d9-2fcc-4e7b-9f0a-b8287488cc5f">

**Comment by zraxx** [comment]
同样问题！
