### ISSUE TITLE
[错误报告]: QB转移TR导致种子Track消失

### ISSUE THREAD

**Issue by MrSaiDing** [jxxghp/MoviePilot#579]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.1.9

### 问题类型

插件问题

### 问题描述

QBv4.5.5 转移到TR3.0 track消失
[img]https://ptpimg.me/02cd9d.png[/img]

**Comment by mjsoftking** [comment]
我是升级TR到4.0.4了，没有问题了

**Comment by MrSaiDing** [comment]
问题是大部分人还是在用TR3.0，还有一些站点不支持TR4.0
如果我这个问题是普遍问题的话，这就很麻烦。我这边没有备份，种子丢失track只能重下，要找回的话要花很长的时间

**Comment by mjsoftking** [comment]
@jxxghp 老大，经测试TR4.0.4的是正常的，TR3.00转移做种还存在问题，会丢失track。

**Comment by jxxghp** [comment]
改成了使用和NT一样的模块，可以更新下试试（注意先不要扣选删除源种子）。

```shell
MOVIEPILOT_AUTO_UPDATE_DEV=true #开启重启更新最新代码
```

**Comment by mjsoftking** [comment]
@jxxghp 重新下载了3.00，测了一下，目前正常
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/57929a35-2f19-4505-a864-51c0ad0acb71)
