### ISSUE TITLE
[错误报告]: 使用EMBY webhook删除源文件，只有电影可以删除，电视剧不能删除

### ISSUE THREAD

**Issue by MrSaiDing** [jxxghp/MoviePilot#580]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.1.9

### 问题类型

插件问题

### 问题描述

Emby版本是4.8.0.46，使用webhook删除电影正常，但是电视剧这边没有任何日志
[img]https://ptpimg.me/0a5k9u.png[/img]

**Comment by thsrite** [comment]
emby的问题，emby再删除电视剧季和整部电视剧时没有发送webhook
close吧

**Comment by MrSaiDing** [comment]
所以说可以找emby那边提交bug对吗？ 让luke修复？

**Comment by thsrite** [comment]
> 所以说可以找emby那边提交bug对吗？ 让luke修复？

https://emby.media/community/index.php?/topic/121297-emby-48045-librarydeleted-webhook-bugs/
我提了
