### ISSUE TITLE
形如“S1E1”集数识别问题

### ISSUE THREAD

**Issue by dandkong** [jxxghp/MoviePilot#581]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.1.9

### 问题类型

主程序运行问题

### 问题描述

是用工具批量重命名的，如图S01E1,S1E1这种命名法不能正确识别，改成S01E01才能识别
![photo_6055143914828053500_y](https://github.com/jxxghp/MoviePilot/assets/31849833/061ab61a-dd2a-40e7-950e-4f5c6a020b5e)

### 发生问题时系统日志和配置文件

```bash
暂无
```

**Comment by dandkong** [comment]
类型s1e1这种也不行，只有一位数就识别不出来了

**Comment by jxxghp** [comment]
可以的，无法识别媒体信息可能是TMDB短暂性连不上。集数无法识别也不会报这个错，只会不显示信数。

<img width="821" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/f153b329-f59d-4c50-8c01-cfe76dd3ed33">

**Comment by dandkong** [comment]
> 可以的，无法识别媒体信息可能是TMDB短暂性连不上。集数无法识别也不会报这个错，只会不显示集数。
> 
> 
> 
> <img width="821" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/f153b329-f59d-4c50-8c01-cfe76dd3ed33">
> 
> 

经过测试发现是空格的问题，“爱很美味S01E7”不能识别，“爱很美味 S01E7”就可以了，不知道算不算可以优化
