### ISSUE TITLE
[错误报告]: 请在此处简单描述你的问题

### ISSUE THREAD

**Issue by johnita-biubiu** [jxxghp/MoviePilot#585]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.0

### 问题类型

插件问题

### 问题描述

自动签到插件-Ourbits我堡站点不能自动签到，辛苦大佬。

**Comment by thsrite** [comment]
不能

**Comment by johnita-biubiu** [comment]
> 不能

 大佬这个问题是不能修复对吗？

**Comment by jxxghp** [comment]
已经优化了
