### ISSUE TITLE
[Feature Request]: 目录监控，多种转移方式共存

### ISSUE THREAD

**Issue by ershouqingge** [jxxghp/MoviePilot#586]
### 当前程序版本

v1.2.0

### 功能改进

不同的目录有不同的目的，有的目录需要硬链接保种，有的目录例如网盘只能直接转移。

### 参考资料

监控目录:转移目录:转移方式

**Comment by ershouqingge** [comment]
我遇到这个问题主要是因为我的tr下载器不能被mp监控标签和正在下载的任务，无法通过下载器硬链接转移入库。#331


我尝试使用目录监控，但是目录监控只有一种转移方式。

**Comment by mrxiaozuo** [comment]
升级到tr4.0以上版本可正常监控显示正在下载任务列表

**Comment by thsrite** [comment]
#765 同
