### ISSUE TITLE
安装配置更新问题

### ISSUE THREAD

**Issue by glenhuo** [jxxghp/MoviePilot#59]
请问大大有考虑MoviePilot安装配置像nastool一样在应用内配置吗？还有更新可以如同nastool那样docker重启自动更新吗？

**Comment by yalidabuda** [comment]
同问，是否计划改为图形界面来设置，现在用变量设置对俺们手残党来说，压力有点个大。😂😂

**Comment by libashanxi** [comment]
其实能理解大佬这么设置的原因。如果配置和nt一样应用内配置，这种太简单了反而就没有门槛了，所以我猜哈，不保证准确，哈哈哈哈。
大概全部都用环境变量的方法设置，大佬的言外之意就是让大家折腾，如果这点东西搞不明白，可能说明mp不适合现阶段的你。

**Comment by yalidabuda** [comment]
> 其实能理解大佬这么设置的原因。如果配置和nt一样应用内配置，这种太简单了反而就没有门槛了，所以我猜哈，不保证准确，哈哈哈哈。 大概全部都用环境变量的方法设置，大佬的言外之意就是让大家折腾，如果这点东西搞不明白，可能说明mp不适合现阶段的你。

所以这不是过来问一嘴大佬咋想的😂，环境变量倒不是搞不明白，就是感觉麻烦，没有图形界面来的省事。

**Comment by LeanFly** [comment]
就是为了劝退，傻瓜式容易泛滥
