### ISSUE TITLE
[错误报告]: 媒体服务器使用emby会出现报错

### ISSUE THREAD

**Issue by jiangxiaobo1994** [jxxghp/MoviePilot#592]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.0

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/105762008/2b7acf65-38ab-4932-b792-9cbad441665c)
媒体服务器使用emby会出现报错

### 发生问题时系统日志和配置文件

```bash
00:08:33,506	
__init__.py
运行模块 media_exists 出错：EmbyModule - 'NoneType' object has no attribute 'get'
```

**Comment by jxxghp** [comment]
emby没连上吧

**Comment by jiangxiaobo1994** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/105762008/a12129e4-1664-41d6-8ede-cf47c9b61abd)
此处已有媒体库信息

**Comment by jiangxiaobo1994** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/105762008/b9c7b4a0-18e7-47f7-af9d-38f42912b808)

**Comment by jiangxiaobo1994** [comment]
请问如何自查呢

**Comment by jiangxiaobo1994** [comment]
Traceback (most recent call last):
  File "/app/app/chain/__init__.py", line 90, in run_module
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/emby/__init__.py", line 79, in media_exists
    tvs = self.emby.get_tv_episodes(title=mediainfo.title,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/emby/emby.py", line 341, in get_tv_episodes
    item_tmdbid = (self.get_iteminfo(item_id).get("ProviderIds") or {}).get("Tmdb")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:   __init__.py - 运行模块 media_exists 出错：EmbyModule - 'NoneType' object has no attribute 'get'
None
