### ISSUE TITLE
[错误报告]: 站点有资源但是搜索匹配不到

### ISSUE THREAD

**Issue by MrSaiDing** [jxxghp/MoviePilot#597]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.2.0

### 问题类型

主程序运行问题

### 问题描述

搜索匹配好像有一些问题，有些资源明明有，但是搜索不到
比如 狐墓迷影 和 画不投机 站点有这些资源，但是最后匹配还是失败

下面是站点资源和日志截图

https://ptpimg.me/8p5sio.png
https://ptpimg.me/l35sx3.jpg
https://ptpimg.me/j88017.png
https://ptpimg.me/86lcoa.png

**Comment by jxxghp** [comment]
匹配是按themoviedb的名称和别名、译名数据来的，themoviedb里有维护种子里这些别名吗？

**Comment by MrSaiDing** [comment]
https://www.themoviedb.org/movie/1042508   画不投机标题就有
https://www.themoviedb.org/movie/1048887   狐墓迷影只有英文标题，但是在Original Title这边有中文的 狐墓迷影

**Comment by jxxghp** [comment]
@MrSaiDing 你的种子并不是中文哪而是拼音吧？

**Comment by MrSaiDing** [comment]
PT的主标题都是英文的，副标题有中文

**Comment by jxxghp** [comment]
@MrSaiDing 副标题是描述信息，是没办法提取出准确的名字的。要维护TMDB里的别名数据，加上种子的命名。

**Comment by MrSaiDing** [comment]
是不是可以理解为 MP只是比对主标题和 TMDB的标题
很多用拼音命名的主标题基本都匹配不了

有什么办法匹配副标题吗？

**Comment by MrSaiDing** [comment]
所有PT站的命名规则都是 
主标题英文
副标题中文
这样导致的结果的是 会有好多资源匹配不了 （特别是用拼音翻译成主标题的资源）

**Comment by jxxghp** [comment]
@MrSaiDing 副标题会识别季集数，但这个描述文本是没有固定格式的，没法精确提取出中文名。要正常维护TMDB的别名数据才行。NT也是这样。

**Comment by MrSaiDing** [comment]
原来如此，那就没办法了
谢谢！

**Comment by mosu14121** [comment]
出现同样情况。不过我发现如果是NT的话，点击搜索框右边的高级搜索再去搜资源的话就不会出现这个问题，不知道MP是不是也会出一个类似的高级搜索功能，或者将这个高级搜索功能作为默认搜索选项之一？
