### ISSUE TITLE
[错误报告]: rss订阅剧集，无法正常订阅下载

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/MoviePilot#603]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.1

### 问题类型

主程序运行问题

### 问题描述

rss订阅剧集无法正常下载，电影是没有问题的，本以为是我本地程序的问题，重新配置了一套容器，还是有问题

### 发生问题时系统日志和配置文件

```bash
INFO】2023-09-16 18:13:23,530 - __init__.py - 发送消息：channel=MessageChannel.Telegram，title=开始刷新订阅 ..., text=None，userid=xxxx
【INFO】2023-09-16 18:13:24,364 - torrents.py - 开始获取站点 ptchdbits.co RSS ...
【INFO】2023-09-16 18:13:25,244 - torrents.py - 彩虹岛 有 10 个新种子
【INFO】2023-09-16 18:13:25,278 - torrents.py - 处理资源：Lian Qi Shi Wan Nian S01 1080p WEB-DL HEVC AAC-CHDWEB[[2023年2月国漫] 炼气十万年 第64集][157.69 MB] ...
【INFO】2023-09-16 18:13:25,282 - __init__.py - Lian Qi Shi Wan Nian 使用识别缓存：炼气十万年
【INFO】2023-09-16 18:13:25,282 - tmdbapi.py - 正在查询TMDB电视剧：220850 ...
【INFO】2023-09-16 18:13:25,283 - tmdbapi.py - 220850 查询结果：炼气十万年
【INFO】2023-09-16 18:13:25,284 - __init__.py - Lian Qi Shi Wan Nian 识别结果：电视剧 炼气十万年 (2023) 220850
【INFO】2023-09-16 18:13:25,813 - subscribe.py - 开始匹配订阅，标题：炼气十万年 ...
【INFO】2023-09-16 18:13:25,814 - __init__.py - 炼气十万年 使用识别缓存：炼气十万年
【INFO】2023-09-16 18:13:25,815 - tmdbapi.py - 正在查询TMDB电视剧：220850 ...
【INFO】2023-09-16 18:13:25,816 - tmdbapi.py - 220850 查询结果：炼气十万年
【INFO】2023-09-16 18:13:25,817 - __init__.py - 炼气十万年 识别结果：电视剧 炼气十万年 (2023) 220850
【INFO】2023-09-16 18:13:25,856 - __init__.py - 炼气十万年 (2023) 媒体库中已存在：{1: [63]}
【INFO】2023-09-16 18:13:25,857 - subscribe.py - 订阅 炼气十万年 (2023) S01 缺失集：[64, 65]
【INFO】2023-09-16 18:13:25,874 - subscribe.py - 炼气十万年 (2023) 匹配完成，共匹配到0个资源
【INFO】2023-09-16 18:13:25,874 - subscribe.py - 炼气十万年 (2023) 季 1 更新缺失集数为2 ...
【INFO】2023-09-16 18:13:25,878 - __init__.py - 发送消息：channel=MessageChannel.Telegram，title=订阅刷新完成！, text=None，userid=xxxx
【INFO】2023-09-16 18:13:26,428 - command.py - 用户 953994877 刷新订阅 执行完成
【INFO】2023-09-16 18:13:26,429 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f98d2713100>, <function WebHook.send at 0x7f98d275d760>]
【INFO】2023-09-16 18:13:26,429 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f98d2713100>, <function WebHook.send at 0x7f98d275d760>]
```

**Comment by xuanqb** [comment]
条目信息：Lian Qi Shi Wan Nian S01 1080p WEB-DL HEVC AAC-CHDWEB[[2023年2月国漫] 炼气十万年 第64集][157.69 MB]
<img width="904" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/25526210/5a6db5bc-b1ca-4ad5-b57a-f1ae7d79a3e8">

**Comment by paysenyu** [comment]
同样问题

改成rss后，部分剧几天都没有更新 

手动搜索后才行

**Comment by xuanqb** [comment]
用github上最新版本的代码在本地跑了下竟然能成功订阅，commit_id：c86a21d1
> INFO:     127.0.0.1:65414 - "OPTIONS /api/v1/subscribe/refresh HTTP/1.1" 200 OK
INFO:    torrents.py - 开始获取站点 hddolby.com RSS ...
INFO:    torrents.py - 高清杜比 有 10 个新种子
INFO:    torrents.py - 处理资源：Rakshasa Street 2023 S03E09 1080p WEB-DL AVC AAC-QHstudIo[镇魂街 第三季 第09集【导演： 尹嘉庚 | 主演：郭盛 |  黎筱濛 | 图特哈蒙 | 锦鲤】QHstudIo小组作品] ...
INFO:    __init__.py - Rakshasa Street 使用识别缓存：镇魂街
INFO:    tmdbapi.py - 正在查询TMDB电视剧：70923 ...
INFO:    tmdbapi.py - 70923 查询结果：镇魂街
INFO:    __init__.py - Rakshasa Street 识别结果：电视剧 镇魂街 (2016) 70923
INFO:    subscribe.py - 开始匹配订阅，标题：镇魂街 ...
INFO:    __init__.py - 镇魂街 使用识别缓存：镇魂街
INFO:    tmdbapi.py - 正在查询TMDB电视剧：70923 ...
INFO:    tmdbapi.py - 70923 查询结果：镇魂街
INFO:    __init__.py - 镇魂街 识别结果：电视剧 镇魂街 (2016) 70923
INFO:    __init__.py - 镇魂街 (2016) 媒体库中已存在：{3: [8]}
INFO:    subscribe.py - 订阅 镇魂街 (2016) S03 缺失集：[9, 10, 11, 12, 13, 14, 15, 16]
INFO:    subscribe.py - 镇魂街 (2016) 匹配成功：Rakshasa Street 2023 S03E09 1080p WEB-DL AVC AAC-QHstudIo[镇魂街 第三季 第09集【导演： 尹嘉庚 | 主演：郭盛 |  黎筱濛 | 图特哈蒙 | 锦鲤】QHstudIo小组作品]
INFO:    subscribe.py - 镇魂街 (2016) 匹配完成，共匹配到1个资源
INFO:    torrent.py - 解析种子：[DBY].[镇魂街 第三季].Rakshasa.Street.2023.S03.1080p.WEB-DL.AVC.AAC-QHstudIo.torrent => 目录：[镇魂街 第三季].Rakshasa.Street.2023.S03.1080p.WEB-DL.AVC.AAC-QHstudIo，文件清单：['[镇魂街 第三季].Rakshasa.Street.2023.S03E09.1080p.WEB-DL.AVC.AAC-QHstudIo.mp4']
INFO:    __init__.py - 发送消息：channel=None，title=镇魂街 (2016) S03 E09 开始下载, text=站点：高清杜比
质量： WEB-DL 1080p
大小：424.85M
种子：Rakshasa Street 2023 S03E09 1080p WEB-DL AVC AAC-QHstudIo[镇魂街 第三季 第09集【导演： 尹嘉庚 | 主演：郭盛 |  黎筱濛 | 图特哈蒙 | 锦鲤】QHstudIo小组作品]
发布时间：2023-09-16 20:55:28，userid=None
INFO:    command.py - 处理事件：notice.message - [<function MessageForward.send at 0x1162191c0>, <function WebHook.send at 0x116264040>]
INFO:    command.py - 处理事件：download.added - [<function WebHook.send at 0x116264040>]
INFO:    subscribe.py - 镇魂街 (2016) 季 3 更新缺失集数为7 ...
INFO:     127.0.0.1:65416 - "GET /api/v1/subscribe/refresh HTTP/1.1" 200 OK

**Comment by xuanqb** [comment]
docker 环境变量 MOVIEPILOT_AUTO_UPDATE_DEV设置为true，更新了下最新的代码，测试了下，确认问题已经修复
