### ISSUE TITLE
[错误报告]: Cloudflare IP优选 界面丢失

### ISSUE THREAD

**Issue by xwxw098** [jxxghp/MoviePilot#606]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.1

### 问题类型

插件问题

### 问题描述

<img width="1393" alt="QQ20230917-153226@2x" src="https://github.com/jxxghp/MoviePilot/assets/113512030/40977f35-8f6b-425d-8655-762b837d555a">

### 发生问题时系统日志和配置文件

```bash
Cloudflare IP优选 界面丢失
```

**Comment by xwxw098** [comment]
重新安装也无丢失，重新启动也丢失

**Comment by jxxghp** [comment]
不给日志，怎么知道你是什么问题呢
