### ISSUE TITLE
认证站点时是不是没走PROXY_HOST？

### ISSUE THREAD

**Issue by SmallMX** [jxxghp/MoviePilot#610]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.1

### 问题类型

主程序运行问题

### 问题描述

配置了PROXY_HOST，连通性测试没问题
 [31mERROR: [0m singleton.py - 无法连接站点
 看了之前的提问，是因为有人代理配置错误造成无无法认证，所以认证时改为不走代理了吗？

### 发生问题时系统日志和配置文件

```bash
[31mERROR: [0m singleton.py - 无法连接站点
```

**Comment by jxxghp** [comment]
站点认证从来就没有走过代理
