### ISSUE TITLE
[错误报告]: 升级1.2.2后自动签到插件加载失败

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#613]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.2

### 问题类型

插件问题

### 问题描述

升级后自动签到插件加载失败

![cf910186d4b218826e3b613aefe5fec](https://github.com/jxxghp/MoviePilot/assets/23021469/a9b5dd54-ed15-4c7e-8e95-2ec8fea7ecbf)

### 发生问题时系统日志和配置文件

```bash
INFO	18:04:54,199	
slack.py
	Slack消息接收服务启动
INFO	18:04:54,199	
module.py
	Moudle Loaded：SlackModule
INFO	18:04:54,199	
module.py
	Moudle Loaded：SubtitleModule
INFO	18:04:54,207	
module.py
	Moudle Loaded：TheMovieDbModule
INFO	18:04:54,208	
module.py
	Moudle Loaded：TheTvDbModule
INFO	18:04:54,238	
client.py
	Starting to receive messages from a new connection (session id: 5456d1e0-acb5-4b34-829f-0f4fd52c4ed9)
ERROR	18:04:54,342	
plugin.py
	加载插件 AutoSignIn 出错：argument of type 'NoneType' is not iterable - Traceback (most recent call last):
INFO	18:04:54,351	
plugin.py
	Plugin Loaded：SiteStatistic
INFO	18:04:54,352	
plugin.py
	Plugin Loaded：DoubanSync
```

**Comment by jxxghp** [comment]
@mjsoftking thsrite

**Comment by mjsoftking** [comment]
@thsrite 自动签到插件故障

**Comment by mjsoftking** [comment]
插件配置如下

plugin.AutoSignIn	

{"enabled": true, "notify": true, "cron": "0 4,12,18,22 * * *", "onlyonce": false, "queue_cnt": 5, "sign_sites": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
