### ISSUE TITLE
[Feature Request]: 希望可以添加手动生成 token 来调用 HTTP API

### ISSUE THREAD

**Issue by FaintGhost** [jxxghp/MoviePilot#614]
### 当前程序版本

1.2.2

### 功能改进

想把各种信息显示接入 Home Assistant 面板显示，看了一下用的 Authorization Bearer token 但是每次登陆之后 token 就变了，是否可以让用户自己生成 token 来调用 HTTP API 呢？

**Comment by Sowevo** [comment]
自己调用`/api/v1/login/access-token`登录接口传用户名密码获取一个就行
