### ISSUE TITLE
全剧搜索和订阅拆分

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#618]
### 当前程序版本

1.2.2

### 功能改进

有点小众需求的场景

搜索希望可以有1080p or 720p 来寻找老的资源使用，用规则匹配自行配置

订阅都是新资源，希望默认全都2160p，就会用全局变量4k

在这个时候搜索和订阅的全局变量就会有一些冲突，希望能把这俩的全局变量拆分

**Comment by loveu5522** [comment]
同样需求， 十分建议订阅和搜索分2套过滤规则
