### ISSUE TITLE
[错误报告]: 在历史记录里重新整理，导致整个媒体库文件都删除了

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#625]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.3

### 问题类型

主程序运行问题

### 问题描述

选择重新整理后，整个二级目录下的所有媒体都被删除了，只保留了这个被整理的文件。

![截图_20230920154340](https://github.com/jxxghp/MoviePilot/assets/44762565/00c028da-3313-4f95-8f70-dec707eb5640)

原先外语电影里有100多个电影，重新整理里就只剩一个了。之前遇到过一次也是被删除了，我不知道怎么回事，没当回事，这是第二次了。之前一次是在历史记录里删除媒体文件。
![截图_20230920154216](https://github.com/jxxghp/MoviePilot/assets/44762565/e1e5d309-0f70-4186-94b4-a9894a86f90d)

**Comment by loveu5522** [comment]
这是刚刚整理的，结果我重新整理这个 2012  就全没了，只剩下2012了
![截图_20230920154659](https://github.com/jxxghp/MoviePilot/assets/44762565/2f2bf139-4483-4dc0-a76b-ca3ccda86c6e)

**Comment by loveu5522** [comment]
上传下日志
[moviepilot.log](https://github.com/jxxghp/MoviePilot/files/12670322/moviepilot.log)

**Comment by jxxghp** [comment]
@loveu5522 thsrite 大佬看看，跟那个unraid优化的pr有关么，或者是之前的bug
