### ISSUE TITLE
[错误报告]: 多个硬盘目录下电影、电视剧的目录无法识别

### ISSUE THREAD

**Issue by naoki66** [jxxghp/MoviePilot#627]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.2.2

### 问题类型

主程序运行问题

### 问题描述

程序无法处理多目录，之前nastool可以。
比如我群辉目录配置如下
 /volume1/18T01/PTmove
 /volume2/18T02/PTtv1
 /volume3/18T03/PTtv2
映射到MoviePilot容器内
/18T01/PTmove
/18T02/PTtv1
/18T03/PTtv2
设置媒体库的环境变量
LIBRARY_PATH=/18T01/links/move,/18T02/links/tv01,/18T03/links/tv02
设置下载目录
DOWNLOAD_MOVIE_PATH=/18T01/PTmove
DOWNLOAD_TV_PATH=/18T02/PTtv1  （此时程序已经无法支持另外一个目录）
设置默认下载目录
DOWNLOAD_PATH=/18T01/PTmove   （此时程序也无法支持多目录，但若不设置这个变量，文件管理无法打开默认文件目录）
-------------------------------
问题：程序无法识别电影、电视剧的目录。
比如把 /18T03/TV03/下的电视剧硬链接到  /18T01/links/move/电视剧。导致会链接到出现夸盘硬链接失败。

### 发生问题时系统日志和配置文件

```bash
<tr><td>2023/09/20&nbsp;18:55:08</td><td>stdout</td><td>[Errno&nbsp;18]&nbsp;Invalid&nbsp;cross-device&nbsp;link:&nbsp;'/18T03/TV03/Ahsoka.S01E06.Part.Six.1080p.DSNP.WEB-DL.DDP5.1.H.264-NTb.mkv'&nbsp;-&gt;&nbsp;'/18T01/links/move/电视剧/阿索卡&nbsp;(2023)/Season&nbsp;1/阿索卡&nbsp;-&nbsp;S01E06&nbsp;-&nbsp;第&nbsp;6&nbsp;集.mkv'
</td></tr>
<tr><td>2023/09/20&nbsp;18:55:08</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;__init__.py&nbsp;-&nbsp;正在转移文件：/18T03/TV03/Ahsoka.S01E06.Part.Six.1080p.DSNP.WEB-DL.DDP5.1.H.264-NTb.mkv&nbsp;到&nbsp;/18T01/links/move/电视剧/阿索卡&nbsp;(2023)/Season&nbsp;1/阿索卡&nbsp;-&nbsp;S01E06&nbsp;-&nbsp;第&nbsp;6&nbsp;集.mkv
</td></tr>
<tr><td>2023/09/20&nbsp;18:55:08</td><td>stdout</td><td>[32mINFO:[0m&nbsp;&nbsp;&nbsp;&nbsp;transfer.py&nbsp;-&nbsp;Ahsoka.S01E06.Part.Six.1080p.DSNP.WEB-DL.DDP5.1.H.264-NTb.mkv&nbsp;识别为：电视剧&nbsp;阿索卡&nbsp;(2023)
</td></tr>
```

**Comment by anooki-c** [comment]
我也有这样的问题，好像下载盘只能配置一个，我的电影、电视剧、动漫的下载盘是三个不同的盘，就只能三选一配一个

**Comment by jxxghp** [comment]
不计划支持同一类型多个盘下载。

**Comment by anooki-c** [comment]
> 不计划支持同一类型多个盘下载。

指的电影一个下载盘，电视剧和动漫都属于tv，只能一个下载盘吗

**Comment by naoki66** [comment]
> 不计划支持同一类型多个盘下载。

电视剧太大了，我18T的都很快塞满了。
即便除此，我暂时也没搞懂电影、电视剧分别下载到一个盘的设置。
比如我群辉目录配置如下
/volume1/18T01/PTmove
/volume2/18T02/PTtv1
设置媒体库的环境变量
LIBRARY_PATH=/18T01/links/move,/18T02/links/tv01
设置下载目录
DOWNLOAD_MOVIE_PATH=/18T01/PTmove
DOWNLOAD_TV_PATH=/18T02/PTtv1 
但是他硬链接的时候，还是把/volume2/18T02/PTtv1下的电视剧往LIBRARY_PATH的第一个变量/18T01/links/move下转移。这就导致bug了。

**Comment by Uil-Nella** [comment]
+1，同样遇到这个问题
