### ISSUE TITLE
[Feature Request]: 能否支持电影、电视剧刮削时同时对演员信息刮削

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#636]
### 当前程序版本

1.2.3

### 功能改进

目前发现刮削视频信息仅刮削视频的元数据、图片等信息，对视频关联的演员信息没有做刮削处理。
能否在完成视频元数据刮削后自动开始刮削演员元数据和图片信息

### 参考资料

我写了一个演员刮削的Python脚本，可供参考：[tmdb-person](https://github.com/carolcoral/tmdb-person)
脚本支持多种模式和自定义刮削来源和刮削演员信息保存路径
因为我当前使用的是Emby Server，因此只能确定Emby中保存演员元数据路径为: `~/metadata/metadata/people` 下

<img width="1111" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8952687/fe10237c-12a2-4309-9b9a-9e936917dcb3">

**Comment by cng10001** [comment]
2.1.8版本里面多了个演职人员中文名称刮削的功能
