### ISSUE TITLE
[错误报告]:自定义hosts插件IP更新成功，群晖系统/etc/hosts中未同步记录

### ISSUE THREAD

**Issue by qhly2010** [jxxghp/MoviePilot#644]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.2.3-1

### 问题类型

插件问题

### 问题描述

自定义hosts插件搭配Cloudflare IP优选插件，MP中更新IP成功，但是群晖系统中/etc/hosts未做任何更改，地址都没有添加上，但是docker版的NT中hosts插件就没问题

### 发生问题时系统日志和配置文件

INFO | 11:12:39,035 | __init__.py | Cloudflare CDN优选服务启动，立即运行一次
-- | -- | -- | --
INFO | 11:12:44,362 | __init__.py | CloudflareSpeedTest无新版本，存在可执行版本，继续运行
INFO | 11:12:44,362 | __init__.py | 正在进行CLoudflare CDN优选，请耐心等待
INFO | 11:12:44,363 | __init__.py | 正在执行优选命令 cd /config/plugins/CloudflareSpeedTest && chmod a+x CloudflareST && ./CloudflareST -o /config/plugins/CloudflareSpeedTest/result_hosts.txt -f /config/plugins/CloudflareSpeedTest/ip.txt
INFO | 11:14:06,368 | __init__.py |  
INFO | 11:14:07,173 | __init__.py | Cloudflare CDN优选ip [104.16.36.194] 已替换自定义Hosts插件
INFO | 11:14:07,173 | __init__.py | 通知CustomHosts插件重载 ...
INFO | 11:14:07,190 | command.py | 处理事件：plugin.reload - [<function CustomHosts.reload at 0x7f03e439cfe0>, <function WebHook.send at 0x7f03e445ade0>]
INFO | 11:14:07,190 | __init__.py | 发送消息：channel=None，title=【Cloudflare优选任务完成】, text=原ip：1.1.1.1
INFO | 11:14:07,191 | __init__.py | 更新系统hosts文件成功

**Comment by thsrite** [comment]
权限问题吧

**Comment by qhly2010** [comment]
> 权限问题吧
docker安装的MP，权限也没问题吧，日志都提示更新hosts成功了，刚又发现有多个地址时，hosts插件中的IP居然是同一个，如下：
104.16.36.194 api.themoviedb.org
104.16.36.194 hub.docker.com
104.16.36.194 github.com

**Comment by thsrite** [comment]
额，那没问题啊   mp更新的是docker的hosts文件，
你docker运行的mp，跟群辉系统的/etc/hosts有啥关系？你docker映射了/etc/hosts了？
用了cf优选插件，你这几个hosts设置的同一个ip？建议先了解下cf

**Comment by qhly2010** [comment]
感谢大佬，我再了解一下，应该是我的问题了
