### ISSUE TITLE
[错误报告]: 文件整理 - 搜索窗口 - 光标问题

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#645]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.3-1

### 问题类型

主程序运行问题

### 问题描述

<img width="891" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51367628/dda2755d-adb4-4c98-840c-ba0db7300b57">

<img width="907" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51367628/0d228341-cd7b-4299-9edb-f94a6e2a87d6">

如图，文件管理中 点击放大镜进行搜索时， 默认光标依旧在 “TMDBID” 处，此时输入内容则会输入到TMDBID

而非最新弹出的搜索栏中

**Comment by paysenyu** [comment]
<img width="880" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51367628/f936171e-6e64-42d4-b55d-1f6552c88d26">

重新整理时候也有此问题

**Comment by jxxghp** [comment]
fixed
