### ISSUE TITLE
running man订阅后变成动画片

### ISSUE THREAD

**Issue by elvischeung** [jxxghp/MoviePilot#648]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.4

### 问题类型

主程序运行问题

### 问题描述

尊敬的开发者你好，我从很之前的版本到最新1.2.4都试过了，搜索running man弹出来有正确的综艺信息，点击订阅后会自动变成一部同名的动画片..问过群内几次没有人答复..请赐教

### 发生问题时系统日志和配置文件

```bash
INFO	16:57:44,376	
subscribe.py
开始添加订阅，标题：Running Man ...
INFO	16:57:44,920	
__init__.py
Running Man 使用识别缓存：런닝맨
INFO	16:57:45,052	
tmdbapi.py
正在查询TMDB电视剧：138787 ...
INFO	16:57:45,054	
tmdbapi.py
138787 查询结果：런닝맨
INFO	16:57:45,055	
__init__.py
Running Man 识别结果：电视剧 런닝맨 (2017) 138787
INFO	16:57:45,057	
tmdbapi.py
正在获取电视剧图片：138787...
INFO	16:57:48,400	
subscribe.py
런닝맨 (2017) S01 添加订阅成功
INFO	16:57:48,403	
__init__.py
发送消息：channel=None，title=런닝맨 (2017) S01 已添加订阅, text=评分：0.0，来自用户：admin，userid=None
INFO	16:57:48,404	
command.py
处理事件：notice.message - [<function MessageForward.send at 0x7f28e2fad8a0>, <function WebHook.send at 0x7f28e2f33f60>]
```

**Comment by jxxghp** [comment]
清缓存 + 自定义识别词
