### ISSUE TITLE
[错误报告]: 配置Synologychat后无法使用，发送消息后台没反应

### ISSUE THREAD

**Issue by dick86114** [jxxghp/MoviePilot#649]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.4

### 问题类型

主程序运行问题

### 问题描述

按照教程配置Synologychat后仍然无法使用推送，发送消息后台只是提示post成功，但没有其他反应，chat也收不到消息，同样的配置方式在nastools里是能成收发消息的，而且我已经注意了相对路径/api/v1/message/

### 发生问题时系统日志和配置文件

```bash
2023/9/22 18:20:02  INFO:     192.168.31.1:0 - "POST /api/v1/message/ HTTP/1.1" 200 OK
```

**Comment by jeavenchu** [comment]
我的synologychat的问题是，主动发的通知正常而插件被动发的通知都是发不出的 报错407
![image](https://github.com/jxxghp/MoviePilot/assets/65897645/867d1ff1-4143-41c6-b663-2725bba7a997)

**Comment by dick86114** [comment]
> 我的synologychat的问题是，主动发的通知正常而插件被动发的通知都是发不出的 报错407 ![image](https://user-images.githubusercontent.com/65897645/270099883-867d1ff1-4143-41c6-b663-2725bba7a997.png)

我是完全收发都没反应，也不知道哪里出了问题

**Comment by jeavenchu** [comment]
> > 我的synologychat的问题是，主动发的通知正常而插件被动发的通知都是发不出的 报错407 ![image](https://user-images.githubusercontent.com/65897645/270099883-867d1ff1-4143-41c6-b663-2725bba7a997.png)
> 
> 我是完全收发都没反应，也不知道哪里出了问题

我现在用机器人里面的令牌，然后用最外面的整合中的传入webhook，然后开个频道，机器人加收藏标志，然后再把机器人整合在一起，就可以曲线救国了

**Comment by jxxghp** [comment]
> > 我的synologychat的问题是，主动发的通知正常而插件被动发的通知都是发不出的 报错407 ![image](https://user-images.githubusercontent.com/65897645/270099883-867d1ff1-4143-41c6-b663-2725bba7a997.png)
> 
> 我是完全收发都没反应，也不知道哪里出了问题

贴一下发送的消息内容，我怎么测都是正常收发的。

**Comment by dick86114** [comment]
不好意思了，发现问题原因了，是我message忘记加synologychat了，抱歉

**Comment by dick86114** [comment]
> > > 我的synologychat的问题是，主动发的通知正常而插件被动发的通知都是发不出的 报错407 ![image](https://user-images.githubusercontent.com/65897645/270099883-867d1ff1-4143-41c6-b663-2725bba7a997.png)
> > 
> > 
> > 我是完全收发都没反应，也不知道哪里出了问题
> 
> 贴一下发送的消息内容，我怎么测都是正常收发的。

已验证解决，是我的疏忽，麻烦大佬关闭该问题，再次抱歉
