### ISSUE TITLE
[Feature Request]: 历史记录重新识别，是否添加重新识别媒体文件名，而不是仅有手动添加TMDB编号来识别。

### ISSUE THREAD

**Issue by loveu5522** [jxxghp/MoviePilot#659]
### 当前程序版本

1.2.4

### 功能改进

因为有时是因为文件名错误导致的识别错误，用词表替换更正名称后，在通过历史记录里识别，是否重新通过名称再次识别。

**Comment by dlovew** [comment]
另外最好可以增加批量重新识别
