### ISSUE TITLE
[Feature Request]: 建议J大换用一个端口

### ISSUE THREAD

**Issue by BackspaceM** [jxxghp/MoviePilot#661]
### 当前程序版本

MoviePilot:latest

### 功能改进

由于3000端口是nginx的API端口，NT、MP全需将宿主端口进行映射，但不知其他人是否与我一样，NT、MP只要宿主与容器端口不一致就进不去webui，NT还能在config文件夹中修改config.yaml进行容器内的端口修改，但MP暂未法相有相应修改配置文件

**Comment by dlovew** [comment]
仔细看readme可以改

**Comment by mjsoftking** [comment]
仔细看readme文档
