### ISSUE TITLE
[错误报告]: 手动文件整理时指定目的路径不生效

### ISSUE THREAD

**Issue by abczi** [jxxghp/MoviePilot#662]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.4

### 问题类型

主程序运行问题

### 问题描述

在文件整理时，手动指定了目的路径，剧集类的仍然会被整理到动漫或电视剧目录下
![image](https://github.com/jxxghp/MoviePilot/assets/58116139/c22c5cf0-52bf-44c3-b992-dece2a41d83a)
![image](https://github.com/jxxghp/MoviePilot/assets/58116139/0baeac18-b7a1-47bc-b673-af0f0692f3a3)

我的媒体库目录为：
media
--Anima
--Cartoon
--Movie
--Tv
downloads目录结构与媒体库相同，现在整理Cartoon目录时，总是进入到Anima或Tv目录下
ps: 我的媒体库目录变量为动漫：Anima 电视剧：Tv ，并且关闭了下载监控与目录同步插件

**Comment by ershouqingge** [comment]
+1 目录同步和手动整理，目的地直接去到环境变量设置的媒体库了
