### ISSUE TITLE
[错误报告]: 更新之后不能重启了

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#668]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.2.5

### 问题类型

主程序运行问题

### 问题描述

![iShot_2023-09-26_09 23 51](https://github.com/jxxghp/MoviePilot/assets/34505611/d23ce3dc-839f-478e-b8b0-1d7ad1edd89a)
之前是可以各的，更新最新版后就不行了

**Comment by jxxghp** [comment]
@DDSDerek

**Comment by DDSDerek** [comment]
@jxxghp 在TG交流群里面吗？可以远程看看吗？

**Comment by yellowstrong** [comment]
> @yellowstrong 在TG交流群里面吗？可以远程看看吗？

老大回滚代码以后，可以重启了

**Comment by DDSDerek** [comment]
@yellowstrong 这个我知道，但是我修改是因为这种方法是有问题的，别的人不行，所以我想具体看看您这边是什么问题
找出一个完美的解决方法
