### ISSUE TITLE
[Feature Request]: 建议订阅洗版的时候在订阅图片上显示洗版的字样。

### ISSUE THREAD

**Issue by MichaelYXQ** [jxxghp/MoviePilot#670]
### 当前程序版本

1.2.6

### 功能改进

如题所示，建议订阅洗版的时候在订阅图片上显示洗版的字样。
目前即使选择了洗版，在订阅图片上无法直接识别，只能打开订阅界面检查。
![image](https://github.com/jxxghp/MoviePilot/assets/92349267/b70fb1a1-8d24-4fb9-a135-44173d1b115f)

**Comment by jxxghp** [comment]
@MichaelYXQ 没看见那个虚框吗？

**Comment by MichaelYXQ** [comment]
呃，好吧，确实没有注意到，谢谢提醒。

**Comment by jxxghp** [comment]
@MichaelYXQ 黑色主题下明显些

**Comment by MichaelYXQ** [comment]
收到，感谢提醒。

**Comment by MichaelYXQ** [comment]
@jxxghp 确实如此，已经切换为黑色主题。
