### ISSUE TITLE
[错误报告]: 1.2.5更新后zhuque判断登录依然是cookie失效

### ISSUE THREAD

**Issue by UFO404** [jxxghp/MoviePilot#671]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.6

### 问题类型

主程序运行问题

### 问题描述

看到1.2.5的更新日志里改了zhuque的登录判定方式,更新后实测还是提示cookie失效,并且更新后开启仿真也时提示cookie失效,实际是可以浏览种子列表的

**Comment by hh0610** [comment]
我这边显示正常。你是不是哪里设置错了

**Comment by UFO404** [comment]
> 我这边显示正常。你是不是哪里设置错了
我先是把原来手动加的给删了香同步 日志显示连通失败不同步,然后我又手动加了,然后就都不成功了

**Comment by hh0610** [comment]
> > 我这边显示正常。你是不是哪里设置错了
> > 我先是把原来手动加的给删了香同步 日志显示连通失败不同步,然后我又手动加了,然后就都不成功了

我是没有删，直接更新版本。
