### ISSUE TITLE
icc2022认证时一直提示无法连接站点

### ISSUE THREAD

**Issue by qa19971109** [jxxghp/MoviePilot#672]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.6

### 问题类型

Docker或运行环境问题

### 问题描述

配置了代理节点，使用icc2022认证时一直提示无法连接站点，尝试去除代理也是一致提示无法连接站点

### 发生问题时系统日志和配置文件

```bash
14:12:28,297	
singleton.py
无法连接站点
```

**Comment by jxxghp** [comment]
认证时不会使用内置代理，网络问题自行解决。
