### ISSUE TITLE
好大（高清视界）签到失败

### ISSUE THREAD

**Issue by HamBosco** [jxxghp/MoviePilot#678]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.6

### 问题类型

主程序运行问题

### 问题描述

总是签到失败，但是可以浏览站点资源。
一直提示检查连通性，但是检查了没问题啊。
也更新cookies了。
<img width="844" alt="Screen Shot 2023-09-27 at 3 31 51 PM" src="https://github.com/jxxghp/MoviePilot/assets/139821230/3e1942a3-2997-4aba-805f-24e577538da4">
<img width="844" alt="Screen Shot 2023-09-27 at 3 32 19 PM" src="https://github.com/jxxghp/MoviePilot/assets/139821230/dda7e73e-536e-432c-a1d6-e46b48342f0c">

**Comment by thsrite** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/54088512/12f06d03-557b-4d1a-a146-0515b0d4d299)
![image](https://github.com/jxxghp/MoviePilot/assets/54088512/950522b2-6e81-4a30-ae96-d1f82e8141c1)
没问题，找找网络原因或者更新下ck ua

**Comment by HamBosco** [comment]
> ![image](https://user-images.githubusercontent.com/54088512/273485678-12f06d03-557b-4d1a-a146-0515b0d4d299.png) ![image](https://user-images.githubusercontent.com/54088512/273485704-950522b2-6e81-4a30-ae96-d1f82e8141c1.png) 没问题，找找网络原因或者更新下ck ua

之前突然就好了
