### ISSUE TITLE
[Feature Request]: 站点刷流插件”下载超时时间“以及刷流插件下载的种子无法保留

### ISSUE THREAD

**Issue by MichaelYXQ** [jxxghp/MoviePilot#680]
### 当前程序版本

1.2.6

### 功能改进

两点建议：
站点刷流插件配置中的”下载超时时间“只能设置一个固定的时间，但是往往刷流的种子的免费时长不一致，建议当促销为免费时，增加一个下载超时选项“超出免费时间”，如果免费时间内还没有下载完成则删除种子（HR除外）。

刷流的种子在下载器中被手工删除或者入库保留后，刷流插件无法识别标签已经不存在，导致下载数和删除数和实际有差异。建议刷流插件使用标签或者保存目录定期识别，保持数据一致性。
![image](https://github.com/jxxghp/MoviePilot/assets/92349267/b2b94e31-1399-4b7e-bbeb-e664c5e46129)

**Comment by MichaelYXQ** [comment]
刚刚测试了将刷流好的一个电视剧在qb中转移到MP对应文件夹中，自动生成硬链接，但是刷流插件设置了平均上传小于100KB/s自动删除，结果最后刷流插件将种子删除了。
这样的话刷流回来的种子如果想保留，只能先转移，再清除刷流插件。

**Comment by mjsoftking** [comment]
HR除外，期望刷流最好不要下载HR资源

**Comment by zhangfan1231** [comment]
同题主需求：
1.刷流时，手动删除QB中的种子后 ，刷流插件的显示信息与QB做种的任务数量不一致，刷流插件还存有该种子信息且为正常（期望变为已删除，同时变更已删除种子数）。

2.题主提出的标签的做法我觉得应该可行，在同步刷流信息时，除了同步刷流的历史数据，也能同步当前QB做种的刷流任务状态。

3.清除历史记录后，希望同步当前QB做种的刷流任务信息，使其受控。
