### ISSUE TITLE
[错误报告]: 关于连接媒体服务器问题

### ISSUE THREAD

**Issue by zraxx** [jxxghp/MoviePilot#684]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.6

### 问题类型

主程序运行问题

### 问题描述

mp启动时，若jellyfin媒体服务器没启动，出现连接媒体服务器错误，等媒体服务器启动后，必须重启mp，才能连接媒体服务器。

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-09-28 09:25:03,055 - singleton.py - 用户认证成功！
【INFO】2023-09-28 09:25:08,108 - module.py - Moudle Loaded：DoubanModule
【INFO】2023-09-28 09:25:08,119 - module.py - Moudle Loaded：FanartModule
【INFO】2023-09-28 09:25:08,122 - module.py - Moudle Loaded：FileTransferModule
【INFO】2023-09-28 09:25:08,134 - module.py - Moudle Loaded：FilterModule
【INFO】2023-09-28 09:25:08,145 - module.py - Moudle Loaded：IndexerModule
【ERROR】2023-09-28 09:25:08,155 - jellyfin.py - Users 未获取到返回数据
【ERROR】2023-09-28 09:25:08,165 - jellyfin.py - System/Info 未获取到返回数据
【ERROR】2023-09-28 09:26:26,529 - __init__.py - 获取Jellyfin播放会话失败：replace() argument 2 must be str, not None
```

**Comment by jxxghp** [comment]
每隔10分钟会重连一次

**Comment by zraxx** [comment]
> 每隔10分钟会重连一次
手工 同步媒体服务器或定时同步媒体服务器 还是会出现以下错误，问题可复现。
INFO:    mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
ERROR:   jellyfin.py - Users/Views 未获取到返回数据
INFO:    mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：0
INFO:     192.168.1.228:0 - "GET /api/v1/system/runscheduler?jobid=mediaserver_sync HTTP/1.1" 200 OK
INFO:     192.168.1.228:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
INFO:     192.168.1.228:0 - "GET /api/v1/dashboard/schedule HTTP/1.1" 200 OK
ERROR:   __init__.py - 获取Jellyfin播放会话失败：replace() argument 2 must be str, not None
2023-09-28T08:04:41.529689783Z ERROR:   __init__.py - 获取Jellyfin播放会话失败：replace() argument 2 must be str, not None
2023-09-28T08:04:41.539475171Z INFO:    transfer.py - 开始执行下载器文件转移 ...
2023-09-28T08:04:41.539905898Z INFO:    mediaserver.py - 开始同步媒体库 jellyfin 的数据 ...
2023-09-28T08:04:41.549372441Z ERROR:   jellyfin.py - Users/Views 未获取到返回数据
2023-09-28T08:04:41.549781157Z INFO:    mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：0
2023-09-28T08:04:41.551027430Z INFO:    transfer.py - 没有获取到已完成的下载任务
