### ISSUE TITLE
连不上tr。希望有大佬能帮忙分析下日志。

### ISSUE THREAD

**Issue by Hiccup90** [jxxghp/MoviePilot#69]
变量设置应该是没问题的。检查了好几次。空格也看过了。变量名也是复制的。
<img width="370" alt="1" src="https://github.com/jxxghp/MoviePilot/assets/24733459/45ca229d-c8e6-4151-9dc8-0419625f04af">
<img width="1120" alt="2" src="https://github.com/jxxghp/MoviePilot/assets/24733459/5d94dd67-49ec-48d2-aeff-a415134bdc56">

**Comment by thsrite** [comment]
#58

**Comment by Hiccup90** [comment]
ho~大佬速度真快。
那等待修复即可？
感谢大佬。

**Comment by Hiccup90** [comment]
刚才看到docker有更新。就更新了，但是还是连不上。。
<img width="767" alt="3" src="https://github.com/jxxghp/MoviePilot/assets/24733459/02b990ee-c2fc-4a41-8fc6-bea564acf62f">
这是看到新的错误。
