### ISSUE TITLE
[错误报告]: tmdb 的 http 请求一直不断开

### ISSUE THREAD

**Issue by ccbikai** [jxxghp/MoviePilot#690]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.6

### 问题类型

主程序运行问题

### 问题描述

程序使用 clash 解决网络问题，但是控制台显示大量 tmdb 的请求未关闭。同时内存占用也很高，启动大概 300M

![image](https://github.com/jxxghp/MoviePilot/assets/2959393/2f6cbd37-ea94-48ba-a809-4831c3e85cd1)
![image](https://github.com/jxxghp/MoviePilot/assets/2959393/5c8be0e0-23ef-4608-b619-7397af1fcbaf)

**Comment by Sowevo** [comment]
我也观察到这个现象了

**Comment by jxxghp** [comment]
加了连接超时参数，可以更新到dev代码试试看是否正常了：
**MOVIEPILOT_AUTO_UPDATE_DEV**：重启时更新到未发布的开发版本代码，`true`/`false`，默认`false`

**Comment by ccbikai** [comment]
> 加了连接超时参数，可以更新到dev代码试试看是否正常了： **MOVIEPILOT_AUTO_UPDATE_DEV**：重启时更新到未发布的开发版本代码，`true`/`false`，默认`false`

看到1.2.7-1 里边包含了此变更，试了一下问题还是存在。 感觉不是 timeout 的问题，因为连接是正常返回的， 推测是 keep-alive 相关的问题

**Comment by guziwen** [comment]
测试仍然存在该问题

**Comment by ccbikai** [comment]
1.2.8 版本测试还存在此问题，同时发现豆瓣的域名 frodo.douban.com 也存在此问题。 

![image](https://github.com/jxxghp/MoviePilot/assets/2959393/6479e16c-e96b-4f91-8047-638adc120944)

![image](https://github.com/jxxghp/MoviePilot/assets/2959393/3bf3c90f-9045-4f6b-a702-5153539b1b59)

**Comment by ccbikai** [comment]
怀疑是 HTTP 响应头里边这两个字段导致的

![image](https://github.com/jxxghp/MoviePilot/assets/2959393/45facdc4-3ceb-4ab1-a293-3c3aec4e379c)

**Comment by jxxghp** [comment]
> 怀疑是 HTTP 响应头里边这两个字段导致的
> 
> 
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/2959393/45facdc4-3ceb-4ab1-a293-3c3aec4e379c)
> 
> 

Syntax
HTTP
Keep-Alive: parameters
Directives
parameters
A comma-separated list of parameters, each consisting of an identifier and a value separated by the equal sign ('='). The following identifiers are possible:

timeout: An integer that is the time in seconds that the host will allow an idle connection to remain open before it is closed. A connection is idle if no data is sent or received by a host. A host may keep an idle connection open for longer than timeout seconds, but the host should attempt to retain a connection for at least timeout seconds.

豆瓣30秒内的请求会复用连接应该是正常的。
tmdb的也改成session了，看看是否还会建很多连接。

**Comment by developer-wlj** [comment]
找到一个确认的问题，tmdb相关域名获取的ip是动态的，只要客户端和不同ip通信，就会创建新的tcp连接，除非在host中指定ip，可以尝试把api.tmdb.org指定一个ip写入到host文件中

**Comment by ccbikai** [comment]
最新的 DEV 还有有这个问题， 链接长时间不断开。 

![image](https://github.com/jxxghp/MoviePilot/assets/2959393/952d7eac-17f2-4135-90d3-d30716cdde21)

**Comment by developer-wlj** [comment]
> 最新的 DEV 还有有这个问题， 链接长时间不断开。 
> 
> ![image](https://github.com/jxxghp/MoviePilot/assets/2959393/952d7eac-17f2-4135-90d3-d30716cdde21)
> 
> 

你这个问题，就是上面我说的，看连接的ip是不是不同

**Comment by ii-jj** [comment]
<img width="1565" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/7134747/3336cd85-2ed0-49af-8683-072d7fe86549">

> 连接数 已经 99+ 了。  

目前观察到的 同一个 source IP ，对应 同一个 代理出口的  存在 多个连接。

**Comment by jxxghp** [comment]
> <img alt="image" width="1565" src="https://user-images.githubusercontent.com/7134747/273176886-3336cd85-2ed0-49af-8683-072d7fe86549.png">
> > 连接数 已经 99+ 了。
> 
> 目前观察到的 同一个 ~source~ 目标 IP ，对应 同一个 代理出口的 存在 多个连接。

是否更新到Dev代码？更新到DEV后，连接数应该不会一直涨了。

**Comment by ccbikai** [comment]
> > <img alt="image" width="1565" src="https://user-images.githubusercontent.com/7134747/273176886-3336cd85-2ed0-49af-8683-072d7fe86549.png">
> > > 连接数 已经 99+ 了。
> > 目前观察到的 同一个 ~source~ 目标 IP ，对应 同一个 代理出口的 存在 多个连接。
> 
> 是否更新到Dev代码？更新到DEV后，连接数应该不会一直涨了。

使用最新 DEV，豆瓣和 TMDB 链接数稳定在 6 个
