### ISSUE TITLE
[错误报告]: wechat.py 发送请求失败，错误码：404，错误原因：Not Found

### ISSUE THREAD

**Issue by qa19971109** [jxxghp/MoviePilot#691]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7

### 问题类型

主程序运行问题

### 问题描述

企业微信配置好环境变量后，可以在企业微信中正常使用，但mp一直有个报错

### 发生问题时系统日志和配置文件

```bash
wechat.py 发送请求失败，错误码：404，错误原因：Not Found
```

**Comment by jxxghp** [comment]
@qa19971109 看readme，你的代理有问题，自动添加不了菜单
