### ISSUE TITLE
PTT副标题有的显示有的不显示

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#696]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7

### 问题类型

主程序运行问题

### 问题描述

![1695907472107](https://github.com/jxxghp/MoviePilot/assets/142991330/5015ef66-7d58-47a8-9045-b96a219fdaf5)

**Comment by hh0610** [comment]
![1695913770156](https://github.com/jxxghp/MoviePilot/assets/142991330/6a69adc2-822b-4b02-9c7d-5db05f7ca1ce)
升级到最新版本还是一样不显示副标题

**Comment by hh0610** [comment]
> ![1695913770156](https://user-images.githubusercontent.com/142991330/271330748-6a69adc2-822b-4b02-9c7d-5db05f7ca1ce.jpg) 升级到最新版本还是一样不显示副标题

只要包含 免费  50%免费  2X上传&50%免费   2X免费  这些就不会显示副标题

**Comment by jxxghp** [comment]
@hh0610 没打包上，下个版本

**Comment by hh0610** [comment]
> @hh0610 没打包上，下个版本

升级到1.2.8还是一样的问题
