### ISSUE TITLE
[Feature Request]: 站点刷流插件展示信息能否安排优化

### ISSUE THREAD

**Issue by iceucn** [jxxghp/MoviePilot#697]
### 当前程序版本

1.2.7

### 功能改进

站点刷流插件能否增加一键删除 已删除 的内容；
目前存在大量的已删除记录，要是清空的话，目前还在做种的记录也不显示了，也不能按照规则自动删除；
还有记录上能否增加添加时间字段，在加个按照时间正序、倒序排序的功能

**Comment by jxxghp** [comment]
插件页面现在还不能支持动态交互，vue动态组件不知道怎么插入动态脚本，目前有技术困难。

**Comment by iceucn** [comment]
![微信截图_20230928233127](https://github.com/jxxghp/MoviePilot/assets/134840291/2516d529-6e46-49c0-a69f-eb1778acc2ec)
要不暂时加这里，勾选清除当前 已删除 记录
