### ISSUE TITLE
学校能搜索.在站点管理中测试无法通过也无法浏览种子列表   开仿真也不可以

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#702]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7-1

### 问题类型

主程序运行问题

### 问题描述

![1695923402032(1)](https://github.com/jxxghp/MoviePilot/assets/142991330/64b152b5-745f-4367-8f3c-f58b17d82bad)
![1695923382791](https://github.com/jxxghp/MoviePilot/assets/142991330/68f4f7c7-d6c9-45f6-a48f-76b23fad4783)
![1695923574231](https://github.com/jxxghp/MoviePilot/assets/142991330/139c1d0e-e87d-4eaa-bf25-63ec9355e838)

### 发生问题时系统日志和配置文件

```bash
INFO:    torrents.py - 开始获取站点 btschool.club 最新种子 ...
INFO:    spider.py - 开始请求：https://pt.btschool.club/torrents.php
WARNING: __init__.py - 学校 未搜索到数据，耗时 0 秒
ERROR:   browser.py - 获取网页源码失败: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://pt.btschool.club/", waiting until "load"
============================================================
```

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/09fbe1e5-ca40-4d30-8bf0-7cf879103453)
