### ISSUE TITLE
[错误报告]: 播放限速插件在停止播放后，恢复未限速状态滞后一分多钟

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#705]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7-1

### 问题类型

插件问题

### 问题描述

限速插件在开始播放的同时就直接开始限速设置了，但在停止播放的时候，恢复到未限速状态要1分钟：
<img width="341" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/10297471/79b9a8d7-ffe4-4a8e-82e5-7e474cedc42a">
<img width="336" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/10297471/03da7b2e-872d-435c-8f7e-fee6e6707649">

**Comment by SilenceEagle** [comment]
同样的问题+1，一只存在这个问题，不只是1.2.7-1这个版本独占。
