### ISSUE TITLE
[错误报告]: 演职员刮削插件

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#709]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7.1

### 问题类型

主程序运行问题

### 问题描述

已经是最新dev版本，但是刮削的人员信息位置不对
![screenshot20230930](https://github.com/jxxghp/MoviePilot/assets/59035223/76e05c5a-3cc8-4123-9d64-200c6508a7e5)

![screenshot20230930 (1)](https://github.com/jxxghp/MoviePilot/assets/59035223/97c7cdb2-e169-421a-b0a4-cde90dbf45fb)

**Comment by dlovew** [comment]
并且以往的人物信息是否可以重新刮削

**Comment by jxxghp** [comment]
更新Dev或者等下个版本

**Comment by dlovew** [comment]
> 更新Dev或者等下个版本

🆗
