### ISSUE TITLE
[错误报告]: 我堡种子大小识别错误

### ISSUE THREAD

**Issue by richamon** [jxxghp/MoviePilot#710]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7-1

### 问题类型

主程序运行问题

### 问题描述

我堡资源识别大小错误，从nastool开始就有这个问题，最近两天转到mp发现还是相同的问题
![image](https://github.com/jxxghp/MoviePilot/assets/20623652/228c1989-f149-4ef6-914a-1f62bcdfd83b)
![image](https://github.com/jxxghp/MoviePilot/assets/20623652/ecdf379a-de2f-447d-9a4a-e50c604802bc)

### 发生问题时系统日志和配置文件

```bash
INFO	04:00:48,511	torrents.py  开始获取站点 ourbits.club 最新种子 ...
INFO	04:00:48,514	spider.py    开始请求：https://ourbits.club/torrents.php
INFO	04:00:52,046	__init__.py  我堡 搜索完成，耗时 3 秒，返回数据：100
```

**Comment by richamon** [comment]
站点是通过cookie cloud导入的，发现这个问题后去站点设置页面发现rss订阅地址为空，手动填入rss地址后问题依旧

**Comment by richamon** [comment]
时间这一列也没有数据

**Comment by jxxghp** [comment]
从未有过这个问题：
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/11ef7b34-b6eb-4090-b36d-07356cd29a2b)

**Comment by richamon** [comment]
经过多天测验，当取消勾选 “网站的设置—网站设置—（最后一行）显示评论数但不悬浮提示最新评论内容”后，即出现上述bug，勾选此选项后正常
