### ISSUE TITLE
馒头种子发布时间错误

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#711]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7.1

### 问题类型

主程序运行问题

### 问题描述

馒头只要是免费的种子发布时间显示错误
![12](https://github.com/jxxghp/MoviePilot/assets/142991330/9eafd1cc-9c09-4ec2-a2a5-a4971e380e84)

**Comment by jxxghp** [comment]
真正使用的是下面那个时间，上面这个免费显示限时，不挺好的吗。
