### ISSUE TITLE
[错误报告]: 演职员刮削插件关闭后依然是中文

### ISSUE THREAD

**Issue by huojinming-1997** [jxxghp/MoviePilot#712]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7-1

### 问题类型

主程序运行问题

### 问题描述

演职员刮削插件关闭后甚至已经卸载，emby和mp各自都重启过了依然无法恢复搜刮英文头像（新下载的整理）

**Comment by jxxghp** [comment]
更新dev或者等下个版本
