### ISSUE TITLE
[错误报告]: 豆瓣榜单订阅插件不可用

### ISSUE THREAD

**Issue by JX0204** [jxxghp/MoviePilot#715]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7-1

### 问题类型

插件问题

### 问题描述

豆瓣榜单订阅无法实现订阅反馈未查询到数据，实际rsshub网站可以正常打开并且有数据
<img width="1679" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/115469315/cde35012-7ebe-4315-8f5e-5fa08beb206c">
<img width="1238" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/115469315/6d4af8c9-f956-4f92-953e-00245cfad62c">

### 发生问题时系统日志和配置文件

```bash
23:04:10,696	
__init__.py
豆瓣榜单订阅服务启动，周期：* * * * *
INFO	23:05:00,001	
__init__.py
开始刷新豆瓣榜单 ...
INFO	23:05:00,001	
__init__.py
共 3 个榜单RSS地址需要刷新
INFO	23:05:00,001	
__init__.py
获取RSS：https://rsshub.app/douban/movie/weekly/subject_real_time_hotest ...
ERROR	23:05:06,747	
__init__.py
未解析到已删除媒体信息
ERROR	23:05:20,032	
__init__.py
RSS地址：https://rsshub.app/douban/movie/weekly/subject_real_time_hotest ，未查询到数据
INFO	23:05:20,032	
__init__.py
获取RSS：https://rsshub.app/douban/movie/weekly/movie_hot_gaia ...
ERROR	23:05:40,063	
__init__.py
RSS地址：https://rsshub.app/douban/movie/weekly/movie_hot_gaia ，未查询到数据
INFO	23:05:40,063	
__init__.py
获取RSS：https://rsshub.app/douban/movie/weekly ...
INFO	23:05:52,402	
__init__.py
当前没有正在下载的任务！
WARNING	23:06:00,000	
base.py
Execution of job "豆瓣榜单订阅 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*'], next run at: 2023-09-30 23:06:00 CST)" skipped: maximum number of running instances reached (1)
ERROR	23:06:00,189	
__init__.py
RSS地址：https://rsshub.app/douban/movie/weekly ，未查询到数据
INFO	23:06:00,191	
__init__.py
所有榜单RSS刷新完成
```

**Comment by jxxghp** [comment]
正常使用，检查容器到rsshub的网络。
