### ISSUE TITLE
cookiecloud同步站点无法使用代理

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#719]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7-1

### 问题类型

主程序运行问题

### 问题描述

cookiecloud同步站点能否使用代理同步

### 发生问题时系统日志和配置文件

```bash
WARNING	21:37:42,756	cookiecloud.py    站点 幼儿园 连接失败，无法添加站点
```

**Comment by jxxghp** [comment]
手动添加，然后打开站点代理开关。
都没同步下来，没地方设置使用代理，大部分站点都是不用代理的。
