### ISSUE TITLE
搜索结果添加分辨率过滤选项

### ISSUE THREAD

**Issue by ThierryCheng** [jxxghp/MoviePilot#72]
分辨率选项（1080P，4K，8K等）在搜索结果过滤中还是非常常用的，建议后续可以添加
<img width="1776" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/8851199/1a39ca5d-b6eb-407a-8656-6824a4dd55e2">

**Comment by lddsb** [comment]
个人愚见觉得还是nt的那种列表更直观，相比这种卡片样式

**Comment by jxxghp** [comment]
fdf167b5d63e0353c00906671b38d6568fbd7d6e
