### ISSUE TITLE
[错误报告]: 刷流插件 保种体积判断错误

### ISSUE THREAD

**Issue by zhyi828** [jxxghp/MoviePilot#720]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.7-1

### 问题类型

插件问题

### 问题描述

保种体积作为刷流停止条件时，某些情况下会导致判断错误
判断逻辑在：https://github.com/jxxghp/MoviePilot/blob/35be18bb1a65946a1fa3ddbcc358cfd3de340ae9/app/plugins/brushflow/__init__.py#L1353
暂时没看到根本问题所在，辛苦大佬再帮忙看看

### 发生问题时系统日志和配置文件

```bash
WARNING10:42:50,845
init.py
当前做种体积 0.0B 已超过保种体积 1024，停止新增任务
```

**Comment by jxxghp** [comment]
最新代码已修复
