### ISSUE TITLE
[Feature Request]: 豆瓣榜单订阅,可以增加年份吗？

### ISSUE THREAD

**Issue by dwwl886** [jxxghp/MoviePilot#721]
### 当前程序版本

 v1.2.7-1

### 功能改进类型

主程序

### 功能改进

豆瓣榜单订阅,可以增加年份吗？

### 参考资料

豆瓣榜单订阅,可以增加年份吗？

**Comment by jxxghp** [comment]
rsshub的链接规则是可以带年份的，参考rsshub的wiki
