### ISSUE TITLE
HDZone域名更改

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#724]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7-1

### 问题类型

主程序运行问题

### 问题描述

HDZone的域名有更改
大佬有空的时候麻烦大佬更改下新域名hdfun.me

**Comment by Shurelol** [comment]
@hh0610 感觉可以考虑参考iyuu可以自己设置镜像域名？应该可以规避域名变化问题
