### ISSUE TITLE
[错误报告]: 冰淇淋无法获取种子

### ISSUE THREAD

**Issue by dlovew** [jxxghp/MoviePilot#727]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.7

### 问题类型

主程序运行问题

### 问题描述

已经是最新dev版本
站点管理和刷流，冰淇淋都无法获取种子信息
补充：站点是通的
![screenshot20231003](https://github.com/jxxghp/MoviePilot/assets/59035223/a916b13c-2d6b-4a31-8c99-3d32449f0fe4)

**Comment by Shurelol** [comment]
@dlovew
