### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by xiaohaigge** [jxxghp/MoviePilot#728]
### 当前程序版本

 v1.2.7-1

### 功能改进类型

主程序

### 功能改进

我建议在界面增加选择链接目录 而不是在环境变量，不然排查错误好几个小时还不一定排查出来！！！！ 

最可气的是电影硬链接没问题，电视剧找不到目录？？ what？？？
![image](https://github.com/jxxghp/MoviePilot/assets/129136883/1e1a16ea-4726-4dbc-8562-c0228d628e39)
把所有下载目录整合到一起 没必要分好多插件 设置非常麻烦！

**Comment by jxxghp** [comment]
没人逼你用
