### ISSUE TITLE
[错误报告]: Synologychat部分信息接收不到

### ISSUE THREAD

**Issue by wenhua2008** [jxxghp/MoviePilot#731]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.8

### 问题类型

其他问题

### 问题描述

站点统计和站内信息发送时出现以下错误
ERROR:   synologychat.py - SynologyChat返回错误：407-record is not valid | stdout

机器人CHATPGT对话和订阅下载和整理通知可以收到，请看一下是否有BUG

**Comment by jxxghp** [comment]
看下是否能提供出错时发送的消息内容

**Comment by dick86114** [comment]
我也遇到了407错误，比如插件自动备份运行后，发送通知，后台日志就显示407错误，但是在chat里进行交互是能正常接收到信息回复的

**Comment by dick86114** [comment]
> 看下是否能提供出错时发送的消息内容

我也遇到了407错误，比如插件自动备份运行后，发送通知，后台日志就显示407错误，但是在chat里进行交互是能正常接收到信息回复的

**Comment by fayswing** [comment]
我也遇到了共同的错误      比如签到插件之类的运行没办法接受通知
搜索交互下载是正常的
