### ISSUE TITLE
[错误报告]: 历史记录里的删除功能，有的文件实际没有删除

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#732]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.8 最新

### 问题类型

主程序运行问题

### 问题描述

点击删除历史记录、源文件和媒体库文件，日志显示已删除，但有的文件实际没有被自动删除
我尝试删除了几个历史记录
发现这样的多标点符号的标题可能会存在问题

> ![源文件](https://github.com/jxxghp/MoviePilot/assets/115156545/651b4355-25ef-4490-ad25-8bf3b41c7bd8)

### 发生问题时系统日志和配置文件
日志显示已删除
![jianghu](https://github.com/jxxghp/MoviePilot/assets/115156545/bba6dbfd-809b-42ec-b07c-6c2047aca5ab)

**Comment by yellowstrong** [comment]
你点开文件夹看看里面是不是只剩下了字幕，之前NT就有这个问题，只会删除种子包含的文件，额外下载的字幕不会删除

**Comment by cng10001** [comment]
> 你点开文件夹看看里面是不是只剩下了字幕，之前NT就有这个问题，只会删除种子包含的文件，额外下载的字幕不会删除

没有额外的文件，我不下载字幕的~你有带“[]”这种标题的资源吗 可以帮忙试试吗

**Comment by jimlee2002** [comment]
我也遇到了使用自定义命名规则后，无法正常触发文件删除的问题，这是我使用的自定义命名配置：
```
MOVIE_RENAME_FORMAT="{{original_title}}{% if year %} ({{year}}){% endif %}/{{original_title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if imdbid %} {imdb-{{imdbid}}}{% endif %}{% if videoFormat %} [{{videoFormat}}]{% endif %}{% if edition %}[{{edition}}]{% endif %}{% if audioCodec %}[{{audioCodec}}]{% endif %}{% if videoCodec %}[{{videoCodec}}]{% endif %}{% if releaseGroup %}-{{releaseGroup}}{% endif %}{{fileExt}}"
TV_RENAME_FORMAT="{{original_title}}{% if year %} ({{year}}){% endif %}/Season {{season}}/{{original_title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if imdbid %} {imdb-{{imdbid}}}{% endif %}{% if videoFormat %} [{{videoFormat}}]{% endif %}{% if edition %}[{{edition}}]{% endif %}{% if audioCodec %}[{{audioCodec}}]{% endif %}{% if videoCodec %}[{{videoCodec}}]{% endif %}{% if releaseGroup %}-{{releaseGroup}}{% endif %}{% endif %}{{fileExt}}"
```

**Comment by cng10001** [comment]
@jxxghp 大佬能否再优化下
(和历史记录-删除里面手动操作一样,把媒体库文件连同刮削文件夹一并删除),现在刮削文件夹和里面的nfo还有图片信息还留着
