### ISSUE TITLE
[错误报告]: 演职人员刮削插件使用问题

### ISSUE THREAD

**Issue by cng10001** [jxxghp/MoviePilot#733]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.2.8 最新

### 问题类型

插件问题

### 问题描述

环目前环境是群晖Docker，使用的媒体库是Jellyfin

> ①有的演员会刮削错误，日志上看英文名中文名似乎都是对的，但是Jellyfin上实际不对
![费翔](https://github.com/jxxghp/MoviePilot/assets/115156545/1357fe07-a85e-439a-9411-496e861793d9)
![人物错误](https://github.com/jxxghp/MoviePilot/assets/115156545/5f060275-158f-4f10-a105-0a55bc0a4d53)

> ②头像显示不出来，必须一个个点进去才能显示。以为是浏览器缓存问题，但是换了也是这样
![默认头像](https://github.com/jxxghp/MoviePilot/assets/115156545/daf94112-b6c7-4e1e-8743-2aa958341e93)

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-05 03:05:58,424 - __init__.py - 演职人员刮削服务启动，立即运行一次
【INFO】2023-10-05 03:06:01,380 - __init__.py - 开始刮削服务器 jellyfin 的演员信息 ...
【INFO】2023-10-05 03:06:01,581 - __init__.py - 开始刮削媒体库 迅雷-电影 的演员信息 ...
【INFO】2023-10-05 03:06:01,798 - __init__.py - 开始刮削 封神第一部：朝歌风云 的演员信息 ...
【INFO】2023-10-05 03:06:01,799 - tmdbapi.py - 正在查询TMDB电影：856289 ...
【INFO】2023-10-05 03:06:02,663 - tmdbapi.py - 856289 查询结果：封神第一部：朝歌风云
【INFO】2023-10-05 03:06:02,664 - __init__.py - 856289 识别结果：电影 封神第一部：朝歌风云 (2023)
【INFO】2023-10-05 03:06:06,724 - __init__.py - 开始获取豆瓣信息：10604086 ...
【INFO】2023-10-05 03:06:11,571 - tmdbapi.py - 正在获取人物详情：1133067...
【INFO】2023-10-05 03:06:12,317 - __init__.py - Kris Phillips 从TMDB获取到中文名：费翔
【INFO】2023-10-05 03:06:12,317 - __init__.py - Kris Phillips 从TMDB获取到中文描述
【INFO】2023-10-05 03:06:12,317 - __init__.py - Kris Phillips 从TMDB获取到图片：/gh6dlF5SkVKfNrRaHVseBwiTbUA.jpg
【INFO】2023-10-05 03:06:12,318 - __init__.py - Kris Phillips 从豆瓣中获取到饰演角色：商王殷寿
【INFO】2023-10-05 03:06:12,318 - __init__.py - 更新人物 Kris Phillips 的图片：https://image.tmdb.org/t/p/original/gh6dlF5SkVKfNrRaHVseBwiTbUA.jpg
【INFO】2023-10-05 03:06:14,719 - __init__.py - 更新人物 Kris Phillips 的信息：{'Name': '费翔', 'ServerId': '97030c83e6b4480db8737c056068aeea', 'Id': 'bc52deb935b75087fa22a5da679c94df', 'Etag': '23b5eb306814728d94b27f5b06b89180', 'DateCreated': '2023-10-02T07:24:53.9806901Z', 'CanDelete': False, 'CanDownload': False, 'SortName': 'Kris Phillips', 'PremiereDate': '1960-12-23T16:00:00.0000000Z', 'ExternalUrls': [{'Name': 'IMDb', 'Url': 'https://www.imdb.com/name/nm1191525'}, {'Name': 'TheMovieDb', 'Url': 'https://www.themoviedb.org/person/1133067'}], 'Path': '/config/metadata/People/K/Kris Phillips', 'EnableMediaSourceDisplay': True, 'ChannelId': None, 'Overview': '费翔（英文名：Kris Phillips）是台湾裔美籍华语流行乐歌手及电影、电视演员与美国百老汇音乐剧演员，中华民国新北新店人。1980年代在台湾出道并走红，之后往东南亚发展，在新加坡被评选为亚洲十大歌星之一，1987年成为第一位到中国大陆的台湾歌手，至1989年在中国大陆举办了65场个人演唱会，后来淡出萤光幕前，定居在英国。', 'Taglines': [], 'Genres': [], 'PlayAccess': 'Full', 'RemoteTrailers': [], 'ProviderIds': {'Tmdb': '1133067', 'Imdb': 'nm1191525'}, 'ParentId': None, 'Type': 'Person', 'People': [], 'Studios': [], 'GenreItems': [], 'LocalTrailerCount': 0, 'UserData': {'PlaybackPositionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False, 'Key': 'Person-Kris Phillips'}, 'ChildCount': 1, 'SpecialFeatureCount': 0, 'DisplayPreferencesId': 'b607178b0ac2f604a458d3d2363fdc83', 'Tags': [], 'PrimaryImageAspectRatio': 0.6659856996935649, 'ImageTags': {'Primary': '51228ecf166ab3d30f3527f1a859ad36'}, 'BackdropImageTags': [], 'ImageBlurHashes': {'Primary': {'51228ecf166ab3d30f3527f1a859ad36': 'dIBWJNIo0L-oI9ogS5s.9Fay%2Rj%gayxFj]Nbs:n$WY'}}, 'LocationType': 'FileSystem', 'LockedFields': ['Name', 'Overview'], 'TrailerCount': 0, 'MovieCount': 1, 'SeriesCount': 0, 'ProgramCount': 0, 'EpisodeCount': 0, 'SongCount': 0, 'AlbumCount': 0, 'ArtistCount': 0, 'MusicVideoCount': 0, 'LockData': False, 'FileName': 'Kris Phillips'}
```

**Comment by cng10001** [comment]
还有大佬能说下插件配置其中的“入库延迟时间”是什么意思嘛

**Comment by qhly2010** [comment]
我的也是这样，演员图片不显示，以前都是正常显示的，不知道啥时候开始就不行了。对比了一下nt刮削出来的电影nfo文件，发现mp刮削出来的nfo文件内容比nt少了三项，如下图:
Nt的nfo
![Screenshot_20230930_155351_com rhmsoft editt_edit_740593851120846](https://github.com/jxxghp/MoviePilot/assets/97014801/6045fe29-4aca-4fd3-a652-529eccdf68eb)
Mp的nfo
![Screenshot_20230930_155437_com rhmsoft editt_edit_740609307169802](https://github.com/jxxghp/MoviePilot/assets/97014801/eb5ff358-c01d-4dfe-8dc7-c3b86b537506)
其中thumb这项后面的地址就是演员头像图片，刚好mp刮削出来的就没有。网络测试mp中api.tmdb.org和www.themoviedb.org是通的。
查看了emby安装目录内的people文件夹，发现里面也没有生成演员图片，不清楚这个演员头像图片是跟mp的刮削有关还是跟emby有关了。

**Comment by yunzhongci** [comment]
这个演职人员刮削之后的数据是存在哪个文件夹？

**Comment by cng10001** [comment]
> 我的也是这样，演员图片不显示，以前都是正常显示的，不知道啥时候开始就不行了。对比了一下nt刮削出来的电影nfo文件，发现mp刮削出来的nfo文件内容比nt少了三项，如下图: Nt的nfo ![Screenshot_20230930_155351_com rhmsoft editt_edit_740593851120846](https://user-images.githubusercontent.com/97014801/272948360-6045fe29-4aca-4fd3-a652-529eccdf68eb.jpg) Mp的nfo ![Screenshot_20230930_155437_com rhmsoft editt_edit_740609307169802](https://user-images.githubusercontent.com/97014801/272948462-eb5ff358-c01d-4dfe-8dc7-c3b86b537506.jpg) 其中thumb这项后面的地址就是演员头像图片，刚好mp刮削出来的就没有。网络测试mp中api.tmdb.org和www.themoviedb.org是通的。 查看了emby安装目录内的people文件夹，发现里面也没有生成演员图片，不清楚这个演员头像图片是跟mp的刮削有关还是跟emby有关了。

我的jellyfin在metadata\People里面,有啊

**Comment by cng10001** [comment]
> 这个演职人员刮削之后的数据是存在哪个文件夹？

在你媒体库配置文件夹里 metadata\People

**Comment by jxxghp** [comment]
89854d188d07726371d6e3cb32e84f5f54a5726b

**Comment by yunzhongci** [comment]
> > 这个演职人员刮削之后的数据是存在哪个文件夹？> > 这个演职人员刮削之后的数据是存在哪个文件夹？>> 在你媒体库配置文件夹里 metadata\People>> 在你媒体库配置文件夹里 metadata\People

要额外映射文件夹吗？怎么映射？

**Comment by cng10001** [comment]
> > > 这个演职人员刮削之后的数据是存在哪个文件夹？> > 这个演职人员刮削之后的数据是存在哪个文件夹？>> 在你媒体库配置文件夹里 metadata\People>> 在你媒体库配置文件夹里 metadata\People
> 
> 要额外映射文件夹吗？怎么映射？

 你还没有开始用嘛，不需要映射啊

**Comment by zraxx** [comment]
插件另一个问题：（媒体库为jellyfin）
日志如下：演职人员刮削 亿万 (2016) 在媒体库中不存在
<html>
<body>


INFO | 14:59:47,267 | __init__.py | Billions 使用识别缓存：亿万
-- | -- | -- | --
INFO | 14:59:47,268 | tmdbapi.py | 正在查询TMDB电视剧：62852 ...
INFO | 14:59:47,271 | tmdbapi.py | 62852 查询结果：亿万
INFO | 14:59:47,272 | __init__.py | Billions 识别结果：电视剧 亿万 (2016) 62852
INFO | 14:59:47,272 | transfer.py | Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：亿万 (2016)
INFO | 14:59:47,273 | transfer.py | 开始删除文件以及空目录：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
WARNING | 14:59:47,295 | transfer.py | 文件 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 已删除
INFO | 14:59:47,297 | transfer.py | Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：电视剧 亿万 (2016)
INFO | 14:59:47,297 | tmdbapi.py | 正在查询TMDB电视剧：62852，季：7 ...
INFO | 14:59:47,323 | __init__.py | 正在转移文件：/share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 到 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv
INFO | 14:59:47,324 | __init__.py | 文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv link完成
INFO | 14:59:47,325 | __init__.py | 文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移成功
INFO | 14:59:47,335 | __init__.py | 开始刮削媒体库文件：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
INFO | 14:59:47,336 | tmdbapi.py | 正在查询TMDB电视剧：62852，季：7 ...
INFO | 14:59:47,337 | scraper.py | 正在生成剧集NFO文件：亿万 - S07E09 - 第 9 集.mkv
INFO | 14:59:47,337 | scraper.py | NFO文件已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.nfo
INFO | 14:59:47,337 | scraper.py | 正在下载亿万 - S07E09 - 第 9 集图片：https://image.tmdb.org/t/p/original/4FsGS85hlElg8vupbtmkvIoRi5s.jpg ...
INFO | 14:59:48,445 | scraper.py | 图片已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.jpg
INFO | 14:59:48,446 | __init__.py | /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 刮削完成
INFO | 14:59:48,455 | __init__.py | 发送消息：channel=None，title=亿万 (2016) S07 E09 已入库, text=评分：7.7，类型：电视剧，质量： WEB-DL 2160p，共1个文件，大小：6.23G，userid=None
INFO | 14:59:48,455 | command.py | 处理事件：notice.message - [<function MessageForward.send at 0x7f77a9462700>, <function WebHook.send at 0x7f77a944df80>]
INFO | 14:59:48,745 | transfer.py | /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
INFO | 14:59:48,746 | command.py | 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f77a9563740>, <function PersonMeta.scrap_rt at 0x7f77a94e8540>, <function WebHook.send at 0x7f77a944df80>]
INFO | 14:59:58,815 | __init__.py | 亿万 (2016) 文件系统已存在：{2: [4, 8, 1, 6, 5, 3, 11, 12, 10, 9, 2, 7], 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 3: [4, 1, 6, 3, 8, 11, 10, 12, 9, 7, 5, 2], 6: [1, 2, 3, 4, 6, 5, 7, 8, 9, 10, 11, 12], 4: [10, 9, 3, 8, 5, 2, 7, 4, 1, 6, 12, 11], 5: [6, 2, 9, 11, 8, 10, 1, 5, 7, 3, 4, 12], 7: [1, 2, 3, 4, 5, 6, 7, 8, 9]}
WARNING | 14:59:58,816 | __init__.py | 演职人员刮削 亿万 (2016) 在媒体库中不存在


</body>
</html>

**Comment by cng10001** [comment]
> 插件另一个问题：（mp版本为：v1.2.8，媒体库为jellyfin） 日志如下：演职人员刮削 亿万 (2016) 在媒体库中不存在
> 
> INFO	14:59:47,267	**init**.py	Billions 使用识别缓存：亿万
> INFO	14:59:47,268	tmdbapi.py	正在查询TMDB电视剧：62852 ...
> INFO	14:59:47,271	tmdbapi.py	62852 查询结果：亿万
> INFO	14:59:47,272	**init**.py	Billions 识别结果：电视剧 亿万 (2016) 62852
> INFO	14:59:47,272	transfer.py	Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：亿万 (2016)
> INFO	14:59:47,273	transfer.py	开始删除文件以及空目录：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
> WARNING	14:59:47,295	transfer.py	文件 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 已删除
> INFO	14:59:47,297	transfer.py	Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：电视剧 亿万 (2016)
> INFO	14:59:47,297	tmdbapi.py	正在查询TMDB电视剧：62852，季：7 ...
> INFO	14:59:47,323	**init**.py	正在转移文件：/share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 到 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv
> INFO	14:59:47,324	**init**.py	文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv link完成
> INFO	14:59:47,325	**init**.py	文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移成功
> INFO	14:59:47,335	**init**.py	开始刮削媒体库文件：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
> INFO	14:59:47,336	tmdbapi.py	正在查询TMDB电视剧：62852，季：7 ...
> INFO	14:59:47,337	scraper.py	正在生成剧集NFO文件：亿万 - S07E09 - 第 9 集.mkv
> INFO	14:59:47,337	scraper.py	NFO文件已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.nfo
> INFO	14:59:47,337	scraper.py	正在下载亿万 - S07E09 - 第 9 集图片：https://image.tmdb.org/t/p/original/4FsGS85hlElg8vupbtmkvIoRi5s.jpg ...
> INFO	14:59:48,445	scraper.py	图片已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.jpg
> INFO	14:59:48,446	**init**.py	/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 刮削完成
> INFO	14:59:48,455	**init**.py	发送消息：channel=None，title=亿万 (2016) S07 E09 已入库, text=评分：7.7，类型：电视剧，质量： WEB-DL 2160p，共1个文件，大小：6.23G，userid=None
> INFO	14:59:48,455	command.py	处理事件：notice.message - [<function MessageForward.send at 0x7f77a9462700>, <function WebHook.send at 0x7f77a944df80>]
> INFO	14:59:48,745	transfer.py	/share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
> INFO	14:59:48,746	command.py	处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f77a9563740>, <function PersonMeta.scrap_rt at 0x7f77a94e8540>, <function WebHook.send at 0x7f77a944df80>]
> INFO	14:59:58,815	**init**.py	亿万 (2016) 文件系统已存在：{2: [4, 8, 1, 6, 5, 3, 11, 12, 10, 9, 2, 7], 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 3: [4, 1, 6, 3, 8, 11, 10, 12, 9, 7, 5, 2], 6: [1, 2, 3, 4, 6, 5, 7, 8, 9, 10, 11, 12], 4: [10, 9, 3, 8, 5, 2, 7, 4, 1, 6, 12, 11], 5: [6, 2, 9, 11, 8, 10, 1, 5, 7, 3, 4, 12], 7: [1, 2, 3, 4, 5, 6, 7, 8, 9]}
> WARNING	14:59:58,816	**init**.py	演职人员刮削 亿万 (2016) 在媒体库中不存在

你Jellyfin有多个用户吗

**Comment by qhly2010** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/97014801/230027bd-fc95-4de2-9c0a-c0c3293e32a6)
更新最新版本后，虽然nfo文件内有thumb信息了，但是emby还是不显示演员头像，而且mp刮削出来的nfo信息还有乱码
日志：

> INFO:    __init__.py - Creation Of The Gods I Kingdom Of Storms 使用识别缓存：封神第一部：朝歌风云                                                                                                          
INFO:    tmdbapi.py - 正在查询TMDB电影：856289 ...                                                                                                                                                          
INFO:    tmdbapi.py - 856289 查询结果：封神第一部：朝歌风云                                                                                                                                                 
INFO:    __init__.py - Creation Of The Gods I Kingdom Of Storms 识别结果：电影 封神第一部：朝歌风云 (2023) 856289                                                                                           
INFO:    transfer.py - Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB.mkv 识别为：封神第一部：朝歌风云 (2023)                                                             
WARNING: __init__.py - 没有获取到 封神第一部：朝歌风云 (2023) 的Fanart图片数据                                                                                                                              
INFO:    tmdbapi.py - 正在获取电影图片：856289...                                                                                                                                                           
INFO:    transfer.py - 开始删除文件以及空目录：/volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.mkv ...                                                         
WARNING: transfer.py - 文件 /volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.mkv 已删除                                                                         
WARNING: transfer.py - 目录 /volume1/Download/Links/电影/封神第一部：朝歌风云 (2023) 已删除                                                                                                                 
INFO:    transfer.py - Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB.mkv 识别为：电影 封神第一部：朝歌风云 (2023)                                                        
WARNING: __init__.py - 没有获取到 封神第一部：朝歌风云 (2023) 的Fanart图片数据                                                                                                                              
INFO:    __init__.py - 正在转移文件：/volume1/Download/Media/封神第一部：朝歌风云.Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB/Creation.of.the.Gods.I.Kingdom.of.Storms.
2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB.mkv 到 /volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.mkv                                                             
INFO:    __init__.py - 文件 /volume1/Download/Media/封神第一部：朝歌风云.Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB/Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160
p.HQ.WEB-DL.H265.DDP5.1-CHDWEB.mkv link完成                                                                                                                                                                 
INFO:    __init__.py - 文件 /volume1/Download/Media/封神第一部：朝歌风云.Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB/Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160
p.HQ.WEB-DL.H265.DDP5.1-CHDWEB.mkv 转移成功                                                                                                                                                                 
INFO:    __init__.py - 开始刮削媒体库文件：/volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.mkv ...                                                             
INFO:    scraper.py - 正在生成电影NFO文件：封神第一部：朝歌风云 (2023) - 2160p.mkv                                                                                                                          
INFO:    scraper.py - NFO文件已保存：/volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.nfo                                                                       
INFO:    scraper.py - 正在下载backdrop图片：https://image.tmdb.org/t/p/original/xxcybNaW4oHyhBHMA4ppU8K45ET.jpg ...                                                                                         
INFO:    scraper.py - 图片已保存：/volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/backdrop.jpg                                                                                                     
INFO:    scraper.py - 正在下载poster图片：https://image.tmdb.org/t/p/original/6P4bZuV9barAeJstqAwkE1F0XmN.jpg ...                                                                                           
INFO:    scraper.py - 图片已保存：/volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/poster.jpg                                                                                                       
INFO:    __init__.py - /volume1/Download/Links/电影/封神第一部：朝歌风云 (2023)/封神第一部：朝歌风云 (2023) - 2160p.mkv 刮削完成                                                                            
INFO:    emby.py - 开始刷新Emby媒体库...                                                                                                                                                                    
INFO:    __init__.py - 发送消息：channel=None，title=封神第一部：朝歌风云 (2023)  已入库, text=评分：7.4，类型：电影，质量： WEB-DL 2160p，共1个文件，大小：21.11G，userid=None                             
INFO:    command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f9aeee8a020>, <function WebHook.send at 0x7f9aeecd18a0>]                                                              
INFO:    transfer.py - /volume1/Download/Media/封神第一部：朝歌风云.Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.H265.DDP5.1-CHDWEB/Creation.of.the.Gods.I.Kingdom.of.Storms.2023.2160p.HQ.
WEB-DL.H265.DDP5.1-CHDWEB.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个                                                                                                                                   
INFO:    command.py - 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f9aeede3240>, <function PersonMeta.scrap_rt at 0x7f9aeee8be20>, <function WebHook.send at 0x7f9aeecd18a0>]   
INFO:     172.17.0.1:0 - "POST /api/v1/history/transfer?mtype=&new_tmdbid=0 HTTP/1.1" 200 OK                                                                                                                
INFO:     172.17.0.1:0 - "GET /api/v1/history/transfer?page=1&count=25&title= HTTP/1.1" 200 OK                                                                                                              
INFO:    __init__.py - 媒体库中已存在：[MediaServerItem(id=None, server='emby', library=None, item_id='127550', item_type='Movie', title='封神第一部：朝歌风云', original_title=None, year='2023', tmdbid=No
ne, imdbid=None, tvdbid=None, path=None, seasoninfo=None, note=None, lst_mod_date=None)]                                                                                                                    
INFO:    __init__.py - 开始获取豆瓣信息：10604086 ...                                                                                                                                                       
WARNING: __init__.py - 未找到人物 Sheng Cao 的信息

**Comment by zraxx** [comment]
> > 插件另一个问题：（mp版本为：v1.2.8，媒体库为jellyfin） 日志如下：演职人员刮削 亿万 (2016) 在媒体库中不存在
> > 
> > INFO	14:59:47,267	**init**.py	Billions 使用识别缓存：亿万
> > INFO	14:59:47,268	tmdbapi.py	正在查询TMDB电视剧：62852 ...
> > INFO	14:59:47,271	tmdbapi.py	62852 查询结果：亿万
> > INFO	14:59:47,272	**init**.py	Billions 识别结果：电视剧 亿万 (2016) 62852
> > INFO	14:59:47,272	transfer.py	Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：亿万 (2016)
> > INFO	14:59:47,273	transfer.py	开始删除文件以及空目录：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
> > WARNING	14:59:47,295	transfer.py	文件 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 已删除
> > INFO	14:59:47,297	transfer.py	Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 识别为：电视剧 亿万 (2016)
> > INFO	14:59:47,297	tmdbapi.py	正在查询TMDB电视剧：62852，季：7 ...
> > INFO	14:59:47,323	**init**.py	正在转移文件：/share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 到 /share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv
> > INFO	14:59:47,324	**init**.py	文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv link完成
> > INFO	14:59:47,325	**init**.py	文件 /share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移成功
> > INFO	14:59:47,335	**init**.py	开始刮削媒体库文件：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv ...
> > INFO	14:59:47,336	tmdbapi.py	正在查询TMDB电视剧：62852，季：7 ...
> > INFO	14:59:47,337	scraper.py	正在生成剧集NFO文件：亿万 - S07E09 - 第 9 集.mkv
> > INFO	14:59:47,337	scraper.py	NFO文件已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.nfo
> > INFO	14:59:47,337	scraper.py	正在下载亿万 - S07E09 - 第 9 集图片：https://image.tmdb.org/t/p/original/4FsGS85hlElg8vupbtmkvIoRi5s.jpg ...
> > INFO	14:59:48,445	scraper.py	图片已保存：/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.jpg
> > INFO	14:59:48,446	**init**.py	/share/downloads2/media/电视剧/亿万 (2016)/Season 7/亿万 - S07E09 - 第 9 集.mkv 刮削完成
> > INFO	14:59:48,455	**init**.py	发送消息：channel=None，title=亿万 (2016) S07 E09 已入库, text=评分：7.7，类型：电视剧，质量： WEB-DL 2160p，共1个文件，大小：6.23G，userid=None
> > INFO	14:59:48,455	command.py	处理事件：notice.message - [<function MessageForward.send at 0x7f77a9462700>, <function WebHook.send at 0x7f77a944df80>]
> > INFO	14:59:48,745	transfer.py	/share/downloads2/电视/Billions.S07.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB/Billions.S07E09.Game.Theory.Optimal.2160p.SHO.WEB-DL.DD.5.1.H.265-CHDWEB.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
> > INFO	14:59:48,746	command.py	处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f77a9563740>, <function PersonMeta.scrap_rt at 0x7f77a94e8540>, <function WebHook.send at 0x7f77a944df80>]
> > INFO	14:59:58,815	**init**.py	亿万 (2016) 文件系统已存在：{2: [4, 8, 1, 6, 5, 3, 11, 12, 10, 9, 2, 7], 1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 3: [4, 1, 6, 3, 8, 11, 10, 12, 9, 7, 5, 2], 6: [1, 2, 3, 4, 6, 5, 7, 8, 9, 10, 11, 12], 4: [10, 9, 3, 8, 5, 2, 7, 4, 1, 6, 12, 11], 5: [6, 2, 9, 11, 8, 10, 1, 5, 7, 3, 4, 12], 7: [1, 2, 3, 4, 5, 6, 7, 8, 9]}
> > WARNING	14:59:58,816	**init**.py	演职人员刮削 亿万 (2016) 在媒体库中不存在
> 
> 你Jellyfin有多个用户吗

多用户
