### ISSUE TITLE
[错误报告]: 刷流与订阅冲突

### ISSUE THREAD

**Issue by iceucn** [jxxghp/MoviePilot#737]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.8

### 问题类型

插件问题

### 问题描述

当订阅与刷流插件同时开启时
订阅的内容被刷流先行下载后，订阅添加种子的时候会提示添加下载失败，因为刷流插件已经添加了此种子；
改进建议：当订阅任务执行时，先判断是否开启了刷流插件，如果开启，订阅添加种子失败后，执行查询是否此种子刷流中，转换下载器标签；
因为还有些手工添加的种子在下载器，或者在订阅添加种子失败后，统一查询下下载器是否存在此种子，然后变换标签等操作~

**Comment by jxxghp** [comment]
这是比较困难的，主干程序不应该去检测插件的行为。
刷流也要有规划，不建议盲开。
