### ISSUE TITLE
[错误报告]: 历史记录删除中，删除源文件的同时，是否应该删除下载器种子。

### ISSUE THREAD

**Issue by iceucn** [jxxghp/MoviePilot#738]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.8

### 问题类型

主程序运行问题

### 问题描述

历史记录删除，目前选在删除记录的时候，选择删除 历史记录和源文件，历史记录与源文件删除了，但是下载器种子还未删除，源文件已经删除了，下载器的种子应该也不能做种了，是否应该一并删除？

**Comment by jxxghp** [comment]
开启媒体文件同步删除插件
