### ISSUE TITLE
[Feature Request]: 是否考虑增加音乐文件的搜刮整理插件

### ISSUE THREAD

**Issue by iceucn** [jxxghp/MoviePilot#739]
### 当前程序版本

1.2.8

### 功能改进类型

插件

### 功能改进

目前市面上音乐文件的搜刮整理程序参差不齐，是否考虑增加音乐文件的 整理与搜刮，数据用腾讯音乐或者网易云的~！

**Comment by dlovew** [comment]
建议用Musictag
