### ISSUE TITLE
[Feature Request]: ocr识别服务可否增加BaiduOCR

### ISSUE THREAD

**Issue by wangzhili888** [jxxghp/MoviePilot#744]
### 当前程序版本

1.2.8

### 功能改进类型

Docker

### 功能改进

ocr识别服务可否增加BaiduOCR，然后填写Baidu OCR API Key和Baidu OCR Secret Key，MP的ocr服务总搭建不成功，一直重启。

**Comment by jxxghp** [comment]
验证码图片如果不做处理，直接识别的成率率是很低的。

**Comment by wangzhili888** [comment]
接口选用百度高精度，识别率很高，各个站试了10多次，我这边还没有失败的，调用也很快，免费个人额度500次每天，个人用完全够用。

**Comment by wangzhili888** [comment]
别用标准版，标准版识别是不行。
