### ISSUE TITLE
[连接数过多]: 通过代理面板可以看到较多themoviedb api的连接一直存在。

### ISSUE THREAD

**Issue by lie5860** [jxxghp/MoviePilot#746]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

laster

### 问题类型

其他问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/30894657/b0c41b1a-bdb7-4a84-ab55-439cf551f458)
接入代理后，运行一段时间后 会发现themoviedb api连接会一直存在。关闭容器连接会全部关闭。应该较易复现。不太确定未close的原因。
这些连接会占用设备的端口和内存，如果可以，希望能正常释放掉。

### 发生问题时系统日志和配置文件

```bash
日志中无明显报错。有需要可以提供相关日志。
```

**Comment by jxxghp** [comment]
不是刚发了版本吗

**Comment by lie5860** [comment]
> 不是刚发了版本吗

太棒了太棒了。刚提了 这么巧已经处理了
