### ISSUE TITLE
[错误报告]: 增加app.env文件后，启动一直报错，容器无限重启

### ISSUE THREAD

**Issue by dick86114** [jxxghp/MoviePilot#748]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.2.9

### 问题类型

Docker或运行环境问题

### 问题描述

增加app.env文件，启动后一直报错，提示python-dotenv无法安装，容器反复重启，无法正常使用。设备是极空间z4s，家里网络已科学。

### 发生问题时系统日志和配置文件

```bash
日志
lmportError: python-dotenv is not installed, run pip install pydantic[dotenv]
File "pydantic/env settings.py", line 332, in pydantic.env settings.read env file
File "pydantic/env settings.py", line 226, in pydantic.env settings.EnvSettingsSource. read env filesFile "pydantic/env settings.py", line 177,in pydantic.env settings.EnvSettingsSource. call
File "pydantic/env settings.py", line 76, in pydantic.env settings.BaseSettings. build valuesFile "pydantic/env settings.py", line 41, in pydantic.env settings.BaseSettings. init
super0. init (**kwargs)
File"/app/app/core/config.py",line 272, in init

settings = Settings0
File"/app/app/core/config.py”，ine 289, in <module>
from app.core.config import settings
File "/app/app/chain/ init py", line 13,in <module>
from app.chain import ChainBase
File"/app/app/command.py”,line 5, in <module>
```

**Comment by thsrite** [comment]
@dick86114 重拉镜像

**Comment by dick86114** [comment]
> @dick86114 重拉镜像

好的，已经可以，感谢

**Comment by dick86114** [comment]
> @dick86114 重拉镜像

又有了新问题，我把环境变量里的参数都删了，然后都改到env里配置，结果重启容器后，又会自动添加默认环境变量，因为环境变量优先级更高，导致不会先读取env文件，而是走了环境变量里的容器默认配置

**Comment by jxxghp** [comment]
> > @dick86114 重拉镜像
> 
> 又有了新问题，我把环境变量里的参数都删了，然后都改到env里配置，结果重启容器后，又会自动添加默认环境变量，因为环境变量优先级更高，导致不会先读取env文件，而是走了环境变量里的容器默认配置

是用compose建的环境吗？ 怀疑env不能跟compose同时使用。

**Comment by dick86114** [comment]
> > > @dick86114 重拉镜像
> > 
> > 
> > 又有了新问题，我把环境变量里的参数都删了，然后都改到env里配置，结果重启容器后，又会自动添加默认环境变量，因为环境变量优先级更高，导致不会先读取env文件，而是走了环境变量里的容器默认配置
> 
> 是用compose建的环境吗？ 怀疑env不能跟compose同时使用。

不是的，我是极空间，极空间的docker不支持compose，所以之前是手动一项一项配置的，终于等到了env方式，但极空间在启动容器的时候会添加一些默认的配置项，如下图：
<img width="295" alt="f898ddeb021a6ddfe83a12af35bc4cb" src="https://github.com/jxxghp/MoviePilot/assets/9260418/37addcab-3a5b-432f-b13a-80f39d52112b">

目前我的解决办法是把默认的环境变量配置项都配全，然后其他项在env里配置。
另外，环境变量里还需要增加IYUU_SIGN的配置，否则后台提示未配置IYUU_SIGN（即便在env里已经配置好了IYUU_SIGN）

**Comment by jxxghp** [comment]
我知道了，是dockerfile有默认值的原因。我更新下镜像。
