### ISSUE TITLE
使用jellyseerr提交电视剧请求时，发送给moviepilot的是tvdb的id，然而moviepilot识别不了

### ISSUE THREAD

**Issue by CookieJaySJ** [jxxghp/MoviePilot#75]
修复后问题依旧😂   

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Waynenet** [comment]
好像豆瓣同步也会这样

**Comment by yubanmeiqin9048** [comment]
请不要提重复的issue
