### ISSUE TITLE
[错误报告]: IYUU自动辅种清除缓存后在运行实际并未完全清楚缓存

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#753]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.2.9

### 问题类型

插件问题

### 问题描述

IYUU自动辅种清除缓存后在运行实际并未完全清楚缓存,上次由于https的原因，天空大量辅种失败，后面想用清楚缓存再重新运行一边辅种程序，发现无论如何都辅不到之前下载失败的种子了，查看日志发现报辅种失败且已缓存过...
<img width="969" alt="iShot_2023-10-07_22 44 42" src="https://github.com/jxxghp/MoviePilot/assets/34505611/66c591d1-df8c-425e-9059-ed2ec5de720e">

**Comment by jxxghp** [comment]
站点选了天空？

**Comment by yellowstrong** [comment]
> 站点选了天空？

有选择天空，特别关注过

**Comment by yellowstrong** [comment]
> 站点选了天空？

刚刚测试通过原版的IYUU对天空进行辅种，成功出现种子，应该确认了是清除缓存的功能并没有完全清楚之前辅种下载失败的缓存导致的

**Comment by jxxghp** [comment]
从代码上看，如果是缓存的原因，日志里一定会有缓存字样。

**Comment by yellowstrong** [comment]
> 从代码上看，如果是缓存的原因，日志里一定会有缓存字样。

这是我勾选了立即运行一次和清除缓存后运行，执行确认后的日志信息，可以看到有大量的种子是提示辅种失败且已缓存，跳过...
![iShot_2023-10-09_10 51 42](https://github.com/jxxghp/MoviePilot/assets/34505611/da8fa980-54b7-44af-9f1e-455f2d419afd)

![2023-10-09 10 50 05](https://github.com/jxxghp/MoviePilot/assets/34505611/641688f2-5284-4b22-bed0-584b5aadf7f1)

**Comment by yellowstrong** [comment]
> > 从代码上看，如果是缓存的原因，日志里一定会有缓存字样。
> 
> 这是我勾选了立即运行一次和清除缓存后运行，执行确认后的日志信息，可以看到有大量的种子是提示辅种失败且已缓存，跳过... ![iShot_2023-10-09_10 51 42](https://user-images.githubusercontent.com/34505611/273489986-da8fa980-54b7-44af-9f1e-455f2d419afd.png)
> 
> ![2023-10-09 10 50 05](https://user-images.githubusercontent.com/34505611/273489940-641688f2-5284-4b22-bed0-584b5aadf7f1.png)

怀疑是不是plugindata表里面的iyuu相关数据没有清楚干净导致的？
