### ISSUE TITLE
[错误报告]: 媒体库同步 - 用户id key 问题

### ISSUE THREAD

**Issue by paysenyu** [jxxghp/MoviePilot#770]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.0

### 问题类型

主程序运行问题

### 问题描述

前几天发现emby 媒体库同步老是0 ,今天切到debug 一看, 原来是connectionpool.py 绑定了我专门给小姐姐的userid

(暂不清楚mp 是怎么从3个user中,选择了指定的一个user) 

但是mp端又没有地方可以切换userid, 导致同步emby的时候,只能同步这个固定user的媒体库

可否加入选择emby user的选项, 或者 在env中指定 user key 

### 发生问题时系统日志和配置文件

```bash
INFO:    mediaserver.py - 开始同步媒体库 emby 的数据 ...
DEBUG:   __init__.py - 请求模块执行：mediaserver_librarys ...
DEBUG:   connectionpool.py - Starting new HTTP connection (1): 10.105.1.5:8096
DEBUG:   connectionpool.py - http://10.105.1.5:8096 "GET /emby/Users/9721451379304293a4a4225a9839202b/Views?api_key=a03d455b1f8c45259e16dd949d0872ee HTTP/1.1" 200 606
INFO:    mediaserver.py - 【MediaServer】媒体库数据同步完成，同步数量：0
```

**Comment by jxxghp** [comment]
优先使用与媒体服务与mp相同用户名称的账号，否则使用admin
