### ISSUE TITLE
win版 站点认证参数设置 

### ISSUE THREAD

**Issue by FireGodson** [jxxghp/MoviePilot#771]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.0

### 问题类型

其他问题

### 问题描述

你好，win版认证参数在哪里设置呢，app.env文件里没有相关参数设置，要自己填写么。在app.env文件里加上这两个参数AUTH_SITE=iyuu
IYUU_SIGN=
填上自己的iyuu登录令牌后依旧提示错误
![20231009_105110](https://github.com/jxxghp/MoviePilot/assets/32048420/c83f2980-613b-4a83-993f-1fce9cea2aed)
![20231009_111623](https://github.com/jxxghp/MoviePilot/assets/32048420/9043059c-fe00-44b4-a862-058295b02bab)

**Comment by AisukaYuki** [comment]
这个可以在系统环境中设置变量临时解决一下，最大的bug是插件库404。无解，我用源码直接跑。

**Comment by BackspaceM** [comment]
CMD管理员命令   
setx IYUU_SIGN ’令牌‘ （无引号）

**Comment by FireGodson** [comment]
> 这个可以在系统环境中设置变量临时解决一下，最大的bug是插件库404，加载不了插件。无解，等修复。 我用源码直接跑，没问题

好的谢谢啦

**Comment by FireGodson** [comment]
> CMD管理员命令 setx IYUU_SIGN ’令牌‘ （无引号）

好的谢谢啦

**Comment by SoTender** [comment]
请问最新1.7.2win版的这个应该如何设置？站点时HHCLUB

**Comment by BackspaceM** [comment]
> 请问最新1.7.2win版的这个应该如何设置？站点时HHCLUB

一样的啊，先增加认证类型的变量，然后填写该认证的站点即可，命令是上述的setx AUTH_SITE hhclub，然后setx hHHCLUB_USERNAME 你的用户名，最后setx HHCLUB_PASSKEY 你得passkey
