### ISSUE TITLE
[错误报告]: 目录监控插件配置转移方式异常

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#773]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.0

### 问题类型

插件问题

### 问题描述

目录监控插件配置转移方式异常

插件配置
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/5acd0b92-2cad-43a2-b57e-22c461928f97)

转移结果
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/c875d874-d72b-46a8-b470-c526244149e4)

设置为move的并未移动，原文件还在
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/2360995f-72d5-4daa-b34c-7cdcb8a347b1)

**Comment by mjsoftking** [comment]
另外文件整理时选择 移动方式也不正确
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/06a9556c-89fd-4521-8463-bc9bb7462ead)

![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/f946480c-2cf1-41d1-a7bc-771438dd9657)

**Comment by thsrite** [comment]
> ### 确认
> * [x]  我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
> * [x]  我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
> * [x]  我已经修改标题，将标题中的 描述 替换为我遇到的问题。
> 
> ### 当前程序版本
> 1.3.0
> 
> ### 问题类型
> 插件问题
> 
> ### 问题描述
> 目录监控插件配置转移方式异常
> 
> 插件配置 ![图片](https://user-images.githubusercontent.com/23021469/273712265-5acd0b92-2cad-43a2-b57e-22c461928f97.png)
> 
> 转移结果 ![图片](https://user-images.githubusercontent.com/23021469/273712413-c875d874-d72b-46a8-b470-c526244149e4.png)
> 
> 设置为move的并未移动，原文件还在 ![图片](https://user-images.githubusercontent.com/23021469/273712798-2360995f-72d5-4daa-b34c-7cdcb8a347b1.png)
> 
> ### 发生问题时系统日志和配置文件
> _No response_

监控目录:转移目的目录#转移方式

**Comment by mjsoftking** [comment]
@thsrite 改了#号是这样的错误
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/afffcce9-3b51-46d6-a5d1-20b4257703d7)

**Comment by mjsoftking** [comment]
@thsrite 更新测试版后转移成功，但是历史记录与源文件还是存在错误
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/44afd922-f279-4eb6-91de-97fef85b370e)

历史记录
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/bca15b7f-2c97-4208-a0a8-70d17e5d9bba)

使用的是move 移动模式，转移后源文件还存在
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/b81073cd-6258-451e-8ecd-3840af6e5a78)

**Comment by mjsoftking** [comment]
> @thsrite 更新测试版后转移成功，但是历史记录与源文件还是存在错误 ![图片](https://user-images.githubusercontent.com/23021469/273786470-44afd922-f279-4eb6-91de-97fef85b370e.png)
> ### 历史记录，不显示转移方式
> 
> ![图片](https://user-images.githubusercontent.com/23021469/273786545-bca15b7f-2c97-4208-a0a8-70d17e5d9bba.png)
> ### 使用的是 move 移动模式，转移后源文件还存在**
> 
> ![图片](https://user-images.githubusercontent.com/23021469/273786642-b81073cd-6258-451e-8ecd-3840af6e5a78.png)

@jxxghp 应该是处理转移的方法出现的问题，1：没记录转移方式，2：移动转移未删除源文件
