### ISSUE TITLE
[错误报告]: 豆瓣同步插件多ID只生效一个

### ISSUE THREAD

**Issue by Ailina0728** [jxxghp/MoviePilot#775]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.0

### 问题类型

插件问题

### 问题描述

豆瓣同步插件同时填写多个豆瓣ID，只能处理一个ID的想看，其他的ID无论怎么添加想看都无法同步，直接提示同步完成。日志中测试ID:227693177，始终无法正确同步

### 发生问题时系统日志和配置文件

```bash
INFO:    __init__.py - 豆瓣想看服务启动，立即运行一次
Pending jobs:
    豆瓣想看 (trigger: interval[0:30:00], pending)
    DoubanSync.sync (trigger: date[2023-10-10 13:14:47 CST], pending)
INFO:     192.168.10.99:0 - "PUT /api/v1/plugin/DoubanSync HTTP/1.1" 200 OK
INFO:     192.168.10.99:0 - "GET /api/v1/plugin/ HTTP/1.1" 200 OK
INFO:    __init__.py - 开始同步用户 227693177 的豆瓣想看数据 ...
INFO:     192.168.10.99:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1NTgxOTMsInN1YiI6IjEifQ.kBGpcNtfeimiTKqt5ZpbXBwE02GIqglw6gkt5eYb9AA HTTP/1.1" 200 OK
INFO:    __init__.py - 用户 227693177 豆瓣想看同步完成
INFO:    __init__.py - 开始同步用户 161609925 的豆瓣想看数据 ...
INFO:    __init__.py - 已超过同步天数，标题：三十二，发布时间：2023-01-15 08:52:00+00:00
INFO:    __init__.py - 用户 161609925 豆瓣想看同步完成
```

**Comment by jxxghp** [comment]
看日志程序是有处理的，打开这个键接看一下，会不会最近10条记录都不是影视动态：
https://www.douban.com/feed/people/用户编号/interests

**Comment by Ailina0728** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/24652865/6efcbaae-0262-439a-929d-376097ab00ac)
大佬我截取了一部分，是您说的这个意思么

**Comment by jxxghp** [comment]
只有想看的才处理，添加了日志打印，还有问题再贴日志重提。
