### ISSUE TITLE
[Feature Request]: 推荐板块中返回上一层功能

### ISSUE THREAD

**Issue by Ailina0728** [jxxghp/MoviePilot#779]
### 当前程序版本

1.3.0

### 功能改进类型

主程序

### 功能改进

推荐板块下，各项分类及其中资源点进去没有返回上一层按钮，想回到上一层只能点击推荐再重新进入对应分类或资源再次翻阅，所以应该添加一个返回按钮，点击回到上一层，分类中资源详情回到分类这样

**Comment by jxxghp** [comment]
浏览器的返回键，或者手机上左划。
