### ISSUE TITLE
请教微信回调地址怎么写，谢谢！

### ISSUE THREAD

**Issue by zraxx** [jxxghp/MoviePilot#78]
![Screenshot_2023-08-12-00-11-54-043_com.github.android.png](https://github.com/jxxghp/MoviePilot/assets/25578054/3d92b0f6-f54b-47f3-93d6-e7cee4a6ff7c)

**Comment by jxxghp** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/51039935/1ceda3c0-aa36-425b-a47f-36106e167bd4)

**Comment by HAN915** [comment]
具体要怎么写啊，没有这方面基础的，看不懂这个，最后就卡在这一步了我写的是http://1.1.1.1:1234/message/?token=1234，这样不行啊

**Comment by zraxx** [comment]
> 具体要怎么写啊，没有这方面基础的，看不懂这个，最后就卡在这一步了我写的是http://1.1.1.1:1234/message/?token=1234，这样不行啊

http://域名：端口号/api/v1/message

**Comment by HAN915** [comment]
> > 具体要怎么写啊，没有这方面基础的，看不懂这个，最后就卡在这一步了我写的是[http://1.1.1.1:1234/message/?token=1234，这样不行啊](http://1.1.1.1:1234/message/?token=1234%EF%BC%8C%E8%BF%99%E6%A0%B7%E4%B8%8D%E8%A1%8C%E5%95%8A)
> 
> [http://域名：端口号/api/v1/message](http://%E5%9F%9F%E5%90%8D%EF%BC%9A%E7%AB%AF%E5%8F%A3%E5%8F%B7/api/v1/message) 须有公网IP、一级域名、ip地址写到企业微信白名单

真是太感谢了，按这个格式终于搞定了
