### ISSUE TITLE
集数定位无法识别三位数

### ISSUE THREAD

**Issue by zero617** [jxxghp/MoviePilot#788]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.0-1

### 问题类型

主程序运行问题

### 问题描述

[Judas] Bleach - 100.mkv使用[Judas] Bleach - {ep}.mkv 无法识别集数

### 发生问题时系统日志和配置文件

```bash
WARNING	02:53:26,934	
__init__.py
文件 /mnt/Storage1/video/download/anime/[Judas] Bleach [BD 1080p][HEVC x265 10bit]/[Judas] Bleach - 100.mkv 转移失败：未识别到文件集数
WARNING	02:53:26,934	
transfer.py
[Judas] Bleach - 100.mkv 入库失败：未识别到文件集数
```

**Comment by AisukaYuki** [comment]
批量手动转移感觉不如正则方便，
\[Judas\].(Bleach).-.(.+\d) => \1 S01EP\2
填到自定义识别词里面试试
