### ISSUE TITLE
目录监控设置一对一转移，不增加一层一级目录

### ISSUE THREAD

**Issue by stephen909** [jxxghp/MoviePilot#792]
### 当前程序版本

1.3.0

### 功能改进类型

插件

### 功能改进

希望目录监控插件可以像nt一样，目录一对一设置后，媒体文件直接转移，不再添加电源/电视剧这一层一级目录。
非常感谢，目前只此唯一的功能还在用nastool。

### 参考资料

nastool
/media/downloads/收藏电影：/media/电影/收藏电影

**Comment by IITII** [comment]
关闭二级分类应该就行了

**Comment by IITII** [comment]
LIBRARY_PATH 
 ： 媒体库目录，多个目录使用,分隔
LIBRARY_MOVIE_NAME： 电影媒体库目录名称（不是完整路径），默认电影
LIBRARY_TV_NAME： 电视剧媒体库目录称（不是完整路径），默认电视剧
LIBRARY_ANIME_NAME： 动漫媒体库目录称（不是完整路径），默认电视剧/动漫

设置了吗?

**Comment by stephen909** [comment]
设置了，如下：
> LIBRARY_PATH=/media
> 
> LIBRARY_MOVIE_NAME=电影
> 
> LIBRARY_TV_NAME=电视剧
> 
> LIBRARY_ANIME_NAME=动画片

**Comment by berry8838** [comment]
我是直接

**Comment by ershouqingge** [comment]
LIBRARY_PATH=/media/电影/收藏电影
LIBRARY_MOVIE_NAME=/media/电影/收藏电影

LIBRARY_TV_NAME=/media/电影/收藏电影

LIBRARY_ANIME_NAME=/media/电影/收藏电影
