### ISSUE TITLE
[Feature Request]: 搜索框交互

### ISSUE THREAD

**Issue by IITII** [jxxghp/MoviePilot#793]
### 当前程序版本

v1.3.0

### 功能改进类型

主程序

### 功能改进

1. 希望搜索框加上 自动聚焦
   1. 因为现在的搜索框是点击后出现在屏幕中央的, 距离上稍微有点远, 加上 autoFocus 的话, 搜索起来更方便
3. 希望搜索框支持回车直接触发搜索，而不是点按钮

**Comment by jxxghp** [comment]
下个版本
