### ISSUE TITLE
[错误报告]: 企业微信配置失败, 回调日志http 307

### ISSUE THREAD

**Issue by Matzoh** [jxxghp/MoviePilot#795]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.1

### 问题类型

其他问题

### 问题描述

微信通知失败, 请问怎么争取配置
按照 nt 及 mp 的文档进行了配置, 使用了代理服务器 (nt 正常)
配置了 token, 回调路径也填了/api/v1/message

### 发生问题时系统日志和配置文件

```bash
企业微信回调添的:
http://mp-wechat.abc.xyz/api/v1/message?token=xxxx

nginx抓包: 
/api/v1/message?token=xxx&msg_signature=xxx&timestamp=1697025394&nonce=1696720932&echostr=xxx HTTP/1.1" 307 0 "-" "Mozilla/4.0"


server {
    listen 80;
    server_name  mp-wechat.abc.xyz;
    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        proxy_ssl_server_name on;
        proxy_pass https://mp.abc.xyz:8443;
    }

    location /cgi-bin/gettoken {
        proxy_pass https://qyapi.weixin.qq.com;
    }
    location /cgi-bin/message/send
    {
        proxy_pass https://qyapi.weixin.qq.com;
    }

    location /cgi-bin/menu/create {
        proxy_pass https://qyapi.weixin.qq.com;
    }
}
```
```

**Comment by whosneo** [comment]
README.md 中写的是`/api/v1/message/`，所以，你末尾少了个`/`，加上就正常了。
