### ISSUE TITLE
[错误报告]: 手动重新整理，出现“目录缺失nfo 数据”错误

### ISSUE THREAD

**Issue by Nothend** [jxxghp/MoviePilot#796]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.1

### 问题类型

主程序运行问题

### 问题描述

最新版本目录监控，手动整理了下，识别正常。但是日志中有提示：目录缺失nfo 数据。但是我进去目录有nfo 文件，emby 也刷新到了。
![ebd9f2222e893fc6dfd98e5a108d700](https://github.com/jxxghp/MoviePilot/assets/73117056/c158b2e1-2991-4143-9784-11e3c48637a9)

### 发生问题时系统日志和配置文件

```bash
ERROR 21:18:43338 init__py   /media/links/movie/华语电影/扬名立万(2021)/扬名立万(201080pmp4目录缺失nfo元数据

Info  21:19:13,341 init__py  媒体库中已存在:[MediaServerltem(id=None,server='emklibrary=None,item_id=208440item_type='Movie' title=original_title=None,year='2021tmdbid=None,imdbid=Ntvdbid=None,path=None,seasoninfo=None,note=Nonest mod date=None)]
```

**Comment by jxxghp** [comment]
CSF报的，同 #785
