### ISSUE TITLE
[错误报告]: 演职人员刮削插件是否需要额外设置或者前置条件？

### ISSUE THREAD

**Issue by yunzhongci** [jxxghp/MoviePilot#799]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.1

### 问题类型

插件问题

### 问题描述

INFO | 03:56:26,301 | __init__.py | 演职人员刮削服务启动，立即运行一次
-- | -- | -- | --
INFO | 03:56:29,301 | __init__.py | 开始刮削服务器 emby 的演员信息 ...
INFO | 03:56:29,301 | __init__.py | 服务器 emby 的演员信息刮削完成

在日志中提示演职人员刮削服务启动病情完成，但是在 emby 中并没有看到演职人员相关信息。
请问是需要映射对应文件夹吗？
我记得之前的演职人员插件有需要填写路径，现在的插件中没有这个选项了。
请问针对演职人员插件的启用，是否需要额外设置或者前置条件？

**Comment by yunzhongci** [comment]
<img width="893" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/49399931/d5e98cc2-1c7c-4b63-ae7e-78c633a32310">
请问这里对应 mp 容器内的映射路径是什么

**Comment by zraxx** [comment]
jellyfin媒体服务器，入库时插件运行不正常（在媒体库中不存在），插件运行一次功能时可正常刮削：日志如下：
开始刮削媒体库文件：/share/downloads2/media/电视剧/早间新闻 (2019)/Season 3/早间新闻 - S03E06 - 第 6 集.mkv ...
--
INFO | 11:03:25,993 | tmdbapi.py | 正在查询TMDB电视剧：90282，季：3 ...
INFO | 11:03:25,994 | scraper.py | 正在生成剧集NFO文件：早间新闻 - S03E06 - 第 6 集.mkv
INFO | 11:03:25,994 | scraper.py | NFO文件已保存：/share/downloads2/media/电视剧/早间新闻 (2019)/Season 3/早间新闻 - S03E06 - 第 6 集.nfo
INFO | 11:03:25,994 | scraper.py | 正在下载早间新闻 - S03E06 - 第 6 集图片：https://image.tmdb.org/t/p/original/lcPSpEzolEoePyWjNhaqO0LFLEZ.jpg ...
<html>
<body>


INFO | 11:03:27,418 | scraper.py | 图片已保存：/share/downloads2/media/电视剧/早间新闻 (2019)/Season 3/早间新闻 - S03E06 - 第 6 集.jpg
-- | -- | -- | --
INFO | 11:03:27,419 | __init__.py | /share/downloads2/media/电视剧/早间新闻 (2019)/Season 3/早间新闻 - S03E06 - 第 6 集.mkv 刮削完成
INFO | 11:03:27,436 | __init__.py | 发送消息：channel=None，title=早间新闻 (2019) S03 E06 已入库, text=评分：7.9，类型：电视剧，质量： WEB-DL DV 2160p，共1个文件，大小：9.87G，userid=None
INFO | 11:03:27,436 | command.py | 处理事件：notice.message - [<function MessageForward.send at 0x7f1493478e00>, <function WebHook.send at 0x7f1493274860>]
INFO | 11:03:28,044 | transfer.py | /share/downloads2/电视/The.Morning.Show.S03.2019.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.H.265-HHWEB/The.Morning.Show.S03E06.2019.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.H.265-HHWEB.mkv 转移完成，共 1 个文件，失败 0 个，跳过 0 个
INFO | 11:03:28,044 | command.py | 处理事件：transfer.complete - [<function ChineseSubFinder.download at 0x7f14933a1940>, <function PersonMeta.scrap_rt at 0x7f149347ade0>, <function WebHook.send at 0x7f1493274860>]
INFO | 11:03:28,046 | __init__.py | 通知ChineseSubFinder下载字幕: /media/电视剧/早间新闻 (2019)/Season 3/早间新闻 - S03E06 - 第 6 集.mkv
INFO | 11:03:28,089 | __init__.py | ChineseSubFinder任务添加成功：5ddb1e3e233a
INFO | 11:04:28,110 | __init__.py | 早间新闻 (2019) 文件系统已存在：{1: [4, 5, 1, 3, 2, 7, 6, 8, 9, 10], 2: [3, 1, 2, 5, 4, 6, 10, 7, 8, 9], 3: [1, 2, 3, 4, 5, 6]}
-- | -- | -- | --
WARNING | 11:04:28,110 | __init__.py | 演职人员刮削 早间新闻 (2019) 在媒体库中不存在

INFO | 11:10:08,132 | __init__.py | 演职人员刮削服务启动，立即运行一次
-- | -- | -- | --
INFO | 11:10:11,132 | __init__.py | 开始刮削服务器 jellyfin 的演员信息 ...
INFO | 11:10:11,138 | __init__.py | 开始刮削媒体库 电视 的演员信息 ...
INFO | 11:10:11,444 | __init__.py | 开始刮削 王朝 的演员信息 ...
INFO | 11:10:11,444 | tmdbapi.py | 正在查询TMDB电视剧：82953 ...
INFO | 11:10:11,445 | tmdbapi.py | 82953 查询结果：王朝
INFO | 11:10:11,445 | __init__.py | 82953 识别结果：电视剧 王朝 (2018)
INFO | 11:10:11,445 | tmdbapi.py | 正在获取剧集组年份：64d262dd549dda00e2dee678...
INFO | 11:10:11,457 | __init__.py | 王朝 的人物信息已是中文，无需更新

**Comment by jxxghp** [comment]
新片入库后才能刮削演员，可以调大入库延尽时间。
