### ISSUE TITLE
[Feature Request]: 优先级规则添加 60fps 高帧率 选项

### ISSUE THREAD

**Issue by likecreep** [jxxghp/MoviePilot#800]
### 当前程序版本

最新版本

### 功能改进类型

主程序

### 功能改进

优先级规则添加 60fps 高帧率 选项

### 参考资料

现在一些影视资源有60fps版本，想要优先下载

**Comment by jxxghp** [comment]
给几个种子命名示例看看

**Comment by likecreep** [comment]
> 给几个种子命名示例看看

[M-TEAM].[消失的她].Lost.in.the.Stars.2022.1080p.60fps.WEB-DL.HEVC.10bit.DDP5.1.Atmos.3Audios-QHstudIo.torrent

[M-TEAM].[独行月球].Moon.Man.2022.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.2Audios-QHstudIo.torrent

[M-TEAM].封神第一部：朝歌风云.Creation.of.the.Gods.Ⅰ.Kingdom.of.Storms.2023.2160p.HQ.WEB-DL.AAC.60fps.H.265-HDSWEB.torrent 

部分种子是在副标题里备注的
