### ISSUE TITLE
[错误报告]: mp自动刷新极空间，以前的电影消失

### ISSUE THREAD

**Issue by wangzhili888** [jxxghp/MoviePilot#801]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.1

### 问题类型

主程序运行问题

### 问题描述

mp重新整理文件后，发现极空间极影视里面的电影就剩刚整理的一部分电影，在极影视点重新获取，能将以前的电影获取出来，但是之前整理的合集全得重新整理。

### 发生问题时系统日志和配置文件

```bash
*
```

**Comment by jxxghp** [comment]
文件没被删除的话，跟MP没关系的吧，我又不调他接口。
