### ISSUE TITLE
[错误报告]: 下载目录制定不成功

### ISSUE THREAD

**Issue by cend1s** [jxxghp/MoviePilot#805]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.31

### 问题类型

主程序运行问题

### 问题描述

我将下载目录在Docker和配置文件中都做了修改，可再次下载文件时，用的还是不是制定的目录，为上一级目录。
![image](https://github.com/jxxghp/MoviePilot/assets/125641670/fd17c656-7cb0-4984-ba63-7cb926de0459)
![image](https://github.com/jxxghp/MoviePilot/assets/125641670/4202b6f7-aa82-4307-b100-42161d653d87)
![image](https://github.com/jxxghp/MoviePilot/assets/125641670/17b9c87d-8e77-4d20-bab2-7e4b9fd0d884)
![image](https://github.com/jxxghp/MoviePilot/assets/125641670/2873bd96-69ca-454a-ae44-9e693ac28043)

现在不知道为什么会发生这种情况。之前用“历史记录同步插件”进行了数据同步，不知道是否和这个有关。

### 发生问题时系统日志和配置文件

```bash
日志和系统中看不到现在制定的路径和配置文件读取情况。
```

**Comment by Whichbfj28** [comment]
你是不是开启了qb下载二级分类功能？
QB_CATEGORY=false

**Comment by jxxghp** [comment]
基础配置问题自己排查
