### ISSUE TITLE
[Feature Request]: 电影格式重命名增加指定语种标题

### ISSUE THREAD

**Issue by EraSun** [jxxghp/MoviePilot#813]
### 当前程序版本

1.3.2

### 功能改进类型

主程序

### 功能改进

希望电影重命名格式MOVIE_RENAME_FORMAT，能够支持重命名指定语种标题，比如{{en_title}}

**Comment by cng10001** [comment]
支持en_title标题蛤，毕竟站点列表上标题一般都是英文

**Comment by jxxghp** [comment]
v1.4.8-1
