### ISSUE TITLE
[错误报告]: win端部分插件如签到，刷流等插件运行提示错误。

### ISSUE THREAD

**Issue by Yustyn555** [jxxghp/MoviePilot#817]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.3.2-1

### 问题类型

插件问题

### 问题描述

插件无法运行，提示错误

### 发生问题时系统日志和配置文件

```bash
INFO	11:09:29,857	
__init__.py
开始检查刷流下载任务 ...
ERROR	11:09:29,857	
base.py
Job "站点刷流检查服务 (trigger: interval[0:05:00], next run at: 2023-10-13 11:14:29 CST)" raised an exception
INFO	11:16:07,754	
__init__.py
站点自动签到服务启动，立即运行一次
INFO	11:16:07,780	
__init__.py
站点自动签到服务启动，执行周期 0点-24点 每8小时执行一次
ERROR	11:16:10,776	
base.py
Job "站点自动签到 (trigger: date[2023-10-13 11:16:10 CST], next run at: 2023-10-13 11:16:10 CST)" raised an exception
```

**Comment by jxxghp** [comment]
@Yustyn555 暂不支持仿真
