### ISSUE TITLE
[Feature Request]: 请求电影剧集订阅编辑页面添加制作组选项

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#818]
### 当前程序版本

V1.3.2

### 功能改进类型

主程序

### 功能改进

感谢作者在最新版本的订阅编辑页面中添加了质量，分辨率，特效三个常用的选择，另外还希望能够添加一个制作组的选项，这个也是比较常用的，有的时候想只下载某个制作组的剧集，就不是很方便了，然后现在特效的话可以选择杜比视界，HDR，另外希望能增加SDR的选项，有的剧集观看设备不支持特效，下载SDR就够了，谢谢，希望作者能够采纳

**Comment by jxxghp** [comment]
@yellowstrong 制作组放包含里就行了，程序识别制任组没有关键字这么好使

**Comment by yellowstrong** [comment]
> @yellowstrong 制作组放包含里就行了，程序识别制任组没有关键字这么好使

收到！好的！
