### ISSUE TITLE
Unraid下,只能使用HOST网络模式才能进入WEBUI

### ISSUE THREAD

**Issue by insomnia417** [jxxghp/MoviePilot#82]
改用bridge或者用macvlan/ipvlan都打不开

**Comment by thsrite** [comment]
<img width="462" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/54088512/c511f3fd-0579-446a-b42a-75f8cabed24c">
<img width="873" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/54088512/4bb5f68e-4261-4d37-8cf9-694ada413db1">
访问地址。ip:3003

**Comment by insomnia417** [comment]
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/54088512/260196134-c511f3fd-0579-446a-b42a-75f8cabed24c.png"> <img alt="image" width="873" src="https://user-images.githubusercontent.com/54088512/260196152-4bb5f68e-4261-4d37-8cf9-694ada413db1.png"> 访问地址。ip:3003

只能用HOST , 我需要macvlan
