### ISSUE TITLE
[Feature Request]: MP给TR发送下载任务改进

### ISSUE THREAD

**Issue by gravitation-ch** [jxxghp/MoviePilot#820]
### 当前程序版本

1.3.1

### 功能改进类型

主程序

### 功能改进

MP给TR发送下载任务的时候，可以不包含下载路径吗？
因为我的MP是docker，TR是群晖套件
如果用docker的下载路径，TR不认得。如果用TR的下载路径，MP不认得。

**Comment by qhly2010** [comment]
下载保存目录设置成tr一样的路径就行

**Comment by gravitation-ch** [comment]
> 下载保存目录设置成tr一样的路径就行
 目录设置成TR，确实可以下载，但是一些插件就不认识这个路径。
能不能像之前nastool配置下载器的时候一样，有两个路径，一个是下载器的路径，一个是nastool可以识别的路径。

**Comment by gravitation-ch** [comment]
> 下载保存目录设置成tr一样的路径就行

目录设置成TR，确实可以下载，但是一些插件就不认识这个路径。
能不能像之前nastool配置下载器的时候一样，有两个路径，一个是下载器的路径，一个是nastool可以识别的路径。

**Comment by mjsoftking** [comment]
> > 下载保存目录设置成tr一样的路径就行
> 
> 目录设置成TR，确实可以下载，但是一些插件就不认识这个路径。 能不能像之前nastool配置下载器的时候一样，有两个路径，一个是下载器的路径，一个是nastool可以识别的路径。

使用目录监控，禁用下载监控，目录这么设置就可以

**Comment by gravitation-ch** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/129346715/db35eb82-2e3d-4742-badb-23738a7962bc)
像之前这样的设置是不是皆大欢喜？

**Comment by baichenxu06** [comment]
mp目录映射，/volume3/video:/volume3/video, #下载目录 DOWNLOAD_PATH=/volume3/video/downloads 。tr下载目录/volume3/video/downloads。这样mp和tr都识别，mq插件也识别
多盘干脆直接全映射根目录，如果下载目录修改，就要修改配置。选择目录监控，监控多个盘目录

**Comment by mjsoftking** [comment]
> mp目录映射，/volume3/video:/volume3/video, #下载目录 DOWNLOAD_PATH=/volume3/video/downloads 。tr下载目录/volume3/video/downloads。这样mp和tr都识别，mq插件也识别 多盘干脆直接全映射根目录，如果下载目录修改，就要修改配置。选择目录监控，监控多个盘目录

![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/8994069a-0c9a-4039-bc9a-ffe9a3d29207)
我是这么设置的，download的目录时文件管理直接打开对应位置，其余的会传递给qb去下载，qb和tr全都保持一致的下载路径

**Comment by gravitation-ch** [comment]
> /volume3/video:/volume3/video



> > mp目录映射，/volume3/video:/volume3/video, #下载目录 DOWNLOAD_PATH=/volume3/video/downloads 。tr下载目录/volume3/video/downloads。这样mp和tr都识别，mq插件也识别 多盘干脆直接全映射根目录，如果下载目录修改，就要修改配置。选择目录监控，监控多个盘目录
> 
> [![图片](https://user-images.githubusercontent.com/23021469/274812354-8994069a-0c9a-4039-bc9a-ffe9a3d29207.png)](javascript:void(0)) 我是这么设置的，download的目录时文件管理直接打开对应位置，其余的会传递给qb去下载，qb和tr全都保持一致的下载路径

我怎么没想到，这办法好，把路径原样映射一遍，感谢感谢
