### ISSUE TITLE
[Feature Request]: 馒头站点什么时候能支持啊

### ISSUE THREAD

**Issue by carolcoral** [jxxghp/MoviePilot#823]
### 当前程序版本

1.3.2-1

### 功能改进类型

其他

### 功能改进

很多资源都在馒头上，请问什么时候新增站点可以支持馒头啊

**Comment by jxxghp** [comment]
@carolcoral 一直都支持，.io域名

**Comment by mjsoftking** [comment]
使用馒头新域名，早就切换过来了

**Comment by carolcoral** [comment]
@jxxghp 好吧，我还一直用的 `.cc` 的域名
