### ISSUE TITLE
[错误报告]: 历史记录中删除历史记录、源文件和媒体库文件，需要对影片执行两次才能完全删除

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#826]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.3.2

### 问题类型

主程序运行问题

### 问题描述

如视频操作，不知其他选项是否有同样问题

https://github.com/jxxghp/MoviePilot/assets/34505611/ebf61505-0a78-4354-b223-2f3a7152e680

**Comment by jxxghp** [comment]
> 同issue反馈一下某聪明网站搜索问题，敢死队4这部电影资源，网站有4部不同的版本，MP只能搜出来一部，名称测试没问题 ![iShot_2023-10-13_16 47 41](https://user-images.githubusercontent.com/34505611/274849174-e7514ae2-22aa-48e6-b473-0992e6d71c8e.png) ![iShot_2023-10-13_16 48 21](https://user-images.githubusercontent.com/34505611/274849197-70018471-3401-4eb1-8fee-037f7d4168bd.png) ![iShot_2023-10-13_16 48 43](https://user-images.githubusercontent.com/34505611/274849382-3a312e7d-208d-4389-8a7f-c6e017941987.png) ![iShot_2023-10-13_16 50 28](https://user-images.githubusercontent.com/34505611/274849397-15b2cec2-0e89-436c-97b3-9826dc69d57f.png)

中文命名的问题，完整名称是：敢死队4：最终章，用中文搜到了就不会再用英文搜了。
