### ISSUE TITLE
订阅中的分辨率选项不起作用

### ISSUE THREAD

**Issue by dandkong** [jxxghp/MoviePilot#829]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.2-1

### 问题类型

主程序运行问题

### 问题描述

如图，指定了4k但还是下了1080的
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/3dabcc05-45ac-4cf4-af19-5a56a809e416)
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/2e951eff-dfae-416f-a521-2a854dcac29d)

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-13 20:00:32,784 - __init__.py - 乐队的夏天 识别结果：电视剧 乐队的夏天 (2019) 90756
【INFO】2023-10-13 20:00:32,800 - __init__.py - 乐队的夏天 (2019) 媒体库中已存在：{3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]}
【INFO】2023-10-13 20:00:32,801 - subscribe.py - 订阅 乐队的夏天 (2019) S03 缺失集：[19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
【INFO】2023-10-13 20:00:32,807 - __init__.py - 种子 憨憨 - The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB[新] 优先级为 2
【INFO】2023-10-13 20:00:32,807 - subscribe.py - 乐队的夏天 (2019) 匹配成功：The Big Band S03 2023 1080p WEB-DL H265 AAC-HHWEB[新]
【INFO】2023-10-13 20:00:32,808 - subscribe.py - 乐队的夏天 (2019) 匹配完成，共匹配到1个资源
【INFO】2023-10-13 20:00:36,761 - torrent.py - 解析种子：[HHC].乐队的夏天.The.Big.Band.S03.2023.1080p.WEB-DL.H265.AAC-HHWEB.torrent => 目录：乐队的夏天.The.Big.Band.S03.2023.1080p.WEB-DL.H265.AAC-HHWEB，文件清单：['The.Big.Band.S03E19.2023.1080p.WEB-DL.H265.AAC-HHWEB.mp4', 'The.Big.Band.S03E20.2023.1080p.WEB-DL.H265.AAC-HHWEB.mp4']
【INFO】2023-10-13 20:00:40,425 - __init__.py - 发送消息：channel=None，title=乐队的夏天 (2019) S03 E19-E20 开始下载, text=
```

**Comment by thsrite** [comment]
我也遇到一次，订阅选的1080
订阅页面点了下搜索
前面下载的都是1080，最后下载的是4k

因为演职人员刮削插件日志太多，没查日志
