### ISSUE TITLE
有的电影无法搜索

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#833]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.2-1

### 问题类型

主程序运行问题

### 问题描述

![1697217141186(1)](https://github.com/jxxghp/MoviePilot/assets/142991330/7f61ae88-7b2f-44ca-bb97-ec2a66df747f)
![1697217159713](https://github.com/jxxghp/MoviePilot/assets/142991330/f52a2261-bda3-45ce-bd8b-a9cd9a43a099)

**Comment by cng10001** [comment]
是不是网不好，我是这样的↓

https://github.com/jxxghp/MoviePilot/assets/115156545/dea70ff1-f7cf-41d0-80f3-b23d3c8c011c

**Comment by jxxghp** [comment]
<img width="505" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/359d2d5f-2123-4d3b-9bb9-e5e0fbe2c0a9">

**Comment by jxxghp** [comment]
<img width="657" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/a8f36086-31fa-41f4-9fce-617e62a3a9ad">
