### ISSUE TITLE
[Feature Request]: 希望识别历史记录可以增加筛选条件

### ISSUE THREAD

**Issue by ShunpingZhu** [jxxghp/MoviePilot#835]
### 当前程序版本

v1.3.1

### 功能改进类型

主程序

### 功能改进

希望识别记录可以增加筛选条件，比如说按照状态进行筛选，这样能够更快的识别出失败的记录以便进行手动识别

**Comment by lovesakuratears** [comment]
希望再加个搜索记录，可以快速筛选某部剧相关集数的记录筛选，以便直接全部选择该部剧集

**Comment by MichaelYXQ** [comment]
还建议增加在历史记录中进行目录跳转，点击历史记录可以直接跳转到对应的文件夹。
