### ISSUE TITLE
[错误报告]：在机器人添加下载，使用 自动选择下载时，不会采用优先级规则

### ISSUE THREAD

**Issue by likecreep** [jxxghp/MoviePilot#836]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.2-1

### 问题类型

主程序运行问题

### 问题描述

在机器人添加下载，使用 自动选择下载时，不会采用优先级规则选择合适的种子。

猜测可能原因是，机器人选择了分页展示搜索结果，而机器人的自动选择没有综合每一页的结果，只使用了当前页的结果。

**Comment by jxxghp** [comment]
第1条就是优先级最高的，输入0不是先下载排最前面的吗

**Comment by likecreep** [comment]
> 第1条就是优先级最高的，输入0不是先下载排最前面的吗

0确实是下载排最前面的。但是第1条不是优先级最高的，而是 做种数最多的

**Comment by jxxghp** [comment]
就是按整体优先级排序的呀，跟WEB界面搜索是同一个排序逻辑，贴出你的示例和规则证明一下看看。

**Comment by likecreep** [comment]
> 就是按整体优先级排序的呀，跟WEB界面搜索是同一个排序逻辑，贴出你的示例和规则证明一下看看。

比如搜索 情枭的黎明，在tg机器人的结果如下：
【情枭的黎明】共找到31条相关资源，请回复对应数字下载（0: 自动选择 p: 上一页 n: 下一页）
1.【馒头】[BluRay 1080p X264 BMDru] 7.84G 50% 306↑
2.【馒头】[BluRay 720p X264 BMDru] 3.85G 50% 123↑
3.【馒头】[BluRay UHD 2160p HEVC] 90.96G 50% 38↑
4.【馒头】[BluRay HDR UHD 2160p X265 10bit FRDS] 26.33G 50% 33↑
5.【馒头】[BluRay DIY UHD 2160p HEVC OurBits] 91.04G 50% 29↑
6.【馒头】[BluRay HDR UHD 2160p X265 10bit BeiTai] 21.04G 50% 17↑
7.【馒头】[BluRay 1080p VC1 CMCT] 41.35G 50% 16↑
8.【馒头】[BluRay DIY UHD 2160p HEVC HDHome] 92.28G 50% 14↑

最终自动选择下载了第一个 【馒头】[BluRay 1080p X264 BMDru] 7.84G 50% 306↑。 并不符合 4k remux > 1080p 的规则。

但是如果使用网页版的 订阅=》搜索自动下载， 下载的是 Carlito's Way 1993 2160p UHD BluRay REMUX HEVC DTS-X 7.1-PTer，符合优先级规则。 但是该种子如果在tg搜索的话，处于搜索结果的第二页第7条。

**Comment by likecreep** [comment]
> 就是按整体优先级排序的呀，跟WEB界面搜索是同一个排序逻辑，贴出你的示例和规则证明一下看看。

我懂了。 我之前只设置了订阅优先级，没有设置搜索优先级，原来需要分开设置。
