### ISSUE TITLE
[错误报告]: 当订阅影片后，点击搜索，有概率不会执行搜索却提示搜索完成

### ISSUE THREAD

**Issue by likecreep** [jxxghp/MoviePilot#840]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.2-1

### 问题类型

主程序运行问题

### 问题描述

当订阅影片后，点击搜索，有概率不会执行搜索，网页下方却提示搜索完成。 查看日志并没有执行搜索。 

另，建议新订阅影片后立即自动触发执行一次搜索。

**Comment by jxxghp** [comment]
请提供日志
