### ISSUE TITLE
[Feature Request]: 普通用户的仪表板订阅栏只有一项日历可以查看，是否能再添加电影和电视剧呢？

### ISSUE THREAD

**Issue by yanyisio** [jxxghp/MoviePilot#844]
### 当前程序版本

v1.3.2-1

### 功能改进类型

主程序

### 功能改进

作者大大好！
       普通用户的仪表板，订阅栏只有一项日历可以查看，是否能再添加电影和电视剧呢？
       谢谢！

**Comment by nathandingx** [comment]
大大，再加个动漫就更完美了！
