### ISSUE TITLE
[Feature Request]: 改进一下微信交互通知

### ISSUE THREAD

**Issue by mzj001** [jxxghp/MoviePilot#851]
### 当前程序版本

 v1.3.1

### 功能改进类型

插件

### 功能改进

开启“目录监控”这个插件，下载电视剧，入库通知频繁，希望能改成整部电视剧入库完成后通知一次。

### 参考资料

![微信图片_20231015104743](https://github.com/jxxghp/MoviePilot/assets/53402347/3b3d4862-8878-4ff2-ba87-ec1f2bf5781d)

**Comment by thsrite** [comment]
@mzj001 Qb开!qb后缀和临时目录啊，下载完统一处理
要不就用下载器监控

**Comment by mzj001** [comment]
> @mzj001 Qb开!qb后缀和临时目录啊，下载完统一处理 要不就用下载器监控

**Comment by mzj001** [comment]
> @mzj001 Qb开!qb后缀和临时目录啊，下载完统一处理 要不就用下载器监控
qb下载器开启!qb后缀和临时目录了的
![捕获](https://github.com/jxxghp/MoviePilot/assets/53402347/8de2feca-7ac2-451e-bf69-9037c84700d9)
