### ISSUE TITLE
[Feature Request]: 希望可以添加qb的分类

### ISSUE THREAD

**Issue by EdisonCh4n** [jxxghp/MoviePilot#854]
### 当前程序版本

1.3.1

### 功能改进类型

主程序

### 功能改进

希望可以通过mp传递qb的分类，就像nastool一样，最好可以支持多个qb，这样将刷流的和入库的影片分开

**Comment by jxxghp** [comment]
QB_CATEGORY： qbittorrent分类自动管理，true/false，默认false，开启后会将下载二级分类传递到下载器，由下载器管理下载目录，需要同步开启DOWNLOAD_CATEGORY
