### ISSUE TITLE
设置参数决定添加订阅后是否立即自动搜索一次

### ISSUE THREAD

**Issue by likecreep** [jxxghp/MoviePilot#855]
### 当前程序版本

1.3.2-1

### 功能改进类型

主程序

### 功能改进

增加配置选项，订阅新电影或者电视剧后，能够立即执行一次自动搜索，若资源存在则立即添加下载

**Comment by cng10001** [comment]
啊这~以前有反馈，能不能不要立即搜索，因为~还来不及编辑更多参数，所以现在软件设定是点击订阅后中间故意设置了一段缓冲时间

**Comment by likecreep** [comment]
> 啊这~以前有反馈，能不能不要立即搜索，因为还来不及编辑更多参数，所以现在软件设定是点击订阅后中间故意设置了一段缓冲时间

这样啊。大概缓冲时间多少呢。或者干脆设置一个缓冲时间的参数。值设置为0就立即搜索。

**Comment by dlovew** [comment]
> > 啊这~以前有反馈，能不能不要立即搜索，因为还来不及编辑更多参数，所以现在软件设定是点击订阅后中间故意设置了一段缓冲时间
> 
> 这样啊。大概缓冲时间多少呢。或者干脆设置一个缓冲时间的参数。值设置为0就立即搜索。

好像是两分钟完全不影响使用
