### ISSUE TITLE
[错误报告]: 手动整理下载电视剧目录不生成nfo文件

### ISSUE THREAD

**Issue by hn315** [jxxghp/MoviePilot#857]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.3

### 问题类型

主程序运行问题

### 问题描述

1、原来订阅下载《南风知我意》电视剧，全剧完成后入库
2、因我筛选条件设置的问题，有几集下载有问题，我就删除了历史记录，下载源目录、和整理硬连接媒体目录
3、我重新下载完结版，整理后发现媒体目录中没有像以前一样每一集都会有一个nfo文件
4、我再次删除历史记录、媒体库，手动在上载源目录整理，其他正常就是不出现nfo文件

<img width="400" alt="捕获" src="https://github.com/jxxghp/MoviePilot/assets/63461319/4b3da9ed-b659-426e-9039-ba5b41fac5f8">

<img width="735" alt="11" src="https://github.com/jxxghp/MoviePilot/assets/63461319/af034ff7-76fe-4f21-a6ec-4136c2a711b9">

<img width="721" alt="12" src="https://github.com/jxxghp/MoviePilot/assets/63461319/e9196b60-f3a3-4c04-a783-2e2c960e5160">

<img width="700" alt="13" src="https://github.com/jxxghp/MoviePilot/assets/63461319/e030884e-8652-48bc-93a9-2076bc392442">

**Comment by jxxghp** [comment]
你的网络一堆下载失败，先把网络搞通畅吧。，日志提示很明显了，测试能连通不代表稳定可用。
