### ISSUE TITLE
演职刮削插件，可否新增把演员图片下载本地 

### ISSUE THREAD

**Issue by hh0610** [jxxghp/MoviePilot#860]
### 当前程序版本

1.3.3

### 功能改进类型

主程序

### 功能改进

演职刮削插件，可否新增把演员图片下载本地

**Comment by dlovew** [comment]
不是已经下载了？

**Comment by hh0610** [comment]
> 不是已经下载了？

没有下载到本地啊jellyfin演员图片还是要手动识别才能显示图片

**Comment by dlovew** [comment]
不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放任务信息的文件夹下也能看到图片和人物信息的nfo文件！

**Comment by hh0610** [comment]
> 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！

你是怎么设置的，能说下吗

**Comment by dlovew** [comment]
> > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> 
> 你是怎么设置的，能说下吗

我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！

**Comment by hh0610** [comment]
> > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > 
> > 
> > 你是怎么设置的，能说下吗
> 
> 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！

我在jellyfin存放演员头像的文件夹中都没有找到图片

**Comment by hh0610** [comment]
> > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > 
> > 
> > 你是怎么设置的，能说下吗
> 
> 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！

你mp是用root用户启动的吗

**Comment by dlovew** [comment]
> > > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > > 
> > > 
> > > 你是怎么设置的，能说下吗
> > 
> > 
> > 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！
> 
> 我在jellyfin存放演员头像的文件夹中都没有找到图片

emby/config/metadata/people这是emby存放目录，jellyfin我不清楚，你可以看日志有没有下载记录，emby刮削有下载图片的记录，如下，
【INFO】2023-10-15 15:04:02,748 - tmdbapi.py - 正在获取人物详情：144586...
【INFO】2023-10-15 15:04:02,748 - __init__.py - 黄宗泽 从TMDB获取到中文名：黄宗泽
【INFO】2023-10-15 15:04:02,749 - __init__.py - 黄宗泽 从TMDB获取到中文描述
【INFO】2023-10-15 15:04:02,749 - __init__.py - 黄宗泽 从TMDB获取到图片：/o6RGUQXQRobk2PhoTc6zqpOC9yr.jpg
【INFO】2023-10-15 15:04:02,749 - __init__.py - 更新人物 黄宗泽 的图片：https://image.tmdb.org/t/p/original/o6RGUQXQRobk2PhoTc6zqpOC9yr.jpg
【INFO】2023-10-15 15:04:03,602 - __init__.py - 更新人物 黄宗泽 的信息：{'Name': '黄宗泽', 'ServerId': 'b3fd3723f418450098d6ca6da5a4ba6e', 'Id': '8037', 'Etag': '841cb095b261520ef4b9ae5d65201ecf', 'DateCreated': '2023-10-01T17:23:11.0000000Z', 'CanDelete': False, 'CanDownload': False, 'PresentationUniqueKey': '91a5e8d79e1a43a084446b8a5bad2b77', 'SortName': '黄宗泽', 'ForcedSortName': '黄宗泽', 'ExternalUrls': [{'Name': 'IMDb', 'Url': 'https://www.imdb.com/name/nm2350266'}, {'Name': 'TheMovieDb', 'Url': 'https://www.themoviedb.org/person/144586'}], 'Overview': '黄宗泽（Bosco Wong），1980年12月13日出生，香港男演员、歌手。\n\n1999年加入TVB成为合约艺人，2003年参演时装剧《冲上云霄》。2005年在《我师傅系黄飞鸿》中首次担正男主角，凭借古装剧《我的野蛮奶奶》夺得TVB万千星辉颁奖典礼“飞跃进步男艺员奖”；同年开始演唱动画与电视剧主题曲。2008年与东亚唱片公司签约，在香港十大劲歌金曲颁奖礼上夺得“最受欢迎男新人银奖”。\n\n2013年9月，凭借《好心作怪》获得星和无线电视大奖 “我最爱TVB男艺人”与“我最爱TVB荧幕情侣”奖，凭借《护花危情》获得星和无线电视大奖“我最爱TVB电视男角色”奖。 [1]  2014年11月23日，凭借《点金胜手》获得星和无线电视大奖“最喜爱TVB电视角色”奖。 [2]  11月25日，黄宗泽凭借《男人不可以穷》于第六届英国万像国际华语电影节颁奖典礼上获“最佳男主角“奖。', 'Taglines': [], 'PlayAccess': 'Full', 'RemoteTrailers': [], 'ProviderIds': {'tmdb': '144586', 'imdb': 'nm2350266'}, 'Type': 'Person', 'TagItems': [], 'UserData': {'PlaybackPositionTicks': 0, 'PlayCount': 0, 'IsFavorite': False, 'Played': False}, 'DisplayPreferencesId': 'b607178b0ac2f604a458d3d2363fdc83', 'PrimaryImageAspectRatio': 0.6666666666666666, 'ImageTags': {'Primary': '98edca261bdabb61cd89a3bed0c06996'}, 'BackdropImageTags': [], 'LockedFields': ['Name', 'Overview'], 'LockData': False}

**Comment by dlovew** [comment]
> > > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > > 
> > > 
> > > 你是怎么设置的，能说下吗
> > 
> > 
> > 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！
> 
> 你mp是用root用户启动的吗

不是，不过我emby，qb，mp都是同一用户，避免权限问题

**Comment by hh0610** [comment]
> > > > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > > > 
> > > > 
> > > > 你是怎么设置的，能说下吗
> > > 
> > > 
> > > 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！
> > 
> > 
> > 你mp是用root用户启动的吗
> 
> 不是，不过我emby，qb，mp都是同一用户，避免权限问题

Jellyfin/config/metadata/people这个是Jellyfin的演员图片路径

**Comment by hh0610** [comment]
> > > > > 不知道是jellyfin的问题还是你设置的问题，我用emby正常！在emby存放人物信息的文件夹下也能看到图片和人物信息的nfo文件！
> > > > 
> > > > 
> > > > 你是怎么设置的，能说下吗
> > > 
> > > 
> > > 我也没做什么特别设置，如果你刮削了但是图片不显示，你可以找找计划任务里有没有一个Scan Metadata Folder，运行一下试试！
> > 
> > 
> > 你mp是用root用户启动的吗
> 
> 不是，不过我emby，qb，mp都是同一用户，避免权限问题

试了好几遍还是不行用root权限一样不行

**Comment by hh0610** [comment]
已经找到问题.权限没有给够

**Comment by lovefan-fan** [comment]
> 已经找到问题.权限没有给够

不好意思，请问一下，我是docker部署的，这怎么解决呢

**Comment by Aqr-K** [comment]
@lovefan-fan docker部署，通过设置环境变量的 PUID 和 PGID 来控制，值给个0就好了
