### ISSUE TITLE
[错误报告]: 资源搜索界面做种人数大于1000时，显示错误

### ISSUE THREAD

**Issue by xuanqb** [jxxghp/MoviePilot#866]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.3

### 问题类型

主程序运行问题

### 问题描述

实际做种人数为1166 
<img width="1165" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/25526210/2627b984-8038-4bd5-ad75-30fffbd65a2e">

**Comment by jxxghp** [comment]
怀疑跟这个站点页面有关，种子列表中超过1000时的种子显示有什么不一样吗？ 我不知道这个图标是哪个站的。

**Comment by xuanqb** [comment]
> 怀疑跟这个站点页面有关，种子列表中超过1000时的种子显示有什么不一样吗？ 我不知道这个图标是哪个站的。

站点名是：朋友 
``` html
<a href="details.php?id=6399&amp;hit=1&amp;dllist=1#seeders">1,162</a>
```
<img width="1297" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/25526210/d29fe532-a485-4e51-9113-d347f536fcf5">

**Comment by xuanqb** [comment]
馒头一样也有问题
<img width="1920" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/25526210/912ebe4c-e52d-4b2b-9fb1-bae1382436fb">
<img width="1465" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/25526210/83d1ef22-b57c-453b-9ca8-7ab68ea51e82">

**Comment by Sebastian2333** [comment]
@jxxghp 作者你好,我现在用最新版1.6.7仍然存在这个问题,至少朋友和馒头两个站的种子,做种数一千以上会显示为0.

**Comment by Sebastian2333** [comment]
已经修复了,可以关闭issue了
