### ISSUE TITLE
朱雀站点未获取到token

### ISSUE THREAD

**Issue by zhangfan1231** [jxxghp/MoviePilot#869]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.3.3

### 问题类型

其他问题

### 问题描述

手动添加朱雀站点或者cookie同步朱雀站点，测试时都显示未获取到token，无法用mp在朱雀搜到任何数据，但实际站点有想要的数据。

### 发生问题时系统日志和配置文件

```bash
23:42:05,172	
torrents.py
开始获取站点 zhuque.in 最新种子 ...
WARNING	23:42:05,197	
tnode.py
朱雀 未获取到token，无法搜索
WARNING	23:42:05,198	
indexer
朱雀 未搜索到数据，耗时 0 秒
```

**Comment by zhangfan1231** [comment]
最后是通过手动添加朱雀站点，并且USER_AGENT使用app.env中的例子填写的，虽然测试不能通过，但是能搜索了。

**Comment by hbmask** [comment]
同样的问题，别人没这个问题，我有，我郁闷找了几天没能解决。。
