### ISSUE TITLE
[错误报告]: 定时作业时后台任务列表有时无

### ISSUE THREAD

**Issue by AilonHuang** [jxxghp/MoviePilot#870]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.3 之前的版本也有这个问题

### 问题类型

主程序运行问题

### 问题描述

定时作业时后台任务列表有时无
![image](https://github.com/jxxghp/MoviePilot/assets/18651361/5f67bb97-3045-4af2-945e-b4f94fb4961a)

**Comment by ershouqingge** [comment]
解决了吗  我的也是空的

**Comment by thsrite** [comment]
是否 app.env 里的DEV设置为了true，
如是改为false

**Comment by AilonHuang** [comment]
> 解决了吗 我的也是空的

解决了，按 thsrite 的方法，把dev设置为false
