### ISSUE TITLE
[错误报告]: 推荐 中 不显示库中已存在标志

### ISSUE THREAD

**Issue by mjsoftking** [jxxghp/MoviePilot#873]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.3

### 问题类型

主程序运行问题

### 问题描述

推荐 中 不显示库中已存在标志

![fbefa27d1266536055d7d161dcaeeba](https://github.com/jxxghp/MoviePilot/assets/23021469/088a2741-cbc0-4da6-8808-a3d88cb76cb2)

**Comment by dlovew** [comment]
先同步一下媒体库，再ctrl+f5强制刷新一下网页试试

**Comment by mjsoftking** [comment]
@dlovew 重启，更新媒体库，ctrl+f5都用了
