### ISSUE TITLE
建议分辨率【增加更多规则】

### ISSUE THREAD

**Issue by Whichbfj28** [jxxghp/MoviePilot#875]
### 当前程序版本

1.3.3

### 功能改进类型

主程序

### 功能改进

建议增加DVD、VCD、480P分辨率。老电影有的时候只有这种分辨率
建议增加排除4K、排除2160P分辨率规则。比如我这样的，只想安静在电视上看电影的，4K是纯属于多余的分辨率（或者只想在手机上看电影的话。1080P都是多余的分辨率】。但是现有条件下根本无法帅选。默认排除规则优先级低于订阅规则。

**Comment by Shurelol** [comment]
@Whichbfj28 包含排除里自己写正则

**Comment by Whichbfj28** [comment]
> @Whichbfj28 包含排除里自己写正则

建议看最后一句话。
以及：https://github.com/jxxghp/MoviePilot/issues/874
