### ISSUE TITLE
[错误报告]: 目录监控的媒体识别以电视剧类型进行识别

### ISSUE THREAD

**Issue by Nothend** [jxxghp/MoviePilot#877]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.3

### 问题类型

插件问题

### 问题描述

**新下载一个电影，（测试了三个电影）。开启目录监控，下载的时候微信推送的识别信息正确，入库的时候，却提示入库失败。看了下日志，目录监控 进行识别的时候，总是以电视剧进行识别。
失败之后，在历史记录中进行手动识别，目的路径必须是“/media/links” 而不能留空或者“/media/links/movie” ，否则提示路径错误。还必须清理缓存，否则目录监控已经错误识别过一次，手动整理还会以缓存中的进行识别**。
![image](https://github.com/jxxghp/MoviePilot/assets/73117056/0e548b53-dcee-46b2-81e7-2b29f4fe3819)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/dab891bd-330f-4953-8575-b41724ffab2e)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/a7199195-6dbe-43df-9c5c-41a8b807d686)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/e860ca17-a8ac-42fe-9b94-98550318e1ca)

**唯一成功的是《鬼子来了》**

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/637c9058-dac5-45e5-a567-2a455a898796)

### 配置文件如下：
`

SEARCH_SOURCE=themoviedb
SCRAP_METADATA=true
SCRAP_FOLLOW_TMDB=true
SCRAP_SOURCE=themoviedb
TMDB_IMAGE_DOMAIN=image.tmdb.org
TMDB_API_DOMAIN=api.themoviedb.org

DOWNLOADER=qbittorrent
DOWNLOADER_MONITOR=false
QB_HOST=10.0.0.6:8589
QB_USER=admin
QB_PASSWORD=888888
QB_CATEGORY=false

TORRENT_TAG=MOVIEPILOT
DOWNLOAD_PATH=/media/downloads
DOWNLOAD_MOVIE_PATH=/media/downloads/movie
DOWNLOAD_TV_PATH=/media/downloads/tv
DOWNLOAD_ANIME_PATH=
DOWNLOAD_CATEGORY=true
DOWNLOAD_SUBTITLE=true

MEDIASERVER=emby
REFRESH_MEDIASERVER=true
MEDIASERVER_SYNC_INTERVAL=6
MEDIASERVER_SYNC_BLACKLIST=
EMBY_HOST=10.0.0.6:8096
EMBY_API_KEY=8e1f654c71960515d

TRANSFER_TYPE=link
LIBRARY_PATH=/media/links
LIBRARY_MOVIE_NAME=movie
LIBRARY_TV_NAME=tv
LIBRARY_ANIME_NAME=
LIBRARY_CATEGORY=true
`

群晖中的目录：
![image](https://github.com/jxxghp/MoviePilot/assets/73117056/539065b7-09f8-479d-8115-93eead91a37f)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/20720278-ed60-4ab8-b4a4-f5f57103880f)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/c383bf25-c357-4301-840a-6b067dcb047c)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/fd87215d-86bf-4e11-92ed-1dd0dd963b86)

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-16 13:07:38,349 - torrent.py - 解析种子：[HDHome].穿条纹睡衣的男孩.The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS.torrent => 目录：穿条纹睡衣的男孩.The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS，文件清单：['The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS.mkv']
【INFO】2023-10-16 13:07:41,864 - chain - 发送消息：channel=None，title=穿条纹睡衣的男孩 (2008)  开始下载, text=
站点：家园
质量： BluRay 1080p
大小：7.18G
种子：The Boy in the Striped Pajamas 2008 BluRay 1080p x265 10bit DDP5.1 MNHD-FRDS
发布时间：2022-07-12 18:52:40
做种数：170
促销：普通
描述：【穿条纹睡衣的男孩/穿条纹衣的男孩/穿条纹衣服的男孩】简英/简中 双特效 繁中/繁英字幕，userid=None
【INFO】2023-10-16 13:07:41,864 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f3b46f33ba0>, <function WebHook.send at 0x7f3b46e877e0>]
【INFO】2023-10-16 13:07:42,428 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7f3b46e877e0>]
INFO:     172.17.0.1:0 - "POST /api/v1/download/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:0 - "GET /api/v1/system/logging?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgxMTY4MjQsInN1YiI6IjEifQ
INFO:     172.17.0.1:0 - "GET /api/v1/download/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:0 - "GET /api/v1/history/transfer?page=1&count=25&title= HTTP/1.1" 200 OK
【INFO】2023-10-16 13:11:09,184 - tmdbapi.py - 正在查询TMDB电视剧：14574 ...
【INFO】2023-10-16 13:11:09,835 - tmdbapi.py - 14574 查询结果：The Raggy Dolls
【INFO】2023-10-16 13:11:09,835 - themoviedb - The Boy In The Striped Pajamas 识别结果：电视剧 The Raggy Dolls (1986) 14574
【INFO】2023-10-16 13:11:10,185 - dirmonitor - The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS.mkv 识别为：电视剧 The Raggy Dolls (1986)
【WARNING】2023-10-16 13:11:10,977 - fanart - 没有获取到 The Raggy Dolls (1986) 的Fanart图片数据
【INFO】2023-10-16 13:11:10,978 - tmdbapi.py - 正在获取电视剧图片：14574...
【INFO】2023-10-16 13:11:11,323 - tmdbapi.py - 正在查询TMDB电视剧：14574，季：1 ...
【WARNING】2023-10-16 13:11:11,883 - filetransfer - 文件 /media/downloads/movie/外语电影/穿条纹睡衣的男孩.The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS/The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-16 13:11:11,884 - dirmonitor - The.Boy.in.the.Striped.Pajamas.2008.BluRay.1080p.x265.10bit.DDP5.1.MNHD-FRDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-16 13:11:12,166 - chain - 发送消息：channel=None，title=The Raggy Dolls (1986) 入库失败！, text=原因：未识别到文件集数，userid=None
```

**Comment by Nothend** [comment]
1.3.4 之后问题依然存在，如日志所示：

18:59:56,102	
torrent.py
解析种子：[HDHome].哈尔的移动城堡.Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.torrent => 目录：哈尔的移动城堡.Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS，文件清单：["Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv", 'cover.jpg', "Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.nfo"]
INFO	19:00:00,197	
chain
发送消息：channel=None，title=哈尔的移动城堡 (2004) 开始下载, text=
INFO	19:00:00,198	
command.py
处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]
INFO	19:00:00,524	
command.py
处理事件：download.added - [<function WebHook.send at 0x7f1006c87b00>]
INFO	19:02:36,187	
tmdbapi.py
正在查询TMDB电视剧：4935 ...
INFO	19:02:36,924	
tmdbapi.py
4935 查询结果：Roar
INFO	19:02:36,925	
themoviedb
Howl'S Moving Castle 识别结果：电视剧 Roar (1997) 4935
INFO	19:02:37,270	
dirmonitor
Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 识别为：电视剧 Roar (1997)
INFO	19:02:38,008	
tmdbapi.py
正在查询TMDB电视剧：4935，季：1 ...
WARNING	19:02:38,545	
filetransfer
文件 /media/downloads/movie/动画电影/哈尔的移动城堡.Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS/Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 转移失败：未识别到文件集数
WARNING	19:02:38,546	
dirmonitor
Howl's.Moving.Castle.2004.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 入库失败：未识别到文件集数
INFO	19:02:38,846	
chain
发送消息：channel=None，title=Roar (1997) 入库失败！, text=原因：未识别到文件集数，userid=None

**Comment by Nothend** [comment]
【INFO】2023-10-16 08:42:22,533 - search.py - 匹配完成，共匹配到 26 个资源
【INFO】2023-10-16 08:44:06,499 - torrent.py - 解析种子：[HDHome].龙猫.My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.torrent => 目录：龙猫.My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS，文件清单：['My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv', 'cover.jpg', 'My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.nfo']
【INFO】2023-10-16 08:44:10,946 - chain - 发送消息：channel=None，title=龙猫 (1988)  开始下载, text=
站点：家园
质量： BluRay 1080p
大小：5.07G
种子：My Neighbor Totoro 1988 BluRay 1080p x265 10bit 4Audio MNHD-FRDS
发布时间：2021-12-11 12:38:20
做种数：462
促销：普通
描述：【龙猫/邻家的豆豆龙/隔壁的特特罗】 Top 250 #130 宫崎骏作品 国粤英日四语 10bit HEVC版本，userid=None
【INFO】2023-10-16 08:44:10,946 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7fd0bdab1120>, <function WebHook.send at 0x7fd0bda18ae0>]
【INFO】2023-10-16 08:44:11,042 - tmdbapi.py - 正在查询TMDB电视剧：8392 ...
【INFO】2023-10-16 08:44:11,269 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7fd0bda18ae0>]
【INFO】2023-10-16 08:44:12,250 - tmdbapi.py - 8392 查询结果：大力水手
【INFO】2023-10-16 08:44:12,250 - themoviedb - My Neighbor Totoro 识别结果：电视剧 大力水手 (1960) 8392
【INFO】2023-10-16 08:44:12,589 - dirmonitor - My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 识别为：电视剧 大力水手 (1960)
【WARNING】2023-10-16 08:44:13,347 - fanart - 没有获取到 大力水手 (1960) 的Fanart图片数据
【INFO】2023-10-16 08:44:13,347 - tmdbapi.py - 正在获取电视剧图片：8392...
【INFO】2023-10-16 08:44:13,692 - tmdbapi.py - 正在查询TMDB电视剧：8392，季：1 ...
【WARNING】2023-10-16 08:44:14,718 - filetransfer - 文件 /media/downloads/movie/动画电影/龙猫.My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS/My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-16 08:44:14,718 - dirmonitor - My.Neighbor.Totoro.1988.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-16 08:44:15,191 - chain - 发送消息：channel=None，title=大力水手 (1960) 入库失败！, text=原因：未识别到文件集数，userid=None

**Comment by Nothend** [comment]
【INFO】2023-10-16 09:18:03,726 - torrent.py - 解析种子：[HDSky].UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS.torrent => 目录：UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS，文件清单：['UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS.mkv']
【INFO】2023-10-16 09:18:07,242 - chain - 发送消息：channel=None，title=飞屋环游记 (2009)  开始下载, text=
站点：天空
质量： BluRay 1080p
大小：8.09G
种子：UP 2009 1080p BluRay DTS 3Audio x264-HDS
发布时间：2015-10-01 18:52:20
做种数：21
促销：50%
描述：飞屋环游记/冲天救兵(港)/天外奇迹(台)/飞屋历险记 [国语台配/粤语配音/繁简英字幕][豆瓣TOP250补全计划NO.059]，userid=None
【INFO】2023-10-16 09:18:07,243 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7fd0bdab1120>, <function WebHook.send at 0x7fd0bda18ae0>]
【INFO】2023-10-16 09:18:07,513 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7fd0bda18ae0>]
【INFO】2023-10-16 09:18:14,448 - tmdbapi.py - 正在查询TMDB电视剧：14160 ...
【INFO】2023-10-16 09:18:15,709 - tmdbapi.py - 14160 查询结果：Tokyo Morning Express
【INFO】2023-10-16 09:18:15,709 - themoviedb - Up 识别结果：电视剧 Tokyo Morning Express 14160
【INFO】2023-10-16 09:18:16,124 - dirmonitor - UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS.mkv 识别为：电视剧 Tokyo Morning Express
【INFO】2023-10-16 09:18:16,124 - fanart - Tokyo Morning Express 没有tvdbid，无法获取Fanart图片
【INFO】2023-10-16 09:18:16,124 - tmdbapi.py - 正在获取电视剧图片：14160...
【INFO】2023-10-16 09:18:16,511 - tmdbapi.py - 正在查询TMDB电视剧：14160，季：1 ...
【WARNING】2023-10-16 09:18:17,482 - filetransfer - 文件 /media/downloads/movie/动画电影/UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS/UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-16 09:18:17,482 - dirmonitor - UP.2009.1080p.BluRay.DTS.3Audio.x264-HDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-16 09:18:17,797 - chain - 发送消息：channel=None，title=Tokyo Morning Express 入库失败！, text=原因：未识别到文件集数，userid=None

**Comment by Nothend** [comment]
【INFO】2023-10-17 07:11:40,871 - torrent.py - 解析种子：[HDHome].The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.torrent => 目录：The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH，文件清单：['The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.mkv', 'Cover.jpg', 'The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.nfo']
【INFO】2023-10-17 07:11:45,034 - chain - 发送消息：channel=None，title=钢琴家 (2002)  开始下载, text=
站点：家园
质量： BluRay REMUX UHD 2160p
大小：64.76G
种子：The Pianist 2002 2160p UHD Blu-ray REMUX HEVC DTS-HD MA5.1-HDH
发布时间：2023-09-30 22:58:51
做种数：60
促销：普通
描述：钢琴家/钢琴战曲(港)/战地琴人(台) | 内封官译简繁+简英繁英双语字幕，userid=None
【INFO】2023-10-17 07:11:45,034 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 07:11:45,595 - command.py - 处理事件：download.added - [<function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 07:59:53,099 - tmdbapi.py - 正在查询TMDB电视剧：423 ...
【INFO】2023-10-17 07:59:53,802 - tmdbapi.py - 423 查询结果：I Luv NY
【INFO】2023-10-17 07:59:53,803 - themoviedb - The Pianist 识别结果：电视剧 I Luv NY 423
【INFO】2023-10-17 07:59:54,149 - dirmonitor - The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.mkv 识别为：电视剧 I Luv NY
【INFO】2023-10-17 07:59:54,149 - fanart - I Luv NY 没有tvdbid，无法获取Fanart图片
【INFO】2023-10-17 07:59:54,150 - tmdbapi.py - 正在获取电视剧图片：423...
【INFO】2023-10-17 07:59:54,492 - tmdbapi.py - 正在查询TMDB电视剧：423，季：1 ...
【WARNING】2023-10-17 07:59:55,051 - filetransfer - 文件 /media/downloads/movie/外语电影/The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH/The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-17 07:59:55,051 - dirmonitor - The.Pianist.2002.2160p.UHD.Blu-ray.REMUX.HEVC.DTS-HD.MA5.1-HDH.mkv 入库失败：未识别到文件集数
【INFO】2023-10-17 07:59:55,593 - chain - 发送消息：channel=None，title=I Luv NY 入库失败！, text=原因：未识别到文件集数，userid=None
【INFO】2023-10-17 07:59:55,593 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]

**Comment by jxxghp** [comment]
识别错误可能是因为缓存导致，我测试是对的。清除缓存，再使用右上角识别功能进行测试。
<img width="843" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/cdbd2634-56e9-4f1b-a22f-4aacef8bfc2f">

**Comment by Nothend** [comment]
> 识别错误可能是因为缓存导致，我测试是对的。清除缓存，再使用右上角识别功能进行测试。 <img alt="image" width="843" src="https://user-images.githubusercontent.com/51039935/275782214-cdbd2634-56e9-4f1b-a22f-4aacef8bfc2f.png">

感谢楼主！确实清除缓存是可以的，但是每个电影下载之前都要清除缓存一次吗？我下载了上面多个电影，都是这种情况，第一部下载后我就清除缓存了，再下载还是同样的问题。之前也没搜索过，缓存是哪里来的啊？感谢啊！

**Comment by jxxghp** [comment]
@Nothend 我从未清除过缓存，但一直正常。你什么情况自己研究一下。

**Comment by Nothend** [comment]
> @Nothend 我从未清除过缓存，但一直正常。你什么情况自己研究一下。

谢谢楼主，我同步过nt的历史记录不知道是不是这个问题，实在不行就全新重装了。谢谢！

**Comment by FireGodson** [comment]
> a/links” 而不能留空或者“/media/links/movie” ，否则提示路径错误。还必须清理缓存，否则目录监控已经错误识别过一次，手动整理还会以缓存中的进行

我的也是这种情况，你重装后好了么，之前1.3.2 是好的

**Comment by Nothend** [comment]
> > a/links” 而不能留空或者“/media/links/movie” ，否则提示路径错误。还必须清理缓存，否则目录监控已经错误识别过一次，手动整理还会以缓存中的进行
> 
> 我的也是这种情况，你重装后好了么，之前1.3.2 是好的

重装不行我试过，要全新重装我明天试试

**Comment by FireGodson** [comment]
我也试过了不行，名称测试是好的，但是下载的在转移就识别成电视剧，不知道为啥

**Comment by Nothend** [comment]
> 我也试过了不行，名称测试是好的，但是下载的在转移就识别成电视剧，不知道为啥

全新安装，还不行？

**Comment by FireGodson** [comment]
> > 我也试过了不行，名称测试是好的，但是下载的在转移就识别成电视剧，不知道为啥
> 
> 全新安装，还不行？

嗯，不过我是windows版，你试一下吧
