### ISSUE TITLE
[错误报告]: 关于“刷流插件”刷不到人人人站。种子大小设置区间值，会刷不到该站种子。

### ISSUE THREAD

**Issue by z2561221** [jxxghp/MoviePilot#878]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.3

### 问题类型

插件问题

### 问题描述

关于“刷流插件”刷不到人人人站。种子大小设置区间值，会刷不到该站种子。
（之前提过issue，未找到问题所在点。目前找到问题，且能复现。）

设置种子大小区间 1-30 会一个种子都刷不到。

仅设置 30 就能正常刷到。但也能刷到38.3GB的种子(QB显示的大小)

**Comment by jxxghp** [comment]
人人人是什么站？

**Comment by z2561221** [comment]
![photo_2023-10-17_20-10-08](https://github.com/jxxghp/MoviePilot/assets/30318614/9b885c59-c1e0-4f41-aef6-1ec57f15b063)
![photo_2023-10-17_20-10-03](https://github.com/jxxghp/MoviePilot/assets/30318614/bd11cf01-7d62-4034-b9b5-ff58bc66e4ff)
下载到了超出设定得大小。。。

**Comment by jxxghp** [comment]
在站点浏览里面看一下这个站的种子大小显示这不正常，如果显示不正常，说明UI变了，看一下是不是有什么设置会改变种子列表的界面

**Comment by z2561221** [comment]
> 在站点浏览里面看一下这个站的种子大小显示这不正常，如果显示不正常，说明UI变了，看一下是不是有什么设置会改变种子列表的界面

还真是。网页设定恢复默认后，一切都正常了。刷流、站点浏览也是。 感谢~！
