### ISSUE TITLE
刷流排除HR

### ISSUE THREAD

**Issue by qiuyan81** [jxxghp/MoviePilot#880]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.2-1

### 问题类型

插件问题

### 问题描述

使用了刷流插件,今天看到学校站点有23个HR,能否把hr的排除掉?

**Comment by jxxghp** [comment]
@qiuyan81 识别hr要访问详情页，站点压力加大，不打算加。如果有的站点在列表也有HR标志的，请告知可以加。

**Comment by Whichbfj28** [comment]
可否增加规则。比如学校这种有HR的站点的话。做种时间强制不能低于多少。
其实我个人是不喜欢这样的。因为会让程序变的臃肿。

**Comment by AboutCXJ** [comment]
学校好像是全站hr，没有过滤的必要

**Comment by aliezguy** [comment]
> 识别hr要访问详情页，站点压力加大，不打算加。 如果有的站点在列表也有HR标志的，请告知可以加。

观众列表有HR标志,希望作者大大可以排除hr种子

**Comment by terryyj** [comment]
我堡在列表页面也有HR标志
