### ISSUE TITLE
[功能改进]: 建议把win版的nginx配置释放到程序根目录

### ISSUE THREAD

**Issue by youyifentian** [jxxghp/MoviePilot#884]
### 当前程序版本

v1.3.4

### 功能改进类型

主程序

### 功能改进

测试了一下win版的mp，有用到nginx，并且是程序自己打包后释放的，并且整到了临时目录，这样很容易有权限问题或者被杀软干掉，建议把nginx直接释放到config或者程序根目录下自动创建nginx目录
我在有的win11电脑上面测试就nginx无法成功释放运行，有个黑色命令窗口一闪而过，只有mp启动了，而导致无法打开webui，这个win11电脑上面安装过火绒，但是关闭了或者添加信任也无效，就是nginx一闪而过，但是如果把其他电脑上面程序正常释放的nginx复制过来，手动运行，程序就能起来，webui啥的一切正常，希望大佬考虑下！

**Comment by LeePhe** [comment]
复议！

**Comment by kklod** [comment]
我遇到一样的问题  应该是 #882

**Comment by aoerboquartz** [comment]
我擦，我好像碰到了和你一样的问题。
大佬
把其他电脑上面程序正常释放的nginx复制过来
这个nginx默认存放在哪个目录？
然后
手动运行
是如何运行？

**Comment by youyifentian** [comment]
> 我擦，我好像碰到了和你一样的问题。 大佬 把其他电脑上面程序正常释放的nginx复制过来 这个nginx默认存放在哪个目录？ 然后 手动运行 是如何运行？

随便放个位置，要把nginx整个文件复制除了，可以放到mp根目录下，直接双击nginx.exe即可，然后双击mp就行了

**Comment by Yustyn555** [comment]
非常认同
