### ISSUE TITLE
订阅的电视剧添加下载后，在下次rss订阅搜索之前未下载完毕，会触发重复下载。

### ISSUE THREAD

**Issue by ATMrunaway** [jxxghp/MoviePilot#885]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.4

### 问题类型

主程序运行问题

### 问题描述

正常订阅的电视剧发送到qb下载后，如果下载在下次rss订阅搜索前未完成，会再次触发下载，然后重复添加任务，提示添加任务失败。不知道为什么没有检测qb中正在下载当前的集数。
![IMG_3973](https://github.com/jxxghp/MoviePilot/assets/99494643/a5fb0e33-2d50-4f27-9771-3182c8a5df40)
![IMG_3972](https://github.com/jxxghp/MoviePilot/assets/99494643/adda0933-5e1a-4dfe-846b-94be7e424505)
![IMG_3971](https://github.com/jxxghp/MoviePilot/assets/99494643/a2799d7e-5818-4d02-b98b-ca138c640013)

**Comment by jxxghp** [comment]
提供日志，专门设计过来避免这种情况的。只要不重新添加订阅，已下载的会记录。

**Comment by MichaelYXQ** [comment]
我也遇到了同样的问题，会重复添加提示添加失败，直到媒体统计读取后存在剧集。日志只能下一次遇到后提供。暂时提供推送的消息，可以看一下时间差。

行尸走肉：达里尔·迪克森 (2023) S01 E06 开始下载
站点：彩虹岛
质量： WEB-DL 1080p
大小：2.04G
种子：The Walking Dead Daryl Dixon S01 1080p Stan WEB-DL DDP 5.1 H.264-CHDWEB
发布时间：2023-10-16 17:03:59
做种数：76
描述：美剧：行尸走肉：达里尔·迪克森 第一季 第06集 /行尸走肉：戴瑞·迪克森/行尸走肉：弩哥/行尸走肉衍生剧 | 剧情/恐怖..

MoviePilot [聊天机器人]17:58
添加下载任务失败：行尸走肉：达里尔·迪克森 (2023) S01 E06
站点：彩虹岛
种子名称：The Walking Dead Daryl Dixon S01 1080p Stan WEB-DL DDP 5.1 H.264-CHDWEB
错误信息：添加种子任务失败：/config/temp/[CHDBits].The.Walking.Dead.Daryl.Dixon.S01.1080p.Stan.WEB-DL.DDP.5.1.H.264-CHDWEB.torrent

**Comment by ATMrunaway** [comment]
> 提供日志，专门设计过来避免这种情况的。只要不重新添加订阅，已下载的会记录。

这是截图那次的日志，后面还重复下载过

【INFO】2023-10-16 19:49:44,416 - subscribe.py - 开始匹配订阅，标题：虎鹤妖师录 ...
【INFO】2023-10-16 19:49:44,417 - themoviedb - 虎鹤妖师录 使用识别缓存：虎鹤妖师录
【INFO】2023-10-16 19:49:44,418 - tmdbapi.py - 正在查询TMDB电视剧：235589 ...
【INFO】2023-10-16 19:49:44,418 - tmdbapi.py - 235589 查询结果：虎鹤妖师录
【INFO】2023-10-16 19:49:44,419 - themoviedb - 虎鹤妖师录 识别结果：电视剧 虎鹤妖师录 (2023) 235589
【INFO】2023-10-16 19:49:44,436 - emby - 虎鹤妖师录 (2023) 媒体库中已存在：{1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]}
【INFO】2023-10-16 19:49:44,437 - subscribe.py - 订阅 虎鹤妖师录 (2023) S01 缺失集：[32, 33, 34, 35, 36, 29, 30, 31]
【INFO】2023-10-16 19:49:44,463 - filter - 种子 憨憨 - Tiger and Crane S01 2023 2160p WEB-DL H265 AAC-HHWEB[虎鹤妖师录 | 第29-36集 | 4K  | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] 优先级为 11
【INFO】2023-10-16 19:49:44,464 - subscribe.py - 虎鹤妖师录 (2023) 匹配成功：Tiger and Crane S01 2023 2160p WEB-DL H265 AAC-HHWEB[虎鹤妖师录 | 第29-36集 | 4K  | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青]
【INFO】2023-10-16 19:49:44,528 - filter - 种子 憨憨 - Tiger and Crane S01 2023 1080p WEB-DL H264 AAC-HHWEB[虎鹤妖师录 | 第29-36集 | 1080p  | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] 优先级为 27
【INFO】2023-10-16 19:49:44,529 - subscribe.py - 虎鹤妖师录 (2023) 匹配成功：Tiger and Crane S01 2023 1080p WEB-DL H264 AAC-HHWEB[虎鹤妖师录 | 第29-36集 | 1080p  | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青]
【INFO】2023-10-16 19:49:44,552 - filter - 种子 憨憨 - Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] 优先级为 9
【INFO】2023-10-16 19:49:44,553 - subscribe.py - 虎鹤妖师录 (2023) 匹配成功：Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青]
【INFO】2023-10-16 19:49:44,578 - filter - 种子 高清杜比 - Tiger Crane 2023 S01E29-E30 2160p WEB-DL HEVC DDP5.1 & AAC-QHstudIo[虎鹤妖师录【第29-30集】【4K+杜比环绕】【主演：蒋龙.张凌赫.王玉雯.陈宥维.叶青】QHstudIo小组作品] 优先级为 11
【INFO】2023-10-16 19:49:44,579 - subscribe.py - 虎鹤妖师录 (2023) 匹配成功：Tiger Crane 2023 S01E29-E30 2160p WEB-DL HEVC DDP5.1 & AAC-QHstudIo[虎鹤妖师录【第29-30集】【4K+杜比环绕】【主演：蒋龙.张凌赫.王玉雯.陈宥维.叶青】QHstudIo小组作品]
【INFO】2023-10-16 19:49:44,648 - filter - 种子 高清杜比 - Tiger Crane 2023 S01E29-E30 1080p WEB-DL AVC DDP5.1 & AAC-QHstudIo[虎鹤妖师录【第29-30集】【杜比环绕】【主演：蒋龙.张凌赫.王玉雯.陈宥维.叶青】QHstudIo小组作品] 优先级为 27
【INFO】2023-10-16 19:49:44,648 - subscribe.py - 虎鹤妖师录 (2023) 匹配成功：Tiger Crane 2023 S01E29-E30 1080p WEB-DL AVC DDP5.1 & AAC-QHstudIo[虎鹤妖师录【第29-30集】【杜比环绕】【主演：蒋龙.张凌赫.王玉雯.陈宥维.叶青】QHstudIo小组作品]
【INFO】2023-10-16 19:49:44,649 - subscribe.py - 虎鹤妖师录 (2023) 匹配完成，共匹配到5个资源
【INFO】2023-10-16 19:49:50,667 - torrent.py - 解析种子：[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent => 目录：虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB，文件清单：['Tiger.and.Crane.S01E29.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E30.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E31.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E32.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E33.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E34.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E35.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E36.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv']
【ERROR】2023-10-16 19:49:50,673 - download.py - 虎鹤妖师录 (2023) 添加下载任务失败：Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] - https://hhanclub.top/download.php?id=63077&downhash=17155%7CRnrr，添加种子任务失败：/config/temp/[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent
【INFO】2023-10-16 19:49:50,674 - chain - 发送消息：channel=None，title=添加下载任务失败：虎鹤妖师录 (2023) S01 E29-E36, text=站点：憨憨
种子名称：Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青]
错误信息：添加种子任务失败：/config/temp/[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent，userid=None
【INFO】2023-10-16 19:49:50,674 - command.py - 处理事件：notice.message - []
【INFO】2023-10-16 19:49:54,302 - torrent.py - 解析种子：[DBY].[虎鹤妖师录].Tiger.Crane.2023.S01.2160p.WEB-DL.HEVC.DDP5.1.&.AAC-QHstudIo.torrent => 目录：[虎鹤妖师录].Tiger.Crane.2023.S01.2160p.WEB-DL.HEVC.DDP5.1.&.AAC-QHstudIo，文件清单：['[虎鹤妖师录].Tiger.Crane.2023.S01E30.2160p.WEB-DL.HEVC.DDP5.1.&.AAC-QHstudIo.mp4', '[虎鹤妖师录].Tiger.Crane.2023.S01E29.2160p.WEB-DL.HEVC.DDP5.1.&.AAC-QHstudIo.mp4']
【INFO】2023-10-16 19:49:57,449 - chain - 发送消息：channel=None，title=虎鹤妖师录 (2023) S01 E29-E30 开始下载, text=
站点：高清杜比
质量： WEB-DL 2160p
大小：4.1G
种子：Tiger Crane 2023 S01E29-E30 2160p WEB-DL HEVC DDP5.1 & AAC-QHstudIo[虎鹤妖师录【第29-30集】【4K+杜比环绕】【主演：蒋龙.张凌赫.王玉雯.陈宥维.叶青】QHstudIo小组作品]
发布时间：2023-10-16 19:14:31，userid=None
【INFO】2023-10-16 19:49:57,449 - command.py - 处理事件：notice.message - []
【INFO】2023-10-16 19:49:57,661 - command.py - 处理事件：download.added - []
【INFO】2023-10-16 19:50:04,129 - torrent.py - 解析种子：[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent => 目录：虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB，文件清单：['Tiger.and.Crane.S01E29.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E30.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E31.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E32.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E33.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E34.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E35.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E36.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv']
【INFO】2023-10-16 19:50:04,135 - download.py - 憨憨 - Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] 解析文件集数：[32, 33, 34, 35, 36, 29, 30, 31]
【INFO】2023-10-16 19:50:04,136 - download.py - 憨憨 - Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] 选中集数：{32, 33, 34, 35, 36, 31}
【INFO】2023-10-16 19:50:04,139 - torrent.py - 解析种子：[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent => 目录：虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB，文件清单：['Tiger.and.Crane.S01E29.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E30.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E31.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E32.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E33.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E34.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E35.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv', 'Tiger.and.Crane.S01E36.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.mkv']
【ERROR】2023-10-16 19:50:04,146 - download.py - 虎鹤妖师录 (2023) 添加下载任务失败：Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青] - https://hhanclub.top/download.php?id=63077&downhash=17155%7CRnrr，添加种子任务失败：/config/temp/[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent
【INFO】2023-10-16 19:50:04,147 - chain - 发送消息：channel=None，title=添加下载任务失败：虎鹤妖师录 (2023) S01 E29-E36, text=站点：憨憨
种子名称：Tiger and Crane S01 2023 2160p WEB-DL H265 HDR DDP5.1-HHWEB[虎鹤妖师录 | 第29-36集 | 4K HDR | 类型: 悬疑/奇幻/古装 | 导演: 郭虎 | 主演: 蒋龙/张凌赫/王玉雯/陈宥维/叶青]
错误信息：添加种子任务失败：/config/temp/[HHC].虎鹤妖师录.Tiger.and.Crane.S01.2023.2160p.WEB-DL.H265.HDR.DDP5.1-HHWEB.torrent，userid=None

**Comment by MichaelYXQ** [comment]
我也遇到了同样的问题，会重复添加提示添加失败，直到媒体统计读取后存在剧集。日志只能下一次遇到后提供。暂时提供推送的消息，可以看一下时间差。

行尸走肉：达里尔·迪克森 (2023) S01 E06 开始下载
站点：彩虹岛
质量： WEB-DL 1080p
大小：2.04G
种子：The Walking Dead Daryl Dixon S01 1080p Stan WEB-DL DDP 5.1 H.264-CHDWEB
发布时间：2023-10-16 17:03:59
做种数：76
描述：美剧：行尸走肉：达里尔·迪克森 第一季 第06集 /行尸走肉：戴瑞·迪克森/行尸走肉：弩哥/行尸走肉衍生剧 | 剧情/恐怖..

MoviePilot [聊天机器人]17:58
添加下载任务失败：行尸走肉：达里尔·迪克森 (2023) S01 E06
站点：彩虹岛
种子名称：The Walking Dead Daryl Dixon S01 1080p Stan WEB-DL DDP 5.1 H.264-CHDWEB
错误信息：添加种子任务失败：/config/temp/[CHDBits].The.Walking.Dead.Daryl.Dixon.S01.1080p.Stan.WEB-DL.DDP.5.1.H.264-CHDWEB.torrent

**Comment by jxxghp** [comment]
@MichaelYXQ 看一下日志前后有没有锁库的信息，database is locked

**Comment by ATMrunaway** [comment]
> @MichaelYXQ 看一下日志前后有没有锁库的信息，database is locked

我的日志里查询不到有locked


![image](https://github.com/jxxghp/MoviePilot/assets/99494643/4d8d6f86-e020-4a21-b823-78a44e3bf671)

**Comment by jxxghp** [comment]
@ATMrunaway 有没有这个：This session is provisioning a new conection;

**Comment by ATMrunaway** [comment]
> @ATMrunaway 有没有这个：This session is provisioning a new conection;

也没有。。。

![image](https://github.com/jxxghp/MoviePilot/assets/99494643/c7b96bb3-ac9b-43cc-98fb-48d2389063c3)
