### ISSUE TITLE
请问一下，我转移影片时提示这个是什么问题？ 运行模块 recognize_media 出错

### ISSUE THREAD

**Issue by snow61520** [jxxghp/MoviePilot#887]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.3.3

### 问题类型

Docker或运行环境问题

### 问题描述

INFO | 22:43:46,860 | transfer.py | 手动转移：/downloads/before/Fall.2022.2160p.BluRay.x265.10bit.Atmos.TrueHD7.1-WiKi ...
-- | -- | -- | --
INFO | 22:43:46,920 | themoviedb | Fall 使用识别缓存：Fall
INFO | 22:43:46,920 | tmdbapi.py | 正在查询TMDB电影：1091068 ...
INFO | 22:43:50,152 | tmdbapi.py | 1091068 查询结果：Fall
ERROR | 22:43:50,158 | chain | 运行模块 recognize_media 出错：TheMovieDbModule - 'str' object has no attribute 'items'
WARNING | 22:43:50,158 | transfer.py | /downloads/before/Fall.2022.2160p.BluRay.x265.10bit.Atmos.TrueHD7.1-WiKi/Fall.2022.2160p.BluRay.x265.10bit.Atmos.TrueHD7.1-WiKi.mkv 未识别到媒体信息
INFO | 22:43:50,236 | chain | 发送消息：channel=None，title=Fall.2022.2160p.BluRay.x265.10bit.Atmos.TrueHD7.1-WiKi.mkv 未识别到媒体信息，无法入库！
INFO | 22:43:50,237 | command.py | 处理事件：notice.message - []

**Comment by cng10001** [comment]
梯子不行吧

**Comment by snow61520** [comment]
> 梯子不行吧

用这个还需要梯子吗，我之前用nastool没问题，连通性测试也没啥问题

**Comment by cng10001** [comment]
mp不需要梯子，但是大陆联通themoviedb是需要梯子的，上面写 未识别到媒体信息 大概率连通性不好哦- -

**Comment by snow61520** [comment]
> mp不需要梯子，但是大陆联通themoviedb是需要梯子的，上面写 未识别到媒体信息 大概率连通性不好哦- -

很奇怪的地方是，我有一些电影能识别，但是部分不能识别，同一个时间点

**Comment by snow61520** [comment]
> mp不需要梯子，但是大陆联通themoviedb是需要梯子的，上面写 未识别到媒体信息 大概率连通性不好哦- -

我用tinyMediaManager，都能识别出来
