### ISSUE TITLE
[错误报告]: 历史记录中手动整理，提示None目标目录不存在。历史记录和文件管理中的【手动整理】效果不一致。

### ISSUE THREAD

**Issue by Nothend** [jxxghp/MoviePilot#890]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.4

### 问题类型

主程序运行问题

### 问题描述

下载的电影，目录监控转移失败（因为目录监控将电影识别为电视剧，所以手动清空缓存，识别没有问题了），但是历史记录中手动整理，提示None目标目录不存在。如下图

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/0f53167e-841c-4d64-83ab-fea3ad59b66a)

但是！！！ 在文件管理中，找到电影所在位置，进行手动整理，却可以正确转移。我看下两个对话框是一样的，里面填的内容完全一样默认，结果却不一样。不知是何原因：如下图
![image](https://github.com/jxxghp/MoviePilot/assets/73117056/e73028c8-cb41-4489-be12-9eeae4c1e124)

**个人配置如下：**
`

SEARCH_SOURCE=themoviedb
SCRAP_METADATA=true
SCRAP_FOLLOW_TMDB=true
SCRAP_SOURCE=themoviedb
TMDB_IMAGE_DOMAIN=image.tmdb.org
TMDB_API_DOMAIN=api.themoviedb.org

DOWNLOADER=qbittorrent
DOWNLOADER_MONITOR=false
QB_HOST=10.0.0.6:8589
QB_USER=admin
QB_PASSWORD=888888
QB_CATEGORY=false

TORRENT_TAG=MOVIEPILOT
DOWNLOAD_PATH=/media/downloads
DOWNLOAD_MOVIE_PATH=/media/downloads/movie
DOWNLOAD_TV_PATH=/media/downloads/tv
DOWNLOAD_ANIME_PATH=
DOWNLOAD_CATEGORY=true
DOWNLOAD_SUBTITLE=true

MEDIASERVER=emby
REFRESH_MEDIASERVER=true
MEDIASERVER_SYNC_INTERVAL=6
MEDIASERVER_SYNC_BLACKLIST=
EMBY_HOST=10.0.0.6:8096
EMBY_API_KEY=8e1f654c71960515d

TRANSFER_TYPE=link
LIBRARY_PATH=/media/links
LIBRARY_MOVIE_NAME=movie
LIBRARY_TV_NAME=tv
LIBRARY_ANIME_NAME=
LIBRARY_CATEGORY=true
`

群晖中的目录：

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/82bda6a9-1b7c-49da-8385-0e691746f7c1)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/2421b9a8-1fd8-47f6-9cd6-ea01195d393e)

![image](https://github.com/jxxghp/MoviePilot/assets/73117056/60f9c42b-cadc-4113-baa8-c06f82df0773)

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-17 08:51:29,272 - transfer.py - 手动转移：/media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv ...
【INFO】2023-10-17 08:51:29,273 - themoviedb - Kung Fu Hustle 使用识别缓存：The Penthouse Club
【INFO】2023-10-17 08:51:29,273 - tmdbapi.py - 正在查询TMDB电视剧：9470 ...
【INFO】2023-10-17 08:51:29,273 - tmdbapi.py - 9470 查询结果：The Penthouse Club
【INFO】2023-10-17 08:51:29,273 - themoviedb - Kung Fu Hustle 识别结果：电视剧 The Penthouse Club 9470
【INFO】2023-10-17 08:51:29,274 - transfer.py - [功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 识别为：电视剧 The Penthouse Club
【INFO】2023-10-17 08:51:29,274 - fanart - The Penthouse Club 没有tvdbid，无法获取Fanart图片
【INFO】2023-10-17 08:51:29,274 - tmdbapi.py - 正在获取电视剧图片：9470...
【INFO】2023-10-17 08:51:29,274 - tmdbapi.py - 正在查询TMDB电视剧：9470，季：1 ...
【WARNING】2023-10-17 08:51:29,275 - transfer.py - [功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 入库失败：None 目标路径不存在
【INFO】2023-10-17 08:51:30,048 - chain - 发送消息：channel=None，title=The Penthouse Club  入库失败！, text=原因：None 目标路径不存在，userid=None
【INFO】2023-10-17 08:51:30,049 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 08:51:30,342 - transfer.py - /media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 转移完成，共 1 个文件，失败 1 个，跳过 0 个
【INFO】2023-10-17 08:54:05,319 - wechat - 收到微信事件：userid=LiPengGuo, event=/clear_cache
【INFO】2023-10-17 08:54:05,383 - message.py - 收到用户消息内容，用户：LiPengGuo，内容：/clear_cache
【INFO】2023-10-17 08:54:05,383 - command.py - 处理事件：command.excute - [<function Command.command_event at 0x7f100a87a2a0>, <function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 08:54:05,384 - command.py - 用户 LiPengGuo 开始执行：清理缓存 ...
【INFO】2023-10-17 08:54:05,464 - chain - 发送消息：channel=MessageChannel.Wechat，title=缓存清理完成！, text=None，userid=LiPengGuo
【INFO】2023-10-17 08:54:05,822 - command.py - 用户 LiPengGuo 清理缓存 执行完成
【INFO】2023-10-17 08:54:05,823 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 08:54:29,299 - transfer.py - 开始删除文件以及空目录：None ...
【INFO】2023-10-17 08:54:29,299 - transfer.py - 手动转移：/media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv ...
【INFO】2023-10-17 08:54:29,300 - themoviedb - 正在识别 Kung Fu Hustle ...
【INFO】2023-10-17 08:54:30,012 - tmdbapi.py - 正在查询TMDB电影：9470 ...
【INFO】2023-10-17 08:54:30,660 - tmdbapi.py - 9470 查询结果：功夫
【INFO】2023-10-17 08:54:30,660 - themoviedb - Kung Fu Hustle 识别结果：电影 功夫 (2004) 9470
【INFO】2023-10-17 08:54:30,661 - transfer.py - [功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 识别为：电影 功夫 (2004)
【WARNING】2023-10-17 08:54:31,500 - transfer.py - [功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 入库失败：None 目标路径不存在
【INFO】2023-10-17 08:54:32,014 - chain - 发送消息：channel=None，title=功夫 (2004)  入库失败！, text=原因：None 目标路径不存在，userid=None
【INFO】2023-10-17 08:54:32,015 - command.py - 处理事件：notice.message - [<function MessageForward.send at 0x7f1006ccc040>, <function WebHook.send at 0x7f1006c87b00>]
【INFO】2023-10-17 08:54:32,274 - transfer.py - /media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 转移完成，共 1 个文件，失败 1 个，跳过 0 个
【INFO】2023-10-17 09:03:24,968 - transfer.py - 手动转移：/media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv ...
【INFO】2023-10-17 09:03:24,970 - themoviedb - Kung Fu Hustle 使用识别缓存：功夫
【INFO】2023-10-17 09:03:24,970 - tmdbapi.py - 正在查询TMDB电影：9470 ...
【INFO】2023-10-17 09:03:24,971 - tmdbapi.py - 9470 查询结果：功夫
【INFO】2023-10-17 09:03:24,971 - themoviedb - Kung Fu Hustle 识别结果：电影 功夫 (2004) 9470
【INFO】2023-10-17 09:03:24,971 - transfer.py - [功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 识别为：电影 功夫 (2004)
【INFO】2023-10-17 09:03:24,989 - filetransfer - 正在转移文件：/media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 到 /media/links/movie/华语电影/功夫 (2004)/功夫 (2004) - 1080p.mkv
【INFO】2023-10-17 09:03:25,007 - filetransfer - 文件 /media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv link完成
【INFO】2023-10-17 09:03:25,008 - filetransfer - 文件 /media/downloads/movie/华语电影/功夫.2004.1080p.国粤双语.简繁中字￡CMCT旧梦/[功夫].Kung.Fu.Hustle.2004.BluRay.1080p.x264.DTS.2Audios-CMCT.mkv 转移成功
【INFO】2023-10-17 09:03:25,816 - themoviedb - 开始刮削媒体库文件：/media/links/movie/华语电影/功夫 (2004)/功夫 (2004) - 1080p.mkv ...
```

**Comment by jxxghp** [comment]
重现不了这个情况。
1、你试一下清除下浏览器缓存看看，正常在整理界面的目的路径都是会带入历史记录中的值的，但你上面是空白的。
2、另外试一下选每条记录右边的三个点下拉的重新整理菜单试试，看是不是一样的问题。

**Comment by Nothend** [comment]
> 重现不了这个情况。 1、你试一下清除下浏览器缓存看看，正常在整理界面的目的路径都是会带入历史记录中的值的，但你上面是空白的。 2、另外试一下选每条记录右边的三个点下拉的重新整理菜单试试，看是不是一样的问题。

谢谢指导，浏览器缓存清理、更换浏览器、换了个电脑，都试了。并且，我就是用的历史记录中每条记录的三个点中的重新整理，然后目的路径留空，其他默认。 依然是同样的情况。但是如果使用【文件管理】中的【重新整理】却可以成功。

**Comment by jxxghp** [comment]
你处理的这条历史记录完整截图看一下

**Comment by Nothend** [comment]
> 你处理的这条历史记录完整截图看一下

![f8cc6e1a36e602590f9ff90cb127fa2](https://github.com/jxxghp/MoviePilot/assets/73117056/42980462-2c1d-4a98-9deb-8cd54cb4abd1)

![0a6a9c8b5e27a077e58b57e1c4ca024](https://github.com/jxxghp/MoviePilot/assets/73117056/b2c96017-af18-478b-91cf-26b3903fcdb8)

**Comment by jxxghp** [comment]
> > 你处理的这条历史记录完整截图看一下
> 
> ![f8cc6e1a36e602590f9ff90cb127fa2](https://user-images.githubusercontent.com/73117056/275729655-42980462-2c1d-4a98-9deb-8cd54cb4abd1.png)
> 
> ![0a6a9c8b5e27a077e58b57e1c4ca024](https://user-images.githubusercontent.com/73117056/275729687-b2c96017-af18-478b-91cf-26b3903fcdb8.png)

这两条是重新整理时生成的吧？最开始那条截一下。

**Comment by Nothend** [comment]
> > > 你处理的这条历史记录完整截图看一下
> > 
> > 
> > ![f8cc6e1a36e602590f9ff90cb127fa2](https://user-images.githubusercontent.com/73117056/275729655-42980462-2c1d-4a98-9deb-8cd54cb4abd1.png)
> > ![0a6a9c8b5e27a077e58b57e1c4ca024](https://user-images.githubusercontent.com/73117056/275729687-b2c96017-af18-478b-91cf-26b3903fcdb8.png)
> 
> 这两条是重新整理时生成的吧？最开始那条截一下。

![4c1889be1fd70140da380521b002156](https://github.com/jxxghp/MoviePilot/assets/73117056/e2965cde-72fa-4724-b99f-4a64e348a761)

最开始是这样的，识别错误

**Comment by Nothend** [comment]
> 你处理的这条历史记录完整截图看一下

【文件整理】中的【重新整理】可以正常使用

![4dd6d497a26564f79e2836261b8aa16](https://github.com/jxxghp/MoviePilot/assets/73117056/fcc18b90-eb9c-4fe8-8311-12293ab37441)

![8d0943a50256f11d5d88f74db569ceb](https://github.com/jxxghp/MoviePilot/assets/73117056/f6e4e0a2-a9d2-40b1-916a-456e794f3dbc)
