### ISSUE TITLE
[Feature Request]: 入库时候能不能增加“转移文件的大小限制”

### ISSUE THREAD

**Issue by gravitation-ch** [jxxghp/MoviePilot#892]
### 当前程序版本

1.3.4

### 功能改进类型

插件

### 功能改进

目录监控入库时候能不能增加“转移文件的大小限制”，这样的话避免一些sample，steam之类的小文件也入库了。

**Comment by mjsoftking** [comment]
![图片](https://github.com/jxxghp/MoviePilot/assets/23021469/c76a5cb8-5d88-4939-9b3d-32156a0a8454)

添加这个就可以

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/31412273-b4da-4657-80d4-fe672a8e0840)
除了上面说到的屏蔽词，点整理的时候有大小限制的设置的啊，不知道楼主说的是不是这个

**Comment by cng10001** [comment]
光文件整理这一块就感觉好复杂，我感觉要等多几个版本再更新了~
