### ISSUE TITLE
目录监控  把电影识别成电视剧

### ISSUE THREAD

**Issue by FireGodson** [jxxghp/MoviePilot#899]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

win版1.3.4

### 问题类型

主程序运行问题

### 问题描述

同样的配置和电影，在1.3.2能正确识别，1.3.3和1.3.4都会识别成电视剧，通过右上角名称测试可以正确识别， 但是如果直接下载，在通过目录监控插件识别的话就会识别成电视剧。

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-17 19:56:19,839 - tmdbapi.py - 正在查询TMDB电视剧：81481 ...
【INFO】2023-10-17 19:56:20,870 - tmdbapi.py - 81481 查询结果：L'Été Rouge
【INFO】2023-10-17 19:56:20,872 - themoviedb - Silenced 识别结果：电视剧 L'Été Rouge (2002) 81481
【INFO】2023-10-17 19:56:21,340 - dirmonitor - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 识别为：电视剧 L'Été Rouge (2002)
【WARNING】2023-10-17 19:56:22,400 - fanart - 没有获取到 L'Été Rouge (2002) 的Fanart图片数据
【INFO】2023-10-17 19:56:22,402 - tmdbapi.py - 正在获取电视剧图片：81481...
【INFO】2023-10-17 19:56:22,860 - tmdbapi.py - 正在查询TMDB电视剧：81481，季：1 ...
【WARNING】2023-10-17 19:56:23,978 - filetransfer - 文件 D:\video\熔炉.Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS\Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-17 19:56:23,979 - dirmonitor - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-17 19:56:23,989 - chain - 发送消息：channel=None，title=L'Été Rouge (2002) 入库失败！, text=原因：未识别到文件集数，userid=None



【INFO】2023-10-17 21:25:11,478 - media.py - 开始识别媒体信息，标题：Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS，副标题： ...
【INFO】2023-10-17 21:25:11,494 - themoviedb - 正在识别 Silenced ...
【INFO】2023-10-17 21:25:12,153 - tmdbapi.py - 正在查询TMDB电影：86707 ...
【INFO】2023-10-17 21:25:12,951 - tmdbapi.py - 86707 查询结果：Hiljaisuus
【INFO】2023-10-17 21:25:12,951 - tmdbapi.py - 正在查询TMDB电影：110962 ...
【INFO】2023-10-17 21:25:13,221 - tmdbapi.py - 110962 查询结果：La Fin du silence
【INFO】2023-10-17 21:25:13,221 - tmdbapi.py - 正在查询TMDB电影：81481 ...
【INFO】2023-10-17 21:25:13,632 - tmdbapi.py - 81481 查询结果：熔炉
【INFO】2023-10-17 21:25:13,633 - themoviedb - Silenced 识别结果：电影 熔炉 (2011) 81481
【INFO】2023-10-17 21:25:13,633 - media.py - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS 识别到媒体信息：电影 熔炉 (2011)
```

**Comment by FireGodson** [comment]
刚又试了一下docker版好使，win版就无法识别，上面的docker的日志，下面的是window的。都是同时识别的
【INFO】2023-10-17 14:08:25,718 - themoviedb - 正在识别 To Live ...
【INFO】2023-10-17 14:08:26,510 - tmdbapi.py - 正在查询TMDB电影：674346 ...
【INFO】2023-10-17 14:08:27,126 - tmdbapi.py - 674346 查询结果：摇滚中国乐势力1994年香港红磡演唱会
【INFO】2023-10-17 14:08:27,151 - tmdbapi.py - 正在查询TMDB电影：570036 ...
【INFO】2023-10-17 14:08:27,277 - tmdbapi.py - 570036 查询结果：葉山宏治＆ブラザーズ LIVE６連発スペシャル
【INFO】2023-10-17 14:08:27,290 - tmdbapi.py - 正在查询TMDB电影：504361 ...
【INFO】2023-10-17 14:08:27,459 - tmdbapi.py - 504361 查询结果：王菲 最精彩的演唱會
【INFO】2023-10-17 14:08:27,459 - tmdbapi.py - 正在查询TMDB电影：31719 ...
【INFO】2023-10-17 14:08:27,719 - tmdbapi.py - 31719 查询结果：Billy Connolly Live 1994
【INFO】2023-10-17 14:08:27,722 - tmdbapi.py - 正在查询TMDB电影：76992 ...
【INFO】2023-10-17 14:08:27,876 - tmdbapi.py - 76992 查询结果：La bella vita
【INFO】2023-10-17 14:08:27,877 - tmdbapi.py - 正在查询TMDB电影：773309 ...
【INFO】2023-10-17 14:08:28,168 - tmdbapi.py - 773309 查询结果：Les noms n'habitent nulle part
【INFO】2023-10-17 14:08:28,168 - tmdbapi.py - 正在查询TMDB电影：250642 ...
【INFO】2023-10-17 14:08:28,300 - tmdbapi.py - 250642 查询结果：新边缘人
【INFO】2023-10-17 14:08:28,300 - tmdbapi.py - 正在查询TMDB电影：810930 ...
【INFO】2023-10-17 14:08:28,378 - tmdbapi.py - 810930 查询结果：Whitney Houston Live：Concert For A New South Africa
【INFO】2023-10-17 14:08:28,378 - tmdbapi.py - 正在查询TMDB电影：716576 ...
【INFO】2023-10-17 14:08:28,573 - tmdbapi.py - 716576 查询结果：Babylon: la paura è la migliore amica dell'uomo
【INFO】2023-10-17 14:08:28,573 - tmdbapi.py - 正在查询TMDB电影：31439 ...
【INFO】2023-10-17 14:08:28,774 - tmdbapi.py - 31439 查询结果：活着
【INFO】2023-10-17 14:08:28,780 - themoviedb - To Live 识别结果：电影 活着 (1994) 31439
【INFO】2023-10-17 14:08:28,780 - dirmonitor - To.Live.1994.JPN.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 识别为：电影 活着 (1994)


【INFO】2023-10-17 22:08:10,485 - tmdbapi.py - 正在查询TMDB电视剧：31439 ...
【INFO】2023-10-17 22:08:11,364 - tmdbapi.py - 31439 查询结果：If I Can Dream
【INFO】2023-10-17 22:08:11,364 - themoviedb - To Live 识别结果：电视剧 If I Can Dream (2010) 31439
【INFO】2023-10-17 22:08:11,758 - dirmonitor - To.Live.1994.JPN.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 识别为：电视剧 If I Can Dream (2010)
【WARNING】2023-10-17 22:08:11,986 - fanart - 没有获取到 If I Can Dream (2010) 的Fanart图片数据
【INFO】2023-10-17 22:08:11,987 - tmdbapi.py - 正在获取电视剧图片：31439...
【INFO】2023-10-17 22:08:12,316 - tmdbapi.py - 正在查询TMDB电视剧：31439，季：1 ...
【WARNING】2023-10-17 22:08:13,423 - filetransfer - 文件 D:\video\活着.To.Live.1994.JPN.BluRay.1080p.x265.10bit.MNHD-FRDS\To.Live.1994.JPN.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-17 22:08:13,424 - dirmonitor - To.Live.1994.JPN.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-17 22:08:13,434 - chain - 发送消息：channel=None，title=If I Can Dream (2010) 入库失败！, text=原因：未识别到文件集数，userid=None

**Comment by jxxghp** [comment]
有文件名时，会优先使用文件名，所以测试你要使用这个名字去测：Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv

我测的也是对的，你清下缓存看看：

<img width="826" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/f78ac6b8-68a9-45bc-aaf9-8ac6ee365110">

**Comment by jxxghp** [comment]
<img width="834" alt="image" src="https://github.com/jxxghp/MoviePilot/assets/51039935/ff6eae34-cf25-4865-a612-757a578336ad">

**Comment by FireGodson** [comment]
大佬你是不是用的是docker版啊，我的是win版。win版，我试了用名称识别是正确的，但要如果清除缓存后直接下载用目录监控插件就会识别成电视剧，如果用docker版下载的也是能正确识别的真是奇怪了，下面日志上面的win版，下面的是docker的
【INFO】2023-10-18 14:30:59,276 - tmdbapi.py - 正在查询TMDB电视剧：81481 ...
【INFO】2023-10-18 14:30:59,932 - tmdbapi.py - 81481 查询结果：L'Été Rouge
【INFO】2023-10-18 14:30:59,935 - themoviedb - Silenced 识别结果：电视剧 L'Été Rouge (2002) 81481
【INFO】2023-10-18 14:31:00,208 - dirmonitor - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 识别为：电视剧 L'Été Rouge (2002)
【INFO】2023-10-18 14:31:00,211 - tmdbapi.py - 正在获取电视剧图片：81481...
【WARNING】2023-10-18 14:31:06,814 - fanart - 没有获取到 L'Été Rouge (2002) 的Fanart图片数据
【INFO】2023-10-18 14:31:06,817 - tmdbapi.py - 正在查询TMDB电视剧：81481，季：1 ...
【WARNING】2023-10-18 14:31:07,644 - filetransfer - 文件 D:\video\熔炉.Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS\Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 转移失败：未识别到文件集数
【WARNING】2023-10-18 14:31:07,644 - dirmonitor - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 入库失败：未识别到文件集数
【INFO】2023-10-18 14:31:07,653 - chain - 发送消息：channel=None，title=L'Été Rouge (2002) 入库失败！, text=原因：未识别到文件集数，userid=None


【INFO】2023-10-18 14:31:01,050 - themoviedb - 正在识别 Silenced ...
【INFO】2023-10-18 14:31:01,602 - tmdbapi.py - 正在查询TMDB电影：86707 ...
【INFO】2023-10-18 14:31:02,216 - tmdbapi.py - 86707 查询结果：Hiljaisuus
【INFO】2023-10-18 14:31:02,217 - tmdbapi.py - 正在查询TMDB电影：110962 ...
【INFO】2023-10-18 14:31:02,567 - tmdbapi.py - 110962 查询结果：La Fin du silence
【INFO】2023-10-18 14:31:02,567 - tmdbapi.py - 正在查询TMDB电影：81481 ...
【INFO】2023-10-18 14:31:02,668 - tmdbapi.py - 81481 查询结果：熔炉
【INFO】2023-10-18 14:31:02,669 - themoviedb - Silenced 识别结果：电影 熔炉 (2011) 81481
【INFO】2023-10-18 14:31:02,669 - dirmonitor - Silenced.2011.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv 识别为：电影 熔炉 (2011)
