### ISSUE TITLE
自定义RSS插件“动作”没有正确保存

### ISSUE THREAD

**Issue by dandkong** [jxxghp/MoviePilot#904]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.4

### 问题类型

主程序运行问题

### 问题描述

我前两天设置RSS插件动作为“下载”，但今天发现动作会变成空并添加了订阅，看代码可能是因为没有保存相关变量
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/8b0ba5f9-c5e2-4a9d-b1e9-e2f34e3d98f2)
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/a25e69ef-7728-4a08-97ff-f4c434a9b4e7)
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/a14e41a8-4981-41b8-a09b-61348599253f)
![image](https://github.com/jxxghp/MoviePilot/assets/31849833/5e0484a8-ff4c-4afe-a6fc-ba6c1a15e04b)

### 发生问题时系统日志和配置文件

```bash
暂无
```

**Comment by jxxghp** [comment]
多来几个看代码提问的人就好啦
