### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by xzshow** [jxxghp/MoviePilot#905]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

 v1.3.4

### 问题类型

主程序运行问题

### 问题描述

[错误报告]:我用PVE下安装UBUNtu系统下，使用DOCKER安装MP，然后乌班图一个MEDIA挂载192.168.100.20群晖下的MEDIA目录（下面有DOWNLOAD和电影 ，电视，动画目录），同时在DOCKER下将MEDFIA映射到MP的MEDIA目录，启动什么一切正常，MEDIA下面的所有文件在MP的文件管理 中也能看到，但出现 问题，在启动目录监控情况（LINK方式） 下，如果在MP中修改文件名，群晖和乌班图文件名也发生变化 ，目录监控也会以整理，但如果群晖中加入电影或者修改电影名，乌班图和MP中的文件名也会发生变化，但目录监控不转移，但我手动整理这个文件可以转移，如果我启动目录监控中立即运行一次也会整理文件。（直接用LXC安装DOCKER也是一个情况，同样配置如果群晖安装一切正常）不知道这是不是BUG，望大佬指导或者 处理

### 发生问题时系统日志和配置文件

```bash
目录启动，在群晖中修改或者 加入文件，没有日志发生
```

**Comment by jxxghp** [comment]
话说监控模式里面有性能模式和兼容模式两个选项，有没有想过调整一下？
对于网络挂载的，很多情况下都是没有文件事件的。

**Comment by jxxghp** [comment]
另外，如果操作系统的监控文件句柄数不足，再启动的时候也会报错，要看启动时的日志。

**Comment by xzshow** [comment]
我谢大佬 提醒 ，我一直是兼容模式，我再试下子

**Comment by xzshow** [comment]
好像可以了，我一直是性能模式，自己傻B搞了一天，就没改这个，装了十几次系统，感谢大佬 ，再测试下子

**Comment by xzshow** [comment]
谢谢大佬 ，好像可以，就是有点慢

**Comment by xzshow** [comment]
监控文件句柄数不足这个是啥子 意思，大佬
