### ISSUE TITLE
[错误报告]: 不论添加什么站点都显示站点不支持

### ISSUE THREAD

**Issue by SkySlity** [jxxghp/MoviePilot#910]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.4

### 问题类型

主程序运行问题

### 问题描述

不论添加什么站点都显示站点不支持，馒头，hdfans什么都试了下不行

**Comment by ddgocl** [comment]
你好,我也是同样的问题,mteam和岛都不行
