### ISSUE TITLE
[Feature Request]: 增强历史记录模块功能

### ISSUE THREAD

**Issue by gzxiexl** [jxxghp/MoviePilot#913]
### 当前程序版本

V1.3.4

### 功能改进类型

主程序

### 功能改进

1、增加筛选功能，比如筛选出状态为失败的记录，便于重新整理；
2、搜索增加对“目录”列内容的搜索，比如我需要对具体路径的文件重新整理。

**Comment by ThierryCheng** [comment]
筛选失败记录需求+1

**Comment by fengtion11** [comment]
筛选失败记录需求+2
