### ISSUE TITLE
目录监控插件无法监控挂载到本地的网盘目录

### ISSUE THREAD

**Issue by 757321061** [jxxghp/MoviePilot#920]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.4

### 问题类型

主程序运行问题

### 问题描述

目录监控插件无法监控挂载到本地的网盘目录
网盘目录新增更新的视频，他不自动转移。可以增加一个定时功能吗。定时检测。

**Comment by thsrite** [comment]
兼容模式

**Comment by 757321061** [comment]
> 兼容模式

感谢  已解决
