### ISSUE TITLE
豆瓣反复订阅问题

### ISSUE THREAD

**Issue by c77187326** [jxxghp/MoviePilot#923]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.5

### 问题类型

主程序运行问题

### 问题描述

昨天豆瓣添加了一部电视剧，反复通知订阅，时间间隔为30分钟。
![IMG_20231020_064340](https://github.com/jxxghp/MoviePilot/assets/51660545/6555238b-bde5-4309-af28-c0b2a48a317a)

### 发生问题时系统日志和配置文件
WARNING】2023-10-20 01:34:12,458 - search.py - 叠影狙击 没有符合优先级规则的资源
【WARNING】2023-10-20 01:34:12,458 - doubansync - 叠影狙击 (2023) 未搜索到资源
【INFO】2023-10-20 01:34:12,459 - subscribe.py - 开始添加订阅，标题：叠影狙击 ...
【INFO】2023-10-20 01:34:12,461 - themoviedb - 叠影狙击 使用识别缓存：叠影狙击
【INFO】2023-10-20 01:34:12,461 - tmdbapi.py - 正在查询TMDB电视剧：236726 ...
【INFO】2023-10-20 01:34:12,463 - tmdbapi.py - 236726 查询结果：叠影狙击
【INFO】2023-10-20 01:34:12,464 - themoviedb - 叠影狙击 识别结果：电视剧 叠影狙击 (2023) 236726
【INFO】2023-10-20 01:34:12,465 - fanart - 叠影狙击 (2023) 没有tvdbid，无法获取Fanart图片
【INFO】2023-10-20 01:34:12,465 - tmdbapi.py - 正在获取电视剧图片：236726...
【INFO】2023-10-20 01:34:12,470 - subscribe.py - 叠影狙击 (2023) S01 添加订阅成功
【INFO】2023-10-20 01:34:12,472 - chain - 发送消息：channel=None，title=叠影狙击 (2023) S01 已添加订阅, text=评分：10.0，来自用户：豆瓣想看，userid=None

_No response_

**Comment by jxxghp** [comment]
日志发全一点

**Comment by c77187326** [comment]
> 日志发全一点

我在豆瓣点击完成已看  不再出现了，后面出现再发。
