### ISSUE TITLE
[Feature Request]: http(s)代理能不能增加用户认证，谢谢

### ISSUE THREAD

**Issue by kingcard1131** [jxxghp/MoviePilot#926]
### 当前程序版本

1.3.5-1

### 功能改进类型

主程序

### 功能改进

https代理能否增加用户认证，防止其他人用代理，谢谢

**Comment by Shurelol** [comment]
@kingcard1131 其他人是谁？

**Comment by kingcard1131** [comment]
> @kingcard1131 其他人是谁？
如果不增加认证，别人知道你的IP或者域名+端口（对公网开放的话）别人就可以使用你的代理了
不过目前的版本socks5是支持认证的

**Comment by Shurelol** [comment]
@kingcard1131 用本地代理

**Comment by ReddotCleaner** [comment]
http://user:password@192.168.1.1:7889    这里不就是有用户和密码的认证了吗

**Comment by kingcard1131** [comment]
> @kingcard1131 用本地代理

本地也需要验证

**Comment by kingcard1131** [comment]
> http://user:password@192.168.1.1:7889 这里不就是有用户和密码的认证了吗

看文档socks5是可以的，你这样官方没说，可以试一下。

**Comment by kingcard1131** [comment]
目前使用socks5代理可以加用户认证，关闭！
