### ISSUE TITLE
[错误报告]: 种子文件包含Sample会重复转移

### ISSUE THREAD

**Issue by yellowstrong** [jxxghp/MoviePilot#928]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.3.5

### 问题类型

主程序运行问题

### 问题描述

如题，有个别种子文件中，除了电影主文件意外，会包含一个Sample文件夹，其中也有一小段影片，非正片，类似简介一样的，这种样片也会进行转移。
<img width="1156" alt="iShot_2023-10-19_23 31 42" src="https://github.com/jxxghp/MoviePilot/assets/34505611/73f24973-58d4-4217-b4a1-e977dd218142">

**Comment by Shurelol** [comment]
@yellowstrong 转移黑名单
