### ISSUE TITLE
[错误报告]: 插件在重启后变乱/复原

### ISSUE THREAD

**Issue by rotent** [jxxghp/MoviePilot#931]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.5-1

### 问题类型

插件问题

### 问题描述

目前使用5个插件，如图
![fb823ff6f9fd89040a205f0736dcfb1](https://github.com/jxxghp/MoviePilot/assets/93746829/bfe19c26-f908-4e6e-9882-1af00d92ec83)
![e5c0e0ee7cead6741b37dac17690549](https://github.com/jxxghp/MoviePilot/assets/93746829/056cda28-b113-4316-906f-9e350a9c33cd)
mp重启后如图，iyuu配置没了，自动转移做种插件没了，并且多了个目录监控插件，其他三个插件正常
![976f806f034e044005b181f18c17577](https://github.com/jxxghp/MoviePilot/assets/93746829/ced2d52f-9228-411d-acd9-f6f97ee4d08f)
![698785fa07b426f03062161ade00420](https://github.com/jxxghp/MoviePilot/assets/93746829/842ff8d5-f8f3-44c7-986a-e9e9399639b2)

**Comment by thsrite** [comment]
重启了几次。
重启第一次掉了认证 插件没了
重启第二次认证成功 插件回来了？

**Comment by rotent** [comment]
> 重启了几次。 重启第一次掉了认证 插件没了 重启第二次认证成功 插件回来了？

就重启一次，刚刚尝试了重启第二次插件并没有回来，还是如图三一样（我第二次重启之前并没有将插件改回图一那样）

**Comment by Nothend** [comment]
同样的问题，我是自动更新插件没有了，重新安装了一下

**Comment by hh0610** [comment]
我是装的插件重启只剩下签到插件

**Comment by HAN915** [comment]
一样有这个问题，重启以后插件没了

**Comment by rotent** [comment]
1.3.6正常了
