### ISSUE TITLE
种子识别错误

### ISSUE THREAD

**Issue by AboutCXJ** [jxxghp/MoviePilot#934]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.351

### 问题类型

主程序运行问题

### 问题
1893是分集的名字
![image](https://github.com/jxxghp/MoviePilot/assets/19811825/520a6619-7150-48b3-a5dc-6e4a4eaab625)

**Comment by jxxghp** [comment]
种子命名问题，无法解决。
