### ISSUE TITLE
[Feature Request]: 系统更新插件能否根据当前版本是否一致再通知？

### ISSUE THREAD

**Issue by Nothend** [jxxghp/MoviePilot#935]
### 当前程序版本

1.3.5-1

### 功能改进类型

插件

### 功能改进

更新插件，在已经是最新版本的情况下，依旧会发通知。是否可以判断当前版本小于最新版本的情况下，再推送通知？

**Comment by thsrite** [comment]
下个版本修复了，或者更新dev代码

**Comment by thsrite** [comment]
#925

**Comment by Nothend** [comment]
> 下个版本修复了，或者更新dev代码

辛苦了，感谢！

**Comment by whosneo** [comment]
@thsrite 目前看到插件通知的更新发布时间为 UTC 时间，可否让插件以当前系统时区显示更新发布时间呢？
