### ISSUE TITLE
[错误报告]: 部分媒体搜索不到tmdb词条

### ISSUE THREAD

**Issue by LiXianSebastian** [jxxghp/MoviePilot#937]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.5-1

### 问题类型

主程序运行问题

### 问题描述

部分媒体在tmdb和豆瓣存在词条,比如深喉(1972),但使用moviepilot搜素不到此电影词条
同时,在深喉2(1974)的词条界面,点击女主角,显示女主角参演的其他电影中存在深喉(1972).

**Comment by cng10001** [comment]
不支持成人内容，tmdb上成人内容默认也是关闭的，应该是你此前自行设置开启的

**Comment by LiXianSebastian** [comment]
> 不支持成人内容，tmdb上成人内容默认也是关闭的，应该是你此前自行设置开启的

好的,不过tmdb不用登陆就能搜到成人内容
