### ISSUE TITLE
synology chat机器人没有对任何人可见

### ISSUE THREAD

**Issue by HAN915** [jxxghp/MoviePilot#941]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.5-1

### 问题类型

其他问题

### 问题描述

配置了synology chat，moviepilot运行时，收不到消息推送，日志中显示机器人没有对任何人可见，是我缺了什么设置吗，还是chat不好用了

**Comment by jxxghp** [comment]
要先在chat中添加机器人，跟机器人聊天。

**Comment by leaguetao** [comment]
> > 要先在chat中添加机器人，跟机器人聊天。
> 
> 我也是这问题，机器人已经添加了，在nt时候正常使用的，mp现在就不行

我也是一样 好尴尬~
