### ISSUE TITLE
[错误报告]: 普通用户权限问题

### ISSUE THREAD

**Issue by AboutCXJ** [jxxghp/MoviePilot#947]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

普通用户可通过 仪表板-最近入库-查看详情，进入到历史记录，这原本应该是没权限的
<img width="1413" alt="截屏2023-10-21 21 21 29" src="https://github.com/jxxghp/MoviePilot/assets/19811825/28735b4c-a641-4322-ba1c-e14f3433d2a5">

**Comment by jxxghp** [comment]
https://github.com/jxxghp/MoviePilot-Frontend/commit/2855bf812bd15f0045c70719c2dd911183ee2e5e
