### ISSUE TITLE
[Feature Request]: 请求缓存机制的优化

### ISSUE THREAD

**Issue by amtoaer** [jxxghp/MoviePilot#951]
### 当前程序版本

1.3.6

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

看了下现有的使用 `lru_cache` 装饰器的方法，基本上是把异常捕获然后返回了 `None`，这意味着各种由于网络波动导致请求失败的情况都会被缓存下来，修复网络问题后也无法继续重试。
虽然 IM 端有 `clear_cache` 的命令，但我认为这是缓存机制本身的问题（即错误的请求不应该被缓存），不应依赖用户手动清除缓存。

### 参考资料

1. 在函数内部抛出异常，错误将不会被缓存：
![image](https://github.com/jxxghp/MoviePilot/assets/32017007/2427990d-5b1e-428e-a4da-25006ad76a76)
2. 在函数内部捕获后返回 None，错误将被缓存：
![image](https://github.com/jxxghp/MoviePilot/assets/32017007/427c12b6-e0c1-4bbb-b951-22a153a0a2c1)

**Comment by yellowstrong** [comment]
确实存在这个问题，我还想着这几天复现一下提issue呢，这个地方确实会把请求失败的也缓存下来，造成短时间内无法搜索

**Comment by cend1s** [comment]
怎么清理缓存，我现在就是这个状况，之前网络错误的时候缓存的TMDB数据，现在TMDB网络恢复了，这个电视剧是“未识别到TMDB媒体信息”，TMDB网站，NT上查询都可以找到。

**Comment by amtoaer** [comment]
@cend1s 使用 clear_cache 命令。
![Screenshot_2023-10-23-17-05-17-668_org telegram messenger-edit](https://github.com/jxxghp/MoviePilot/assets/32017007/b4b7c43f-fd92-441d-a07c-f681addab611)

**Comment by Whichbfj28** [comment]
难怪我的经常无法搜索!
