### ISSUE TITLE
文件同步删除插件--未获取到可删除数据

### ISSUE THREAD

**Issue by lhlxx2010** [jxxghp/MoviePilot#968]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

emby配置好了Scripter-X，看日志也是通知到了MV了，但是MV中总是显示未获取到可删除数据，不知道为何。大佬们求解。
![fddcc1c5b7be9133a4befe89280c77e](https://github.com/jxxghp/MoviePilot/assets/74414383/71c2dc4a-bdcd-493e-874b-1dbd8d1e3b02)
![image](https://github.com/jxxghp/MoviePilot/assets/74414383/c0f0a88e-5bc8-49f3-854d-f7454927f3e1)

**Comment by thsrite** [comment]
同步删除只能处理mp入库的记录，前提是历史记录中有这个媒体的记录
另外
插件的媒体库映射填了吗？填对了吗？

自己找找原因吧，程序没问题

**Comment by lhlxx2010** [comment]
> 同步删除只能处理mp入库的记录，前提是历史记录中有这个媒体的记录 另外 插件的媒体库映射填了吗？填对了吗？
> 
> 自己找找原因吧，程序没问题

历史记录中是有的，能麻烦问一下媒体库的映射填法吗？我目前写的是emby路径：mv路径，确实没找到地方查这部分的写法。谢谢！

**Comment by thsrite** [comment]
emby：/data/series/国产剧/狂飙 (2023)/Season 1/狂飙 - S01E04 - 第4集.mp4
mp： /mnt/link/series/国产剧/狂飙 (2023)/Season 1/狂飙 - S01E38 - 第38集.mp4
路径映射：/data:/mnt/link

issue关了吧

**Comment by lhlxx2010** [comment]
> emby：/data/series/国产剧/狂飙 (2023)/Season 1/狂飙 - S01E04 - 第4集.mp4 mp： /mnt/link/series/国产剧/狂飙 (2023)/Season 1/狂飙 - S01E38 - 第38集.mp4 路径映射：/data:/mnt/link
> 
> issue关了吧

谢谢大佬！我先试一下
