### ISSUE TITLE
[错误报告]: 名称识别通过，但是订阅中仍然显示标题不匹配

### ISSUE THREAD

**Issue by JamesYuuu** [jxxghp/MoviePilot#973]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.6

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/95520900/429cf321-ef38-4d1e-ba3b-1112c7bc2ae5)
![image](https://github.com/jxxghp/MoviePilot/assets/95520900/025122a4-c651-49d6-9e31-5f30b4154c76)
![image](https://github.com/jxxghp/MoviePilot/assets/95520900/b657afe1-fba5-4da0-aacf-714a62789d5d)

订阅搜索的时候，显示标题不匹配，然后我通过修改自定义识别词矫正匹配，且通过了名称识别测试，再次使用订阅搜索，仍然显示标题不匹配，请问是什么原因？

**Comment by Shurelol** [comment]
@JamesYuuu 清除缓存

**Comment by cng10001** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/115156545/3b2db519-7f1c-4f8a-833c-6709dc5e3eaa)
一样，实际不能订阅，我感觉是16bit识别的原因，
大家可以实测下

**Comment by jxxghp** [comment]
16bit是关键字，无法解决。自定认识别词改吧。

**Comment by cng10001** [comment]
@JamesYuuu 额
群里问了，有人说能识别，这个片子在名称识别测试里不用自定义识别词也能正常识别，而且我看了是观众的订阅，我看你也是观众，但是同样显示显示标题不匹配，奇奇怪怪的。
作者所说自定义识别词不知道什么思路，因为tmdb上标题都有16bit字符，绕不开啊。
所以我觉得只能自定义订阅插件了。

**Comment by Shurelol** [comment]
@cng10001

**Comment by Shurelol** [comment]
@cng10001 翻译，别名里多找，总有能绕开的，比如希伯来语的

**Comment by Shurelol** [comment]
![Screenshot_20231004_160903_Chrome.jpg](https://github.com/jxxghp/MoviePilot/assets/16237201/4dcdc0ba-cd1a-41de-91e1-d016a2f3200f)

**Comment by Shurelol** [comment]
@JamesYuuu 包括有同名同年的情况，别名或者翻译里多找找有特别的替换下就行
