### ISSUE TITLE
[错误报告]: 使用NFS存储作为Docker Volume给MP使用，硬链接显示成功，但是实际使用了2倍存储空间

### ISSUE THREAD

**Issue by OpsDarren** [jxxghp/MoviePilot#981]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

1.3.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

目前我的架构是这样
1、小主机上安装Linux Docker
2、群晖上共享文件夹Video通过NFS挂载给Docker Volume，MP和Transmission都是去使用这个Docker Volume
```
docker volume create --driver local \
  --opt type=nfs \
  --opt o=addr=<NAS_IP>,rw \
  --opt device=:/volume1/video \
  nas-video
```
3、创建MP的时候，存储挂载是`--mount "source=nas-video,target=/video"`，默认转移方式硬链接`-e "TRANSFER_TYPE=link"`
4、Transmission下我的参数是这样的
```
docker run -d \
  --network macvlan \
  --ip=<TR_IP> \
  --name=transmission \
  -e "TRANSMISSION_WEB_HOME=/config/web" \
  -v /etc/localtime:/etc/localtime:ro \
  -v /docker/transmission/config:/config \
  -v /docker/transmission/watch:/watch \
  --mount "source=nas-video,target=/video" \
  --restart always \
  linuxserver/transmission:4.0.4
```
5、MP下我的参数是这样的
```
docker run -d \
  --network macvlan \
  --ip=<MP_IP> \
  --name moviepilot \
  --hostname moviepilot \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -v /docker/moviepilot/config:/config \
  --mount "source=nas-video,target=/video" \
  -e "DOWNLOAD_PATH=/video/RAW/" \
  -e "DOWNLOAD_MOVIE_PATH=/video/RAW/Movie/" \
  -e "DOWNLOAD_TV_PATH=/video/RAW/TV/" \
  -e "DOWNLOAD_ANIME_PATH=/video/RAW/Anime/" \
  -e "DOWNLOAD_CATEGORY=false" \
  -e "LIBRARY_PATH=/video/Metadata/" \
  -e "LIBRARY_MOVIE_NAME=Movie" \
  -e "LIBRARY_TV_NAME=TV" \
  -e "LIBRARY_ANIME_NAME=Anime" \
  -e "LIBRARY_CATEGORY=false" \
  -e "TRANSFER_TYPE=link" \
  -e "DOWNLOADER=transmission" \
  -e "TR_HOST=<TR_IP>:9091" \
  -e "TR_USER=admin" \
  -e "TR_PASSWORD=********" \
  -e "DOWNLOADER_MONITOR=true" \
  jxxghp/moviepilot:1.3.7
```

我目前遇到的情况如下，在MP中刮削后，历史记录转移方式确实是显示“硬链接”，但是实际在群晖中，刮削后文件占据群晖的存储空间是跟原始文件一样大的，相当于变成了复制，我在群晖里，video是共享文件夹层级，Docker内，源文件目录是/video/RAW/，转移目录是/video/Metadata/，请问这样的目录挂载，在MP内也会识别成跨盘吗？

**Comment by 757321061** [comment]
建议搜一下 这个有人提过

**Comment by OpsDarren** [comment]
> 建议搜一下 这个有人提过

仔细搜了下发现确实是有，抱歉是我搜索没搜全面，这个issue关闭了，有同样问题的朋友参考下方链接

https://github.com/jxxghp/MoviePilot/issues/735

**Comment by jxxghp** [comment]
NFS共享，还指望能硬链接？物理上就不可行。

**Comment by OpsDarren** [comment]
> NFS共享，还指望能硬链接？物理上就不可行。

原来如此，谢谢大大解惑
