### ISSUE TITLE
[错误报告]: 更新到1.3.7后部分插件消失

### ISSUE THREAD

**Issue by RSG2019** [jxxghp/MoviePilot#989]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

V1.3.7

### 运行环境

Docker

### 问题类型

主程序运行问题

### 问题描述

使用docker compose pull 拉取最新容器并更新后 进入web ui 插件内的自定义插件和和一些插件都不见了。

**Comment by jxxghp** [comment]
掉认证了吧
