### ISSUE TITLE
[Feature Request]: 能否增加使用英文来重命名文件和文件夹

### ISSUE THREAD

**Issue by RSG2019** [jxxghp/MoviePilot#990]
### 当前程序版本

V1.3.7

### 运行环境

Docker

### 功能改进类型

主程序

### 功能改进

在使用MoviePilot下载剧集和电影的时候，程序会自动用中文来重命名文件，但是中文的文件在plex 或者emby 用官方自带的OpenSubtitles 来搜索字幕的时候plex或者emby 会自动填充文件名来搜索，但是OpenSubtitles对中文的友好度特别不好，在同一个影视作品中，中文搜索就无字幕结果但是英文搜索就可以获取到字幕，希望作者能考虑下。

**Comment by mjsoftking** [comment]
![image](https://github.com/jxxghp/MoviePilot/assets/23021469/c86b97ba-80ed-42ed-8ead-265156809da5)
应该是这个字段吧

**Comment by sjtuross** [comment]
original_title可能是各个国家，比如韩剧就是韩语了，希望有原来nt的那个en_title

**Comment by RSG2019** [comment]
> original_title可能是各个国家，比如韩剧就是韩语了，希望有原来nt的那个en_title

我也想 但是作者好像并没有添加的意思
