### ISSUE TITLE
[错误报告]: 请求IYUU失败，状态码：403，返回信息：非法请求：用户未绑定合作站点账号

### ISSUE THREAD

**Issue by 318182456** [jxxghp/MoviePilot#998]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/jxxghp/MoviePilot/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/jxxghp/MoviePilot/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经 [Telegram频道](https://t.me/moviepilot_channel) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

v1.3.7

### 运行环境

Docker

### 问题类型

插件问题

### 问题描述

![image](https://github.com/jxxghp/MoviePilot/assets/33387786/661b4d9d-396f-4236-a929-d8b1a7664ae3)
站点列表中是有hddolby的，但是一直提示【非法请求：用户未绑定合作站点账号！】

### 发生问题时系统日志和配置文件

```bash
【INFO】2023-10-28 15:05:07,194 - iyuuautoseed - 开始辅种任务 ...
【INFO】2023-10-28 15:05:07,194 - iyuuautoseed - 开始扫描下载器 qbittorrent ...
【INFO】2023-10-28 15:05:07,252 - iyuuautoseed - 下载器 qbittorrent 已完成种子数：217
【INFO】2023-10-28 15:05:07,253 - iyuuautoseed - 总共需要辅种的种子数：217
【INFO】2023-10-28 15:05:07,253 - iyuuautoseed - 下载器 qbittorrent 开始查询辅种，数量：200 ...
【WARNING】2023-10-28 15:05:07,465 - iyuuautoseed - 当前种子列表没有可辅种的站点：请求IYUU失败，状态码：403，返回信息：非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/
【INFO】2023-10-28 15:05:07,466 - iyuuautoseed - 下载器 qbittorrent 开始查询辅种，数量：17 ...
【WARNING】2023-10-28 15:05:07,666 - iyuuautoseed - 当前种子列表没有可辅种的站点：请求IYUU失败，状态码：403，返回信息：非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/
【INFO】2023-10-28 15:05:07,969 - iyuuautoseed - 辅种任务执行完成
```

**Comment by AboutCXJ** [comment]
用过iyuu官方镜像吗？要在iyuu绑定认证站

**Comment by 318182456** [comment]
之前nt用过iyuu换到这个就不好使了
